(function () {
    "use strict";
    const guides = {
        microbes: [
            ["Classification and cellular organization", "Classification groups organisms using shared characters and evolutionary relationships. A species name has a genus and specific epithet; the genus is capitalized and both are conventionally italicized. Historical two- and five-kingdom schemes remain useful examination topics but are not interchangeable with modern domain-based phylogeny. Bacteria are prokaryotes with no membrane-bound nucleus, although they possess organized genetic material, ribosomes and cellular machinery."],
            ["Bacteria and viruses", "Bacterial peptidoglycan is structurally different from fungal chitin and plant cellulose. Gram staining reflects envelope structure rather than whether a bacterium is beneficial or pathogenic. Conjugation, transformation and transduction transfer genetic information by different mechanisms. Viruses depend on host cells for replication; their genomes may be DNA or RNA. Viroids are small infectious RNAs without a protein coat, while prions involve infectious protein conformations. The old mesosome-as-respiratory-organelle model reflects preparation artifacts and should not be treated as a modern universal bacterial structure."]
        ],
        fungi: [
            ["Fungal organization", "Fungi are heterotrophic eukaryotes that absorb nutrients after extracellular digestion. Most have chitin-containing cell walls and a body of hyphae forming a mycelium; yeasts are mainly unicellular. Septate and coenocytic organization, reproductive spores and life-cycle stages distinguish major groups. A fruiting body is not the entire fungus."],
            ["Associations and uses", "Lichens associate a fungal partner with a photosynthetic alga or cyanobacterium. Mycorrhiza is an association between fungi and roots that can improve mineral and water acquisition. Fungi are decomposers, pathogens and sources of foods, fermentation products and drugs. Penicillium, Saccharomyces, Rhizopus and common mushrooms have distinct reproductive structures and uses; their names are not interchangeable simply because they are fungi."]
        ],
        algae: [
            ["Major groups", "Algae include several evolutionary lineages rather than one simple natural plant group. Green algae typically contain chlorophyll a and b and store starch; brown algae have fucoxanthin and often store laminarin and mannitol; red algae contain phycobilin pigments and store floridean starch. Habitat, pigment, reserve material and cell-wall composition are useful comparison features."],
            ["Representative forms", "Chlamydomonas is commonly a motile unicell with two flagella; Spirogyra is a filamentous green alga with spiral chloroplasts. Spirogyra conjugation transfers cell contents through a conjugation connection and produces a zygospore. Diatoms have silica-rich walls. Isogamy, anisogamy and oogamy describe gamete similarity and differentiation, not the number of chromosomes in every life-cycle stage."]
        ],
        bryophytes: [
            ["Dominant generation", "Bryophytes are nonvascular land plants whose conspicuous generation is the haploid gametophyte. They produce gametes in antheridia and archegonia, and fertilization generally requires water for motile sperm. Rhizoids anchor the body but are not true vascular roots. The diploid sporophyte remains attached to and nutritionally dependent on the gametophyte to varying degrees."],
            ["Moss and liverwort cycles", "In a moss such as Funaria, a spore develops into a protonema and then a leafy gametophyte. The sporophyte includes foot, seta and capsule. Meiosis in the capsule produces haploid spores. In Marchantia, gemmae provide vegetative reproduction. Calyptra is derived from gametophytic archegonial tissue and is haploid, unlike the enclosed sporophyte capsule."]
        ],
        pteridophytes: [
            ["Vascular spore plants", "Pteridophytes have vascular tissue and a dominant independent sporophyte with true organs. They reproduce through spores rather than seeds. The gametophyte is often a small prothallus, and motile sperm still generally require water. Fern sori are groups of sporangia, not gametangia."],
            ["Homosporous and heterosporous", "Homosporous forms produce one spore category; heterosporous forms produce microspores and megaspores that develop into male and female gametophytes. Selaginella is a familiar heterosporous example. Heterospory is an important step in the evolution of seed habit but does not by itself make a plant seed-bearing. Equisetum, Lycopodium and common ferns differ in stem, leaf and sporangium organization."]
        ],
        gymnosperms: [
            ["Seeds without an enclosing ovary", "Gymnosperm ovules and seeds are not enclosed within a true ovary and fruit. Their dominant body is a vascular sporophyte, while gametophytes are reduced. Pollen transfers the male gametophyte and removes the ordinary need for free external water for sperm delivery, although motile sperm persist in some lineages such as Cycas."],
            ["Cycas, Pinus and life cycles", "Cycas is usually dioecious and has coralloid roots associated with nitrogen-fixing cyanobacteria. Pinus typically has male and female cones on the same plant and often mycorrhizal roots. Gymnosperm nutritive female-gametophyte tissue is haploid and forms before fertilization; it differs from the usually triploid angiosperm endosperm. Haploid and diploid stages both undergo mitosis in alternation of generations, whereas meiosis reduces chromosome number."]
        ],
        "flowering-plants": [
            ["Vegetative morphology", "Roots commonly arise from the radicle, stems from the plumule and leaves laterally from shoot meristems. Modified storage, support and climbing organs must be identified from their origin and anatomy, not appearance alone. Potato is a stem tuber and sweet potato a storage root. Phyllotaxy is leaf arrangement; venation is the vein pattern. Simple and compound leaves are distinguished by whether the lamina is divided into separate leaflets."],
            ["Flowers, fruits and families", "A flower has reproductive organs and often sepals and petals. Ovary position, floral symmetry, aestivation, placentation and stamen arrangement help identify families. A fruit usually develops from an ovary; accessory tissues may also contribute. Brassicaceae commonly has tetradynamous stamens, Fabaceae commonly a legume fruit and marginal placentation, and Solanaceae commonly epipetalous stamens. Individual family traits have exceptions and should be interpreted as a combination."]
        ],
        "plant-anatomy": [
            ["Tissues and growth", "Meristems contain dividing cells. Apical meristems extend roots and shoots, while lateral meristems increase girth in plants with secondary growth. Parenchyma usually has living thin-walled cells; collenchyma provides flexible support with uneven primary-wall thickening; sclerenchyma commonly has lignified thick secondary walls. Mature conducting xylem elements are usually dead, while sieve-tube elements are living but depend strongly on companion cells."],
            ["Bundles and organ sections", "Xylem carries water and minerals and phloem distributes organic solutes. A conjoint bundle contains both tissues together; radial arrangement alternates xylem and phloem as in typical roots. Open bundles have vascular cambium, while closed bundles lack it. Typical dicot stems have a ring of bundles and monocot stems scattered closed bundles. Roots are commonly exarch and stems endarch. These are diagnostic patterns, not exception-free definitions of every plant."],
            ["Secondary growth", "Vascular cambium forms secondary xylem inward and secondary phloem outward. Cork cambium contributes to the periderm. Annual-ring visibility depends on seasonal growth differences; heartwood and sapwood describe functional and structural zones rather than separate tissue origins. Root lateral branches commonly originate from the pericycle, while shoot branches arise from buds."]
        ],
        "plant-transport": [
            ["Membrane transport and water potential", "Diffusion follows a chemical-potential gradient. Osmosis is net water movement across a selectively permeable membrane toward lower water potential. In a simple cell model, $\\Psi_w=\\Psi_s+\\Psi_p$. Solute potential is nonpositive relative to pure water; positive turgor pressure can offset it. Plasmolysis occurs when a cell loses water sufficiently for the protoplast to withdraw from the wall."],
            ["Long-distance transport", "Transpiration from leaves creates tension transmitted through cohesive xylem water columns. Root pressure can contribute under some conditions but does not generally explain ascent in tall trees. Phloem translocation moves from sources to sinks through pressure-flow processes; source and sink roles change with development. Individual sieve-tube pathways may flow in different directions, which is distinct from simultaneous opposite flow in one tube."],
            ["Stomata and guttation", "Guard-cell turgor regulates stomatal aperture. Light, internal CO2, water status and hormones influence opening and closure. Transpiration loses water vapour, whereas guttation exudes liquid containing dissolved substances through hydathodes. Dew is condensed atmospheric water and is not guttation. The source's fixed universal rates or temperature optima should be read as context-dependent examples."]
        ],
        photosynthesis: [
            ["Light reactions", "Light-harvesting pigments transfer excitation to reaction centres. PSII uses a P680 reaction centre and PSI P700. In linear electron flow, water supplies electrons, oxygen is released and electrons pass through carriers to reduce NADP+. A proton gradient drives ATP synthesis. The oxygen released in photosynthesis originates from water, not directly from CO2."],
            ["Carbon fixation", "In the Calvin cycle, Rubisco fixes CO2 to RuBP, producing 3-phosphoglycerate after an unstable intermediate splits. ATP and NADPH support reduction and RuBP regeneration. C4 plants initially fix bicarbonate through PEP carboxylase into a four-carbon product, then concentrate CO2 around Rubisco. Kranz anatomy and dimorphic chloroplasts are common C4 features. CAM separates initial fixation and the Calvin cycle mainly in time rather than the C4 spatial arrangement."],
            ["Limiting factors", "Light, CO2, temperature and water can limit net photosynthesis. Photorespiration begins with Rubisco oxygenation and can reduce carbon gain, especially under conditions favoring low internal CO2. Respiration still occurs in illuminated plants, so gross photosynthesis and net gas exchange are not identical."]
        ],
        "plant-respiration": [
            ["Pathway sequence", "Glycolysis in the cytosol converts glucose into two pyruvates, with net two ATP and two NADH per glucose in the standard pathway. Under aerobic conditions, pyruvate oxidation forms acetyl-CoA, and the citric-acid cycle produces reduced carriers and CO2. In eukaryotes these reactions are associated with mitochondria; glycolysis is not mitochondrial."],
            ["ATP and fermentation", "Electrons from NADH and FADH2 pass through a respiratory chain that helps establish a proton gradient for ATP synthase. Oxygen is the terminal acceptor in aerobic respiration. Fermentation regenerates NAD+ and does not add the large oxidative-phosphorylation yield. Total ATP per glucose is not one universal 36-or-38 figure: coupling, shuttles and conditions matter. Respiratory quotient is CO2 released divided by O2 consumed under specified conditions."]
        ],
        "cell-biology": [
            ["Compartments and membranes", "The plasma membrane is a dynamic lipid bilayer with embedded proteins, selective transport and signaling functions. The nucleus contains most eukaryotic DNA; mitochondria and chloroplasts contain additional genomes. Ribosomes synthesize proteins. Rough ER participates in synthesis and processing of many secreted and membrane proteins, while smooth ER has important lipid and detoxification functions."],
            ["Organelles and traffic", "The Golgi modifies, sorts and packages materials. Lysosomes support intracellular degradation, peroxisomes perform oxidative reactions including peroxide metabolism, and mitochondria couple respiration to ATP generation. Plant vacuoles contribute storage, degradation and turgor. Cell-wall cellulose, fungal chitin and bacterial peptidoglycan are chemically different. A chloroplast and a mitochondrion both have internal membranes but carry out distinct energy transformations."],
            ["Cell cycle", "DNA replication occurs in S phase, not simply whenever a chromosome becomes visible. Mitosis separates replicated chromosomes and normally preserves chromosome number. Meiosis includes one replication followed by two divisions, with homolog separation in meiosis I and sister-chromatid separation in meiosis II. Chromosome number and DNA amount must be tracked separately."]
        ],
        "plant-reproduction": [
            ["Gametophyte formation", "Anthers contain microsporangia where microspore mother cells undergo meiosis. A pollen grain is a male gametophyte, not itself a sperm cell. A typical ovule contains integuments and nucellus surrounding a female gametophyte. In the common Polygonum pattern, the mature embryo sac is seven-celled and eight-nucleate, including an egg apparatus, antipodals and a central cell with two polar nuclei."],
            ["Pollination and fertilization", "Pollination transfers pollen to a receptive stigma and is distinct from fertilization. The pollen tube delivers two male gametes. One fuses with the egg to form the diploid zygote; the other typically fuses with two polar nuclei to form a triploid primary endosperm nucleus. Thus double fertilization combines syngamy with triple fusion. After fertilization, ovule generally becomes seed and ovary becomes fruit, with exceptions such as parthenocarpy and apomixis."]
        ],
        genetics: [
            ["Mendelian crosses", "Alleles are alternative forms at a locus; a diploid individual normally carries two copies at an autosomal locus. Aa x Aa gives a genotype ratio 1:2:1 and, only with complete dominance, a phenotype ratio 3:1. A test cross uses a homozygous recessive partner. A 9:3:3:1 phenotype ratio requires the appropriate dihybrid cross, independent assortment and dominance assumptions; it is not a genotype ratio."],
            ["Probability and interactions", "For independent loci, multiply probabilities: in AaBbCc x AaBbCc, P(AaBBCc) is 1/2 x 1/4 x 1/2 = 1/16. A single parent with n independently assorting heterozygous loci can produce 2^n gamete types. Linkage changes the simple independence assumption. Pleiotropy is one gene affecting several traits; polygenic inheritance is several loci contributing to a trait; epistasis is interaction between loci, often involving masking."],
            ["DNA, RNA and expression", "DNA replication is semiconservative and new strands extend 5' to 3'. Helicase unwinds the duplex, polymerases synthesize DNA and ligase seals nicks. Transcription makes RNA from DNA, translation reads mRNA on ribosomes, and reverse transcription makes DNA from RNA. A codon is a triplet; a cistron is a historical functional gene unit. Introns are removed from many primary RNA transcripts by splicing."],
            ["Chromosomes and inheritance", "Aneuploidy changes individual chromosome dosage; polyploidy changes complete sets. Classic examples include trisomy 21, 45,X and 47,XXY. Common red-green colour-vision deficiency and haemophilia A/B are X-linked recessive. An unaffected daughter of an affected father is normally a carrier in the simple model. Carrier trait must be distinguished from disease, especially when discussing the malaria association of HbAS."]
        ],
        biotechnology: [
            ["Recombinant DNA", "Restriction endonucleases recognize and cleave particular DNA sequences; ligases join DNA ends. A useful cloning vector has an origin of replication, selectable marker and suitable insertion sites. Plasmids and bacteriophages are different vector systems. PCR amplifies a selected DNA region through denaturation, primer annealing and polymerase extension, using a thermostable polymerase."],
            ["Culture and applications", "Plant tissue culture grows cells or tissues aseptically on a suitable medium. Totipotency is the capacity to regenerate a complete plant under appropriate conditions, not a guarantee that every cell will do so easily. Auxin-cytokinin balance influences organ formation in many culture systems. Microbes contribute antibiotics, enzymes, fermentation products and biofertilizers; the organism, product and process should be matched precisely."]
        ],
        ecology: [
            ["Levels and interactions", "An organism, population, community and ecosystem represent different levels of organization. An ecosystem includes abiotic surroundings as well as organisms. Habitat is where an organism lives; niche includes its ecological role and requirements. Mutualism, competition, predation, parasitism and commensalism are defined by the interaction's effects, which can vary with conditions."],
            ["Energy and nutrients", "Energy generally flows through trophic levels and is dissipated as heat, whereas matter cycles. The familiar 10% trophic-transfer rule is a rough teaching approximation, not a universal measured constant. Energy pyramids are upright for a defined flow interval; biomass and number pyramids can have different shapes. Primary productivity, decomposition and nutrient cycling connect living and nonliving components."],
            ["Conservation and pollution", "Conservation can occur in situ within habitats or ex situ outside them. Eutrophication is nutrient enrichment that can promote excessive production and subsequent oxygen depletion. Biomagnification concerns increasing concentration through trophic transfer, not merely accumulation within one organism. Population growth, carrying capacity, succession and species richness measure different ecological processes and should not be substituted for each other."]
        ],
        "plant-growth": [
            ["Growth regulators", "Auxins, gibberellins, cytokinins, abscisic acid and ethylene have overlapping, context-dependent roles. Auxin influences elongation and apical dominance, gibberellins can promote stem elongation and germination, and cytokinins promote cell division in suitable conditions. ABA is important in stress responses and dormancy; ethylene promotes ripening in climacteric fruits and participates in senescence and stress."],
            ["Development and movement", "Photoperiodism concerns the response to day-night duration, often with the uninterrupted dark period being critical. Vernalization is promotion of flowering by an appropriate cold treatment. Tropisms are directional growth responses, while nastic movements are not directed by stimulus direction. Epigeal germination raises cotyledons chiefly through hypocotyl elongation; hypogeal germination keeps them below ground, commonly with epicotyl elongation."]
        ],
        "plant-minerals": [
            ["Essential elements", "An essential element is required to complete the life cycle, has a specific role and cannot simply be replaced by another element. The standard current list for higher plants includes 17 essential elements, including nickel; older 16-element lists omit it. Macronutrients and micronutrients are distinguished by amount required, not importance. Carbon, hydrogen and oxygen are commonly obtained from CO2 and water."],
            ["Functions and deficiency", "Nitrogen is needed for amino acids and nucleotides, magnesium is part of chlorophyll, iron participates in electron-transfer proteins, and potassium contributes to osmotic and enzyme functions. Deficiency location depends partly on mobility: mobile-element symptoms often appear in older leaves first. Nitrogen fixation reduces atmospheric N2 to biologically useful reduced nitrogen; nitrification oxidizes ammonium, and denitrification returns nitrogen to gaseous forms."]
        ],
        biomolecules: [
            ["Molecular classes", "Carbohydrates, proteins, lipids and nucleic acids have different building blocks and roles. Polysaccharides link sugar residues, proteins amino acids and nucleic acids nucleotides. Lipids include fats, phospholipids and steroids and are not all polymers. A nucleotide contains base, sugar and phosphate; a nucleoside contains base and sugar only."],
            ["Enzymes and structure", "Enzymes lower activation energy without changing the reaction equilibrium constant. Substrate specificity depends on active-site structure and dynamics. Temperature and pH effects reflect both reaction kinetics and molecular stability. Competitive inhibitors often compete at the active site; increasing substrate can reduce their effect in the ideal competitive model. Protein denaturation changes higher-order structure and need not cleave the peptide backbone."]
        ],
        digestion: [
            ["Pathway and secretions", "Mechanical processing and enzymatic hydrolysis convert food into absorbable units. Salivary amylase begins starch digestion; gastric acid supports pepsin action and inhibits many microbes. Pancreatic and intestinal enzymes complete most digestion in the small intestine. Bile contains no digestive enzyme: bile salts support lipid emulsification and micellar transport."],
            ["Absorption", "Villi and microvilli enlarge absorptive area. Many sugars and amino acids enter portal blood, while absorbed long-chain lipids are reassembled and packaged into chylomicrons that enter lymph. Micelles and chylomicrons are different structures: micelles help deliver digestion products to the intestinal surface, and chylomicrons are assembled within enterocytes. The liver receives portal blood and performs metabolic, storage, synthetic and detoxification functions."]
        ],
        nutrition: [
            ["Vitamins", "A, D, E and K are fat-soluble; the B-group and C are water-soluble. Vitamin A supports visual pigment and epithelial functions, vitamin D calcium-phosphate homeostasis, vitamin K synthesis of several coagulation proteins, and vitamin C collagen-related hydroxylation. Deficiency syndromes must be distinguished from effects of excess intake."],
            ["Balanced requirements", "A balanced diet supplies energy, essential amino acids and fatty acids, micronutrients, water and appropriate fibre. Protein-energy malnutrition and a single-vitamin deficiency are different problems. Requirements vary with age, growth, pregnancy, disease and activity. The named nutrient associations in entrance-exam notes are not sufficient for diagnosing or treating a person."]
        ],
        "nervous-system": [
            ["Resting and action potentials", "A typical neuron rests near -70 mV, although values vary. Ion gradients are maintained by transporters including the Na+/K+-ATPase, which moves three sodium ions out and two potassium ions in per ATP. Potassium leak permeability strongly influences resting voltage. A typical axonal upstroke follows voltage-gated sodium entry; sodium inactivation and potassium efflux support repolarization."],
            ["Refractory period and myelin", "During absolute refractoriness, inactivated sodium channels prevent immediate refiring. During relative refractoriness, a stronger stimulus can fire recovered channels despite residual potassium conductance and hyperpolarization. The refractory region behind an impulse explains ordinary one-way propagation. Myelin instead speeds conduction by reducing leak and capacitance; action potentials regenerate at nodes of Ranvier."],
            ["Synaptic communication", "An arriving impulse opens presynaptic calcium channels. Calcium triggers vesicle fusion and neurotransmitter release into the cleft, followed by receptor binding on the next cell. Acetylcholine excites skeletal muscle at nicotinic neuromuscular receptors. GABA is a major mature-CNS inhibitory transmitter, not a universal direct muscle-relaxation transmitter. Dendrites and soma receive and integrate inputs; the initial segment near the axon hillock is a usual trigger zone."]
        ],
        endocrine: [
            ["Signaling and feedback", "Endocrine glands release hormones into internal fluids, while exocrine glands use ducts. Peptide hormones commonly act through membrane receptors; steroid and thyroid hormones often regulate gene expression through intracellular receptors. These are broad patterns with additional signaling mechanisms. Negative feedback limits many endocrine axes; positive feedback is a specific amplifying loop such as the preovulatory LH surge."],
            ["Major axes", "Hypothalamic releasing hormones regulate anterior pituitary secretion. The posterior pituitary releases ADH and oxytocin synthesized in hypothalamic neurons. Thyroid hormones influence metabolism, parathyroid hormone calcium balance, insulin and glucagon glucose regulation, and adrenal cortical hormones salt balance and stress metabolism. Adrenal medulla and cortex have different developmental origins and secretions."]
        ],
        circulation: [
            ["Double circulation", "Systemic circulation carries blood between the left heart and body, while pulmonary circulation carries blood between the right heart and lungs. Artery and vein are defined by direction relative to the heart, not oxygen content. Pulmonary arteries therefore carry relatively deoxygenated blood and pulmonary veins oxygenated blood. Valves promote one-way flow in response to pressure differences."],
            ["Cardiac cycle and control", "The sinoatrial node normally initiates the rhythm, followed by conduction through atria, AV node, bundle system and ventricles. Ventricular systole and diastole describe contraction and relaxation phases. S1 is associated mainly with AV-valve closure and S2 with semilunar-valve closure. Cardiac output equals heart rate times stroke volume; neither 72 beats/min nor 5 L/min is a fixed value for every healthy person."],
            ["Blood vessels", "Capillary structure supports exchange, while arterioles strongly influence resistance. Plasma proteins contribute osmotic balance, transport, immunity and coagulation. A portal system connects two capillary beds before returning to the heart: intestinal venous blood reaches liver sinusoids via the hepatic portal vein and leaves via hepatic veins."]
        ],
        "human-respiration": [
            ["Ventilation and exchange", "During quiet inspiration the diaphragm contracts and thoracic volume increases, lowering alveolar pressure below atmospheric pressure. Quiet expiration is mainly passive elastic recoil; forced expiration recruits additional muscles. Oxygen and carbon dioxide diffuse along partial-pressure gradients across the respiratory membrane."],
            ["Transport and regulation", "Most oxygen is transported bound to haemoglobin; most carbon dioxide is carried as bicarbonate. Increased CO2, acidity and temperature generally favor oxygen unloading from haemoglobin. The medullary respiratory network is regulated by chemical and other inputs; CO2-related changes are major normal ventilatory drivers. Tidal volume, residual volume and vital capacity are different measurements, and simple spirometry cannot directly measure residual volume."]
        ],
        "human-reproduction": [
            ["Gametogenesis", "Spermatogenesis occurs in seminiferous tubules and begins at puberty. Sertoli cells support developing germ cells and Leydig cells produce testosterone. Primary oocytes begin meiosis before birth and remain arrested until later development; the ovulated cell is usually a secondary oocyte arrested in metaphase II. One oogenic meiosis normally produces one large functional ovum and polar bodies, not four equal ova."],
            ["Cycles and fertilization", "FSH supports follicular development and LH participates in ovulation and luteinization. Estradiol promotes proliferative endometrial growth and progesterone supports the secretory phase. Fertilization commonly occurs in the ampullary region of the uterine tube; implantation occurs later in the endometrium. Placenta enables exchange and endocrine signaling, but maternal and fetal blood do not normally mix as one continuous circulation."],
            ["Reproductive health", "Contraceptive methods act through different mechanisms and differ in protection against sexually transmitted infections. Infertility investigations and assisted reproduction depend on the underlying cause. Developmental timing and menstrual phase lengths vary, so a memorized 28-day scheme is a model rather than a rule for every person."]
        ],
        excretion: [
            ["Nephron processing", "Glomerular filtration transfers water and small solutes into Bowman's space while normally retaining cells and most plasma proteins. Tubular reabsorption returns useful substances to blood; tubular secretion transfers selected substances from blood into the tubule. Filtration, reabsorption and secretion are different processes. Most filtered water and sodium are reabsorbed before final urine is formed."],
            ["Concentration and regulation", "The loop of Henle and associated vessels help establish and preserve the medullary gradient. ADH increases water permeability in the collecting system through aquaporin regulation. Aldosterone promotes sodium reabsorption and potassium secretion in appropriate distal nephron segments. Creatinine is a waste marker and should not be confused with creatine or phosphocreatine in muscle energy buffering."],
            ["Urinary tract", "Ureters carry urine from kidneys to the bladder. The bladder's transitional epithelium accommodates stretch, and neural control coordinates detrusor and sphincter activity. The external urethral sphincter has voluntary control. Fixed statements that a sphincter opens at exactly 501 or 1000 mL are not physiological universal thresholds. Urea, uric acid and ammonia have different solubility, toxicity and water requirements across animal groups."]
        ],
        senses: [
            ["Vision", "The cornea and lens focus light on the retina. Rods support dim-light vision, while cones support colour and high-acuity vision. Photoreceptor signals pass through retinal circuits toward ganglion-cell axons that form the optic nerve. Accommodation changes lens power. The optic disc lacks photoreceptors and is the blind spot; the foveal region has especially high cone density."],
            ["Hearing and balance", "Sound is transmitted through the tympanic membrane and middle-ear ossicles to the oval window, setting cochlear fluids and the basilar membrane in motion. Hair cells in the organ of Corti transduce mechanical displacement. Semicircular ducts detect angular acceleration, while utricle and saccule contribute linear-acceleration and gravity sensing. Endolymph and perilymph occupy different spaces and have different ionic compositions."]
        ],
        protozoa: [
            ["Diversity and movement", "The historical term protozoa groups diverse animal-like unicellular eukaryotes and is not one modern natural lineage. Amoeba forms pseudopodia, Paramecium uses cilia and Euglena commonly uses a flagellum. Contractile vacuoles help freshwater forms manage osmotic water entry. Feeding, movement and reproduction vary widely among the groups."],
            ["Representative processes", "Amoeboid phagocytosis encloses particles in a food vacuole. Paramecium has nuclear dimorphism: a macronucleus supports many day-to-day functions and a micronucleus participates in genetic exchange. Conjugation exchanges genetic material but is not itself the same as increasing cell number by fission. Parasitic forms have specialized transmission stages and should be matched to their specific disease and host."]
        ],
        plasmodium: [
            ["Hosts and infective stages", "Female Anopheles mosquitoes transmit human malaria by inoculating sporozoites. Sporozoites invade liver cells, followed by blood-stage merozoites that infect erythrocytes. Gametocytes taken up by a mosquito develop into gametes; fertilization and subsequent development occur in the mosquito. The mosquito is the definitive host because sexual reproduction occurs there."],
            ["Cycles and disease", "Asexual multiplication in human tissues is schizogony, while sporogony follows fertilization in the mosquito. Different Plasmodium species have different clinical and recurrence patterns. Fever periodicity reflects blood-stage cycles but is not perfectly regular in every infection. Hypnozoites are dormant liver stages associated especially with P. vivax and P. ovale, not every malaria species."]
        ],
        evolution: [
            ["Evidence and mechanisms", "Evolution is change in heritable population characteristics across generations. Homology reflects shared ancestry; analogy reflects similar function that can evolve independently. Fossils, anatomy, embryology and molecular sequences provide complementary evidence. Natural selection acts on heritable variation in reproductive success, while mutation, recombination, drift and gene flow also change population genetics."],
            ["Models and history", "Lamarck, Darwin and later geneticists proposed distinct mechanisms; historical theories should not be treated as interchangeable. Hardy-Weinberg proportions follow a model with assumptions including random mating and no net evolutionary forces at the locus. For two alleles, $p+q=1$ and genotype frequencies are $p^2+2pq+q^2=1$. Speciation concerns reproductive and evolutionary divergence, not simply one individual adapting during its lifetime."],
            ["Origin of life", "Abiogenesis hypotheses concern the origin of living systems from nonliving chemistry on early Earth. Experimental synthesis of organic molecules does not demonstrate creation of a complete cell. Biogenesis describes observed reproduction from existing life under present conditions. The fossil record and molecular phylogeny support branching evolution rather than a ladder in which living species are all direct ancestors of humans."]
        ],
        "animal-diversity": [
            ["Body plans", "Symmetry, tissue layers, coelom, segmentation, digestive tract and embryonic development help compare animal groups. Sponges lack true tissues; cnidarians have cnidocytes; flatworms are generally dorsoventrally flattened; nematodes have a pseudocoelom and cuticle; annelids show segmented coelomic organization. Arthropods have jointed appendages and a chitinous exoskeleton; molluscs typically have a mantle and muscular foot."],
            ["Chordates and vertebrates", "Chordates share a notochord, dorsal hollow nerve cord, pharyngeal slits and post-anal tail at some developmental stage. Vertebrate classes differ in skin, respiration, circulation, reproduction and temperature regulation. Echinoderms have a water-vascular system and bilaterally symmetric larvae despite common adult radial symmetry. Common names can mislead: a jellyfish is not a fish and a starfish is an echinoderm."],
            ["Interpreting exceptions", "A character should be checked for its life stage and taxon. Amphibian larvae and adults can differ in respiratory organs; mammalian egg-laying and marsupial reproduction differ from placental patterns. Statements like 'all mammals have seven neck vertebrae' or 'all reptiles have identical heart structure' have known exceptions. Classification tables are best used as comparisons, not collections of unqualified absolutes."]
        ],
        earthworm: [
            ["Body organization", "The commonly taught Pheretima/Metaphire posthuma model is a segmented, bilaterally symmetric annelid. The clitellum occupies segments 14-16 in this model and secretes material involved in cocoon formation. Setae contribute anchorage during locomotion and are absent from the first and last segments and clitellar region. Skin must remain suitably moist for cutaneous gas exchange."],
            ["Systems and reproduction", "A complete digestive tract includes specialized regions such as gizzard and intestine; typhlosole increases absorptive area. Circulation is closed and nephridia support excretion and osmoregulation. Earthworms are hermaphrodites but normally cross-fertilize. Spermathecae store received sperm, and a cocoon supports subsequent development. Segment numbers vary among earthworm taxa, so the named model must be kept explicit."]
        ],
        frog: [
            ["Amphibian organization", "A typical adult frog is an ectothermic amphibian with moist glandular skin, lungs and cutaneous respiration. A three-chambered heart has two atria and one ventricle, with circulation patterns that reduce but do not abolish mixing. Larval and adult morphology and feeding differ markedly. The vertebrate body plan and specialized amphibian adaptations should be separated."],
            ["Source cautions", "The scanned 'absent in frog' list contains overgeneralizations. Frogs do have Sertoli cells, and amphibian eyes can accommodate by moving the lens. A mammalian-style diaphragm is absent, but this does not imply every nonmammalian ventilatory structure is absent. A columella transmits middle-ear vibrations; it is incorrect to say there are no ear ossicles and simultaneously describe one. Interpret species-specific nerve, kidney and reproductive anatomy using the named model, not the label 'exclusive to mammals'."]
        ],
        "animal-tissues": [
            ["Four major tissue classes", "Epithelial tissues form coverings, linings and glands. Connective tissues have cells within an extracellular matrix and include bone, cartilage, blood and fibrous tissues. Muscle specializes in contraction, while nervous tissue supports signaling and integration. Simple versus stratified epithelium describes layers; squamous, cuboidal and columnar describe cell shape."],
            ["Blood and support", "Mature human erythrocytes lack nuclei and carry haemoglobin. Leukocytes have immune roles, and platelets are cell fragments involved in haemostasis. Plasma contains proteins and soluble substances; serum is obtained after clotting and differs in clotting factors. Bone is mineralized connective tissue with remodeling cells, while cartilage has a different matrix and vascular supply. Fixed blood counts are reference ranges, not identical values in all people."]
        ],
        diseases: [
            ["Causes and transmission", "Infectious diseases involve specific agents and routes: tuberculosis is commonly caused by Mycobacterium tuberculosis, typhoid by Salmonella Typhi, and AIDS results from advanced HIV infection. A disease name, causative organism, vector and mode of transmission are separate facts. Screening seeks possible disease before symptoms or definitive diagnosis; a positive screen may require confirmation."],
            ["Immunity", "Innate immunity includes barriers and rapid cellular responses. Adaptive immunity involves antigen-specific lymphocytes and memory. B cells can differentiate into antibody-secreting plasma cells; T-cell subsets have distinct helper and cytotoxic roles. Vaccination induces active immune responses, whereas supplied antibodies provide passive immunity. Antibiotics are not a general cure for viral disease, and historical notes on tests and treatment are not current individual medical advice."]
        ],
        embryology: [
            ["Early development", "Fertilization forms a zygote, cleavage partitions it into blastomeres, and gastrulation establishes germ-layer organization. Cleavage increases cell number without the same overall growth pattern as later development. Morula, blastula and gastrula are distinct stages. Frog cleavage and yolk distribution differ from human early development."],
            ["Germ layers and neurulation", "Ectoderm contributes epidermis and neural tissue, mesoderm muscle and many connective and circulatory structures, and endoderm much of the digestive and respiratory epithelial lining. Neurulation forms the neural tube through coordinated tissue changes. An organ often contains derivatives of several germ layers, so assigning an entire complex organ to one layer can be misleading."]
        ],
        skeleton: [
            ["Bones and joints", "The typical adult human skeleton has 206 bones, but individual variation and fusion affect counts. Axial skeleton includes skull, vertebral column and thoracic cage; appendicular skeleton includes girdles and limbs. Joint categories distinguish structure and permitted movement. Synovial joints contain a cavity, articular cartilage and a capsule rather than being simply 'freely movable' in all possible directions."],
            ["Movement and contraction", "Skeletal muscle shortens through sliding of actin and myosin filaments rather than shortening of each filament. Calcium binding to troponin permits interaction in the standard skeletal-muscle model, and ATP is required for cross-bridge detachment and cycling. Tendons connect muscle to bone, while ligaments commonly connect bones. The longest, smallest or strongest structure must be defined by the particular measurement being compared."]
        ],
        adaptation: [
            ["Behavior", "Innate behavior develops without the relevant learning experience, while learned behavior changes with experience. Reflexes, orientation responses, conditioning and imprinting are different categories. Taxis is directional movement relative to a stimulus; kinesis changes movement rate or turning without requiring a directional relation. Behavioral explanations should distinguish immediate mechanisms from evolutionary function."],
            ["Adaptation and migration", "An evolutionary adaptation is a heritable feature shaped by selection, whereas acclimatization is an individual's adjustment. Migration is organized movement between areas and differs from random dispersal. Aquatic, arboreal and aerial adaptations occur as suites of traits. Statements in the source such as a camel storing water in its hump are misleading: the hump primarily stores fat, while water balance depends on multiple physiological mechanisms."]
        ],
        "applied-zoology": [
            ["Animal-based production", "Apiculture concerns bees, sericulture silkworms, pisciculture fish culture and poultry farming domesticated birds. Species, breed, product and management objective are different categories. Pollination and ecological services can be as important as directly harvested products. Disease control and environmental conditions determine sustainable production."],
            ["Reproductive and biological technology", "Artificial insemination transfers semen without ordinary mating, while in vitro fertilization involves fertilization outside the body followed by embryo transfer. IVF is not simply the growth of a whole fetus in a laboratory vessel. Vaccines and biological products can be produced through multiple technologies; live attenuated, inactivated and subunit categories have distinct properties."]
        ]
    };
    window.CEE_NOTE_GUIDES = Object.assign(window.CEE_NOTE_GUIDES || {}, guides);
})();