(function () {
    "use strict";
    const rows = [
        [123, "A nucleotide unit of a nucleic acid contains which components?", ["Phosphate, sugar and amino acid", "Protein, phosphate and lipid", "Phosphate, pentose sugar and nitrogenous base", "Phosphate, lipid and fatty acid"], "c", "Each nucleotide consists of a pentose, a nitrogenous base and one or more phosphates. Nucleic acids are polymers of nucleotide residues, not protein-phosphate complexes."],
        [124, "What is the name of the correspondence between mRNA codons and amino acids or stop signals?", ["Genetic code", "Gene pool", "Chromosome number", "Replication fork"], "a", "The genetic code is the codon-to-amino-acid or stop correspondence. A protein's actual amino-acid order is determined by its mRNA coding sequence interpreted with that code.", "The source conflates sequence information in a gene with the code used to interpret it. The mapping itself is now tested."],
        [125, "Passage of an X-linked allele from a father through a daughter to a grandson is classically called what?", ["Holandric inheritance", "Criss-cross inheritance", "Blending inheritance", "Strict father-to-son inheritance"], "b", "A father transmits his X to daughters, who may transmit that X-linked allele to sons. Y-specific father-to-son transmission is holandric.", "The source's 'diagenetic' wording is replaced with the conventional criss-cross description; X-linked transmission is not exclusively this one route."],
        [126, "The common full-trisomy form of Down syndrome is caused by which dosage change?", ["Monosomy 21", "Trisomy 21", "Nullisomy 21", "Tetrasomy 21"], "b", "Trisomy 21 means three copies of chromosome 21. Monosomy means one copy, nullisomy no copies and tetrasomy four copies."],
        [127, "An alternative form of a gene is called what?", ["Allele", "Homozygote", "Heterozygote", "Hemizygote"], "a", "An allele is an alternative genetic form at a locus. The other terms describe how allele copies are represented in an individual."],
        [128, "Which meiotic error commonly produces a gamete that can lead to full trisomy 13 after fertilization?", ["Chromosome inversion", "Normal crossing over", "Nondisjunction", "Single-base substitution"], "c", "Nondisjunction is failure of chromosomes or chromatids to separate normally. A gamete with an extra chromosome 13 can produce trisomy 13 after fertilization."],
        [129, "A phenotypically normal daughter of an X-linked colour-blind man marries an unaffected man. What is the risk among their sons?", ["All daughters affected", "All sons unaffected", "Half the sons affected", "Half the daughters affected"], "c", "The woman must have inherited her father's affected X, so she is a carrier. XNXc x XNY gives half the sons XcY and no affected daughters in this simple model."],
        [130, "Which statements about a typical tRNA molecule are correct?<br>1. It contains internally base-paired regions.<br>2. It contains hydrogen bonds.<br>3. It contains uracil.<br>4. It is formed from one RNA strand.", ["1, 3 and 4 only", "1 and 2 only", "1, 2, 3 and 4", "2 and 3 only"], "c", "tRNA is a single RNA strand folded by internal hydrogen-bonded base pairing. It contains uracil and modified bases; single-stranded does not mean completely unpaired."],
        [131, "An uncorrected DNA-polymerase copying error can introduce a gene mutation during which process?", ["DNA replication", "Cytokinesis alone", "Protein translation", "RNA transcription alone"], "a", "Misincorporated nucleotides during DNA replication can become heritable DNA sequence changes if proofreading and repair fail. Other mutational mechanisms also exist.", "The source implies mutation occurs only in one process. This adapted question specifies an uncorrected copying error."],
        [132, "Which newly synthesized DNA strand is formed discontinuously as Okazaki fragments?", ["Both strands continuously", "Leading strand", "Lagging strand", "Neither strand"], "c", "DNA synthesis proceeds only 5' to 3'. Because templates are antiparallel, the lagging strand must be made in repeated short segments as the fork opens."],
        [133, "Hybridization between different species followed by chromosome-set doubling can produce what?", ["Autopolyploidy", "Allopolyploidy", "Aneuploidy", "One extra chromosome only"], "b", "An allopolyploid combines chromosome sets derived from different species. Doubling can provide pairing partners for homologues and restore fertility in an otherwise sterile hybrid.", "Different species and chromosome-set doubling are specified; hybridization alone does not define allopolyploidy."],
        [134, "Expression of a protein-coding gene can ultimately produce which functional product?", ["A polypeptide", "A whole chromosome", "A new allele by necessity", "A spindle fibre without translation"], "a", "The gene is transcribed into RNA, and its mRNA can be translated into a polypeptide. Not all genes encode proteins; some encode functional RNAs.", "The question specifies a protein-coding gene to avoid claiming every gene produces an enzyme or protein."],
        [135, "The classic 45,X form of Turner syndrome is an example of what?", ["Disomy X", "Trisomy X", "Monosomy X", "Whole-set polyploidy"], "c", "45,X means one X chromosome instead of the usual two sex chromosomes. It is monosomy, a form of aneuploidy."],
        [136, "Removal of introns and joining of exons in a pre-mRNA molecule is called what?", ["Transduction", "Induction", "RNA splicing", "Constitutive expression"], "c", "Splicing removes intervening intron sequences and joins exons. It can occur during or after transcription and is distinct from translation."],
        [137, "Which inherited haemoglobin disorder is associated with HbS?", ["Phenylketonuria", "Sickle-cell disease", "Haemophilia A", "Red-green colour-vision deficiency"], "b", "HbS contains a beta-globin amino-acid substitution that can promote polymerization when deoxygenated. Sickle-cell disease and the heterozygous carrier trait must be distinguished.", "The source's unqualified claim about the 'most common disease' in a community is not established here. The same disorder is tested through its haemoglobin identity."],
        [138, "What process converts an intron-containing primary RNA transcript into an exon-joined transcript?", ["Transduction", "Induction", "Splicing", "Formation of constitutive genes"], "c", "The spliceosome removes most nuclear pre-mRNA introns and joins exons. The process changes the RNA transcript, not the original DNA gene."],
        [139, "In the approximate school-level B-DNA model with 3.4 nm per turn and 0.34 nm rise per base pair, how many base pairs occupy one turn?", ["11", "12", "10", "9"], "c", "Number per turn = 3.4/0.34 = 10. Real B-DNA averages about 10.5 base pairs per turn depending on conditions, so the approximation is stated explicitly."],
        [140, "Human skin pigmentation is a classic example of which broad inheritance pattern?", ["A single Mendelian locus only", "Polygenic quantitative inheritance", "One complementary pair only", "Y-linked inheritance only"], "b", "Many genes contribute to pigmentation, with environmental influences such as ultraviolet exposure as well. The resulting variation is quantitative, not a universal single-gene dominant-recessive trait."],
        [141, "In the standard E. coli replication model, which enzyme removes RNA primers using 5'-to-3' exonuclease activity and replaces them with DNA?", ["DNA ligase", "DNA polymerase III", "DNA polymerase I", "Primase"], "c", "E. coli DNA polymerase I removes primers and fills the resulting gaps. Ligase seals remaining nicks. Eukaryotes use different primer-removal machinery.", "The bacterial model is specified; DNA polymerase I is not the universal answer for all cells."],
        [142, "Colchicine can be used in plant breeding to induce which change by interfering with spindle formation?", ["Only single-base substitution", "Only gene deletion", "Chromosome-set doubling", "Only chromosome inversion"], "c", "Colchicine disrupts microtubule assembly and can prevent normal chromosome separation. Under suitable conditions the resulting cell retains doubled chromosome sets, producing polyploidy."],
        [143, "In an organism with photolyase, visible-light-driven reversal of UV-induced pyrimidine dimers is called what?", ["Mutagenesis", "Photoreactivation", "Vernalization", "Chromosome inversion"], "b", "Photolyase can use light energy to reverse particular UV-induced DNA lesions. This mechanism occurs in many organisms, but humans do not have functional photolyase-mediated photoreactivation.", "The mechanism and organismal limitation are specified rather than asserting that every cell repairs UV damage this way."],
        [144, "Which is the general composition of a nucleotide?", ["Base, sugar and phosphate", "Sugar and phosphate without a base", "Purine and phosphate without a sugar", "Pyrimidine and sugar without phosphate"], "a", "A nucleotide has a nitrogenous base, pentose sugar and phosphate. Base plus sugar without phosphate is a nucleoside.", "The original purine-only and pyrimidine-only choices describe valid subtypes; choices now distinguish complete from incomplete composition."],
        [145, "Synthesis of DNA using an RNA template is called what?", ["Transcription", "Transduction", "Ordinary DNA replication", "Reverse transcription"], "d", "Reverse transcriptase is an RNA-dependent DNA polymerase. It forms DNA from an RNA template, as in retroviral replication."],
        [146, "A genetically dwarf tt pea becomes taller after gibberellin treatment. It is crossed with a pure tall TT pea. With complete dominance, what offspring phenotype is expected?", ["100% dwarf", "100% tall", "75% tall and 25% dwarf", "50% tall and 50% dwarf"], "b", "Gibberellin changes growth without changing tt into TT. The genetic cross remains tt x TT, giving all Tt offspring with the tall phenotype."],
        [147, "A diploid species has haploid number n = 20. What are the chromosome counts for monosomy and tetrasomy of one chromosome?", ["20 and 40", "39 and 42", "40 and 42", "19 and 22"], "b", "The normal diploid number is 2n = 40. Monosomy is 2n-1 = 39; tetrasomy of one chromosome is 2n+2 = 42, not whole-set tetraploidy."],
        [148, "Adenine accounts for 29% of the bases in a double-stranded DNA molecule. What percentage is cytosine?", ["58%", "21%", "42%", "71%"], "b", "A = T = 29%, leaving 100-58 = 42% for G and C. Because G = C, cytosine is 42/2 = 21%."],
        [149, "Inheritance of an X-linked allele from a father through a daughter to a grandson is called what?", ["Complete linkage", "Criss-cross inheritance", "New mutation", "Polygenic inheritance"], "b", "A father gives his X to daughters rather than sons. A daughter can then pass the allele to a son, producing the classic criss-cross pattern."],
        [150, "What may differ between corresponding loci of a pair of homologous chromosomes?", ["Their usual centromere position", "Their usual overall size", "Their membership in the same pair", "The alleles they carry"], "d", "Homologues carry the same kinds of genes at corresponding loci but may carry different alleles, such as A and a. One homologue is normally inherited from each parent."],
        [151, "Which statement about RNA is incorrect?", ["mRNA carries codons", "tRNA carries an anticodon", "rRNA participates in protein synthesis", "tRNA is always the largest RNA class"], "d", "tRNA is relatively small, typically about 70-90 nucleotides. rRNAs and many mRNAs are much longer. RNA lengths vary, but tRNA is not the largest class."],
        [152, "Which is the recessive form among these Mendelian pea traits?", ["Green pod", "Round seed", "Axial flowers", "Green seed"], "d", "Green seed colour is recessive to yellow. Green pods, round seeds and axial flowers are the dominant forms of their corresponding Mendelian contrasts."],
        [153, "A breeder repeats a cross with the sexes of the two parental genotypes interchanged. What is this called?", ["Reverse mutation", "Reciprocal cross", "Test cross", "Dihybrid cross"], "b", "A reciprocal cross swaps which parental genotype supplies pollen versus ovules, or sperm versus eggs. It can help detect sex-linked or maternal effects.", "The source's 'gametes reversed in offspring' wording is replaced with the actual parental-sex reversal."],
        [154, "Compared with HbAA, heterozygous HbAS sickle-cell trait is associated with which effect in malaria-endemic settings?", ["Greater risk of severe falciparum malaria", "Reduced risk of severe falciparum malaria", "Greater risk of typhoid by definition", "Complete immunity to all infections"], "b", "HbAS provides relative protection against severe Plasmodium falciparum malaria, not complete immunity. This heterozygote advantage differs from HbSS sickle-cell disease, which has substantial health risks.", "The source incorrectly generalizes protection to 'sickle cell anaemic' people. Carrier trait and reduced severe-malaria risk are specified."],
        [155, "A phenotypically unaffected daughter of a man with X-linked recessive haemophilia marries a non-haemophilic man. What outcome is expected?", ["All children affected", "All daughters affected", "Half the sons affected, no daughters affected", "No affected children are possible"], "c", "The woman is an obligate carrier: XHXh. Crossing with XHY gives XHXH, XHXh, XHY and XhY equally. Half the sons are affected; with equal sexes, affected children are one quarter of all offspring.", "The source omits the mother's phenotype and incorrectly offers 'all sons haemophilic'. Carrier status and the 50%-of-sons answer are corrected."],
        [156, "In historical terminology, what is the smallest unit of DNA capable of recombination?", ["Recon", "Cistron", "Muton", "Codon"], "a", "A recon is the smallest recombination unit. A muton concerns mutation, a cistron function, and a codon translation."],
        [157, "Common inherited red-green colour-vision deficiency usually follows which pattern?", ["X-linked dominant", "X-linked recessive", "Y-linked dominant", "Obligately both X- and Y-linked"], "b", "The common red-green forms are X-linked recessive. A male with the affected allele on his single X is typically affected; a heterozygous female is usually a carrier."],
        [158, "What is the underlying cause of genetic drift?", ["A necessarily increasing allele count", "Random sampling of alleles between generations", "A fixed increase in every allele frequency", "Migration alone between populations"], "b", "Drift is random change in allele frequency caused by finite sampling of gametes and individuals. It is especially strong in small populations and differs from directed selection or gene flow.", "The source defines any allele-frequency change as drift; random sampling is added to distinguish drift from other evolutionary processes."]
    ];
    window.CEE_SOURCE_QUESTIONS = (window.CEE_SOURCE_QUESTIONS || []).concat(rows.map(([number, text, choices, answer, explanation, editorialNote]) => ({
        id: "pdf-bio-bank-" + number, subject: "Botany", topicId: "genetics", text,
        options: choices.map((value, index) => ({ key: "abcd"[index], text: value })), answer, explanation,
        source: { document: "biology", page: 212, set: "genetics-bank", number, adapted: true },
        ...(editorialNote ? { editorialNote } : {})
    })));
})();