window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["adaptation"] = {
    id: "adaptation",
    subject: "Zoology",
    title: "Animal adaptation and behaviour",
    sections: [
        {
            id: "behaviour-innate-and-learned",
            title: "Behaviour, ethology and inherited versus learned components",
            sources: [{ document: "biology", page: 150 }, { document: "biology", page: 151 }, { document: "biology", page: 153 }, { document: "biology", page: 156 }],
            html: "<p>Behaviour is the observable activity of an organism in relation to internal or external conditions; the source describes outwardly expressed responses to stimuli. Ethology is the study of animal behaviour. A stimulus can be light, a chemical, temperature, a mechanical event or an internal physiological signal.</p>" +
                "<p>The source groups stereotyped, inherited, innate and instinctive behaviour as inborn adaptive mechanisms. Its inventory includes reflexes, taxes, instincts, migration, social behaviour, mating, dominance, courtship and territorial behaviour. These can have inherited components, but the terms are not exact synonyms and many behaviours also depend on learning, maturation and circumstances. An innate behaviour need not remain identical throughout life.</p>" +
                "<p>Learned or acquired behaviour changes through experience. The source examples are singing, cycling, swimming, painting and leadership. Learned content is not directly transmitted as a newly encoded skill through gametes, although capacities for learning have inherited influences and information can pass socially. Learning is not restricted to animals with a supposedly 'higher' nervous system; invertebrates can learn too. Singing and swimming may combine learned and innate components depending on species.</p>" +
                "<p><strong>Source correction:</strong> the page classifies leadership as learned, while the next calls it innate. Neither blanket label is sufficient. The claim that all plant responses are animal-like innate behaviour also conflates different mechanisms: plants respond to stimuli without animal nerves. Spider web-building has a strong species-typical component, as the page 153 note emphasizes, but web geometry can change with conditions and experience; 'fixed web pattern' is not absolute rigidity.</p>"
        },
        {
            id: "reflex-arc-and-types",
            title: "Reflex arc, integration sites and conditioned responses",
            sources: [{ document: "biology", page: 150 }],
            html: "<p>A reflex is a relatively rapid automatic response mediated through a neural pathway. The source's diagram reads stimulus &rarr; receptor &rarr; sensory or afferent neuron &rarr; central integration in spinal cord or brain &rarr; motor or efferent neuron &rarr; effector &rarr; response. Its five text stages are reception, afferent conduction, modulation or interpretation, efferent conduction and effect. A receptor detects the stimulus; an effector is a muscle or gland that executes the response.</p>" +
                "<table><thead><tr><th>Source type</th><th>Examples and qualification</th></tr></thead><tbody><tr><td>Spinal reflex</td><td>Knee jerk; the principal reflex integration is in the spinal cord, although the brain can modulate it</td></tr><tr><td>Brain or cranial reflex</td><td>Reflex blinking, salivation and sneezing involve brainstem circuits</td></tr><tr><td>Combined reflex</td><td>The source lists hunger and cough. Hunger is primarily a regulated drive, not a simple reflex; coughing is a coordinated brainstem-mediated response involving multiple muscles</td></tr><tr><td>Unconditioned reflex</td><td>An unlearned response, such as protective blinking to an appropriate stimulus</td></tr><tr><td>Conditioned response</td><td>A learned response to a previously neutral cue, such as salivation to a bell after pairing with food</td></tr></tbody></table>" +
                "<p><strong>Source correction:</strong> a reflex is not necessarily controlled consciously by the brain and is not limited to one part of the body. The source's neuron spelling is corrected from 'neutron'. Reflex effectors include glands as well as muscles, so 'motor response' alone does not cover every example.</p>" +
                "<p>In the bell example, food naturally elicits salivation; repeated association can make the bell a conditioned stimulus. This is classical conditioning. A reward delivered as a consequence of an action instead describes operant conditioning, so the source's phrase 'repetitive stimulus and reward mechanism' must not erase the distinction.</p>"
        },
        {
            id: "orientation-taxis-kinesis",
            title: "Orientation, taxis, kinesis and tropism",
            sources: [{ document: "biology", page: 150 }, { document: "biology", page: 151 }],
            html: "<p>Orientation relates an organism's position or movement to a reference. The source's primary orientation means maintaining posture relative to gravity or a supporting surface, illustrated by a fish in water, a bird in air and a lizard on a wall. Secondary orientation means positioning in relation to other stimuli.</p>" +
                "<table><thead><tr><th>Response</th><th>Defining distinction</th></tr></thead><tbody><tr><td>Positive taxis</td><td>Directed movement or orientation toward a stimulus source under a specified convention</td></tr><tr><td>Negative taxis</td><td>Directed movement away from a stimulus source</td></tr><tr><td>Kinesis</td><td>Nondirectional change in movement rate or turning frequency with stimulus intensity</td></tr><tr><td>Tropism</td><td>A directional growth response in the usual plant-biological sense; older usage also described bending orientation of attached organisms</td></tr></tbody></table>" +
                "<p>A faster random walk in an unfavourable environment can change where an animal accumulates without each step being directed toward a source. That is why kinesis is not interchangeable with taxis. The source gives Hydra tentacle movement as a kinesis example, but an unspecified tentacle contraction is not enough to demonstrate stimulus-dependent nondirectional locomotion; the example is retained with this limitation.</p>" +
                "<p><strong>Source qualification:</strong> a taxic response must be defined with its stimulus, direction and conditions. The same organism may approach one intensity or concentration and avoid another. Protist and bacterial examples in the source table illustrate orientation beyond animals in modern classification.</p>"
        },
        {
            id: "stimulus-taxis-table",
            title: "Every stimulus-based taxis example in the source table",
            sources: [{ document: "biology", page: 151 }, { document: "biology", page: 156 }],
            html: "<table><thead><tr><th>Stimulus and term</th><th>Positive column in source</th><th>Negative column in source</th></tr></thead><tbody><tr><td>Light: phototaxis</td><td>Euglena; moths</td><td>Earthworms; cockroaches</td></tr><tr><td>Chemicals: chemotaxis</td><td>Bacteria, ants and bees toward food; male gametes</td><td>Mosquitoes, pests and cockroaches avoiding repellent; earthworm exposed to dilute HCl</td></tr><tr><td>Temperature: thermotaxis</td><td>Planaria</td><td>Earthworm</td></tr><tr><td>Gravity: geotaxis</td><td>Earthworm; cnidarian planula</td><td>Cnidarian ephyra</td></tr><tr><td>Current: rheotaxis</td><td>Butterfly</td><td>Salmon, Planaria and Petromyzon or lamprey</td></tr><tr><td>Oxygen: aerotaxis</td><td>Aerobic bacteria</td><td>No negative example supplied</td></tr><tr><td>Electric field: galvanotaxis</td><td>Paramecium</td><td>No negative example supplied</td></tr></tbody></table>" +
                "<p>The table records the source assignments before qualification. Euglena can orient to suitable light, and earthworms or cockroaches often avoid illumination. Moth behaviour near artificial lamps is more complex than a universal attraction reflex and can include disruption of flight orientation. Chemical attraction and avoidance depend on the compound and concentration; the source's acid exposure is an example to interpret, not an animal-testing instruction. Chemotaxis of male gametes is species-specific, not a universal rule for all sperm.</p>" +
                "<p>Planarians and earthworms respond to temperature gradients within physiological ranges; neither always seeks greater heat or always avoids any warming. Planula and ephyra responses depend on species and developmental context; an ephyra is a juvenile medusa. These unqualified signs are not used as scored species constants.</p>" +
                "<p><strong>Source correction:</strong> conventional positive rheotaxis is orientation or swimming against an oncoming water current. The source's negative column for upstream-oriented fishes is therefore misleading. Movement relative to wind is more specifically anemotaxis; the butterfly row supplies no clear heading or reference direction. Aerotaxis concerns oxygen concentration rather than simply 'toward air'. Paramecium can orient in an electric field, but the page does not establish a distinct anatomical organ called a galvanoreceptor or an electrode polarity for every condition.</p>"
        },
        {
            id: "orientation-mechanisms",
            title: "Klinotaxis, tropotaxis, telotaxis, menotaxis and mnemotaxis",
            sources: [{ document: "biology", page: 151 }],
            html: "<table><thead><tr><th>Mechanism</th><th>How the source describes orientation</th></tr></thead><tbody><tr><td>Klinotaxis</td><td>Successive sampling while moving or sweeping; the organism changes direction as stimulus intensity changes. Euglena orienting to light is listed</td></tr><tr><td>Tropotaxis</td><td>Simultaneous comparison by spatially separated receptors can orient an organism toward or away from a source. Lice, ticks and Planaria are named</td></tr><tr><td>Telotaxis</td><td>Selection of one stimulus source among alternatives rather than steering to an average direction. Dragonfly and hermit crab are the examples</td></tr><tr><td>Menotaxis</td><td>Maintaining a constant angle relative to a cue, such as a light-compass reference. Ants and bees guided by sunlight are listed</td></tr><tr><td>Mnemotaxis</td><td>Orientation using remembered spatial cues or landmarks. Wasps and bees are the examples</td></tr></tbody></table>" +
                "<p><strong>Source correction:</strong> klinotaxis is not defined by complete absence of a sensory receptor; sequential sampling is the key. The source's 'sidewise' and 'straight' labels are useful sketches but not complete definitions. Planaria under '+ve phototropotaxis' should not be memorized as a universal positive-light response; many planarians avoid light, independently of how receptors compare signals.</p>" +
                "<p>The telotaxis example uses two equal-intensity sources to make the selection idea clear, but exact equality is not required by the definition. Menotaxis concerns an angular bearing, not necessarily heading directly toward the sun. A learned visual landmark and a chemical trail are different navigation cues: the source's claim that a bee 'makes landmarks using a trail of chemicals' conflates them. Mnemotaxis relies on remembered cues, while chemical trail-following must be described separately.</p>"
        },
        {
            id: "leadership-and-dominance",
            title: "Leadership, dominance and the limits of sex-based generalizations",
            sources: [{ document: "biology", page: 150 }, { document: "biology", page: 151 }],
            html: "<p>Leadership means influencing or initiating a group's movement or activity. The source's qualities are initiating, stabilizing and integrating the group. Dominance concerns repeated asymmetries in social interactions and access to resources such as food, mates or shelter. Dominance rank and leadership can coincide, but one does not define the other.</p>" +
                "<table><thead><tr><th>Source example or claim</th><th>Qualification</th></tr></thead><tbody><tr><td>Rhesus monkey as herd leader</td><td>Macaque groups have complex, sex- and relationship-dependent hierarchies; not a single universal herd-leader rule</td></tr><tr><td>Mostly male leaders</td><td>Not a general law across social animals</td></tr><tr><td>Female leaders: red deer, spotted hyena, African elephant</td><td>Female-led groups or female dominance occur in particular social contexts; elephant matriarchal groups are a useful example, while the species and group type matter</td></tr><tr><td>Female leaders: ants and bees</td><td>Queens are reproductive females, not commanders directing every worker action; colony coordination is largely distributed</td></tr><tr><td>Female lemurs and dogs dominate males in breeding season</td><td>Female dominance occurs in some lemurs, but the combined statement is not a universal rule for every lemur or dog population</td></tr><tr><td>A newly mature songbird dominates an older bird</td><td>No species, situation or evidence is specified; this is not a reliable age-based law</td></tr></tbody></table>" +
                "<p>The notes call dominance both innate and learned. Inherited traits, development, prior encounters, social relationships and environment can all contribute. 'Weaker members' is not a complete definition of subordinate status, and leadership need not be held by the physically strongest or highest-ranking individual. The examples are behavioral comparisons, not claims about human gender roles.</p>"
        },
        {
            id: "migration-and-fish-types",
            title: "Migration and the complete fish-migration classification",
            sources: [{ document: "biology", page: 152 }],
            html: "<p>The source defines migration as regular, periodic or cyclic movement between places, often associated with food, climate or breeding. It calls migration complex innate behaviour and a two-way journey. Many migrations include inherited programmes and learned navigation, and return movement may be completed by another generation; the same individual need not always make a round trip.</p>" +
                "<table><thead><tr><th>Type</th><th>Movement distinction</th><th>Source examples</th></tr></thead><tbody><tr><td>Diadromous</td><td>Movement between freshwater and seawater during the life cycle</td><td>Parent category for anadromy, catadromy and amphidromy</td></tr><tr><td>Anadromous</td><td>Growth largely at sea, with movement into freshwater to reproduce</td><td>Salmon, sea lamprey or Petromyzon, hilsa</td></tr><tr><td>Catadromous</td><td>Growth largely in freshwater or continental waters, with reproduction at sea</td><td>European and American freshwater eels</td></tr><tr><td>Amphidromous</td><td>Movement between sea and freshwater not primarily the adult spawning migration itself</td><td>Some gobies</td></tr><tr><td>Potamodromous</td><td>Migration entirely within freshwater</td><td>Carp and freshwater-resident trout populations</td></tr><tr><td>Oceanodromous</td><td>Migration entirely within seawater</td><td>Tuna, mackerel and herring examples</td></tr></tbody></table>" +
                "<p><strong>Source correction:</strong> 'true migratory' for diadromous and 'false migratory' for potamodromous are misleading labels. Freshwater-only movement can be genuine migration. Trout include different life histories, so the common name alone does not establish the category.</p>" +
                "<p>The eel names are reversed in the handwriting. The European eel is <em>Anguilla anguilla</em>, historically also called A. vulgaris; the American eel is <em>Anguilla rostrata</em>. Both are classical catadromous examples. The short Nepali sound cue next to anadromous means coming inward and serves only to recall sea-to-freshwater spawning; the reproductive destination, not the sound of the word, defines the category.</p>"
        },
        {
            id: "fish-migration-directions-and-purposes",
            title: "Fish migration by direction and biological purpose",
            sources: [{ document: "biology", page: 152 }],
            html: "<table><thead><tr><th>Directional label</th><th>Source definition and examples</th></tr></thead><tbody><tr><td>Latitudinal</td><td>North-south movement; swordfish and a partly unclear name resembling barracuda are written</td></tr><tr><td>Horizontal</td><td>Movement upstream or downstream in the source river example; not only one direction</td></tr><tr><td>Vertical</td><td>Movement between surface and deeper water; swordfish is listed</td></tr><tr><td>Shoreward</td><td>The source says water-to-land and back, naming common eel and climbing perch</td></tr></tbody></table>" +
                "<p><strong>Source qualification:</strong> shoreward normally means toward a shore and need not include leaving the water. Eels and climbing perch can move over wet ground in some circumstances, but an overland excursion is not a defining feature of every shoreward migration. The partly unclear fish name is not converted into a verified species claim.</p>" +
                "<table><thead><tr><th>Purpose label</th><th>Function</th></tr></thead><tbody><tr><td>Alimental migration</td><td>Obtaining food</td></tr><tr><td>Gametic or spawning migration</td><td>Reproduction</td></tr><tr><td>Climatic or wintering migration</td><td>Avoiding or exploiting seasonal environmental conditions</td></tr><tr><td>Osmoregulatory migration</td><td>Moving among conditions relevant to water and ion balance</td></tr></tbody></table>" +
                "<p>These classifications answer different questions. A spawning migration may be anadromous by salinity, upstream by direction and reproductive by purpose simultaneously. Direction alone does not establish its life-history category.</p>"
        },
        {
            id: "bird-migration-patterns",
            title: "Bird migration: routes, timing and every listed example",
            sources: [{ document: "biology", page: 152 }, { document: "biology", page: 153 }],
            html: "<p>The source calls birds great migrants and names Siberian crane, Arctic tern, golden plover, an abbreviated B &amp; W cuckoo entry and goose. These are examples of migratory birds, not a claim that every individual of each broad common-name group follows the same route. Phenology studies the timing of recurring seasonal biological events, including migration; it is not exclusively the science of bird migration.</p>" +
                "<table><thead><tr><th>Pattern</th><th>Source route or timing</th><th>Examples and limits</th></tr></thead><tbody><tr><td>Latitudinal</td><td>Across latitudes, broadly north-south and back</td><td>Golden plover; Eurasian and Siberian birds. The globe's arrows run between north and south</td></tr><tr><td>Longitudinal</td><td>Across longitudes, broadly east-west and back</td><td>Starling; the source writes eastern Europe to Asia to avoid winter without a species or population, so the route is not generalized</td></tr><tr><td>Altitudinal or vertical</td><td>Seasonal movement between lower and higher elevations</td><td>Woodcock and bushchat; particular populations and species determine the pattern</td></tr><tr><td>Daily local movement</td><td>Leaving a nest or roost and returning in the evening</td><td>Sparrow and crow; usually daily commuting or foraging rather than migration in the narrower seasonal sense</td></tr><tr><td>Summer visitors</td><td>Seasonal arrival in a reference region</td><td>Swifts and swallows</td></tr><tr><td>Winter visitors</td><td>Seasonal arrival in a reference region</td><td>Fieldfare and snow bunting</td></tr></tbody></table>" +
                "<p>Summer and winter visitor depend on the observation region, which the source does not specify. The labels must not be assumed to describe every Nepal locality.</p>" +
                "<table><thead><tr><th>Flight timing in source</th><th>Named groups</th></tr></thead><tbody><tr><td>Nocturnal migration</td><td>Warblers, thrushes and sparrows</td></tr><tr><td>Diurnal migration</td><td>Crows, swallows, robins, hawks and cranes</td></tr><tr><td>Both day and night</td><td>Ducks and gulls</td></tr></tbody></table>" +
                "<p><strong>Source qualification:</strong> these are broad examples, not exceptionless rules; robin is especially ambiguous as a common name, and several migratory robins travel at night. A bird can migrate at night while feeding mainly by day.</p>"
        },
        {
            id: "migration-cues-and-records",
            title: "Seasonal cues, endocrine associations and record claims",
            sources: [{ document: "biology", page: 153 }],
            html: "<p>The source links migration with daylight effects on endocrine glands, associates the pituitary with seasonal migration, and the pineal with seasonal fertility. Seasonal photoperiod can influence biological clocks, endocrine signalling and reproductive state. Environmental conditions, fuel stores, inherited programmes and experience also affect migration.</p>" +
                "<p>The specific claim that pituitary FSH and LH make birds travel fastest during migration overstates their role. These are chiefly gonadotropins in reproductive regulation, not a universal direct control of migration speed. Pineal and pituitary functions participate in broader timing systems rather than one gland exclusively causing one seasonal behaviour.</p>" +
                "<p><strong>Source correction:</strong> golden plover is labelled the longest nonstop flyer without a date, measured distance or species. That is not a defensible current universal record; tracked bar-tailed godwits have demonstrated exceptionally long nonstop flights. The Arctic tern's very long annual migration is a different metric from the longest single nonstop flight. No flight-distance record is scored from the unqualified source line.</p>"
        },
        {
            id: "adaptation-and-evolutionary-patterns",
            title: "Adaptation, phenotype and evolutionary patterns",
            sources: [{ document: "biology", page: 153 }],
            html: "<p>The source defines adaptation as adjustment or fitness of an organism in its environment. In evolutionary usage an adaptation is a heritable feature shaped by selection because it contributes to reproductive success in a context. An individual's short-term physiological acclimatization is not automatically a genetic adaptation.</p>" +
                "<p>The notes say adaptation is expressed in somatoplasm and has its reason in germ plasm. The useful distinction is phenotype expressed in a developing organism versus inherited information transmitted through reproductive lineages. <strong>Source correction:</strong> gametes do not intentionally generate traits because an animal needs them, and environmental influence on a phenotype does not by itself show that the acquired change is inherited.</p>" +
                "<table><thead><tr><th>Source pattern</th><th>Examples and precise reading</th></tr></thead><tbody><tr><td>Convergence: dissimilar to similar</td><td>Insect, bird and bat flight; aquatic locomotion of whales, fishes and webbed ducks. Comparable functions evolved independently at the relevant character level</td></tr><tr><td>Divergence: similar to dissimilar</td><td>Turtles and tortoises; Darwin's finches. Related lineages acquire differing specializations</td></tr><tr><td>Parallelism: similar to similar</td><td>The source lists aquatic-mammal limbs and climbing-vertebrate limbs. These are only broad examples; distinguishing parallelism from convergence requires a defined trait and phylogeny</td></tr></tbody></table>" +
                "<p>Bird and bat forelimbs remain homologous even when their wings are compared as independently evolved flight structures. The source classes of adaptations are structural, meaning morphological or anatomical; physiological; and protective. They can overlap: an anatomical feature may have a physiological and protective role.</p>"
        },
        {
            id: "primary-aquatic-adaptations",
            title: "Fish body form, fins, buoyancy and sensory structures",
            sources: [{ document: "biology", page: 153 }, { document: "biology", page: 156 }],
            html: "<p>The source's primary aquatic adaptation refers to fishes as lineages adapted to aquatic life, in contrast with land-vertebrate lineages that later returned to water. It does not mean that every fish has the same shape or physiology.</p>" +
                "<table><thead><tr><th>Feature</th><th>Source detail and function</th></tr></thead><tbody><tr><td>Body form</td><td>Streamlined body, conical head, often lateral compression, and little externally distinct neck reduce or manage resistance during locomotion; different swimming niches produce different shapes</td></tr><tr><td>Gills and scales</td><td>Gills exchange gases; scales provide protection in many fishes. Scale absence and accessory air breathing occur in some lineages</td></tr><tr><td>Flexible body and fins</td><td>The source calls body movement primary and fins secondary. Axial muscles, tail and fins contribute differently in different swimming modes</td></tr><tr><td>Swim or air bladder</td><td>A buoyancy-related organ of many bony fishes with evolutionary homology to lungs; absent in cartilaginous fishes and also absent or reduced in some bony fishes</td></tr><tr><td>Lateral line</td><td>Mechanosensory system detecting local water movement and pressure disturbances; the source calls it a rheoreceptor or current receptor</td></tr><tr><td>Epidermal mucus</td><td>Mucus-producing cells or glands protect the surface and influence interaction with water</td></tr><tr><td>Nictitating membrane</td><td>A third eyelid in some vertebrates, including some sharks and amphibians, not a universal feature of fishes</td></tr></tbody></table>" +
                "<p><strong>Source correction:</strong> a streamlined swimmer need not be laterally compressed, and not every deep-sea fish is dorsoventrally flattened. The source's deep-sea pair, flattened body and no swim bladder, describes possible adaptations rather than a definition of all deep-sea fishes; body form and buoyancy organs vary greatly by habitat and lineage.</p>"
        },
        {
            id: "aquatic-osmoregulation",
            title: "Water balance in fishes and freshwater protists",
            sources: [{ document: "biology", page: 153 }, { document: "biology", page: 154 }],
            html: "<p>Kidneys and gills contribute to fish osmoregulation. The source contrasts salt-absorbing cells in freshwater with salt-secreting cells in marine conditions. This is useful for typical teleosts but does not cover every aquatic animal.</p>" +
                "<table><thead><tr><th>Typical teleost habitat</th><th>Osmotic problem</th><th>Compensating processes</th></tr></thead><tbody><tr><td>Freshwater</td><td>Body fluids are more concentrated than the surroundings; water enters and salts tend to be lost</td><td>Active ion uptake at gills and excretion of relatively abundant dilute urine</td></tr><tr><td>Seawater</td><td>Body fluids are less concentrated than seawater; water tends to leave and salts enter</td><td>Drinking, intestinal water uptake and ion secretion, especially at gills, with limited water loss</td></tr></tbody></table>" +
                "<p><strong>Source correction:</strong> the goal is regulated internal composition, not necessarily an isotonic state with the external water. Typical freshwater and marine teleosts maintain differences from their surroundings. Marine cartilaginous fishes have a different strategy involving retained organic solutes; the teleost comparison is not universal.</p>" +
                "<p>Many freshwater protozoans have contractile vacuoles that collect and expel excess water entering by osmosis. This is a cell-level water-balance adaptation, not a substitute for a fish kidney and not the main locomotor organ. The source separately names cilia, flagella and pseudopodia for locomotion.</p>"
        },
        {
            id: "secondary-aquatic-inventory",
            title: "Secondary aquatic adaptation: all source vertebrate examples",
            sources: [{ document: "biology", page: 154 }],
            html: "<p>Secondarily aquatic vertebrates have land-dwelling ancestors and retain lungs; they must obtain atmospheric oxygen even when specialized for diving. The source says they surface frequently and may enter water for food. Surfacing interval and time spent on land vary widely, and the word amphibious here describes lifestyle, not membership in the class Amphibia.</p>" +
                "<table><thead><tr><th>Group</th><th>Amphibious column in source</th><th>Aquatic column in source</th></tr></thead><tbody><tr><td>Reptiles</td><td>Turtles, crocodiles and alligators</td><td>Marine turtles; extinct Ichthyosauria</td></tr><tr><td>Birds</td><td>Albatross, pelican, gulls, ducks and geese</td><td>Penguins</td></tr><tr><td>Mammals</td><td>Sea otter, hippopotamus and Ornithorhynchus or platypus</td><td>Cetaceans: whales and dolphins; a mistaken sirenian list containing seals, sea lions and sea cows</td></tr></tbody></table>" +
                "<p><strong>Source correction:</strong> seals and sea lions are pinnipeds within Carnivora, not sirenians. Sirenians include manatees and dugongs, commonly called sea cows. Cetaceans and living sirenians are fully aquatic; seals and sea lions commonly haul out. Penguins still come ashore or onto ice to breed, and sea turtles generally lay eggs on land. Thus 'aquatic' in this comparison does not always mean incapable of terrestrial activity.</p>" +
                "<p>Several adaptations recur independently: a streamlined outline, reduced external neck, modified limbs and nostrils capable of closure. Upward or dorsal nostril placement is especially pronounced in some lineages, not identical in every example.</p>"
        },
        {
            id: "aquatic-locomotion-and-insulation",
            title: "Paddles, tails, blubber and echolocation",
            sources: [{ document: "biology", page: 154 }, { document: "biology", page: 156 }],
            html: "<table><thead><tr><th>Source feature</th><th>Checked function and limitation</th></tr></thead><tbody><tr><td>Webbed feet, flippers or paddles</td><td>Increase or shape propulsive and control surfaces; turtles are the source's oar-propulsion example</td></tr><tr><td>Tail propulsion</td><td>Whales and dolphins use dorsoventral movement of horizontal flukes</td></tr><tr><td>Seals and sea lions</td><td>The source places them under tail propulsion, but sea lions mainly use foreflippers and true seals mainly use hindflippers with body movement</td></tr><tr><td>Reduced hair</td><td>Marked in cetaceans; not universal among aquatic mammals, since otters and pinnipeds retain substantial fur</td></tr><tr><td>Blubber</td><td>Subcutaneous fat provides insulation, an energy reserve and buoyancy effects in many marine mammals</td></tr><tr><td>Echolocation</td><td>Sound production and analysis of echoes support navigation or prey detection in toothed whales and many bats</td></tr></tbody></table>" +
                "<p><strong>Source correction:</strong> the oar-versus-tail table labels oar propulsion more powerful and tail propulsion less powerful without specifying force, speed or efficiency. No universal ranking follows. Turtle limbs need not all be equal-sized, and marine turtles can use flipper strokes resembling underwater flight rather than simple rowing.</p>" +
                "<p>Blubber is living fat tissue, not merely emergency food, and fur can provide an alternative insulation strategy. Echolocation is not present in every aquatic mammal or every bat. The source's bat &rarr; ultrasound &rarr; echolocation shorthand is useful for many echolocating bats, but flying foxes of the genus Pteropus do not use the typical laryngeal echolocation of many other bats.</p>"
        },
        {
            id: "aquatic-invertebrate-adaptations",
            title: "Aquatic invertebrates and protists: all locomotor and respiratory entries",
            sources: [{ document: "biology", page: 154 }],
            html: "<table><thead><tr><th>Source group</th><th>Named structure and role</th></tr></thead><tbody><tr><td>Protozoans</td><td>Cilia, flagella or pseudopodia provide different locomotor mechanisms; freshwater forms often use contractile vacuoles for water balance</td></tr><tr><td>Porifera</td><td>Flagellated or ciliated larval surfaces permit free-swimming dispersal before settlement; adults are generally sessile</td></tr><tr><td>Coelenterates or Cnidaria</td><td>Tentacles are characteristic of polyps and medusae for capture and interaction with the surroundings</td></tr><tr><td>Marine polychaete annelids</td><td>Parapodia in Nereis assist locomotion and can contribute to gas exchange</td></tr><tr><td>Crustacean arthropods</td><td>Abdominal appendages such as pleopods can function in swimming</td></tr><tr><td>Echinoderms</td><td>Skin gills or papulae in sea stars and peristomial gills in some sea urchins contribute to respiration; tube feet contribute to locomotion and other functions</td></tr></tbody></table>" +
                "<p><strong>Source correction:</strong> 'tentacles in polyp larva' conflates a polyp body form with a larval stage; a planula is typically ciliated rather than a miniature tentacled polyp. Echinoderm respiratory structures differ among classes, so each listed type must not be assigned to every echinoderm. The source's old Protozoa grouping is retained as a teaching category, not a claim that all protists are animals.</p>"
        },
        {
            id: "cursorial-adaptations",
            title: "Cursorial locomotion, foot posture and reduced digits",
            sources: [{ document: "biology", page: 154 }],
            html: "<p>Cursorial means adapted for running. The source's broad terrestrial inventory lists lizards, snakes and dinosaurs; emus, ostriches and rheas; kangaroos, hares, rabbits, zebras, dogs, cats and horses; and cockroaches, spiders, centipedes and millipedes. These are not all equivalent specialized runners. Snakes move without limbs, and kangaroos, hares and rabbits prominently use hopping or bounding, often described as saltatorial locomotion.</p>" +
                "<p>The source features are a streamlined or spindle-like outline, powerful hindlimbs, reduced digits, reduction of fibula and ulna, and a long balancing tail or tail used as a third support. These are lineage-specific combinations. Bipedality means locomotion on two limbs, not loss of digits; a human remains bipedal with five toes, and a running quadruped can have reduced toes.</p>" +
                "<table><thead><tr><th>Foot posture</th><th>Contact with ground</th><th>Source examples</th></tr></thead><tbody><tr><td>Plantigrade</td><td>Much of the sole, including the heel, bears weight; 'palm' is not the precise term for a hindfoot</td><td>Bear, raccoon, baboon and human</td></tr><tr><td>Digitigrade</td><td>Weight borne on digits with the heel raised</td><td>Dogs; many birds and theropod dinosaurs, not every dinosaur</td></tr><tr><td>Unguligrade</td><td>Weight borne mainly on terminal digits enclosed by hooves</td><td>Hoofed mammals in the next comparison</td></tr></tbody></table>" +
                "<table><thead><tr><th>Source hoof group</th><th>Examples and qualification</th></tr></thead><tbody><tr><td>Artiodactyla, even-toed</td><td>Cow, pig and buffalo; the functional axis lies between the third and fourth digits, with other digits reduced to differing degrees</td></tr><tr><td>Perissodactyla, odd-toed</td><td>Horse and rhinoceros; the third digit is the main axis. A simple count of one or three fits these examples but is not the whole classification</td></tr></tbody></table>" +
                "<p><strong>Source correction:</strong> hooves are specialized keratinized coverings, not just ordinary nails. Fibula or ulna reduction and longer hindlimbs are not mandatory in every cursorial species. The source's tail-as-third-limb phrase is especially relevant to particular support patterns such as in kangaroos, not all runners.</p>"
        },
        {
            id: "arboreal-and-climbing-adaptations",
            title: "Arboreal, scansorial and wall-climbing examples",
            sources: [{ document: "biology", page: 154 }, { document: "biology", page: 155 }, { document: "biology", page: 156 }],
            html: "<p>Arboreal means tree-dwelling; scansorial refers to climbing, including trunks, rocks or walls. Tail balancing can stabilize movement on narrow supports, whereas a prehensile tail can grasp a support. These are different functions.</p>" +
                "<table><thead><tr><th>Source example</th><th>Adaptation and correction</th></tr></thead><tbody><tr><td>Climbing perch, Anabas</td><td>Can move over wet ground and tolerate air exposure; its common name does not establish routine tree-climbing as an arboreal specialist</td></tr><tr><td>Tree frog, Hyla</td><td>Adhesive toe pads assist attachment</td></tr><tr><td>Chameleon</td><td>Opposing digit bundles and a prehensile tail assist grasping; a long protrusible tongue is a feeding adaptation, not a climbing organ</td></tr><tr><td>Geckos, wall lizards, Hemidactylus</td><td>Adhesive toe structures allow attachment; the microscopic setae of many geckos act through close-contact surface forces, not suction or a vacuum</td></tr><tr><td>Tree snakes</td><td>Body and muscular control permit climbing without digits</td></tr><tr><td>Parrot and woodpecker</td><td>Grasping feet; a parrot can also use its beak in climbing, and woodpecker tail feathers can brace against a trunk</td></tr><tr><td>Cormorant</td><td>Listed among climbing birds, but is principally a swimming and diving bird, not a standard zygodactyl climber</td></tr><tr><td>Tree kangaroo, sloth, cats and flying squirrel</td><td>Different climbing specializations rather than one shared fused-digit pattern</td></tr><tr><td>Monkeys</td><td>Some New World monkeys have prehensile tails, not all monkeys and not all New World species</td></tr></tbody></table>" +
                "<p>Zygodactyly means two toes directed forward and two backward, typically digits II and III forward and I and IV backward in the examples. It is more precise than saying merely that the fourth toe can move backward. Syndactyly means fusion or close union of digits; it is not a universal adaptation of climbing mammals. The source's general statement 'syndactyl digits with claws' therefore needs lineage-specific interpretation.</p>" +
                "<p>Page 155 contrasts terrestrio-arboreal animals, described as nesting in trees but feeding on the ground, with true tree dwellers. It lists sloth, bear, tiger and flying squirrel in the first set and squirrels, marsupials, lemurs and chameleons in the second. <strong>Source correction:</strong> this partition is overbroad: sloths and flying squirrels are strongly arboreal, tigers are primarily terrestrial, and not all marsupials are tree dwellers. The useful categories are degree and kind of tree use, not these universal species assignments. 'Branch runners' and 'prehensile tail' likewise describe some, not every, arboreal animal.</p>"
        },
        {
            id: "gliding-and-powered-flight",
            title: "Gliding versus powered flight",
            sources: [{ document: "biology", page: 155 }],
            html: "<p>The source distinguishes gliding or passive flight from true or active flight. A glider uses an aerodynamic surface and gravitational potential energy or rising air to move through the air without sustained flapping propulsion. Its launch and control still require muscle activity, so 'no locomotive power from the body' is an oversimplification.</p>" +
                "<table><thead><tr><th>Named example</th><th>Mode and structure</th></tr></thead><tbody><tr><td>Exocoetus, flying fish</td><td>Glides with enlarged fins after a powered launch from water</td></tr><tr><td>Rhacophorus, flying frog</td><td>Glides or parachutes using expanded webbing and body surfaces</td></tr><tr><td>Draco, flying lizard</td><td>Glides using a membrane supported by elongated ribs</td></tr><tr><td>Pteropus, flying fox</td><td>A bat capable of powered flight, incorrectly placed in the source's glider list</td></tr><tr><td>Bats, insects and birds</td><td>Powered flight occurs in these groups, but not every species in each group flies</td></tr></tbody></table>" +
                "<p><strong>Source correction:</strong> a flying fox is not a flying squirrel. Flying squirrels glide, while Pteropus uses flapping wings. Bird and bat wings are modified forelimbs, whereas insect wings have a different origin. The source's detailed feathered-body list in the following section applies to birds, not all flying animals.</p>"
        },
        {
            id: "avian-flight-structure",
            title: "Avian flight adaptations: feathers, skeleton and muscles",
            sources: [{ document: "biology", page: 155 }, { document: "biology", page: 156 }],
            html: "<table><thead><tr><th>Source feature</th><th>Function or identity</th></tr></thead><tbody><tr><td>Body shape</td><td>A relatively streamlined outline helps manage aerodynamic drag</td></tr><tr><td>Forelimbs</td><td>Modified into wings</td></tr><tr><td>Down feathers</td><td>Insulation and warmth</td></tr><tr><td>Wing flight feathers</td><td>Remiges</td></tr><tr><td>Tail flight feathers</td><td>Rectrices; contribute to control and other functions</td></tr><tr><td>Hindlimbs</td><td>Support, launch, landing and perching or other locomotor tasks; claws and position vary by ecology</td></tr><tr><td>Beak</td><td>Keratin-covered jaw structure; living birds lack teeth</td></tr><tr><td>Pneumatic bones</td><td>Air-containing spaces in many bones; not every bone or every bird has identical pneumatization</td></tr><tr><td>Pygostyle</td><td>Fused terminal caudal vertebrae supporting tail structures</td></tr><tr><td>Furcula</td><td>Fused clavicles</td></tr><tr><td>Sternal keel</td><td>Large attachment area for flight muscles in many birds</td></tr><tr><td>Pectoral muscles</td><td>Powerful muscles drive wing motion</td></tr><tr><td>Syrinx</td><td>The characteristic avian sound-producing organ named in the final recap</td></tr></tbody></table>" +
                "<p>The source describes a short tail, a small light skull and uncinate processes. The bony tail is shortened in modern birds even when tail feathers are long. Uncinate processes project from ribs and support thoracic mechanics; calling them simply flat flight-muscle attachment plates is incomplete. Feathers are epidermal derivatives, not the entire avian exoskeleton in the sense of an arthropod cuticle.</p>" +
                "<p><strong>Source qualification:</strong> flightless birds do not all retain the same keel or bone pattern as flying birds, and some diving birds have relatively dense bones. Each feature should be linked to its function and lineage rather than treated as an exceptionless checklist for anything airborne.</p>"
        },
        {
            id: "avian-flight-physiology",
            title: "Avian physiology: corrected ovary, aorta, respiration and vision",
            sources: [{ document: "biology", page: 155 }],
            html: "<p>The source lists a high metabolic rate, high oxygen-transport capacity, rapid respiration, compact relatively rigid lungs with air sacs, large eyes and optic lobes, and a well-developed cerebellum. These support sustained activity, sensory processing and coordination. Air sacs ventilate the lungs and help maintain airflow; the principal gas-exchange surfaces are in the lungs, not the air sacs.</p>" +
                "<table><thead><tr><th>Source statement</th><th>Corrected interpretation</th></tr></thead><tbody><tr><td>High haemoglobin percentage</td><td>A broad oxygen-transport association, not a supplied universal concentration</td></tr><tr><td>Eyes have 'pectin'</td><td>The structure is the pecten oculi, a vascular ocular structure, not the plant polysaccharide pectin</td></tr><tr><td>Monocular vision</td><td>Many birds have broad lateral fields; binocular overlap varies and is pronounced in some groups, so vision is not exclusively monocular</td></tr><tr><td>Only one right ovary; no left ovary</td><td>Reversed: most female birds have the left ovary and oviduct functional, with exceptions</td></tr><tr><td>Only left systemic artery; no right systemic aorta</td><td>Reversed: birds retain the right systemic aortic arch; mammals retain the left</td></tr><tr><td>Body temperature 46 degrees C</td><td>Not a universal normal value; many birds normally maintain roughly 40-42 degrees C, with species and activity variation</td></tr><tr><td>No urinary bladder; uricotelic</td><td>Generally correct for birds: nitrogen is excreted mainly as urates with relatively little water. The source also notes absence of a urinary bladder in crocodilians and snakes</td></tr></tbody></table>" +
                "<p><strong>Source correction:</strong> high metabolism does not make a fixed temperature of 46 degrees C normal for every bird. Anatomical side labels are especially important: functional left female reproductive organs and a right aortic arch must not be swapped to match the handwriting.</p>"
        },
        {
            id: "desert-adaptations",
            title: "Desert life: water conservation, protective structures and camel myth",
            sources: [{ document: "biology", page: 155 }, { document: "biology", page: 156 }],
            html: "<p>Xerocoles are desert-dwelling animals, while xerophytes are plants adapted to dry conditions. Xeric describes a dry environment. The source groups the following water-conserving and protective traits together, but not every desert species has every trait.</p>" +
                "<table><thead><tr><th>Source entry</th><th>Functional reading and limit</th></tr></thead><tbody><tr><td>Thick, tough or rough skin</td><td>Surface barriers can reduce evaporative water loss; 'avoid precipitation' is a misuse of the word and should refer to water loss or perspiration where relevant</td></tr><tr><td>Few sweat glands</td><td>Reduced sweating can conserve water in some mammals, but heat dissipation involves trade-offs and species differ</td></tr><tr><td>Venomous spines or poison glands</td><td>Defensive structures in certain animals, not universal desert or water-saving traits</td></tr><tr><td>Hygroscopic lizard skin</td><td>Some specialized lizards channel collected water across patterned scales toward the mouth; not all desert lizards absorb atmospheric water through ordinary skin</td></tr><tr><td>Colour matched to surroundings</td><td>Camouflage can reduce detection; colour may also have thermal or signalling roles</td></tr><tr><td>Developed sight, hearing and smell</td><td>Sensory adaptations depend on activity and ecology, not a universal enhancement of all senses</td></tr><tr><td>Protective eyelids</td><td>Structures around eyes can reduce sand injury; enlarged eyelids alone are not a defining desert character</td></tr><tr><td>Concentrated urine</td><td>Many desert mammals conserve water through renal concentration; desert reptiles and arthropods use different excretory strategies</td></tr></tbody></table>" +
                "<p><strong>Source correction:</strong> both pages assert that a camel stores water in special 'water cells' in a stomach rumen. Camels do not have a separate reservoir of drinking water in such cells, and their three-compartment foregut is not the same as a ruminant's four-compartment stomach. Foregut glandular sacs are not water tanks. Their survival involves integrated water conservation and tolerance of dehydration. The hump stores fat, not liquid water; metabolism of reserves can contribute water without making the hump a water container.</p>"
        },
        {
            id: "parasitic-and-fossorial-adaptations",
            title: "Parasitic and burrowing adaptations",
            sources: [{ document: "biology", page: 155 }],
            html: "<p>Ectoparasites live on a host's surface; the source notes sucking mechanisms, although attachment and feeding structures vary. Endoparasites live inside a host. The named example Ascaris has a muscular pumping pharynx and a digestive tract.</p>" +
                "<table><thead><tr><th>Parasitic feature listed</th><th>Qualification</th></tr></thead><tbody><tr><td>Anaerobic respiration</td><td>Low-oxygen metabolism is important in many intestinal parasites, but not all parasites or all life stages use one metabolic mode</td></tr><tr><td>Reduced sense organs and nervous system</td><td>Can accompany life in a comparatively stable host environment; degree of reduction varies</td></tr><tr><td>High reproductive capacity</td><td>Can compensate for low probability of transmission to another host</td></tr><tr><td>Absorption through general body surface</td><td>Important in parasites such as tapeworms, not a universal substitute for an intestine in Ascaris</td></tr><tr><td>Protective cuticle</td><td>Helps nematodes resist the host environment; other parasite groups have different coverings, such as a tegument</td></tr></tbody></table>" +
                "<p>Fossorial means adapted to digging or burrowing. The source's body-shape examples are cylindrical Ichthyophis, a caecilian amphibian, and burrowing snakes, contrasted with the compact spindle-like mole. A tapering snout helps entry through substrate, and powerful clawed forelimbs are useful in limb-bearing diggers.</p>" +
                "<p><strong>Source correction:</strong> limbless caecilians and snakes cannot have the same powerful forelimb adaptation as a mole. The source's 'hibernate in winter' is not a necessary property of burrowers; many moles remain active through winter, and dormancy depends on species and climate.</p>"
        },
        {
            id: "integument-and-recap",
            title: "Integument and final source recap",
            sources: [{ document: "biology", page: 156 }],
            html: "<p>A rabbit's claw is a keratinized epidermal derivative. The source calls a rhinoceros horn matted hair. <strong>Source correction:</strong> a rhinoceros horn is a keratin-rich structure with specialized organization, not a bundle of ordinary hairs glued together, and it lacks the bony core of a typical bovid horn.</p>" +
                "<p>The remaining recap associations are tail as an arboreal balancer; ultrasonic echolocation in many bats; ethology for animal behaviour; syrinx for avian sound production; prehensile tails in some New World monkeys and chameleons; lateral-line sensing of water movement; and Paramecium orientation to electric fields. Each is explained in its relevant source-linked section with its conditions retained. The repeated camel water-cell claim is explicitly corrected in the desert section, not silently copied as fact.</p>"
        }
    ],
    pageCoverage: [
        { document: "biology", page: 150, status: "transcribed", sectionIds: ["behaviour-innate-and-learned", "reflex-arc-and-types", "orientation-taxis-kinesis"], unresolved: [] },
        { document: "biology", page: 151, status: "partial", sectionIds: ["behaviour-innate-and-learned", "orientation-taxis-kinesis", "stimulus-taxis-table", "orientation-mechanisms", "leadership-and-dominance"], unresolved: ["Left taxis table, rheotaxis row: butterfly is placed in the positive column without a specified wind/current direction or experimental condition. Its intended signed response cannot be recovered and is not scored."] },
        { document: "biology", page: 152, status: "partial", sectionIds: ["migration-and-fish-types", "fish-migration-directions-and-purposes", "bird-migration-patterns"], unresolved: ["Upper-right latitudinal fish-migration list: the name before Sword Fish resembles 'Bracadas' or barracuda but is not reliably spelled; no species identity is inferred.", "Right bird-migration list: 'B & W cuckoos' is an abbreviated common-name entry without a species or expanded name. The abbreviation is retained but not scored."] },
        { document: "biology", page: 153, status: "transcribed", sectionIds: ["behaviour-innate-and-learned", "bird-migration-patterns", "migration-cues-and-records", "adaptation-and-evolutionary-patterns", "primary-aquatic-adaptations", "aquatic-osmoregulation"], unresolved: [] },
        { document: "biology", page: 154, status: "transcribed", sectionIds: ["aquatic-osmoregulation", "secondary-aquatic-inventory", "aquatic-locomotion-and-insulation", "aquatic-invertebrate-adaptations", "cursorial-adaptations", "arboreal-and-climbing-adaptations"], unresolved: [] },
        { document: "biology", page: 155, status: "transcribed", sectionIds: ["arboreal-and-climbing-adaptations", "gliding-and-powered-flight", "avian-flight-structure", "avian-flight-physiology", "desert-adaptations", "parasitic-and-fossorial-adaptations"], unresolved: [] },
        { document: "biology", page: 156, status: "transcribed", sectionIds: ["behaviour-innate-and-learned", "stimulus-taxis-table", "primary-aquatic-adaptations", "aquatic-locomotion-and-insulation", "arboreal-and-climbing-adaptations", "avian-flight-structure", "desert-adaptations", "integument-and-recap"], unresolved: [] }
    ],
    questions: [
        {
            id: "note-adaptation-001", text: "Which discipline directly investigates the courtship, orientation and social interactions grouped on the source pages?",
            options: [{ key: "a", text: "Histology" }, { key: "b", text: "Etiology" }, { key: "c", text: "Ethology" }, { key: "d", text: "Embryology" }], answer: "c",
            explanation: "Ethology studies animal behaviour, including courtship, movement responses and social interactions. Histology studies tissues, etiology causes of disease, and embryology development. Biology pp. 150 and 156 explicitly identify ethology.", sectionId: "behaviour-innate-and-learned", source: { document: "biology", page: 150 }, cognitive: "recall"
        },
        {
            id: "note-adaptation-002", text: "In the illustrated reflex arc, which component carries information from the receptor toward the central integrating region?",
            options: [{ key: "a", text: "Afferent neuron" }, { key: "b", text: "Efferent neuron" }, { key: "c", text: "Effector muscle" }, { key: "d", text: "Secretory gland" }], answer: "a",
            explanation: "Afferent or sensory neurons carry receptor information toward the CNS. Efferent neurons carry outgoing instructions to effectors such as muscles and glands. The directional arrows and five-stage sequence on Biology p. 150 make this distinction explicit.", sectionId: "reflex-arc-and-types", source: { document: "biology", page: 150 }, cognitive: "recall"
        },
        {
            id: "note-adaptation-003", text: "A bell that initially produces no salivation is repeatedly paired with food and later elicits salivation alone. What has the bell become?",
            options: [{ key: "a", text: "An unconditioned response" }, { key: "b", text: "A motor effector" }, { key: "c", text: "An unconditioned food stimulus" }, { key: "d", text: "A conditioned stimulus" }], answer: "d",
            explanation: "Through association with food, the initially neutral bell becomes a conditioned stimulus. Salivation to it is the conditioned response; the bell is neither the response nor the effector. Biology p. 150 gives the dog-and-bell example.", sectionId: "reflex-arc-and-types", source: { document: "biology", page: 150 }, cognitive: "application"
        },
        {
            id: "note-adaptation-004", text: "An animal changes its random walking speed as humidity changes, without steering toward either end of the humidity gradient. Which response category fits?",
            options: [{ key: "a", text: "Positive taxis" }, { key: "b", text: "Kinesis" }, { key: "c", text: "Negative tropism" }, { key: "d", text: "Menotaxis" }], answer: "b",
            explanation: "Kinesis is a nondirectional change in activity or turning with stimulus intensity. The stated lack of directional steering distinguishes it from taxis. This constructed example applies the explicit kinesis definition on Biology p. 150 without relying on the source's ambiguous Hydra example.", sectionId: "orientation-taxis-kinesis", source: { document: "biology", page: 150 }, cognitive: "application"
        },
        {
            id: "note-adaptation-005", text: "A bacterium biases its movement toward a suitable nutrient concentration. Which source term classifies the cue involved?",
            options: [{ key: "a", text: "Geotaxis" }, { key: "b", text: "Chemotaxis" }, { key: "c", text: "Phototaxis" }, { key: "d", text: "Galvanotaxis" }], answer: "b",
            explanation: "A nutrient concentration is a chemical cue, so directed movement relative to it is chemotaxis. The response is positive for the suitable attractant described, but would not necessarily remain positive at every concentration. Biology p. 151 lists bacteria moving toward food under chemotaxis.", sectionId: "stimulus-taxis-table", source: { document: "biology", page: 151 }, cognitive: "understanding"
        },
        {
            id: "note-adaptation-006", text: "A fish faces and swims against an oncoming water current. Under the conventional rheotaxis definition, this is which response?",
            options: [{ key: "a", text: "Negative rheotaxis" }, { key: "b", text: "Positive phototaxis" }, { key: "c", text: "Negative geotaxis" }, { key: "d", text: "Positive rheotaxis" }], answer: "d",
            explanation: "Orientation against an oncoming water current is conventionally called positive rheotaxis. The source's negative-column placement of upstream fishes is misleading. Biology p. 151 supplies the current-response comparison, with the sign convention explicitly corrected in the typed section.", sectionId: "stimulus-taxis-table", source: { document: "biology", page: 151 }, cognitive: "understanding"
        },
        {
            id: "note-adaptation-007", text: "An organism compares stimulus intensity successively while sweeping its body and adjusts its path after each sample. Which orientation mechanism is illustrated?",
            options: [{ key: "a", text: "Klinotaxis" }, { key: "b", text: "Tropotaxis" }, { key: "c", text: "Telotaxis" }, { key: "d", text: "Mnemotaxis" }], answer: "a",
            explanation: "Klinotaxis uses successive sampling over time, often with sweeping or changes of heading. Tropotaxis instead compares inputs from spatially separated receptors simultaneously. Biology p. 151 describes these contrasting orientation mechanisms.", sectionId: "orientation-mechanisms", source: { document: "biology", page: 151 }, cognitive: "understanding"
        },
        {
            id: "note-adaptation-008", text: "A navigating insect keeps a constant angular bearing relative to sunlight rather than flying directly toward the sun. Which term fits?",
            options: [{ key: "a", text: "Kinesis" }, { key: "b", text: "Telotaxis" }, { key: "c", text: "Menotaxis" }, { key: "d", text: "Tropotaxis" }], answer: "c",
            explanation: "Menotaxis is orientation at a maintained angle to a reference cue, illustrated by a light-compass response. Keeping a bearing differs from simply approaching the light source. Ants and bees using sunlight are the source examples on Biology p. 151.", sectionId: "orientation-mechanisms", source: { document: "biology", page: 151 }, cognitive: "application"
        },
        {
            id: "note-adaptation-009", text: "A wasp returns to a nest by recognizing previously learned nearby landmarks. Which source mechanism most directly explains this return?",
            options: [{ key: "a", text: "Galvanotaxis" }, { key: "b", text: "Thermotaxis" }, { key: "c", text: "Telotaxis" }, { key: "d", text: "Mnemotaxis" }], answer: "d",
            explanation: "Mnemotaxis uses remembered spatial cues such as landmarks. The key here is learned location information, not electricity, temperature or choosing one of two immediate targets. Biology p. 151 names wasps in the landmark-based orientation section.", sectionId: "orientation-mechanisms", source: { document: "biology", page: 151 }, cognitive: "application"
        },
        {
            id: "note-adaptation-010", text: "A knowledgeable group member initiates travel, although another member usually wins food contests. Which distinction best explains this observation?",
            options: [{ key: "a", text: "Leadership and dominance must always belong to one individual" }, { key: "b", text: "Influence on movement differs from priority in social contests" }, { key: "c", text: "Dominance is impossible in a group showing learned navigation" }, { key: "d", text: "The highest food rank necessarily determines all travel decisions" }], answer: "b",
            explanation: "Leadership concerns influencing or initiating group activity, while dominance concerns repeated social asymmetries and resource access. They can be held by different individuals. Biology p. 151 supplies both headings, whose overly close equation is corrected in the notes.", sectionId: "leadership-and-dominance", source: { document: "biology", page: 151 }, cognitive: "understanding"
        },
        {
            id: "note-adaptation-011", text: "A fish spends its main growth phase at sea and enters a river to spawn. Which life-history category applies?",
            options: [{ key: "a", text: "Catadromous" }, { key: "b", text: "Potamodromous" }, { key: "c", text: "Anadromous" }, { key: "d", text: "Oceanodromous" }], answer: "c",
            explanation: "Anadromous fishes move from marine feeding or growth habitat into freshwater to reproduce. Catadromy reverses the reproductive destination; potamodromy and oceanodromy remain within one salinity realm. Biology p. 152 lists salmon, sea lamprey and hilsa as anadromous examples.", sectionId: "migration-and-fish-types", source: { document: "biology", page: 152 }, cognitive: "understanding"
        },
        {
            id: "note-adaptation-012", text: "Which eel identification repairs the swapped names in the source migration table?",
            options: [{ key: "a", text: "American eel: Anguilla rostrata" }, { key: "b", text: "European eel: Anguilla rostrata" }, { key: "c", text: "American eel: Anguilla anguilla" }, { key: "d", text: "European eel: Petromyzon marinus" }], answer: "a",
            explanation: "Anguilla rostrata is the American eel; the European eel is A. anguilla, historically A. vulgaris. The source reverses their common-name associations on Biology p. 152. Both eels remain classical catadromous examples after the naming correction.", sectionId: "migration-and-fish-types", source: { document: "biology", page: 152 }, cognitive: "recall"
        },
        {
            id: "note-adaptation-013", text: "A fish migrates between feeding and spawning sites, but every site remains freshwater. Which category describes this without calling the migration false?",
            options: [{ key: "a", text: "Potamodromous" }, { key: "b", text: "Oceanodromous" }, { key: "c", text: "Catadromous" }, { key: "d", text: "Anadromous" }], answer: "a",
            explanation: "Potamodromous migration occurs entirely within freshwater. It is genuine migration, even though the source calls such fishes 'false migratory'. Biology p. 152 contrasts this category with movements between sea and freshwater and with marine-only migration.", sectionId: "migration-and-fish-types", source: { document: "biology", page: 152 }, cognitive: "application"
        },
        {
            id: "note-adaptation-014", text: "Which distinction is needed to define amphidromy more precisely than merely movement in both directions between fresh and salt water?",
            options: [{ key: "a", text: "Adults must enter freshwater specifically to deposit their eggs" }, { key: "b", text: "Adults must enter seawater specifically to deposit their eggs" }, { key: "c", text: "The habitat transfer is not primarily the adult spawning journey" }, { key: "d", text: "The habitat transfer remains entirely within marine coastal waters" }], answer: "c",
            explanation: "Amphidromous life cycles include transfers between fresh and marine waters not primarily as the adult spawning migration itself. The distinction prevents overlap with anadromy and catadromy based only on two-way movement. Biology p. 152 supplies the goby example and the incomplete directional definition.", sectionId: "migration-and-fish-types", source: { document: "biology", page: 152 }, cognitive: "understanding"
        },
        {
            id: "note-adaptation-015", text: "Birds move from high mountain breeding sites to lower valleys as the cold season arrives. Which spatial migration category fits this observation?",
            options: [{ key: "a", text: "Longitudinal migration" }, { key: "b", text: "Altitudinal migration" }, { key: "c", text: "Oceanodromous migration" }, { key: "d", text: "Daily roost commuting" }], answer: "b",
            explanation: "Movement between higher and lower elevations is altitudinal or vertical migration. It need not involve a major east-west shift or remain an ordinary daily commute. Biology p. 152 explicitly describes movement along slopes between hills and mountains.", sectionId: "bird-migration-patterns", source: { document: "biology", page: 152 }, cognitive: "application"
        },
        {
            id: "note-adaptation-016", text: "A typical freshwater teleost continually gains water by osmosis. Which response combination best offsets its water and salt problem?",
            options: [{ key: "a", text: "Drink seawater and excrete salt at the gills" }, { key: "b", text: "Retain all incoming water and stop ion uptake" }, { key: "c", text: "Produce little concentrated urine and release ions" }, { key: "d", text: "Produce dilute urine and actively absorb ions" }], answer: "d",
            explanation: "Freshwater teleost body fluids are more concentrated than the environment, so water enters while ions tend to be lost. Dilute urine removes excess water and active gill uptake replaces ions. Biology p. 153 supplies the freshwater salt-absorbing-cell entry, with the mistaken isotonic claim corrected.", sectionId: "aquatic-osmoregulation", source: { document: "biology", page: 153 }, cognitive: "application"
        },
        {
            id: "note-adaptation-017", text: "Which fish system detects nearby water movement and pressure disturbances in the source's sensory comparison?",
            options: [{ key: "a", text: "Swim bladder" }, { key: "b", text: "Mucous gland" }, { key: "c", text: "Lateral line" }, { key: "d", text: "Gill ionocyte" }], answer: "c",
            explanation: "The lateral line is a mechanosensory system that detects water movement and pressure changes. A swim bladder primarily concerns buoyancy, mucus protects the surface, and ionocytes regulate ions. Biology pp. 153 and 156 associate the lateral line with a current or rheoreceptor function.", sectionId: "primary-aquatic-adaptations", source: { document: "biology", page: 156 }, cognitive: "recall"
        },
        {
            id: "note-adaptation-018", text: "Which rearrangement corrects the source's aquatic-mammal classification?",
            options: [{ key: "a", text: "Place dolphins with sirenians and dugongs with pinnipeds" }, { key: "b", text: "Place seals with cetaceans and whales with sea otters" }, { key: "c", text: "Place sea lions with monotremes and platypuses with cetaceans" }, { key: "d", text: "Place seals with pinnipeds and sea cows with sirenians" }], answer: "d",
            explanation: "Seals and sea lions are pinnipeds, while manatees and dugongs are sirenians. Whales and dolphins are cetaceans. Biology p. 154 incorrectly groups seals and sea lions under sirenians; the corrected inventory preserves the examples without preserving the false classification.", sectionId: "secondary-aquatic-inventory", source: { document: "biology", page: 154 }, cognitive: "understanding"
        },
        {
            id: "note-adaptation-019", text: "Which set of functions matches the source's blubber entry in marine mammals?",
            options: [{ key: "a", text: "Insulation, energy storage and buoyancy effects" }, { key: "b", text: "Insulation, food digestion and salt excretion" }, { key: "c", text: "Buoyancy, oxygen storage and sound generation" }, { key: "d", text: "Energy storage, ion secretion and water absorption" }], answer: "a",
            explanation: "Blubber is subcutaneous fat that can insulate, store energy and influence buoyancy. Its roles are not the functions of gills or specialized sensory organs. Biology p. 154 lists these three functional associations, qualified because some aquatic mammals rely heavily on fur instead.", sectionId: "aquatic-locomotion-and-insulation", source: { document: "biology", page: 154 }, cognitive: "recall"
        },
        {
            id: "note-adaptation-020", text: "Which source example has the whole sole, including the heel, participating in the usual ground-contact posture?",
            options: [{ key: "a", text: "A digitigrade dog" }, { key: "b", text: "A plantigrade bear" }, { key: "c", text: "An unguligrade horse" }, { key: "d", text: "An unguligrade cow" }], answer: "b",
            explanation: "Plantigrade posture places much of the sole and heel on the ground. Digitigrade animals raise the heel and bear weight on digits, while unguligrade animals bear weight through hoofed digit tips. Biology p. 154 lists bears among the plantigrade examples.", sectionId: "cursorial-adaptations", source: { document: "biology", page: 154 }, cognitive: "recall"
        },
        {
            id: "note-adaptation-021", text: "A hoofed mammal bears weight mainly through the terminal parts of its digits. What is the foot-posture term?",
            options: [{ key: "a", text: "Plantigrade" }, { key: "b", text: "Digitigrade" }, { key: "c", text: "Palmigrade" }, { key: "d", text: "Unguligrade" }], answer: "d",
            explanation: "Unguligrade posture concentrates support on hoof-enclosed terminal digits. The source distinguishes it from plantigrade whole-sole contact and digitigrade contact on the digits without the same hoof-tip specialization. Biology p. 154 supplies the posture table.", sectionId: "cursorial-adaptations", source: { document: "biology", page: 154 }, cognitive: "recall"
        },
        {
            id: "note-adaptation-022", text: "What mechanism corrects the source's claim that a wall-climbing gecko adheres by creating a vacuum under its toes?",
            options: [{ key: "a", text: "A sticky secretion deposited by glands under the toes" }, { key: "b", text: "Interlocking claws as the sole grip on smooth glass" }, { key: "c", text: "Close-contact adhesion from microscopic toe setae" }, { key: "d", text: "Pressure reduction inside sealed toe-pad chambers" }], answer: "c",
            explanation: "Many geckos use arrays of microscopic setae that create close-contact adhesive forces with a surface. They do not rely on a vacuum or a blood-powered suction cup. Biology pp. 154-155 name geckos and Hemidactylus, with the vacuum explanation explicitly corrected.", sectionId: "arboreal-and-climbing-adaptations", source: { document: "biology", page: 154 }, cognitive: "understanding"
        },
        {
            id: "note-adaptation-023", text: "Which source example must be moved from the gliding list to powered flight?",
            options: [{ key: "a", text: "Draco, flying lizard" }, { key: "b", text: "Pteropus, flying fox" }, { key: "c", text: "Exocoetus, flying fish" }, { key: "d", text: "Rhacophorus, flying frog" }], answer: "b",
            explanation: "Pteropus is a bat that flies using powered wingbeats. Draco, Exocoetus and Rhacophorus are standard gliding or parachuting examples in this comparison. Biology p. 155 incorrectly puts the flying fox beside gliders; it must not be confused with a flying squirrel.", sectionId: "gliding-and-powered-flight", source: { document: "biology", page: 155 }, cognitive: "recall"
        },
        {
            id: "note-adaptation-024", text: "Which pairing correctly names the principal quill-feather groups on a bird's wing and tail?",
            options: [{ key: "a", text: "Wing: remiges; tail: rectrices" }, { key: "b", text: "Wing: rectrices; tail: remiges" }, { key: "c", text: "Wing: down; tail: remiges" }, { key: "d", text: "Wing: rectrices; tail: down" }], answer: "a",
            explanation: "Remiges are wing flight feathers and rectrices are tail flight feathers. Down feathers are primarily insulating rather than the stiff quill feathers in this pairing. Biology p. 155 explicitly labels all three types.", sectionId: "avian-flight-structure", source: { document: "biology", page: 155 }, cognitive: "recall"
        },
        {
            id: "note-adaptation-025", text: "Which combination repairs both left-right reversals in the source's avian physiology notes?",
            options: [{ key: "a", text: "Right ovary usually functional; left aortic arch retained" }, { key: "b", text: "Right ovary usually functional; right aortic arch retained" }, { key: "c", text: "Left ovary usually functional; right aortic arch retained" }, { key: "d", text: "Left ovary usually functional; left aortic arch retained" }], answer: "c",
            explanation: "Most female birds retain functional left reproductive organs, while birds retain the right systemic aortic arch. The source reverses each side on Biology p. 155. These are independent anatomical distinctions, not a rule that every retained structure must be on one side.", sectionId: "avian-flight-physiology", source: { document: "biology", page: 155 }, cognitive: "recall"
        },
        {
            id: "note-adaptation-026", text: "A bird's air sacs are functioning normally. What is their main respiratory contribution compared with the lung's exchange surfaces?",
            options: [{ key: "a", text: "They replace lungs as the principal exchange surfaces" }, { key: "b", text: "They help ventilate the relatively rigid lungs" }, { key: "c", text: "They inflate alveoli by stretching the lung tissue" }, { key: "d", text: "They prevent fresh air from entering during expiration" }], answer: "b",
            explanation: "Air sacs act mainly in ventilation, moving air through the avian respiratory system, while the lung provides the principal exchange surfaces. Biology p. 155 pairs relatively inelastic lungs with air sacs; the typed section explains the functional division without calling air sacs the lungs themselves.", sectionId: "avian-flight-physiology", source: { document: "biology", page: 155 }, cognitive: "understanding"
        },
        {
            id: "note-adaptation-027", text: "Which statement corrects the repeated camel 'water cells' claim in the source?",
            options: [{ key: "a", text: "The hump is a separate stomach chamber filled with drinking water" }, { key: "b", text: "The foregut contains tanks that replace all kidney water regulation" }, { key: "c", text: "The stomach rumen stores pure water without any food mixing" }, { key: "d", text: "Water conservation is integrated; neither hump nor stomach is a water tank" }], answer: "d",
            explanation: "Camels conserve water through multiple physiological mechanisms rather than special tanks of stored drinking water. Their hump stores fat, and the foregut sacs are not water reservoirs. Biology pp. 155-156 repeat the misleading claim that the corrected desert section explicitly rejects.", sectionId: "desert-adaptations", source: { document: "biology", page: 156 }, cognitive: "understanding"
        },
        {
            id: "note-adaptation-028", text: "A single-celled freshwater organism expels excess incoming water through a contractile vacuole. Which function does this most directly serve?",
            options: [{ key: "a", text: "Osmoregulation" }, { key: "b", text: "Pseudopodial locomotion" }, { key: "c", text: "Flagellar propulsion" }, { key: "d", text: "External fertilization" }], answer: "a",
            explanation: "A contractile vacuole removes excess water entering a freshwater cell by osmosis, helping maintain water balance. Cilia, flagella and pseudopodia are separately listed locomotor structures. Biology p. 154 supplies this distinction among protist adaptations.", sectionId: "aquatic-osmoregulation", source: { document: "biology", page: 154 }, cognitive: "understanding"
        },
        {
            id: "note-adaptation-029", text: "Why is absorption of all food through the general body surface not a valid universal definition of endoparasitism?",
            options: [{ key: "a", text: "All endoparasitic worms ingest food only through their cuticle" }, { key: "b", text: "Some endoparasites, including Ascaris, retain a digestive tract" }, { key: "c", text: "Endoparasite intestines function only before entry into the host" }, { key: "d", text: "Every parasite pharynx attaches but never participates in feeding" }], answer: "b",
            explanation: "Endoparasitism is defined by living inside the host, not by one universal digestive arrangement. Ascaris has a muscular pharynx and intestine, whereas tapeworms absorb nutrients through their surface. Biology p. 155 puts these traits together, so the typed correction separates the examples.", sectionId: "parasitic-and-fossorial-adaptations", source: { document: "biology", page: 155 }, cognitive: "understanding"
        },
        {
            id: "note-adaptation-030", text: "Which source-defined anatomical structure is a keratinized derivative of the epidermis?",
            options: [{ key: "a", text: "A rabbit's claw" }, { key: "b", text: "A deer's bony antler" }, { key: "c", text: "A mammal's tooth dentine" }, { key: "d", text: "A fish's dermal scale plate" }], answer: "a",
            explanation: "The rabbit claw is formed by keratinization of epidermal tissue, as stated in the Biology p. 156 recap. Antler bone, tooth dentine and a dermal scale plate are not keratinized epidermal claw tissue. The neighbouring rhinoceros-horn note also concerns keratin but requires correction of the misleading matted-hair description.", sectionId: "integument-and-recap", source: { document: "biology", page: 156 }, cognitive: "recall"
        }
    ]
};