window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["alcohols"] = {
  id: "alcohols",
  subject: "Chemistry",
  title: "Alcohols, phenols and ethers",
  sections: [
    {
      id: "alkene-hydration-methods",
      title: "Alcohols from alkenes: three distinct hydration methods",
      sources: [{ document: "quick-revision", page: 79 }],
      html: "<p>The source sends three alkene-reaction branches to a common alcohol label. The carbon skeleton is retained, but the position of OH depends on the method.</p><table><thead><tr><th>Source reagents and necessary clarification</th><th>Orientation</th></tr></thead><tbody><tr><td>H<sub>2</sub>SO<sub>4</sub>/H<sub>2</sub>O; acid-catalysed hydration</td><td>Markovnikov alcohol; carbocation rearrangement is possible</td></tr><tr><td>First B<sub>2</sub>H<sub>6</sub> in THF, then H<sub>2</sub>O<sub>2</sub>/OH<sup>-</sup>; hydroboration-oxidation</td><td>Anti-Markovnikov alcohol, with overall syn addition of H and OH</td></tr><tr><td>First (CH<sub>3</sub>COO)<sub>2</sub>Hg in aqueous medium, then NaBH<sub>4</sub>/OH<sup>-</sup>; oxymercuration-demercuration</td><td>Markovnikov alcohol without the usual free-carbocation rearrangement</td></tr></tbody></table><p><strong>Source corrections:</strong> the hydroboration work-up prints H<sub>2</sub>O/OH<sup>-</sup>, omitting the peroxide required for oxidation of the carbon-boron bond. The common product label RCH<sub>2</sub>OH is too restrictive: alcohol class depends on the substrate and regiochemistry. For propene, acid hydration or oxymercuration gives propan-2-ol, whereas hydroboration-oxidation gives propan-1-ol. THF means tetrahydrofuran; diborane supplies borane in the ether medium. The listed methods are alternatives, not reagents to combine in one vessel.</p>"
    },
    {
      id: "carbonyl-to-alcohol",
      title: "Alcohols from carbonyl compounds and carboxylic acids",
      sources: [{ document: "quick-revision", page: 79 }],
      html: "<ul><li><strong>Aldehyde reduction:</strong> RCHO + 2[H] &rarr; RCH<sub>2</sub>OH. The source lists H<sub>2</sub> with Pt, Pd or Ni and labels the product a primary alcohol. Formaldehyde gives methanol, the unsubstituted limiting case.</li><li><strong>Ketone reduction:</strong> RCOR' + 2[H] &rarr; RCH(OH)R', using NaBH<sub>4</sub> or LiAlH<sub>4</sub>, followed by appropriate protonation. The product is secondary; the two R groups need not be identical.</li><li><strong>Grignard addition to a ketone:</strong> RCOR' reacts first with R''MgX in dry ether, then with H<sub>2</sub>O/H<sup>+</sup>, to give R-C(OH)(R')-R''. The former carbonyl carbon now carries three carbon groups, so the alcohol is tertiary. The acid is a later work-up, not present during Grignard addition.</li><li><strong>Carboxylic-acid reduction:</strong> RCOOH + 4[H] &rarr; RCH<sub>2</sub>OH + H<sub>2</sub>O. LiAlH<sub>4</sub> in ether followed by aqueous work-up is legible in the source. Ordinary NaBH<sub>4</sub> is not the corresponding standard reagent for a free carboxylic acid.</li></ul><p><strong>Partial source passage:</strong> the alternative borane formula beside LiAlH<sub>4</sub> in the carboxylic-acid branch has an unclear final hydrogen subscript. It is not silently transcribed as a definite reagent. Independently, BH<sub>3</sub> complexes and diborane are established borane-based acid-reduction reagents, but that scientific fact does not establish the exact printed subscript. The unclear label is excluded from scored questions.</p>"
    },
    {
      id: "alcohol-oh-cleavage",
      title: "O-H cleavage: alkoxides and acid-base reactions",
      sources: [{ document: "quick-revision", page: 79 }],
      html: "<p>The source separates O-H cleavage from C-O cleavage. In O-H deprotonation, the original carbon-oxygen bond remains intact and the alcohol becomes an alkoxide.</p><table><thead><tr><th>Source reagent</th><th>Balanced reaction or product</th></tr></thead><tbody><tr><td>Na or K</td><td>2ROH + 2M &rarr; 2ROM + H<sub>2</sub>, where M is Na or K</td></tr><tr><td>Al</td><td>6ROH + 2Al &rarr; 2Al(OR)<sub>3</sub> + 3H<sub>2</sub></td></tr><tr><td>Metal hydride MH</td><td>ROH + MH &rarr; ROM + H<sub>2</sub> for a suitable monovalent-metal hydride</td></tr><tr><td>NaNH<sub>2</sub></td><td>ROH + NaNH<sub>2</sub> &rarr; RONa + NH<sub>3</sub></td></tr><tr><td>Grignard reagent R'MgX</td><td>ROH + R'MgX &rarr; ROMgX + R'H</td></tr></tbody></table><p><strong>Source corrections:</strong> the single-alcohol metal arrows omit stoichiometric coefficients. Sodium amide produces ammonia, not hydrogen. The organomagnesium branch appears as R'MgH while the product retains MgX; the chemically consistent Grignard reagent is R'MgX. The alcohol proton quenches its carbon-metal bond to give R'H.</p><p>The source's blanket sentence linking nucleophiles to O-H cleavage and electrophiles to C-O cleavage is not a general mechanistic rule. Bases remove the O-H proton; an alcohol oxygen can itself attack an electrophile; and nucleophiles can replace an activated OH group at carbon. Identify the actual bond and reaction type rather than inferring it solely from those two labels.</p>"
    },
    {
      id: "alcohol-esters-ethers",
      title: "Alcohol esterification and O-alkylation branches",
      sources: [{ document: "quick-revision", page: 79 }],
      html: "<p>The source includes esterification in both reaction charts. The complete set is consolidated here, preserving each reagent and by-product.</p><ul><li><strong>Carboxylic acid:</strong> ROH + R'COOH &harr; R'COOR + H<sub>2</sub>O, with acid catalysis; concentrated H<sub>2</sub>SO<sub>4</sub> and heat are listed in the second chart. This is reversible esterification.</li><li><strong>Acyl chloride:</strong> ROH + R'COCl &rarr; R'COOR + HCl, with pyridine shown. Pyridine accepts the acid generated.</li><li><strong>Acid anhydride:</strong> ROH + (R'CO)<sub>2</sub>O &rarr; R'COOR + R'COOH; the source lists H<sup>+</sup>.</li><li><strong>Dialkyl sulfate:</strong> the source represents ROH + (R'O)<sub>2</sub>SO<sub>2</sub> &rarr; ROR' + R'OSO<sub>3</sub>H. The useful bond change is O-alkylation, usually facilitated by converting the alcohol to its alkoxide. The abbreviated neutral equation alone does not specify effective reaction conditions.</li><li><strong>Sulfuric-acid ester:</strong> ROH + H<sub>2</sub>SO<sub>4</sub> &harr; ROSO<sub>3</sub>H + H<sub>2</sub>O, producing an alkyl hydrogen sulfate. The source's acid label is malformed, but the drawn RO-SO<sub>2</sub>OH product requires sulfuric acid.</li><li><strong>Nitric-acid ester:</strong> ROH + HNO<sub>3</sub> &harr; RONO<sub>2</sub> + H<sub>2</sub>O, an alkyl nitrate. The oxygen link R-O-N distinguishes a nitrate ester from a nitroalkane R-NO<sub>2</sub>.</li></ul><p><strong>Source classification correction:</strong> ordinary Fischer esterification normally preserves the alcohol's alkyl C-O bond. Including its arrow among all C-O-cleavage reactions is misleading. These equations describe functional-group changes, not safe preparation protocols; reactive alkylating and nitrating reagents require controlled professional handling.</p>"
    },
    {
      id: "alcohol-halogenation-dehydration",
      title: "Replacement of OH and dehydration",
      sources: [{ document: "quick-revision", page: 79 }],
      html: "<table><thead><tr><th>Reagents in the source</th><th>Transformation</th></tr></thead><tbody><tr><td>HX, anhydrous ZnCl<sub>2</sub>, heat</td><td>ROH + HX &rarr; RX + H<sub>2</sub>O; ZnCl<sub>2</sub> is especially associated with the HCl route</td></tr><tr><td>PX<sub>3</sub></td><td>3ROH + PX<sub>3</sub> &rarr; 3RX + H<sub>3</sub>PO<sub>3</sub></td></tr><tr><td>PX<sub>5</sub></td><td>ROH + PX<sub>5</sub> &rarr; RX + POX<sub>3</sub> + HX, as in the PCl<sub>5</sub> case</td></tr><tr><td>Red P/X<sub>2</sub>, heat</td><td>Phosphorus halide formed in situ replaces OH by X; the source also lists H<sub>3</sub>PO<sub>3</sub> as by-product</td></tr><tr><td>SOCl<sub>2</sub>/pyridine</td><td>ROH + SOCl<sub>2</sub> &rarr; RCl + SO<sub>2</sub> + HCl</td></tr><tr><td>Concentrated H<sub>2</sub>SO<sub>4</sub> at 443 K, or concentrated H<sub>3</sub>PO<sub>4</sub></td><td>Alcohol &rarr; alkene + H<sub>2</sub>O, when elimination is possible</td></tr></tbody></table><p>The thionyl-chloride route is labelled Darzens' process in this source; here that means alcohol chlorination, not the separate Darzens carbonyl condensation. The phosphorus-trihalide coefficients have been restored. PX<sub>5</sub> is a source shorthand exemplified by PCl<sub>5</sub>, not a claim that every possible phosphorus pentahalide is an equally available reagent.</p><p>Dehydration removes H and OH from adjacent positions to form C=C. The 443 K condition is the usual ethanol-to-ethene teaching example, not a universal temperature for every alcohol. Substitution, rearrangement and competing ether formation depend on substrate and conditions.</p>"
    },
    {
      id: "alcohol-oxidation-copper",
      title: "Oxidation levels and the heated-copper comparison",
      sources: [{ document: "quick-revision", page: 79 }],
      html: "<p>The oxidation branches require the alcohol class to be specified; the common centre ROH in the drawing does not make all products applicable to all alcohols.</p><ul><li>A primary alcohol can follow RCH<sub>2</sub>OH + [O] &rarr; RCHO + H<sub>2</sub>O, then RCHO + [O] &rarr; RCOOH.</li><li>The source lists KMnO<sub>4</sub> in acidic or alkaline medium, or K<sub>2</sub>Cr<sub>2</sub>O<sub>7</sub>/H<sup>+</sup>, for oxidation to the carboxylic-acid level. In alkaline medium the actual product is carboxylate until acid work-up.</li><li>PCC gives an aldehyde from a primary alcohol under suitable anhydrous conditions. The alternative notation CrO<sub>3</sub>&middot;C<sub>5</sub>H<sub>5</sub>N&middot;HCl in the scan denotes pyridinium chlorochromate, not an unrelated additional reagent.</li><li>A secondary alcohol RCH(OH)R' oxidizes to RCOR', a ketone. A tertiary alcohol has no hydrogen on the OH-bearing carbon and cannot give an ordinary carbonyl by simple removal of those two hydrogens without C-C cleavage.</li></ul><p><strong>Alcohol vapours over heated copper at 573 K:</strong></p><table><thead><tr><th>Class</th><th>Source product and balance</th></tr></thead><tbody><tr><td>Primary</td><td>RCH<sub>2</sub>OH &rarr; RCHO + H<sub>2</sub></td></tr><tr><td>Secondary</td><td>RCH(OH)R' &rarr; RCOR' + H<sub>2</sub></td></tr><tr><td>Tertiary with a suitable beta H</td><td>Dehydration to an alkene + H<sub>2</sub>O</td></tr></tbody></table><p><strong>Source correction:</strong> oxidation is not generally cleavage of the alcohol's C-O bond, despite the chart heading. The oxygen normally remains bonded to the same carbon as that bond becomes C=O.</p>"
    },
    {
      id: "phenol-preparation",
      title: "Phenol structure and the preparation network",
      sources: [{ document: "quick-revision", page: 79 }],
      html: "<p>A phenol has OH directly attached to an aromatic ring carbon. The parent phenol is C<sub>6</sub>H<sub>5</sub>OH; this formula is not shared by every substituted phenol. An OH on a side-chain CH<sub>2</sub> is an alcohol rather than a phenolic OH.</p><ol><li><strong>From benzenesulfonic acid:</strong> form sodium benzenesulfonate, fuse with NaOH at the printed 573-623 K to sodium phenoxide, then acidify with dilute HCl. The fusion equation is C<sub>6</sub>H<sub>5</sub>SO<sub>3</sub>Na + 2NaOH &rarr; C<sub>6</sub>H<sub>5</sub>ONa + Na<sub>2</sub>SO<sub>3</sub> + H<sub>2</sub>O. Acidification gives phenol and NaCl.</li><li><strong>From aniline:</strong> NaNO<sub>2</sub>/HCl converts C<sub>6</sub>H<sub>5</sub>NH<sub>2</sub> into benzenediazonium chloride; preparation of this intermediate is kept cold. Subsequent warm water replaces the diazonio group by OH: C<sub>6</sub>H<sub>5</sub>N<sub>2</sub>Cl + H<sub>2</sub>O &rarr; C<sub>6</sub>H<sub>5</sub>OH + N<sub>2</sub> + HCl.</li><li><strong>From phenylmagnesium bromide:</strong> the source shows oxygen in dry ether giving C<sub>6</sub>H<sub>5</sub>OMgBr, then H<sub>2</sub>O/H<sup>+</sup> giving phenol. Its oxygen coefficient is one half per Grignard formula unit; equivalently 2C<sub>6</sub>H<sub>5</sub>MgBr + O<sub>2</sub> &rarr; 2C<sub>6</sub>H<sub>5</sub>OMgBr as an idealized net oxygenation. Oxygenation can involve peroxide intermediates; the diagram is not a complete mechanism.</li><li><strong>From sodium salicylate:</strong> soda lime, NaOH/CaO, removes the carboxyl group. The source draws sodium phenoxide, with Na<sub>2</sub>CO<sub>3</sub> and water lost, then dilute HCl gives phenol. A balanced excess-base version is HO-C<sub>6</sub>H<sub>4</sub>-COONa + 2NaOH &rarr; C<sub>6</sub>H<sub>5</sub>ONa + Na<sub>2</sub>CO<sub>3</sub> + H<sub>2</sub>O.</li><li><strong>From chlorobenzene, Dow's process:</strong> NaOH at 623 K gives sodium phenoxide, followed by dilute HCl to phenol. The drawing omits NaOH on part of this arrow; strong alkaline hydrolysis, not heating chlorobenzene alone, is required.</li><li><strong>From cumene:</strong> C<sub>6</sub>H<sub>5</sub>CH(CH<sub>3</sub>)<sub>2</sub> is oxidized with O<sub>2</sub> to cumene hydroperoxide, then cleaved in aqueous acid. The products are phenol and acetone. <strong>Source correction:</strong> acetone is omitted from the central-phenol map; the complete net equation is C<sub>9</sub>H<sub>12</sub> + O<sub>2</sub> &rarr; C<sub>6</sub>H<sub>6</sub>O + C<sub>3</sub>H<sub>6</sub>O.</li></ol>"
    },
    {
      id: "phenol-acidity-tests",
      title: "Phenol acidity, qualitative tests and reduction",
      sources: [{ document: "quick-revision", page: 79 }, { document: "quick-revision", page: 80 }],
      html: "<p>Phenols are more acidic than ordinary aliphatic alcohols because the phenoxide conjugate base is resonance stabilized. The source continues with two diagnostic observations: phenol gives a violet colour with FeCl<sub>3</sub>, and bromine water gives a white precipitate of 2,4,6-tribromophenol. Ferric-chloride colour depends on the phenol and test conditions and is not unique to phenol in every mixture.</p><ul><li>With sodium: 2C<sub>6</sub>H<sub>5</sub>OH + 2Na &rarr; 2C<sub>6</sub>H<sub>5</sub>ONa + H<sub>2</sub>.</li><li>With NaOH: C<sub>6</sub>H<sub>5</sub>OH + NaOH &rarr; C<sub>6</sub>H<sub>5</sub>ONa + H<sub>2</sub>O. Unlike sodium metal, sodium hydroxide does not give hydrogen in this neutralization.</li><li>With zinc and heat: C<sub>6</sub>H<sub>5</sub>OH + Zn &rarr; C<sub>6</sub>H<sub>6</sub> + ZnO. The source's product ring is benzene.</li><li>Hydrogenation with Ni at the printed 533 K: C<sub>6</sub>H<sub>5</sub>OH + 3H<sub>2</sub> &rarr; C<sub>6</sub>H<sub>11</sub>OH, cyclohexanol. The source's H<sub>2</sub> arrow is a reagent label, not a one-equivalent stoichiometric equation.</li></ul>"
    },
    {
      id: "phenol-ring-substitution",
      title: "Phenol ring-substitution map and the picric-acid correction",
      sources: [{ document: "quick-revision", page: 80 }],
      html: "<table><thead><tr><th>Source reagent and conditions</th><th>Ring products and labels</th></tr></thead><tbody><tr><td>H<sub>2</sub>SO<sub>4</sub>, 373 K</td><td>Para-phenolsulfonic acid, HO-C<sub>6</sub>H<sub>4</sub>-SO<sub>3</sub>H, with OH and SO<sub>3</sub>H opposite</td></tr><tr><td>3Br<sub>2</sub> in water</td><td>2,4,6-Tribromophenol + 3HBr; white precipitate</td></tr><tr><td>Br<sub>2</sub> in CS<sub>2</sub>, 273 K</td><td>Para-bromophenol, labelled major, plus ortho-bromophenol, labelled minor</td></tr><tr><td>Dilute HNO<sub>3</sub>, 298 K</td><td>Ortho-nitrophenol, labelled major, plus para-nitrophenol, labelled minor</td></tr><tr><td>Concentrated HNO<sub>3</sub>/H<sub>2</sub>SO<sub>4</sub></td><td>2,4,6-Trinitrophenol, picric acid</td></tr><tr><td>CH<sub>3</sub>Cl, anhydrous AlCl<sub>3</sub>/HCl as printed</td><td>Para-cresol, labelled major, plus ortho-cresol, labelled minor</td></tr></tbody></table><p>OH activates the ring and directs substitution ortho/para. The choice of medium and amount of reagent distinguishes monobromination in the cold nonaqueous example from tribromination in bromine water. The labels major and minor record the specified source examples, not fixed universal percentages.</p><p><strong>Source correction:</strong> the picric-acid caption wrongly says '2,4,6-tribromophenol', even though all three drawn substituents are NO<sub>2</sub> and the reagents are nitrating acids. Picric acid is 2,4,6-trinitrophenol; 2,4,6-tribromophenol is the separate bromine-water product. For nitration the balanced net substitution is C<sub>6</sub>H<sub>5</sub>OH + 3HNO<sub>3</sub> &rarr; C<sub>6</sub>H<sub>2</sub>(NO<sub>2</sub>)<sub>3</sub>OH + 3H<sub>2</sub>O.</p><p><strong>Source qualification:</strong> the cresol drawings show the intended ring-alkylation pattern, but free phenol can complex with AlCl<sub>3</sub> and undergo competing oxygen chemistry. The abbreviated arrow is not enough to establish an exclusive, generally clean cresol preparation, so no exact yield or guaranteed product ratio is inferred.</p>"
    },
    {
      id: "phenol-kolbe-reimer-oxidation",
      title: "Kolbe-Schmitt, Reimer-Tiemann and quinone formation",
      sources: [{ document: "quick-revision", page: 80 }],
      html: "<p><strong>Kolbe-Schmitt reaction:</strong> phenol first forms sodium phenoxide with NaOH. Reaction with CO<sub>2</sub> under suitable carboxylation conditions, followed by acid work-up, gives salicylic acid, 2-hydroxybenzoic acid. The source depicts OH at carbon 1 and COOH at carbon 2. Its 'Kolbe reaction' label refers to phenoxide carboxylation, not Kolbe electrolysis of an aliphatic carboxylate.</p><p><strong>Reimer-Tiemann reaction:</strong> phenoxide reacts with CHCl<sub>3</sub> and aqueous NaOH, giving an ortho-formyl phenoxide in the source map; H<sup>+</sup>/H<sub>2</sub>O work-up gives salicylaldehyde, 2-hydroxybenzaldehyde. OH and CHO occupy neighbouring ring positions. A balanced overall neutral-product equation is C<sub>6</sub>H<sub>5</sub>OH + CHCl<sub>3</sub> + 3NaOH &rarr; HO-C<sub>6</sub>H<sub>4</sub>-CHO + 3NaCl + 2H<sub>2</sub>O. The ortho product is the depicted main product; a para product can also occur.</p><p><strong>Oxidation:</strong> Na<sub>2</sub>Cr<sub>2</sub>O<sub>7</sub>/H<sub>2</sub>SO<sub>4</sub> converts phenol to p-benzoquinone in the source. The product is cyclohexa-2,5-diene-1,4-dione, with carbonyl groups opposite each other. The net oxygen balance can be written C<sub>6</sub>H<sub>6</sub>O + 2[O] &rarr; C<sub>6</sub>H<sub>4</sub>O<sub>2</sub> + H<sub>2</sub>O.</p><p><strong>Source drawing correction:</strong> the benzoquinone sketch retains a benzene-style inner circle. A quinone is not an ordinary aromatic benzene ring: its correct structure has two C=O groups and two carbon-carbon double bonds, not the six-pi-electron benzene circle.</p>"
    },
    {
      id: "ether-structure-preparation",
      title: "Ether structure, dehydration and Williamson synthesis",
      sources: [{ document: "quick-revision", page: 80 }],
      html: "<p>An ether has R-O-R' connectivity. The source gives C<sub>n</sub>H<sub>2n+2</sub>O, valid for acyclic saturated ethers with one oxygen. Its oxygen sketch shows two C-O bonds, two lone pairs and a bent C-O-C arrangement, with an angle of 111.7&deg;. This is a representative value, not an exact universal angle for every ether.</p><p><strong>Intermolecular alcohol dehydration:</strong> 2ROH &rarr; ROR + H<sub>2</sub>O, using H<sub>2</sub>SO<sub>4</sub> at the printed 413 K. <strong>Source correction:</strong> water is omitted from the printed product. This teaching condition is especially associated with suitable primary alcohols such as ethanol; secondary or tertiary alcohols readily compete by forming alkenes. Mixing two different alcohols does not generally yield one pure unsymmetrical ether.</p><p><strong>Williamson synthesis:</strong> RX + R'ONa &rarr; ROR' + NaX, with heating as needed. The source's alkyl-halide label is malformed as '2X'; the carbon group R must be present, and R and R' need not be identical. An alkoxide displaces halide by an SN2 mechanism.</p><p>The source says the halide must be primary and that tertiary or hindered primary/secondary halides eliminate. <strong>Source clarification:</strong> methyl halides are also excellent SN2 substrates. Unhindered primary halides are generally preferred; secondary substrates can substitute but have greater elimination competition, and tertiary substrates are unsuitable for the ordinary SN2 route. For an aryl-alkyl ether, use an alkyl halide and phenoxide rather than expecting SN2 at an aryl halide.</p>"
    },
    {
      id: "ether-acid-cleavage",
      title: "Ether cleavage by hydrogen halides: site selection and exceptions",
      sources: [{ document: "quick-revision", page: 80 }],
      html: "<p>The general source equation is ROR' + HX &rarr; ROH + R'X. Strong HI or HBr is normally effective after protonation of oxygen; HCl is not generally interchangeable under ordinary cleavage conditions. With excess halide acid, the initially formed aliphatic alcohol may react further.</p><p>The source states 'small group forms alkyl halide'. For methyl/primary/secondary combinations that react by SN2, the less hindered alkyl carbon is usually attacked, giving its halide and leaving the other group as an alcohol. For example, methyl ethyl ether initially gives CH<sub>3</sub>I and C<sub>2</sub>H<sub>5</sub>OH with one-equivalent HI conditions.</p><ul><li><strong>Aryl-alkyl ether:</strong> C<sub>6</sub>H<sub>5</sub>OR + HI &rarr; C<sub>6</sub>H<sub>5</sub>OH + RI. The alkyl-O bond breaks; the aryl-O bond remains. Anisole therefore gives phenol and methyl iodide, not iodobenzene and methanol.</li><li><strong>Tertiary exception drawn in the source:</strong> (CH<sub>3</sub>)<sub>3</sub>C-OCH<sub>3</sub> + HI &rarr; (CH<sub>3</sub>)<sub>3</sub>CI + CH<sub>3</sub>OH. Cleavage can occur at the tertiary carbon through an SN1 pathway, forming tert-butyl iodide and methanol.</li></ul><p><strong>Source correction:</strong> the second example contradicts an unconditional 'smaller group' rule. Tertiary, allylic or benzylic groups can favour ionization; elimination can also compete. Regioselectivity must therefore be based on the feasible mechanism, not size alone.</p>"
    },
    {
      id: "aromatic-ether-substitution",
      title: "Anisole nitration and the alkoxy directing group",
      sources: [{ document: "quick-revision", page: 80 }],
      html: "<p>Aromatic ethers undergo electrophilic substitution on the ring. An -OR substituent donates electron density by resonance, activates benzene toward this reaction class, and directs the incoming group mainly ortho and para.</p><p>The source example is anisole, C<sub>6</sub>H<sub>5</sub>OCH<sub>3</sub>, with HNO<sub>3</sub>/H<sub>2</sub>SO<sub>4</sub>. The products are 2-nitroanisole, labelled minor, and 4-nitroanisole, labelled major. OCH<sub>3</sub> remains attached to carbon 1; NO<sub>2</sub> enters carbon 2 or 4. Lower crowding often favours the para product in this example, but a universal para-major rule for every aromatic-ether substitution would be too broad.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 79, status: "partial", sectionIds: ["alkene-hydration-methods", "carbonyl-to-alcohol", "alcohol-oh-cleavage", "alcohol-esters-ethers", "alcohol-halogenation-dehydration", "alcohol-oxidation-copper", "phenol-preparation", "phenol-acidity-tests"], unresolved: ["In the carboxylic-acid-to-primary-alcohol preparation arrow, the final hydrogen subscript of the alternative borane reagent beside LiAlH4 is not confidently readable. The legible LiAlH4 route is transcribed; no scored question depends on the ambiguous formula."] },
    { document: "quick-revision", page: 80, status: "transcribed", sectionIds: ["phenol-acidity-tests", "phenol-ring-substitution", "phenol-kolbe-reimer-oxidation", "ether-structure-preparation", "ether-acid-cleavage", "aromatic-ether-substitution"], unresolved: [] }
  ],
  questions: [
    { id: "note-alcohols-001", text: "Which work-up converts the organoborane from alkene hydroboration into an alcohol?", options: [{ key: "a", text: "Hydrogen peroxide in aqueous base" }, { key: "b", text: "Sodium chloride in aqueous acid" }, { key: "c", text: "Hydrogen gas in dry ether alone" }, { key: "d", text: "Calcium oxide in anhydrous benzene" }], answer: "a", explanation: "Basic H2O2 oxidizes the carbon-boron bonds to carbon-oxygen bonds. Water and hydroxide alone, as incompletely printed in the source, do not supply this oxidation step.", sectionId: "alkene-hydration-methods", source: { document: "quick-revision", page: 79 }, cognitive: "understanding" },
    { id: "note-alcohols-002", text: "Which pair correctly compares propene hydration products?", options: [{ key: "a", text: "Acid gives propan-1-ol; hydroboration gives propan-2-ol" }, { key: "b", text: "Acid gives propan-2-ol; hydroboration gives propan-1-ol" }, { key: "c", text: "Acid gives propanal; hydroboration gives propanone" }, { key: "d", text: "Acid gives propanone; hydroboration gives propanal" }], answer: "b", explanation: "Acid hydration is Markovnikov, placing OH at the secondary carbon. Hydroboration followed by alkaline peroxide is anti-Markovnikov, placing OH at the terminal carbon.", sectionId: "alkene-hydration-methods", source: { document: "quick-revision", page: 79 }, cognitive: "application" },
    { id: "note-alcohols-003", text: "What alcohol is formed by NaBH4 reduction of butan-2-one followed by protonation?", options: [{ key: "a", text: "Butan-1-ol" }, { key: "b", text: "2-Methylpropan-1-ol" }, { key: "c", text: "Butan-2-ol" }, { key: "d", text: "2-Methylpropan-2-ol" }], answer: "c", explanation: "The ketone's carbon skeleton is retained and C=O becomes CH-OH. CH3COCH2CH3 therefore gives CH3CH(OH)CH2CH3, a secondary alcohol.", sectionId: "carbonyl-to-alcohol", source: { document: "quick-revision", page: 79 }, cognitive: "application" },
    { id: "note-alcohols-004", text: "Propanone reacts with CH3MgBr in dry ether, then receives aqueous acid work-up. Which alcohol results?", options: [{ key: "a", text: "Propan-2-ol" }, { key: "b", text: "Butan-1-ol" }, { key: "c", text: "2-Methylpropan-1-ol" }, { key: "d", text: "2-Methylpropan-2-ol" }], answer: "d", explanation: "The methyl nucleophile adds to the carbonyl carbon of propanone. That carbon then bears three methyl groups and OH after work-up, giving tert-butanol.", sectionId: "carbonyl-to-alcohol", source: { document: "quick-revision", page: 79 }, cognitive: "application" },
    { id: "note-alcohols-005", text: "Which gas accompanies alkoxide formation when an alcohol reacts with sodium amide?", options: [{ key: "a", text: "Ammonia, NH3" }, { key: "b", text: "Hydrogen, H2" }, { key: "c", text: "Nitrogen, N2" }, { key: "d", text: "Carbon dioxide, CO2" }], answer: "a", explanation: "NH2- removes the alcohol proton and becomes NH3. Hydrogen gas is produced by sodium metal or an appropriate metal hydride, not by this sodium-amide proton transfer.", sectionId: "alcohol-oh-cleavage", source: { document: "quick-revision", page: 79 }, cognitive: "understanding" },
    { id: "note-alcohols-006", text: "With sodium in excess, what amount of H2 follows complete reaction of 0.20 mol of a monohydric alcohol?", options: [{ key: "a", text: "0.05 mol of H2" }, { key: "b", text: "0.10 mol of H2" }, { key: "c", text: "0.20 mol of H2" }, { key: "d", text: "0.40 mol of H2" }], answer: "b", explanation: "The balanced equation is 2ROH + 2Na giving 2RONa + H2. Each alcohol contributes one hydrogen atom, so 0.20 mol alcohol gives 0.10 mol hydrogen molecules.", sectionId: "alcohol-oh-cleavage", source: { document: "quick-revision", page: 79 }, cognitive: "application" },
    { id: "note-alcohols-007", text: "Which reagent is appropriate for oxidizing a primary alcohol to an aldehyde while limiting further oxidation under suitable anhydrous conditions?", options: [{ key: "a", text: "Excess hot acidified permanganate" }, { key: "b", text: "Refluxing aqueous dichromate acid" }, { key: "c", text: "Pyridinium chlorochromate, PCC" }, { key: "d", text: "Lithium aluminium hydride, LiAlH4" }], answer: "c", explanation: "PCC can stop primary-alcohol oxidation at the aldehyde under suitable anhydrous conditions. Strong aqueous oxidants favour acid formation, while LiAlH4 is a reductant.", sectionId: "alcohol-oxidation-copper", source: { document: "quick-revision", page: 79 }, cognitive: "understanding" },
    { id: "note-alcohols-008", text: "Propan-2-ol vapour passes over heated copper at 573 K. Which organic product is predicted by the source comparison?", options: [{ key: "a", text: "Propanal" }, { key: "b", text: "Propanoic acid" }, { key: "c", text: "Propan-1-ol" }, { key: "d", text: "Propanone" }], answer: "d", explanation: "A secondary alcohol loses two hydrogen atoms in copper-catalysed dehydrogenation. Propan-2-ol gives propanone plus H2, rather than a primary-alcohol oxidation product.", sectionId: "alcohol-oxidation-copper", source: { document: "quick-revision", page: 79 }, cognitive: "application" },
    { id: "note-alcohols-009", text: "Which two by-products are shown for alcohol chlorination with thionyl chloride?", options: [{ key: "a", text: "SO2 and HCl" }, { key: "b", text: "SO3 and H2" }, { key: "c", text: "CO2 and HCl" }, { key: "d", text: "H2S and Cl2" }], answer: "a", explanation: "ROH + SOCl2 gives RCl + SO2 + HCl. These by-products conserve the oxygen, sulfur and two chlorine atoms of the reactants.", sectionId: "alcohol-halogenation-dehydration", source: { document: "quick-revision", page: 79 }, cognitive: "recall" },
    { id: "note-alcohols-010", text: "Which coproduct must accompany phenol in the usual acid cleavage of cumene hydroperoxide?", options: [{ key: "a", text: "Methanal" }, { key: "b", text: "Propanone" }, { key: "c", text: "Ethanal" }, { key: "d", text: "Butanone" }], answer: "b", explanation: "The nine-carbon cumene framework splits into six-carbon phenol and three-carbon acetone, or propanone. Omitting acetone loses three carbon atoms from the source map.", sectionId: "phenol-preparation", source: { document: "quick-revision", page: 79 }, cognitive: "understanding" },
    { id: "note-alcohols-011", text: "Which observation is associated with phenol in the ferric-chloride test described by the source?", options: [{ key: "a", text: "A silver mirror forms" }, { key: "b", text: "A brick-red precipitate forms" }, { key: "c", text: "A violet colour develops" }, { key: "d", text: "A yellow iodoform deposit forms" }], answer: "c", explanation: "Phenol gives the characteristic violet ferric-chloride complex under suitable test conditions. The other observations belong to different diagnostic reaction systems.", sectionId: "phenol-acidity-tests", source: { document: "quick-revision", page: 80 }, cognitive: "recall" },
    { id: "note-alcohols-012", text: "Sodium phenoxide is carboxylated with CO2 under Kolbe-Schmitt conditions and then acidified. What is the depicted main product?", options: [{ key: "a", text: "Benzene-1,2-diol" }, { key: "b", text: "2-Hydroxybenzaldehyde" }, { key: "c", text: "2-Methylphenol" }, { key: "d", text: "2-Hydroxybenzoic acid" }], answer: "d", explanation: "Kolbe-Schmitt introduces COOH adjacent to the phenolic oxygen in the depicted product. Acid work-up gives salicylic acid, which differs from the CHO product of Reimer-Tiemann.", sectionId: "phenol-kolbe-reimer-oxidation", source: { document: "quick-revision", page: 80 }, cognitive: "application" },
    { id: "note-alcohols-013", text: "Which group is introduced mainly ortho to OH in the Reimer-Tiemann reaction followed by acid work-up?", options: [{ key: "a", text: "A formyl group, -CHO" }, { key: "b", text: "A carboxyl group, -COOH" }, { key: "c", text: "A methyl group, -CH3" }, { key: "d", text: "A nitro group, -NO2" }], answer: "a", explanation: "CHCl3 and aqueous base introduce the formyl group. The main depicted neutral product is salicylaldehyde, with neighbouring OH and CHO groups.", sectionId: "phenol-kolbe-reimer-oxidation", source: { document: "quick-revision", page: 80 }, cognitive: "recall" },
    { id: "note-alcohols-014", text: "Which name correctly identifies picric acid despite the source's erroneous caption?", options: [{ key: "a", text: "2,4,6-Tribromophenol" }, { key: "b", text: "2,4,6-Trinitrophenol" }, { key: "c", text: "2,4,6-Trimethylphenol" }, { key: "d", text: "2,4,6-Trichlorophenol" }], answer: "b", explanation: "The drawn picric-acid substituents are three NO2 groups, and the reagent is a nitrating mixture. The correct name is 2,4,6-trinitrophenol, not tribromophenol.", sectionId: "phenol-ring-substitution", source: { document: "quick-revision", page: 80 }, cognitive: "recall" },
    { id: "note-alcohols-015", text: "Which product accounts for the white precipitate when phenol reacts with bromine water?", options: [{ key: "a", text: "2-Bromophenol" }, { key: "b", text: "4-Bromophenol" }, { key: "c", text: "2,4,6-Tribromophenol" }, { key: "d", text: "2,4,6-Trinitrophenol" }], answer: "c", explanation: "The strongly activated phenol ring is brominated at both ortho positions and the para position in bromine water, producing poorly soluble 2,4,6-tribromophenol.", sectionId: "phenol-ring-substitution", source: { document: "quick-revision", page: 80 }, cognitive: "recall" },
    { id: "note-alcohols-016", text: "Which structural description matches the ether oxygen diagram?", options: [{ key: "a", text: "Three carbon bonds and one unpaired electron" }, { key: "b", text: "One carbon bond and no lone pairs" }, { key: "c", text: "Two carbon bonds in a linear arrangement" }, { key: "d", text: "Two carbon bonds and two lone pairs" }], answer: "d", explanation: "A neutral ether oxygen forms two single bonds and retains two lone pairs. The resulting C-O-C shape is bent; the source's angle is representative rather than universal.", sectionId: "ether-structure-preparation", source: { document: "quick-revision", page: 80 }, cognitive: "understanding" },
    { id: "note-alcohols-017", text: "Which Williamson pairing best avoids a tertiary carbon as the site of SN2 attack when making methyl tert-butyl ether?", options: [{ key: "a", text: "Sodium tert-butoxide and methyl iodide" }, { key: "b", text: "Sodium methoxide and tert-butyl iodide" }, { key: "c", text: "Methanol and tert-butyl iodide alone" }, { key: "d", text: "tert-Butanol and methyl iodide alone" }], answer: "a", explanation: "The bulky group should be on the alkoxide and the unhindered methyl group on the halide. Methyl iodide allows SN2 attack, whereas tert-butyl iodide favours elimination or ionization.", sectionId: "ether-structure-preparation", source: { document: "quick-revision", page: 80 }, cognitive: "application" },
    { id: "note-alcohols-018", text: "What are the products of anisole cleavage by HI under the usual ether-cleavage conditions?", options: [{ key: "a", text: "Iodobenzene and methanol" }, { key: "b", text: "Phenol and methyl iodide" }, { key: "c", text: "Benzene and methyl hypoiodite" }, { key: "d", text: "Benzoic acid and methane" }], answer: "b", explanation: "Iodide attacks the methyl carbon of protonated anisole. The aryl-O bond is retained, giving phenol plus CH3I rather than replacing aryl oxygen with iodine.", sectionId: "ether-acid-cleavage", source: { document: "quick-revision", page: 80 }, cognitive: "application" },
    { id: "note-alcohols-019", text: "Why can methyl tert-butyl ether give tert-butyl iodide and methanol with HI, despite methyl being the smaller group?", options: [{ key: "a", text: "Every ether cleaves only at methyl carbon" }, { key: "b", text: "Iodide cannot bind to a tertiary carbon" }, { key: "c", text: "Tertiary C-O ionization enables an SN1 route" }, { key: "d", text: "The oxygen becomes a carbonyl without cleavage" }], answer: "c", explanation: "The tertiary side can ionize to a relatively stable carbocation and then capture iodide. This is a mechanistic exception to the less-hindered-site rule for SN2 cleavage.", sectionId: "ether-acid-cleavage", source: { document: "quick-revision", page: 80 }, cognitive: "understanding" },
    { id: "note-alcohols-020", text: "Which nitroanisole is labelled the major product of anisole nitration in the source?", options: [{ key: "a", text: "2-Nitroanisole" }, { key: "b", text: "3-Nitroanisole" }, { key: "c", text: "2,6-Dinitroanisole" }, { key: "d", text: "4-Nitroanisole" }], answer: "d", explanation: "The methoxy group activates the ortho and para sites. The source labels the less crowded para monosubstitution product, 4-nitroanisole, as major and the ortho product as minor.", sectionId: "aromatic-ether-substitution", source: { document: "quick-revision", page: 80 }, cognitive: "recall" }
  ]
};