window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["algae"] = {
  id: "algae",
  subject: "Botany",
  title: "Algae",
  sections: [
    {
      id: "algal-identity-and-scope",
      title: "Algae, phycology and the historical Thallophyta grouping",
      sources: [{ document: "biology", page: 240 }, { document: "biology", page: 242 }],
      html: "<p>The source names F. E. Fritsch as the father of phycology and credits C. Linnaeus with algae as a classification term. Algae is an older word, so the attribution should be understood as historical taxonomic usage rather than proof that Linnaeus invented the word. Phycology is the study of algae. Pioneers of the plant kingdom and child of the sea are the handwritten memory descriptions.</p>" +
        "<p>The heading Algae (Thallophyta) refers to the old grouping of relatively undifferentiated bodies. Typical algae have a thallus rather than true roots, stems and leaves, and many are aquatic photosynthetic organisms. The source calls them autotrophic eukaryotes with cellulose walls, while acknowledging some facultative parasites.</p>" +
        "<p><strong>Source corrections:</strong> these statements are not universal. The same notes include cyanobacteria under blue-green algae; they are prokaryotes, not eukaryotes. Colourless parasitic algae do not fit obligatory photoautotrophy. Wall composition varies, as the silica of diatoms and the group-specific polysaccharides show. The dependent sporophyte and independent gametophyte sentence is a bryophyte-like pattern, not a general algal life cycle.</p>"
    },
    {
      id: "three-life-cycle-patterns",
      title: "Haplontic, diplontic and haplodiplontic cycles",
      sources: [{ document: "biology", page: 240 }, { document: "biology", page: 241 }],
      html: "<table><thead><tr><th>Pattern</th><th>Phase organization and listed examples</th></tr></thead><tbody><tr><td>Haplontic</td><td>The growing body is haploid; the diploid phase is restricted to the zygote, which undergoes meiosis. Source examples: Volvox, Spirogyra and Chlamydomonas.</td></tr><tr><td>Diplontic</td><td>The growing body is diploid and the haploid phase is represented by gametes. Fucus is the algal example.</td></tr><tr><td>Haplodiplontic</td><td>Both haploid gametophyte and diploid sporophyte undergo multicellular development. Their relative size and dependence can differ.</td></tr></tbody></table>" +
        "<p>The source writes most algae beside the haplontic green examples; this is a broad teaching generalization, not a census establishing the proportion across every algal lineage. The third column lists Sphagnum, Marchantia, Polytrichum and Funaria among bryophytes, and Pteris, Dryopteris and Selaginella among pteridophytes. These names are retained as comparisons rather than relabelled algae. The page's two life cycles line is corrected by its own three-column table.</p>" +
        "<p><strong>Source corrections:</strong> haplodiplontic does not necessarily mean both generations are independent. Bryophyte sporophytes remain attached to and dependent on the gametophyte; Selaginella gametophytes are reduced and endosporic. Likewise, gymnosperms and angiosperms in the diplontic column have a dominant sporophyte but still produce multicellular, highly reduced gametophytes. They are not literally reduced to haploid gametes alone as in the strict Fucus comparison. A resting algal zygote need not be called nutritionally dependent simply because it is the only diploid stage.</p>"
    },
    {
      id: "chloroplast-shapes-and-pyrenoids",
      title: "Chloroplast shapes and the pyrenoid starch sheath",
      sources: [{ document: "biology", page: 240 }, { document: "biology", page: 242 }, { document: "biology", page: 243 }, { document: "quick-revision", page: 111 }],
      html: "<table><thead><tr><th>Shape</th><th>Source example</th></tr></thead><tbody><tr><td>Ribbon/spiral</td><td>Spirogyra; the source gives 1-16 chloroplasts with wavy margins, a species-dependent range rather than a fixed cell count.</td></tr><tr><td>U-shaped, collar, girdle or horseshoe</td><td>Ulothrix; the U resembles a horseshoe memory cue.</td></tr><tr><td>Cup-shaped</td><td>Chlamydomonas and Chlorella; the familiar Chlamydomonas cell is shown with one chloroplast.</td></tr><tr><td>Reticulate/net-like</td><td>Oedogonium, accompanied by a small net drawing.</td></tr><tr><td>Stellate/star-shaped</td><td>Zygnema; the handwritten Zygnemia spelling is normalized.</td></tr></tbody></table>" +
        "<p>The pyrenoid drawing has a protein-rich central region and an associated outer starch sheath. The source repeatedly emphasizes protein inside, starch outside. The protein/enzyme named in the group table is Rubisco, associated with carbon fixation. Pyrenoids are structures in chloroplasts, not separate storage plastids.</p>" +
        "<p><strong>Source clarification:</strong> describing the whole pyrenoid simply as a lump of stored starch loses the protein core. The surrounding starch can serve as stored carbohydrate, while the pyrenoid is associated with the photosynthetic carbon-concentrating system. Presence, number and sheath organization vary among algae; a single pyrenoid in the illustrated Chlamydomonas is not a count for every species. Cyanobacteria have no chloroplast pyrenoids.</p>"
    },
    {
      id: "spirogyra-body-and-taxonomy",
      title: "Spirogyra: filament, wall and traditional classification",
      sources: [{ document: "biology", page: 241 }, { document: "biology", page: 240 }, { document: "quick-revision", page: 111 }],
      html: "<p>Spirogyra has an unbranched filament made of cylindrical cells. The source names are pond scum, pond silk, water silk and hair of princess. Its chloroplasts are spiral ribbons with wavy margins, and cytoplasmic strands support the internal cell organization. Pectic material at the cell surface forms mucilage in water, accounting for the slimy, slippery feel.</p>" +
        "<table><thead><tr><th>Traditional rank</th><th>Name on the page</th></tr></thead><tbody><tr><td>Division</td><td>Chlorophyta.</td></tr><tr><td>Class</td><td>Chlorophyceae.</td></tr><tr><td>Order</td><td>Conjugales/Zygnematales.</td></tr><tr><td>Family</td><td>Zygnemataceae.</td></tr></tbody></table>" +
        "<p>This is the source's traditional green-alga classification. Modern treatments place Spirogyra among the zygnematophycean streptophyte algae; the historical division/class should not be presented as an exclusive modern phylogeny. The whole wall does not disappear when mucilage forms: hydration or release of outer pectic material is distinct from dissolving all structural wall layers.</p>" +
        "<p>The central cycle map marks fragmentation as the most common vegetative method. Rare nonmotile resting alternatives are labelled akinetes, hypnospores and parthenospores. No zoospores is emphasized. Sexual conjugation is the route to the thick-walled diploid zygospore, not an asexual production of flagellated cells.</p>"
    },
    {
      id: "spirogyra-conjugation",
      title: "Scalariform and lateral conjugation",
      sources: [{ document: "biology", page: 241 }, { document: "quick-revision", page: 111 }],
      html: "<p>The notes place Spirogyra sexual reproduction near the end of favourable growing conditions. Whole cell contents function as nonflagellate gametes. They are morphologically similar, so the standard answer is isogamy; donor and recipient behaviour creates the source's physiological anisogamy distinction. The latter does not mean that a large egg and small flagellated sperm are present.</p>" +
        "<table><thead><tr><th>Conjugation</th><th>Route of transfer</th></tr></thead><tbody><tr><td>Scalariform</td><td>Compatible cells in two adjacent filaments connect by conjugation tubes, producing a ladder-like arrangement. The source associates this with heterothallic filaments.</td></tr><tr><td>Direct lateral</td><td>Adjacent cells of the same filament communicate through a perforation in their common septum. The donor contents pass directly to the recipient.</td></tr><tr><td>Indirect lateral</td><td>A side tube connects adjacent cells of the same filament, allowing donor contents to reach the recipient by that route.</td></tr></tbody></table>" +
        "<p>The handwritten description calls lateral conjugation homothallic because both compatible roles occur within the same filament in that example. A wall-dissolving enzyme is written cytase. The source labels active/male and passive/female refer to transfer versus retention of contents; plus and minus denote compatibility. Scalariform and lateral distinguish where the participating cells are, whereas direct and indirect distinguish the lateral path.</p>" +
        "<p><strong>Source clarification:</strong> the little male-gamete sketch's wavy line must not be read as a flagellum: Spirogyra gametes are aplanogametes, and transfer occurs through the connection. A conjugation tube is a connection between cells, not the entire pair of filaments; the complete series of connections produces the ladder appearance.</p>"
    },
    {
      id: "spirogyra-zygospore-and-meiosis",
      title: "Zygospore germination and the surviving haploid nucleus",
      sources: [{ document: "biology", page: 241 }, { document: "quick-revision", page: 111 }, { document: "quick-revision", page: 113 }],
      html: "<ol><li>Fusion of the two haploid gametes and their nuclei establishes a diploid zygote.</li><li>The zygote develops a thick outer covering and becomes the resting zygospore, marked 2n in the drawing.</li><li>During germination under suitable conditions, the diploid nucleus undergoes meiosis.</li><li>The source's ordinary Spirogyra account shows four haploid nuclei, three crossed out as degenerating and one retained as functional.</li><li>The surviving nucleus supports germling growth by mitosis, restoring one haploid filament in the illustrated sequence.</li></ol>" +
        "<p><strong>Source correction:</strong> Quick Revision calls the four products meiospores, three of which degenerate. The handwritten nucleus diagram makes the distinction clearer: four meiotic nuclei are formed, not necessarily four separately released spores with only one germinating. Meiosis precedes subsequent mitotic filament growth.</p>" +
        "<p>The two source self-checks ask where meiosis occurs, offering zygote in one version and during germination of zygospore in the other. These describe the same zygotic reduction in this cycle. Meiosis is not the division forming gametes in the haploid filament, not conjugation itself, and not ordinary aplanospore formation.</p>" +
        "<p>An azygospore or parthenospore develops from gametic contents that fail to fuse and instead form a resistant covering. In the source's haploid gamete account it remains haploid. This is distinct from the diploid zygospore produced after fusion, despite the similar-looking resting wall.</p>"
    },
    {
      id: "sexual-reproduction-types",
      title: "Isogamy, anisogamy and oogamy",
      sources: [{ document: "biology", page: 241 }, { document: "biology", page: 243 }, { document: "quick-revision", page: 111 }, { document: "quick-revision", page: 112 }],
      html: "<table><thead><tr><th>Mode</th><th>Gametes and source examples</th></tr></thead><tbody><tr><td>Isogamy</td><td>Morphologically similar gametes with compatible physiological/mating types. The ISO means same mnemonic concerns form, not identical mating behaviour.</td></tr><tr><td>Anisogamy</td><td>Unequal-sized gametes with broadly similar organization; the larger is conventionally female and the smaller male.</td></tr><tr><td>Oogamy</td><td>A large nonmotile egg and a small male gamete, motile in the illustrated algal examples; pronounced differences in size, structure and role.</td></tr></tbody></table>" +
        "<p>Isogametes can be motile planogametes or nonmotile aplanogametes. Spirogyra supplies the nonmotile example. Oedogonium and particular Chlamydomonas species are listed under oogamy. Chlamydomonas is represented by isogamous, anisogamous and oogamous species in the source's broad treatment.</p>" +
        "<p><strong>Source clarification:</strong> the repeated all three methods sentence means variation across the genus, not that one individual necessarily changes among all three modes. The short fertilization is isogamous entry on p.243 is the familiar example, not a contradiction of that diversity. Most primitive for isogamy and most advanced for oogamy are historical teaching labels for differentiation, not a universal evolutionary ranking of every living species.</p>"
    },
    {
      id: "vegetative-fragments-and-hormogonia",
      title: "Vegetative multiplication, hormogonia and heterocysts",
      sources: [{ document: "biology", page: 241 }, { document: "biology", page: 242 }, { document: "quick-revision", page: 111 }, { document: "quick-revision", page: 112 }, { document: "quick-revision", page: 113 }],
      html: "<p>The general vegetative list includes fragmentation, cell division, hormogonia and a printed budding entry. These processes belong to different organisms; the list does not say that Spirogyra uses all of them. Fragmentation is the common Spirogyra route. Each viable fragment can continue growth into a filament.</p>" +
        "<p>In the Nostoc/Anabaena drawing, a long trichome has a labelled necrotic cell or necridium at a break point. The filament separates into short multicellular fragments called hormogonia. Each hormogonium can grow into a new filament. The labelled trichomes are rows of cells, not nuclei within one cell.</p>" +
        "<p>Heterocysts are separately marked thick-walled, pale cells specialized for nitrogen fixation. Their protected internal conditions help oxygen-sensitive nitrogenase function. The illustration's colourless label distinguishes them from the ordinary green vegetative cells; it is not proof that they contain no photosynthetic components whatsoever.</p>" +
        "<p><strong>Source corrections:</strong> the printed heterocyst that form hormogonia line merges two roles. Heterocysts fix nitrogen; hormogonia are dispersal/growth fragments, and necridia can facilitate breakage. A heterocyst is not itself a short filament. Cyanobacterial nitrogen fixation can improve paddy soil nitrogen and yield under suitable management, but a uniform yield increase is not specified. Teichoic acid in the Nostoc cell wall is also incorrect as a general diagnostic claim: cyanobacterial envelopes contain peptidoglycan and an outer membrane rather than the classic teichoic-acid-rich Gram-positive wall.</p>"
    },
    {
      id: "asexual-and-resting-stages",
      title: "Zoospores, aplanospores, hypnospores and akinetes",
      sources: [{ document: "biology", page: 241 }, { document: "quick-revision", page: 112 }, { document: "quick-revision", page: 113 }],
      html: "<table><thead><tr><th>Stage</th><th>Source characters and conditions</th></tr></thead><tbody><tr><td>Zoospore</td><td>Motile, flagellated dispersal cell, associated with favourable conditions; absent from Spirogyra. The no covering note means no rigid resting wall during the motile stage, not absence of a plasma membrane.</td></tr><tr><td>Aplanospore</td><td>Nonmotile and nonflagellated, with a relatively thin covering. Ulothrix is the printed abundant example. The handwritten favourable-condition association is not an exceptionless rule across species.</td></tr><tr><td>Hypnospore</td><td>A thick-walled nonmotile resting stage associated with unfavourable conditions.</td></tr><tr><td>Akinete</td><td>A resistant, thick-walled cell that perennates, preserving living material from one season to the next. The source associates very adverse conditions with this stage.</td></tr><tr><td>Azygospore/parthenospore</td><td>An unfused gamete develops a covering; no fertilization has restored diploidy in the haploid example.</td></tr></tbody></table>" +
        "<p><strong>Source clarification:</strong> thickest for hypnospores in print and very thick for akinetes in the handwriting are descriptive cues, not a measured universal thickness ranking. The exact environmental trigger and terminology depend on the organism. Non-ciliated in the aplanospore line means lacking locomotory flagella, not a statement about a multicellular animal ciliated epithelium.</p>"
    },
    {
      id: "palmella-and-flagella-comparison",
      title: "Palmella stage and flagella counts",
      sources: [{ document: "biology", page: 241 }, { document: "biology", page: 243 }, { document: "quick-revision", page: 111 }, { document: "quick-revision", page: 112 }],
      html: "<p>The palmella or palmelloid stage consists of nonmotile cells retained within a common mucilaginous matrix, often after flagella are lost and divisions continue. Chlamydomonas and Ulothrix are the source examples, retained by <strong>CPU</strong>: Chlamydomonas, Palmella, Ulothrix.</p>" +
        "<p><strong>Source correction:</strong> the handwritten definition as zygospores/aplanospores getting covered by mucilage is too narrow and conflates a vegetative palmelloid condition with a sexual resting zygospore. Mucilage alone does not determine the ploidy or make a cell a zygospore.</p>" +
        "<table><thead><tr><th>Organism</th><th>Source flagellated stage</th></tr></thead><tbody><tr><td>Chlamydomonas</td><td>Biflagellate zoospores; the printed Bi-Ch sound cue joins bi, two, with Chlamydomonas.</td></tr><tr><td>Ulothrix</td><td>Ordinary macrozoospores quadriflagellate; gametes biflagellate. The Q / kyu / U cue links four with Ulothrix.</td></tr><tr><td>Oedogonium</td><td>Multiflagellate zoospores.</td></tr><tr><td>Vaucheria</td><td>A large multiflagellate compound zoospore, or synzoospore.</td></tr><tr><td>Fern and Cycas</td><td>Multiflagellate sperm in this comparison; these are land-plant male gametes, not algal zoospores.</td></tr></tbody></table>" +
        "<p>Spore and gamete must be identified before a flagellum count is used. One source may describe a transient motile zygote, another a mature resting zygospore, and a third an asexual zoospore; these names are not interchangeable.</p>"
    },
    {
      id: "chlamydomonas-and-ulothrix",
      title: "Chlamydomonas and Ulothrix: body and habitat details",
      sources: [{ document: "biology", page: 243 }, { document: "biology", page: 242 }, { document: "quick-revision", page: 111 }, { document: "quick-revision", page: 112 }],
      html: "<p><strong>Chlamydomonas:</strong> the source describes stagnant fresh water, a unicellular motile body, an eyespot or stigma, one cup-shaped chloroplast and, in the ordinary example, one pyrenoid. Zoospores are biflagellate; palmella stages occur. Its presence in nutrient-rich water and its use with Chlorella in sewage-related systems are noted. The printed high organic matter content is found in Chlamydomonas line does not say whether it means habitat or biomass and is retained as incomplete rather than converted into a quantitative composition claim.</p>" +
        "<p><strong>Ulothrix:</strong> the handwritten example lives in slowly flowing cold water and is attached by a colourless basal holdfast cell. Its chloroplast is girdle-, collar- or horseshoe-shaped. Gametes have two flagella; the ordinary macrozoospores have four and are released through an opening in a lateral cell wall.</p>" +
        "<p><strong>Source corrections:</strong> the marine entry for Ulothrix in the group table is not a universal habitat and must not replace the freshwater example on p.243. Fusion of two biflagellate gametes can produce a briefly quadriflagellate planozygote, but the mature resting zygospore is nonmotile. Thus spores (zygospores): quadriflagellated in print confuses stages. The separate zoo gametes: sex determination phrase has no process or species explanation; it is not a complete testable mechanism.</p>"
    },
    {
      id: "cyanobacteria-and-green-algae-table",
      title: "Cyanobacteria and green algae: the complete comparison",
      sources: [{ document: "biology", page: 242 }, { document: "biology", page: 240 }, { document: "quick-revision", page: 111 }],
      html: "<table><thead><tr><th>Feature</th><th>Cyanophyceae/Myxophyceae/BGA</th></tr></thead><tbody><tr><td>Modern identity</td><td>Cyanobacteria, prokaryotes historically called blue-green algae.</td></tr><tr><td>Pigments listed</td><td>Chlorophyll a, beta-carotene, c-phycocyanin and c-phycoerythrin. The source highlights chlorophyll a and beta-carotene as general photosynthetic cues.</td></tr><tr><td>Reserve</td><td>Cyanophycean starch, a glycogen-like reserve, not chloroplast starch surrounding a pyrenoid.</td></tr><tr><td>Pyrenoids</td><td>Absent.</td></tr><tr><td>Size/body</td><td>Microscopic; the source says unicellular but its Nostoc and Anabaena examples are filamentous, so that word is not universal.</td></tr><tr><td>Examples</td><td>Nostoc and Anabaena: nitrogen fixation; Spirulina: high-protein biomass; Trichodesmium erythraeum: the Red Sea bloom association.</td></tr></tbody></table>" +
        "<p>The source leaves the cyanobacterial wall and habitat cells of this particular table blank; those empty cells do not mean absence of a wall or habitat. The later prokaryotic clarification is not a claim that the empty boxes contained unreadable text.</p>" +
        "<table><thead><tr><th>Feature</th><th>Green algae in the source's broad Chlorophyceae treatment</th></tr></thead><tbody><tr><td>Pigments</td><td>Chlorophyll a, chlorophyll b and beta-carotene.</td></tr><tr><td>Reserve and wall</td><td>Starch, often associated with a protein/Rubisco pyrenoid; cellulose is the listed wall material, with species exceptions.</td></tr><tr><td>Habitats</td><td>Fresh water, sea water, terrestrial surfaces and some hot-spring habitats, with certain Chlorella given as an example.</td></tr><tr><td>Size</td><td>Microscopic to macroscopic; Chlorella is the source's smallest example, not an established universal size record.</td></tr></tbody></table>" +
        "<p><strong>Source corrections:</strong> floridean starch appears in the green-alga reserve cell but belongs to the red-alga comparison. Most advanced algae is a historical label, not a modern ranking of all green lineages. The table's cellulose line must not override known wall diversity within the listed genera.</p>"
    },
    {
      id: "green-algal-examples-and-protein",
      title: "Green-algal examples, high-protein biomass and Chlorella uses",
      sources: [{ document: "biology", page: 242 }, { document: "quick-revision", page: 111 }, { document: "quick-revision", page: 112 }],
      html: "<table><thead><tr><th>Example</th><th>Every source association</th></tr></thead><tbody><tr><td>Spirogyra</td><td>Filamentous green alga with spiral chloroplasts.</td></tr><tr><td>Chlamydomonas</td><td>Motile unicellular body.</td></tr><tr><td>Volvox</td><td>Motile colony.</td></tr><tr><td>Ulva</td><td>Parenchymatous marine thallus; sea lettuce.</td></tr><tr><td>Oedogonium</td><td>Freshwater filament, described as floating; attached growth also occurs.</td></tr><tr><td>Ulothrix</td><td>Listed as marine in the group table, with the freshwater qualification given in its own section.</td></tr><tr><td>Cephaleuros</td><td>Parasitic green alga associated with algal red-rust disease.</td></tr><tr><td>Chlorella</td><td>Space algae, small cells, protein-rich biomass, chlorellin, antioxidant compounds, possible lichen symbiosis and sewage-related uses.</td></tr></tbody></table>" +
        "<p>The richest-protein list ranks Spirulina maximum and Chlorella second. These are source memory rankings for protein-rich microbial biomass, not a universal nutritional league table independent of strain, growth conditions or dry-mass basis. Spirulina is cyanobacterial biomass and Chlorella is a eukaryotic green alga.</p>" +
        "<p>Space research investigates photosynthetic oxygen production and protein-containing biomass from organisms such as Chlorella and Spirulina in controlled life-support systems. This is not proof that every strain or uncontrolled culture is suitable food. Chlorellin is the historical name for an antibacterial preparation from Chlorella; the word antibiotic in the notes does not establish a licensed clinical treatment. Antioxidant activity is a compound/property entry, not a universal medical benefit from eating the organism.</p>"
    },
    {
      id: "brown-algae-table-and-uses",
      title: "Brown algae: pigments, reserves, kelps and products",
      sources: [{ document: "biology", page: 242 }, { document: "quick-revision", page: 112 }, { document: "quick-revision", page: 113 }],
      html: "<table><thead><tr><th>Feature</th><th>Source content</th></tr></thead><tbody><tr><td>Pigments</td><td>Chlorophyll a, chlorophyll c, beta-carotene and the brown-associated fucoxanthin; antioxidant activity is noted beside fucoxanthin.</td></tr><tr><td>Reserves</td><td>Laminarin as the major storage carbohydrate in the table; mannitol, a sugar alcohol; oils, with an omega-3 fatty-acid annotation for kelp.</td></tr><tr><td>Wall</td><td>Cellulose and alginate.</td></tr><tr><td>Habitat and body</td><td>Especially colder marine coasts; multicellular, often large thalli.</td></tr><tr><td>Size example</td><td>Macrocystis pyrifera, a giant kelp. The source calls it largest/longest and also writes rockweed.</td></tr><tr><td>Named examples</td><td>Fucus, Laminaria and Sargassum; Sargassum is gulf weed.</td></tr></tbody></table>" +
        "<p>Mannitol is associated in the handwritten cell with low-calorie sweetener, thickening agent and diuretic. <strong>Source clarification:</strong> mannitol is a sugar alcohol and a pharmaceutical osmotic agent under controlled use, whereas alginates are the characteristic brown-algal thickeners/stabilizers. The row must not make an unmeasured portion of kelp a diuretic treatment. Omega-3 composition likewise varies and is not a quantitative claim about every oil sample.</p>" +
        "<p>Algin is used in food and cosmetic formulations as a thickener, stabilizer and emulsification aid, rendered fat emulsify in the source. Seaweeds are associated with iodine. Kelp is used in soup stocks, including those for miso soup; glutamic acid/glutamate contributes umami flavour. Kombu, printed Khombu, is linked to Laminaria in the older naming.</p>" +
        "<p><strong>Source corrections:</strong> kelp properly includes Laminaria and Macrocystis, not every brown seaweed. Rockweed is more commonly associated with Fucus than giant Macrocystis. The isolated pyrenoids bullet lacks a presence/absence qualification and is not a universal brown-algal feature. Trumpet hyphae in kelps are elongated conducting cells analogous in transport role to sieve tubes; the comparison does not give kelps vascular-plant phloem.</p>" +
        "<p>The handwritten sound mnemonic is retained as Algi lage Lamo time [Fucus cue] garera Sarga janu: Algi recalls algin, Lamo recalls Laminaria, the Fuc sound recalls Fucus, and Sarga recalls Sargassum. The colloquial connecting words provide no additional biological claim.</p>"
    },
    {
      id: "red-algae-table-and-products",
      title: "Red algae: reserves, habitats and phycocolloids",
      sources: [{ document: "biology", page: 242 }, { document: "biology", page: 240 }, { document: "quick-revision", page: 111 }, { document: "quick-revision", page: 112 }],
      html: "<table><thead><tr><th>Feature</th><th>Red-algal source entry</th></tr></thead><tbody><tr><td>Pigments</td><td>Chlorophyll a, chlorophyll d in the traditional table, beta-carotene, r-phycoerythrin and r-phycocyanin.</td></tr><tr><td>Reserve</td><td>Floridean starch, with potential biofuel noted as a possible use rather than an established yield.</td></tr><tr><td>Wall</td><td>Cellulose and sulphated polysaccharides.</td></tr><tr><td>Habitats</td><td>Marine waters, including deeper illuminated water and intertidal zones; some freshwater forms. The source also notes extreme saline/hot-spring environments for particular lineages, not every genus.</td></tr><tr><td>Calcified forms</td><td>Coralline red algae deposit CaCO<sub>3</sub> and contribute to reef structure.</td></tr><tr><td>Size</td><td>Any size is the handwritten wording, expressing diversity rather than a diagnostic measurement.</td></tr></tbody></table>" +
        "<p><strong>Source clarification:</strong> chlorophyll d is not a secure universal defining pigment of red algae; chlorophyll a and phycobiliproteins are the sound general distinction. The bare pyrenoids bullet does not establish their presence throughout the group. Coralline algae contribute to reef frameworks but are not the reef-building coral animals themselves.</p>" +
        "<table><thead><tr><th>Example/product</th><th>Use and source qualification</th></tr></thead><tbody><tr><td>Gelidium and Gracilaria</td><td>Agar-agar, including use as a gelling support in tissue-culture media. AA ... GG links agar-agar with the two genera.</td></tr><tr><td>Polysiphonia and Batrachospermum</td><td>Both are listed red algae. The source brackets them towards carragenine, an inadequately qualified commercial-product association.</td></tr><tr><td>Chondrus</td><td>Irish moss; the source mentions supplements. Chondrus is a familiar carrageenan source.</td></tr><tr><td>Porphyra</td><td>Edible seaweed used with sushi; potential biofuel is also written in the table.</td></tr><tr><td>Carrageenan</td><td>Red-algal hydrocolloid used for gel/jelly and formulation properties; not the same material as agar.</td></tr></tbody></table>" +
        "<p>The sound mnemonics are Gelly Grass - Agar khako ho, Polysi Bazar ma Car insurance, and Por - sushi ra labh milega. They cue Gelidium/Gracilaria/agar, Polysiphonia/carrageenan terminology, and Porphyra/sushi/benefit. The carrageenan mnemonic preserves the source association but cannot establish every linked genus as a standard commercial source. Batrachospermum is the freshwater red alga that need not appear visibly red. Harveyella is the colourless parasite on other red algae, an exception to a blanket photosynthetic-pigment rule.</p>"
    },
    {
      id: "snow-colours-and-blooms",
      title: "Snow colours, Red Sea and red tides",
      sources: [{ document: "quick-revision", page: 111 }, { document: "quick-revision", page: 113 }, { document: "biology", page: 240 }, { document: "biology", page: 242 }],
      html: "<table><thead><tr><th>Source colour entry</th><th>Names retained from the page</th></tr></thead><tbody><tr><td>Red snow</td><td>Chlamydomonas nivalis, Haematococcus nivalis, and Ulothrix flaccida in the printed list. The handwritten list repeats the first two, with inconsistent nivalis spellings.</td></tr><tr><td>Green snow</td><td>C. yellowstonensis; the printed genus is abbreviated and the spelling is retained without inventing a modern species identification.</td></tr><tr><td>Black snow</td><td>Scotiella nivalis and Raphidonema, as printed.</td></tr><tr><td>Red Sea bloom association</td><td>Trichodesmium erythraeum, a cyanobacterium; the source's erythium spelling is normalized.</td></tr><tr><td>Red tide</td><td>Dinoflagellates/Dinophyceae, separate from the Red Sea cyanobacterial association.</td></tr></tbody></table>" +
        "<p>Cryophytic algae grow on snow or ice. The source connects resistant hypnospores with haematochrome and red snow. <strong>Source correction:</strong> haematochrome is an older collective pigment term associated with reddish carotenoids, including astaxanthin in familiar examples; red colour is not necessarily deposited in the cell wall as the printed line states. Old snow-alga names have undergone taxonomic revision and colour can depend on life stage. The full historical list is retained, but its spelling and one-to-one colour associations are not independently secure enough for scored species-identification questions.</p>" +
        "<p>Red tides are bloom phenomena, not astronomical tides caused by algae. Dinoflagellates are common causes, but not every bloom is red or toxic and not every discoloured bloom has the same organism. Likewise, the Trichodesmium entry is a bloom association, not proof that the whole Red Sea is permanently red.</p>"
    },
    {
      id: "habitats-and-symbiotic-associations",
      title: "Benthic, thermal, endophytic and animal-associated algae",
      sources: [{ document: "biology", page: 240 }, { document: "quick-revision", page: 111 }, { document: "quick-revision", page: 112 }],
      html: "<p>The cryptophytic/benthic algae - in soil heading lists Chara, or stonewort. <strong>Source correction:</strong> benthic means associated with the bottom of a water body; Chara may be anchored in bottom sediment but is not thereby a terrestrial soil plant. Cryptophytic is not a universal synonym for benthic. Thermophytic means associated with warm habitats; the hot-spring example is written Haplosiphon, with no species or temperature supplied.</p>" +
        "<table><thead><tr><th>Association</th><th>Definition and source examples</th></tr></thead><tbody><tr><td>Endophytic</td><td>Inside plant tissues. The clear example is Nostoc in Cycas coralloid roots. The same block places Anabaena beside Anthoceros and Cladophora beside Lemna, but these alignments require correction/qualification.</td></tr><tr><td>Epiphytic</td><td>On a plant surface. Oedogonium on orchids is the handwritten example, without a species or evidence that distinguishes it from ordinary growth on aquatic plants.</td></tr><tr><td>Endozoic</td><td>Inside an animal. Zoochlorella in the gastrodermis of green Hydra is the repeated example.</td></tr><tr><td>Epizoic</td><td>On an animal surface. Cladophora on a snail shell is the repeated example; it is listed from both freshwater and marine settings.</td></tr></tbody></table>" +
        "<p>The printed habitat table adds protozoan with Cyanella, mosquito with Characium, and fish gill with Stigeoclonium, in addition to Hydra with Zoochlorella and snail with Cladophora. These are the literal host/associate rows, not proof of universal occurrence on every host species.</p>" +
        "<p><strong>Source corrections:</strong> the familiar hornwort Anthoceros association is with Nostoc; the Anabaena alignment should not replace it. Cladophora associated with Lemna need not be inside its tissues. Zoochlorella is green-algal, not BGA; the nearby Zooxanthia/zooxanthellae label generally refers to dinoflagellate symbionts and does not identify the ordinary green-Hydra partner. The sparse orchid, protozoan, mosquito and fish-gill entries do not provide enough organism-level context for reliable scored pairings.</p>"
    },
    {
      id: "parasitic-algae-and-diatoms",
      title: "Algal parasites, diatoms and Vaucheria",
      sources: [{ document: "biology", page: 240 }, { document: "biology", page: 242 }, { document: "quick-revision", page: 111 }, { document: "quick-revision", page: 112 }],
      html: "<p>The parasitic list gives Cephaleuros virescens for red rust of tea, Cephaleuros arabica for red rust of coffee, and Harveyella as a parasitic red alga. Cephaleuros is a green alga even though its disease is called red rust. That disease name does not make it the basidiomycete Puccinia or an oomycete white rust. The coffee entry is retained as a source name, not a modern assertion that only one species can affect coffee.</p>" +
        "<p>Diatoms are called jewels of the plant kingdom because of their patterned siliceous walls. Silicified cell walls contribute to the accumulated material used in filtration or sound-insulating materials. The source describes sexual reproduction through auxospore formation and identifies the auxospore as diploid. In the usual sexual size-restoration cycle, an enlarging auxospore restores a larger cell size; auxospore is not simply another name for a motile zoospore.</p>" +
        "<p><strong>Source clarification:</strong> the building-material use belongs to diatomaceous material rather than a living cell instantly producing a soundproof sheet. Auxospore formation is commonly linked to sex but its occurrence and development vary among diatoms. Cymbella is separately labelled biological filter with no mechanism or device specified, so that short entry is not expanded into an invented treatment process.</p>" +
        "<p>Vaucheria is coenocytic: its filament contains continuous multinucleate cytoplasm without ordinary repeated cross walls. Its large compound motile spore is a synzoospore with numerous flagella, and oil is the printed reserve. Coenocytic does not mean the organism is a colony of separately walled cells.</p>"
    },
    {
      id: "sewage-and-other-economic-entries",
      title: "Sewage systems, phycocolloids and qualified economic claims",
      sources: [{ document: "quick-revision", page: 112 }, { document: "biology", page: 242 }],
      html: "<p>Chlamydomonas and Chlorella are listed for sewage disposal. In suitable algal treatment systems, photosynthesis supplies oxygen and growing biomass takes up nutrients; this is not a claim that a culture alone removes every pathogen or makes sewage drinkable. The space-research oxygen/protein entries and the protein-rich Spirulina/Chlorella comparison concern selected cultures under managed conditions.</p>" +
        "<p>Agar from Gelidium and Gracilaria, carrageenan from red-algal sources, and alginate from brown algae are distinct phycocolloids. Their gelling, thickening, stabilizing or formulation roles explain the tissue-culture, jelly, food and cosmetic entries; they are not three names for one reserve food. The printed Ca RRagenin capitalization is a carrageenan/red-algae memory cue, not a chemical formula containing calcium.</p>" +
        "<p>The printed Anabaena and Aulosira: larvicidal algae line names neither species, active substance nor tested larva. It is preserved as an unqualified source claim and is not used to assert that these genera are universally safe or effective insect-control agents. The short Cymbella biological-filter entry is similarly limited. Porphyra/floridean-starch biofuel entries are potential research uses, not production quantities or proven commercial outcomes.</p>"
    },
    {
      id: "boundary-respiration-and-nitrogen",
      title: "Shared printed page: oxygen requirements and nitrogen conversions",
      sources: [{ document: "quick-revision", page: 112 }],
      html: "<p>The assigned algae spread includes a separate respiration block, retained here in full. Facultative is remembered by the source's Faculty sometimes attends cue, a translation of the short Nepali memory sentence. The cue means optional/flexible dependence, not a biochemical definition.</p>" +
        "<table><thead><tr><th>Source heading</th><th>Definition and necessary distinction</th></tr></thead><tbody><tr><td>Facultative aerobes</td><td>Printed as anaerobes that can survive in oxygen. Survival/tolerance alone does not establish use of oxygen in respiration.</td></tr><tr><td>Facultative anaerobes</td><td>Can grow with oxygen and also without it, using an appropriate alternative metabolism in its absence.</td></tr><tr><td>Obligate aerobes</td><td>Require oxygen for growth; the source phrases this as inability to survive without it.</td></tr><tr><td>Obligate anaerobes</td><td>Grow without oxygen and are harmed by oxygen exposure to a degree that depends on the organism and conditions.</td></tr></tbody></table>" +
        "<p><strong>Source correction:</strong> the first pair should not be taught as two perfectly opposite physiological categories merely from the wording. Aerotolerant anaerobes can tolerate oxygen without using it; facultative anaerobes can use oxygen and switch when it is absent. Growth requirements, survival time and oxygen toxicity are related but distinct observations.</p>" +
        "<p><strong>Ammonification:</strong> organic nitrogen, including protein-derived nitrogen, is converted to ammonia/ammonium during decomposition. The source examples are Bacillus vulgaris and Bacillus ramosus, historical names not securely mapped to current taxa on this page.</p>" +
        "<p><strong>Denitrification:</strong> nitrate is reduced through intermediates towards gaseous nitrogen, commonly under oxygen-limited conditions. Pseudomonas denitrificans and Thiobacillus denitrificans are the listed examples. It returns nitrogen towards the atmosphere and is not fixation of atmospheric N<sub>2</sub>, nor simply conversion of protein to ammonia.</p>"
    },
    {
      id: "boundary-bryophyte-characters",
      title: "Shared printed page: the beginning of Bryophyta",
      sources: [{ document: "quick-revision", page: 113 }],
      html: "<p>The algae assignment continues into the Bryophyta heading. The repeated first land plants, first land inhabiting plants and first embryophytes labels describe an early land-plant comparison; extant bryophytes are not thereby proved to be the unchanged first land plants. Amphibians of the plant kingdom refers to land growth combined with water-dependent fertilization.</p>" +
        "<ul><li>The source describes biflagellate antherozoids and a need for water for sperm transport.</li><li>Sex organs are multicellular and jacketed, often stalked, unlike the simplified unicellular algal comparison.</li><li>Sexual reproduction is oogamous, with a retained egg.</li><li>The sporophyte remains attached to the gametophyte. Marchantia is described as dependent and Funaria as semidependent because green sporophytic parts can photosynthesize; neither is an independent fern-like adult.</li><li>Funaria is given as the largest-archegonia example. The comparative superlative lacks a species/measurement survey and is not used as an unrestricted record.</li><li>Sphagnum is peat moss or bog moss.</li><li>The preceding moss rarely found near sea note expresses a general scarcity of marine mosses, not a prohibition on growth near a coast.</li></ul>" +
        "<p>The isolated sex cells formation and capsule main characteristics bullets are unfinished prompts with no explanatory content on this page. They are recorded as incomplete rather than supplemented with invented source text.</p>"
    },
    {
      id: "boundary-bryophyte-classification",
      title: "Shared printed page: liverwort, hornwort and moss comparison",
      sources: [{ document: "quick-revision", page: 113 }],
      html: "<table><thead><tr><th>Traditional class</th><th>Rhizoids, dispersal and examples</th></tr></thead><tbody><tr><td>Hepaticopsida: liverworts</td><td>Unicellular rhizoids on the ventral surface, with smooth and tuberculate types in the Marchantia comparison; multicellular scales. Elaters assist spore dispersal in many liverworts. Riccia and Marchantia are listed.</td></tr><tr><td>Anthocerotopsida: hornworts</td><td>Smooth-walled unicellular rhizoids on the ventral side. Pseudoelaters occur in the sporophyte. Anthoceros is the example; PP recalls pyrenoid and pseudoelater.</td></tr><tr><td>Bryopsida: mosses</td><td>Multicellular rhizoids with oblique septa. Both elaters and pseudoelaters are absent in the source comparison. Funaria, Sphagnum and Polytrichum are listed.</td></tr></tbody></table>" +
        "<p>The table prints pyrenoid present but absent in Marchantia for liverworts, pyrenoid present for hornworts and absent for mosses. <strong>Source correction:</strong> pyrenoids are not a general liverwort feature with Marchantia as the lone exception. Anthoceros is the familiar hornwort example, but even that should not be generalized to every hornwort species. Riccia also lacks the typical liverwort elaters; its presence in the examples does not make every character uniform across the entire column. Adult Sphagnum does not retain the ordinary rhizoids of many leafy mosses.</p>"
    },
    {
      id: "boundary-marchantia-and-funaria",
      title: "Shared printed page: Marchantia, archegonial counts and Funaria",
      sources: [{ document: "quick-revision", page: 113 }],
      html: "<p><strong>Marchantia:</strong> separate male and female gametophytes are dioecious. Gemma cups provide vegetative propagation. Mature archegonia are borne beneath the female receptacle and are described as inverted. The male receptacle is disc-like and the female receptacle is star-like. <strong>Source correction:</strong> the printed disc-shaped antheridia and star-shaped archegonium confuse the antheridiophore/archegoniophore receptacles with the individual sex organs.</p>" +
        "<p>Marchantia air pores occur in the upper epidermis. They are not actively opening and closing stomata. The source's rod-shaped antherozoids are elongated, motile sperm; the simplified shape word should not exclude their curved/coiled organization. Elaters assist spore dispersal through hygroscopic movements. The source's hydrochasy label must not be taken to mean the elaters simply throw spores out by opening on wetting: drying-related twisting and loosening are important in the ordinary account.</p>" +
        "<table><thead><tr><th>Source archegonium</th><th>Listed internal cells</th></tr></thead><tbody><tr><td>Marchantia</td><td>4-6 neck canal cells, one ventral canal cell and one egg.</td></tr><tr><td>Funaria</td><td>6-10 neck canal cells, one ventral canal cell and one egg.</td></tr><tr><td>Riccia</td><td>Four neck canal cells, one ventral canal cell and one egg.</td></tr></tbody></table>" +
        "<p>NCC means neck canal cell and VCC means ventral canal cell. These are the source's conventional counts; stage/species variation should not be erased by treating each range as an immutable count for all members of a genus.</p>" +
        "<p><strong>Funaria:</strong> the page calls it monoecious and autoecious, with male and female organs on distinct branches of the same gametophyte. Archegonia are erect; antheridia are club-shaped and archegonia flask-shaped. Gregarious means growing in groups or patches. Sperm are biflagellate and spirally coiled, with the source specifying about one and a half coils. Rhizoids are multicellular with oblique septa. The final note says spores contain many chloroplasts; no universal plastid number is supplied. These characters are retained as the familiar Funaria account, not transferred to the preceding algae.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 111, status: "partial", sectionIds: ["chloroplast-shapes-and-pyrenoids", "spirogyra-body-and-taxonomy", "spirogyra-conjugation", "spirogyra-zygospore-and-meiosis", "sexual-reproduction-types", "vegetative-fragments-and-hormogonia", "palmella-and-flagella-comparison", "chlamydomonas-and-ulothrix", "cyanobacteria-and-green-algae-table", "green-algal-examples-and-protein", "red-algae-table-and-products", "snow-colours-and-blooms", "habitats-and-symbiotic-associations", "parasitic-algae-and-diatoms"], unresolved: ["Left snow-colour table: 'C. yellowstonensis' has an abbreviated genus and uncertain species spelling; historical snow-alga identities and exact colour assignments are retained but not scored.", "Upper-right Chlamydomonas list: 'High organic matter content is found in Chlamydomonas' does not distinguish habitat from biomass composition.", "Right Ulothrix list: 'Zoo gametes: Sex determination' is incomplete and supplies no developmental mechanism.", "Right habitat table: Cyanella/protozoan, Characium/mosquito and Stigeoclonium/fish gill lack host species and a defined internal/external association; literal rows are retained, not scored."] },
    { document: "quick-revision", page: 112, status: "partial", sectionIds: ["sexual-reproduction-types", "vegetative-fragments-and-hormogonia", "asexual-and-resting-stages", "palmella-and-flagella-comparison", "chlamydomonas-and-ulothrix", "green-algal-examples-and-protein", "brown-algae-table-and-uses", "red-algae-table-and-products", "habitats-and-symbiotic-associations", "parasitic-algae-and-diatoms", "sewage-and-other-economic-entries", "boundary-respiration-and-nitrogen"], unresolved: ["Right economic list: 'Cymbella: Biological filter' supplies no mechanism, material or treatment system.", "Right economic list: 'Anabena, Aulosira: Larvicidal algae' supplies no species, active substance, target larva or conditions.", "Right respiration block: Bacillus vulgaris and Bacillus ramosus are legacy names without sufficient context to resolve current taxonomic identities."] },
    { document: "quick-revision", page: 113, status: "partial", sectionIds: ["spirogyra-zygospore-and-meiosis", "vegetative-fragments-and-hormogonia", "asexual-and-resting-stages", "brown-algae-table-and-uses", "snow-colours-and-blooms", "boundary-bryophyte-characters", "boundary-bryophyte-classification", "boundary-marchantia-and-funaria"], unresolved: ["Left Bryophyta character list: 'Sex cells formation' and 'Capsule main characteristics' are unfinished headings without their intended points; they are explicitly retained as incomplete prompts."] },
    { document: "biology", page: 240, status: "partial", sectionIds: ["algal-identity-and-scope", "three-life-cycle-patterns", "chloroplast-shapes-and-pyrenoids", "spirogyra-body-and-taxonomy", "cyanobacteria-and-green-algae-table", "red-algae-table-and-products", "snow-colours-and-blooms", "habitats-and-symbiotic-associations", "parasitic-algae-and-diatoms"], unresolved: ["Right hot-spring heading: the example is written 'Haplosiphon', without species or temperature; its precise intended taxon is not established.", "Right association grid: Cladophora/Lemna and Oedogonium/on orchids lack tissue, host-species or observational context. The literal entries are preserved without inventing verified endophytic/epiphytic pairings."] },
    { document: "biology", page: 241, status: "transcribed", sectionIds: ["three-life-cycle-patterns", "spirogyra-body-and-taxonomy", "spirogyra-conjugation", "spirogyra-zygospore-and-meiosis", "sexual-reproduction-types", "vegetative-fragments-and-hormogonia", "asexual-and-resting-stages", "palmella-and-flagella-comparison"], unresolved: [] },
    { document: "biology", page: 242, status: "partial", sectionIds: ["algal-identity-and-scope", "chloroplast-shapes-and-pyrenoids", "vegetative-fragments-and-hormogonia", "chlamydomonas-and-ulothrix", "cyanobacteria-and-green-algae-table", "green-algal-examples-and-protein", "brown-algae-table-and-uses", "red-algae-table-and-products", "snow-colours-and-blooms", "parasitic-algae-and-diatoms", "sewage-and-other-economic-entries"], unresolved: ["Brown- and red-algal reserve cells: each has a bare 'pyrenoids' bullet with no presence/absence or taxon qualification; no universal condition is inferred.", "Red-algal examples: the Polysiphonia/Batrachospermum bracket points towards 'Carragenine' but does not establish species or a commercial-source claim. The mnemonic and bracket are retained with the limitation."] },
    { document: "biology", page: 243, status: "transcribed", sectionIds: ["chloroplast-shapes-and-pyrenoids", "sexual-reproduction-types", "palmella-and-flagella-comparison", "chlamydomonas-and-ulothrix"], unresolved: [] }
  ],
  questions: [
    {
      id: "note-algae-001", text: "In a Spirogyra culture, two adjacent filaments develop a series of connecting bridges. Which observation specifically supports scalariform conjugation?",
      options: [{ key: "a", text: "Direct openings join neighbours in one filament" }, { key: "b", text: "Side tubes join neighbours in one filament" }, { key: "c", text: "Bridges form a ladder between two filaments" }, { key: "d", text: "A single filament breaks into viable fragments" }],
      answer: "c", explanation: "Scalariform conjugation occurs between cells of adjacent filaments and the connecting tubes create a ladder-like appearance. The first two routes describe lateral conjugation, and simple breakage is vegetative fragmentation.", sectionId: "spirogyra-conjugation", source: { document: "biology", page: 241 }, cognitive: "application"
    },
    {
      id: "note-algae-002", text: "Which taxonomic family is written for Spirogyra in the source's traditional classification?",
      options: [{ key: "a", text: "Zygnemataceae" }, { key: "b", text: "Volvocaceae" }, { key: "c", text: "Oedogoniaceae" }, { key: "d", text: "Ulotrichaceae" }],
      answer: "a", explanation: "The source places Spirogyra in Zygnemataceae, under Conjugales/Zygnematales. Its traditional division and class are distinguished in the notes from newer phylogenetic treatments of streptophyte algae.", sectionId: "spirogyra-body-and-taxonomy", source: { document: "biology", page: 241 }, cognitive: "recall"
    },
    {
      id: "note-algae-003", text: "Why can Spirogyra conjugation be called morphologically isogamous even when one cell donates its contents and the other retains them?",
      options: [{ key: "a", text: "The donor is diploid and the recipient is haploid" }, { key: "b", text: "The donor is a flagellated sperm and the recipient an egg" }, { key: "c", text: "Both gametes must perform identical movements" }, { key: "d", text: "Similar gamete form can coexist with different roles" }],
      answer: "d", explanation: "Isogamy refers to similar gamete morphology, whereas donor and recipient behaviour gives the physiological distinction emphasized in the notes. Neither different ploidy nor flagellated sperm is required in Spirogyra conjugation.", sectionId: "spirogyra-conjugation", source: { document: "quick-revision", page: 111 }, cognitive: "understanding"
    },
    {
      id: "note-algae-004", text: "Eight Spirogyra zygospores each undergo the illustrated meiosis, with three of four nuclei degenerating. How many functional haploid nuclei remain before further mitosis?",
      options: [{ key: "a", text: "4 functional nuclei" }, { key: "b", text: "8 functional nuclei" }, { key: "c", text: "24 functional nuclei" }, { key: "d", text: "32 functional nuclei" }],
      answer: "b", explanation: "Each zygospore produces four meiotic nuclei but retains only one in this account. Eight zygospores therefore leave eight functional haploid nuclei, although 32 nuclei were initially produced and 24 degenerated.", sectionId: "spirogyra-zygospore-and-meiosis", source: { document: "biology", page: 241 }, cognitive: "application"
    },
    {
      id: "note-algae-005", text: "Which event distinguishes a haploid Spirogyra azygospore from its ordinary diploid zygospore?",
      options: [{ key: "a", text: "The azygospore forms a covering without gamete fusion" }, { key: "b", text: "The azygospore forms after two diploid gametes fuse" }, { key: "c", text: "The azygospore is an asexual quadriflagellate cell" }, { key: "d", text: "The azygospore arises by division of a heterocyst" }],
      answer: "a", explanation: "The source describes an azygospore as unfused gametic contents acquiring a resistant covering. Without fertilization, the haploid gamete has not become diploid, unlike the zygospore produced after compatible gametes fuse.", sectionId: "spirogyra-zygospore-and-meiosis", source: { document: "quick-revision", page: 113 }, cognitive: "understanding"
    },
    {
      id: "note-algae-006", text: "Which chloroplast form is paired with Oedogonium in the handwritten comparison?",
      options: [{ key: "a", text: "Spiral ribbon" }, { key: "b", text: "Single cup" }, { key: "c", text: "Reticulate network" }, { key: "d", text: "Girdle-shaped band" }],
      answer: "c", explanation: "Oedogonium is the reticulate or net-like chloroplast example. Spirogyra supplies the spiral ribbon, Chlamydomonas the cup, and Ulothrix the girdle-like band, so these shape associations are separate.", sectionId: "chloroplast-shapes-and-pyrenoids", source: { document: "biology", page: 240 }, cognitive: "recall"
    },
    {
      id: "note-algae-007", text: "The pyrenoid sketch places Rubisco in a protein-rich core. What surrounds this core in the familiar green-algal example?",
      options: [{ key: "a", text: "A silica frustule" }, { key: "b", text: "A starch sheath" }, { key: "c", text: "A chitin jacket" }, { key: "d", text: "A peptidoglycan layer" }],
      answer: "b", explanation: "The source emphasizes protein inside and starch outside: starch forms an associated sheath around the pyrenoid's protein-rich core. Silica, chitin and peptidoglycan belong to different wall or envelope comparisons.", sectionId: "chloroplast-shapes-and-pyrenoids", source: { document: "quick-revision", page: 111 }, cognitive: "recall"
    },
    {
      id: "note-algae-008", text: "A cyanobacterial filament breaks into short multicellular pieces while separate pale cells fix nitrogen. Which assignment is correct?",
      options: [{ key: "a", text: "Fragments: heterocysts; nitrogen-fixing cells: hormogonia" }, { key: "b", text: "Fragments: auxospores; nitrogen-fixing cells: pyrenoids" }, { key: "c", text: "Fragments: pyrenoids; nitrogen-fixing cells: auxospores" }, { key: "d", text: "Fragments: hormogonia; nitrogen-fixing cells: heterocysts" }],
      answer: "d", explanation: "Hormogonia are short multicellular trichome fragments that grow into new filaments. Heterocysts are specialized nitrogen-fixing cells; the two structures must not be merged merely because both appear in the Nostoc diagram.", sectionId: "vegetative-fragments-and-hormogonia", source: { document: "biology", page: 241 }, cognitive: "application"
    },
    {
      id: "note-algae-009", text: "Which algal reproductive stage is explicitly absent from the Spirogyra account?",
      options: [{ key: "a", text: "Resting zygospore" }, { key: "b", text: "Viable filament fragment" }, { key: "c", text: "Flagellated zoospore" }, { key: "d", text: "Unfused parthenospore" }],
      answer: "c", explanation: "No zoospores is repeatedly emphasized for Spirogyra. It can multiply by fragmentation, reproduce sexually through zygospores, and form some nonmotile alternatives; these do not create a flagellated stage.", sectionId: "asexual-and-resting-stages", source: { document: "quick-revision", page: 112 }, cognitive: "recall"
    },
    {
      id: "note-algae-010", text: "An Ulothrix sample contains the ordinary macrozoospores and separate sexual gametes. Which flagellum counts match the notes?",
      options: [{ key: "a", text: "Macrozoospores: two; gametes: four" }, { key: "b", text: "Macrozoospores: four; gametes: two" }, { key: "c", text: "Macrozoospores: two; gametes: two" }, { key: "d", text: "Macrozoospores: four; gametes: four" }],
      answer: "b", explanation: "The ordinary Ulothrix macrozoospore is quadriflagellate and the gamete is biflagellate. Distinguishing stages prevents the source's separate zygospore/zoospore wording error from being carried into the comparison.", sectionId: "palmella-and-flagella-comparison", source: { document: "biology", page: 243 }, cognitive: "recall"
    },
    {
      id: "note-algae-011", text: "Chlamydomonas cells lose motility but continue dividing while retained in a common mucilage. Which condition is being described?",
      options: [{ key: "a", text: "A motile synzoospore" }, { key: "b", text: "An expanding auxospore" }, { key: "c", text: "A scalariform connection" }, { key: "d", text: "A palmelloid stage" }],
      answer: "d", explanation: "A palmelloid stage consists of nonmotile cells retained within a common mucilaginous matrix. It need not consist of fertilized zygospores, and the mucilage alone provides no evidence of a change in ploidy.", sectionId: "palmella-and-flagella-comparison", source: { document: "biology", page: 241 }, cognitive: "understanding"
    },
    {
      id: "note-algae-012", text: "Which feature anchors the cold-water Ulothrix filament described on the final handwritten page?",
      options: [{ key: "a", text: "A colourless basal holdfast cell" }, { key: "b", text: "A multicellular vascular root" }, { key: "c", text: "A terminal nitrogen-fixing cell" }, { key: "d", text: "A floating gas-filled bladder" }],
      answer: "a", explanation: "The source describes attachment by a colourless basal cell or holdfast. This is not a true vascular root, and it is unrelated to the heterocysts of cyanobacteria or buoyancy structures of some seaweeds.", sectionId: "chlamydomonas-and-ulothrix", source: { document: "biology", page: 243 }, cognitive: "recall"
    },
    {
      id: "note-algae-013", text: "Across different Chlamydomonas species, the notes list isogamy, anisogamy and oogamy. What does that statement justify?",
      options: [{ key: "a", text: "Every cell must use the three modes sequentially" }, { key: "b", text: "All gametes in the genus have the same size" }, { key: "c", text: "The genus includes more than one gamete-differentiation pattern" }, { key: "d", text: "All sexual cells in the genus lack flagella" }],
      answer: "c", explanation: "The three-mode statement describes variation across the genus. It does not establish that every species or individual uses all three, nor that the different reproductive modes have identical gamete size and motility.", sectionId: "sexual-reproduction-types", source: { document: "biology", page: 243 }, cognitive: "understanding"
    },
    {
      id: "note-algae-014", text: "Which name in the source identifies the motile colonial green-algal example?",
      options: [{ key: "a", text: "Chlorella" }, { key: "b", text: "Volvox" }, { key: "c", text: "Spirogyra" }, { key: "d", text: "Ulva" }],
      answer: "b", explanation: "Volvox is the colonial motile example. Chlorella is unicellular but not the motile colony, Spirogyra is filamentous, and Ulva has the source's parenchymatous marine thallus.", sectionId: "green-algal-examples-and-protein", source: { document: "biology", page: 242 }, cognitive: "recall"
    },
    {
      id: "note-algae-015", text: "A green-algal reserve cell in the source contains the phrase floridean starch. Which correction preserves the group distinction?",
      options: [{ key: "a", text: "Floridean starch belongs with red-algal reserves" }, { key: "b", text: "Floridean starch is the universal cyanobacterial wall" }, { key: "c", text: "Floridean starch is the principal diatom shell mineral" }, { key: "d", text: "Floridean starch is a synonym for brown-algal mannitol" }],
      answer: "a", explanation: "Floridean starch is characteristic of the red-algal comparison and was misplaced in the green-algal row. It is neither a wall mineral nor a synonym for mannitol, and ordinary green-algal storage starch should remain distinguished.", sectionId: "cyanobacteria-and-green-algae-table", source: { document: "biology", page: 242 }, cognitive: "understanding"
    },
    {
      id: "note-algae-016", text: "Which compound in the brown-algal row is responsible for the characteristic brown coloration?",
      options: [{ key: "a", text: "Chlorellin" }, { key: "b", text: "C-phycocyanin" }, { key: "c", text: "Floridean starch" }, { key: "d", text: "Fucoxanthin" }],
      answer: "d", explanation: "Fucoxanthin is the brown-associated accessory pigment listed alongside chlorophylls a and c. Chlorellin is a historical antibacterial preparation, and floridean starch is a red-algal reserve rather than a pigment.", sectionId: "brown-algae-table-and-uses", source: { document: "biology", page: 242 }, cognitive: "recall"
    },
    {
      id: "note-algae-017", text: "Which brown-algal product best fits the notes' food-and-cosmetic thickener/stabilizer role?",
      options: [{ key: "a", text: "Rubisco" }, { key: "b", text: "Alginates" }, { key: "c", text: "Haematochrome" }, { key: "d", text: "Cyanophycean starch" }],
      answer: "b", explanation: "Alginates are the brown-algal polysaccharide materials used for thickening and stabilization. The source's nearby mannitol annotations must not transfer this formulation role to every reserve compound in the row.", sectionId: "brown-algae-table-and-uses", source: { document: "biology", page: 242 }, cognitive: "application"
    },
    {
      id: "note-algae-018", text: "The AA ... GG mnemonic links agar-agar to which two genera?",
      options: [{ key: "a", text: "Fucus and Laminaria" }, { key: "b", text: "Chlorella and Chlamydomonas" }, { key: "c", text: "Gelidium and Gracilaria" }, { key: "d", text: "Nostoc and Anabaena" }],
      answer: "c", explanation: "Gelidium and Gracilaria supply the two G names in the agar-agar mnemonic. Agar is a gelling material used in culture media, distinct from brown-algal alginate and from cyanobacterial nitrogen-fixing biomass.", sectionId: "red-algae-table-and-products", source: { document: "quick-revision", page: 112 }, cognitive: "recall"
    },
    {
      id: "note-algae-019", text: "A carbonate-depositing red alga helps bind a reef framework. Which source distinction explains its contribution?",
      options: [{ key: "a", text: "Coralline algae deposit calcium carbonate in their structure" }, { key: "b", text: "Every red alga is a colony of reef-building coral animals" }, { key: "c", text: "Floridean starch becomes a nitrogen-fixing heterocyst" }, { key: "d", text: "All red algae replace cellulose with silica frustules" }],
      answer: "a", explanation: "Coralline red algae can deposit CaCO3 and contribute to reef construction or consolidation. They are algae rather than coral animals, and their role is unrelated to heterocysts or the silica frustules of diatoms.", sectionId: "red-algae-table-and-products", source: { document: "biology", page: 242 }, cognitive: "understanding"
    },
    {
      id: "note-algae-020", text: "Which organism group is associated with the red-tide entry rather than the source's Trichodesmium Red Sea entry?",
      options: [{ key: "a", text: "Liverworts" }, { key: "b", text: "Brown kelps" }, { key: "c", text: "Fission yeasts" }, { key: "d", text: "Dinoflagellates" }],
      answer: "d", explanation: "The notes associate red tides with dinoflagellates and separately associate Trichodesmium, a cyanobacterium, with Red Sea blooms. Neither wording means every bloom is permanently red or necessarily toxic.", sectionId: "snow-colours-and-blooms", source: { document: "biology", page: 240 }, cognitive: "recall"
    },
    {
      id: "note-algae-021", text: "A diatom forms the usual diploid auxospore after sexual fusion. What is its characteristic role in that cycle?",
      options: [{ key: "a", text: "Fixing nitrogen within a heterocyst" }, { key: "b", text: "Anchoring a filament through a holdfast" }, { key: "c", text: "Restoring a larger cell size by expansion" }, { key: "d", text: "Moving as a compound multiflagellate zoospore" }],
      answer: "c", explanation: "An auxospore commonly expands during the diatom sexual size-restoration cycle. It differs from a cyanobacterial heterocyst, an algal holdfast and the multiflagellate synzoospore associated with Vaucheria.", sectionId: "parasitic-algae-and-diatoms", source: { document: "quick-revision", page: 111 }, cognitive: "understanding"
    },
    {
      id: "note-algae-022", text: "Which pair correctly separates an alga inside an animal from an alga growing on an animal surface?",
      options: [{ key: "a", text: "Zoochlorella in Hydra: endozoic; Cladophora on a snail: epizoic" }, { key: "b", text: "Zoochlorella in Hydra: epizoic; Cladophora on a snail: endozoic" }, { key: "c", text: "Zoochlorella in Hydra: epiphytic; Cladophora on a snail: endophytic" }, { key: "d", text: "Zoochlorella in Hydra: endophytic; Cladophora on a snail: epiphytic" }],
      answer: "a", explanation: "Endozoic means inside an animal, exemplified by Zoochlorella in green Hydra. Epizoic means on the outside, as with growth on a snail shell. Endophytic and epiphytic instead refer to associations with plants.", sectionId: "habitats-and-symbiotic-associations", source: { document: "biology", page: 240 }, cognitive: "application"
    },
    {
      id: "note-algae-023", text: "Which structural pairing matches the Vaucheria entry?",
      options: [{ key: "a", text: "Septate mycelium with endogenous ascospores" }, { key: "b", text: "Dorsiventral thallus with a sporophytic capsule" }, { key: "c", text: "Siliceous single cell with an expanding auxospore" }, { key: "d", text: "Coenocytic filament with a compound synzoospore" }],
      answer: "d", explanation: "Vaucheria is described as coenocytic and produces a large compound multiflagellate synzoospore. The other pairs refer to fungal, bryophyte or diatom structures, not the continuous multinucleate filament in this entry.", sectionId: "parasitic-algae-and-diatoms", source: { document: "quick-revision", page: 112 }, cognitive: "recall"
    },
    {
      id: "note-algae-024", text: "A microbe grows with oxygen but switches to an appropriate alternative metabolism when oxygen is absent. Which category fits the observation?",
      options: [{ key: "a", text: "Obligate aerobe" }, { key: "b", text: "Facultative anaerobe" }, { key: "c", text: "Obligate anaerobe" }, { key: "d", text: "Oxygen-intolerant phototroph" }],
      answer: "b", explanation: "A facultative anaerobe can use oxygen when available and grow by alternative metabolism when it is absent. Mere oxygen tolerance without using it would not establish the same physiological capacity.", sectionId: "boundary-respiration-and-nitrogen", source: { document: "quick-revision", page: 112 }, cognitive: "application"
    },
    {
      id: "note-algae-025", text: "Which transformation identifies denitrification rather than ammonification in the shared printed block?",
      options: [{ key: "a", text: "Atmospheric nitrogen converted into ammonia" }, { key: "b", text: "Protein nitrogen converted into ammonium" }, { key: "c", text: "Nitrate reduced towards gaseous nitrogen" }, { key: "d", text: "Ammonium oxidized towards nitrate" }],
      answer: "c", explanation: "Denitrification reduces nitrate through intermediates towards gases such as N2. Ammonification converts organic nitrogen to ammonia/ammonium, fixation incorporates atmospheric N2, and oxidation of ammonium belongs to nitrification.", sectionId: "boundary-respiration-and-nitrogen", source: { document: "quick-revision", page: 112 }, cognitive: "understanding"
    },
    {
      id: "note-algae-026", text: "In which source-listed life cycle is the haploid phase strictly represented by gametes rather than a multicellular gametophyte?",
      options: [{ key: "a", text: "Fucus: diplontic" }, { key: "b", text: "Spirogyra: haplontic" }, { key: "c", text: "Marchantia: haplodiplontic" }, { key: "d", text: "Dryopteris: haplodiplontic" }],
      answer: "a", explanation: "Fucus illustrates the strict diplontic pattern in the table: the multicellular body is diploid and meiosis produces the haploid sexual stage. Spirogyra has a haploid filament, while the other two have multicellular gametophytes.", sectionId: "three-life-cycle-patterns", source: { document: "biology", page: 240 }, cognitive: "recall"
    },
    {
      id: "note-algae-027", text: "Why is a bryophyte's photosynthetic sporophyte still described as dependent or semidependent?",
      options: [{ key: "a", text: "It must lack every chloroplast throughout its life" }, { key: "b", text: "It remains attached to the gametophyte for resources" }, { key: "c", text: "It produces haploid eggs instead of meiotic spores" }, { key: "d", text: "It is the free-living haploid generation of the plant" }],
      answer: "b", explanation: "Photosynthesis by green sporophytic tissue does not make the bryophyte sporophyte fully independent. It remains attached to the gametophyte and relies on it for resources, explaining the source's Funaria semidependence wording.", sectionId: "boundary-bryophyte-characters", source: { document: "quick-revision", page: 113 }, cognitive: "understanding"
    },
    {
      id: "note-algae-028", text: "The printed PP cue in the hornwort column links which two structures?",
      options: [{ key: "a", text: "Pollen and peristome" }, { key: "b", text: "Pinnae and pinnules" }, { key: "c", text: "Prothallus and pollen" }, { key: "d", text: "Pyrenoid and pseudoelater" }],
      answer: "d", explanation: "PP recalls pyrenoid and pseudoelater in the source's Anthoceros comparison. It does not imply that all hornwort species have an identical pyrenoid condition, and it is unrelated to fern pinnae or seed-plant pollen.", sectionId: "boundary-bryophyte-classification", source: { document: "quick-revision", page: 113 }, cognitive: "recall"
    },
    {
      id: "note-algae-029", text: "Which correction is needed when the source calls Marchantia antheridia disc-shaped and archegonia star-shaped?",
      options: [{ key: "a", text: "The shapes describe their supporting gametangiophore receptacles" }, { key: "b", text: "The shapes describe individual haploid spores in the capsule" }, { key: "c", text: "The shapes describe the two kinds of unicellular rhizoid" }, { key: "d", text: "The shapes describe male and female pollen grains" }],
      answer: "a", explanation: "The disc-like and star-like forms belong to the male and female gametangiophore receptacles. Individual antheridia and archegonia are different structures, and Marchantia produces neither pollen grains nor pollen-bearing organs.", sectionId: "boundary-marchantia-and-funaria", source: { document: "quick-revision", page: 113 }, cognitive: "understanding"
    },
    {
      id: "note-algae-030", text: "Which two source examples are paired with sewage-related algal systems?",
      options: [{ key: "a", text: "Fucus and Macrocystis" }, { key: "b", text: "Chlamydomonas and Chlorella" }, { key: "c", text: "Gelidium and Gracilaria" }, { key: "d", text: "Porphyra and Chondrus" }],
      answer: "b", explanation: "Chlamydomonas and Chlorella are the sewage-related examples, associated with photosynthetic oxygen supply and nutrient uptake in managed systems. The other pairs are marine seaweeds linked to kelps, agar or edible/hydrocolloid uses.", sectionId: "sewage-and-other-economic-entries", source: { document: "quick-revision", page: 112 }, cognitive: "recall"
    }
  ]
};