window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["biotechnology"] = {
  id: "biotechnology",
  subject: "Botany",
  title: "Biotechnology and applied botany",
  sections: [
    {
      id: "culture-explants",
      title: "Plant tissue culture: explants and culture types",
      sources: [{ document: "biology", page: 167 }],
      html: "<p>An explant is the plant material introduced into a culture. Plant tissue culture uses the capacity of suitable living cells or tissues to regenerate under controlled conditions. The source distinguishes the following explants rather than treating every culture as a shoot culture.</p><table><thead><tr><th>Explant</th><th>Culture and purpose</th></tr></thead><tbody><tr><td>Shoot tip or axillary bud</td><td>Shoot culture; multiplication of existing shoot meristems.</td></tr><tr><td>Isolated protoplast</td><td>Protoplast culture; wall-free cells can be fused, including some combinations difficult to obtain by sexual crossing.</td></tr><tr><td>Embryo from an immature seed</td><td>Embryo culture; an embryo is grown separately from the seed.</td></tr><tr><td>Anther or pollen</td><td>Anther or microspore culture; haploid production through androgenesis.</td></tr><tr><td>Apical meristem</td><td>Meristem culture; useful in multiplication and production of pathogen-tested planting material.</td></tr><tr><td>Root tip</td><td>Root-tip culture; actively dividing cells are useful for studying mitosis.</td></tr></tbody></table><p><strong>Source correction:</strong> the handwritten anther-culture label means microspore, not microscope. Protoplast culture is described as advanced and as producing germ-free plants, but wall removal does not eliminate intracellular viruses or guarantee freedom from pathogens. Meristem culture, appropriate treatment and testing are relevant to obtaining healthy stock. No culture type is universally the most advanced.</p><p>Rapid clonal propagation can produce large numbers, retain desired characters and improve availability of productive, healthy planting material. These are potential benefits, not a guarantee that every regenerated plant is identical. Variation arising among tissue-culture regenerants is <em>somaclonal variation</em>.</p>"
    },
    {
      id: "culture-medium-and-asepsis",
      title: "Culture medium, asepsis and shoot-root control",
      sources: [{ document: "biology", page: 167 }, { document: "quick-revision", page: 142 }],
      html: "<p>Agar is a polysaccharide-rich gelling material obtained from red algae, particularly <em>Gelidium</em> and <em>Gracilaria</em>. Its main gelling component, agarose, contains alternating galactose-derived units; calling it simply a polymer of galactose is a revision shorthand. It supports a culture medium but is not the complete nutrient supply.</p><p>The handwritten comparison associates relatively more cytokinin with shoots and relatively more auxin with roots. In responsive tissues, a high cytokinin-to-auxin ratio generally favours shoot formation, while a high auxin-to-cytokinin ratio generally favours rooting. Actual responses depend on species, explant, hormone identities and concentrations, so the inequality is a useful trend rather than a universal recipe.</p><table><thead><tr><th>Item</th><th>Source sterilization note</th></tr></thead><tbody><tr><td>Explant</td><td>Sodium hypochlorite, NaOCl, for surface disinfection.</td></tr><tr><td>Medium</td><td>Autoclave: the source writes 15-20 lb and 120 &deg;C.</td></tr><tr><td>Instruments</td><td>Dry oven at 160-180 &deg;C for 3-4 hours.</td></tr><tr><td>Scalpels and forceps</td><td>The source lists 95% ethanol.</td></tr></tbody></table><p><strong>Source clarification:</strong> the autoclave pressure must be expressed as pressure, commonly about 15 psi gauge for saturated steam near 121 &deg;C, not as a mass in pounds. Exposure time depends on the load. The dry-heat range is the source's note, not a validated interchangeable time-temperature schedule. Ethanol alone is not reliable sterilization against spores, and 95% ethanol is not automatically the best disinfectant concentration. Surface disinfection is distinct from elimination of an internal infection. These are study comparisons, not a complete laboratory operating procedure.</p>"
    },
    {
      id: "recombinant-dna-tools",
      title: "Recombinant DNA: sequence of operations and enzyme roles",
      sources: [{ document: "biology", page: 167 }, { document: "quick-revision", page: 141 }],
      html: "<p>Genetic engineering deliberately changes genetic material. The source associates it with gene transfer, gene replacement, recombinant DNA technology and gene splicing; these are related techniques, not synonyms for every possible genetic change.</p><ol><li>Identify and isolate donor DNA containing the target sequence or desired genetic information.</li><li>Cut suitable donor and vector DNA with a restriction endonuclease.</li><li>Join the desired DNA to vector DNA with DNA ligase to form a recombinant molecule.</li><li>Introduce that molecule into a suitable host cell.</li><li>Allow the recombinant DNA to be copied as the host or vector replicates; this produces cloned DNA.</li></ol><table><thead><tr><th>Tool</th><th>Distinct action</th></tr></thead><tbody><tr><td>Restriction endonuclease</td><td>Recognizes particular DNA sequences and cuts within DNA. The source mnemonic is molecular scissors or scalpel.</td></tr><tr><td>Exonuclease</td><td>Removes nucleotides from an accessible 5-prime or 3-prime end, depending on the enzyme.</td></tr><tr><td>DNA ligase</td><td>Seals suitable breaks in the sugar-phosphate backbone; it joins DNA fragments rather than finding a restriction site.</td></tr><tr><td>DNA polymerase</td><td>Synthesizes DNA from a template and a suitable primer end.</td></tr></tbody></table><p>The source ranks restriction endonuclease, ligase and polymerase in that order as an examination memory cue. It is not a biological hierarchy of importance: each performs a different required task. Exonucleases are not a subdivision of restriction endonucleases, despite the way the handwritten arrows are arranged.</p><p><strong>Source correction:</strong> the printed scientist table's Smith and North should not be memorized as a discovery pair. Hamilton Smith is associated with characterization of a type II restriction enzyme; Werner Arber and Daniel Nathans are also central to restriction-enzyme history. Payen and Persoz isolated diastase, an early enzyme preparation; the printed Payne spelling is corrected here.</p>"
    },
    {
      id: "vectors-and-constructs",
      title: "Vectors, target DNA, markers and promoters",
      sources: [{ document: "biology", page: 167 }, { document: "biology", page: 168 }, { document: "quick-revision", page: 141 }],
      html: "<p>A vector is a DNA vehicle used to carry a sequence into a host and, for a cloning vector, permit its maintenance or replication. The source lists plasmids, bacteriophages, cosmids, yeast artificial chromosomes (YACs) and bacterial artificial chromosomes (BACs). These are different vector systems with different hosts and capacities; the target DNA is the selected donor sequence carrying the genetic information of interest.</p><p><em>Agrobacterium tumefaciens</em> provides a vector-mediated route for plant transformation through its DNA-transfer machinery. The source also names adenovirus, retrovirus including MLV, and lentivirus as other vector groups. A lentivirus is itself a type of retrovirus; these categories are not mutually exclusive. Vector design and suitability depend on the organism and purpose.</p><p><strong>Source correction:</strong> the printed pairing Plants: Agrobacterium and Animals: Escherichia coli is too broad. <em>E. coli</em> is commonly a bacterial cloning or expression host and can produce proteins encoded by introduced genes; it is not the universal vector for gene delivery into animal cells.</p><table><thead><tr><th>Term</th><th>Meaning</th></tr></thead><tbody><tr><td>Marker gene</td><td>A selectable or detectable feature helps identify cells or constructs. Easy detection is the useful property; instantaneous expression is not a definition.</td></tr><tr><td>Promoter DNA</td><td>A regulatory DNA region at which the transcription machinery assembles to initiate transcription.</td></tr><tr><td>Recombinant DNA</td><td>A molecule assembled by joining DNA segments in a new combination.</td></tr><tr><td>Transgene</td><td>A gene introduced into an organism through genetic engineering.</td></tr><tr><td>Cloned DNA</td><td>Copies of a DNA sequence produced through a cloning process.</td></tr></tbody></table><p><strong>Source correction:</strong> a promoter is not simply a gene that promotes a desired character, and recombinant DNA is not automatically synonymous with transgene. A marker can be linked to a construct without being part of the desired trait gene itself.</p>"
    },
    {
      id: "fusion-and-transgenic-examples",
      title: "Protoplast fusion, hybrids, cybrids and named examples",
      sources: [{ document: "biology", page: 167 }, { document: "biology", page: 168 }],
      html: "<p>A protoplast is a plant cell after removal of its wall, with the plasma membrane retained. Cellulase and pectinase are the wall-digesting enzymes named in the source. Polyethylene glycol (PEG) can promote fusion of suitable protoplasts. The resulting somatic fusion bypasses fertilization between gametes and can combine some otherwise difficult parental combinations.</p><p>A somatic hybrid combines nuclear contributions from the fused parental cells. A cybrid, or cytoplasmic hybrid, retains predominantly the nucleus of one parent with cytoplasmic or organellar contributions from another. The handwritten nucleus-of-one into cytoplasm-of-another sketch captures this distinction, but a cybrid need not contain literally all the cytoplasm of only the second parent.</p><p>The source puts conventional breeding and protoplast fusion under direct gene transfer. <strong>Source correction:</strong> conventional sexual breeding reshuffles inherited genomes and is not direct transfer of isolated DNA. Protoplast fusion is somatic hybridization; it should also be distinguished from introducing a defined isolated DNA construct.</p><ul><li><strong>Tobacco:</strong> a classic early transgenic plant example.</li><li><strong>Supermouse:</strong> the growth-enhanced transgenic mouse is the source's memorable animal example. It is not a secure designation of the first genetically modified animal of any kind.</li><li><strong>Dolly:</strong> born in Scotland in 1996, a sheep cloned using the nucleus of an adult somatic cell. She was the first mammal cloned from an adult somatic cell, not the first organism or first animal ever cloned.</li><li><strong>Polly and Molly:</strong> named transgenic sheep examples in the source, distinct from Dolly's role as the adult-cell cloning landmark.</li></ul><p>A transgenic animal carries an introduced gene; a heritable transgene is present in its germ line. A genetically modified organism is a broader category and does not always require foreign-species DNA. Cloning and transgenesis answer different questions: copying an existing genome is not the same as introducing a gene.</p>"
    },
    {
      id: "pcr-and-applications",
      title: "PCR and applications of biotechnology",
      sources: [{ document: "biology", page: 168 }],
      html: "<p>PCR means polymerase chain reaction. It amplifies a selected DNA region in vitro. Preserve the handwritten mnemonic <strong>DAE</strong>: denaturation, annealing, extension.</p><ol><li><strong>Denaturation:</strong> the two DNA strands separate.</li><li><strong>Annealing:</strong> primers bind to complementary template sequences.</li><li><strong>Extension:</strong> DNA polymerase extends the bound primers to synthesize DNA.</li></ol><p>The source adds analysis or electrophoresis after these three stages. <strong>Source correction:</strong> electrophoresis is a possible analysis of the product, not the fourth repeatedly cycling PCR stage. PCR amplifies DNA; reverse transcription is additionally needed when RNA is the initial template for an RNA-target test.</p><p>Under the idealized assumption that every amplifiable double-stranded starting molecule doubles in each cycle, $N=N_0 2^n$. For example, three starting molecules after seven ideal cycles give $N=3(2^7)=384$. Real amplification efficiency, early product lengths and plateau effects can differ; the doubling rule is a theoretical count, not a yield guarantee.</p><p>The application list on the page includes hybridoma technology, gene mapping, investigation or treatment of genetic disorders, DNA fingerprinting in crime investigation, vaccines, pharmaceutical products such as insulin, and agriculture. DNA profiling compares variable DNA markers; it is not a reading of every gene or, by itself, proof of how a sample arrived at a scene. Applications involving genetic disorders depend on the particular disorder and technique, not a general promise of cure.</p>"
    },
    {
      id: "hybridoma-and-diagnosis",
      title: "Hybridoma technology and antibody applications",
      sources: [{ document: "biology", page: 168 }, { document: "quick-revision", page: 141 }],
      html: "<p>A hybridoma is formed by combining an antibody-producing B lymphocyte with a suitable myeloma cell. The lymphocyte supplies antibody specificity; the myeloma contribution provides sustained proliferative capacity. A selected clone can produce large quantities of one monoclonal antibody. The source credits Kohler and Milstein with hybridoma technology.</p><p>Monoclonal means derived from a single cell clone and directed to one antigenic determinant. It does not mean an antibody that recognizes every pathogen. The source's applications are disease diagnosis, disease treatment and passive immunization.</p><table><thead><tr><th>Named diagnostic example</th><th>Principle and qualification</th></tr></thead><tbody><tr><td>ELISA: HIV, hepatitis and herpes examples</td><td>Enzyme-linked detection of a selected antigen or antibody, depending on the assay. Different infections need different validated assays.</td></tr><tr><td>RIA: viral-infection example</td><td>Radioimmunoassay uses a radioactive label. It is an assay principle, not a universal viral-infection test.</td></tr><tr><td>Monoclonal antibodies to hCG</td><td>Specific recognition of human chorionic gonadotropin is used in pregnancy testing.</td></tr></tbody></table><p>Passive immunization supplies preformed antibodies and can act without waiting for the recipient to make that antibody. Active immunization instead stimulates the recipient's own immune response and memory. Antibody-based treatments and laboratory detection use the same specificity principle for different purposes.</p>"
    },
    {
      id: "antibodies-and-antigens",
      title: "Antibody classes, antigens, epitopes and paratopes",
      sources: [{ document: "quick-revision", page: 141 }, { document: "biology", page: 168 }],
      html: "<p>The basic immunoglobulin unit has four polypeptide chains: two heavy and two light chains arranged in a Y-shaped unit. Its antigen-binding site is the <em>paratope</em>; the corresponding recognized region on the antigen is the <em>epitope</em>. Antigens may occur on cell surfaces, but soluble molecules can also be antigens. Proteins and carbohydrates are important antigen classes.</p><p><strong>Source correction:</strong> the printed tertiary-structure label is insufficient for the complete antibody. Each chain folds, but association of multiple chains gives the antibody quaternary structure. Orientation of the drawn Y does not change this fact.</p><table><thead><tr><th>Class</th><th>Source-linked role</th></tr></thead><tbody><tr><td>IgA</td><td>Found in secretions such as tears, saliva and breast milk; protects mucosal surfaces against microorganisms.</td></tr><tr><td>IgE</td><td>Associated with immediate allergy, including allergic asthma; receptor-bound IgE on mast cells can trigger release of histamine when cross-linked by antigen.</td></tr><tr><td>IgM</td><td>An early antibody in a primary response; its secreted pentameric form is the largest common circulating antibody assembly.</td></tr></tbody></table><p><strong>GAME</strong> is the printed decreasing-abundance mnemonic for IgG, IgA, IgM and IgE. It omits IgD; it is not a complete five-class serum ordering. IgM on a B-cell surface is monomeric, so largest must be tied to the secreted assembly rather than every form. IgE is involved in allergic forms of asthma, not every possible asthma mechanism.</p><p>The handwritten question pairs antigen with triggering an immune response and interferon with antiviral protein. An antigen is recognized by immune receptors; an immunogen is an antigen capable of inducing a response in the relevant context. Interferons are host signalling proteins that help establish antiviral responses, not antibody classes.</p>"
    },
    {
      id: "vaccines-insulin-and-history",
      title: "Vaccine categories and insulin landmarks",
      sources: [{ document: "quick-revision", page: 141 }, { document: "quick-revision", page: 142 }],
      html: "<p>The printed vaccine-generation scheme calls microbe-based vaccines first generation, genetically engineered or recombinant-DNA vaccines second generation, and synthetically produced vaccines third generation. It names hepatitis B and herpes virus in the second group and a foot-and-mouth-virus vaccine example in the third. Preserve these as the source's classification, not a universally standardized modern naming system.</p><p><strong>Source clarification:</strong> recombinant hepatitis B surface-antigen vaccine is a sound recombinant example. Herpes viruses include different pathogens and different vaccine technologies, so herpes virus alone does not identify a single recombinant vaccine. Synthetic peptide approaches have been studied for foot-and-mouth disease, but the phrase must not imply that every foot-and-mouth vaccine is synthetic. Traditional vaccines may contain an antigen; nucleic-acid or vector vaccines can instead deliver instructions for antigen production.</p><table><thead><tr><th>Insulin point</th><th>Study detail</th></tr></thead><tbody><tr><td>Isolation landmark</td><td>The source names Banting and Best; development of usable insulin also involved a wider research team.</td></tr><tr><td>Naming</td><td>The source names Sharpey-Schafer, with a misspelled form. Naming history is not identical to isolation history.</td></tr><tr><td>Molecular structure</td><td>Sanger established the amino-acid sequence of insulin.</td></tr><tr><td>Mature human insulin</td><td>51 amino acids: an A chain of 21 and a B chain of 30, connected by disulfide bonds.</td></tr></tbody></table><p><strong>Historical clarification:</strong> Jean de Meyer had used the name insuline before Sharpey-Schafer's later discussion of the proposed pancreatic substance. A question about coining the name therefore needs its historical wording specified. Insulin sequence determination, discovery of its physiological role, extraction and recombinant manufacture are separate achievements.</p>"
    },
    {
      id: "antibiotics-and-microbial-products",
      title: "Antibiotics, enzymes and industrial microbial products",
      sources: [{ document: "quick-revision", page: 141 }, { document: "quick-revision", page: 142 }],
      html: "<p>The source describes antibiotics as microbial chemical products that kill or inhibit other organisms and credits Waksman with the term antibiotic. Modern usage also includes related semisynthetic agents; antibacterial and antifungal activities depend on the compound. Antibiotics do not generally treat viral infections. The source's magic-bullet phrase is a cue for selective action, not a promise of no adverse effects.</p><table><thead><tr><th>Agent</th><th>Target or use</th></tr></thead><tbody><tr><td>Penicillin</td><td>Inhibits bacterial cell-wall synthesis, specifically peptidoglycan cross-linking in susceptible growing bacteria.</td></tr><tr><td>Rifampicin</td><td>Inhibits bacterial RNA polymerase and hence transcription, including mRNA synthesis.</td></tr><tr><td>Ciprofloxacin</td><td>Interferes with bacterial DNA gyrase or topoisomerase IV and DNA replication. The printed CD cue pairs ciprofloxacin with DNA.</td></tr><tr><td>Rennet</td><td>Milk-coagulating enzyme preparation used in cheese making.</td></tr><tr><td>Interferon</td><td>Host antiviral signalling protein, not an antibiotic produced by a bacterium.</td></tr></tbody></table><ul><li><em>Aspergillus niger</em>: industrial citric-acid production.</li><li><em>Acetobacter aceti</em>: acetic-acid production associated with vinegar.</li><li>Actinomycetes: an important source of many antibiotics; not every antibiotic comes from this group.</li><li><em>Clostridium</em>: the printed page associates it with riboflavin and methanol. Products vary by species and strain; this is not a valid genus-wide production rule.</li></ul><p><strong>Source correction:</strong> methanol should not be memorized as the standard product of <em>Clostridium</em> fermentation. Solvent-producing <em>C. acetobutylicum</em> is associated with acetone and butanol; the original riboflavin/methanol pairing is retained here as a flagged claim, not a scored fact.</p><p>The page calls penicillin the first isolated antibiotic. It is the classic early successful antibacterial-antibiotic discovery associated with Fleming, but absolute first-isolated claims depend on how antibiotic and isolation are defined. Streptomycin was isolated by Albert Schatz in Waksman's laboratory, with Elizabeth Bugie and Waksman part of the research history; attributing the isolation solely to Waksman omits that contribution.</p><p><strong>Source correction:</strong> Kuhne coined the term enzyme; he did not discover all enzymes. Payen and Persoz's diastase work is a different earlier landmark. Classical Koch postulates have limitations for obligate intracellular viruses and <em>Mycobacterium leprae</em>, which cannot be routinely grown in ordinary cell-free culture; the printed not-applicable sentence is a limitation of the classical culture requirement, not evidence against microbial causation.</p>"
    },
    {
      id: "biocontrol-and-economic-botany",
      title: "Biocontrol and economic-botany examples",
      sources: [{ document: "quick-revision", page: 141 }, { document: "quick-revision", page: 142 }],
      html: "<p>Bt insecticidal proteins originate from the prokaryote <em>Bacillus thuringiensis</em>. Genes encoding appropriate Cry proteins can confer resistance to susceptible insect pests in crops. Their action is target-dependent; Bt plants do not kill every insect or resist every pest.</p><p>The source lists blockage of photolysis and phloem transport under herbicides. <strong>Source clarification:</strong> herbicides have different targets. Some inhibit photosynthetic electron transport; others inhibit particular enzymes or growth processes. These two phrases are not universal mechanisms shared by all herbicides. Pyrethroids are a synthetic insecticide class related to pyrethrins; the printed most-recent claim is time-dependent and is not a current scientific ranking.</p><ul><li>Modern bread wheat, <em>Triticum aestivum</em>, is hexaploid, with six basic chromosome sets.</li><li><strong>Source correction:</strong> ordinary wheat protein is limited in lysine rather than being generically high in lysine. A statement about a specially improved high-lysine line must identify that line.</li><li><em>Ephedra</em> is the medicinal-source example linked with respiratory conditions; ephedrine-related compounds explain the historical association.</li><li><em>Adhatoda</em>, commonly treated as <em>Justicia adhatoda</em>, is the source's bronchitis-related medicinal-plant example. This is botanical context, not a treatment recommendation.</li><li>Rice, <em>Oryza sativa</em>, and sorghum, printed as <em>Sorghum vulgare</em> and now generally treated under <em>S. bicolor</em>, provide fibrous residues usable in paper manufacture.</li></ul>"
    },
    {
      id: "green-manures",
      title: "Green manure: purpose and named crops",
      sources: [{ document: "biology", page: 168 }, { document: "quick-revision", page: 141 }],
      html: "<p>Green manuring incorporates a growing crop into the soil while its material is still green. The handwritten Nepali phrase describes ploughing and mixing that material with soil. Fast-growing herbaceous crops, especially suitable legumes, are used to enrich soil with organic matter and recycled nutrients. Nitrogen fixed through a legume's symbiosis enters plant compounds; the crop does not simply add bottled or free nitrogen gas to the soil.</p><p>The page lists reduced leaching and soil erosion as benefits. A living cover can retain nutrients and protect the soil; the outcome depends on establishment, timing and management. The named examples are <em>Trifolium</em> or berseem clover, <em>Sesbania</em>, sunn hemp, <em>Cyamopsis</em>, and <em>Melilotus parviflora</em> as written for sweet clover.</p><p>The printed page calls <em>Sesbania robusta</em> a common green manure in Nepal. That exact name is retained as a source claim; the page does not establish which commonly used green-manure <em>Sesbania</em> was intended. It is not used as a species-identification answer. The reliable shared point is use of suitable <em>Sesbania</em> crops as green manure.</p><p>Green manure is plant biomass incorporated into soil. A biofertilizer is an inoculum of beneficial living organisms; the terms are not interchangeable even when both ultimately improve nutrient availability.</p>"
    },
    {
      id: "biofertilizer-organisms",
      title: "Biofertilizers: cyanobacteria and bacteria",
      sources: [{ document: "biology", page: 169 }, { document: "quick-revision", page: 142 }],
      html: "<p>Biofertilizers contain organisms that improve nutrient supply or availability to plants. The source's BGA means blue-green algae, now classified as cyanobacteria: photosynthetic prokaryotes, not eukaryotic algae. Photosynthesis can provide energy and carbon supporting nitrogen fixation, but not every cyanobacterium fixes nitrogen under every condition.</p><table><thead><tr><th>Association or mode</th><th>Named examples</th></tr></thead><tbody><tr><td>Symbiotic cyanobacterium in a water fern</td><td><em>Anabaena azollae</em> associated with <em>Azolla</em>; used in wet rice-field systems.</td></tr><tr><td>Cyanobacterium associated with cycads</td><td>The source names <em>Anabaena cycadae</em> in <em>Cycas</em>; cyanobacteria occur in its coralloid-root association.</td></tr><tr><td>Free-living cyanobacterial examples</td><td><em>Nostoc</em>, <em>Anabaena</em>, <em>Aulosira</em> and <em>Plectonema</em>.</td></tr><tr><td>Free-living aerobic bacterium</td><td><em>Azotobacter</em>.</td></tr><tr><td>Free-living anaerobic bacterium</td><td>Nitrogen-fixing members of <em>Clostridium</em>.</td></tr><tr><td>Symbiotic bacterium</td><td><em>Rhizobium</em> and related rhizobia in legume root nodules.</td></tr></tbody></table><p>The note calls <em>Aulosira</em> the most active nitrogen-fixing BGA. This is an examination emphasis on an effective rice-field example, not a universal quantitative ranking independent of strain and conditions.</p><p><strong>Source correction:</strong> the handwritten <em>Rhizobium</em> line says heterocyst in connection with legumes. Rhizobia occur in root nodules, with bacterial bacteroids inside plant cells; they do not occupy legume heterocysts. Heterocysts are specialized cells of certain filamentous cyanobacteria. Keep root nodules, coralloid roots and cyanobacterial heterocysts distinct.</p>"
    },
    {
      id: "mycorrhiza-and-scp",
      title: "Mycorrhiza, phosphate nutrition and single-cell protein",
      sources: [{ document: "biology", page: 169 }, { document: "quick-revision", page: 142 }],
      html: "<p>Mycorrhiza is a symbiotic association between fungi and plant roots. Fungal hyphae can explore soil beyond the root surface and improve mineral uptake, particularly phosphate. Vesicular-arbuscular mycorrhiza (VAM), now commonly discussed as arbuscular mycorrhiza, is the source's phosphate-nutrition cue.</p><table><thead><tr><th>Source group</th><th>Examples and interpretation</th></tr></thead><tbody><tr><td>Endophytic or internal association</td><td>Coffee, pepper and cardamom are listed. Arbuscular fungi establish characteristic structures within root cortical cells.</td></tr><tr><td>Orchid association</td><td>Orchids have an internal fungal association, but orchid mycorrhiza is not simply VAM. Its characteristic intracellular coils are called pelotons.</td></tr><tr><td>Ectophytic or external association</td><td><em>Pinus</em>, oak and <em>Eucalyptus</em> are listed. Ectomycorrhizal fungi form a sheath and an intercellular network rather than arbuscules within root cells.</td></tr><tr><td>Peach in the source's external list</td><td><strong>Source correction:</strong> peach is commonly associated with arbuscular mycorrhiza and is not a standard ectomycorrhizal example. Some host groups can have more than one association.</td></tr></tbody></table><p>The single-cell-protein example is <em>Spirulina</em>, a protein-rich cyanobacterial biomass used in food or feed contexts. The expression single-cell protein includes harvested microbial biomass and does not mean that every producing organism must be a solitary, nonfilamentous cell. Nitrogen fixation and phosphate acquisition are different services: a mycorrhizal phosphate benefit should not be described automatically as fungal nitrogen fixation.</p>"
    },
    {
      id: "breeding-selection",
      title: "Plant breeding, selection and domestication",
      sources: [{ document: "biology", page: 169 }],
      html: "<p>Plant breeding is the art and science of improving the genetic constitution of plants for useful traits such as yield. The page includes acclimatization, selection, hybridization and polyploid breeding. Acclimatization is adjustment to a new environment; it should not automatically be equated with a heritable evolutionary adaptation.</p><table><thead><tr><th>Selection type</th><th>Distinction preserved from the source</th></tr></thead><tbody><tr><td>Mass selection</td><td>Many desirable-looking, healthy plants are chosen mainly by phenotype and their seed may be pooled.</td></tr><tr><td>Pure-line selection</td><td>Progeny from an individual suitable self-pollinated plant are evaluated and a genetically uniform line selected.</td></tr><tr><td>Clonal selection</td><td>A desirable vegetatively propagated genotype is selected and multiplied.</td></tr></tbody></table><p>The source contrasts phenotype for mass selection with genotype for pure-line selection. This is a useful emphasis on progeny testing, not a claim that a genotype can be read directly from appearance. Pure lines and extensively inbred lines are characteristically homozygous and relatively homogeneous. Homozygosity describes allele identity within individuals; homogeneity describes similarity among individuals. A clone may retain heterozygosity and still be uniform.</p><p>Domestication brings a wild population under human management and selection; cultivation means growing a plant and is not by itself proof of genetic domestication. The source's short checks also associate pure-line breeding with homozygosity and new varieties with selection and hybridization. <strong>Source clarification:</strong> mutation followed by selection can also create varieties; the printed alternatives must not be treated as proof that only one named breeding route is possible.</p>"
    },
    {
      id: "hybridization-and-polyploidy",
      title: "Hybridization categories and polyploid corrections",
      sources: [{ document: "biology", page: 169 }, { document: "quick-revision", page: 142 }],
      html: "<p>Hybridization crosses genetically dissimilar parents. Heterosis, or hybrid vigour, is superior performance of a hybrid relative to an explicitly chosen parental comparison. Hybridization does not guarantee vigour in every cross or for every trait.</p><table><thead><tr><th>Term</th><th>Relationship of parents</th></tr></thead><tbody><tr><td>Intraspecific</td><td>Within one species, often between varieties.</td></tr><tr><td>Interspecific</td><td>Between different species.</td></tr><tr><td>Intrageneric</td><td>Within one genus; can include crosses between its species.</td></tr><tr><td>Intergeneric</td><td>Between different genera.</td></tr></tbody></table><p>The source's named combinations are brinjal with tomato, wheat (<em>Triticum</em>) with rye (<em>Secale</em>) producing triticale, and potato with tomato. Tomato was historically placed in <em>Lycopersicon</em> but is now generally placed in <em>Solanum</em>, alongside potato and brinjal. Consequently, the source's placement of all tomato combinations under intergeneric is not appropriate under that modern taxonomy. Potato-tomato somatic fusion also differs from an ordinary fertile sexual cross.</p><p>Polyploidy means more than two basic chromosome sets. Unreduced gametes or chromosome doubling can generate polyploids. Colchicine interferes with spindle microtubules and can be used to induce chromosome doubling. The second handwritten chemical beside colchicine appears as granoson; its identity is unresolved and is not a recommended reagent or an assessed fact.</p><p><strong>Source correction:</strong> fusion of several male gametes with one egg is not the standard plant-breeding explanation for polyploid production. The diagram labelling triticale 3n and pointing to <em>Triticum aestivum</em> 6n conflates different crops. Bread wheat is AABBDD, $2n=6x=42$. Triticale combines wheat and rye genomes and common forms are hexaploid or octoploid, not universally triploid. In an illustrative sterile AB hybrid, doubling to AABB supplies a homologous partner for each parental chromosome; it does not turn that hybrid into bread wheat.</p>"
    },
    {
      id: "ecology-on-assigned-page",
      title: "Ecology and Nepal vegetation details on the assigned printed page",
      sources: [{ document: "quick-revision", page: 142 }],
      html: "<p>The assigned printed page continues into ecology. Autecology concerns an individual organism or species in relation to its environment; synecology concerns communities. Stenothermic organisms tolerate a narrow temperature range, while eurythermic organisms tolerate a wide range. Preserve the stenothermic short or narrow memory cue.</p><p>Allopatric speciation involves geographical separation. The page's Nepali cue can be rendered A bata, alag, tadha: separate and far away. Sympatric speciation develops reproductive isolation without the initial geographical separation of populations. Merely sharing a place does not mean individuals belong to one interbreeding species.</p><table><thead><tr><th>Source vegetation belt</th><th>Altitude and examples</th></tr></thead><tbody><tr><td>Tropical</td><td>Below about 1,000 m; <em>Shorea robusta</em> emphasized. ABCD cue: A, <em>Acacia catechu</em>; B, <em>Bauhinia vahlii</em>; C, <em>Shorea robusta</em>; D, <em>Dalbergia sissoo</em>. C is the mnemonic position, not the initial of Shorea.</td></tr><tr><td>Subtropical</td><td>About 1,000-2,000 m; <em>Pinus roxburghii</em> and <em>Arisaema</em>.</td></tr><tr><td>Temperate</td><td>About 2,000-3,000 m; the source names <em>Taxus baccata</em>, <em>Rhododendron</em>, oak and <em>Cinnamomum</em>.</td></tr><tr><td>Subalpine</td><td>About 3,000-4,000 m; <em>Abies</em>, <em>Betula</em> and rhododendron forest.</td></tr></tbody></table><p>These are the printed revision bands, not exact universal distribution limits: aspect, rainfall, latitude and species identity matter. The source's Himalayan Taxus naming is retained, but modern regional treatments distinguish Himalayan yew taxa from European <em>T. baccata</em>.</p><table><thead><tr><th>Conservation mode</th><th>Meaning and examples</th></tr></thead><tbody><tr><td>Ex situ</td><td>Outside the natural habitat: gene banks, zoos and botanical gardens. The source's local memory examples are the botanical garden at Godawari and the zoo at Jawalakhel in Kathmandu Valley.</td></tr><tr><td>In situ</td><td>In the native ecosystem: national parks, sanctuaries, conservation areas or parks, and biosphere reserves.</td></tr></tbody></table><p>The Kathmandu-Valley cue identifies memorable ex-situ examples; it does not claim that all ex-situ facilities are in that valley or that a gene bank is a natural ecosystem.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 141, status: "partial", sectionIds: ["recombinant-dna-tools", "vectors-and-constructs", "hybridoma-and-diagnosis", "antibodies-and-antigens", "vaccines-insulin-and-history", "antibiotics-and-microbial-products", "biocontrol-and-economic-botany", "green-manures"], unresolved: ["Special Notes prints Sesbania robusta as a common Nepal green manure; the intended species cannot be established from this page. The exact printed name is retained and excluded from scored identification questions."] },
    { document: "quick-revision", page: 142, status: "transcribed", sectionIds: ["culture-medium-and-asepsis", "vaccines-insulin-and-history", "antibiotics-and-microbial-products", "biocontrol-and-economic-botany", "biofertilizer-organisms", "mycorrhiza-and-scp", "hybridization-and-polyploidy", "ecology-on-assigned-page"], unresolved: [] },
    { document: "biology", page: 167, status: "transcribed", sectionIds: ["culture-explants", "culture-medium-and-asepsis", "recombinant-dna-tools", "vectors-and-constructs", "fusion-and-transgenic-examples"], unresolved: [] },
    { document: "biology", page: 168, status: "transcribed", sectionIds: ["vectors-and-constructs", "fusion-and-transgenic-examples", "pcr-and-applications", "hybridoma-and-diagnosis", "antibodies-and-antigens", "green-manures"], unresolved: [] },
    { document: "biology", page: 169, status: "partial", sectionIds: ["biofertilizer-organisms", "mycorrhiza-and-scp", "breeding-selection", "hybridization-and-polyploidy"], unresolved: ["Right column, Polyploid Breeding: the chemical name following colchicine appears as granoson. Its exact intended identity is not reliably established, so it is retained as uncertain and excluded from the MCQs."] }
  ],
  questions: [
    { id: "note-biotechnology-001", text: "A nursery multiplies an elite plant using its axillary buds as explants. Which culture name most directly describes the starting material?", options: [{ key: "a", text: "Shoot culture" }, { key: "b", text: "Embryo culture" }, { key: "c", text: "Anther culture" }, { key: "d", text: "Protoplast culture" }], answer: "a", explanation: "Axillary buds contain shoot meristems, so their multiplication is shoot culture. Embryo, anther and protoplast cultures are named for different starting materials, not simply for the eventual production of shoots.", sectionId: "culture-explants", source: { document: "biology", page: 167 }, cognitive: "application" },
    { id: "note-biotechnology-002", text: "In a hormone-responsive explant, cytokinin is increased relative to auxin while other conditions remain suitable. Which response is generally favoured?", options: [{ key: "a", text: "Preferential root initiation" }, { key: "b", text: "Preferential shoot initiation" }, { key: "c", text: "Loss of every chromosome" }, { key: "d", text: "Fusion of all protoplasts" }], answer: "b", explanation: "A relatively high cytokinin-to-auxin ratio generally favours shoots; relatively more auxin favours roots. The response still depends on the plant and explant, so the ratio is a trend rather than an unconditional rule.", sectionId: "culture-medium-and-asepsis", source: { document: "biology", page: 167 }, cognitive: "application" },
    { id: "note-biotechnology-003", text: "A label claims that removing a plant cell wall guarantees a virus-free regenerated plant. Which assessment is scientifically justified?", options: [{ key: "a", text: "Correct, because a virus can occur only in a wall" }, { key: "b", text: "Correct, because every protoplast is a haploid cell" }, { key: "c", text: "Incorrect, because an intracellular virus can remain" }, { key: "d", text: "Incorrect, because a protoplast retains its rigid wall" }], answer: "c", explanation: "A protoplast has lost its wall, not necessarily its intracellular pathogens. Virus-free planting material requires an appropriate production and testing strategy; wall removal alone is not proof of freedom from infection.", sectionId: "culture-explants", source: { document: "biology", page: 167 }, cognitive: "understanding" },
    { id: "note-biotechnology-004", text: "An immature seed contains a living embryo that is excised and grown separately. Which explant-culture pairing fits this work?", options: [{ key: "a", text: "Pollen grain and androgenesis" }, { key: "b", text: "Root tip and root-tip culture" }, { key: "c", text: "Axillary bud and shoot culture" }, { key: "d", text: "Immature embryo and embryo culture" }], answer: "d", explanation: "The cultured material is the immature embryo, which defines embryo culture. Androgenesis begins from male gametophytic material, whereas shoot and root-tip cultures begin from their respective meristematic tissues.", sectionId: "culture-explants", source: { document: "biology", page: 167 }, cognitive: "application" },
    { id: "note-biotechnology-005", text: "Which enzyme pair matches the wall-removal step before the plant-cell fusion described in the notes?", options: [{ key: "a", text: "Cellulase and pectinase" }, { key: "b", text: "Ligase and polymerase" }, { key: "c", text: "Amylase and pepsin" }, { key: "d", text: "Lipase and trypsin" }], answer: "a", explanation: "Cellulase attacks cellulose and pectinase attacks pectic material, allowing protoplast preparation from suitable plant tissue. DNA ligase and polymerase act on nucleic acids, while the other pairs do not match plant-wall removal.", sectionId: "fusion-and-transgenic-examples", source: { document: "biology", page: 168 }, cognitive: "recall" },
    { id: "note-biotechnology-006", text: "A nuclease shortens a DNA fragment by repeatedly removing nucleotides from a free end. Which term identifies this mode of action?", options: [{ key: "a", text: "Internal restriction cutting" }, { key: "b", text: "Exonucleolytic degradation" }, { key: "c", text: "Template-directed extension" }, { key: "d", text: "Backbone nick sealing" }], answer: "b", explanation: "Exonucleases remove nucleotides from accessible ends. Endonucleases cut within a chain; polymerases extend DNA and ligases seal appropriate breaks. The position of cleavage distinguishes the two nuclease modes.", sectionId: "recombinant-dna-tools", source: { document: "biology", page: 167 }, cognitive: "understanding" },
    { id: "note-biotechnology-007", text: "Two compatible DNA fragments have been aligned, but their sugar-phosphate backbones are not yet joined. Which enzyme supplies the missing joining activity?", options: [{ key: "a", text: "DNA helicase" }, { key: "b", text: "RNA polymerase" }, { key: "c", text: "DNA ligase" }, { key: "d", text: "Exonuclease" }], answer: "c", explanation: "DNA ligase forms the required phosphodiester linkage at suitable DNA ends or nicks. Aligning complementary ends does not itself covalently join the backbones, and a nuclease would cut rather than seal them.", sectionId: "recombinant-dna-tools", source: { document: "biology", page: 167 }, cognitive: "application" },
    { id: "note-biotechnology-008", text: "The molecular-scissors mnemonic in these notes refers most specifically to which sequence-recognizing tool?", options: [{ key: "a", text: "A membrane transport protein" }, { key: "b", text: "A chromosome spindle fibre" }, { key: "c", text: "A DNA-fragment joining enzyme" }, { key: "d", text: "A restriction endonuclease" }], answer: "d", explanation: "Restriction endonucleases recognize particular DNA sequences and cleave DNA. This is the molecular-scissors action; DNA ligase supplies the contrasting joining function during recombinant-molecule assembly.", sectionId: "recombinant-dna-tools", source: { document: "biology", page: 167 }, cognitive: "recall" },
    { id: "note-biotechnology-009", text: "A construct contains a target gene and a nearby region where transcription machinery assembles. What is that regulatory region?", options: [{ key: "a", text: "A promoter" }, { key: "b", text: "An antibody" }, { key: "c", text: "A protoplast" }, { key: "d", text: "An exonuclease" }], answer: "a", explanation: "A promoter is a DNA regulatory region involved in transcription initiation. It is not defined as a protein-coding gene that somehow promotes the desired phenotype; the source shorthand is corrected by distinguishing regulation from coding.", sectionId: "vectors-and-constructs", source: { document: "biology", page: 168 }, cognitive: "understanding" },
    { id: "note-biotechnology-010", text: "Which listed item can serve as a DNA vehicle for carrying a selected insert into a compatible host?", options: [{ key: "a", text: "Agar gel" }, { key: "b", text: "Plasmid DNA" }, { key: "c", text: "Mature insulin" }, { key: "d", text: "Cellulose wall" }], answer: "b", explanation: "A plasmid can be designed as a cloning vector that carries an insert and is maintained in a compatible host. Agar supports a medium, insulin is a protein product, and a cell wall is not a DNA vector.", sectionId: "vectors-and-constructs", source: { document: "biology", page: 167 }, cognitive: "recall" },
    { id: "note-biotechnology-011", text: "In a hybridoma, which contribution mainly addresses the limited long-term proliferation of an antibody-producing B cell?", options: [{ key: "a", text: "The antigen supplies ribosomes" }, { key: "b", text: "The vector removes all antibodies" }, { key: "c", text: "The myeloma supplies sustained growth" }, { key: "d", text: "The agar supplies antigen specificity" }], answer: "c", explanation: "The myeloma partner contributes sustained proliferative capacity, while the B-cell partner provides the selected antibody specificity. Combining these properties supports production of a monoclonal antibody by an established clone.", sectionId: "hybridoma-and-diagnosis", source: { document: "biology", page: 168 }, cognitive: "understanding" },
    { id: "note-biotechnology-012", text: "A recipient is given a prepared monoclonal antibody rather than an antigen intended to induce a new response. Which description fits this immune intervention?", options: [{ key: "a", text: "Acclimatization to a new climate" }, { key: "b", text: "Selection of a plant pure line" }, { key: "c", text: "Active induction of antibody memory" }, { key: "d", text: "Passive provision of specific antibody" }], answer: "d", explanation: "Preformed antibody is supplied directly, which is passive immunization. Active immunization instead stimulates the recipient to generate an immune response; receiving an antibody does not by itself establish the same immune memory.", sectionId: "hybridoma-and-diagnosis", source: { document: "biology", page: 168 }, cognitive: "application" },
    { id: "note-biotechnology-013", text: "Which operation belongs to analysis after PCR rather than to its repeating DAE cycle?", options: [{ key: "a", text: "Separating products by electrophoresis" }, { key: "b", text: "Separating template DNA strands" }, { key: "c", text: "Binding primers to complementary DNA" }, { key: "d", text: "Extending DNA from bound primers" }], answer: "a", explanation: "DAE means denaturation, annealing and extension. Electrophoresis can analyse amplified products after cycling, but is not a fourth stage repeated to create each new DNA copy. The distinction corrects the source's four-item list.", sectionId: "pcr-and-applications", source: { document: "biology", page: 168 }, cognitive: "understanding" },
    { id: "note-biotechnology-014", text: "Assume three amplifiable DNA molecules double perfectly during each of seven PCR cycles. How many double-stranded molecules does this ideal model predict?", options: [{ key: "a", text: "192 molecules" }, { key: "b", text: "384 molecules" }, { key: "c", text: "768 molecules" }, { key: "d", text: "128 molecules" }], answer: "b", explanation: "Use $N=N_0 2^n$. Here $N=3(2^7)=3(128)=384$. The 128 choice ignores the three starting molecules; 192 and 768 correspond to one fewer and one extra ideal doubling respectively.", sectionId: "pcr-and-applications", source: { document: "biology", page: 168 }, cognitive: "application" },
    { id: "note-biotechnology-015", text: "A diploid plant has 24 chromosomes in its somatic cells. A regenerant develops directly from one normal haploid microspore without chromosome doubling. What chromosome count is expected?", options: [{ key: "a", text: "6 chromosomes" }, { key: "b", text: "24 chromosomes" }, { key: "c", text: "12 chromosomes" }, { key: "d", text: "48 chromosomes" }], answer: "c", explanation: "The somatic count is $2n=24$, so a normal reduced microspore has $n=12$. Androgenesis from that microspore preserves the haploid count unless doubling occurs; doubling is explicitly excluded in the question.", sectionId: "culture-explants", source: { document: "biology", page: 167 }, cognitive: "application" },
    { id: "note-biotechnology-016", text: "Several regenerated plants differ from the original donor after a period in tissue culture. Which source term describes this origin of variation?", options: [{ key: "a", text: "Sympatric isolation" }, { key: "b", text: "Passive immunization" }, { key: "c", text: "Autecological tolerance" }, { key: "d", text: "Somaclonal variation" }], answer: "d", explanation: "Somaclonal variation is variation observed among plants regenerated through tissue culture. It explains why rapid clonal multiplication is not an unconditional guarantee that every regenerated plant retains the original genotype and phenotype.", sectionId: "culture-explants", source: { document: "biology", page: 167 }, cognitive: "recall" },
    { id: "note-biotechnology-017", text: "A plant regenerant retains the nuclear genome of one parent but organellar contributions from another. Which outcome best matches that description?", options: [{ key: "a", text: "A cybrid" }, { key: "b", text: "A hybridoma" }, { key: "c", text: "An antibody" }, { key: "d", text: "An antigen" }], answer: "a", explanation: "A cybrid is a cytoplasmic hybrid: nuclear inheritance is predominantly from one parent while cytoplasmic or organellar material includes another parent's contribution. A hybridoma is instead an antibody-producing lymphocyte-myeloma fusion.", sectionId: "fusion-and-transgenic-examples", source: { document: "biology", page: 167 }, cognitive: "application" },
    { id: "note-biotechnology-018", text: "Why does the complete two-heavy-chain, two-light-chain antibody have quaternary structure?", options: [{ key: "a", text: "Its sequence contains only four amino acids" }, { key: "b", text: "Several folded polypeptide chains associate" }, { key: "c", text: "It is made from four separate DNA molecules" }, { key: "d", text: "Each chain is an unfolded carbohydrate strand" }], answer: "b", explanation: "Quaternary structure describes association of multiple polypeptide chains. Individual antibody chains also possess lower levels of structure, but their assembly means that tertiary alone is not an adequate description of the complete immunoglobulin.", sectionId: "antibodies-and-antigens", source: { document: "quick-revision", page: 141 }, cognitive: "understanding" },
    { id: "note-biotechnology-019", text: "Which antibody class connects the notes' early primary-response cue with a large secreted pentameric assembly?", options: [{ key: "a", text: "IgA" }, { key: "b", text: "IgE" }, { key: "c", text: "IgM" }, { key: "d", text: "IgD" }], answer: "c", explanation: "IgM is prominent early in a primary immune response and is commonly secreted as a pentamer. The assembly qualification matters because membrane IgM on a B cell is monomeric rather than a circulating pentamer.", sectionId: "antibodies-and-antigens", source: { document: "quick-revision", page: 141 }, cognitive: "recall" },
    { id: "note-biotechnology-020", text: "An allergen cross-links antibody already attached to mast cells, promoting histamine release. Which immunoglobulin class is involved in this classic immediate-allergy pathway?", options: [{ key: "a", text: "IgG" }, { key: "b", text: "IgM" }, { key: "c", text: "IgA" }, { key: "d", text: "IgE" }], answer: "d", explanation: "IgE binds high-affinity receptors on mast cells. Appropriate antigen cross-linking triggers mediator release, including histamine. This explains the source's IgE-allergy association without claiming that every asthma case has the same mechanism.", sectionId: "antibodies-and-antigens", source: { document: "quick-revision", page: 141 }, cognitive: "application" },
    { id: "note-biotechnology-021", text: "Tears, saliva and breast milk share an important antibody contribution to mucosal protection. Which class is the source's common link?", options: [{ key: "a", text: "IgA" }, { key: "b", text: "IgD" }, { key: "c", text: "IgE" }, { key: "d", text: "IgM" }], answer: "a", explanation: "IgA, especially secretory IgA, contributes to protection at mucosal surfaces and occurs in the named secretions. The question asks for their shared source association, not which class is most abundant in blood serum.", sectionId: "antibodies-and-antigens", source: { document: "quick-revision", page: 141 }, cognitive: "recall" },
    { id: "note-biotechnology-022", text: "Which source-listed antibacterial drug most directly blocks bacterial transcription rather than peptidoglycan cross-linking?", options: [{ key: "a", text: "Penicillin" }, { key: "b", text: "Rifampicin" }, { key: "c", text: "Ciprofloxacin" }, { key: "d", text: "Streptomycin" }], answer: "b", explanation: "Rifampicin inhibits bacterial RNA polymerase and therefore transcription. Penicillin targets cell-wall synthesis; ciprofloxacin interferes with DNA topoisomerases, and streptomycin principally affects bacterial protein synthesis.", sectionId: "antibiotics-and-microbial-products", source: { document: "quick-revision", page: 141 }, cognitive: "recall" },
    { id: "note-biotechnology-023", text: "A revision card uses the cue CD to connect a drug with interference in bacterial DNA replication. Which pairing correctly expands the cue?", options: [{ key: "a", text: "Cellulase and DNA cleavage" }, { key: "b", text: "Cytokinin and DNA ligation" }, { key: "c", text: "Ciprofloxacin and DNA synthesis" }, { key: "d", text: "Colchicine and DNA transcription" }], answer: "c", explanation: "The source cue links ciprofloxacin with DNA. More precisely, ciprofloxacin targets bacterial DNA gyrase or topoisomerase IV, disrupting DNA replication; it should not be described as a DNA-joining enzyme.", sectionId: "antibiotics-and-microbial-products", source: { document: "quick-revision", page: 141 }, cognitive: "recall" },
    { id: "note-biotechnology-024", text: "A crop expresses a selected Cry protein from Bacillus thuringiensis. Which outcome is justified without overstating the trait?", options: [{ key: "a", text: "Resistance to every plant virus" }, { key: "b", text: "Complete removal of all weeds" }, { key: "c", text: "Direct fixation of nitrogen gas" }, { key: "d", text: "Resistance to susceptible insect pests" }], answer: "d", explanation: "A suitable Bt Cry protein can act against susceptible target insects. The trait does not imply universal insect control, antiviral resistance, herbicidal action or nitrogen fixation; target specificity is essential to the claim.", sectionId: "biocontrol-and-economic-botany", source: { document: "quick-revision", page: 141 }, cognitive: "understanding" },
    { id: "note-biotechnology-025", text: "Which association explains the nitrogen-enrichment value of Azolla in the rice-field example?", options: [{ key: "a", text: "Azolla with its nitrogen-fixing cyanobacterium" }, { key: "b", text: "Azolla with a milk-coagulating enzyme" }, { key: "c", text: "Azolla with an antibody-producing myeloma" }, { key: "d", text: "Azolla with a peptidoglycan antibiotic" }], answer: "a", explanation: "The source pairs Azolla with Anabaena azollae, a nitrogen-fixing cyanobacterial symbiont. It is the biological association, not an enzyme for cheese making or a medical antibody system, that supports the rice-field use.", sectionId: "biofertilizer-organisms", source: { document: "biology", page: 169 }, cognitive: "understanding" },
    { id: "note-biotechnology-026", text: "Which pair preserves the source distinction between a free-living aerobic and a free-living anaerobic nitrogen fixer, in that order?", options: [{ key: "a", text: "Clostridium; Azotobacter" }, { key: "b", text: "Azotobacter; Clostridium" }, { key: "c", text: "Rhizobium; Acetobacter" }, { key: "d", text: "Acetobacter; Rhizobium" }], answer: "b", explanation: "Azotobacter is the free-living aerobic example and nitrogen-fixing Clostridium the anaerobic example. Rhizobium is associated with legume nodules, while the source uses Acetobacter for acetic-acid production.", sectionId: "biofertilizer-organisms", source: { document: "biology", page: 169 }, cognitive: "recall" },
    { id: "note-biotechnology-027", text: "A student places Rhizobium inside a legume heterocyst. Which replacement fixes the biological location?", options: [{ key: "a", text: "Inside a legume pollen tetrad" }, { key: "b", text: "Inside a legume thylakoid stack" }, { key: "c", text: "Inside a legume root-nodule association" }, { key: "d", text: "Inside a legume antibody-producing cell" }], answer: "c", explanation: "Rhizobia form nitrogen-fixing associations in root nodules. Heterocysts are specialized cyanobacterial cells, not legume structures; the handwritten source has conflated two different nitrogen-fixation contexts.", sectionId: "biofertilizer-organisms", source: { document: "biology", page: 169 }, cognitive: "understanding" },
    { id: "note-biotechnology-028", text: "Fungal hyphae extend the effective soil volume explored by a plant root. Which nutrient benefit is especially linked with VAM in the notes?", options: [{ key: "a", text: "Production of atmospheric oxygen only" }, { key: "b", text: "Replacement of every nitrogen source" }, { key: "c", text: "Complete removal of all soil salts" }, { key: "d", text: "Improved acquisition of phosphate" }], answer: "d", explanation: "Arbuscular mycorrhizal hyphae are particularly important in acquiring relatively immobile phosphate from soil. This is not automatically nitrogen fixation and does not mean all nutrient inputs or all dissolved salts disappear.", sectionId: "mycorrhiza-and-scp", source: { document: "quick-revision", page: 142 }, cognitive: "understanding" },
    { id: "note-biotechnology-029", text: "An illustrative sterile AB plant hybrid has 16 chromosomes, with no homologous partner for each parental chromosome. If its complete chromosome complement doubles, which result is expected?", options: [{ key: "a", text: "AABB with 32 chromosomes" }, { key: "b", text: "AB with 8 chromosomes" }, { key: "c", text: "AAB with 24 chromosomes" }, { key: "d", text: "AABB with 16 chromosomes" }], answer: "a", explanation: "Whole-complement doubling takes 16 to 32 chromosomes and changes AB to AABB. Each parental chromosome can then have a homologous partner. The process does not identify the crop as bread wheat, and it is not merely the addition of one genome set.", sectionId: "hybridization-and-polyploidy", source: { document: "biology", page: 169 }, cognitive: "application" },
    { id: "note-biotechnology-030", text: "Which statement distinguishes a genetically uniform clone from a highly inbred pure line?", options: [{ key: "a", text: "Every clone must be haploid at every locus" }, { key: "b", text: "A uniform clone can retain heterozygous loci" }, { key: "c", text: "Every pure line contains several unrelated species" }, { key: "d", text: "A pure line is defined only by large plant size" }], answer: "b", explanation: "Vegetative multiplication can preserve the same heterozygous genotype throughout a clone, so uniformity does not require homozygosity. A highly inbred pure line is instead characteristically homozygous at many or essentially all loci.", sectionId: "breeding-selection", source: { document: "biology", page: 169 }, cognitive: "understanding" }
  ]
};