window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["carboxylic-acids"] = {
  id: "carboxylic-acids",
  subject: "Chemistry",
  title: "Carboxylic acids and derivatives",
  sections: [
    {
      id: "acid-hydrogen-bonding",
      title: "Boiling points and the hydrogen-bonded dimer",
      sources: [{ document: "quick-revision", page: 83 }],
      html: "<p>The source compares carboxylic acids with aldehydes, ketones and alcohols of comparable molecular mass and attributes the generally higher acid boiling points to strong intermolecular hydrogen bonding.</p><p>Its dimer diagram contains two R-C(=O)-OH molecules joined in a ring by two O-H&middot;&middot;&middot;O=C hydrogen bonds. Each acid molecule donates its hydroxyl hydrogen to the other molecule's carbonyl oxygen. The dotted links are intermolecular hydrogen bonds, not new covalent C-O bonds or the oxygen bridge of an anhydride.</p><p>The source says acids exist as dimers in the vapour state. <strong>Source clarification:</strong> appreciable vapour-phase dimers can exist in equilibrium with monomers, with the proportion depending on temperature and pressure. It is not a claim that every vapour molecule is always dimeric or that aqueous solutions contain only cyclic dimers. Molecular mass, structure and medium also affect boiling-point comparisons.</p>"
    },
    {
      id: "acid-phenol-distinction",
      title: "Distinguishing a simple phenol from a carboxylic acid",
      sources: [{ document: "quick-revision", page: 83 }],
      html: "<table><thead><tr><th>Test</th><th>Phenol</th><th>Carboxylic acid</th></tr></thead><tbody><tr><td>NaHCO<sub>3</sub></td><td>No brisk acid-base gas evolution for simple phenol</td><td>Brisk effervescence of CO<sub>2</sub> in the ordinary positive case</td></tr><tr><td>FeCl<sub>3</sub></td><td>Violet colour for phenol under suitable conditions</td><td>The source prints a buff-coloured precipitate</td></tr></tbody></table><p><strong>Source correction:</strong> the buff precipitate is not a universal FeCl<sub>3</sub> response of every carboxylic acid. Formation of ferric carboxylate species depends on the particular acid, concentration and pH; ferric benzoate can precipitate under suitable conditions. The bicarbonate comparison is the more useful general distinction between an ordinary carboxylic acid and simple phenol.</p><p>The gas follows RCOOH + NaHCO<sub>3</sub> &rarr; RCOONa + CO<sub>2</sub> + H<sub>2</sub>O. Strongly electron-withdrawing substituents can make some phenols much more acidic than phenol itself, so the negative bicarbonate entry must not be extended to every substituted phenol. A sample containing both functional groups can show both kinds of response.</p>"
    },
    {
      id: "acid-ionization-neutralization",
      title: "Acidity, carboxylate resonance and O-H cleavage",
      sources: [{ document: "quick-revision", page: 83 }],
      html: "<p>Ordinary carboxylic acids are stronger acids than ordinary aliphatic alcohols and simple phenol, but weaker than strong mineral acids such as HCl. <strong>Source clarification:</strong> 'weaker than mineral acids' does not include every inorganic acid; acid strength depends on the actual acid and solvent.</p><p>In water, RCOOH + H<sub>2</sub>O &harr; RCOO<sup>-</sup> + H<sub>3</sub>O<sup>+</sup>. The carboxylate anion is resonance stabilized, with negative charge distributed over two oxygen atoms. Its two C-O bonds are equivalent in the ideal unperturbed ion; it is not one permanently localized C=O and one permanently localized C-O<sup>-</sup>.</p><p>The source's O-H-cleavage map is reproduced with full coefficients:</p><ul><li>2RCOOH + 2Na &rarr; 2RCOONa + H<sub>2</sub>.</li><li>RCOOH + NaOH &rarr; RCOONa + H<sub>2</sub>O.</li><li>2RCOOH + Na<sub>2</sub>CO<sub>3</sub> &rarr; 2RCOONa + CO<sub>2</sub> + H<sub>2</sub>O.</li><li>RCOOH + NaHCO<sub>3</sub> &rarr; RCOONa + CO<sub>2</sub> + H<sub>2</sub>O.</li></ul><p><strong>Source correction:</strong> carbonate neutralization requires two monocarboxylic-acid molecules per carbonate, whereas bicarbonate requires one. The sodium-metal branch gives hydrogen; the carbonate and bicarbonate branches give carbon dioxide; sodium hydroxide gives water without either gas.</p>"
    },
    {
      id: "acid-derivative-preparations",
      title: "Replacing the acid OH: chlorides, amides, anhydrides and esters",
      sources: [{ document: "quick-revision", page: 83 }],
      html: "<p>The source labels this family cleavage of the C-OH bond of the carboxyl group. The carbonyl carbon stays in the acyl product; this is not removal of the whole COOH group.</p><table><thead><tr><th>Derivative</th><th>Source reagents and complete reaction</th></tr></thead><tbody><tr><td>Acyl chloride RCOCl</td><td>PCl<sub>3</sub>, PCl<sub>5</sub>, or SOCl<sub>2</sub> in pyridine. With PCl<sub>3</sub>: 3RCOOH + PCl<sub>3</sub> &rarr; 3RCOCl + H<sub>3</sub>PO<sub>3</sub>. With PCl<sub>5</sub>: RCOOH + PCl<sub>5</sub> &rarr; RCOCl + POCl<sub>3</sub> + HCl. With SOCl<sub>2</sub>: RCOOH + SOCl<sub>2</sub> &rarr; RCOCl + SO<sub>2</sub> + HCl.</td></tr><tr><td>Primary amide RCONH<sub>2</sub></td><td>NH<sub>3</sub>, then heat and loss of water. Acid-base reaction first gives ammonium carboxylate; suitable heating dehydrates it to the amide. Net: RCOOH + NH<sub>3</sub> &rarr; RCONH<sub>2</sub> + H<sub>2</sub>O.</td></tr><tr><td>Anhydride RCO-O-COR</td><td>The source lists a second RCOOH with H<sup>+</sup>/heat or P<sub>2</sub>O<sub>5</sub>/heat. The net dehydration is 2RCOOH &rarr; (RCO)<sub>2</sub>O + H<sub>2</sub>O.</td></tr><tr><td>Ester RCOOR'</td><td>R'OH/H<sup>+</sup>, with loss of water: RCOOH + R'OH &harr; RCOOR' + H<sub>2</sub>O.</td></tr></tbody></table><p><strong>Source conditions:</strong> merely mixing an acid with ammonia at room temperature normally gives its ammonium salt, not immediate complete amide formation. Likewise, ordinary heating of any two monocarboxylic-acid molecules does not guarantee clean anhydride formation; effective dehydration or activation is required. The listed P<sub>2</sub>O<sub>5</sub> is a dehydrating reagent. Esterification is reversible, and the alkyl group attached through oxygen comes from R'OH, not from exchanging the acid's carbon skeleton.</p>"
    },
    {
      id: "acid-reduction-decarboxylation",
      title: "Reduction and decarboxylation of the COOH group",
      sources: [{ document: "quick-revision", page: 83 }],
      html: "<p><strong>Reduction:</strong> the source lists LiAlH<sub>4</sub> in ether, or B<sub>2</sub>H<sub>6</sub> in ether, then H<sub>3</sub>O<sup>+</sup>, to convert RCOOH into RCH<sub>2</sub>OH. The original carboxyl carbon becomes the CH<sub>2</sub>OH carbon, so the carbon count is retained. A net hydrogen-equivalent balance is RCOOH + 4[H] &rarr; RCH<sub>2</sub>OH + H<sub>2</sub>O. The aqueous step is work-up after the moisture-sensitive reductant, not a solvent to add at the start.</p><p><strong>Soda-lime decarboxylation:</strong> a sodium carboxylate is heated with NaOH and CaO. RCOONa + NaOH &rarr; RH + Na<sub>2</sub>CO<sub>3</sub>. Starting with the free acid first requires its neutralization. The alkane has one carbon fewer than the acid because the carboxyl carbon enters carbonate.</p><p><strong>Source correction:</strong> the decarboxylation arrow prints RX, although no halogen source is present. The hydrocarbon product is RH, not RX. Sodium butanoate, CH<sub>3</sub>CH<sub>2</sub>CH<sub>2</sub>COONa, therefore gives propane, not a propyl halide or butane.</p>"
    },
    {
      id: "hvz-aromatic-substitution",
      title: "Alpha halogenation and aromatic ring substitution",
      sources: [{ document: "quick-revision", page: 83 }],
      html: "<p><strong>Hell-Volhard-Zelinsky reaction:</strong> RCH<sub>2</sub>COOH is treated first with X<sub>2</sub>/red phosphorus, then water, to give RCHXCOOH, an alpha-halocarboxylic acid. The alpha carbon is the carbon immediately next to COOH. At least one alpha hydrogen is needed in the ordinary reaction; the typical halogens are bromine or chlorine. The carboxyl group is recovered on hydrolysis and the carbon skeleton is retained.</p><p><strong>Aromatic acids:</strong> a COOH group attached directly to benzene deactivates the ring toward electrophilic substitution and directs mainly meta. The source depicts the following independent transformations of benzoic acid:</p><ul><li>Br<sub>2</sub>, FeBr<sub>3</sub> and heat give 3-bromobenzoic acid, with Br at carbon 3 relative to COOH, plus HBr.</li><li>Concentrated HNO<sub>3</sub>/H<sub>2</sub>SO<sub>4</sub> give 3-nitrobenzoic acid plus H<sub>2</sub>O.</li></ul><p><strong>Source arrow correction:</strong> the bromination arrow is drawn from the brominated ring toward benzoic acid. Its reagent label describes bromination, so the chemically correct direction is benzoic acid &rarr; meta-bromobenzoic acid, not reductive removal of bromine. The two ring products are separate reactions, not a sequence in which bromine must be removed before nitration.</p>"
    },
    {
      id: "amine-boundary-classification",
      title: "Amines beginning on page 83: degree and shape",
      sources: [{ document: "quick-revision", page: 83 }],
      html: "<p>The right-hand page begins the Amines chapter. All its legible introductory material is retained here because it lies on this topic's assigned page.</p><table><thead><tr><th>Amine class</th><th>Groups directly attached to N</th></tr></thead><tbody><tr><td>Primary, RNH<sub>2</sub></td><td>One alkyl or aryl group and two hydrogens</td></tr><tr><td>Secondary, R<sub>2</sub>NH</td><td>Two alkyl and/or aryl groups and one hydrogen</td></tr><tr><td>Tertiary, R<sub>3</sub>N</td><td>Three alkyl and/or aryl groups and no N-H hydrogen</td></tr></tbody></table><p>Amine degree counts the carbon groups bonded directly to nitrogen, not the degree of the neighbouring carbon. Different R groups are allowed; a methyl and an ethyl group on the same NH nitrogen make a secondary amine.</p><p>The source describes nitrogen as sp<sup>3</sup>, pyramidal, with C-N-R angles below 109.5&deg;, where the last R may mean C or H in that sentence. <strong>Source qualification:</strong> simple amines commonly have three bonds and a lone pair in a pyramidal arrangement, but exact angles are not uniformly below 109.5&deg;. Substituent crowding and lone-pair conjugation can alter angles and planarity, particularly in arylamines. The simple sp<sup>3</sup> picture is not a universal description of every nitrogen-containing functional group.</p>"
    },
    {
      id: "amine-reduction-preparations",
      title: "Page 83: reductions to amines and carbon retention",
      sources: [{ document: "quick-revision", page: 83 }],
      html: "<p>The source routes several precursors toward a central RNH<sub>2</sub> box. Each route must retain or lose carbon according to its actual chemistry, rather than reuse R with a silently changed meaning.</p><ul><li><strong>Nitrile reduction, source heading Mendius reduction:</strong> RCN + 4[H] &rarr; RCH<sub>2</sub>NH<sub>2</sub>. The arrow lists H<sub>2</sub>/Ni, LiAlH<sub>4</sub>/ether, or Na-Hg in C<sub>2</sub>H<sub>5</sub>OH as reducing alternatives. The classical Mendius name is associated with nitrile reduction using sodium in alcohol; the other labels are alternative reduction systems, not all the same reagent. The nitrile carbon becomes CH<sub>2</sub>.</li><li><strong>Nitro-compound reduction:</strong> RNO<sub>2</sub> + 6[H] &rarr; RNH<sub>2</sub> + 2H<sub>2</sub>O. The source lists Sn/HCl, Fe/HCl, H<sub>2</sub>/Pd, or LiAlH<sub>4</sub>/ether. Nitrobenzene gives aniline. Acidic metal reductions initially give an ammonium salt; appropriate work-up frees the amine.</li><li><strong>Amide reduction:</strong> RCONH<sub>2</sub> + 4[H] &rarr; RCH<sub>2</sub>NH<sub>2</sub> + H<sub>2</sub>O as a net hydrogen-equivalent balance. LiAlH<sub>4</sub>/ether followed by work-up is the standard source-listed route. The source also prints Na/C<sub>2</sub>H<sub>5</sub>OH; that bare label is not a general substitute for controlled amide reduction and is not used as a scored reagent claim.</li></ul><p><strong>Source correction:</strong> nitrile and amide reductions do not remove the nitrile or carbonyl carbon. Their direct product is RCH<sub>2</sub>NH<sub>2</sub>, not RNH<sub>2</sub> with the original R unchanged. Thus ethanamide gives ethylamine on LiAlH<sub>4</sub> reduction, whereas its Hofmann degradation gives methylamine. The distinction is a one-carbon difference, not just a change of reaction name.</p>"
    },
    {
      id: "ammonolysis-hofmann",
      title: "Page 83: ammonolysis and Hofmann bromamide degradation",
      sources: [{ document: "quick-revision", page: 83 }],
      html: "<p><strong>Hofmann ammonolysis:</strong> the source heats RX with NH<sub>3</sub> at 373 K to obtain a primary amine. An overall equation including neutralization by excess ammonia is RX + 2NH<sub>3</sub> &rarr; RNH<sub>2</sub> + NH<sub>4</sub>X. An alkylammonium intermediate forms first. Further alkylation can give secondary and tertiary amines and quaternary ammonium salts; a single clean primary-amine product is not guaranteed by this general arrow.</p><p><strong>Hofmann bromamide degradation:</strong> RCONH<sub>2</sub> with Br<sub>2</sub>/KOH and heat gives RNH<sub>2</sub>, losing the amide carbonyl carbon. The balanced alkaline equation is RCONH<sub>2</sub> + Br<sub>2</sub> + 4KOH &rarr; RNH<sub>2</sub> + 2KBr + K<sub>2</sub>CO<sub>3</sub> + 2H<sub>2</sub>O. The carbonyl carbon appears in carbonate, while R becomes attached to nitrogen.</p><p>Ammonolysis replaces a leaving group on an alkyl carbon and retains that carbon skeleton. Bromamide degradation is a rearrangement of a primary amide with loss of one carbon. Despite the similar Hofmann names, these are different transformations.</p>"
    },
    {
      id: "gabriel-phthalimide",
      title: "Page 83: Gabriel phthalimide synthesis",
      sources: [{ document: "quick-revision", page: 83 }],
      html: "<p>The source's fused-ring reagent is phthalimide, C<sub>6</sub>H<sub>4</sub>(CO)<sub>2</sub>NH. Its five-membered imide ring contains N-H between two carbonyl carbons and is fused to a benzene ring. The sequence printed beside it is:</p><ol><li>Alcoholic KOH removes the imide N-H proton to give potassium phthalimide.</li><li>RX and heat alkylate the nitrogen by substitution, producing N-alkylphthalimide and KX.</li><li>Acidic or alkaline aqueous hydrolysis with heat releases the primary amine and phthalic-acid-derived products. Under acidic hydrolysis the amine is protonated until subsequent work-up.</li></ol><p>The method prepares primary alkylamines without the repeated alkylation typical of direct ammonia alkylation. Its usual alkylation step is SN2, so a suitable methyl or primary alkyl halide is preferred.</p><p>The source correctly states that ordinary Gabriel synthesis does not prepare primary aromatic amines such as aniline from an aryl halide: the necessary SN2 displacement does not occur at that aryl carbon. This restriction does not exclude benzylamine, C<sub>6</sub>H<sub>5</sub>CH<sub>2</sub>NH<sub>2</sub>, whose nitrogen is attached to a side-chain carbon rather than directly to the ring.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 83, status: "transcribed", sectionIds: ["acid-hydrogen-bonding", "acid-phenol-distinction", "acid-ionization-neutralization", "acid-derivative-preparations", "acid-reduction-decarboxylation", "hvz-aromatic-substitution", "amine-boundary-classification", "amine-reduction-preparations", "ammonolysis-hofmann", "gabriel-phthalimide"], unresolved: [] }
  ],
  questions: [
    { id: "note-carboxylic-acids-001", text: "How are the two molecules connected in the usual cyclic carboxylic-acid dimer?", options: [{ key: "a", text: "By two intermolecular hydrogen bonds" }, { key: "b", text: "By two new carbon-carbon single bonds" }, { key: "c", text: "By one covalent anhydride oxygen bridge" }, { key: "d", text: "By one shared carbonyl carbon atom" }], answer: "a", explanation: "Each molecule's OH donates a hydrogen bond to the other molecule's carbonyl oxygen. The two dotted O-H...O links form a hydrogen-bonded ring without covalent condensation.", sectionId: "acid-hydrogen-bonding", source: { document: "quick-revision", page: 83 }, cognitive: "recall" },
    { id: "note-carboxylic-acids-002", text: "Which interaction explains the source's generally high boiling points of carboxylic acids compared with carbonyl compounds of similar mass?", options: [{ key: "a", text: "Complete formation of gaseous ions" }, { key: "b", text: "Strong intermolecular hydrogen bonding" }, { key: "c", text: "Absence of any intermolecular attraction" }, { key: "d", text: "Breaking of every carbon-carbon bond" }], answer: "b", explanation: "Carboxylic acids can form strong intermolecular O-H...O interactions and associated structures. More energy is generally required to separate those molecules into the vapour.", sectionId: "acid-hydrogen-bonding", source: { document: "quick-revision", page: 83 }, cognitive: "understanding" },
    { id: "note-carboxylic-acids-003", text: "Which observation with aqueous sodium bicarbonate best separates an ordinary carboxylic acid from simple phenol?", options: [{ key: "a", text: "A silver mirror from the acid" }, { key: "b", text: "Violet colour from the acid" }, { key: "c", text: "Carbon dioxide effervescence from the acid" }, { key: "d", text: "Hydrogen evolution from the phenol" }], answer: "c", explanation: "An ordinary carboxylic acid protonates bicarbonate, producing CO2, water and a carboxylate salt. Simple phenol normally does not produce this brisk bicarbonate effervescence.", sectionId: "acid-phenol-distinction", source: { document: "quick-revision", page: 83 }, cognitive: "understanding" },
    { id: "note-carboxylic-acids-004", text: "How should the source's buff-precipitate FeCl3 entry for carboxylic acids be interpreted?", options: [{ key: "a", text: "Every carboxylic acid must give it at any pH" }, { key: "b", text: "Every phenol must give it instead of a colour" }, { key: "c", text: "The precipitate uniquely proves any acid identity" }, { key: "d", text: "The response depends on the acid and conditions" }], answer: "d", explanation: "Ferric-carboxylate complexation and precipitation depend on the acid, pH and concentration. The table's buff precipitate is not a universal diagnostic of all carboxylic acids.", sectionId: "acid-phenol-distinction", source: { document: "quick-revision", page: 83 }, cognitive: "understanding" },
    { id: "note-carboxylic-acids-005", text: "What is the correct idealized description of the two C-O bonds in a carboxylate ion?", options: [{ key: "a", text: "Equivalent through resonance delocalization" }, { key: "b", text: "One permanently single and one permanently triple" }, { key: "c", text: "Both absent until protonation occurs" }, { key: "d", text: "Both ordinary localized carbon-oxygen double bonds" }], answer: "a", explanation: "The two major carboxylate contributors interchange which oxygen carries the formal double bond. The real ion has delocalized bonding and equivalent C-O bonds in the ideal model.", sectionId: "acid-ionization-neutralization", source: { document: "quick-revision", page: 83 }, cognitive: "understanding" },
    { id: "note-carboxylic-acids-006", text: "Complete reaction of 0.30 mol of a monocarboxylic acid with excess sodium metal releases how much H2?", options: [{ key: "a", text: "0.30 mol of H2" }, { key: "b", text: "0.15 mol of H2" }, { key: "c", text: "0.60 mol of H2" }, { key: "d", text: "0.90 mol of H2" }], answer: "b", explanation: "Two acid molecules supply the two hydrogen atoms of one H2 molecule. The hydrogen amount is therefore half the acid amount: half of 0.30 mol is 0.15 mol H2.", sectionId: "acid-ionization-neutralization", source: { document: "quick-revision", page: 83 }, cognitive: "application" },
    { id: "note-carboxylic-acids-007", text: "When 0.40 mol of a monocarboxylic acid exactly neutralizes sodium carbonate, how much CO2 forms?", options: [{ key: "a", text: "0.10 mol of CO2" }, { key: "b", text: "0.40 mol of CO2" }, { key: "c", text: "0.20 mol of CO2" }, { key: "d", text: "0.80 mol of CO2" }], answer: "c", explanation: "Carbonate consumes two acid equivalents per CO2 produced: 2RCOOH + Na2CO3 gives 2RCOONa + CO2 + H2O. Thus 0.40 mol acid generates 0.20 mol CO2.", sectionId: "acid-ionization-neutralization", source: { document: "quick-revision", page: 83 }, cognitive: "application" },
    { id: "note-carboxylic-acids-008", text: "Which organic product results when ethanoic acid is converted to its acid chloride with SOCl2?", options: [{ key: "a", text: "CH3CH2Cl" }, { key: "b", text: "CH3Cl" }, { key: "c", text: "CH2ClCOOH" }, { key: "d", text: "CH3COCl" }], answer: "d", explanation: "Thionyl chloride replaces the OH of COOH by Cl while retaining the carbonyl carbon and oxygen. Ethanoic acid therefore gives ethanoyl chloride, CH3COCl.", sectionId: "acid-derivative-preparations", source: { document: "quick-revision", page: 83 }, cognitive: "application" },
    { id: "note-carboxylic-acids-009", text: "What normally forms first when ethanoic acid and ammonia are mixed before any dehydrating heating step?", options: [{ key: "a", text: "Ammonium ethanoate" }, { key: "b", text: "Ethanamide exclusively" }, { key: "c", text: "Ethylamine exclusively" }, { key: "d", text: "Ethanoic anhydride" }], answer: "a", explanation: "The immediate process is acid-base proton transfer, yielding ammonium ethanoate. Dehydration of a suitable ammonium carboxylate on heating is a separate amide-forming step.", sectionId: "acid-derivative-preparations", source: { document: "quick-revision", page: 83 }, cognitive: "understanding" },
    { id: "note-carboxylic-acids-010", text: "In the ideal formation of one symmetrical anhydride molecule from two monocarboxylic-acid molecules, what small molecule is eliminated?", options: [{ key: "a", text: "One molecule of H2" }, { key: "b", text: "One molecule of H2O" }, { key: "c", text: "Two molecules of H2O" }, { key: "d", text: "One molecule of CO2" }], answer: "b", explanation: "Combining two RCOOH units to RCO-O-COR removes one H2O. The carbonyl carbons are retained, distinguishing dehydration from decarboxylation.", sectionId: "acid-derivative-preparations", source: { document: "quick-revision", page: 83 }, cognitive: "understanding" },
    { id: "note-carboxylic-acids-011", text: "Propanoic acid undergoes the Hell-Volhard-Zelinsky reaction with bromine/red phosphorus followed by water. Where is bromine introduced?", options: [{ key: "a", text: "At carbon 3, giving 3-bromopropanoic acid" }, { key: "b", text: "At oxygen, giving a carboxylic hypobromite" }, { key: "c", text: "At carbon 2, giving 2-bromopropanoic acid" }, { key: "d", text: "At carbon 1, giving propanoyl bromide as final acid" }], answer: "c", explanation: "HVZ halogenates an alpha C-H position. In CH3CH2COOH the alpha carbon is carbon 2, so hydrolysis gives CH3CHBrCOOH while retaining COOH.", sectionId: "hvz-aromatic-substitution", source: { document: "quick-revision", page: 83 }, cognitive: "application" },
    { id: "note-carboxylic-acids-012", text: "What hydrocarbon is obtained by soda-lime decarboxylation of sodium butanoate?", options: [{ key: "a", text: "Methane" }, { key: "b", text: "Ethane" }, { key: "c", text: "Butane" }, { key: "d", text: "Propane" }], answer: "d", explanation: "The four-carbon carboxylate loses its carboxyl carbon to carbonate. The remaining three-carbon propyl fragment receives H, forming propane rather than the source's mistaken RX.", sectionId: "acid-reduction-decarboxylation", source: { document: "quick-revision", page: 83 }, cognitive: "application" },
    { id: "note-carboxylic-acids-013", text: "Which monobrominated product follows the COOH directing effect when benzoic acid undergoes electrophilic bromination?", options: [{ key: "a", text: "3-Bromobenzoic acid" }, { key: "b", text: "2-Bromobenzoic acid" }, { key: "c", text: "4-Bromobenzoic acid" }, { key: "d", text: "Benzoyl bromide" }], answer: "a", explanation: "COOH is a ring-deactivating meta director. The expected orientation places Br at carbon 3, while benzoyl bromide would require replacement within the acid group.", sectionId: "hvz-aromatic-substitution", source: { document: "quick-revision", page: 83 }, cognitive: "application" },
    { id: "note-carboxylic-acids-014", text: "Which ester combines the acyl portion of ethanoic acid with the alcohol portion of propan-2-ol?", options: [{ key: "a", text: "Ethyl propanoate" }, { key: "b", text: "Propan-2-yl ethanoate" }, { key: "c", text: "Propan-1-yl ethanoate" }, { key: "d", text: "Methyl butanoate" }], answer: "b", explanation: "The acid provides CH3COO- and the alcohol provides the isopropyl group bonded through oxygen. The ester is CH3COOCH(CH3)2, propan-2-yl ethanoate.", sectionId: "acid-derivative-preparations", source: { document: "quick-revision", page: 83 }, cognitive: "application" },
    { id: "note-carboxylic-acids-015", text: "Propanenitrile, CH3CH2CN, is fully reduced with LiAlH4 and then worked up. Which primary amine retains its nitrile carbon?", options: [{ key: "a", text: "Methanamine" }, { key: "b", text: "Ethanamine" }, { key: "c", text: "Propan-1-amine" }, { key: "d", text: "Butan-1-amine" }], answer: "c", explanation: "The nitrile carbon becomes CH2 next to NH2. CH3CH2CN therefore becomes CH3CH2CH2NH2 with three carbons, not the two-carbon amine implied by dropping that carbon.", sectionId: "amine-reduction-preparations", source: { document: "quick-revision", page: 83 }, cognitive: "application" },
    { id: "note-carboxylic-acids-016", text: "Which amine results from LiAlH4 reduction of ethanamide, CH3CONH2, followed by work-up?", options: [{ key: "a", text: "Methylamine" }, { key: "b", text: "Dimethylamine" }, { key: "c", text: "Propylamine" }, { key: "d", text: "Ethylamine" }], answer: "d", explanation: "Amide reduction changes C=O into CH2 while retaining the nitrogen attachment. CH3CONH2 becomes CH3CH2NH2, so both original carbons remain in ethylamine.", sectionId: "amine-reduction-preparations", source: { document: "quick-revision", page: 83 }, cognitive: "application" },
    { id: "note-carboxylic-acids-017", text: "Which amine instead forms when ethanamide undergoes Hofmann bromamide degradation with Br2/KOH?", options: [{ key: "a", text: "Methylamine" }, { key: "b", text: "Ethylamine" }, { key: "c", text: "Dimethylamine" }, { key: "d", text: "Propylamine" }], answer: "a", explanation: "Hofmann degradation removes the carbonyl carbon and transfers the remaining CH3 group to nitrogen. Ethanamide therefore gives CH3NH2, unlike carbon-retaining LiAlH4 reduction.", sectionId: "ammonolysis-hofmann", source: { document: "quick-revision", page: 83 }, cognitive: "application" },
    { id: "note-carboxylic-acids-018", text: "Which amine cannot be made by the ordinary Gabriel route using the corresponding halide for SN2 alkylation?", options: [{ key: "a", text: "Methylamine from methyl bromide" }, { key: "b", text: "Aniline from chlorobenzene" }, { key: "c", text: "Ethylamine from bromoethane" }, { key: "d", text: "Benzylamine from benzyl bromide" }], answer: "b", explanation: "Chlorobenzene does not undergo the required ordinary SN2 displacement at its aryl carbon. Benzyl bromide reacts at a side-chain carbon, so benzylamine is not excluded by this rule.", sectionId: "gabriel-phthalimide", source: { document: "quick-revision", page: 83 }, cognitive: "understanding" },
    { id: "note-carboxylic-acids-019", text: "An amine nitrogen is bonded to one methyl group, one ethyl group and one hydrogen. What is its class?", options: [{ key: "a", text: "Primary amine" }, { key: "b", text: "Tertiary amine" }, { key: "c", text: "Secondary amine" }, { key: "d", text: "Quaternary ammonium ion" }], answer: "c", explanation: "There are two carbon groups directly attached to nitrogen and one N-H bond. That is the R2NH pattern of a secondary amine, regardless of the sizes of the two alkyl groups.", sectionId: "amine-boundary-classification", source: { document: "quick-revision", page: 83 }, cognitive: "application" },
    { id: "note-carboxylic-acids-020", text: "After complete nitro-group reduction of nitrobenzene and work-up to the free base, what is the organic product?", options: [{ key: "a", text: "Benzylamine" }, { key: "b", text: "Benzamide" }, { key: "c", text: "Benzonitrile" }, { key: "d", text: "Aniline" }], answer: "d", explanation: "Reduction changes the ring-bound NO2 group into NH2 without adding or removing a carbon. The product is C6H5NH2, aniline; benzylamine would contain an extra CH2 group.", sectionId: "amine-reduction-preparations", source: { document: "quick-revision", page: 83 }, cognitive: "application" }
  ]
};