window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["circular-motion"] = {
  id: "circular-motion",
  subject: "Physics",
  title: "Circular motion",
  sections: [
    {
      id: "radial-tangential-acceleration",
      title: "What changes speed and what changes direction",
      sources: [{ document: "quick-revision", page: 7 }, { document: "quick-revision", page: 8 }],
      html: "<p>For a particle constrained to a circle of fixed radius $r$, velocity is tangential. Tangential acceleration changes its speed, while inward radial acceleration changes its direction. In symbols, $a_t=\\frac{dv}{dt}$ and $a_r=\\frac{v^2}{r}=\\omega^2r$, with $v=\\omega r$. The components are perpendicular, so total acceleration has magnitude $a=\\sqrt{a_r^2+a_t^2}$.</p><p><strong>Source clarification:</strong> page 7's 'tangential acceleration = magnitude of velocity' and 'radial acceleration = direction of velocity' describe what each component changes; they are not literal equalities between acceleration and velocity. Nonuniform circular motion generally has both components. Uniform circular motion has $a_t=0$ but $a_r$ remains nonzero at nonzero speed.</p><p>The net inward force required by the circular constraint is $F_r=\\frac{mv^2}{r}=m\\omega^2r$, as listed on page 8. It is the radial resultant of actual forces, such as tension, gravity components, friction or a normal reaction, not an extra force to add again after those forces have already been resolved.</p>"
    },
    {
      id: "vertical-circle-regimes",
      title: "A flexible string in a vertical circle",
      sources: [{ document: "quick-revision", page: 7 }, { document: "quick-revision", page: 8 }],
      html: "<p>Consider a particle on a light inextensible string of length $r$ (the source also uses $l$), initially moving horizontally at the lowest point A with speed $v_A$. Neglect air resistance and other energy transfers. A string can pull but cannot push. Energy at an angle $\\theta$ from the downward vertical gives $v^2=v_A^2-2gr(1-\\cos\\theta)$.</p><ul><li>If $v_A\\geq\\sqrt{5gr}$, the particle can complete a vertical circle without needing negative tension. At the limiting speed the string tension is zero only at the top.</li><li>If $0&lt;v_A\\leq\\sqrt{2gr}$, it turns back at or below the horizontal level and oscillates along an arc rather than completing a circle. At its turning point, $\\cos\\theta_{\\max}=1-\\frac{v_A^2}{2gr}$. With $v_A=0$, it simply stays at the bottom in this ideal model.</li><li>If $\\sqrt{2gr}&lt;v_A&lt;\\sqrt{5gr}$, the string becomes slack above the horizontal before a complete revolution. The particle leaves the constrained circular path and undergoes projectile motion until another contact or string constraint acts.</li></ul><p><strong>Source corrections:</strong> the intermediate-speed line omits its upper comparison sign and says motion 'is ceased'. It is the circular constraint that ceases, not the particle's motion. The last bullet calls $\\sqrt{2gl}$ the minimum horizontal speed 'to reach highest point'. Starting at the bottom, this is the threshold for reaching the side at the pivot's height, not the top of the circle. The string-loop threshold is $\\sqrt{5gl}$. An ideal rigid rod can push as well as pull, so the flexible-string threshold must not be transferred to it; the energy threshold for reaching the top with a rod is $2\\sqrt{gl}$, with nonzero excess needed for passage through the top rather than the limiting zero-speed state.</p>"
    },
    {
      id: "vertical-circle-tensions",
      title: "Top and bottom speeds and tensions",
      sources: [{ document: "quick-revision", page: 8 }, { document: "quick-revision", page: 7 }],
      html: "<p>For the same ideal vertical-circle motion, the bottom radial equation is $T_b-mg=\\frac{mv_b^2}{r}$, while at the top it is $T_t+mg=\\frac{mv_t^2}{r}$. Gravity aids the inward resultant at the top and opposes it at the bottom. Energy between those positions gives $v_b^2-v_t^2=4gr$.</p><p>Subtracting the tension equations therefore gives $T_b-T_t=6mg$. This consolidates the two printed $T_{\\max}-T_{\\min}=6mg$ statements. Tension is largest at the bottom and smallest at the top when the body remains on the full circle and gravity is the only force doing work.</p><p>For the marginal complete revolution, $T_t=0$, $v_t=\\sqrt{gr}$ and $v_b=\\sqrt{5gr}$. Substitution gives $T_b=6mg$. The source's 'minimum tension at maximum point = 0' means the top of the limiting orbit. Its 'minimum tension at minimum point = 6mg' means the minimum bottom tension needed among complete flexible-string revolutions, even though bottom tension is the maximum around that particular orbit.</p><p><strong>Source correction:</strong> the lines $T_{\\max}=\\sqrt{5rg}$ and $T_{\\min}=\\sqrt{rg}$ have speed units, not tension units. They belong to the marginal bottom and top speeds, respectively. The later pair $u_{\\max}=\\sqrt{gr}$ and $u_{\\min}=\\sqrt{5gr}$ reverses maximum/minimum speed labels, or uses them ambiguously for highest/lowest positions. Unambiguous notation is $v_{\\mathrm{top,critical}}=\\sqrt{gr}$ and $v_{\\mathrm{bottom,critical}}=\\sqrt{5gr}$. Actual speeds and tensions can exceed their critical values.</p>"
    },
    {
      id: "coin-on-turntable",
      title: "A coin on a horizontal rotating platform",
      sources: [{ document: "quick-revision", page: 7 }],
      html: "<p>A coin at radius $r$ on a horizontal platform rotating steadily at angular speed $\\omega$ needs inward static friction $f_s=m\\omega^2r$. Since $N=mg$ and $f_s\\leq\\mu_smg$, no slipping requires $m\\omega^2r\\leq\\mu_smg$. Therefore $\\omega\\leq\\sqrt{\\frac{\\mu_sg}{r}}$, or $v\\leq\\sqrt{\\mu_sgr}$.</p><p><strong>Source correction:</strong> the printed equality $\\mu mg=m\\omega^2r$ is the limiting case. Under the shared heading 'Minimum rotational speed', it actually sets a <em>maximum</em> speed for a coin at fixed radius. At slower steady rotation the required static friction is smaller, not automatically equal to its maximum. Coins farther from the axis reach the slipping limit at a lower angular speed for the same surfaces.</p>"
    },
    {
      id: "rotating-cylinder",
      title: "Support against a rotating cylinder wall",
      sources: [{ document: "quick-revision", page: 7 }],
      html: "<p>For an object carried around the inside of a vertical rotating cylinder of radius $r$, the wall normal provides radial acceleration: $N=m\\omega^2r$. Upward static friction must support the object's weight when the floor is absent, so $mg\\leq\\mu_sN$.</p><p>The limiting equality is the source formula $mg=\\mu_s m\\omega^2r$. It gives a genuine minimum angular speed, $\\omega_{\\min}=\\sqrt{\\frac{g}{\\mu_s r}}$. Faster rotation can supply a larger normal reaction and hence a larger available friction limit; actual vertical friction remains $mg$ for no vertical acceleration. The mass cancels from the threshold. This geometry reverses the speed inequality compared with the coin on a horizontal platform.</p>"
    },
    {
      id: "banking-and-wheel-loads",
      title: "Banking, lean and wheel reactions",
      sources: [{ document: "quick-revision", page: 7 }, { document: "quick-revision", page: 8 }],
      html: "<p>For a frictionless road banked at angle $\\theta$ to the horizontal, a vehicle following a horizontal circle has $N\\cos\\theta=mg$ and $N\\sin\\theta=\\frac{mv^2}{r}$. Division gives $\\tan\\theta=\\frac{v^2}{rg}$, equivalently $v=\\sqrt{rg\\tan\\theta}$. The same ratio describes the required lean angle from vertical of an ideal rider whose resultant support force passes through the centre of mass.</p><p><strong>Source correction:</strong> page 7 labels this 'maximum speed', and page 8 repeats the relation. On a frictionless bank it is the one design speed for that angle, not a general maximum safe speed. Friction changes the range of possible speeds; overturning additionally depends on track width, centre-of-mass height and support geometry.</p><p>On a level bend, a vehicle with its centre of mass above the road transfers normal load from its inner wheels to its outer wheels. This is the source statement that the inner-wheel reaction is smaller than the outer-wheel reaction. Sufficient outward load transfer can unload the inner wheels and initiate outward overturning.</p><p>The source also states that low-speed vehicles overturn inward. This is not a general consequence of driving slowly on a level turn. On a sufficiently steep bank, gravity can favour inward/down-bank motion at low speed, but whether the vehicle slides or overturns depends on friction and geometry. The source provides no bank angle or vehicle dimensions to establish such a threshold.</p>"
    },
    {
      id: "rotation-observations",
      title: "Tachometers, bubbles and magnetic deflection",
      sources: [{ document: "quick-revision", page: 7 }],
      html: "<p>A tachometer measures rotational speed, commonly in revolutions per minute. For a reading $n$ in revolutions per minute, angular speed in radians per second is $\\omega=\\frac{2\\pi n}{60}$.</p><p>The source says bubbles in a revolved soda bottle collect near the edges. <strong>Source correction:</strong> in liquid undergoing steady rotation, pressure increases outward from the rotation axis. The pressure-gradient force makes a low-density bubble migrate inward relative to the denser liquid, toward the axis, rather than toward the outermost radius. Gravity can also move it upward. The source does not specify the bottle's orientation, rotation axis or transient motion, so a particular bottle wall or edge cannot be identified.</p><p>A magnetic force $\\vec F=q\\vec v\\times\\vec B$ is perpendicular to the charged particle's velocity and does no work. With no electric field or other work-producing force, the particle's speed and kinetic energy stay unchanged while its velocity and momentum direction can change. A velocity perpendicular to a uniform magnetic field produces circular motion; a parallel component produces helical motion, and a wholly parallel velocity is not deflected. This states the conditions behind the source's magnetic-field speed-versus-direction distinction.</p>"
    },
    {
      id: "centrifugal-frame-examples",
      title: "Centrifugal descriptions and a rotating bucket",
      sources: [{ document: "quick-revision", page: 7 }],
      html: "<p>In a reference frame rotating with angular speed $\\omega$, centrifugal force on a body at radius $r$ is the apparent force of magnitude $m\\omega^2r$ directed radially outward. It accounts for the frame's acceleration; it is not a second real outward force that cancels the inward force in an inertial-frame circular-motion equation.</p><p>During a vehicle's turn, a passenger tends to continue along the previous tangent. The seat or vehicle side supplies the inward force needed to turn the passenger. The passenger feels pressed toward the outer side, which the turning frame describes using an outward inertial force.</p><p>The source's water-in-a-rotated-bucket example requires sufficient speed near the top of a vertical circle. At the top, gravity and the bucket's contact force both act toward the circle centre, so $mg+N=\\frac{mv^2}{r}$. Water can stay in contact if $N\\geq0$, requiring $v^2\\geq gr$. Merely rotating the bucket at any speed does not guarantee retention. In the co-rotating description, the apparent outward effect is away from the centre; the inertial description uses gravity and contact forces only.</p>"
    },
    {
      id: "momentum-and-velocity-change",
      title: "Angular momentum and a finite change in velocity",
      sources: [{ document: "quick-revision", page: 8 }],
      html: "<p>For a particle moving in a circle, angular momentum about the centre has magnitude $L=mrv=I\\omega$, where $I=mr^2$. Combining these relations with $F_r=m\\omega^2r$ gives the source expression $F_r=\\frac{L^2}{Ir}$. Here capital $L$ is angular momentum, not a length, and the moment of inertia is that of the particle about the circle axis. The expression is not an unrestricted net-force formula for an arbitrary extended rotor.</p><p>If two velocity vectors have the same magnitude $v$ and enclose angle $\\theta$, their difference has magnitude $|\\Delta\\vec v|=\\sqrt{2v^2(1-\\cos\\theta)}$, or $|\\Delta\\vec v|=2v\\left|\\sin\\frac{\\theta}{2}\\right|$. For a direction change between zero and $180^\\circ$, this is the printed $2v\\sin\\frac{\\theta}{2}$. At a half-turn it is $2v$; after a full revolution it is zero even though the particle has accelerated continuously. Average acceleration magnitude over a specified interval is $\\frac{|\\Delta\\vec v|}{\\Delta t}$, not generally the instantaneous radial acceleration.</p>"
    },
    {
      id: "rotating-extended-body-force",
      title: "The unidentified other-end force formula",
      sources: [{ document: "quick-revision", page: 8 }],
      html: "<p>The source lists $F=\\frac{ml\\omega^2}{2}$ with only the description 'Force exerted on other end'. It does not show a body, rotation axis or endpoint. A consistent conditional model is a uniform rod of total mass $m$ and length $l$, rotating horizontally at fixed angular speed about one end, with no other horizontal force.</p><p>The centre of mass is at radius $\\frac{l}{2}$, so the required net radial support force is $F=m\\omega^2\\frac{l}{2}$. Equivalently, summing $\\omega^2x\\,dm$ over a uniform radial distribution yields $\\frac{ml\\omega^2}{2}$. The force at a free outer end is not this support reaction. Because 'other end' is unlabelled in the source, the printed expression cannot identify a particular support or free end without an additional diagram.</p>"
    },
    {
      id: "centre-of-mass",
      title: "Centre of mass and fragmentation",
      sources: [{ document: "quick-revision", page: 8 }],
      html: "<p>For fixed particle masses, the centre-of-mass position is $\\vec R_{\\mathrm{CM}}=\\frac{\\sum_i m_i\\vec r_i}{M}$, where $M=\\sum_i m_i$. Measured relative to that point, the first mass moment is zero: $\\sum_i m_i(\\vec r_i-\\vec R_{\\mathrm{CM}})=0$. This is the source's 'sum of moment of mass about CM = 0'; it is not a statement that the moment of inertia is zero.</p><p>The motion of the centre of mass describes the system's overall translational motion. Its acceleration is controlled by the resultant external force, $M\\vec a_{\\mathrm{CM}}=\\vec F_{\\mathrm{ext}}$. Internal forces can change relative motion, shape or rotation without changing the total momentum on their own.</p><p>The source contrasts an unchanged centre-of-mass location in rotation with a changed location in translation. This is correct for pure rotation about a stationary centre of mass. Rotation about a different fixed pivot can make the centre of mass move in a circle, so 'rotation' alone does not imply a fixed centre of mass.</p><p>The breakup shorthand says 'CM on same vertical line'. This holds when the original centre of mass has zero horizontal velocity and there is no horizontal external force. In uniform gravity, internal breakup does not change the original centre-of-mass trajectory: a vertically moving body's centre of mass stays on that vertical line, while an obliquely launched projectile's centre of mass continues on its parabola until external interactions such as fragment impacts intervene. Initial motion is necessary to interpret the printed vertical-line claim.</p>"
    },
    {
      id: "rolling-descent-time",
      title: "Rolling descent and radius of gyration",
      sources: [{ document: "quick-revision", page: 8 }],
      html: "<p>For a rigid body rolling without slipping down a fixed incline, write $I=mk^2$ about the centre of mass and let $R$ be the rolling radius. Gravity supplies both translational and rotational kinetic energy. Combining translation with rotational dynamics gives $a=\\frac{g\\sin\\theta}{1+\\frac{k^2}{R^2}}$, assuming adequate static friction and negligible rolling resistance.</p><p>For an equal travel distance $s$ from rest, $t=\\sqrt{\\frac{2s}{g\\sin\\theta}}\\sqrt{1+\\frac{k^2}{R^2}}$. <strong>Source correction:</strong> the printed $t\\propto(1+\\frac{K^2}{R^2})$ lacks the square root if $t$ means this descent time and capital K denotes radius of gyration. The unsquared factor is proportional to $t^2$, not $t$. The source does not actually define these symbols or the travel geometry, so the correction is tied to the explicitly stated standard rolling experiment.</p><p>For a thin ring, $\\frac{k^2}{R^2}=1$; for a uniform solid sphere it is $\\frac25$. Thus, among the familiar ring, cylindrical and spherical bodies released under the same conditions, the ring takes the longest time and the uniform solid sphere the shortest, as in the source's maximum/minimum comparison. For a ring and solid sphere, $\\frac{t_{\\mathrm{ring}}}{t_{\\mathrm{sphere}}}=\\sqrt{\\frac{2}{\\frac{7}{5}}}=\\sqrt{\\frac{10}{7}}$. The ordering is for rolling without sliding, not unrestricted slipping.</p>"
    },
    {
      id: "rolling-point-fragments",
      title: "Surface-point speeds with an undefined angle",
      sources: [{ document: "quick-revision", page: 8 }],
      html: "<p>The final solid-sphere lines read $2v\\cos(45^\\circ+\\frac{\\theta}{2})$ 'Above CM' and $2v\\cos(45^\\circ-\\frac{\\theta}{2})$ 'Below CM'. The source provides neither a point diagram nor a definition of $\\theta$, the reference direction or the sphere's plane of motion. These expressions and labels cannot be matched safely to particular points.</p><p>The reliable general relation is $\\vec v_P=\\vec v_{\\mathrm{CM}}+\\vec\\omega\\times\\vec r_P$, where $\\vec r_P$ is measured from the centre of mass. For pure rolling on level ground, the bottom contact point is instantaneously at rest and the top point has speed twice the centre-of-mass speed. Those checks help test a fully labelled diagram, but they do not recover the missing angle convention in the two printed formulas. The unidentified above/below-CM expressions are retained as unresolved source material and are not used as scored answers.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 7, status: "partial", sectionIds: ["radial-tangential-acceleration", "vertical-circle-regimes", "vertical-circle-tensions", "coin-on-turntable", "rotating-cylinder", "banking-and-wheel-loads", "rotation-observations", "centrifugal-frame-examples"], unresolved: ["The intermediate vertical-circle range omits the comparison sign before sqrt(5gl); its intended interval is reconstructed from the adjoining regimes and explicitly corrected.", "sqrt(2gl) as the minimum horizontal velocity to reach highest point has no launch-point or target-point diagram; it reaches the horizontal side from the bottom, not the top of a taut-string circle.", "The soda-bottle bubbles-near-edges claim does not specify the rotation axis, bottle orientation or transient motion; only the steady co-rotating-fluid inward drift can be established.", "Low-speed inward overturning and the maximum-speed label on tan(theta)=v^2/(rg) omit the bank angle convention, friction and vehicle support geometry."] },
    { document: "quick-revision", page: 8, status: "partial", sectionIds: ["radial-tangential-acceleration", "vertical-circle-regimes", "vertical-circle-tensions", "banking-and-wheel-loads", "momentum-and-velocity-change", "rotating-extended-body-force", "centre-of-mass", "rolling-descent-time", "rolling-point-fragments"], unresolved: ["F=ml*omega^2/2, Force exerted on other end does not identify the rotating body, axis or the endpoint; a uniform-rod support-force model is supplied only conditionally.", "Body breaks: CM on same vertical line omits initial centre-of-mass velocity and external forces; the vertical trajectory is only a conditional case.", "The rolling proportionality t proportional to (1+K^2/R^2) leaves t, K and the travel geometry undefined; for descent time over a fixed distance from rest it needs a square root.", "The final above-CM and below-CM speeds 2v cos(45 degrees plus or minus theta/2) lack the point diagram, theta definition and reference direction, so their labels remain unresolved."] }
  ],
  questions: [
    { id: "note-circular-motion-001", text: "A bead speeds up while remaining on a circular wire of fixed radius. Which roles do its two acceleration components play?", options: [{ key: "a", text: "Radial changes speed; tangential changes direction." }, { key: "b", text: "Tangential changes speed; radial changes direction." }, { key: "c", text: "Both components change only the speed." }, { key: "d", text: "Both components change only the direction." }], answer: "b", explanation: "The tangential component is along the instantaneous direction of travel and changes the velocity magnitude. The inward radial component turns the velocity vector. They are perpendicular components, not interchangeable names for the same acceleration.", sectionId: "radial-tangential-acceleration", source: { document: "quick-revision", page: 7 }, cognitive: "understanding" },
    { id: "note-circular-motion-002", text: "At one instant, a particle moves at $4.0\\,\\mathrm{m\\,s^{-1}}$ on a circle of radius $2.0\\,\\mathrm m$, with tangential acceleration $6.0\\,\\mathrm{m\\,s^{-2}}$. What is its total acceleration magnitude?", options: [{ key: "a", text: "$6.0\\,\\mathrm{m\\,s^{-2}}$" }, { key: "b", text: "$8.0\\,\\mathrm{m\\,s^{-2}}$" }, { key: "c", text: "$14\\,\\mathrm{m\\,s^{-2}}$" }, { key: "d", text: "$10\\,\\mathrm{m\\,s^{-2}}$" }], answer: "d", explanation: "The radial component is $a_r=\\frac{4^2}{2}=8\\,\\mathrm{m\\,s^{-2}}$. Radial and tangential components are perpendicular, so the resultant is $\\sqrt{8^2+6^2}=10\\,\\mathrm{m\\,s^{-2}}$, rather than their arithmetic sum.", sectionId: "radial-tangential-acceleration", source: { document: "quick-revision", page: 7 }, cognitive: "application" },
    { id: "note-circular-motion-003", text: "A bob on a light flexible string of length $0.80\\,\\mathrm m$ is launched from the lowest point. Neglecting losses, what is the minimum bottom speed for a complete vertical circle when $g=10\\,\\mathrm{m\\,s^{-2}}$?", options: [{ key: "a", text: "$6.32\\,\\mathrm{m\\,s^{-1}}$" }, { key: "b", text: "$2.83\\,\\mathrm{m\\,s^{-1}}$" }, { key: "c", text: "$4.00\\,\\mathrm{m\\,s^{-1}}$" }, { key: "d", text: "$5.66\\,\\mathrm{m\\,s^{-1}}$" }], answer: "a", explanation: "At the top, nonnegative tension requires $v_t^2\\geq gr$. Climbing through height $2r$ uses an additional $4gr$ in squared speed, so $v_b^2\\geq5gr$. The limiting bottom speed is $\\sqrt{5\\times10\\times0.80}=\\sqrt{40}=6.32\\,\\mathrm{m\\,s^{-1}}$.", sectionId: "vertical-circle-regimes", source: { document: "quick-revision", page: 7 }, cognitive: "application" },
    { id: "note-circular-motion-004", text: "A string pendulum starts from its lowest point with $v_A^2=gr$. In loss-free motion, at what angle from the downward vertical does it first stop and turn back?", options: [{ key: "a", text: "$30^\\circ$" }, { key: "b", text: "$45^\\circ$" }, { key: "c", text: "$60^\\circ$" }, { key: "d", text: "$90^\\circ$" }], answer: "c", explanation: "At the turning point kinetic energy is zero. Energy gives $gr=2gr(1-\\cos\\theta)$, hence $\\cos\\theta=\\frac12$ and $\\theta=60^\\circ$. The point is below the horizontal, so the string does not need negative tension to reach it.", sectionId: "vertical-circle-regimes", source: { document: "quick-revision", page: 7 }, cognitive: "application" },
    { id: "note-circular-motion-005", text: "A bob is launched from the bottom of a vertical string circle with $v_A^2=3gr$. Which event occurs before a full revolution, assuming no losses?", options: [{ key: "a", text: "The string slackens and the bob follows a projectile path." }, { key: "b", text: "The string stays taut and the bob completes the circle." }, { key: "c", text: "The bob stops at the bottom and remains motionless." }, { key: "d", text: "The bob reverses below the horizontal with positive tension." }], answer: "a", explanation: "The launch speed lies between $\\sqrt{2gr}$ and $\\sqrt{5gr}$. It is enough to pass the horizontal but not enough for a full taut-string revolution. The tension reaches zero above the horizontal, after which gravity continues to move the bob along a projectile path.", sectionId: "vertical-circle-regimes", source: { document: "quick-revision", page: 7 }, cognitive: "understanding" },
    { id: "note-circular-motion-006", text: "A $0.25\\,\\mathrm{kg}$ bob completes a loss-free vertical string circle. For $g=10\\,\\mathrm{m\\,s^{-2}}$, how much greater is the bottom tension than the top tension?", options: [{ key: "a", text: "$5.0\\,\\mathrm N$" }, { key: "b", text: "$15\\,\\mathrm N$" }, { key: "c", text: "$10\\,\\mathrm N$" }, { key: "d", text: "$2.5\\,\\mathrm N$" }], answer: "b", explanation: "Energy gives $v_b^2-v_t^2=4gr$. Subtracting the radial-force equations adds a further $2mg$, so $T_b-T_t=6mg=6\\times0.25\\times10=15\\,\\mathrm N$. The difference is independent of radius under the stated conditions.", sectionId: "vertical-circle-tensions", source: { document: "quick-revision", page: 8 }, cognitive: "application" },
    { id: "note-circular-motion-007", text: "For the marginal complete revolution of a bob on a flexible string, what is the string tension exactly at the highest point?", options: [{ key: "a", text: "$mg$" }, { key: "b", text: "$2mg$" }, { key: "c", text: "$6mg$" }, { key: "d", text: "$0$" }], answer: "d", explanation: "In the limiting orbit, gravity alone supplies the required inward force at the top: $mg=\\frac{mv_t^2}{r}$. The top tension is therefore zero. A faster complete revolution would have positive top tension.", sectionId: "vertical-circle-tensions", source: { document: "quick-revision", page: 8 }, cognitive: "recall" },
    { id: "note-circular-motion-008", text: "A coin lies $0.20\\,\\mathrm m$ from the axis of a horizontal turntable. If $\\mu_s=0.50$ and $g=10\\,\\mathrm{m\\,s^{-2}}$, what is its largest no-slip steady angular speed?", options: [{ key: "a", text: "$2.5\\,\\mathrm{rad\\,s^{-1}}$" }, { key: "b", text: "$10\\,\\mathrm{rad\\,s^{-1}}$" }, { key: "c", text: "$5.0\\,\\mathrm{rad\\,s^{-1}}$" }, { key: "d", text: "$25\\,\\mathrm{rad\\,s^{-1}}$" }], answer: "c", explanation: "The largest required radial friction equals the static limit: $m\\omega^2r=\\mu_smg$. Thus $\\omega_{\\max}=\\sqrt{\\frac{0.50\\times10}{0.20}}=5.0\\,\\mathrm{rad\\,s^{-1}}$. It is an upper limit; smaller steady angular speeds also permit no slipping.", sectionId: "coin-on-turntable", source: { document: "quick-revision", page: 7 }, cognitive: "application" },
    { id: "note-circular-motion-009", text: "An object is held against the inside of a vertical rotating cylinder of radius $0.50\\,\\mathrm m$. With $\\mu_s=0.80$ and $g=10\\,\\mathrm{m\\,s^{-2}}$, what minimum angular speed prevents it sliding down?", options: [{ key: "a", text: "$2.0\\,\\mathrm{rad\\,s^{-1}}$" }, { key: "b", text: "$4.0\\,\\mathrm{rad\\,s^{-1}}$" }, { key: "c", text: "$5.0\\,\\mathrm{rad\\,s^{-1}}$" }, { key: "d", text: "$8.0\\,\\mathrm{rad\\,s^{-1}}$" }], answer: "c", explanation: "Here the wall reaction is $N=m\\omega^2r$ and its friction must balance $mg$. Thus $\\omega_{\\min}=\\sqrt{\\frac{10}{0.80\\times0.50}}=5.0\\,\\mathrm{rad\\,s^{-1}}$. This is a lower limit because the normal reaction grows with rotational speed.", sectionId: "rotating-cylinder", source: { document: "quick-revision", page: 7 }, cognitive: "application" },
    { id: "note-circular-motion-010", text: "Which instrument directly reports a motor shaft's rotational speed?", options: [{ key: "a", text: "Tachometer" }, { key: "b", text: "Manometer" }, { key: "c", text: "Dynamometer" }, { key: "d", text: "Galvanometer" }], answer: "a", explanation: "A tachometer measures rotational speed, often in revolutions per minute. The other instruments measure pressure, force or torque-related quantities, and small electric current rather than directly serving as rotational-speed indicators.", sectionId: "rotation-observations", source: { document: "quick-revision", page: 7 }, cognitive: "recall" },
    { id: "note-circular-motion-011", text: "A liquid is in steady rotation about a vertical axis. Relative to the surrounding liquid, which radial tendency does a small low-density bubble have?", options: [{ key: "a", text: "Toward larger radius because pressure is lower there" }, { key: "b", text: "Toward the axis because pressure is lower there" }, { key: "c", text: "Toward larger radius because pressure is uniform" }, { key: "d", text: "No radial tendency because density is irrelevant" }], answer: "b", explanation: "Steady rotation requires pressure to increase outward. The pressure force acting on the volume occupied by a light bubble exceeds the inward force its own small mass needs, giving an inward migration relative to the dense liquid. Gravity can additionally make it rise.", sectionId: "rotation-observations", source: { document: "quick-revision", page: 7 }, cognitive: "understanding" },
    { id: "note-circular-motion-012", text: "A frictionless banked curve has radius $40\\,\\mathrm m$ and $\\tan\\theta=0.25$. With $g=10\\,\\mathrm{m\\,s^{-2}}$, what speed matches the bank without lateral friction?", options: [{ key: "a", text: "$5.0\\,\\mathrm{m\\,s^{-1}}$" }, { key: "b", text: "$20\\,\\mathrm{m\\,s^{-1}}$" }, { key: "c", text: "$40\\,\\mathrm{m\\,s^{-1}}$" }, { key: "d", text: "$10\\,\\mathrm{m\\,s^{-1}}$" }], answer: "d", explanation: "The horizontal-to-vertical normal-force ratio gives $v^2=rg\\tan\\theta$. Substitution gives $v=\\sqrt{40\\times10\\times0.25}=10\\,\\mathrm{m\\,s^{-1}}$. This is the frictionless design speed, not a universal maximum speed once friction and overturning are considered.", sectionId: "banking-and-wheel-loads", source: { document: "quick-revision", page: 7 }, cognitive: "application" },
    { id: "note-circular-motion-013", text: "A car turns left and its passenger feels pressed against the right-hand side. In an inertial frame, which horizontal force must the car exert to turn the passenger with it?", options: [{ key: "a", text: "A rightward force away from the turn centre" }, { key: "b", text: "A leftward force toward the turn centre" }, { key: "c", text: "No force because the passenger's speed is steady" }, { key: "d", text: "A backward force opposite the car's velocity" }], answer: "b", explanation: "The passenger needs inward acceleration toward the centre of the left turn. The car therefore supplies a leftward real force. The outward feeling is described by a centrifugal inertial force in the turning frame, not a real rightward force in the inertial-frame equation.", sectionId: "centrifugal-frame-examples", source: { document: "quick-revision", page: 7 }, cognitive: "understanding" },
    { id: "note-circular-motion-014", text: "A charged particle enters a uniform magnetic field perpendicular to its velocity. No other force acts. Which pair of changes occurs?", options: [{ key: "a", text: "Speed increases; momentum direction stays fixed." }, { key: "b", text: "Speed decreases; momentum direction stays fixed." }, { key: "c", text: "Speed stays fixed; momentum direction changes." }, { key: "d", text: "Speed increases; momentum direction changes." }], answer: "c", explanation: "Magnetic force is perpendicular to velocity, so its power is zero and it cannot change kinetic energy or speed. It continuously turns the velocity and momentum, producing circular motion for the perpendicular-entry condition.", sectionId: "rotation-observations", source: { document: "quick-revision", page: 7 }, cognitive: "understanding" },
    { id: "note-circular-motion-015", text: "A particle's speed remains $6.0\\,\\mathrm{m\\,s^{-1}}$ as its velocity turns through $120^\\circ$. What is the magnitude of its velocity change?", options: [{ key: "a", text: "$3\\sqrt3\\,\\mathrm{m\\,s^{-1}}$" }, { key: "b", text: "$6\\,\\mathrm{m\\,s^{-1}}$" }, { key: "c", text: "$12\\,\\mathrm{m\\,s^{-1}}$" }, { key: "d", text: "$6\\sqrt3\\,\\mathrm{m\\,s^{-1}}$" }], answer: "d", explanation: "Equal-magnitude velocity vectors separated by angle $\\theta$ differ by $2v\\sin\\frac{\\theta}{2}$. Here that is $12\\sin60^\\circ=6\\sqrt3\\,\\mathrm{m\\,s^{-1}}$. The unchanged speed does not imply an unchanged velocity vector.", sectionId: "momentum-and-velocity-change", source: { document: "quick-revision", page: 8 }, cognitive: "application" },
    { id: "note-circular-motion-016", text: "For a particle in circular motion, angular momentum about the circle axis is $0.60\\,\\mathrm{kg\\,m^2\\,s^{-1}}$, moment of inertia is $0.030\\,\\mathrm{kg\\,m^2}$ and radius is $0.30\\,\\mathrm m$. What is the inward force?", options: [{ key: "a", text: "$40\\,\\mathrm N$" }, { key: "b", text: "$12\\,\\mathrm N$" }, { key: "c", text: "$20\\,\\mathrm N$" }, { key: "d", text: "$60\\,\\mathrm N$" }], answer: "a", explanation: "The angular speed is $\\omega=\\frac{L}{I}=20\\,\\mathrm{rad\\,s^{-1}}$ and the mass is $m=\\frac{I}{r^2}=\\frac13\\,\\mathrm{kg}$. Hence $F=m\\omega^2r=40\\,\\mathrm N$, agreeing with $\\frac{L^2}{Ir}=\\frac{0.36}{0.009}$.", sectionId: "momentum-and-velocity-change", source: { document: "quick-revision", page: 8 }, cognitive: "application" },
    { id: "note-circular-motion-017", text: "Two point masses, $3.0\\,\\mathrm{kg}$ at $x=0$ and $1.0\\,\\mathrm{kg}$ at $x=8.0\\,\\mathrm m$, form a system. Where is its centre of mass?", options: [{ key: "a", text: "$x=4.0\\,\\mathrm m$" }, { key: "b", text: "$x=6.0\\,\\mathrm m$" }, { key: "c", text: "$x=8.0\\,\\mathrm m$" }, { key: "d", text: "$x=2.0\\,\\mathrm m$" }], answer: "d", explanation: "The centre of mass is the mass-weighted position: $x_{\\mathrm{CM}}=\\frac{3\\times0+1\\times8}{3+1}=2.0\\,\\mathrm m$. It lies nearer the heavier mass. The unweighted midpoint would apply only if the two masses were equal.", sectionId: "centre-of-mass", source: { document: "quick-revision", page: 8 }, cognitive: "application" },
    { id: "note-circular-motion-018", text: "A body moving vertically breaks into several pieces in flight. Only uniform gravity acts externally, and no piece has yet hit anything. What happens to the horizontal position of the system's centre of mass?", options: [{ key: "a", text: "It follows the fastest fragment horizontally." }, { key: "b", text: "It stays on the original vertical line." }, { key: "c", text: "It shifts toward the heaviest fragment alone." }, { key: "d", text: "It becomes undefined after the breakup." }], answer: "b", explanation: "The initial horizontal centre-of-mass velocity is zero and there is no horizontal external force. Internal breakup impulses cannot change total horizontal momentum, so the centre of mass stays on the original vertical line despite horizontal motion of individual fragments.", sectionId: "centre-of-mass", source: { document: "quick-revision", page: 8 }, cognitive: "understanding" },
    { id: "note-circular-motion-019", text: "A thin ring and a uniform solid sphere roll from rest through the same distance down the same incline without slipping. What is the ratio of the ring's descent time to the sphere's?", options: [{ key: "a", text: "$\\sqrt{\\frac{10}{7}}$" }, { key: "b", text: "$\\frac{10}{7}$" }, { key: "c", text: "$\\sqrt{\\frac{7}{10}}$" }, { key: "d", text: "$\\frac{7}{10}$" }], answer: "a", explanation: "For fixed distance from rest, time scales as $\\sqrt{1+\\frac{I}{mR^2}}$. The ring has $\\frac{I}{mR^2}=1$ and the sphere has $\\frac25$, so the ratio is $\\sqrt{\\frac{2}{\\frac{7}{5}}}=\\sqrt{\\frac{10}{7}}$. Omitting the square root confuses time with time squared.", sectionId: "rolling-descent-time", source: { document: "quick-revision", page: 8 }, cognitive: "application" },
    { id: "note-circular-motion-020", text: "Which sum must vanish when all particle position vectors are measured relative to their system's centre of mass?", options: [{ key: "a", text: "The sum of all particle kinetic energies" }, { key: "b", text: "The sum of all squared particle distances" }, { key: "c", text: "The mass-weighted sum of position vectors" }, { key: "d", text: "The sum of all moments of inertia" }], answer: "c", explanation: "By definition, $\\sum_i m_i(\\vec r_i-\\vec R_{\\mathrm{CM}})=0$. This is a vector first moment of mass. Squared distances and moments of inertia are generally positive, and locating the centre of mass does not require kinetic energy to vanish.", sectionId: "centre-of-mass", source: { document: "quick-revision", page: 8 }, cognitive: "recall" }
  ]
};