window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["d-block"] = {
  id: "d-block",
  subject: "Chemistry",
  title: "Transition metals and metallurgy",
  sections: [
    {
      id: "d-orbital-colour-carryover",
      title: "d-d transitions: the opening continuation",
      sources: [{ document: "quick-revision", page: 102 }],
      html: "<p>The page opens with the statement that d-d transitions of unpaired electrons cause colour. In many transition-metal complexes, ligand fields split the d-orbital energies. Absorption of suitable wavelengths promotes an electron between these levels, contributing to the observed colour.</p><p><strong>Source correction:</strong> Colour is not determined simply by counting unpaired electrons. Paired-electron configurations can also have optical transitions, and charge-transfer transitions can produce intense colours even when ordinary d-d transitions are unavailable. The energy gap must correspond to visible absorption for a visible colour to result; ligands and oxidation state matter. Partially occupied d orbitals explain many cases, but not every coloured compound.</p>"
    },
    {
      id: "inner-transition-series",
      title: "Inner-transition series and configuration convention",
      sources: [{ document: "quick-revision", page: 102 }],
      html: "<p>The f-block elements are called inner-transition elements, a name repeated in the competitive-exam list. Their defining filling trend concerns an inner f subshell.</p><table><thead><tr><th>Source series</th><th>Range and interpretation</th></tr></thead><tbody><tr><td>Lanthanides</td><td>Atomic numbers 58-71, Ce through Lu, in the source's fourteen-elements-after-La convention. The broader lanthanoid family convention includes La, atomic number 57, and runs La-Lu.</td></tr><tr><td>Actinides</td><td>Atomic numbers 90-103, Th through Lr, in the source's fourteen-elements-after-Ac convention. The broader actinoid family includes Ac, atomic number 89.</td></tr></tbody></table><p>The source writes $(n-2)f^{1-14}(n-1)d^{0-10}ns^2$. <strong>Source correction:</strong> Its d<sup>0-10</sup> term is not the normal general f-block pattern. The introductory pattern is commonly written $(n-2)f^{1-14}(n-1)d^{0-1}ns^2$, with important actual-configuration exceptions. In particular, a family label does not guarantee that the last added electron literally enters f in every neutral ground-state atom. Thorium and lawrencium require individual configuration treatment.</p><p>The f subshell accommodates at most fourteen electrons, associated with seven orbitals. This orbital capacity explains the source's fourteen-element filling spans, while family naming and periodic-table placement introduce boundary conventions.</p>"
    },
    {
      id: "lanthanide-size-and-chemistry",
      title: "Radii, oxidation, air reaction and alloys",
      sources: [{ document: "quick-revision", page: 102 }],
      html: "<ul><li><strong>Atomic and ionic radii:</strong> the source states a steady decrease from La to Lu. The characteristic lanthanide contraction is especially clear for Ln<sup>3+</sup> radii compared at the same coordination number: increasing nuclear charge is incompletely screened by the added 4f electrons. Atomic metallic radii can show anomalies, so 'steadily' should not be applied indiscriminately to every radius convention.</li><li><strong>Oxidation state:</strong> +3 is the principal state of the lanthanides. Other states can occur. <strong>Source qualification:</strong> The broad f-block heading should not make +3 the only important state of all actinides; early actinides show several higher oxidation states.</li><li><strong>Air reaction:</strong> these electropositive metals tarnish readily through reaction with air. This is surface chemical change, not proof of chemical inertness.</li><li><strong>Reducing behavior:</strong> the metals are good reducing agents because they can lose electrons and form positive ions. This statement concerns the elemental metals, not a claim that every compound is an equally strong reductant.</li><li><strong>Alloy formation:</strong> the source notes ready alloy formation with iron. An alloy is a metallic material containing more than one element; the statement supplies no fixed iron/rare-earth percentage.</li></ul>"
    },
    {
      id: "lanthanide-colour-and-magnetism",
      title: "f-f colour and trivalent-ion magnetism",
      sources: [{ document: "quick-revision", page: 102 }],
      html: "<p>Many lanthanide ions show colours associated with f-f electronic transitions. The source's 'forms coloured ions' is a common trend rather than a statement that every f-block ion must absorb visible light. Empty or completely filled f shells do not allow ordinary intra-shell f-f transitions, and even an open shell does not guarantee strong visible absorption.</p><table><thead><tr><th>Trivalent ion</th><th>Configuration and magnetic classification</th></tr></thead><tbody><tr><td>La<sup>3+</sup></td><td>4f<sup>0</sup> beyond the xenon core; no unpaired f electrons; diamagnetic.</td></tr><tr><td>Lu<sup>3+</sup></td><td>4f<sup>14</sup>; the f shell is filled and all its electrons are paired; diamagnetic.</td></tr><tr><td>Other usual trivalent lanthanide ions, Ce<sup>3+</sup> through Yb<sup>3+</sup></td><td>Open 4f shells; conventionally grouped as paramagnetic in introductory comparisons.</td></tr></tbody></table><p>Rare-earth magnetic moments depend strongly on spin-orbit coupling and orbital contributions. The introductory open-shell classification is not permission to use the spin-only 3d formula as an exact prediction for every Ln<sup>3+</sup> ion; ions such as Eu<sup>3+</sup> have more subtle temperature-dependent magnetic responses.</p>"
    },
    {
      id: "copper-colour-and-complexes",
      title: "Copper solution colours and ammonia coordination",
      sources: [{ document: "quick-revision", page: 102 }],
      html: "<p>The source describes four vessels containing different salts, addition of copper, and a blue solution associated with Cu(NO<sub>3</sub>)<sub>2</sub>. Aqueous copper(II) nitrate is blue because it contains hydrated Cu<sup>2+</sup> ions. However, the four starting salts are not listed, and Cu(NO<sub>3</sub>)<sub>2</sub> solution can already be blue before copper metal is added.</p><p><strong>Source limitation:</strong> No unique displacement experiment can be reconstructed from that abbreviated statement. Copper metal needs an appropriate oxidizing partner to become Cu<sup>2+</sup>; simply putting copper into an arbitrary salt solution does not guarantee blue colour. The reliable retained fact is the characteristic colour of hydrated copper(II) in suitable aqueous solution.</p><p>Cu<sup>2+</sup> forms a complex with NH<sub>3</sub>. Ammonia donates the nitrogen lone pair to the metal, forming coordinate bonds. The common deep-blue aqueous tetraammine complex is often abbreviated [Cu(NH<sub>3</sub>)<sub>4</sub>]<sup>2+</sup>; a fuller aqueous description is [Cu(NH<sub>3</sub>)<sub>4</sub>(H<sub>2</sub>O)<sub>2</sub>]<sup>2+</sup>. This also corrects the source's wording 'compound ... = Cu<sup>2+</sup>': Cu<sup>2+</sup> is the metal ion, not by itself the complete complex compound.</p>"
    },
    {
      id: "zinc-hydroxide-and-colour",
      title: "Zinc sulfate with alkali and zinc-salt colour",
      sources: [{ document: "quick-revision", page: 102 }],
      html: "<p>Zinc sulfate reacts with a limited amount of aqueous NaOH to give white zinc hydroxide: Zn<sup>2+</sup> + 2OH<sup>-</sup> &rarr; Zn(OH)<sub>2</sub>(s). In excess hydroxide, the amphoteric precipitate dissolves to give a soluble hydroxo complex: Zn(OH)<sub>2</sub> + 2OH<sup>-</sup> &rarr; [Zn(OH)<sub>4</sub>]<sup>2-</sup>.</p><p>The overall aqueous salt equation is ZnSO<sub>4</sub> + 4NaOH &rarr; Na<sub>2</sub>[Zn(OH)<sub>4</sub>] + Na<sub>2</sub>SO<sub>4</sub>. The source's short answer 'soluble complex' refers to this excess-base condition. It is not hydrogen production by zinc metal: the starting zinc is already Zn<sup>2+</sup>.</p><p>Zn<sup>2+</sup> is 3d<sup>10</sup>, so it has no ordinary d-d excitation within a partially filled d set and is diamagnetic. Its simple salts with colourless anions are usually colourless in solution or white as solids.</p><p><strong>Source correction:</strong> The statement that Zn never shows coloured salts is too broad. A coloured counterion, ligand or charge-transfer process can colour a zinc compound; the filled d shell rules out ordinary zinc-centred d-d colour, not every possible optical mechanism.</p>"
    },
    {
      id: "oxidation-state-and-magnetic-moments",
      title: "Covalent character and the qualified Fe3+ comparison",
      sources: [{ document: "quick-revision", page: 102 }],
      html: "<p>For a comparable set of compounds of the same transition metal, increased oxidation state often increases covalent character. A more highly charged, often smaller cation has greater polarizing power and distorts the ligand or anion electron cloud more strongly. The source's rule concerns comparable compounds, not a universal numerical ranking of unrelated materials.</p><p>The source names Fe<sup>3+</sup> as having the highest magnetic moment but supplies neither the comparison ions nor the ligand field. <strong>Source correction:</strong> High-spin Fe<sup>3+</sup> is 3d<sup>5</sup> with five unpaired electrons and has a large spin-only moment. It is not uniquely highest among all elements or ions; high-spin Mn<sup>2+</sup> also has d<sup>5</sup>, and some f-block ions have larger moments. Low-spin Fe<sup>3+</sup> instead has one unpaired electron.</p><p>For an ion whose orbital contribution is effectively quenched, the approximate spin-only moment is $\\mu_{\\mathrm{so}}=\\sqrt{u(u+2)}\\,\\mu_B$, where $u$ is the number of unpaired electrons and $\\mu_B$ the Bohr magneton.</p><table><thead><tr><th>Specified comparison</th><th>Unpaired electrons and spin-only moment</th></tr></thead><tbody><tr><td>High-spin Fe<sup>3+</sup>, d<sup>5</sup></td><td>5; $\\sqrt{35}\\approx5.92$ BM.</td></tr><tr><td>High-spin Fe<sup>2+</sup>, d<sup>6</sup></td><td>4; $\\sqrt{24}\\approx4.90$ BM.</td></tr><tr><td>Cu<sup>2+</sup>, d<sup>9</sup></td><td>1; $\\sqrt{3}\\approx1.73$ BM.</td></tr><tr><td>Zn<sup>2+</sup>, d<sup>10</sup></td><td>0; zero spin-only moment.</td></tr></tbody></table><p>This explicit comparison repairs the missing condition behind the exam shorthand. It does not make the formula exact for strongly orbital-coupled rare-earth ions or magnetically interacting bulk materials.</p>"
    },
    {
      id: "iron-products-displacement-and-rust",
      title: "Galvanization, iron grades, phosphate and corrosion",
      sources: [{ document: "quick-revision", page: 102 }],
      html: "<ul><li><strong>Galvanization:</strong> iron is coated with zinc. Zinc provides a barrier and, when electrically connected under suitable corrosion conditions, can oxidize sacrificially in preference to iron. This distinguishes zinc coating from a purely passive covering.</li><li><strong>Wrought iron:</strong> the source calls it the purest form of iron. <strong>Source correction:</strong> It is a low-carbon traditional commercial iron containing slag inclusions, and may be described as the purest among certain conventional commercial grades. It is not purer than every specially refined or high-purity laboratory iron.</li><li><strong>Iron(II) phosphate:</strong> Fe<sub>3</sub>(PO<sub>4</sub>)<sub>2</sub>. Each phosphate is PO<sub>4</sub><sup>3-</sup>; two give -6, so three iron ions together supply +6 and each is Fe<sup>2+</sup>.</li><li><strong>Iron nail in copper sulfate:</strong> Fe + CuSO<sub>4</sub> &rarr; FeSO<sub>4</sub> + Cu. The blue copper(II) solution becomes paler and can appear green as Fe<sup>2+</sup> accumulates, while reddish-brown copper deposits. The net reaction is Fe + Cu<sup>2+</sup> &rarr; Fe<sup>2+</sup> + Cu. Residual blue Cu<sup>2+</sup>, concentration and extent of reaction affect the observed colour.</li><li><strong>Rust:</strong> the source uses the shorthand Fe<sub>2</sub>O<sub>3</sub> + Fe(OH)<sub>3</sub>. Actual rust is a variable mixture of hydrated iron(III) oxides and oxyhydroxides, often represented generically as Fe<sub>2</sub>O<sub>3</sub>&middot;xH<sub>2</sub>O and FeOOH. It is not a fixed stoichiometric two-component compound or a universal 1:1 mixture.</li></ul>"
    },
    {
      id: "historical-medical-source-claims",
      title: "Historical medical-use statements and their limits",
      sources: [{ document: "quick-revision", page: 102 }],
      html: "<p>The source associates colloidal gold with treatment of joint disease. <strong>Source correction:</strong> Certain gold compounds were historically used in rheumatoid-arthritis treatment, but this does not establish consumer colloidal gold as a safe or effective treatment for joint disease. The page gives no formulation, evidence, indication or present-day recommendation; the claim is not used to score medical advice.</p><p>The page also names very dilute ZnSO<sub>4</sub> solution as an eye-drop ingredient. This refers to historical or specifically formulated pharmaceutical uses, not arbitrary laboratory zinc sulfate solutions. Sterility, formulation, concentration, indication and regulatory status are essential and absent from the source. No preparation directions or self-treatment recommendation follow from this revision fact.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 102, status: "partial", sectionIds: ["d-orbital-colour-carryover", "inner-transition-series", "lanthanide-size-and-chemistry", "lanthanide-colour-and-magnetism", "copper-colour-and-complexes", "zinc-hydroxide-and-colour", "oxidation-state-and-magnetic-moments", "iron-products-displacement-and-rust", "historical-medical-source-claims"], unresolved: ["The four-vessel copper/blue-solution question omits the identities of the four starting salts and the initial colours, so no unique displacement experiment or original answer comparison can be reconstructed.", "The 'highest magnetic moment = Fe3+' statement omits comparison species, ligand field and spin state; an explicitly high-spin, spin-only comparison is supplied, but the original question context remains unavailable.", "The colloidal-gold joint-treatment and zinc-sulfate eye-drop claims omit formulation, indication, concentration and clinical evidence; they are retained only with historical/medical limitations and are not used as treatment MCQs."] }
  ],
  questions: [
    { id: "note-d-block-001", text: "Which alternative name is used for the elements associated with inner f-subshell filling?", options: [{ key: "a", text: "Inner-transition elements" }, { key: "b", text: "Alkaline-earth elements" }, { key: "c", text: "Coinage elements" }, { key: "d", text: "Halogen elements" }], answer: "a", explanation: "The f-block series are termed inner-transition elements because their defining filling trend involves an inner f subshell. This is distinct from the ordinary d-block transition series.", sectionId: "inner-transition-series", source: { document: "quick-revision", page: 102 }, cognitive: "recall" },
    { id: "note-d-block-002", text: "Using the source's Ce-to-Lu convention, how many atomic numbers are included from 58 through 71?", options: [{ key: "a", text: "12" }, { key: "b", text: "13" }, { key: "c", text: "15" }, { key: "d", text: "14" }], answer: "d", explanation: "The inclusive count is 71 - 58 + 1 = 14. A family convention that also includes La would contain fifteen elements, so the stated range matters.", sectionId: "inner-transition-series", source: { document: "quick-revision", page: 102 }, cognitive: "application" },
    { id: "note-d-block-003", text: "Which pair of trivalent lanthanide-family ions is diamagnetic because its f shell is empty or full?", options: [{ key: "a", text: "Ce<sup>3+</sup> and Nd<sup>3+</sup>" }, { key: "b", text: "La<sup>3+</sup> and Lu<sup>3+</sup>" }, { key: "c", text: "Gd<sup>3+</sup> and Dy<sup>3+</sup>" }, { key: "d", text: "Pr<sup>3+</sup> and Yb<sup>3+</sup>" }], answer: "b", explanation: "La3+ is f0 and Lu3+ is f14, so neither has unpaired f electrons. The source specifically distinguishes these two from the usual open-shell trivalent ions.", sectionId: "lanthanide-colour-and-magnetism", source: { document: "quick-revision", page: 102 }, cognitive: "recall" },
    { id: "note-d-block-004", text: "What best explains contraction of comparable Ln<sup>3+</sup> ions as atomic number rises across the lanthanides?", options: [{ key: "a", text: "Loss of all nuclear protons" }, { key: "b", text: "Perfect screening by each added 4f electron" }, { key: "c", text: "Incomplete 4f screening of increasing nuclear charge" }, { key: "d", text: "Progressive replacement of electrons by neutrons" }], answer: "c", explanation: "Added 4f electrons do not fully screen the increasing positive nuclear charge. The greater effective attraction contracts the electron cloud, giving lanthanide contraction.", sectionId: "lanthanide-size-and-chemistry", source: { document: "quick-revision", page: 102 }, cognitive: "understanding" },
    { id: "note-d-block-005", text: "Which oxidation state is the principal common state of the lanthanides discussed on this page?", options: [{ key: "a", text: "+1" }, { key: "b", text: "+2" }, { key: "c", text: "+4" }, { key: "d", text: "+3" }], answer: "d", explanation: "The characteristic common lanthanide state is +3. This is a predominant state, not a claim that every lanthanide or actinide can exist only in that state.", sectionId: "lanthanide-size-and-chemistry", source: { document: "quick-revision", page: 102 }, cognitive: "recall" },
    { id: "note-d-block-006", text: "Which environment produces the ready tarnishing noted for freshly exposed lanthanide metals?", options: [{ key: "a", text: "Ordinary air" }, { key: "b", text: "Dry argon" }, { key: "c", text: "High vacuum" }, { key: "d", text: "Dry helium" }], answer: "a", explanation: "Tarnishing is surface chemical reaction with air, commonly involving oxidation. The source lists ready tarnishing as a property of these electropositive metals.", sectionId: "lanthanide-size-and-chemistry", source: { document: "quick-revision", page: 102 }, cognitive: "recall" },
    { id: "note-d-block-007", text: "Which metal is specifically named as an alloy-forming partner of the inner-transition metals in the notes?", options: [{ key: "a", text: "Sodium" }, { key: "b", text: "Mercury" }, { key: "c", text: "Iron" }, { key: "d", text: "Lithium" }], answer: "c", explanation: "The source notes ready alloy formation with iron. It gives an alloying tendency and partner, not a fixed percentage composition or a particular commercial grade.", sectionId: "lanthanide-size-and-chemistry", source: { document: "quick-revision", page: 102 }, cognitive: "recall" },
    { id: "note-d-block-008", text: "Which statement best replaces the claim that unpaired-electron count alone determines a transition-metal complex's colour?", options: [{ key: "a", text: "Every diamagnetic complex is necessarily colourless" }, { key: "b", text: "Suitable visible-light electronic transitions determine absorption" }, { key: "c", text: "All complexes of a metal have exactly the same colour" }, { key: "d", text: "Ligands never affect d-orbital energy differences" }], answer: "b", explanation: "Colour requires absorption at appropriate visible energies. Ligand-field and charge-transfer transitions depend on electronic structure and ligands, not solely on the number of unpaired electrons.", sectionId: "d-orbital-colour-carryover", source: { document: "quick-revision", page: 102 }, cognitive: "understanding" },
    { id: "note-d-block-009", text: "Why are many simple Zn<sup>2+</sup> salts with colourless anions colourless in solution?", options: [{ key: "a", text: "Zn2+ has a half-filled 3d subshell" }, { key: "b", text: "Zn2+ has a filled 3d subshell" }, { key: "c", text: "Zn2+ has a singly occupied 3d subshell" }, { key: "d", text: "Zn2+ has an empty 3d subshell" }], answer: "b", explanation: "Zn2+ is 3d10, so ordinary transitions within a partially filled zinc d set are unavailable. The condition about colourless anions avoids falsely claiming every zinc compound is colourless.", sectionId: "zinc-hydroxide-and-colour", source: { document: "quick-revision", page: 102 }, cognitive: "understanding" },
    { id: "note-d-block-010", text: "For high-spin Fe<sup>3+</sup> with five unpaired electrons, what is the approximate spin-only moment using $\\mu=\\sqrt{u(u+2)}$ BM?", options: [{ key: "a", text: "1.73 BM" }, { key: "b", text: "4.90 BM" }, { key: "c", text: "5.92 BM" }, { key: "d", text: "7.94 BM" }], answer: "c", explanation: "Substituting u = 5 gives $\\sqrt{5(5+2)}=\\sqrt{35}=5.92$ BM. The high-spin condition is essential; Fe3+ need not always have five unpaired electrons.", sectionId: "oxidation-state-and-magnetic-moments", source: { document: "quick-revision", page: 102 }, cognitive: "application" },
    { id: "note-d-block-011", text: "Why is 'Fe<sup>3+</sup> always has five unpaired electrons' an unsafe generalization for complexes?", options: [{ key: "a", text: "A sufficiently strong ligand field can give low-spin d5" }, { key: "b", text: "Fe3+ has the same d count as Zn2+" }, { key: "c", text: "Oxidation state never affects electron count" }, { key: "d", text: "All iron ions have an empty 3d shell" }], answer: "a", explanation: "Fe3+ is d5, but orbital occupancy depends on ligand-field splitting versus pairing energy. A low-spin octahedral d5 arrangement has one unpaired electron, not five.", sectionId: "oxidation-state-and-magnetic-moments", source: { document: "quick-revision", page: 102 }, cognitive: "understanding" },
    { id: "note-d-block-012", text: "Which soluble species explains dissolution of Zn(OH)<sub>2</sub> in excess aqueous hydroxide?", options: [{ key: "a", text: "[Zn(NH<sub>3</sub>)<sub>4</sub>]<sup>2+</sup>" }, { key: "b", text: "[Cu(OH)<sub>4</sub>]<sup>2-</sup>" }, { key: "c", text: "[Zn(H<sub>2</sub>O)<sub>6</sub>]<sup>3+</sup>" }, { key: "d", text: "[Zn(OH)<sub>4</sub>]<sup>2-</sup>" }], answer: "d", explanation: "Amphoteric Zn(OH)2 reacts with two additional OH- ions to form soluble tetrahydroxozincate(II), [Zn(OH)4]2-. No ammonia ligand is required for this excess-base reaction.", sectionId: "zinc-hydroxide-and-colour", source: { document: "quick-revision", page: 102 }, cognitive: "recall" },
    { id: "note-d-block-013", text: "Before excess base is added, limited NaOH introduced into aqueous ZnSO<sub>4</sub> produces which precipitate?", options: [{ key: "a", text: "Blue Cu(OH)<sub>2</sub>" }, { key: "b", text: "Brown Fe(OH)<sub>3</sub>" }, { key: "c", text: "White Zn(OH)<sub>2</sub>" }, { key: "d", text: "Black Zn metal" }], answer: "c", explanation: "Two hydroxide ions combine with Zn2+ to form white Zn(OH)2. Only after sufficient excess hydroxide is present does the precipitate dissolve as a soluble hydroxo complex.", sectionId: "zinc-hydroxide-and-colour", source: { document: "quick-revision", page: 102 }, cognitive: "understanding" },
    { id: "note-d-block-014", text: "What does NH<sub>3</sub> supply when it forms a coordinate bond to Cu<sup>2+</sup>?", options: [{ key: "a", text: "One unpaired nitrogen electron" }, { key: "b", text: "A nitrogen lone electron pair" }, { key: "c", text: "A proton from an N-H bond" }, { key: "d", text: "An electron pair donated by Cu2+" }], answer: "b", explanation: "The nitrogen atom of ammonia has a lone pair available for donation to the metal ion. Donation of this pair provides the coordinate bond in the ammine complex.", sectionId: "copper-colour-and-complexes", source: { document: "quick-revision", page: 102 }, cognitive: "understanding" },
    { id: "note-d-block-015", text: "What characteristic colour is associated with the aqueous tetraamminecopper(II) complex?", options: [{ key: "a", text: "Pale yellow" }, { key: "b", text: "Crimson red" }, { key: "c", text: "Apple green" }, { key: "d", text: "Deep blue" }], answer: "d", explanation: "Ammonia coordination to Cu2+ gives the characteristic deep-blue tetraammine complex in aqueous solution. Its ligand environment differs from the simpler hydrated copper(II) ion.", sectionId: "copper-colour-and-complexes", source: { document: "quick-revision", page: 102 }, cognitive: "recall" },
    { id: "note-d-block-016", text: "Which coating metal defines galvanized iron?", options: [{ key: "a", text: "Zinc" }, { key: "b", text: "Copper" }, { key: "c", text: "Tin" }, { key: "d", text: "Silver" }], answer: "a", explanation: "Galvanization coats iron or steel with zinc. Besides creating a barrier, zinc can provide sacrificial protection under suitable electrically connected corrosion conditions.", sectionId: "iron-products-displacement-and-rust", source: { document: "quick-revision", page: 102 }, cognitive: "recall" },
    { id: "note-d-block-017", text: "An electrically connected zinc coating can still protect exposed iron at a small scratch in a moist environment because:", options: [{ key: "a", text: "Zinc can oxidize in preference to the iron" }, { key: "b", text: "Zinc is less reactive than iron and stays inert" }, { key: "c", text: "The exposed iron acts as the sacrificial anode" }, { key: "d", text: "Zinc prevents electrical contact between the metals" }], answer: "a", explanation: "Sacrificial protection means the more readily oxidized zinc supplies the anodic reaction, helping suppress iron oxidation while contact and suitable electrochemical conditions remain.", sectionId: "iron-products-displacement-and-rust", source: { document: "quick-revision", page: 102 }, cognitive: "understanding" },
    { id: "note-d-block-018", text: "Phosphate has charge 3-. What oxidation state must iron have in neutral Fe<sub>3</sub>(PO<sub>4</sub>)<sub>2</sub>?", options: [{ key: "a", text: "+1" }, { key: "b", text: "+3" }, { key: "c", text: "+2" }, { key: "d", text: "+6" }], answer: "c", explanation: "Two phosphate ions contribute -6. The three iron ions must total +6, so each is +2: $3x+2(-3)=0$ gives x = +2, iron(II) phosphate.", sectionId: "iron-products-displacement-and-rust", source: { document: "quick-revision", page: 102 }, cognitive: "application" },
    { id: "note-d-block-019", text: "Assume 2.80 g Fe reacts completely with excess CuSO<sub>4</sub> solely by Fe + CuSO<sub>4</sub> &rarr; FeSO<sub>4</sub> + Cu. Using Fe = 56 and Cu = 64 g mol<sup>-1</sup>, what copper mass forms?", options: [{ key: "a", text: "2.80 g" }, { key: "b", text: "3.20 g" }, { key: "c", text: "1.60 g" }, { key: "d", text: "6.40 g" }], answer: "b", explanation: "Iron amount is 2.80/56 = 0.0500 mol. The balanced displacement gives one mole Cu per mole Fe, so copper mass is 0.0500 x 64 = 3.20 g.", sectionId: "iron-products-displacement-and-rust", source: { document: "quick-revision", page: 102 }, cognitive: "application" },
    { id: "note-d-block-020", text: "Which description best represents the composition of ordinary rust?", options: [{ key: "a", text: "Pure dry iron(III) oxide of fixed composition" }, { key: "b", text: "A single iron(II) hydroxide phase only" }, { key: "c", text: "A fixed 1:1 mixture of Fe2O3 and Fe(OH)3" }, { key: "d", text: "Variable hydrated iron oxides and oxyhydroxides" }], answer: "d", explanation: "Rust has variable hydration and phase composition, including hydrated iron(III) oxides and FeOOH-type phases. The source's Fe2O3 plus Fe(OH)3 is shorthand, not an exact fixed formula.", sectionId: "iron-products-displacement-and-rust", source: { document: "quick-revision", page: 102 }, cognitive: "understanding" }
  ]
};