window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["diseases"] = {
    id: "diseases",
    subject: "Zoology",
    title: "Human diseases and immunity",
    sections: [
        {
            id: "disease-study-and-scope",
            title: "Disease terminology and limits of the medical notes",
            sources: [{ document: "biology", page: 140 }, { document: "biology", page: 145 }],
            html: "<p>Epidemiology studies the distribution and determinants of health-related events in populations, including the causes and spread of disease. Etiology concerns the causes of a particular disease. Oncology is the study and clinical management of cancer. Screening looks for evidence of disease or increased risk before symptoms develop; a positive screening result is not automatically a confirmed diagnosis.</p>" +
                "<p><strong>Medical-education scope:</strong> the named investigations, medicines and historical regimens below are study content, not instructions for diagnosing or treating oneself. Appropriate testing, drug selection and vaccination depend on clinical assessment, age, pregnancy, contraindications, antimicrobial resistance and current local guidance. No dose or self-treatment schedule is supplied.</p>" +
                "<p>The source ranks cardiovascular disease first and cancer second among causes of disease in developed countries. It also calls carcinoma the commonest cancer category and leukemia the commonest childhood cancer. Carcinomas account for a large share of adult cancers, and leukemia is a major childhood cancer, but a ranking requires a defined population, age group, year and measure. Incidence, prevalence and mortality are not interchangeable. The undated country rankings are retained as source claims, not current epidemiological statistics.</p>"
        },
        {
            id: "cancer-behaviour",
            title: "Neoplasms, benign tumours and malignant behaviour",
            sources: [{ document: "biology", page: 140 }],
            html: "<p>A neoplasm is an abnormal proliferation of cells. The source uses tumour as its synonym, although some neoplasms, including leukemias, do not form a discrete solid mass. A carcinogen is a cancer-causing agent. An oncogene is a gene whose abnormal activation or expression can promote malignant growth; normal growth-regulating proto-oncogenes can become oncogenes.</p>" +
                "<table><thead><tr><th>Feature</th><th>Benign</th><th>Malignant</th></tr></thead><tbody><tr><td>Local behaviour</td><td>Usually circumscribed; may be encapsulated</td><td>Can invade surrounding tissues</td></tr><tr><td>Growth</td><td>Often relatively slow</td><td>May be rapid, but rates vary</td></tr><tr><td>Distant spread</td><td>Does not metastasize</td><td>Can produce metastases</td></tr><tr><td>Cell-death control</td><td>No universal diagnostic rule</td><td>Resistance to apoptosis is a common cancer property</td></tr></tbody></table>" +
                "<p>Metastasis is the establishment of tumour deposits at sites distant from the primary tumour. Blood and lymph are important routes; the secondary growth is a consequence of dissemination, not itself a transport route. Local invasion alone is not the same as metastasis. Apoptosis means programmed cell death.</p>" +
                "<p><strong>Source correction:</strong> slow versus rapid growth and encapsulated versus non-encapsulated are tendencies, not exceptionless definitions. Cancer cells do not universally have 'no apoptosis'. The ending -oma does not establish benignity: melanoma and lymphoma are malignant examples. Carcinoma and sarcoma are diagnostic categories, not simply prefixes that identify every malignant tumour.</p>"
        },
        {
            id: "cancer-origins-and-viruses",
            title: "Cancer origins, named examples and associated viruses",
            sources: [{ document: "biology", page: 140 }, { document: "biology", page: 144 }],
            html: "<table><thead><tr><th>Term</th><th>Origin or meaning</th></tr></thead><tbody><tr><td>Carcinoma</td><td>Malignancy of epithelial cells, including epithelial linings and glands</td></tr><tr><td>Sarcoma</td><td>Malignancy of mesenchymal tissues; osteosarcoma involves bone and chondrosarcoma cartilage</td></tr><tr><td>Adenoma</td><td>Benign epithelial tumour with glandular origin or differentiation; the malignant counterpart is an adenocarcinoma</td></tr><tr><td>Lymphoma</td><td>Malignancy of lymphoid cells; may involve lymph nodes or extranodal tissues</td></tr><tr><td>Leukemia</td><td>Malignancy of blood-forming tissues, often with abnormal circulating cells</td></tr><tr><td>Melanoma</td><td>Malignancy of melanocytes, commonly in skin but not limited to skin</td></tr><tr><td>Kaposi sarcoma</td><td>A vascular tumour associated with human herpesvirus 8, also called KSHV</td></tr></tbody></table>" +
                "<p>The source's epithelial examples are cervical, breast, colon, gastric, oral and lung carcinomas. It also lists brain cancer under carcinoma and leukemia and non-Hodgkin lymphoma under sarcoma. <strong>Source correction:</strong> these last placements are not sound general classifications. Many primary brain tumours are glial, while leukemias and lymphomas are hematolymphoid malignancies. Epithelium is not exclusively ectodermal; epithelial tissues arise from different germ layers. A high white-cell count can occur in leukemia but is not required.</p>" +
                "<table><thead><tr><th>Virus in the notes</th><th>Cancer-related qualification</th></tr></thead><tbody><tr><td>HTLV-1; RNA retrovirus</td><td>Associated with adult T-cell leukemia/lymphoma; the source writes 'T-cell leukemia' under RNA viruses</td></tr><tr><td>Hepatitis C virus; RNA</td><td>Chronic infection can increase liver-cancer risk, largely through chronic liver injury</td></tr><tr><td>Human papillomavirus; DNA</td><td>Persistent infection with high-risk types causes most cervical cancers</td></tr><tr><td>Hepatitis B virus; DNA</td><td>Chronic infection increases hepatocellular-carcinoma risk</td></tr><tr><td>Epstein-Barr virus; DNA</td><td>Associated with some lymphomas, not every non-Hodgkin lymphoma</td></tr><tr><td>HHV-8; DNA</td><td>Associated with Kaposi sarcoma, including in advanced HIV infection</td></tr></tbody></table>" +
                "<p>Other listed carcinogenic exposures include ultraviolet radiation, ionizing X-rays and gamma rays, and carcinogenic constituents of tar. An exposure's risk depends on its nature and dose; this list is not a reason to reject clinically justified imaging. 'Viral oncogenes' is an oversimplified heading for the virus list: an oncogenic infection need not cause cancer through a directly carried viral oncogene.</p>"
        },
        {
            id: "cancer-screening-and-investigation",
            title: "Cancer screening, investigations and treatment categories",
            sources: [{ document: "biology", page: 140 }, { document: "biology", page: 145 }, { document: "quick-revision", page: 175 }],
            html: "<table><thead><tr><th>Source item</th><th>Study interpretation</th></tr></thead><tbody><tr><td>Biopsy and histopathology</td><td>A tissue sample is examined to establish the nature of many suspected tumours</td></tr><tr><td>X-ray, CT scan and MRI</td><td>Imaging can locate, characterize or stage lesions; imaging alone does not replace tissue diagnosis in every case</td></tr><tr><td>FNAC</td><td>Fine-needle aspiration cytology examines aspirated cells; breast lesions are the source example</td></tr><tr><td>Pap smear</td><td>Cervical cytology screening, especially for precancerous changes; not by itself definitive proof of invasive carcinoma</td></tr><tr><td>Mammography</td><td>Breast imaging used in appropriate screening and diagnostic settings</td></tr><tr><td>LDCT</td><td>Low-dose computed tomography used for lung-cancer screening in selected higher-risk populations</td></tr></tbody></table>" +
                "<p>The handwritten chart pairs adult men worldwide with lung cancer and adult women worldwide with breast cancer; its Nepal branch pairs men with gastric cancer and women with cervical cancer. These are undated source rankings without a defined registry or measure. They are not asserted as today's Nepal or world rankings, and they are not used as scored facts.</p>" +
                "<p>The four treatment categories listed are surgery, radiotherapy, chemotherapy and immunotherapy. Radioiodine I-131 is used in selected differentiated thyroid cancers that take up iodine, not all thyroid tumours. The printed page names cisplatin as a cancer drug. <strong>Source correction:</strong> cisplatin is a platinum coordination compound, cis-[Pt(NH<sub>3</sub>)<sub>2</sub>Cl<sub>2</sub>], not an organometallic compound in the strict metal-carbon-bond sense. Treatment choice is cancer- and patient-specific.</p>"
        },
        {
            id: "tb-cause-and-transmission",
            title: "Tuberculosis: organism, staining and transmission",
            sources: [{ document: "biology", page: 141 }],
            html: "<p>Tuberculosis is also called Koch's disease in the notes. Robert Koch identified the tubercle bacillus; World TB Day is 24 March. The principal human pathogen is <em>Mycobacterium tuberculosis</em>, also called Koch's bacillus. The source's short question fragments about the genus, species and acid-fast bacilli all refer to this organism; <em>M. leprae</em> causes leprosy instead.</p>" +
                "<p>The lipid-rich cell wall contains mycolic acids, contributing to acid-fast staining. Ziehl-Neelsen staining is abbreviated Z-N or ZN. AFB means acid-fast bacilli. Mycobacteria belong to a Gram-positive bacterial lineage but stain poorly by routine Gram methods; an AFB-positive specimen does not alone identify the species.</p>" +
                "<p><em>Mycobacterium bovis</em> can cause zoonotic TB, with unpasteurized contaminated cow or buffalo milk an example of exposure. The source calls ordinary TB transmission 'droplet infection'. More precisely, infectious pulmonary or laryngeal TB spreads through inhaled airborne particles; it is not restricted to large droplets settling rapidly.</p>" +
                "<p><strong>Source correction:</strong> tuberculin is an antigen preparation, now commonly purified protein derivative for skin testing, not a secreted toxin that explains TB pathology. The stated 'incubation period: 3 weeks to 3 months' is not a fixed interval to active TB. Immune sensitization develops over weeks, whereas infection can remain latent and active disease can occur much later.</p>"
        },
        {
            id: "tb-lesions-and-clinical-features",
            title: "Pulmonary and extrapulmonary TB, Ghon lesions and symptoms",
            sources: [{ document: "biology", page: 141 }],
            html: "<p>Pulmonary TB affects the lungs. Extrapulmonary TB affects sites outside lung parenchyma; lymph nodes are a common site, with the exact distribution varying by population. The notes exclude hair, nails and enamel. These nonliving hard structures are not typical sites of tuberculous infection, but the shorthand must not be read as excluding all skin, adjacent soft-tissue or skeletal TB.</p>" +
                "<p>A Ghon focus is a primary pulmonary tuberculous lesion, usually subpleural. The source describes a granulomatous focus near the pleura or an interlobar region. A Ghon complex comprises the lung focus with involvement of draining regional lymph nodes. The drawing labels the lung lesion and a separate hilar node: it illustrates their combination, not two unrelated diseases. 'Granulosa' in the notes should be granuloma or granulomatous lesion.</p>" +
                "<ul><li>Persistent cough is an important pulmonary symptom.</li><li>Hemoptysis means blood in sputum.</li><li>Weight loss and anorexia, meaning loss of appetite, can occur.</li><li>Low-grade fever, an evening temperature rise and night sweats are classic descriptions.</li></ul>" +
                "<p><strong>Source correction:</strong> the handwritten threshold 'cough &gt;14 weeks' is erroneous as a general screening rule. Many teaching algorithms refer to about two weeks of cough, while current evaluation also depends on risk and other symptoms. No duration establishes or excludes TB, and the source must not encourage waiting fourteen weeks before assessment.</p>"
        },
        {
            id: "tb-investigations",
            title: "What TB investigations actually measure",
            sources: [{ document: "biology", page: 141 }, { document: "biology", page: 145 }],
            html: "<table><thead><tr><th>Investigation</th><th>Meaning and limitation</th></tr></thead><tbody><tr><td>Sputum smear with Z-N staining</td><td>Detects acid-fast bacilli microscopically; relatively inexpensive, but sensitivity is limited and species identity is not established</td></tr><tr><td>Sputum culture</td><td>Demonstrates viable mycobacteria and supports identification and susceptibility testing; results take time</td></tr><tr><td>PCR or GeneXpert</td><td>Molecular detection of mycobacterial nucleic acid; appropriate assays can also identify resistance markers</td></tr><tr><td>Mantoux or tuberculin skin test</td><td>Measures delayed cell-mediated sensitization to mycobacterial antigens; does not distinguish active disease from latent infection by itself</td></tr></tbody></table>" +
                "<p>The source pairs culture with a '3 morning test' and calls it confirmatory. Multiple morning sputum specimens belong to historical collection protocols; the exact number and timing depend on the diagnostic pathway. A sputum smear, a culture and a molecular test are different investigations, not interchangeable names.</p>" +
                "<p><strong>Source correction:</strong> page 141 calls Z-N staining the most effective and reliable test, while page 145 emphasizes cost-effectiveness. Low cost does not make microscopy the most sensitive or universally preferred initial test. Modern diagnostic pathways often prioritize rapid molecular tests. A positive skin test indicates an immune response, not proof that a person currently has contagious pulmonary TB; a negative test also does not reliably exclude disease in every host.</p>"
        },
        {
            id: "tb-prevention-and-treatment",
            title: "BCG, DOTS and the historical treatment mnemonic",
            sources: [{ document: "biology", page: 141 }, { document: "quick-revision", page: 175 }],
            html: "<p>BCG expands to Bacillus Calmette-Guerin. It is a vaccine used for TB prevention, particularly protection against severe childhood forms such as meningeal and disseminated TB. The source describes intradermal vaccination after birth or at an early health-service contact. Eligibility and timing follow the applicable immunization programme; 'first exposure to a hospital' is not a biological indication. BCG is not treatment for an established infection and does not guarantee prevention of every pulmonary infection.</p>" +
                "<p>DOTS stands for directly observed treatment, short-course, a TB-control strategy. The handwritten six-month mnemonic is two months of RIPE followed by four months of RI: rifampicin, isoniazid, pyrazinamide and ethambutol initially, followed by rifampicin and isoniazid. This describes a conventional drug-susceptible-TB regimen, not a universal prescription. Disease site, drug resistance, age and newer approved regimens can change duration and drugs; treatment requires an appropriate clinical programme.</p>" +
                "<p>The printed source locates the SAARC TB Centre and Nepal's national TB centre in Bhaktapur, Nepal, attached to an IOM 2005 examination annotation. This is retained as the source's institutional-location note, not a claim that names, administrative structures or public contact details have been independently updated.</p>"
        },
        {
            id: "enteric-fever-clinical",
            title: "Enteric fever, CARDS and intestinal involvement",
            sources: [{ document: "biology", page: 142 }, { document: "quick-revision", page: 175 }],
            html: "<p>Enteric fever includes typhoid, caused by <em>Salmonella enterica</em> serovar Typhi, and paratyphoid, caused by Paratyphi serovars. The source uses the familiar names <em>Salmonella typhi</em> and <em>S. paratyphi</em>. These are Gram-negative bacilli transmitted through the fecal-oral route, including contaminated food and water. The source's fourteen-day incubation is a typical teaching approximation, not an invariant duration.</p>" +
                "<table><thead><tr><th>CARDS</th><th>Source clinical feature</th></tr></thead><tbody><tr><td>C</td><td>Coated tongue</td></tr><tr><td>A</td><td>Abdominal pain</td></tr><tr><td>R</td><td>Rose spots on the trunk</td></tr><tr><td>D</td><td>Diarrhea</td></tr><tr><td>S</td><td>Splenomegaly, or enlargement of the spleen</td></tr></tbody></table>" +
                "<p>High fever with a step-ladder rise is a classic untreated-case description, not a required pattern. Relative bradycardia means the pulse rises less than expected for the temperature; it does not require a heart rate below 60 beats per minute. The source's reference pulse of 72 is an example rather than a universal normal value. Leukopenia or neutropenia can occur in enteric fever. The general contrasts 'bacterial infection increases neutrophils' and 'viral infection increases lymphocytes' are tendencies with important exceptions, not diagnostic rules.</p>" +
                "<p>Peyer's patches are lymphoid aggregates in the terminal ileum and are involved in typhoid pathology. Chronic carriage can involve persistence in the gallbladder, allowing intermittent fecal shedding even without continuous acute symptoms. The source's spelling 'Payer's patches' is corrected to Peyer's patches.</p>"
        },
        {
            id: "enteric-fever-investigations",
            title: "BASU: preserve the mnemonic, not a rigid testing calendar",
            sources: [{ document: "biology", page: 142 }, { document: "biology", page: 145 }, { document: "quick-revision", page: 175 }],
            html: "<table><thead><tr><th>Source week</th><th>BASU association</th></tr></thead><tbody><tr><td>First</td><td>B: blood culture</td></tr><tr><td>Second</td><td>A: antigen-antibody reaction, referring to the Widal agglutination test</td></tr><tr><td>Third</td><td>S: stool culture</td></tr><tr><td>Fourth</td><td>U: urine culture</td></tr></tbody></table>" +
                "<p>Blood culture can directly establish bacteremia and is especially useful early, although yield depends on specimen volume, prior antibiotics and disease timing. Widal tests serum antibodies against Salmonella antigens; a positive result may reflect prior exposure, vaccination or cross-reaction. Stool culture is also useful for shedding and carriage. Urine culture appears in the historical list but is not a universal fourth-week diagnostic requirement.</p>" +
                "<p><strong>Source correction:</strong> BASU is an examination memory aid, not a schedule in which each investigation becomes valid only during one week. Widal alone does not reliably confirm typhoid, especially in endemic settings. Diagnosis must integrate appropriate microbiological evidence and clinical context.</p>" +
                "<p>The source treatment lists collectively contain ciprofloxacin, chloramphenicol, azithromycin, amoxicillin and ceftriaxone. These names document teaching examples and older practice. None is declared a universally effective first-choice drug: resistance patterns and susceptibility results are decisive, and the lists are not self-medication instructions.</p>"
        },
        {
            id: "cholera",
            title: "Cholera: organism, secretory diarrhea and investigation",
            sources: [{ document: "biology", page: 142 }],
            html: "<p>Cholera is an acute diarrheal infection due to toxigenic <em>Vibrio cholerae</em>. The organism is a curved or comma-shaped Gram-negative bacillus; its flagellum confers motility. Transmission is fecal-oral, typically through contaminated water or food. The source gives an incubation of six hours to three days; this is not a hard limit, and commonly cited ranges extend from about twelve hours to five days.</p>" +
                "<ul><li>Profuse watery diarrhea can have a 'rice-water' appearance.</li><li>Large fluid losses cause dehydration and hypovolemia, with reduced blood pressure in severe cases.</li><li>Nausea is listed; vomiting may also occur.</li><li>Cholera toxin drives intestinal electrolyte and water secretion; its effect is not simply destruction of the bowel wall.</li></ul>" +
                "<p>The notes describe bacteria in stool as showing darting movement, likened to fish in a water stream. This refers to motility seen in a suitable microscopic preparation, not an appearance that a patient identifies by looking at stool. Culture is listed, including Monsur's medium, a historical selective medium. Organism confirmation requires suitable laboratory methods; appearance alone is insufficient.</p>" +
                "<p>The source emphasizes correction of dehydration with oral rehydration solution, locally called Jeevan Jal, and intravenous fluid when clinically indicated. It also lists tetracycline or doxycycline as 'DOC', with ciprofloxacin, ampicillin and erythromycin as other examples. <strong>Source qualification:</strong> fluid replacement is central, but severity, age, pregnancy and local susceptibility govern management. Antibiotics are selected for appropriate cases, not universally prescribed from this list, and severe dehydration requires urgent professional care.</p>"
        },
        {
            id: "influenza",
            title: "Influenza: types, surface proteins and RNA testing",
            sources: [{ document: "biology", page: 143 }],
            html: "<p>Influenza viruses have single-stranded RNA genomes. The source contrasts type A, associated with pandemics; type B, associated with major seasonal outbreaks; and type C, generally associated with milder respiratory illness. <strong>Source correction:</strong> this is the traditional human A-B-C teaching list, not the complete modern taxonomy, which also recognizes influenza D. Both A and B contribute to seasonal influenza; pandemic potential is not the same as severity in an individual.</p>" +
                "<p>Spread involves respiratory particles, including droplets and aerosols. The source gives an incubation of three to seven days; the usual incubation is shorter, about one to four days. Listed symptoms are sore throat, dry cough, fever, chest discomfort and body aches. They overlap with other infections and do not establish influenza without appropriate clinical context.</p>" +
                "<table><thead><tr><th>Label</th><th>Meaning</th></tr></thead><tbody><tr><td>H5N1</td><td>An influenza A subtype associated with avian influenza; not a name for every avian influenza virus</td></tr><tr><td>H1N1</td><td>An influenza A subtype; the 2009 pandemic strain was associated with swine-origin influenza</td></tr><tr><td>Hemagglutinin, H</td><td>Helps virions attach to and enter susceptible cells</td></tr><tr><td>Neuraminidase, N</td><td>Promotes release and spread of newly formed virions by cleaving sialic-acid residues</td></tr></tbody></table>" +
                "<p>The sketch shows an enveloped particle with surface projections and internal RNA; it is a simplified diagram, not a complete map of the segmented genome. A respiratory swab can be tested by reverse-transcription polymerase chain reaction, RT-PCR. Reverse transcription first makes a DNA template from viral RNA. Mild-case symptomatic care and oseltamivir are the source's treatment entries; antiviral use depends on clinical severity, risk, timing and guidance rather than a blanket 'drug of choice' rule.</p>"
        },
        {
            id: "hepatitis",
            title: "Hepatitis A-E: complete source comparison with qualifications",
            sources: [{ document: "biology", page: 143 }],
            html: "<p>Hepatitis means inflammation of the liver. Causes listed include viruses, chemicals, drugs, alcohol and certain genetic disorders. The source's clinical features are marked anorexia, nausea, jaundice, mild fever and right-upper-abdominal pain. Anorexia is loss of appetite, not 'severe appetite'. Liver blood tests, including bilirubin, assess injury or dysfunction; an elevated bilirubin is not specific for viral hepatitis. The source names viral markers but leaves their individual identities blank.</p>" +
                "<table><thead><tr><th>Virus</th><th>Genome</th><th>Main transmission distinction</th></tr></thead><tbody><tr><td>Hepatitis A</td><td>RNA</td><td>Fecal-oral</td></tr><tr><td>Hepatitis B</td><td>DNA</td><td>Infected blood, sexual exposure and perinatal transmission</td></tr><tr><td>Hepatitis C</td><td>RNA</td><td>Primarily bloodborne; sexual and vertical transmission can occur</td></tr><tr><td>Hepatitis D</td><td>RNA</td><td>Requires hepatitis B surface antigen; shares blood and body-fluid exposure routes</td></tr><tr><td>Hepatitis E</td><td>RNA</td><td>Fecal-oral in the source's waterborne context</td></tr></tbody></table>" +
                "<table><thead><tr><th>Virus</th><th>Source incubation entry</th><th>Interpretation</th></tr></thead><tbody><tr><td>A</td><td>2-6 weeks</td><td>A rough teaching interval; the usual range is about 15-50 days</td></tr><tr><td>B</td><td>1-6 months</td><td>Broad approximation; timing varies with infection and outcome measured</td></tr><tr><td>C</td><td>About 6 months</td><td>Not a typical fixed incubation; symptoms, when present, may begin much earlier</td></tr><tr><td>D</td><td>1-6 months</td><td>Not independent of whether infection is simultaneous with HBV or superimposed on chronic HBV</td></tr><tr><td>E</td><td>1-6 weeks</td><td>An incomplete teaching range; commonly cited incubation is about 2-10 weeks</td></tr></tbody></table>" +
                "<p>For A, the source says excellent recovery and lists fever, headache and jaundice. Most patients recover and chronic infection is not typical, but severe acute disease is possible. For B, it gives 5% chronic liver damage and 95% normal recovery, with lamivudine as treatment. <strong>Source qualification:</strong> chronicity is strongly age-dependent; adult-acquisition approximations cannot be applied to infected infants. Lamivudine is an antiviral example, not a universal preferred modern HBV regimen.</p>" +
                "<p>For C, the source gives 85% chronic liver damage and 15% cirrhosis or cancer. These do not form a valid universal outcome split: chronic infection is not synonymous with established liver damage, and cirrhosis and cancer are later risks, not an inevitable separate 15% outcome. Modern direct-acting antivirals can cure most treated HCV infections. For D, the labels 'non-solitary virus' and severe disease refer to its dependence on HBV and potential to aggravate hepatitis. For E, the source emphasizes increased risk in pregnancy and usually no chronicity; severe pregnancy-associated disease is important, but chronic HEV can occur in some immunocompromised patients.</p>"
        },
        {
            id: "candidiasis",
            title: "Candidiasis: risk factors, sites and source treatment list",
            sources: [{ document: "biology", page: 143 }],
            html: "<p>Candidiasis is a fungal infection, commonly involving the yeast <em>Candida albicans</em>. Candida can colonize skin, the gastrointestinal tract and genital mucosa. <strong>Source correction:</strong> although transmission or contact can occur in some settings, many cases result from overgrowth of a person's own colonizing yeast; candidiasis is not simply a disease acquired by physical contact.</p>" +
                "<p>The listed risk settings are low immunity, diabetes mellitus, burns, AIDS, chemotherapy, antibiotic use and surgery. These are risk associations, not a rule that everyone in these groups develops infection.</p>" +
                "<table><thead><tr><th>Site or form</th><th>Source clinical details</th></tr></thead><tbody><tr><td>Oral thrush</td><td>Whitish plaques on tongue, cheeks or palate, with an erythematous background</td></tr><tr><td>Angular cheilitis</td><td>Redness and inflammation at the corners of the mouth; Candida is one possible cause</td></tr><tr><td>Vulvovaginal candidiasis</td><td>Itching, soreness, painful intercourse, painful urination and discharge; the old term moniliasis is recorded</td></tr><tr><td>Candidal balanitis</td><td>Red patches or soreness of the glans or foreskin, sometimes with marked itching</td></tr><tr><td>Ear and nail disease</td><td>Otomycosis and onychomycosis name fungal infections at those sites, but are not specific to Candida</td></tr><tr><td>Deeper disease</td><td>Esophagitis, endocarditis and meningitis are named; esophageal disease is mucosal, not automatically disseminated bloodstream infection</td></tr></tbody></table>" +
                "<p>The source's whitish or gray discharge is not diagnostically specific; classic candidal discharge is often thick and white, and other causes must be distinguished clinically. Microscopic examination and culture are listed investigations. Fluconazole and ketoconazole are named drugs. These are not interchangeable self-treatment choices: species, site and resistance matter, and oral ketoconazole has substantial toxicity concerns and is not routine first-line candidiasis treatment.</p>"
        },
        {
            id: "hiv-biology-and-course",
            title: "HIV, CD4 cells and the source's historical stage scheme",
            sources: [{ document: "biology", page: 144 }],
            html: "<p>HIV, human immunodeficiency virus, is a retrovirus. HIV-1 and HIV-2 are distinguished. HIV-1 is globally distributed, not restricted to the US, Europe and Asia as the source's short map might imply. HIV-2 has a strong historical association with West Africa but is not confined there. World AIDS Day is 1 December.</p>" +
                "<p>HIV infects CD4-bearing cells, notably helper T lymphocytes, and progressive depletion and dysfunction undermine immune responses. The diagram RNA &rarr; DNA describes reverse transcription, historically called Teminism in some examination notes. AIDS is the advanced immune-deficiency syndrome, not a synonym for every stage of HIV infection.</p>" +
                "<table><thead><tr><th>Source stage label</th><th>Meaning and correction</th></tr></thead><tbody><tr><td>Acute viral stage</td><td>Early infection may produce a nonspecific febrile illness; it is not safely identified as an ordinary respiratory infection from cough and fever alone</td></tr><tr><td>Window stage</td><td>A test-dependent interval before a test can reliably detect infection; it overlaps early infection and is not a separate mandatory symptom-free disease stage</td></tr><tr><td>Asymptomatic stage</td><td>May persist for years without treatment; generalized lymphadenopathy can occur and is a sign even if other symptoms are absent</td></tr><tr><td>AIDS-related complex</td><td>Historical label for symptoms such as persistent fever, diarrhea and weight loss with impaired immunity; not the preferred modern staging system</td></tr><tr><td>Advanced AIDS</td><td>Marked immunodeficiency with opportunistic infections and certain cancers; treatment can prevent progression and improve outcomes</td></tr></tbody></table>" +
                "<p>The source's 'months to years' and 'ten years or more' describe variable untreated natural history, not the interval before all tests become positive. The fever-diarrhea-weight-loss triangle explains the historical nickname 'slim disease', which is not a diagnostic criterion. TB is an important opportunistic infection, particularly where prevalent; it is not universally the most common in every setting. Kaposi sarcoma and non-Hodgkin lymphoma are the listed cancer associations.</p>" +
                "<p><strong>Source correction:</strong> early infection may have a high viral load, but 'maximum transmission in the window stage' is not a universal rule. Symptoms and detectability depend on timing and assay. The notes' obsolete AIDS name is misspelled; the historical label GRID was inaccurate and stigmatizing and is not an appropriate disease name. The separate handwritten former-name abbreviation for HIV is unclear and is not reconstructed into a scored fact.</p>"
        },
        {
            id: "hiv-transmission-tests-and-treatment",
            title: "HIV transmission, diagnostic algorithms and antiretroviral names",
            sources: [{ document: "biology", page: 144 }, { document: "biology", page: 145 }],
            html: "<p>The documented transmission routes are sexual exposure, infected blood or blood products, and vertical transmission from mother to child. Needle or sharps exposure is a blood-exposure route, but the source's fourth line, 'infected transmission', is unfinished and does not identify a particular object. HIV is not transmitted by ordinary social contact.</p>" +
                "<p><strong>Source correction:</strong> the source ranks 'blood &gt; vertical &gt; homo &gt; hetero'. This must not be treated as a quantitative rule or a ranking of identities. Risk depends on the specific exposure, viral load, protection and treatment, not a person's orientation. Unscreened infected transfusion and different sexual acts have different risks; effective treatment and prevention alter those risks substantially.</p>" +
                "<table><thead><tr><th>Listed test</th><th>Role</th></tr></thead><tbody><tr><td>ELISA or other immunoassay</td><td>Detects relevant antibodies and, in combined assays, antigen; used within a validated testing algorithm</td></tr><tr><td>Western blot</td><td>Historical supplemental antibody test; no longer a universal preferred confirmatory step</td></tr><tr><td>HIV antigen-antibody test</td><td>Combines markers to improve detection at appropriate stages</td></tr><tr><td>HIV viral load</td><td>Measures viral nucleic acid; especially important for monitoring treatment, with diagnostic use in selected algorithms</td></tr></tbody></table>" +
                "<p>A negative result within a test's window period cannot establish that infection is absent. A reactive screening result requires the prescribed supplemental pathway. The source's ELISA-then-Western-blot pair is retained as historical teaching, not imposed on current services.</p>" +
                "<p>HAART means highly active antiretroviral therapy, now generally called combination ART. Listed names are tenofovir, lamivudine, zidovudine, AZT, nevirapine and saquinavir. AZT, azidothymidine, is zidovudine, not a second distinct drug. The source's 'nevirapine for child' is context-limited historical shorthand, not a universal pediatric recommendation. Drug combinations are selected through current professional guidance; these names are neither a complete modern regimen nor evidence of a cure that removes all latent HIV.</p>"
        },
        {
            id: "parasite-habitats",
            title: "Parasite sites and vectors: every entry in the habitat list",
            sources: [{ document: "biology", page: 145 }, { document: "biology", page: 148 }],
            html: "<table><thead><tr><th>Parasite</th><th>Checked interpretation of the source entry</th></tr></thead><tbody><tr><td>Roundworm; Ascaris</td><td>Adult Ascaris inhabits the small intestine. The source separately writes 'roundworm - jejunum' and 'Ascaris - ileum'; roundworm is not a sufficiently specific second taxon to justify this contrast</td></tr><tr><td>Giardia duodenalis</td><td>Also called G. lamblia or G. intestinalis; trophozoites attach in the upper small intestine, including duodenum and jejunum</td></tr><tr><td>Entamoeba histolytica</td><td>Colon is the main intestinal site; the source also mentions appendix. Disease is not restricted to the appendix</td></tr><tr><td>Enterobius vermicularis</td><td>Pinworm; adults mainly inhabit the ileocecal and adjacent colonic region, and can be found in the appendix</td></tr><tr><td>Trichuris trichiura</td><td>Whipworm; chiefly cecum and colon</td></tr><tr><td>Schistosoma haematobium</td><td>Adults inhabit venous plexuses associated with the urinary bladder, not the bladder lumen as free-swimming worms</td></tr><tr><td>Plasmodium</td><td>Blood-stage parasites occur within red cells; human liver stages must not be forgotten</td></tr><tr><td>Leishmania</td><td>Sand-fly transmission; in humans the characteristic amastigotes are intracellular in macrophages, not simply free parasites in blood</td></tr><tr><td>African trypanosomes</td><td>Tsetse-fly transmission; cause African sleeping sickness, with blood, lymph and later nervous-system involvement</td></tr></tbody></table>" +
                "<p><strong>Source correction:</strong> the asserted Giardia ranking 'jejunum &gt; duodenum' does not make duodenum a wrong answer to a question asking where infection can occur. The two upper-small-intestinal sites should be distinguished from ileal Peyer's patches in typhoid and the large-intestinal habitats of several other parasites. A vector entry and a host-tissue entry answer different questions.</p>"
        },
        {
            id: "cardiovascular-disorders",
            title: "Cardiovascular disorders: ischemia, infarction, failure and arrest",
            sources: [{ document: "biology", page: 146 }],
            html: "<table><thead><tr><th>Disorder</th><th>Definition and source distinction</th></tr></thead><tbody><tr><td>Arteriosclerosis</td><td>Thickening and loss of elasticity of arterial walls; arterial stiffness often increases with age and can contribute to raised pressure</td></tr><tr><td>Atherosclerosis</td><td>Intimal plaques containing lipids, cholesterol, inflammatory and fibrous components; calcification may occur</td></tr><tr><td>Myocardial ischemia</td><td>Insufficient oxygen supply relative to myocardial demand, commonly from reduced coronary blood flow</td></tr><tr><td>Heart failure</td><td>A syndrome of impaired cardiac filling or pumping sufficient to meet the body's needs; ischemic injury is one cause, not the only cause</td></tr><tr><td>Myocardial infarction</td><td>Death of heart-muscle tissue caused by prolonged ischemia; commonly called a heart attack</td></tr><tr><td>Cardiac arrest</td><td>Abrupt loss of effective cardiac pumping and circulation; not identical to myocardial infarction</td></tr><tr><td>Stroke or cerebrovascular accident</td><td>Brain injury from interrupted blood supply or bleeding, which may cause paralysis and other focal deficits</td></tr><tr><td>Congenital heart defect</td><td>Structural abnormality of the heart or great vessels present from birth, arising during development</td></tr></tbody></table>" +
                "<p>The notes' phrase 'cry for oxygen by the heart' refers most closely to ischemic chest discomfort or angina, not the definition of heart failure. Infarction can cause severe pain but can also be atypical or silent. The source attributes arrest to happiness, shock or sadness; emotions are not its defining cause, and dangerous arrhythmias and other cardiac or noncardiac problems are important mechanisms. Stroke includes hemorrhagic as well as ischemic events, correcting the source's blood-flow-stop-only definition.</p>" +
                "<p>Rheumatic heart disease follows immune-mediated damage after infection with group A streptococci. Cross-reactive immune responses can injure valves. <strong>Source correction:</strong> the source highlights bicuspid and tricuspid valves, but the mitral, or bicuspid, valve is most commonly affected and aortic involvement is also important; isolated tricuspid involvement is much less typical. This is not simply ongoing direct bacterial infection of the valve.</p>"
        },
        {
            id: "respiratory-disorders",
            title: "COPD, chronic bronchitis, asthma and bronchiectasis",
            sources: [{ document: "biology", page: 146 }, { document: "biology", page: 147 }],
            html: "<p>Chronic obstructive pulmonary disease, COPD, involves persistent airflow obstruction. Cigarette smoke and other harmful inhaled particles or pollutants are major risk exposures. Chronic bronchitis and emphysema are important related clinical or pathological patterns. The smoking list also explicitly associates COPD with emphysema.</p>" +
                "<table><thead><tr><th>Condition</th><th>Source details with corrected boundaries</th></tr></thead><tbody><tr><td>Chronic bronchitis</td><td>Long-term airway inflammation, excess mucus and chronic productive cough; smoking is an important risk factor and infections may complicate disease</td></tr><tr><td>Asthma</td><td>Chronic airway inflammation with variable airflow limitation; triggers may provoke smooth-muscle spasm, swelling and cough</td></tr><tr><td>Bronchiectasis</td><td>Permanent abnormal widening of bronchi with damaged walls, impaired mucus clearance and recurrent infection risk</td></tr><tr><td>Cystic fibrosis</td><td>An inherited disorder of epithelial ion transport that can cause thick secretions and bronchiectasis, but is not a synonym for bronchiectasis</td></tr><tr><td>Emphysema</td><td>Destruction of alveolar walls with enlargement of distal air spaces, reducing effective gas-exchange surface</td></tr></tbody></table>" +
                "<p><strong>Source correction:</strong> putting asthma and 'cystic fibrosis/bronchiectasis' beneath a COPD heading conflates distinct disorders. They can share cough or obstruction, and overlap can occur, but they are not all one smoke-induced disease. Airway narrowing with mucus differs mechanistically from irreversible bronchial dilation.</p>"
        },
        {
            id: "renal-disorders",
            title: "Kidney disease, stones, cysts and urinary infection",
            sources: [{ document: "biology", page: 146 }],
            html: "<p>Chronic kidney disease means persistent abnormalities of kidney structure or function; diabetes and hypertension are major causes. The source's unspecific 'most common' label has no defined comparison. Loss of kidney function can progress to kidney failure, but neither every kidney disorder nor every urinary infection inevitably does so.</p>" +
                "<table><thead><tr><th>Source term</th><th>Meaning and qualification</th></tr></thead><tbody><tr><td>Nephritis</td><td>Kidney inflammation; glomerular inflammatory disease can produce a nephritic syndrome</td></tr><tr><td>Nephrosis and nephrotic syndrome</td><td>Older nephrosis terminology contrasts with inflammation. Nephrotic syndrome is characterized by heavy urinary protein loss and related features; it is not simply a synonym for all non-inflammatory kidney disease</td></tr><tr><td>Renal calculus or nephrolithiasis</td><td>A kidney stone; calcium oxalate is an important composition. The source sentence ends after 'calcium oxalate crystals' and gives no completed mechanism or management</td></tr><tr><td>Polycystic kidney disease</td><td>Inherited development of multiple renal cysts, usually noncancerous; the common adult form is autosomal dominant, but a recessive form also exists</td></tr><tr><td>Urinary tract infection</td><td>Usually bacterial; the source names urethra and bladder, with possible ascent to the kidneys</td></tr></tbody></table>" +
                "<p>UTIs are more frequent in women in many populations, partly because of urinary anatomy; this is a population association rather than an exclusion of male infection. Ascending infection can cause pyelonephritis and serious complications, but the source's automatic progression from untreated bladder infection to kidney failure overstates inevitability.</p>"
        },
        {
            id: "sedatives-and-opioids",
            title: "Psychoactive drugs: sedatives, hypnotics and opioids",
            sources: [{ document: "biology", page: 147 }],
            html: "<p>The source groups this material under 'social diseases'. Substance-use disorders are health conditions, not moral failings. Psychoactive or psychotropic drugs affect brain function; the label is not restricted to just the two categories bracketed in the source.</p>" +
                "<p>Sedatives reduce arousal; hypnotics promote sleep. Tranquilizer is an older broad term for calming medicines. These effects can overlap and depend on dose and drug. The notes list barbiturates, gamma-hydroxybutyrate, Valium and benzodiazepines. <strong>Source correction:</strong> Valium is diazepam, a benzodiazepine, not a barbiturate, and gamma-hydroxybutyrate is a separate depressant. Benzodiazepines can cause sleepiness, so 'calmness without inducing sleep' is not an absolute class definition.</p>" +
                "<ul><li>Listed depressant effects include impaired concentration or thinking, slowed reactions, calmness, blurred vision and impaired depth perception.</li><li>Source clinical uses include anxiety, tension, panic disorders, sleep disorders and seizures. Which medicine is appropriate depends on the condition; the list is not permission to take a sedative for every listed symptom.</li><li>Dependence, respiratory depression and dangerous interactions are important reasons these are supervised medical or public-health subjects.</li></ul>" +
                "<p>Opioids act at opioid receptors and can relieve pain; some also produce euphoria and reduced anxiety. Natural opium alkaloids come from the latex of unripe capsules of <em>Papaver somniferum</em>. Morphine is an important analgesic, and codeine has analgesic and historically antitussive uses. The source identifies heroin as a chemically modified morphine derivative and pethidine as a synthetic opioid. These are chemical or pharmacological relationships, not preparation instructions.</p>" +
                "<p>The slang 'brown sugar' for illicit heroin and the source's 'most dangerous' label are retained only as source terminology. Illicit composition and overdose risk vary; no single ranking makes another opioid safe. Narcotic is an imprecise older term, not a substitute for a receptor-based classification.</p>"
        },
        {
            id: "hallucinogens-and-stimulants",
            title: "Hallucinogens, cannabinoids and stimulants: corrected source identities",
            sources: [{ document: "biology", page: 147 }],
            html: "<p>The source describes altered perception, dreamlike or floating sensations, nightmares, dilated pupils and uncontrolled laughter under hallucinogens/cannabinoids. These are possible effects rather than a diagnostic checklist, and hallucination is not the same as unconsciousness. Cannabinoids and classical hallucinogens are not identical pharmacological classes.</p>" +
                "<table><thead><tr><th>Source example</th><th>Corrected identification</th></tr></thead><tbody><tr><td>LSD</td><td>A semisynthetic lysergic-acid derivative related to ergot alkaloids; it is not simply naturally extracted LSD from Claviceps purpurea</td></tr><tr><td>Cannabis</td><td>Cannabinoids occur in Cannabis sativa and related cultivated forms</td></tr><tr><td>Marijuana or ganja</td><td>Source association with female flowering material; vernacular composition can vary</td></tr><tr><td>Bhang</td><td>Traditionally associated mainly with leaves, not simply seeds as written</td></tr><tr><td>Charas and hashish</td><td>Resin-based cannabis products, not merely dried leaves; no preparation method is given</td></tr><tr><td>Cocaine</td><td>A stimulant alkaloid of coca, Erythroxylum species, not Theobroma cacao</td></tr><tr><td>Caffeine</td><td>A milder stimulant, including in coffee from Coffea arabica; diuretic effects depend on dose and habituation</td></tr><tr><td>Amphetamine</td><td>A sympathomimetic CNS stimulant related functionally to catecholamine signalling</td></tr></tbody></table>" +
                "<p>Stimulants increase CNS activity and can increase wakefulness and perceived alertness. The source calls cocaine a strong stimulant and links its euphoria to dopamine. More precisely, cocaine inhibits monoamine reuptake, including dopamine transport. The slang coke or crack names drug forms or street terminology, not distinct safe medicines. Amphetamine is described as an 'antisleep' or 'superman' drug; these are informal, potentially misleading labels, not clinical claims about superior performance.</p>" +
                "<p><strong>Source correction:</strong> coca and cacao are different plants; <em>Theobroma cacao</em> is the cocoa plant. The source's unfinished 'dope test to find out' line supplies no assay, analyte or interpretive rule, so none is invented. The material is educational pharmacology and risk awareness, not guidance for recreational use.</p>"
        },
        {
            id: "alcohol-and-tobacco",
            title: "Alcohol-related disease, thiamine and tobacco harms",
            sources: [{ document: "biology", page: 147 }],
            html: "<p>The alcohol discussed is ethanol. The source sequence is fatty liver, liver fibrosis, cirrhosis and hepatocellular carcinoma. Fibrosis involves excessive extracellular-matrix deposition; cirrhosis includes advanced architectural distortion. These are possible consequences of sustained harmful exposure, not an inevitable ordered sequence in every person. Alcohol also has effects outside the liver.</p>" +
                "<p><strong>Source correction:</strong> the page writes vitamin B12 deficiency and then equates it with thiamine deficiency. Thiamine is vitamin B1, not B12. Alcohol-use disorder can be associated with poor thiamine intake, absorption or utilization. Listed deficiency syndromes are beriberi, Wernicke encephalopathy and Korsakoff syndrome. Wernicke and Korsakoff syndromes describe related but distinct neurological consequences, not synonyms for uncomplicated intoxication.</p>" +
                "<p>Tobacco is associated with <em>Nicotiana tabacum</em>. Nicotine is a major addictive constituent. Tar is a mixture containing carcinogenic substances, including polycyclic aromatic hydrocarbons such as benzo[a]pyrene; tar and benzo[a]pyrene are not synonyms. The source's cancer list includes lung, bladder, kidney and oral-cavity cancers. It also links smoking with COPD, emphysema and cardiovascular disease.</p>" +
                "<p>Distinguishing addiction from carcinogenic exposure is useful: nicotine helps sustain dependence, while combustion products carry many carcinogenic and cardiopulmonary hazards. This does not make nicotine harmless or imply that tobacco risks are limited to the named examples.</p>"
        },
        {
            id: "medicines-and-anaesthesia",
            title: "Antipyretics, analgesics, antiseptics and anaesthesia",
            sources: [{ document: "biology", page: 148 }],
            html: "<table><thead><tr><th>Class</th><th>Source examples and meaning</th></tr></thead><tbody><tr><td>Antipyretic</td><td>Reduces fever; paracetamol, aspirin and historical phenacetin are listed</td></tr><tr><td>Analgesic</td><td>Relieves pain; paracetamol, aspirin, morphine, codeine and heroin/diamorphine appear in the source</td></tr><tr><td>Anti-inflammatory</td><td>Reduces inflammation; ibuprofen and mefenamic acid are the examples</td></tr><tr><td>Anaesthetic</td><td>Produces loss of sensation, with or without unconsciousness depending on type; examples are cocaine, ether, chloroform, ethylene and nitrous oxide, N<sub>2</sub>O</td></tr><tr><td>Antiseptic</td><td>Inhibits or kills microorganisms on living tissue at an appropriate formulation and concentration</td></tr></tbody></table>" +
                "<p>Aspirin is acetylsalicylic acid. A medicine can be both analgesic and antipyretic, so these categories are not mutually exclusive. The source's antiseptic inventory is Dettol, Savlon, phenol, Salol, Iodol, boric acid and potassium permanganate. Dettol and Savlon are product names; formulations vary. Salol, Iodol and several other entries represent older antiseptic practice. The list supplies neither an approved use nor a safe concentration.</p>" +
                "<p><strong>Source qualification:</strong> phenacetin and chloroform are obsolete or withdrawn from ordinary clinical use in many settings because of toxicity. Historical anaesthetic and opioid examples must not be taken as household alternatives. Antiseptics and disinfectants are distinguished by intended substrate and formulation, not merely by a chemical's name.</p>" +
                "<p>Local anaesthetics block voltage-gated sodium channels and interrupt propagation of nerve impulses. The source's 'closing of voltage-gated Na<sup>+</sup> ion' means channel blockade, not removal of the sodium ion. Many general anaesthetics enhance inhibitory signalling, including GABA-mediated signalling, and/or reduce excitatory signalling, including glutamatergic signalling. <strong>Source correction:</strong> this is not a universal increase in GABA concentration and decrease in glutamate concentration; different agents act at different molecular targets.</p>"
        },
        {
            id: "genetic-disease-comparisons",
            title: "Genetic disorders: source karyotypes without stereotypes",
            sources: [{ document: "biology", page: 148 }],
            html: "<table><thead><tr><th>Condition</th><th>Genetic basis</th><th>Source features with qualification</th></tr></thead><tbody><tr><td>Down syndrome</td><td>Usually trisomy 21; can affect either sex</td><td>Characteristic facial features, a single transverse palmar crease in some people, variable intellectual disability, and increased likelihood of cardiac, hearing or gastrointestinal conditions</td></tr><tr><td>Turner syndrome</td><td>Typically 45,X, with mosaic and structural variants</td><td>Female phenotype, short stature, broad chest and often ovarian insufficiency with reduced fertility; mnemonic 'Turn on female' is a source memory aid, not diagnostic evidence</td></tr><tr><td>Klinefelter syndrome</td><td>Typically 47,XXY, with variants</td><td>Male phenotype, long limbs, small testes and variable hypogonadism, reduced muscle mass, gynecomastia and impaired fertility</td></tr><tr><td>Marfan syndrome</td><td>A gene-related connective-tissue disorder, not a numerical chromosome disorder</td><td>The source explicitly distinguishes it from the aneuploidies</td></tr><tr><td>Patau syndrome</td><td>Trisomy 13</td><td>A distinct autosomal aneuploidy</td></tr><tr><td>Edwards syndrome</td><td>Trisomy 18</td><td>A distinct autosomal aneuploidy</td></tr><tr><td>Triple-X syndrome</td><td>47,XXX</td><td>Female phenotype with variable effects; many have normal fertility</td></tr><tr><td>XYY syndrome</td><td>47,XYY</td><td>Male phenotype with variable developmental features; does not establish criminality</td></tr></tbody></table>" +
                "<p><strong>Source correction:</strong> the obsolete ethnic label written beside Down syndrome is inappropriate and is replaced with the clinical name. The source's blanket 'sterility' for XXX is false. 'Super female', 'super male' and 'criminal male' are misleading labels, not biological diagnoses or valid predictions of behaviour. The Klinefelter list's small-penis statement is not a necessary feature; testicular insufficiency is the more characteristic distinction. Chromosome findings cannot be used to infer an individual's worth, personality or criminal behaviour.</p>" +
                "<p>The source's short male-only and female-only mnemonics refer to the usual phenotypic associations of these syndromes, not to a complete account of every mosaic or sex-development variant. None of the listed physical features alone establishes a karyotype.</p>"
        },
        {
            id: "giardiasis",
            title: "Giardiasis: upper-intestinal disease and life-cycle stages",
            sources: [{ document: "biology", page: 148 }, { document: "biology", page: 145 }],
            html: "<p>Giardiasis is caused by <em>Giardia duodenalis</em>, also called <em>G. lamblia</em> or <em>G. intestinalis</em>. The source calls it backpacker's disease, reflecting exposure to contaminated untreated water; it is not confined to travelers. Transmission is fecal-oral through ingestion of cysts. The listed seven-day incubation is a teaching approximation; symptoms commonly begin after about one to two weeks, with variation.</p>" +
                "<p>Symptoms listed are foul-smelling fatty stools and abdominal pain. Steatorrhea means excess fat in stool and reflects malabsorption; not every case presents identically. Routine microscopic examination of stool, RME, can identify cysts or trophozoites. A single negative sample need not exclude infection because shedding varies. The source names metronidazole as treatment; this is a recognized drug example, not a universal self-treatment instruction.</p>" +
                "<table><thead><tr><th>Stage</th><th>Source-linked interpretation</th></tr></thead><tbody><tr><td>Cyst</td><td>The environmentally resistant infective stage ingested by the next host</td></tr><tr><td>Trophozoite</td><td>The active intestinal stage that attaches to mucosa and contributes to disease; typically pear-shaped or tennis-racket-shaped, bilaterally symmetrical, with two nuclei</td></tr></tbody></table>" +
                "<p><strong>Source correction:</strong> a Giardia trophozoite has four pairs of flagella, not the single pair written under the sketch. The sketch's single central dot is not an accurate representation of its two nuclei. The source question circles both duodenum and jejunum in different ways; both are valid upper-small-intestinal sites, so a single-choice question must not present them as mutually exclusive alternatives without an additional defensible condition. Ileal Peyer's patches instead belong to the source's typhoid comparison.</p>"
        },
        {
            id: "shared-page-developmental-biology",
            title: "Shared revision page: eggs and early development",
            sources: [{ document: "quick-revision", page: 175 }],
            html: "<p>The disease revision page continues into developmental biology. These legible boundary notes are preserved here rather than silently omitted. Aristotle is traditionally called the father of embryology, and Karl Ernst von Baer the father of modern embryology; these are historical honorifics.</p>" +
                "<table><thead><tr><th>Yolk amount</th><th>Definition and source examples</th></tr></thead><tbody><tr><td>Microlecithal</td><td>Little yolk; starfish, Amphioxus and many mammals are the examples. Human eggs are often called alecithal because they lack appreciable nutritive yolk</td></tr><tr><td>Mesolecithal</td><td>Moderate yolk; frog and other amphibian eggs are standard examples</td></tr><tr><td>Macrolecithal</td><td>Abundant yolk; many arthropods, fishes, reptiles and birds, without implying that every member has identical yolk quantity</td></tr></tbody></table>" +
                "<table><thead><tr><th>Yolk distribution</th><th>Meaning and examples</th></tr></thead><tbody><tr><td>Isolecithal or homolecithal</td><td>Relatively even distribution, commonly with little yolk</td></tr><tr><td>Telolecithal</td><td>Concentrated toward the vegetal pole; degree varies among frog, reptile, bird and fish examples</td></tr><tr><td>Centrolecithal</td><td>Concentrated centrally; cockroach is the source example</td></tr></tbody></table>" +
                "<p>The following cleavage descriptions concern the frog context, not all animals. The first cleavage is meridional and holoblastic; the second is meridional at right angles to the first. The third is displaced toward the animal pole, producing smaller animal-pole and larger yolk-rich vegetal-pole blastomeres. Subsequent cleavage remains complete but is unequal in its overall pattern; not every later individual division has an identical geometry.</p>" +
                "<p>A morula is a solid, mulberry-like cluster of blastomeres. The source's 'after 32-cell stage' is a rough stage association, not a universal cell-number boundary. <strong>Source correction:</strong> the fluid-filled blastocoel belongs to the blastula, not a defining hollow morula. In a frog coeloblastula it lies toward the animal hemisphere; its fluid is not usefully defined by a universal 'albuminous' label.</p>" +
                "<p>The gray crescent marks the future dorsal side in the classical frog description and appears through cytoplasmic reorganization after fertilization, before the blastula stage. Gastrulation establishes ectoderm, mesoderm and endoderm and the primitive gut cavity, the archenteron. These developmental entries are not used to pad the disease-question target.</p>"
        }
    ],
    pageCoverage: [
        { document: "quick-revision", page: 175, status: "transcribed", sectionIds: ["cancer-screening-and-investigation", "tb-prevention-and-treatment", "enteric-fever-clinical", "enteric-fever-investigations", "shared-page-developmental-biology"], unresolved: [] },
        { document: "biology", page: 140, status: "transcribed", sectionIds: ["disease-study-and-scope", "cancer-behaviour", "cancer-origins-and-viruses", "cancer-screening-and-investigation"], unresolved: [] },
        { document: "biology", page: 141, status: "transcribed", sectionIds: ["tb-cause-and-transmission", "tb-lesions-and-clinical-features", "tb-investigations", "tb-prevention-and-treatment"], unresolved: [] },
        { document: "biology", page: 142, status: "transcribed", sectionIds: ["enteric-fever-clinical", "enteric-fever-investigations", "cholera"], unresolved: [] },
        { document: "biology", page: 143, status: "partial", sectionIds: ["influenza", "hepatitis", "candidiasis"], unresolved: ["Right column, hepatitis Diagnosis: 'Hepatitis Viral Marker' is followed by an empty line; the intended individual marker names are not supplied. No marker identity or diagnostic cutoff is reconstructed."] },
        { document: "biology", page: 144, status: "partial", sectionIds: ["cancer-origins-and-viruses", "hiv-biology-and-course", "hiv-transmission-tests-and-treatment"], unresolved: ["Right column below the ART list: the handwritten abbreviation after 'Old name of HIV' cannot be resolved reliably; it is not expanded or used in a question.", "Bottom-left transmission list: the fourth item reads 'Infected Transmission' but names no material, instrument or exposure. Its intended completion is unknown."] },
        { document: "biology", page: 145, status: "partial", sectionIds: ["disease-study-and-scope", "cancer-screening-and-investigation", "tb-investigations", "enteric-fever-investigations", "hiv-transmission-tests-and-treatment", "parasite-habitats", "giardiasis"], unresolved: ["Lower-right Habitats list distinguishes 'Round worm - jejunum' from 'Ascaris - ileum' without specifying a different roundworm taxon. The intended species distinction cannot be recovered; only the supported small-intestinal habitat is taught."] },
        { document: "biology", page: 146, status: "partial", sectionIds: ["cardiovascular-disorders", "respiratory-disorders", "renal-disorders"], unresolved: ["Right column, Renal stone/calculi/nephrolithiasis: the sole explanatory line stops after 'When calcium oxalate crystals,'; the intended remaining mechanism or consequence is absent."] },
        { document: "biology", page: 147, status: "partial", sectionIds: ["respiratory-disorders", "sedatives-and-opioids", "hallucinogens-and-stimulants", "alcohol-and-tobacco"], unresolved: ["Right column under Amphetamine: 'Dope Test to find out' is unfinished and supplies no named assay, analyte or result interpretation."] },
        { document: "biology", page: 148, status: "transcribed", sectionIds: ["parasite-habitats", "medicines-and-anaesthesia", "genetic-disease-comparisons", "giardiasis"], unresolved: [] }
    ],
    questions: [
        {
            id: "note-diseases-001", text: "A normally regulated growth-promoting gene becomes persistently activated in a tumour. Which term describes the altered gene?",
            options: [{ key: "a", text: "Carcinogen" }, { key: "b", text: "Antigen" }, { key: "c", text: "Oncogene" }, { key: "d", text: "Antibody" }], answer: "c",
            explanation: "An oncogene is an abnormally activated or expressed growth-promoting gene. A carcinogen is an agent that can cause cancer, not the name of the altered gene; antigens and antibodies belong to a different distinction. Biology p. 140 supplies the gene-versus-agent comparison.", sectionId: "cancer-behaviour", source: { document: "biology", page: 140 }, cognitive: "understanding"
        },
        {
            id: "note-diseases-002", text: "Malignant cells arising from an epithelial lining are classified primarily as which tumour type?",
            options: [{ key: "a", text: "Carcinoma" }, { key: "b", text: "Sarcoma" }, { key: "c", text: "Lymphoma" }, { key: "d", text: "Leukemia" }], answer: "a",
            explanation: "Carcinoma is an epithelial malignancy; sarcoma arises from mesenchymal tissues. Lymphoma and leukemia are hematolymphoid malignancies, correcting their misleading placement under sarcoma in the source. The tissue-origin comparison is on Biology p. 140.", sectionId: "cancer-origins-and-viruses", source: { document: "biology", page: 140 }, cognitive: "recall"
        },
        {
            id: "note-diseases-003", text: "A lung tumour gives rise to a separate deposit of the same malignant cells in bone. Which process does the new deposit demonstrate?",
            options: [{ key: "a", text: "Encapsulation" }, { key: "b", text: "Apoptosis" }, { key: "c", text: "Differentiation" }, { key: "d", text: "Metastasis" }], answer: "d",
            explanation: "A distant secondary tumour established by cells from a primary tumour is a metastasis. Growth confined to neighbouring tissue would instead be local invasion. Blood and lymph are important dissemination routes in the Biology p. 140 notes.", sectionId: "cancer-behaviour", source: { document: "biology", page: 140 }, cognitive: "application"
        },
        {
            id: "note-diseases-004", text: "An abnormal cervical Pap smear is followed by examination of a tissue biopsy. What is the main distinction between these two steps?",
            options: [{ key: "a", text: "Both methods demonstrate invasion in intact tissue" }, { key: "b", text: "Cytology screens; histology can establish tissue diagnosis" }, { key: "c", text: "Both methods establish whether distant metastases exist" }, { key: "d", text: "Cytology proves invasion; histology only screens shed cells" }], answer: "b",
            explanation: "Pap cytology is a screening investigation for cervical cellular abnormalities, while histopathology evaluates tissue architecture and can establish a diagnosis of invasion. An abnormal screen is not automatically proof of invasive cancer. Biology pp. 140 and 145 distinguish these named investigations.", sectionId: "cancer-screening-and-investigation", source: { document: "biology", page: 145 }, cognitive: "understanding"
        },
        {
            id: "note-diseases-005", text: "Which cell-wall constituent explains the characteristic acid-fast behaviour emphasized for the tubercle bacillus?",
            options: [{ key: "a", text: "Cellulose" }, { key: "b", text: "Mycolic acids" }, { key: "c", text: "Chitin fibres" }, { key: "d", text: "Pectin chains" }], answer: "b",
            explanation: "Mycolic acids contribute to the lipid-rich mycobacterial wall and its acid-fast properties. Cellulose, chitin and pectin are not the distinguishing mycobacterial wall constituent in this comparison. Biology p. 141 links mycolic acid with acid-fast staining.", sectionId: "tb-cause-and-transmission", source: { document: "biology", page: 141 }, cognitive: "recall"
        },
        {
            id: "note-diseases-006", text: "Which finding must be added to a primary pulmonary Ghon focus to describe the classical Ghon complex?",
            options: [{ key: "a", text: "Calcification of every lung lesion" }, { key: "b", text: "A second focus in the opposite lung" }, { key: "c", text: "A positive serum antibody titre" }, { key: "d", text: "Involvement of draining lymph nodes" }], answer: "d",
            explanation: "The Ghon complex combines the primary lung focus with involved regional draining lymph nodes. The labelled lung-and-node drawing on Biology p. 141 depicts this relationship. A focus alone is not the complete complex.", sectionId: "tb-lesions-and-clinical-features", source: { document: "biology", page: 141 }, cognitive: "understanding"
        },
        {
            id: "note-diseases-007", text: "A positive Mantoux test is the only available finding in a hypothetical record. Which conclusion is supported by that result alone?",
            options: [{ key: "a", text: "Mycobacterial antigen sensitization is present" }, { key: "b", text: "Contagious pulmonary TB is already confirmed" }, { key: "c", text: "Rifampicin resistance has been demonstrated" }, { key: "d", text: "Viable bacilli have been cultured from sputum" }], answer: "a",
            explanation: "Mantoux testing measures a delayed cell-mediated response to mycobacterial antigens. It cannot alone distinguish latent infection from active TB, identify drug resistance or demonstrate a positive culture. Biology pp. 141 and 145 provide the skin-test entry, with these diagnostic limits explained in the typed section.", sectionId: "tb-investigations", source: { document: "biology", page: 141 }, cognitive: "application"
        },
        {
            id: "note-diseases-008", text: "Which pairing correctly separates the two TB-related abbreviations BCG and DOTS?",
            options: [{ key: "a", text: "BCG: culture medium; DOTS: staining method" }, { key: "b", text: "BCG: antibody assay; DOTS: vaccine strain" }, { key: "c", text: "BCG: preventive vaccine; DOTS: treatment strategy" }, { key: "d", text: "BCG: molecular assay; DOTS: skin-test antigen" }], answer: "c",
            explanation: "BCG is Bacillus Calmette-Guerin, a vaccine, whereas DOTS means directly observed treatment, short-course. The printed revision p. 175 and Biology p. 141 explicitly make the prevention-versus-treatment distinction. Neither abbreviation names a stand-alone test for active infection.", sectionId: "tb-prevention-and-treatment", source: { document: "quick-revision", page: 175 }, cognitive: "recall"
        },
        {
            id: "note-diseases-009", text: "In the CARDS mnemonic for enteric fever, the final letter refers to enlargement of which organ?",
            options: [{ key: "a", text: "Thyroid" }, { key: "b", text: "Pancreas" }, { key: "c", text: "Thymus" }, { key: "d", text: "Spleen" }], answer: "d",
            explanation: "S represents splenomegaly, enlargement of the spleen. The other mnemonic entries are coated tongue, abdominal pain, rose spots and diarrhea. Biology p. 142 presents the complete CARDS list; it is a memory aid, not a requirement that every patient show every feature.", sectionId: "enteric-fever-clinical", source: { document: "biology", page: 142 }, cognitive: "recall"
        },
        {
            id: "note-diseases-010", text: "An enteric-fever carrier continues shedding Salmonella Typhi after the acute illness has resolved. Which reservoir is specifically highlighted in the notes?",
            options: [{ key: "a", text: "Terminal ileum" }, { key: "b", text: "Gallbladder" }, { key: "c", text: "Mesenteric nodes" }, { key: "d", text: "Liver parenchyma" }], answer: "b",
            explanation: "Persistent colonization of the gallbladder can contribute to chronic typhoid carriage and intermittent fecal shedding. It is distinct from the acute involvement of ileal Peyer's patches. Both sites and their different roles are recorded on Biology p. 142.", sectionId: "enteric-fever-clinical", source: { document: "biology", page: 142 }, cognitive: "understanding"
        },
        {
            id: "note-diseases-011", text: "Why should the BASU mnemonic not be interpreted as proving typhoid whenever a second-week Widal result is positive?",
            options: [{ key: "a", text: "Widal directly identifies living bacteria in the blood" }, { key: "b", text: "A single titre is unaffected by previous vaccination" }, { key: "c", text: "Detected antibodies can reflect exposure or cross-reaction" }, { key: "d", text: "Antibodies are detectable only during one specified week" }], answer: "c",
            explanation: "Widal is an antibody agglutination test, and positivity is not specific proof of current typhoid. Prior exposure, vaccination and cross-reaction complicate interpretation. Biology pp. 142 and 145 supply BASU, but the typed correction rejects a rigid week-by-week diagnostic rule.", sectionId: "enteric-fever-investigations", source: { document: "biology", page: 142 }, cognitive: "understanding"
        },
        {
            id: "note-diseases-012", text: "The immediate danger described for profuse cholera diarrhea is best explained by which physiological change?",
            options: [{ key: "a", text: "Large fluid loss reduces circulating volume" }, { key: "b", text: "Vasodilation causes shock without fluid loss" }, { key: "c", text: "Red-cell destruction produces severe anemia" }, { key: "d", text: "Bowel-wall invasion causes major hemorrhage" }], answer: "a",
            explanation: "Profuse secretory diarrhea removes water and electrolytes, causing dehydration and hypovolemia, with hypotension in severe cases. This explains the source's emphasis on rehydration rather than treating the stool's appearance as the main danger. The symptom and treatment links are on Biology p. 142.", sectionId: "cholera", source: { document: "biology", page: 142 }, cognitive: "understanding"
        },
        {
            id: "note-diseases-013", text: "Which description fits the cholera organism in the checked source comparison?",
            options: [{ key: "a", text: "Curved Gram-negative motile bacillus" }, { key: "b", text: "Acid-fast nonmotile tubercle bacillus" }, { key: "c", text: "Budding yeast with pseudohyphal forms" }, { key: "d", text: "Intracellular red-cell protozoan stage" }], answer: "a",
            explanation: "Vibrio cholerae is a curved or comma-shaped Gram-negative bacterium with flagellar motility. The alternatives describe a mycobacterial, fungal or protozoan pattern rather than Vibrio. Biology p. 142 links its shape, Gram reaction and darting motility.", sectionId: "cholera", source: { document: "biology", page: 142 }, cognitive: "recall"
        },
        {
            id: "note-diseases-014", text: "A hypothetical influenza mutation mainly impairs release of newly formed virions from cells. Which surface-protein function is most directly affected?",
            options: [{ key: "a", text: "Hemagglutinin-mediated attachment" }, { key: "b", text: "Matrix-protein-mediated assembly" }, { key: "c", text: "Neuraminidase-mediated release" }, { key: "d", text: "RNA-polymerase-mediated copying" }], answer: "c",
            explanation: "Neuraminidase promotes release by cleaving sialic-acid residues, whereas hemagglutinin mainly supports attachment and entry. Assembly and genome copying are different parts of viral reproduction, not this surface-mediated release step. The entry-versus-exit comparison is on Biology p. 143.", sectionId: "influenza", source: { document: "biology", page: 143 }, cognitive: "application"
        },
        {
            id: "note-diseases-015", text: "Among the hepatitis viruses compared on the source page, which is distinguished by a DNA genome?",
            options: [{ key: "a", text: "Hepatitis A virus" }, { key: "b", text: "Hepatitis B virus" }, { key: "c", text: "Hepatitis C virus" }, { key: "d", text: "Hepatitis E virus" }], answer: "b",
            explanation: "Hepatitis B virus has a DNA genome, while the A, C and E viruses listed here have RNA genomes. This distinction does not make their transmission routes identical. The genome column on Biology p. 143 supplies the checked comparison.", sectionId: "hepatitis", source: { document: "biology", page: 143 }, cognitive: "recall"
        },
        {
            id: "note-diseases-016", text: "Which existing infection provides the essential viral surface antigen needed by hepatitis D virus?",
            options: [{ key: "a", text: "Hepatitis A infection" }, { key: "b", text: "Hepatitis C infection" }, { key: "c", text: "Hepatitis E infection" }, { key: "d", text: "Hepatitis B infection" }], answer: "d",
            explanation: "HDV depends on hepatitis B surface antigen and therefore occurs with HBV coinfection or as superinfection in a person with HBV. This is the precise meaning behind the source's 'non-solitary virus' label on Biology p. 143, not a dependence on any hepatitis virus indiscriminately.", sectionId: "hepatitis", source: { document: "biology", page: 143 }, cognitive: "understanding"
        },
        {
            id: "note-diseases-017", text: "Candida overgrowth after broad antibacterial exposure most directly illustrates which source-linked principle?",
            options: [{ key: "a", text: "The episode necessarily came from a fresh external contact" }, { key: "b", text: "Antibacterial exposure prevents endogenous fungal growth" }, { key: "c", text: "Altered host conditions can permit opportunistic growth" }, { key: "d", text: "The episode alone proves resistance to antifungal medicines" }], answer: "c",
            explanation: "Candida may already colonize mucosal sites, and altered microbial or immune conditions can allow opportunistic overgrowth. Antibiotic use is among the risk settings listed on Biology p. 143. Physical contact is therefore not the only explanation for candidiasis.", sectionId: "candidiasis", source: { document: "biology", page: 143 }, cognitive: "understanding"
        },
        {
            id: "note-diseases-018", text: "Which source term refers specifically to candidal whitish plaques affecting the tongue, cheeks or palate?",
            options: [{ key: "a", text: "Otomycosis" }, { key: "b", text: "Onychomycosis" }, { key: "c", text: "Balanitis" }, { key: "d", text: "Oral thrush" }], answer: "d",
            explanation: "Oral thrush is the oral mucosal presentation described in the candidiasis list. Otomycosis concerns the ear, onychomycosis the nails and balanitis the glans. Biology p. 143 provides these site-specific names; signs still need clinical assessment rather than self-diagnosis.", sectionId: "candidiasis", source: { document: "biology", page: 143 }, cognitive: "recall"
        },
        {
            id: "note-diseases-019", text: "Loss of which lymphocyte population is central to the immune dysfunction highlighted for HIV?",
            options: [{ key: "a", text: "CD4 helper T cells" }, { key: "b", text: "CD8 cytotoxic T cells" }, { key: "c", text: "CD19-bearing B cells" }, { key: "d", text: "CD16/CD56 natural killer cells" }], answer: "a",
            explanation: "HIV targets CD4-bearing cells, notably helper T lymphocytes, impairing coordination of immune responses as disease progresses. Other lymphocyte populations can be affected indirectly, but helper T-cell depletion is the central source distinction. Biology p. 144 explicitly identifies helper T cells and CD4.", sectionId: "hiv-biology-and-course", source: { document: "biology", page: 144 }, cognitive: "recall"
        },
        {
            id: "note-diseases-020", text: "A teaching case has a negative HIV antibody test very soon after exposure. What does the test-window concept require the reader to recognize?",
            options: [{ key: "a", text: "Every negative result proves lifelong absence of HIV" }, { key: "b", text: "Early infection may precede reliable antibody detection" }, { key: "c", text: "An antibody result directly measures the viral genome" }, { key: "d", text: "The window begins only after advanced AIDS develops" }], answer: "b",
            explanation: "A test's window period is the interval before its marker becomes reliably detectable, so an early negative result cannot alone exclude infection. Different assays have different detection windows. The Biology p. 144 stage list is corrected to separate this testing concept from advanced disease staging.", sectionId: "hiv-transmission-tests-and-treatment", source: { document: "biology", page: 144 }, cognitive: "application"
        },
        {
            id: "note-diseases-021", text: "Which two entries in the handwritten antiretroviral list refer to the same medicine rather than two different drugs?",
            options: [{ key: "a", text: "Tenofovir and lamivudine" }, { key: "b", text: "AZT and zidovudine" }, { key: "c", text: "Nevirapine and saquinavir" }, { key: "d", text: "Lamivudine and nevirapine" }], answer: "b",
            explanation: "AZT is azidothymidine, also called zidovudine. Counting these as separate components would duplicate one medicine. Biology p. 144 lists both names, and the typed treatment section makes their identity explicit without recommending a regimen.", sectionId: "hiv-transmission-tests-and-treatment", source: { document: "biology", page: 144 }, cognitive: "recall"
        },
        {
            id: "note-diseases-022", text: "Which virus is associated with the vascular malignancy Kaposi sarcoma in the source's cancer comparison?",
            options: [{ key: "a", text: "Human herpesvirus 8" }, { key: "b", text: "Epstein-Barr virus" }, { key: "c", text: "Human papillomavirus" }, { key: "d", text: "Hepatitis B virus" }], answer: "a",
            explanation: "Kaposi sarcoma is associated with HHV-8, also called Kaposi sarcoma-associated herpesvirus. Advanced HIV-related immunodeficiency increases the risk, but HIV and HHV-8 are not the same virus. Biology p. 140 names the etiologic association and p. 144 lists the tumour in AIDS.", sectionId: "cancer-origins-and-viruses", source: { document: "biology", page: 140 }, cognitive: "recall"
        },
        {
            id: "note-diseases-023", text: "Which organism in the habitat list is the pinworm associated with the ileocecal region and sometimes the appendix?",
            options: [{ key: "a", text: "Trichuris trichiura" }, { key: "b", text: "Giardia duodenalis" }, { key: "c", text: "Schistosoma haematobium" }, { key: "d", text: "Enterobius vermicularis" }], answer: "d",
            explanation: "Enterobius vermicularis is pinworm. Trichuris is whipworm, Giardia is an upper-intestinal protozoan and S. haematobium is a blood fluke associated with urinary venous plexuses. Biology p. 145 supplies the names and site comparison.", sectionId: "parasite-habitats", source: { document: "biology", page: 145 }, cognitive: "recall"
        },
        {
            id: "note-diseases-024", text: "The phrase 'blood of the urinary tract' in the parasite list refers most precisely to the adult habitat of which organism?",
            options: [{ key: "a", text: "Entamoeba histolytica" }, { key: "b", text: "Ascaris lumbricoides" }, { key: "c", text: "Schistosoma haematobium" }, { key: "d", text: "Trichuris trichiura" }], answer: "c",
            explanation: "Adult S. haematobium inhabits venous plexuses associated with the bladder. The wording does not mean that adults ordinarily live free in urine. Biology p. 145 supplies the urinary-blood association, clarified in the typed habitat table.", sectionId: "parasite-habitats", source: { document: "biology", page: 145 }, cognitive: "understanding"
        },
        {
            id: "note-diseases-025", text: "A hypothetical coronary obstruction first causes oxygen shortage and later causes myocardial cell death. Which sequence names those two changes?",
            options: [{ key: "a", text: "Angina followed by cardiac arrest" }, { key: "b", text: "Infarction followed by ischemia" }, { key: "c", text: "Heart failure followed by atherosclerosis" }, { key: "d", text: "Ischemia followed by infarction" }], answer: "d",
            explanation: "Ischemia is insufficient oxygen delivery relative to demand; prolonged ischemia can cause tissue death, called infarction. Heart failure and cardiac arrest are different functional outcomes, not synonyms for the two stages. Biology p. 146 provides this cardiovascular distinction.", sectionId: "cardiovascular-disorders", source: { document: "biology", page: 146 }, cognitive: "application"
        },
        {
            id: "note-diseases-026", text: "The valve injury described after streptococcal infection in rheumatic heart disease chiefly illustrates which mechanism?",
            options: [{ key: "a", text: "Persistent direct bacterial invasion of valve tissue" }, { key: "b", text: "Passive deposition of cholesterol on valve surfaces" }, { key: "c", text: "Cross-reactive immune injury to host tissues" }, { key: "d", text: "A primary congenital failure of valve formation" }], answer: "c",
            explanation: "Rheumatic heart disease is immune-mediated: responses to group A streptococci can cross-react with host tissues and injure valves. It is not simply bacteria continuously multiplying in a valve. Biology p. 146 identifies the autoimmune relationship, with the valve distribution corrected in the notes.", sectionId: "cardiovascular-disorders", source: { document: "biology", page: 146 }, cognitive: "understanding"
        },
        {
            id: "note-diseases-027", text: "Which term concerns acute vascular injury to brain tissue rather than loss of effective cardiac pumping?",
            options: [{ key: "a", text: "Cardiac arrest" }, { key: "b", text: "Cerebrovascular accident" }, { key: "c", text: "Congenital heart defect" }, { key: "d", text: "Rheumatic valve disease" }], answer: "b",
            explanation: "A cerebrovascular accident is a stroke, involving ischemic or hemorrhagic injury to the brain. Cardiac arrest instead means loss of effective heart pumping and circulation. Biology p. 146 distinguishes the organ involved, while the correction includes hemorrhagic stroke omitted by the source shorthand.", sectionId: "cardiovascular-disorders", source: { document: "biology", page: 146 }, cognitive: "understanding"
        },
        {
            id: "note-diseases-028", text: "Which pairing avoids the source's conflation of bronchiectasis with cystic fibrosis?",
            options: [{ key: "a", text: "Bronchiectasis: dilated bronchi; cystic fibrosis: inherited ion-transport disorder" }, { key: "b", text: "Bronchiectasis: transient bronchial spasm; cystic fibrosis: smoke-induced airway disease" }, { key: "c", text: "Bronchiectasis: alveolar-wall destruction; cystic fibrosis: permanently dilated bronchi" }, { key: "d", text: "Bronchiectasis: inherited ion-transport disorder; cystic fibrosis: allergic airway spasm" }], answer: "a",
            explanation: "Bronchiectasis describes permanent abnormal bronchial dilation, whereas cystic fibrosis is an inherited disorder that can cause bronchiectasis. They are not synonyms and are not both simply cigarette-induced COPD. The relevant conflated heading occurs on Biology p. 146.", sectionId: "respiratory-disorders", source: { document: "biology", page: 146 }, cognitive: "understanding"
        },
        {
            id: "note-diseases-029", text: "Which pair is specifically emphasized as major causes of chronic kidney disease in the source?",
            options: [{ key: "a", text: "Diabetes and hypertension" }, { key: "b", text: "Renal calculi and urinary infections" }, { key: "c", text: "Polycystic disease and nephritis" }, { key: "d", text: "Urinary obstruction and pyelonephritis" }], answer: "a",
            explanation: "Diabetes and hypertension are the two principal causes named in the renal section of Biology p. 146. They can damage kidney structure and function over time. The fact that other diseases can also affect kidneys does not make the alternative pairs the source's emphasized comparison.", sectionId: "renal-disorders", source: { document: "biology", page: 146 }, cognitive: "recall"
        },
        {
            id: "note-diseases-030", text: "Which statement best captures the source's adult polycystic-kidney-disease example without overstating it?",
            options: [{ key: "a", text: "The adult form is acquired from a preceding bladder infection" }, { key: "b", text: "The renal cysts are malignant growths in most affected adults" }, { key: "c", text: "The common adult form is inherited only through the maternal line" }, { key: "d", text: "The common adult form has dominant inheritance and multiple cysts" }], answer: "d",
            explanation: "The notes describe autosomal-dominant polycystic kidney disease with multiple noncancerous cysts. A recessive form also exists, so the adult example cannot be generalized to every inherited cystic condition. Biology p. 146 is the source of the inheritance and cyst entries.", sectionId: "renal-disorders", source: { document: "biology", page: 146 }, cognitive: "understanding"
        },
        {
            id: "note-diseases-031", text: "Correcting the alcohol-related vitamin note, thiamine belongs to which vitamin designation?",
            options: [{ key: "a", text: "Vitamin B2" }, { key: "b", text: "Vitamin B6" }, { key: "c", text: "Vitamin B1" }, { key: "d", text: "Vitamin B12" }], answer: "c",
            explanation: "Thiamine is vitamin B1. Its deficiency is associated with beriberi and Wernicke-Korsakoff syndromes; the handwritten equation with B12 is incorrect. Biology p. 147 provides the deficiency sequence that the typed section explicitly repairs.", sectionId: "alcohol-and-tobacco", source: { document: "biology", page: 147 }, cognitive: "recall"
        },
        {
            id: "note-diseases-032", text: "Which plant identification corrects the source's mistaken association of cocaine with the cocoa plant?",
            options: [{ key: "a", text: "Theobroma cacao, the cocoa plant" }, { key: "b", text: "Erythroxylum species, the coca plants" }, { key: "c", text: "Coffea arabica, the coffee plant" }, { key: "d", text: "Nicotiana tabacum, the tobacco plant" }], answer: "b",
            explanation: "Cocaine is a coca alkaloid associated with Erythroxylum species, not Theobroma cacao. Coffee and tobacco supply different source examples in the same study material. Biology p. 147 contains the botanical misidentification, corrected explicitly without any drug-preparation instructions.", sectionId: "hallucinogens-and-stimulants", source: { document: "biology", page: 147 }, cognitive: "recall"
        },
        {
            id: "note-diseases-033", text: "Which distinction correctly interprets the tobacco components in the source?",
            options: [{ key: "a", text: "Nicotine causes dependence; benzo[a]pyrene is noncarcinogenic" }, { key: "b", text: "Tar is one purified compound; nicotine is an inactive filler" }, { key: "c", text: "Nicotine sustains dependence; tar contains carcinogenic substances" }, { key: "d", text: "Nicotine is the sole carcinogen; tar contains no active compounds" }], answer: "c",
            explanation: "Nicotine is a major addictive constituent, while tar is a mixture containing carcinogens such as benzo[a]pyrene. This distinction does not imply that nicotine is harmless. Biology p. 147 separates addiction from carcinogenic constituents in its smoking notes.", sectionId: "alcohol-and-tobacco", source: { document: "biology", page: 147 }, cognitive: "understanding"
        },
        {
            id: "note-diseases-034", text: "Which source example is a synthetic opioid rather than a stimulant or a benzodiazepine?",
            options: [{ key: "a", text: "Caffeine" }, { key: "b", text: "Pethidine" }, { key: "c", text: "Diazepam" }, { key: "d", text: "Amphetamine" }], answer: "b",
            explanation: "Pethidine is the synthetic opioid listed beside morphine, codeine and heroin in Biology p. 147. Caffeine and amphetamine are stimulants; diazepam is a benzodiazepine. The question concerns pharmacological classification, not a recommendation to use any of these drugs.", sectionId: "sedatives-and-opioids", source: { document: "biology", page: 147 }, cognitive: "recall"
        },
        {
            id: "note-diseases-035", text: "A local anaesthetic prevents a peripheral nerve impulse from propagating. Which direct channel effect matches the source mechanism?",
            options: [{ key: "a", text: "Blockade of voltage-gated sodium channels" }, { key: "b", text: "Activation of voltage-gated sodium channels" }, { key: "c", text: "Opening of nicotinic acetylcholine channels" }, { key: "d", text: "Activation of presynaptic calcium channels" }], answer: "a",
            explanation: "Local anaesthetics block voltage-gated sodium channels, preventing the regenerative sodium current needed for action-potential propagation. The source wording about 'closing Na ions' should be read as channel blockade. Biology p. 148 provides this mechanism and contrasts it with general anaesthesia.", sectionId: "medicines-and-anaesthesia", source: { document: "biology", page: 148 }, cognitive: "understanding"
        },
        {
            id: "note-diseases-036", text: "Which listed medicine illustrates that antipyretic and analgesic categories can overlap?",
            options: [{ key: "a", text: "Morphine" }, { key: "b", text: "Codeine" }, { key: "c", text: "Nitrous oxide" }, { key: "d", text: "Paracetamol" }], answer: "d",
            explanation: "Paracetamol appears in both the fever-reducing and pain-relieving lists on Biology p. 148. Morphine and codeine are opioids, and nitrous oxide is an anaesthetic with analgesic effects; they are not standard antipyretics. Class overlap is a pharmacological point, not dosing advice.", sectionId: "medicines-and-anaesthesia", source: { document: "biology", page: 148 }, cognitive: "recall"
        },
        {
            id: "note-diseases-037", text: "Which Giardia stage is the resistant form normally ingested to establish infection in a new host?",
            options: [{ key: "a", text: "Trophozoite" }, { key: "b", text: "Cyst" }, { key: "c", text: "Sporozoite" }, { key: "d", text: "Merozoite" }], answer: "b",
            explanation: "The cyst is Giardia's environmentally resistant infective stage, whereas the trophozoite is the active intestinal form. Sporozoite and merozoite are not Giardia stages in this life cycle. Biology p. 148 explicitly labels cyst as infective and trophozoite as pathogenic.", sectionId: "giardiasis", source: { document: "biology", page: 148 }, cognitive: "recall"
        },
        {
            id: "note-diseases-038", text: "Why is an unqualified single-answer Giardia question defective if it offers duodenum and jejunum as separate competing sites?",
            options: [{ key: "a", text: "Trophozoites attach only in the ileum, not either offered site" }, { key: "b", text: "Only the resistant cyst attaches at both of the offered sites" }, { key: "c", text: "Both sites can support upper-small-intestinal trophozoites" }, { key: "d", text: "Both alternatives identify the parasite's biliary reservoir" }], answer: "c",
            explanation: "Giardia trophozoites inhabit the upper small intestine, including both duodenum and jejunum. A question without another valid qualifier can therefore have two defensible answers. Biology pp. 145 and 148 contain the conflicting emphasis, which is corrected rather than turned into an arbitrary scored key.", sectionId: "giardiasis", source: { document: "biology", page: 148 }, cognitive: "understanding"
        },
        {
            id: "note-diseases-039", text: "Which disorder is explicitly separated from numerical chromosome abnormalities in the source comparison?",
            options: [{ key: "a", text: "Patau syndrome" }, { key: "b", text: "Edwards syndrome" }, { key: "c", text: "Triple-X syndrome" }, { key: "d", text: "Marfan syndrome" }], answer: "d",
            explanation: "Marfan syndrome is a gene-related connective-tissue disorder, not a change in chromosome number. Patau, Edwards and triple-X syndromes are numerical chromosome conditions in this comparison. Biology p. 148 explicitly labels Marfan as not a chromosome-number disorder.", sectionId: "genetic-disease-comparisons", source: { document: "biology", page: 148 }, cognitive: "understanding"
        },
        {
            id: "note-diseases-040", text: "A teaching karyotype shows a third copy of chromosome 13. Which named syndrome matches that finding?",
            options: [{ key: "a", text: "Patau syndrome" }, { key: "b", text: "Edwards syndrome" }, { key: "c", text: "Down syndrome" }, { key: "d", text: "Turner syndrome" }], answer: "a",
            explanation: "Trisomy 13 is Patau syndrome. Edwards syndrome usually involves trisomy 18, Down syndrome usually trisomy 21, and Turner syndrome typically 45,X. These chromosome-number associations are legible in the Biology p. 148 comparison and do not rely on any stereotyped behavioural labels.", sectionId: "genetic-disease-comparisons", source: { document: "biology", page: 148 }, cognitive: "application"
        }
    ]
};