window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["dynamics"] = {
  id: "dynamics",
  subject: "Physics",
  title: "Linear motion, forces and energy",
  sections: [
    {
      id: "newton-laws",
      title: "Newton's laws and equilibrium",
      sources: [{ document: "quick-revision", page: 2 }],
      html: "<p>The first law is the source's qualitative description of equilibrium: in an inertial frame, a body stays at rest or continues with constant velocity when its resultant external force is zero. Equilibrium does not require zero velocity; it requires zero acceleration for a constant-mass particle.</p><p>The second law is quantitative. The resultant force equals the rate of change of momentum, $\\vec F_{\\mathrm{net}}=\\frac{d\\vec p}{dt}$. For constant mass, $\\vec p=m\\vec v$ and $\\vec F_{\\mathrm{net}}=m\\vec a$. The source calls this the 'universal law'; this is a revision label for the second law, not an additional law or a claim that classical mechanics applies without limits.</p><p>The third law describes interactions: the force of one body on another has an equal-magnitude, opposite-direction partner acting on the first body. These forces act on different bodies, so they do not cancel in the free-body diagram of either body alone. <strong>Source correction:</strong> the printed third-law shorthand 'Property of body' is not a statement of the third law; inertia is the body's resistance to a change of velocity.</p>"
    },
    {
      id: "rope-loads-apparent-weight",
      title: "Rope loads, apparent weight and free fall",
      sources: [{ document: "quick-revision", page: 2 }, { document: "quick-revision", page: 3 }],
      html: "<p>For a climber of mass $m$ supported only by a vertical rope and gravity, upward acceleration of magnitude $a$ requires $T=m(g+a)$. Downward acceleration of magnitude $a$ gives $T=m(g-a)$ while the rope remains taut. A rope does not break if the required tension does not exceed its breaking tension. Velocity direction alone does not decide which expression applies: a descending climber who is slowing down accelerates upward.</p><p>The source's 'up: $(\\beta+1)$; down: $(1-\\beta)$' can represent $\\frac{T}{mg}=1\\pm\\beta$ if $\\beta=\\frac{a}{g}$. The source supplies neither this definition nor the omitted force scale, so this is an explicitly conditional interpretation.</p><p>A scale's normal reaction similarly obeys $N=m(g+a_y)$ for upward-positive acceleration. During ideal free fall, $a_y=-g$ and $N=0$. Thus floor friction proportional to that normal reaction also vanishes, as stated on page 3. This does not eliminate contact forces caused by an independently applied sideways push against a wall.</p><p>The page 2 quick-step statement says that weight first decreases and then gradually increases. True gravitational weight $mg$ has not changed. Such a sequence of apparent weight requires an appropriate downward-then-upward acceleration of the centre of mass; the page gives no motion sequence or weighing arrangement that makes it universal.</p>"
    },
    {
      id: "jet-momentum-recoil",
      title: "Momentum flux, recoil and propulsion",
      sources: [{ document: "quick-revision", page: 2 }],
      html: "<p>A steady jet with density $\\rho$, cross-sectional area $A$ and speed $v$ carries mass at the rate $\\dot m=\\rho Av$. Removing its incoming axial velocity requires force of magnitude $F=\\dot m v=\\rho Av^2$. This is the source's force-to-hold-a-pipe result for an ideal momentum-flux arrangement. Actual pipe support loads may also include pressure forces and the inlet momentum.</p><p>If a fixed obstacle reverses the whole jet through $180^\\circ$ with the same speed, the axial velocity change has magnitude $2v$, giving $F=2\\rho Av^2$. Merely deflecting or slowing the water is not necessarily a complete reversal; the force follows the actual momentum change.</p><p>Total linear momentum of a system is constant when its resultant external force is zero; over a short event it is enough for the external impulse to be negligible. In the recoil example, initially stationary projectile and launcher acquire equal and opposite momenta. If the projectile momentum magnitude is $p$, a freely recoiling launcher of mass $M$ has speed $\\frac{p}{M}$ and kinetic energy $\\frac{p^2}{2M}$. This explains the source's stronger-recoil observation for a lighter rifle at the same projectile momentum; the subjective effect also depends on how recoil is arrested.</p><p>Rocket propulsion illustrates both momentum conservation for rocket plus exhaust and Newton's third-law interaction between them. Exhaust is accelerated backward and the rocket is pushed forward. The rocket need not push against surrounding air.</p>"
    },
    {
      id: "unresolved-force-fragments",
      title: "Force fragments with missing arrangements",
      sources: [{ document: "quick-revision", page: 2 }],
      html: "<p>The isolated line 'Spring: Sum of force on either side' has no associated spring arrangement. The net force is a vector sum of external forces, but the reading of an ideal massless spring pulled equally at its two ends is the tension at either end, not twice that tension. The intended configuration cannot be identified from this line.</p><p>Two further printed results are 'Body freely falls: $g\\cot\\theta$' and 'Remains at rest: $g\\tan\\theta$'. These are dimensionally accelerations, but no diagram, definition of $\\theta$, direction of acceleration or moving support is supplied. They are retained here as unresolved source expressions, not usable free-fall laws. Ordinary unrestrained free fall near Earth has downward acceleration $g$.</p>"
    },
    {
      id: "inclined-plane-motion",
      title: "Smooth and rough inclined planes",
      sources: [{ document: "quick-revision", page: 2 }],
      html: "<p>The source diagram shows a block on a plane of slope length $l$, vertical height $h$ and angle $\\theta$ to the horizontal. Its geometrical relation is $h=l\\sin\\theta$. For a smooth fixed plane, the downhill component of gravity gives $a=g\\sin\\theta$ and the normal reaction is $N=mg\\cos\\theta$.</p><p>Starting from rest, the speed after descending the whole slope is $v=\\sqrt{2gh}$, equivalently $v=\\sqrt{2gl\\sin\\theta}$. The source labels this speed $u$; it is the attained speed, not a nonzero starting speed. Using $s=\\frac12at^2$, one obtains $t^2=\\frac{2s}{a}$ and, for $s=l$, $t^2=\\frac{2l}{g\\sin\\theta}$. Thus $t=\\sqrt{\\frac{2l}{g\\sin\\theta}}$, or $t=\\sqrt{\\frac{2h}{g\\sin^2\\theta}}$.</p><p>With kinetic coefficient $\\mu_k$ and no other applied force, a block already sliding down has downhill acceleration $a=g(\\sin\\theta-\\mu_k\\cos\\theta)$. If this is negative, its downhill motion is slowing; starting from rest additionally requires overcoming static friction. A block sliding up has gravity and friction both directed down the plane. Its downhill acceleration magnitude is $g(\\sin\\theta+\\mu_k\\cos\\theta)$, or its signed uphill acceleration is the negative of that expression. <strong>Source correction:</strong> the positive 'Up' formula is a retardation magnitude, not an acceleration directed up the slope.</p>"
    },
    {
      id: "friction-model",
      title: "Static, limiting and sliding friction",
      sources: [{ document: "quick-revision", page: 3 }],
      html: "<p>In the elementary dry-friction model, limiting friction is proportional to normal reaction: $f_{s,\\max}=\\mu_sN$. The coefficient depends on the nature and condition of the two surfaces. At fixed normal load it is approximately independent of apparent contact area; this is a model for ordinary dry contact, not a law for every adhesive or deformable surface.</p><p>Static friction is self-adjusting: it supplies the amount needed to prevent relative slipping, up to its limiting value. As an applied tangential force increases, static friction can increase until that limit is reached. <strong>Source correction:</strong> static friction is not always maximum. Before impending slip, $0\\leq f_s\\leq\\mu_sN$; an unloaded tangential contact can have $f_s=0$. For sliding, $f_k=\\mu_kN$ in the constant-coefficient model.</p><p>For a body sliding east on stationary level ground, kinetic friction acts west. For horizontal sliding stopped only by friction, the deceleration magnitude is $\\mu_kg$, stopping time is $t=\\frac{u}{\\mu_kg}$ and stopping distance is $s=\\frac{u^2}{2\\mu_kg}$. This explains the source's mass-independent stopping time and distance only when the initial speed, coefficient and gravitational field are the same. It does not apply to a fixed retarding force that is independent of mass.</p>"
    },
    {
      id: "friction-directions-work",
      title: "Walking, rolling, bicycle wheels and frictional work",
      sources: [{ document: "quick-revision", page: 3 }],
      html: "<p>Friction opposes actual or impending relative slip at the contact, not automatically the velocity of the centre of mass. During the propulsive part of walking, the foot pushes the ground backward and the ground's static friction pushes the walker forward.</p><p>The source's bicycle mnemonic, rear wheel forward and front wheel backward, applies to an ideal rear-driven bicycle accelerating forward without slipping: the applied driving torque makes the rear contact tend to slip backward, whereas backward friction supplies the forward-rolling angular acceleration of the passive front wheel. The same direction rule does not describe every braking or coasting condition.</p><p><strong>Source correction:</strong> 'rolling east means friction east' is not universal. Depending on the applied torque and force, static friction can point either way or be zero. The source's unpedalled-bicycle statement assigns backward friction to both wheels, but it omits the forces or torques causing retardation. On an ideal level surface with no resistance, a bicycle can coast uniformly with no tangential contact friction; with drag, bearing resistance or brakes, the required directions must be found from the equations of motion.</p><p>The source says no work is done against static friction. For ideal rolling without slipping on a stationary rigid surface, the instantaneous contact point is stationary, so the contact friction does zero instantaneous work on the rolling body. Static friction can nevertheless do work on a body carried by a moving or accelerating belt. The stationary-contact condition matters.</p>"
    },
    {
      id: "friction-ratio-shortcuts",
      title: "Interpreting the slope ratio shortcuts",
      sources: [{ document: "quick-revision", page: 3 }],
      html: "<p>The three printed coefficient expressions are: time, $(1-\\frac{1}{n^2})\\tan\\theta$; velocity, $(1-\\frac{1}{n^2})\\tan\\theta$; distance, $(1-\\frac{1}{n})\\tan\\theta$. The source does not define $n$, which comparison is smooth or rough, or what is held constant.</p><p>One consistent interpretation compares descents from rest on the same incline. Let $a_0=g\\sin\\theta$ be the smooth-plane acceleration and $a_r=g(\\sin\\theta-\\mu_k\\cos\\theta)$ the rough-plane acceleration. Then $\\frac{a_r}{a_0}=1-\\mu_k\\cot\\theta$.</p><ul><li>Over equal slope distances, if $n=\\frac{t_r}{t_0}$, then $\\frac{a_r}{a_0}=\\frac{1}{n^2}$ and $\\mu_k=(1-\\frac{1}{n^2})\\tan\\theta$.</li><li>Over equal slope distances, if $n=\\frac{v_0}{v_r}$, the squared-speed relation gives the same coefficient expression.</li><li>Over equal elapsed times, if $n=\\frac{s_0}{s_r}$, then $\\frac{a_r}{a_0}=\\frac{1}{n}$ and $\\mu_k=(1-\\frac{1}{n})\\tan\\theta$.</li></ul><p>These definitions are stated here explicitly; they are not present in the shorthand. Changing the meaning of $n$ or comparing velocities after equal times changes the formula.</p>"
    },
    {
      id: "minimum-pulling-forces",
      title: "Least pull, horizontal push and wall support",
      sources: [{ document: "quick-revision", page: 3 }, { document: "quick-revision", page: 4 }],
      html: "<p>Page 3 lists least force $W\\sin\\theta$, least horizontal force $W\\tan\\theta$ and the horizontal wall-support force $mg\\cot\\theta$. Page 4 gives $F=\\frac{mg\\sin\\theta}{\\cos(\\alpha-\\theta)}$ with a minimum-force label. The printed angles and force arrangement are not defined, so the following conditions are essential.</p><p>For a block of weight $W$ on a rough horizontal surface, define the angle of friction $\\phi$ by $\\mu_s=\\tan\\phi$. If a pull $P$ makes angle $\\alpha$ above the horizontal, $N=W-P\\sin\\alpha$. At impending forward motion, $P\\cos\\alpha=\\mu_sN$, hence $P=\\frac{\\mu_sW}{\\cos\\alpha+\\mu_s\\sin\\alpha}$. This is also $P=\\frac{W\\sin\\phi}{\\cos(\\alpha-\\phi)}$. Optimizing over the permitted angle gives $\\alpha=\\phi$ and $P_{\\min}=W\\sin\\phi$. A strictly horizontal pull needs $P=W\\tan\\phi$.</p><p>If the force instead pushes downward at the same angle, $N=W+P\\sin\\alpha$ and $P=\\frac{\\mu_sW}{\\cos\\alpha-\\mu_s\\sin\\alpha}$ when the denominator is positive. This is the stated reason angled pulling is easier than angled pushing. With both forces exactly horizontal there is no such advantage.</p><p>A horizontal force pressing a block against a rough vertical wall supplies $N=P$. Preventing downward slipping requires $\\mu_sP\\geq mg$, so $P_{\\min}=\\frac{mg}{\\mu_s}=mg\\cot\\phi$.</p><p>There is also a different, smooth-incline interpretation of the page 4 expression: for a plane at angle $\\theta$ and a supporting force at angle $\\alpha$ to the horizontal, balance along the plane gives $F\\cos(\\alpha-\\theta)=mg\\sin\\theta$, provided contact is retained. Least unrestricted support is $mg\\sin\\theta$ along the slope; horizontal support is $mg\\tan\\theta$. The source does not distinguish the slope angle from the angle of friction, so these interpretations must not be mixed.</p>"
    },
    {
      id: "atwood-and-balances",
      title: "Atwood machine, pulley load and balance readings",
      sources: [{ document: "quick-revision", page: 3 }, { document: "quick-revision", page: 4 }],
      html: "<p>For two hanging masses joined by a light inextensible string over a light frictionless fixed pulley, let $m_1&gt;m_2$. The heavier mass descends and the lighter rises with equal acceleration magnitude. The equations are $m_1g-T=m_1a$ and $T-m_2g=m_2a$. Thus $a=\\frac{m_1-m_2}{m_1+m_2}g$ and $T=\\frac{2m_1m_2}{m_1+m_2}g$.</p><p>When both string segments are vertical, their downward forces on the pulley add. The source's pulley thrust is $2T=\\frac{4m_1m_2}{m_1+m_2}g$, excluding the pulley's own weight. For nonparallel segments the support load is their vector resultant instead of automatically $2T$.</p><p>The source lists 'Equal arms: $\\frac{w_1+w_2}{2}$' on page 3 and 'Unequal arms: $\\sqrt{w_1w_2}$' on page 4, without defining the readings. A standard conditional application uses two weighings after exchanging the object between pans. With equal arms but an unchanged pan-weight offset, readings $W+\\delta$ and $W-\\delta$ average to the true weight. With unequal arms and otherwise balanced pans, reciprocal arm ratios give $w_1w_2=W^2$, so the true weight is their geometric mean. Without those repeated-weighing conditions, the two formulas are not general laws for any pair of weights.</p>"
    },
    {
      id: "chains-and-rough-patches",
      title: "Hanging chains and partly rough slopes",
      sources: [{ document: "quick-revision", page: 4 }],
      html: "<p>For a uniform chain of total mass $m$ and length $l$, suppose a fraction $\\frac{1}{n}$ hangs vertically below a smooth tabletop. The hanging mass is $\\frac{m}{n}$ and its centre of mass must rise by $\\frac{l}{2n}$ to reach the table. Slow retrieval without friction therefore requires $W=\\frac{mgl}{2n^2}$. <strong>Source clarification:</strong> the printed 'Pull hanging part' expression has units of work, not force; $m$ and $l$ must describe the complete chain for this form.</p><p>For a uniform chain of length $L$ at the verge of sliding off a rough horizontal table, let $x$ hang and let $\\lambda$ be mass per unit length. The hanging weight is $\\lambda xg$ and maximum table friction is $\\mu_s\\lambda(L-x)g$. Equating them gives $\\frac{x}{L}=\\frac{\\mu_s}{1+\\mu_s}$. This neglects edge friction and assumes the chain is flexible and uniformly distributed.</p><p>The source also prints $\\mu=\\frac{\\text{number of parts}}{\\text{number of rough parts}}\\tan\\theta$. It follows from an energy balance for equal-length portions of a fixed incline, identical friction on its rough portions, and equal initial and final kinetic energy: gravity does work $mgL\\sin\\theta$ and friction removes $\\mu mgL_r\\cos\\theta$. Thus $\\mu=\\frac{L}{L_r}\\tan\\theta$. The page omits the equal-length and endpoint-speed conditions; the counting shortcut must not be used without them.</p>"
    },
    {
      id: "conservative-energy",
      title: "Conservative forces, work and potential energy",
      sources: [{ document: "quick-revision", page: 4 }, { document: "quick-revision", page: 6 }],
      html: "<table><thead><tr><th>Conservative interaction</th><th>Nonconservative interaction</th></tr></thead><tbody><tr><td>Work between fixed endpoints is path-independent.</td><td>Work generally depends on the path or motion history.</td></tr><tr><td>A position-dependent potential energy can be assigned, with $W_c=-\\Delta U$.</td><td>No single position-only potential accounts for general dissipative work.</td></tr><tr><td>Mechanical energy $K+U$ stays constant if no other interaction transfers mechanical energy.</td><td>Mechanical energy can change, for example into internal energy.</td></tr><tr><td>Examples: gravity and a position-only central force $F(r)$.</td><td>Examples: sliding friction, viscous drag and resistive forces.</td></tr></tbody></table><p>This includes page 6's statement that potential energy belongs to conservative forces. <strong>Source correction:</strong> 'all central forces' needs the usual position-only, time-independent radial-force condition; a force being momentarily directed toward a centre is not by itself enough. Nonconservative force does not violate conservation of total energy, and zero net nonconservative work can leave mechanical energy unchanged even when such forces are present.</p><p>Momentum and nonrelativistic kinetic energy are related by $K=\\frac{p^2}{2m}$ and $p=\\sqrt{2mK}$. The source unit conversion is $1\\,\\mathrm{J}=10^7\\,\\mathrm{erg}$.</p><p>When like charges are brought closer, their electric potential energy increases; when unlike charges are brought closer, it decreases. With $U=\\frac{k_eq_1q_2}{r}$ and zero at infinite separation, these follow from the sign of $q_1q_2$. A bubble rising in water lowers the gravitational potential energy of the combined bubble-water system because heavier liquid moves down; the bubble's own gravitational potential energy need not decrease.</p><p>Oscillation takes place about a stable equilibrium, not while a body stays exactly at rest at equilibrium. The printed 'Work: P.E. attractive; on body increases (-ve), by body decreases (+ve)' mixes agents and signs. <strong>Source correction:</strong> when an attractive conservative interaction's potential energy increases, its own work is negative; when potential energy decreases, its work is positive. A slow external agent does the opposite work. Negative work and negative potential energy are different concepts, and the intended 'on/by body' labels are not defined on the page.</p>"
    },
    {
      id: "pumping-tank",
      title: "Work to empty a tank",
      sources: [{ document: "quick-revision", page: 4 }],
      html: "<p>Take a vertical tank of uniform cross-sectional area, height $h$ and initial full liquid mass $m$. Pump liquid slowly to the top edge, neglecting losses. A layer at height $y$ above the bottom is lifted through $h-y$, and its mass is $\\frac{m}{h}dy$. Therefore the work for the complete tank is $W=\\frac{mg}{h}\\int_0^h(h-y)\\,dy=\\frac{mgh}{2}$.</p><p>The source labels $\\frac{3mgh}{8}$ 'Half empty tank'. This is the work to remove the lower half that remains in an already half-empty tank, if $m$ still denotes the original full-tank mass. That remaining mass is $\\frac{m}{2}$ and its average lift is $\\frac{3h}{4}$. In contrast, emptying the upper half of an initially full tank requires only $\\frac{mgh}{8}$. These two amounts add to $\\frac{mgh}{2}$.</p><p><strong>Source clarification:</strong> the printed half-empty label does not specify the initial filling, outlet level, tank shape or meaning of $m$. The three results above state a consistent geometry and distinguish removing half from removing the remaining half; the unqualified source phrase is unresolved.</p>"
    },
    {
      id: "collision-conservation",
      title: "Collision conservation and special mass cases",
      sources: [{ document: "quick-revision", page: 4 }, { document: "quick-revision", page: 5 }],
      html: "<p>Total energy is conserved in a closed collision system, including kinetic, deformation, thermal and other internal forms. Total linear momentum is conserved when the external impulse during the collision is negligible. Translational kinetic energy is conserved in an elastic collision, but not generally in an inelastic collision.</p><p>Two equal masses exchange their velocities in a one-dimensional elastic collision. The source's equal-mass result requires this head-on condition; it is not a complete description of arbitrary two-dimensional scattering.</p><p>Page 5 starts with 'A is huge ($m_1\\gg m_2$), B rest' but gives no outcome or complete setup. If this means a head-on elastic collision of moving $m_1$ at speed $u$ with initially stationary $m_2$, the checked formulas are $v_1=\\frac{m_1-m_2}{m_1+m_2}u$ and $v_2=\\frac{2m_1}{m_1+m_2}u$. In that limit, $v_1\\approx u$ and $v_2\\approx2u$. These are conditional completion of the fragment, not a missing printed answer recovered from the image.</p><p>For an oblique elastic collision between equal masses with one initially stationary, momentum gives $\\vec u=\\vec v_1+\\vec v_2$ and kinetic energy gives $u^2=v_1^2+v_2^2$. Comparing the squared vector equation yields $\\vec v_1\\cdot\\vec v_2=0$. The two nonzero outgoing velocities are perpendicular, so the source angles obey $\\alpha+\\beta=90^\\circ$. <strong>Source correction:</strong> equal masses and nonzero outgoing speeds are needed for that directional conclusion; the printed line does not state the equal-mass restriction.</p><p>In an isolated explosion, stored internal energy can become kinetic energy while total momentum remains unchanged. This is the source's exploding-body example: increasing kinetic energy is compatible with momentum conservation.</p>"
    },
    {
      id: "collision-energy-fractions",
      title: "Energy transferred and energy dissipated in collisions",
      sources: [{ document: "quick-revision", page: 5 }],
      html: "<p>For a head-on elastic collision, let $m_1$ initially move at speed $u$ and $m_2$ initially be at rest. The fraction of the initial kinetic energy transferred to the target is $\\frac{K_{2f}}{K_i}=\\frac{4m_1m_2}{(m_1+m_2)^2}$. The same fraction is lost by the incident body's kinetic energy. It is largest, equal to one, when the masses are equal.</p><p><strong>Source correction:</strong> the heading 'fraction of energy lost: elastically' must not mean loss of the system's total kinetic energy. That total loss is zero in an elastic collision. The printed fraction describes transfer from the initially moving body to the initially stationary body under the conditions above.</p><p>For a completely inelastic collision with the same initial arrangement, the bodies stick and move together at $V=\\frac{m_1u}{m_1+m_2}$. Their final kinetic-energy fraction is $\\frac{K_f}{K_i}=\\frac{m_1}{m_1+m_2}$, so the fraction converted to other energy forms is $\\frac{K_i-K_f}{K_i}=\\frac{m_2}{m_1+m_2}$. This explains the mnemonic 'Rest (initially) / Total': numerator means initially stationary mass, denominator means total mass. It does not describe every partially inelastic collision or a target that was already moving.</p>"
    },
    {
      id: "pendulum-rod-potential",
      title: "Raising a pendulum bob or a uniform rod",
      sources: [{ document: "quick-revision", page: 5 }],
      html: "<p>For a simple pendulum of length $l$, deflected through $\\theta$ from its downward vertical equilibrium, the bob rises by $h=l(1-\\cos\\theta)$. Its potential-energy increase is $\\Delta U=mgl(1-\\cos\\theta)$. This geometric expression is exact; it does not require the small-angle approximation used for a simple-pendulum period.</p><p>For a uniform stick of length $l$ pivoted at its upper end and initially hanging vertically downward, the centre of mass is only $\\frac{l}{2}$ from the pivot. Rotation through the same angle raises it by $\\frac{l}{2}(1-\\cos\\theta)$, giving $\\Delta U=\\frac{mgl}{2}(1-\\cos\\theta)$. The source's factor of one-half is a centre-of-mass effect, not a different value of gravitational acceleration. A different pivot or nonuniform mass distribution requires its actual centre-of-mass distance.</p>"
    },
    {
      id: "projectile-components",
      title: "Projectile components and changes of velocity",
      sources: [{ document: "quick-revision", page: 5 }],
      html: "<p>For launch speed $u$ at angle $\\theta$ above the horizontal, neglect air resistance and take uniform downward gravity. The velocity components are $v_x=u\\cos\\theta$ and $v_y=u\\sin\\theta-gt$. Horizontal acceleration is zero and the full acceleration vector is constant downward. The positions relative to launch are $x=u\\cos\\theta\\,t$ and $y=u\\sin\\theta\\,t-\\frac12gt^2$.</p><p>At the highest point, $v_y=0$, but $v_x$ is unchanged. The velocity change from launch to the apex is downward with magnitude $u\\sin\\theta$; the identical horizontal components cancel in the subtraction. From launch to return to the launch height, the change is downward with magnitude $2u\\sin\\theta$. These are vector-velocity changes, not changes in speed.</p><p>For return to the same height, the time of flight is $T=\\frac{2u\\sin\\theta}{g}$, maximum height is $H=\\frac{u^2\\sin^2\\theta}{2g}$ and horizontal range is $R=\\frac{u^2\\sin2\\theta}{g}$. Changing the landing height changes the flight-time and range formulas.</p><p>The source's horizontal-versus-vertical comparison states that the horizontally thrown ball has greater speed but both arrive simultaneously. This holds for a horizontal launch and a simultaneous release from rest from the same height $h$, both with zero initial vertical speed. Their common fall time is $\\sqrt{\\frac{2h}{g}}$. The dropped body's impact speed is $\\sqrt{2gh}$; a horizontal launch at speed $u$ has impact speed $\\sqrt{u^2+2gh}$. A body thrown vertically with nonzero initial vertical velocity does not generally have that same fall time.</p>"
    },
    {
      id: "complementary-projectiles",
      title: "Complementary launch angles",
      sources: [{ document: "quick-revision", page: 5 }],
      html: "<p>Compare launches at the same speed $u$ at angles $\\theta$ and $90^\\circ-\\theta$, with the same launch and landing height, no drag, and the same $g$. Label the first launch 1 and the second 2. The source relationships, with the height-sum correction, are:</p><ul><li>Equal ranges: $R_1:R_2=1:1$, since $\\sin2\\theta=\\sin(180^\\circ-2\\theta)$.</li><li>Flight-time ratio: $\\frac{T_1}{T_2}=\\tan\\theta$.</li><li>Maximum-height ratio: $\\frac{H_1}{H_2}=\\tan^2\\theta$.</li><li>Common range from the two heights: $R=4\\sqrt{H_1H_2}$.</li><li>Product of flight times: $T_1T_2=\\frac{2R}{g}$.</li><li>Sum of maximum heights: $H_1+H_2=\\frac{u^2}{2g}$.</li></ul><p><strong>Source correction:</strong> the page prints $H_1+H_2=\\frac{u^2}{g}$, missing the factor 2 in the denominator. Adding $\\frac{u^2\\sin^2\\theta}{2g}$ and $\\frac{u^2\\cos^2\\theta}{2g}$ directly proves the corrected result. A check at two $45^\\circ$ launches also gives a sum of $\\frac{u^2}{2g}$.</p>"
    },
    {
      id: "wind-source-conditions",
      title: "Wind shorthand and trajectory conditions",
      sources: [{ document: "quick-revision", page: 5 }],
      html: "<p>The printed wind-case statements are 'Steady force: Straight line' and 'Constant speed: Parabola'. Neither specifies the initial velocity, which speed is constant, the force direction, or a drag law.</p><p>For a body released from rest under a constant horizontal force and gravity, both horizontal and vertical displacements are proportional to $t^2$. Their ratio is fixed, so the trajectory is a straight line in the direction of the resultant acceleration. With an initial velocity not parallel to that acceleration, constant resultant force instead produces a generally parabolic trajectory. Thus steady force alone does not guarantee a straight path.</p><p>A motion with constant horizontal velocity and constant downward acceleration is parabolic. This is not a claim that total projectile speed stays constant, nor that any constant wind speed produces the same trajectory. Real wind forces depend on relative velocity and the drag model. These conditional explanations preserve the legible source claims without supplying an unprinted wind setup as an assessed fact.</p>"
    },
    {
      id: "braking-comparisons",
      title: "Bus and car stopping comparisons",
      sources: [{ document: "quick-revision", page: 6 }],
      html: "<p>Under an equal constant retarding-force magnitude $F$, work-energy gives stopping distance $s=\\frac{K_i}{F}$ and impulse gives stopping time $t=\\frac{p_i}{F}$. These equations distinguish the two comparisons on the page.</p><ul><li>Same initial kinetic energy: stopping distances are equal. Because $p_i=\\sqrt{2mK_i}$, stopping time is $t=\\frac{\\sqrt{2mK_i}}{F}$, so $t\\propto\\sqrt m$. The heavier vehicle takes longer, despite starting more slowly.</li><li>Same initial momentum: stopping times are equal. Since $K_i=\\frac{p_i^2}{2m}$, $s=\\frac{p_i^2}{2mF}$. With subscripts c for car and b for bus, $\\frac{s_c}{s_b}=\\frac{m_b}{m_c}$ and $t_c=t_b$.</li></ul><p>Here the source's capital P means linear momentum, not power. Equal retarding force is not the same premise as equal friction coefficient: on a level road the simple sliding-friction force $\\mu mg$ increases with mass.</p>"
    },
    {
      id: "opposite-horizontal-launches",
      title: "Perpendicular velocities and displacement vectors",
      sources: [{ document: "quick-revision", page: 6 }],
      html: "<p>Two particles are launched simultaneously and horizontally from the same point in opposite directions, with positive speed magnitudes $u_1$ and $u_2$. Both experience the same downward acceleration $g$, and the results apply while both remain in flight.</p><p>Their velocities are $(u_1,-gt)$ and $(-u_2,-gt)$. The scalar product is $-u_1u_2+g^2t^2$. Setting it to zero gives the source's perpendicular-velocity time $t_v=\\frac{\\sqrt{u_1u_2}}{g}$.</p><p>Their displacement vectors from the common launch point are $(u_1t,-\\frac12gt^2)$ and $(-u_2t,-\\frac12gt^2)$. Their scalar product is $-u_1u_2t^2+\\frac14g^2t^4$. The nonzero-time solution is $t_r=\\frac{2\\sqrt{u_1u_2}}{g}$. At $t=0$ both displacement vectors are zero, so their directions are not defined. The second result concerns displacements from the launch point, not arbitrary position vectors from a different origin.</p>"
    },
    {
      id: "same-height-times",
      title: "Passing a height twice",
      sources: [{ document: "quick-revision", page: 6 }],
      html: "<p>If upward motion obeys $y=u_yt-\\frac12gt^2$ and a given height is reached at times $t_1$ and $t_2$, the quadratic's root sum is $t_1+t_2=\\frac{2u_y}{g}$. Therefore the time from launch to the highest point is $t_{\\max}=\\frac{t_1+t_2}{2}$. If the body eventually returns to its launch height, the total flight time is $T=t_1+t_2$.</p><p><strong>Source clarification:</strong> 'passes twice through same point' literally fits a vertical throw; for a projectile with nonzero horizontal velocity it means the same height at two different horizontal positions. The total-flight statement also assumes landing at the launch height, rather than on a lower or higher surface.</p>"
    },
    {
      id: "compressed-time-fragments",
      title: "Remaining equilibrium and time mnemonics",
      sources: [{ document: "quick-revision", page: 6 }],
      html: "<p>The standalone 'Equilibrium: Acceleration' line does not state a value or a system. Translational equilibrium of a particle in an inertial frame means zero acceleration, but the intended missing comparison cannot be recovered.</p><p>The printed expression $t=\\frac{t_1t_2}{t_1+t_2}$ is followed by 'Oscillator walks stand wala case'. This appears to mix an oscillator label with a walking/standing example. A valid conditional interpretation is an escalator of fixed length: if a person walking on stationary stairs takes $t_1$, and standing on the moving escalator takes $t_2$, then walking with the same relative speed on that escalator takes $t$, because the two transport speeds add. The page does not define the times or confirm that this is its intended setup.</p><p>The final mnemonic is $t^2=t_1^2+t_2^2$, 'Stopped middle ... again fall'. A consistent free-fall interpretation divides a height into two portions: each fall starts from rest, takes time $t_1$ or $t_2$, and the body is stopped between them. The uninterrupted fall time over the combined height satisfies that squared relation. The actual two-stage elapsed falling time is $t_1+t_2$, plus any waiting time, not $t$. The source does not label which time is uninterrupted or specify the intermediate stopping process.</p>"
    },
    {
      id: "circular-motion-lead-in",
      title: "Circular-motion introduction on the final source page",
      sources: [{ document: "quick-revision", page: 6 }],
      html: "<p>The lower half of this assigned page begins circular motion. For motion around a circle of radius $r$ at nonzero speed $v$, the inward radial acceleration is $a_r=\\frac{v^2}{r}$ and tangential acceleration is the rate of change of speed. Zero tangential acceleration is compatible with nonzero centripetal acceleration.</p><p>If a rope is severed, the instantaneous velocity is along the tangent. With no remaining force, the body subsequently follows that straight tangent; with gravity still acting, it begins a projectile trajectory tangent to the circle at release. Centripetal acceleration and the net radial force point toward the centre along a radius.</p><p><strong>Source correction:</strong> the line 'If velocity is zero, particle moves towards centre along radius' is not automatic. Inward motion from rest requires a remaining inward force and freedom to move radially. A body at rest has no velocity direction, and the circular centripetal term $\\frac{v^2}{r}$ is then zero.</p><p>In uniform circular motion with fixed radius and mass, speed, kinetic energy and angular speed are constant; angular velocity is constant for a fixed plane and rotation sense. Velocity, linear momentum, resultant centripetal force and acceleration have constant magnitudes but continuously change direction. The radial force does no work because it is perpendicular to the instantaneous velocity. Its torque about the circle's centre is zero because force and radius are collinear. This consolidates both printed no-work statements; torque need not be zero about every other origin.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 2, status: "partial", sectionIds: ["newton-laws", "rope-loads-apparent-weight", "jet-momentum-recoil", "unresolved-force-fragments", "inclined-plane-motion"], unresolved: ["The rope no-breaking shortcut gives up (beta+1) and down (1-beta), but does not define beta or the omitted dimensional quantity; the normalized-tension interpretation is conditional.", "The quick-step weight sequence lacks a specified body motion and weighing arrangement.", "Spring: Sum of force on either side has no spring diagram or force arrangement.", "Body freely falls: g cot(theta) and Remains at rest: g tan(theta) lack angle, support, and acceleration-direction definitions."] },
    { document: "quick-revision", page: 3, status: "partial", sectionIds: ["rope-loads-apparent-weight", "friction-model", "friction-directions-work", "friction-ratio-shortcuts", "minimum-pulling-forces", "atwood-and-balances"], unresolved: ["The time, velocity and distance friction shortcuts do not define n or the quantities held equal; explicit conditional definitions are supplied in the notes.", "Unpedalled bicycle: both wheels backward omits the retarding forces and torques, so its claimed friction directions cannot be assigned generally.", "Least force W sin(theta), least horizontal force W tan(theta), and wall force mg cot(theta) do not define theta or their arrangements.", "Equal arms: (w1+w2)/2 does not identify the readings or repeated-weighing procedure; the unequal-pan interpretation is conditional."] },
    { document: "quick-revision", page: 4, status: "partial", sectionIds: ["minimum-pulling-forces", "atwood-and-balances", "chains-and-rough-patches", "conservative-energy", "pumping-tank", "collision-conservation"], unresolved: ["Unequal arms: sqrt(w1 w2) does not define the readings or specify exchange of pans.", "The partial-roughness coefficient formula omits equal-length portions and endpoint-speed conditions.", "F_min = mg sin(theta)/cos(alpha-theta) does not define either angle or distinguish a smooth incline from an angled pull on rough horizontal ground.", "Pull hanging part: mgl/(2n^2) leaves m, l, n and the absence of friction undefined; its work interpretation is conditional.", "Half empty tank: 3mgh/8 omits tank shape, initial filling, outlet height and whether m is the full-tank mass.", "Work: P.E. attractive; on body increases (-ve), by body decreases (+ve) does not identify the agent or the quantity carrying the printed signs."] },
    { document: "quick-revision", page: 5, status: "partial", sectionIds: ["collision-conservation", "collision-energy-fractions", "pendulum-rod-potential", "projectile-components", "complementary-projectiles", "wind-source-conditions"], unresolved: ["The initial fragment A is huge (m1 much greater than m2), B rest gives no collision outcome or explicit geometry; the head-on elastic completion is conditional.", "The horizontal/vertical launch comparison omits initial vertical velocities; simultaneous arrival is justified only for the explicitly stated dropped-versus-horizontal case.", "Wind case: Steady force straight line; Constant speed parabola lacks initial velocity, force direction, the speed being held constant, and a drag model."] },
    { document: "quick-revision", page: 6, status: "partial", sectionIds: ["conservative-energy", "braking-comparisons", "opposite-horizontal-launches", "same-height-times", "compressed-time-fragments", "circular-motion-lead-in"], unresolved: ["Equilibrium: Acceleration is an incomplete standalone statement with no quantity or setup.", "t=t1*t2/(t1+t2), Oscillator walks stand wala case does not define the times or establish whether an escalator rather than an oscillator is intended.", "t^2=t1^2+t2^2, Stopped middle ... again fall does not define which time is uninterrupted or the intermediate stopping process."] }
  ],
  questions: [
    { id: "note-dynamics-001", text: "A glider is already moving east on a straight air track. Its resultant external force becomes zero. Which subsequent motion follows in an inertial frame?", options: [{ key: "a", text: "Its eastward speed steadily decreases." }, { key: "b", text: "Its eastward acceleration stays positive." }, { key: "c", text: "Its eastward velocity remains constant." }, { key: "d", text: "Its velocity immediately becomes zero." }], answer: "c", explanation: "Zero resultant force gives zero acceleration for a constant-mass glider. Its existing velocity therefore persists; equilibrium does not require that the glider was initially at rest.", sectionId: "newton-laws", source: { document: "quick-revision", page: 2 }, cognitive: "understanding" },
    { id: "note-dynamics-002", text: "A water jet of density $1000\\,\\mathrm{kg\\,m^{-3}}$, area $2.0\\times10^{-4}\\,\\mathrm{m^2}$ and speed $5.0\\,\\mathrm{m\\,s^{-1}}$ is completely reversed by a fixed vane without losing speed. What is the force magnitude on the vane?", options: [{ key: "a", text: "$10\\,\\mathrm N$" }, { key: "b", text: "$5.0\\,\\mathrm N$" }, { key: "c", text: "$2.0\\,\\mathrm N$" }, { key: "d", text: "$20\\,\\mathrm N$" }], answer: "a", explanation: "The mass-flow rate is $\\rho Av=1.0\\,\\mathrm{kg\\,s^{-1}}$. Reversal changes the axial velocity by $10\\,\\mathrm{m\\,s^{-1}}$, so the force is $10\\,\\mathrm N$. Stopping the axial flow without reversal would give only $5\\,\\mathrm N$.", sectionId: "jet-momentum-recoil", source: { document: "quick-revision", page: 2 }, cognitive: "application" },
    { id: "note-dynamics-003", text: "Two initially stationary launch carts eject identical test masses with the same final momentum. One cart has half the mass of the other. How does the lighter cart's recoil kinetic energy compare?", options: [{ key: "a", text: "It is one-quarter as large." }, { key: "b", text: "It is unchanged in magnitude." }, { key: "c", text: "It is one-half as large." }, { key: "d", text: "It is twice as large." }], answer: "d", explanation: "Negligible external impulse gives each cart the same recoil momentum magnitude as its ejected test mass. At fixed momentum, $K=\\frac{p^2}{2M}$, so halving the cart mass doubles its recoil kinetic energy.", sectionId: "jet-momentum-recoil", source: { document: "quick-revision", page: 2 }, cognitive: "application" },
    { id: "note-dynamics-004", text: "A $70\\,\\mathrm{kg}$ climber accelerates upward at $2.0\\,\\mathrm{m\\,s^{-2}}$, supported by one vertical rope. Taking $g=10\\,\\mathrm{m\\,s^{-2}}$, what tension must the rope sustain?", options: [{ key: "a", text: "$560\\,\\mathrm N$" }, { key: "b", text: "$840\\,\\mathrm N$" }, { key: "c", text: "$700\\,\\mathrm N$" }, { key: "d", text: "$140\\,\\mathrm N$" }], answer: "b", explanation: "For upward-positive motion, $T-mg=ma$. Therefore $T=70(10+2)=840\\,\\mathrm N$. Subtracting the acceleration term would describe downward acceleration, not the upward acceleration specified.", sectionId: "rope-loads-apparent-weight", source: { document: "quick-revision", page: 2 }, cognitive: "application" },
    { id: "note-dynamics-005", text: "A block starts from rest and descends a smooth slope of length $5.0\\,\\mathrm m$ with $\\sin\\theta=0.40$. For $g=10\\,\\mathrm{m\\,s^{-2}}$, how long does the descent take?", options: [{ key: "a", text: "$1.00\\,\\mathrm s$" }, { key: "b", text: "$1.58\\,\\mathrm s$" }, { key: "c", text: "$2.50\\,\\mathrm s$" }, { key: "d", text: "$5.00\\,\\mathrm s$" }], answer: "b", explanation: "The slope acceleration is $a=g\\sin\\theta=4.0\\,\\mathrm{m\\,s^{-2}}$. From $5=\\frac12(4)t^2$, the time is $\\sqrt{2.5}=1.58\\,\\mathrm s$. The vertical height is not the distance travelled along the slope.", sectionId: "inclined-plane-motion", source: { document: "quick-revision", page: 2 }, cognitive: "application" },
    { id: "note-dynamics-006", text: "A block is sliding up a rough incline with $\\sin\\theta=0.60$, $\\cos\\theta=0.80$ and $\\mu_k=0.20$. For $g=10\\,\\mathrm{m\\,s^{-2}}$, what is its acceleration?", options: [{ key: "a", text: "$4.4\\,\\mathrm{m\\,s^{-2}}$ down the slope" }, { key: "b", text: "$4.4\\,\\mathrm{m\\,s^{-2}}$ up the slope" }, { key: "c", text: "$7.6\\,\\mathrm{m\\,s^{-2}}$ down the slope" }, { key: "d", text: "$7.6\\,\\mathrm{m\\,s^{-2}}$ up the slope" }], answer: "c", explanation: "While the block slides upward, both the downhill weight component and friction point down the slope. Their acceleration contributions add: $a=10(0.60+0.20\\times0.80)=7.6\\,\\mathrm{m\\,s^{-2}}$ downhill.", sectionId: "inclined-plane-motion", source: { document: "quick-revision", page: 2 }, cognitive: "application" },
    { id: "note-dynamics-007", text: "A stationary crate has a limiting static friction of $20\\,\\mathrm N$. A horizontal pull of $12\\,\\mathrm N$ is applied without moving it. What is the actual friction magnitude?", options: [{ key: "a", text: "$12\\,\\mathrm N$" }, { key: "b", text: "$20\\,\\mathrm N$" }, { key: "c", text: "$8\\,\\mathrm N$" }, { key: "d", text: "$32\\,\\mathrm N$" }], answer: "a", explanation: "Static friction supplies the force needed for equilibrium, provided that force is below its limit. Here it balances the $12\\,\\mathrm N$ pull. The $20\\,\\mathrm N$ value is the maximum available friction, not the compulsory friction.", sectionId: "friction-model", source: { document: "quick-revision", page: 3 }, cognitive: "understanding" },
    { id: "note-dynamics-008", text: "A rough incline takes twice as long as a smooth incline of identical length and angle for a block to descend from rest. Sliding continues throughout. Which kinetic coefficient follows?", options: [{ key: "a", text: "$\\frac14\\tan\\theta$" }, { key: "b", text: "$\\frac12\\tan\\theta$" }, { key: "c", text: "$\\frac23\\tan\\theta$" }, { key: "d", text: "$\\frac34\\tan\\theta$" }], answer: "d", explanation: "For equal distances from rest, acceleration varies inversely with the square of the time. Thus $a_r=\\frac{a_0}{4}$. Using $a_r=g(\\sin\\theta-\\mu_k\\cos\\theta)$ and $a_0=g\\sin\\theta$ gives $\\mu_k=\\frac34\\tan\\theta$.", sectionId: "friction-ratio-shortcuts", source: { document: "quick-revision", page: 3 }, cognitive: "application" },
    { id: "note-dynamics-009", text: "An ideal rear-driven bicycle accelerates forward on level ground without slipping. Neglect resistance and braking. In which directions does ground friction act on its rear and passive front wheels?", options: [{ key: "a", text: "Rear backward; front backward" }, { key: "b", text: "Rear backward; front forward" }, { key: "c", text: "Rear forward; front backward" }, { key: "d", text: "Rear forward; front forward" }], answer: "c", explanation: "Driving torque makes the rear contact tend to slip backward, so its friction is forward. The passive front wheel needs a rolling angular acceleration; backward friction supplies that torque. These directions depend on the stated driving conditions.", sectionId: "friction-directions-work", source: { document: "quick-revision", page: 3 }, cognitive: "understanding" },
    { id: "note-dynamics-010", text: "Why can an upward-angled pull move a crate more easily than a downward-angled push of the same angle on rough horizontal ground?", options: [{ key: "a", text: "The pull increases the normal reaction." }, { key: "b", text: "The pull reduces the normal reaction." }, { key: "c", text: "The pull changes the crate's true weight." }, { key: "d", text: "The pull removes the surface coefficient." }], answer: "b", explanation: "An upward force component supports part of the weight, reducing $N$ and hence the friction limit $\\mu_sN$. A downward push adds to $N$. The gravitational weight and the coefficient for the contact surfaces do not change merely because the force is tilted.", sectionId: "minimum-pulling-forces", source: { document: "quick-revision", page: 3 }, cognitive: "understanding" },
    { id: "note-dynamics-011", text: "A horizontal force holds a $2.0\\,\\mathrm{kg}$ block against a vertical wall with $\\mu_s=0.40$. Take $g=10\\,\\mathrm{m\\,s^{-2}}$. What is the minimum force preventing downward slip?", options: [{ key: "a", text: "$8\\,\\mathrm N$" }, { key: "b", text: "$20\\,\\mathrm N$" }, { key: "c", text: "$40\\,\\mathrm N$" }, { key: "d", text: "$50\\,\\mathrm N$" }], answer: "d", explanation: "The applied horizontal force is the wall's normal reaction. At the limiting condition, $\\mu_sF=mg$, so $F=\\frac{2\\times10}{0.40}=50\\,\\mathrm N$. Friction then supplies the required $20\\,\\mathrm N$ upward support.", sectionId: "minimum-pulling-forces", source: { document: "quick-revision", page: 3 }, cognitive: "application" },
    { id: "note-dynamics-012", text: "An ideal Atwood machine has masses $6.0\\,\\mathrm{kg}$ and $4.0\\,\\mathrm{kg}$. For $g=10\\,\\mathrm{m\\,s^{-2}}$, what is the string tension?", options: [{ key: "a", text: "$48\\,\\mathrm N$" }, { key: "b", text: "$40\\,\\mathrm N$" }, { key: "c", text: "$60\\,\\mathrm N$" }, { key: "d", text: "$96\\,\\mathrm N$" }], answer: "a", explanation: "The acceleration is $a=\\frac{6-4}{6+4}10=2\\,\\mathrm{m\\,s^{-2}}$. For the lighter rising mass, $T=4(10+2)=48\\,\\mathrm N$. The $96\\,\\mathrm N$ choice is the combined downward string load on a light pulley with two vertical segments.", sectionId: "atwood-and-balances", source: { document: "quick-revision", page: 3 }, cognitive: "application" },
    { id: "note-dynamics-013", text: "An ideal rigid wheel rolls without slipping on stationary rigid ground. Why is the instantaneous power of its contact friction zero?", options: [{ key: "a", text: "The contact point has zero instantaneous velocity." }, { key: "b", text: "The wheel's centre has zero instantaneous velocity." }, { key: "c", text: "Static friction must have zero force magnitude." }, { key: "d", text: "The wheel cannot have any angular acceleration." }], answer: "a", explanation: "Power supplied by a contact force is its scalar product with the contact-point velocity. In pure rolling on stationary ground that point is instantaneously at rest. The force itself can be nonzero, and the centre can be moving and accelerating.", sectionId: "friction-directions-work", source: { document: "quick-revision", page: 3 }, cognitive: "understanding" },
    { id: "note-dynamics-014", text: "A uniform chain has total mass $3.0\\,\\mathrm{kg}$ and length $2.0\\,\\mathrm m$. One-fifth hangs below a smooth table. What work retrieves the hanging part slowly onto the table, with $g=10\\,\\mathrm{m\\,s^{-2}}$?", options: [{ key: "a", text: "$0.60\\,\\mathrm J$" }, { key: "b", text: "$2.40\\,\\mathrm J$" }, { key: "c", text: "$6.00\\,\\mathrm J$" }, { key: "d", text: "$1.20\\,\\mathrm J$" }], answer: "d", explanation: "The hanging mass is $0.60\\,\\mathrm{kg}$ and its centre of mass lies $0.20\\,\\mathrm m$ below the top. Raising it requires $0.60\\times10\\times0.20=1.20\\,\\mathrm J$. Using the entire chain mass as the lifted mass would overcount the work.", sectionId: "chains-and-rough-patches", source: { document: "quick-revision", page: 4 }, cognitive: "application" },
    { id: "note-dynamics-015", text: "A uniform chain rests partly on a rough horizontal table and partly hangs over a frictionless edge. With $\\mu_s=0.25$, what maximum fraction of its total length can hang in limiting equilibrium?", options: [{ key: "a", text: "$\\frac14$" }, { key: "b", text: "$\\frac15$" }, { key: "c", text: "$\\frac34$" }, { key: "d", text: "$\\frac45$" }], answer: "b", explanation: "At impending slipping, hanging weight equals maximum friction on the supported part. Thus $x=0.25(L-x)$, giving $\\frac{x}{L}=\\frac{0.25}{1.25}=\\frac15$. The friction load decreases as more chain hangs over the edge.", sectionId: "chains-and-rough-patches", source: { document: "quick-revision", page: 4 }, cognitive: "application" },
    { id: "note-dynamics-016", text: "A particle returns to its starting position along a closed route in a time-independent gravitational field. What is the work done by gravity over the complete route?", options: [{ key: "a", text: "Positive for every possible route" }, { key: "b", text: "Negative for every possible route" }, { key: "c", text: "Zero regardless of the route taken" }, { key: "d", text: "Proportional to the route length" }], answer: "c", explanation: "Gravity is conservative, so its work is the negative change of gravitational potential energy. The initial and final positions are identical, making that change zero even if the particle follows a long or complicated route.", sectionId: "conservative-energy", source: { document: "quick-revision", page: 4 }, cognitive: "recall" },
    { id: "note-dynamics-017", text: "A small air bubble rises through water. Which interpretation makes the usual potential-energy decrease statement physically consistent?", options: [{ key: "a", text: "The bubble's own gravitational energy decreases." }, { key: "b", text: "The bubble-water system's gravitational energy decreases." }, { key: "c", text: "The rising bubble's gravitational mass increases." }, { key: "d", text: "The displaced water's gravitational energy increases." }], answer: "b", explanation: "The rising bubble displaces denser water downward, so the combined system can lower its gravitational potential energy. The bubble itself rises and can gain gravitational potential energy. The source statement must refer to the combined arrangement.", sectionId: "conservative-energy", source: { document: "quick-revision", page: 4 }, cognitive: "understanding" },
    { id: "note-dynamics-018", text: "A uniform-cross-section tank is full of $80\\,\\mathrm{kg}$ of water to depth $2.0\\,\\mathrm m$. How much ideal work removes only the upper half through the top edge? Take $g=10\\,\\mathrm{m\\,s^{-2}}$.", options: [{ key: "a", text: "$200\\,\\mathrm J$" }, { key: "b", text: "$400\\,\\mathrm J$" }, { key: "c", text: "$600\\,\\mathrm J$" }, { key: "d", text: "$800\\,\\mathrm J$" }], answer: "a", explanation: "The removed upper half has mass $40\\,\\mathrm{kg}$ and its average lift is $0.50\\,\\mathrm m$. Therefore the work is $40\\times10\\times0.50=200\\,\\mathrm J$. The lower half remaining afterward would require $600\\,\\mathrm J$, explaining the different half-tank formulas.", sectionId: "pumping-tank", source: { document: "quick-revision", page: 4 }, cognitive: "application" },
    { id: "note-dynamics-019", text: "Two equal-mass carts collide head-on elastically. Their initial signed velocities are $+5$ and $-1\\,\\mathrm{m\\,s^{-1}}$. What are their respective final velocities?", options: [{ key: "a", text: "$+2$ and $+2\\,\\mathrm{m\\,s^{-1}}$" }, { key: "b", text: "$-5$ and $+1\\,\\mathrm{m\\,s^{-1}}$" }, { key: "c", text: "$-1$ and $+5\\,\\mathrm{m\\,s^{-1}}$" }, { key: "d", text: "$+1$ and $+3\\,\\mathrm{m\\,s^{-1}}$" }], answer: "c", explanation: "Equal masses exchange their signed velocities in a one-dimensional elastic collision. The final pair is therefore $-1$ and $+5$. Both momentum and kinetic energy are preserved; a common velocity would describe a sticking collision instead.", sectionId: "collision-conservation", source: { document: "quick-revision", page: 4 }, cognitive: "application" },
    { id: "note-dynamics-020", text: "A $1.0\\,\\mathrm{kg}$ cart strikes an initially stationary $3.0\\,\\mathrm{kg}$ cart head-on elastically. What fraction of the incident kinetic energy goes to the target?", options: [{ key: "a", text: "$\\frac14$" }, { key: "b", text: "$\\frac12$" }, { key: "c", text: "$\\frac{9}{16}$" }, { key: "d", text: "$\\frac34$" }], answer: "d", explanation: "The transferred fraction is $\\frac{4m_1m_2}{(m_1+m_2)^2}=\\frac{4\\times1\\times3}{16}=\\frac34$. This is energy transferred to the target, not energy dissipated: the total kinetic energy of both carts is unchanged.", sectionId: "collision-energy-fractions", source: { document: "quick-revision", page: 5 }, cognitive: "application" },
    { id: "note-dynamics-021", text: "A moving $2.0\\,\\mathrm{kg}$ cart sticks to a stationary $4.0\\,\\mathrm{kg}$ cart. External impulse is negligible. What fraction of the initial kinetic energy is converted to other forms?", options: [{ key: "a", text: "$\\frac16$" }, { key: "b", text: "$\\frac13$" }, { key: "c", text: "$\\frac12$" }, { key: "d", text: "$\\frac23$" }], answer: "d", explanation: "Momentum conservation gives a common final speed equal to one-third of the incident speed. The final kinetic-energy fraction is $\\frac{2}{2+4}=\\frac13$, so the converted fraction is $1-\\frac13=\\frac23$.", sectionId: "collision-energy-fractions", source: { document: "quick-revision", page: 5 }, cognitive: "application" },
    { id: "note-dynamics-022", text: "A uniform rod of mass $2.0\\,\\mathrm{kg}$ and length $1.2\\,\\mathrm m$ hangs from one end. It is raised to $60^\\circ$ from the downward vertical. What is its potential-energy increase for $g=10\\,\\mathrm{m\\,s^{-2}}$?", options: [{ key: "a", text: "$3.0\\,\\mathrm J$" }, { key: "b", text: "$6.0\\,\\mathrm J$" }, { key: "c", text: "$12\\,\\mathrm J$" }, { key: "d", text: "$24\\,\\mathrm J$" }], answer: "b", explanation: "The centre of mass is $0.60\\,\\mathrm m$ from the pivot. Its rise is $0.60(1-\\cos60^\\circ)=0.30\\,\\mathrm m$, giving $\\Delta U=2\\times10\\times0.30=6.0\\,\\mathrm J$. Treating all the mass as an end bob would double the result.", sectionId: "pendulum-rod-potential", source: { document: "quick-revision", page: 5 }, cognitive: "application" },
    { id: "note-dynamics-023", text: "A projectile is launched at $20\\,\\mathrm{m\\,s^{-1}}$ and $30^\\circ$ above horizontal. Neglecting drag, what is its velocity change from launch to the highest point?", options: [{ key: "a", text: "$10\\,\\mathrm{m\\,s^{-1}}$ vertically downward" }, { key: "b", text: "$10\\,\\mathrm{m\\,s^{-1}}$ vertically upward" }, { key: "c", text: "$20\\,\\mathrm{m\\,s^{-1}}$ vertically downward" }, { key: "d", text: "$20\\,\\mathrm{m\\,s^{-1}}$ horizontally forward" }], answer: "a", explanation: "The horizontal components at launch and at the apex are equal and cancel in the vector subtraction. The vertical component changes from $20\\sin30^\\circ=10$ to zero, giving a change of $-10\\,\\mathrm{m\\,s^{-1}}$ vertically.", sectionId: "projectile-components", source: { document: "quick-revision", page: 5 }, cognitive: "application" },
    { id: "note-dynamics-024", text: "Two projectiles are launched at $20\\,\\mathrm{m\\,s^{-1}}$ at complementary angles and return to the launch level. With $g=10\\,\\mathrm{m\\,s^{-2}}$, what is the sum of their maximum heights?", options: [{ key: "a", text: "$10\\,\\mathrm m$" }, { key: "b", text: "$40\\,\\mathrm m$" }, { key: "c", text: "$20\\,\\mathrm m$" }, { key: "d", text: "$80\\,\\mathrm m$" }], answer: "c", explanation: "The two squared vertical-speed factors are $\\sin^2\\theta$ and $\\cos^2\\theta$, whose sum is one. Therefore $H_1+H_2=\\frac{20^2}{2\\times10}=20\\,\\mathrm m$. The uncorrected source expression would incorrectly give twice this value.", sectionId: "complementary-projectiles", source: { document: "quick-revision", page: 5 }, cognitive: "application" },
    { id: "note-dynamics-025", text: "At equal launch speeds, how does the maximum height for a $30^\\circ$ projectile compare with that for a $60^\\circ$ projectile in the same gravitational field?", options: [{ key: "a", text: "The height ratio is $1:3$." }, { key: "b", text: "The height ratio is $1:1$." }, { key: "c", text: "The height ratio is $3:1$." }, { key: "d", text: "The height ratio is $1:2$." }], answer: "a", explanation: "Maximum height is proportional to the square of the initial vertical component. The ratio is $\\frac{\\sin^230^\\circ}{\\sin^260^\\circ}=\\frac{\\frac{1}{4}}{\\frac{3}{4}}=\\frac13$. Equal ranges for these complementary angles do not imply equal heights.", sectionId: "complementary-projectiles", source: { document: "quick-revision", page: 5 }, cognitive: "application" },
    { id: "note-dynamics-026", text: "One ball is launched horizontally at $15\\,\\mathrm{m\\,s^{-1}}$ from a $20\\,\\mathrm m$ platform while another is dropped from rest. With no drag and $g=10\\,\\mathrm{m\\,s^{-2}}$, what are their respective impact speeds?", options: [{ key: "a", text: "$15$ and $20\\,\\mathrm{m\\,s^{-1}}$" }, { key: "b", text: "$35$ and $20\\,\\mathrm{m\\,s^{-1}}$" }, { key: "c", text: "$25$ and $20\\,\\mathrm{m\\,s^{-1}}$" }, { key: "d", text: "$25$ and $15\\,\\mathrm{m\\,s^{-1}}$" }], answer: "c", explanation: "Both acquire a downward speed $\\sqrt{2gh}=20\\,\\mathrm{m\\,s^{-1}}$ and fall for $2\\,\\mathrm s$. The launched ball retains its horizontal speed of 15, so its total speed is $\\sqrt{15^2+20^2}=25\\,\\mathrm{m\\,s^{-1}}$; the dropped ball has speed 20.", sectionId: "projectile-components", source: { document: "quick-revision", page: 5 }, cognitive: "application" },
    { id: "note-dynamics-027", text: "Two vehicles have equal initial kinetic energy and experience the same constant retarding force. If one has nine times the other's mass, how does its stopping time compare?", options: [{ key: "a", text: "It is one-third as long." }, { key: "b", text: "It is the same duration." }, { key: "c", text: "It is nine times as long." }, { key: "d", text: "It is three times as long." }], answer: "d", explanation: "At fixed kinetic energy, momentum is $p=\\sqrt{2mK}$. The stopping time under fixed force is $t=\\frac{p}{F}$, so it scales as $\\sqrt m$. Increasing mass by a factor of nine increases stopping time by three, while stopping distance stays the same.", sectionId: "braking-comparisons", source: { document: "quick-revision", page: 6 }, cognitive: "application" },
    { id: "note-dynamics-028", text: "Two particles are launched horizontally in opposite directions from the same high point at speeds $9$ and $16\\,\\mathrm{m\\,s^{-1}}$. With $g=12\\,\\mathrm{m\\,s^{-2}}$, when are their velocities perpendicular?", options: [{ key: "a", text: "$0.50\\,\\mathrm s$" }, { key: "b", text: "$1.00\\,\\mathrm s$" }, { key: "c", text: "$2.00\\,\\mathrm s$" }, { key: "d", text: "$4.00\\,\\mathrm s$" }], answer: "b", explanation: "The velocity scalar product is $-9\\times16+(12t)^2$. Perpendicularity requires this to vanish, so $t=\\frac{\\sqrt{144}}{12}=1.00\\,\\mathrm s$. The displacement vectors become perpendicular at twice this time, provided both particles are still airborne.", sectionId: "opposite-horizontal-launches", source: { document: "quick-revision", page: 6 }, cognitive: "application" },
    { id: "note-dynamics-029", text: "A vertically thrown ball passes a particular height at $2.0$ and $6.0\\,\\mathrm s$ after launch. When does it reach its apex, and when does it return to its launch height?", options: [{ key: "a", text: "Apex at $4.0\\,\\mathrm s$; return at $8.0\\,\\mathrm s$" }, { key: "b", text: "Apex at $2.0\\,\\mathrm s$; return at $6.0\\,\\mathrm s$" }, { key: "c", text: "Apex at $3.0\\,\\mathrm s$; return at $6.0\\,\\mathrm s$" }, { key: "d", text: "Apex at $6.0\\,\\mathrm s$; return at $12\\,\\mathrm s$" }], answer: "a", explanation: "The two crossings of the same height are symmetric about the highest point. The apex time is $\\frac{2+6}{2}=4.0\\,\\mathrm s$. Under constant gravity without drag, return to the initial height takes twice that time, or $8.0\\,\\mathrm s$.", sectionId: "same-height-times", source: { document: "quick-revision", page: 6 }, cognitive: "application" },
    { id: "note-dynamics-030", text: "Which description of a fixed-mass particle in uniform circular motion is correct?", options: [{ key: "a", text: "Momentum is constant and the resultant force is zero." }, { key: "b", text: "Kinetic energy is constant and velocity changes direction." }, { key: "c", text: "Kinetic energy increases and velocity stays constant." }, { key: "d", text: "Acceleration is zero and momentum changes magnitude." }], answer: "b", explanation: "Constant speed keeps $K=\\frac12mv^2$ unchanged, but the direction of velocity and momentum continuously turns. A nonzero inward acceleration and force are required. The force changes direction without doing work on the particle.", sectionId: "circular-motion-lead-in", source: { document: "quick-revision", page: 6 }, cognitive: "recall" }
  ]
};