window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["earthworm"] = {
  id: "earthworm",
  subject: "Zoology",
  title: "Earthworm",
  sections: [
    {
      id: "earthworm-model-habitat",
      title: "The model species, classification and habitat",
      sources: [{ document: "biology", page: 6 }],
      html: "<p>These segment numbers describe the traditional Pheretima posthuma teaching model, now generally named Metaphire posthuma. They are not universal for Lumbricus, all earthworms, or all annelids. The source classification proceeds through Animalia, Annelida, Oligochaeta, Pheretima and posthuma.</p><ul><li>Animalia: a multicellular animal with specialized tissues and organ systems.</li><li>Annelida: true metameric segmentation, with repetition of body regions externally and internally.</li><li>Oligochaeta in the traditional classification: no distinctly differentiated head and locomotory setae; modern accounts place earthworms among clitellate annelids.</li><li>The source associates Pheretima with a clitellum, one female genital opening and paired male openings. In the posthuma model, the single female opening is on segment 14 and male openings on segment 18.</li><li>The animal is triploblastic, bilaterally symmetrical, coelomate and organized as a tube within a tube: the digestive tube lies within the body-wall tube.</li><li>The body is elongated and cylindrical, with a tapering anterior and a relatively blunt posterior end.</li><li>Earthworms inhabit moist soil, maintaining the wet surface required for cutaneous respiration. Severe drying impairs gas exchange and can cause asphyxia.</li><li>Nocturnal means active chiefly at night; fossorial means adapted to burrowing. The source lists positive geotaxis and negative phototaxis as tendencies, not exceptionless responses under every environmental condition.</li><li>The brownish dorsal pigmentation is associated with porphyrin in the body wall, especially the circular muscle region. <strong>Source correction:</strong> the claim that this is simply produced from leaf chlorophyll because worms eat leaves is not established by the source and must not be treated as a demonstrated biosynthetic pathway.</li></ul>"
    },
    {
      id: "earthworm-segments-clitellum",
      title: "Segments, septa, annuli and the clitellum",
      sources: [{ document: "biology", page: 6 }, { document: "biology", page: 12 }],
      html: "<p>The source gives approximately 100-120 segments. The preclitellar region is segments 1-13, the clitellar region 14-16, and the postclitellar region 17 onward. These are model ranges, not a fixed segment count for every individual.</p><ul><li>Metameres are body segments. External grooves delimit annuli; internal partitions are septa, singular septum.</li><li>The notes list septa absent in 1, 2, 3, 4 and 9/10. This mixes segment labels and intersegmental notation, so the precise intended anterior septal boundaries cannot be reconstructed safely. That shorthand is retained, but no scored item depends on it.</li><li>External segmental grooves are obscured at the clitellum, segments 14, 15 and 16. This does not mean those segments cease to exist internally.</li><li>The clitellum or cingulum is a pinkish, thickened, highly glandular collar involved in reproduction and cocoon formation.</li><li>The source calls the adult earthworm clitellum permanent and the leech clitellum temporary, with leech segments 9-11 as its comparison. Those leech positions refer to the customary leech model, not every leech species.</li><li>Forest of nephridia is the mnemonic for the particularly numerous integumentary nephridia in the clitellar region.</li><li>Setae are absent from the first segment, clitellar segments 14-16 and terminal region in this model. The recap also lists ganglia absent from the first two segments, with the cerebral ganglia beginning in segment 3.</li><li>The prostomium is the anterior lobe over the mouth and assists in probing and burrowing. It is not a separate numbered true segment. The peristomium is the first segment surrounding the crescentic mouth; the terminal anal region is conventionally called the pygidium.</li></ul>"
    },
    {
      id: "earthworm-setae-locomotion",
      title: "Setae, anchorage and muscular movement",
      sources: [{ document: "biology", page: 6 }, { document: "biology", page: 7 }],
      html: "<p>Setae are S-shaped, chitinous bristles that grip the substrate during movement. The setal sketch labels a nodule on the bristle, formative cells and the setal sac. Protractor muscles extend a seta and retractor muscles withdraw it. In Pheretima, numerous setae are arranged in a ring around a typical segment: the perichaetine arrangement.</p><p>The source gives 8-100 setae per segment as a broad earthworm comparison. Eight is characteristic of some other earthworm arrangements; it is not the defining number of the perichaetine model. The notes say setae cannot be dissolved in 40% KOH because they are chitinous. This is a traditional preparation observation, not unlimited chemical resistance: effects of strong alkali depend on temperature and exposure, and the source supplies neither.</p><table><thead><tr><th>Locomotory structure</th><th>Source comparison</th></tr></thead><tbody><tr><td>Earthworm</td><td>Setae provide purchase while body-wall muscles act against the coelomic hydrostatic skeleton.</td></tr><tr><td>Leech</td><td>Suckers anchor the body; looping is characteristic of crawling by alternating sucker attachment.</td></tr><tr><td>Nereis</td><td>Setae are associated with parapodia; parapodial movement aids locomotion and the setae provide purchase.</td></tr></tbody></table><table><thead><tr><th>Outer circular muscles</th><th>Inner longitudinal muscles</th></tr></thead><tbody><tr><td>Encircle the body; the source associates porphyrin pigmentation with this layer.</td><td>Run along the body and are described as nonpigmented in the comparison.</td></tr><tr><td>Contraction narrows and lengthens a segment.</td><td>Contraction shortens and widens a segment.</td></tr></tbody></table><p><strong>Source correction:</strong> earthworm progression is chiefly peristaltic alternation of muscular contraction with setal anchorage, not the leech's sucker-based looping motion. Seta protractors and retractors control the bristles; circular and longitudinal body-wall muscles provide the principal body deformation. Longitudinal contraction does mechanical work rather than literally producing energy for the next stroke.</p>"
    },
    {
      id: "earthworm-external-openings",
      title: "Every external pore and reproductive landmark",
      sources: [{ document: "biology", page: 6 }, { document: "biology", page: 11 }],
      html: "<table><thead><tr><th>Structure</th><th>Position and function in the source model</th></tr></thead><tbody><tr><td>Mouth</td><td>In the first, peristomial segment, beneath the prostomium; admits food.</td></tr><tr><td>Anus</td><td>At the terminal pygidial region; expels castings.</td></tr><tr><td>Spermathecal pores</td><td>Four pairs, ventrolaterally in grooves 5/6, 6/7, 7/8 and 8/9. They lead to spermathecae in segments 6, 7, 8 and 9 and receive a partner's sperm.</td></tr><tr><td>Female genital pore</td><td>One, midventral on segment 14; releases ova.</td></tr><tr><td>Male genital pores</td><td>One pair, ventrolateral on segment 18; discharge sperm with prostatic secretion.</td></tr><tr><td>Genital papillae</td><td>Two pairs, ventrolateral on segments 17 and 19; assist attachment during copulation.</td></tr><tr><td>Nephridiopores</td><td>External openings of integumentary nephridia. Page 6 appears to give 7th to second-last segment; this conflicts with the printed nephridial range and remains ungraded.</td></tr><tr><td>Dorsal pores</td><td>Intersegmental openings along the middorsal line, releasing coelomic fluid that helps wet the surface and may be discharged on irritation.</td></tr></tbody></table><p><strong>Source correction:</strong> the dorsal-pore phrase on each segment is too broad; these pores are intersegmental and are not present uniformly from the very first segment. The source supplies no reliable first-pore boundary here, so no exact starting groove is invented. Spermathecal pores receive sperm at mating and release stored sperm into the passing cocoon later; they are not the sperm-producing organs or the male pores.</p>"
    },
    {
      id: "earthworm-body-wall",
      title: "Body-wall layers and all epithelial cell types",
      sources: [{ document: "biology", page: 7 }],
      html: "<p>From outside inward, the body-wall sketch labels cuticle, epidermis, circular muscle and longitudinal muscle. The transverse-section drawing additionally identifies parietal peritoneum, coelom and visceral peritoneum around the gut. The parietal layer lines the inside of the body wall, whereas the visceral layer covers the alimentary canal.</p><ul><li><strong>Cuticle:</strong> outermost, noncellular and nonchitinous. The source calls it albuminoid and double-layered and says it is secreted by epidermal supporting cells. Proteinaceous or collagenous is more precise than treating it as a layer of pure albumin.</li><li><strong>Epidermis:</strong> a single layer of glandular columnar epithelium.</li><li><strong>Supporting cells:</strong> the majority of the epithelium; tall, columnar and uninucleate.</li><li><strong>Glandular or mucous cells:</strong> numerous cells secreting mucus, maintaining a moist surface for cutaneous respiration.</li><li><strong>Albuminous cells:</strong> provide nutritive secretion associated with cocoon formation. The source describes their distribution in the first 16 segments; this is a model-specific entry rather than a universal annelid count.</li><li><strong>Sensory or receptor cells:</strong> lie among supporting cells; touch receptors are called thigmoreceptors.</li><li><strong>Basal cells:</strong> lie near the bases of supporting and glandular cells and replace worn-out cells.</li></ul><p>The comparative muscle table puts outer longitudinal and inner circular layers in the usual human/frog alimentary-canal wall, but outer circular and inner longitudinal layers in the earthworm body wall. These are different structures, not a contradiction: an intestine's muscle sequence must not be copied onto the earthworm's body wall.</p>"
    },
    {
      id: "earthworm-coelom",
      title: "Coelomic fluid, corpuscles and the hydrostatic skeleton",
      sources: [{ document: "biology", page: 7 }],
      html: "<p>The true coelom is a fluid-filled space between the body wall and alimentary canal. The source describes it as a schizocoel formed by splitting of mesoderm. Its fluid and compartmentalization support locomotion and burrowing as a hydrostatic skeleton.</p><p>The fluid is described as milky and alkaline, containing water, salts and proteins. The parietal lining contributes to its formation. Fluid can pass through dorsal pores and help maintain surface moisture. Discharge of coelomic fluid is not the same as urine passing through a nephridiopore.</p><table><thead><tr><th>Cell or source label</th><th>Meaning and listed functions</th></tr></thead><tbody><tr><td>Amoebocytes, granulocytes or phagocytes</td><td>Numerous mobile defensive cells; phagocytosis removes foreign material and debris. These historical labels overlap rather than define three perfectly separate universal cell types.</td></tr><tr><td>Mucocytes</td><td>Described as modified amoebocytes, elongated or fan-like and associated with mucus.</td></tr><tr><td>Leucocytes</td><td>The page associates them with circulation of digested food. Coelomic cells can participate in transport, but leucocyte terminology mainly denotes defensive cells and is not a replacement for the vascular nutrient-transport system.</td></tr><tr><td>Chloragogen or yellow cells</td><td>Described as star-shaped and functionally analogous to liver cells, with storage, detoxification and nitrogen metabolism. They chiefly form tissue around the intestine; free cells or derivatives may occur in coelomic fluid.</td></tr><tr><td>Bioluminescent cells</td><td>A comparison with luminous annelids, naming Polynoe and Chaetopterus. It is not evidence that the Pheretima model is itself luminous.</td></tr></tbody></table><p><strong>Source correction:</strong> chloragogen deamination acts on amino acids during nitrogen metabolism, not directly on an intact protein as one undifferentiated reaction. The source's forms protein wording denotes metabolic activity, not a claim that chloragogen cells are a separate digestive gland equivalent to a vertebrate liver.</p>"
    },
    {
      id: "earthworm-digestive-map",
      title: "Complete alimentary canal and segment map",
      sources: [{ document: "biology", page: 8 }, { document: "quick-revision", page: 166 }],
      html: "<p>The alimentary canal is a complete, largely straight tube with a separate mouth and anus, and digestion is extracellular in its lumen. The source calls the earthworm an omnivore. More specifically, the soil-feeding model ingests detritus, microorganisms and organic material with soil. <strong>Source correction:</strong> sanguivorous means blood-feeding and is inappropriate for this earthworm; it belongs to a comparison with blood-feeding leeches.</p><table><thead><tr><th>Region</th><th>Source position</th></tr></thead><tbody><tr><td>Mouth or peristome</td><td>Segment 1, the peristomium.</td></tr><tr><td>Buccal cavity</td><td>Segments 2-3.</td></tr><tr><td>Pharynx</td><td>Segment 4.</td></tr><tr><td>Oesophagus</td><td>Segments 5-7.</td></tr><tr><td>Gizzard</td><td>Segment 8.</td></tr><tr><td>Stomach</td><td>Segments 9-14.</td></tr><tr><td>Intestine, pretyphlosolar region</td><td>Segments 15-26; contains the origin of the intestinal caeca.</td></tr><tr><td>Typhlosolar region</td><td>From segment 27 to the start of the terminal approximately 23-segment region.</td></tr><tr><td>Posttyphlosolar region</td><td>The last approximately 23 segments, extending to the terminal region; no typhlosole.</td></tr><tr><td>Anus</td><td>The terminal pygidial region.</td></tr></tbody></table><p>The handwriting uses 27th to last 23rd and last 23 to last. Because total segment number varies, these are relative posterior descriptions, not an invitation to invent one universal final typhlosolar segment. The printed source describes the typhlosolar region as highly absorptive and the posttyphlosolar region as absorptive and excretory. The latter receives gut-directed nephridial waste and expels it with residues, while water absorption and egestion remain distinct functions.</p>"
    },
    {
      id: "earthworm-anterior-digestion",
      title: "Buccal cavity, pharynx, oesophagus, gizzard and stomach",
      sources: [{ document: "biology", page: 8 }, { document: "biology", page: 9 }],
      html: "<ul><li><strong>Buccal cavity, 2-3:</strong> muscular, non-glandular and protrusible. Chemoreceptors near the mouth detect food-related chemicals; the source calls the taste and smell components gustatoreceptors and olfactoreceptors.</li><li><strong>Pharynx, 4:</strong> muscular and glandular. Contraction of radial dilator muscles running toward the body wall enlarges the pharyngeal cavity and draws food inward by suction. Thus contraction of a dilator enlarges, rather than constricts, this lumen.</li><li>Pharyngeal chromophil cells produce secretion containing mucus or mucin for lubrication and proteolytic enzymes for protein hydrolysis. The source contrasts a dorsal ciliated glandular chamber with a ventral nonciliated nonglandular chamber. Its effective organ for digestion mnemonic emphasizes the pharynx's early role, not the absence of later intestinal digestion.</li><li><strong>Oesophagus, 5-7:</strong> a tubular food passage; goblet cells supply lubricating mucus.</li><li><strong>Gizzard, 8:</strong> a tough mechanical grinder with powerful circular musculature and a thick cuticular lining. The notes describe longitudinal musculature as absent and call it the hardest part. Squeezing and rolling reduce food to small particles. The reference to an oblique septum concerns the local displacement of partitions by this muscular organ.</li><li><strong>Stomach, 9-14:</strong> relatively less muscular and more glandular. Gastric glands contribute digestive secretion, including proteolytic activity. Calciferous glands contribute calcium-carbonate-related secretion and acid-base regulation; the school account emphasizes neutralization of acidic food.</li></ul><p><strong>Source correction:</strong> the calciferous gland should not be described as secreting quicklime, CaO, as written on page 8. Calcium carbonate and carbonate chemistry are relevant to the traditional neutralization account; CaO is not the stated physiological secretion. The outer body cuticle and tough gizzard lining are protective structural layers, not digestive enzymes.</p>"
    },
    {
      id: "earthworm-intestine-castings",
      title: "Intestinal caeca, typhlosole and posterior absorption",
      sources: [{ document: "biology", page: 8 }, { document: "biology", page: 9 }, { document: "quick-revision", page: 166 }],
      html: "<p>The intestine, beginning in segment 15, is a wider, relatively less muscular, glandular and highly vascular part of the alimentary canal. The paired intestinal caeca arise at segment 26 and project forward toward segment 22 in the source drawing. Its two blind forward-projecting sacs flank the gut; their direction must not be reversed merely because food itself moves posteriorly.</p><p>The caeca contribute digestive secretion, including amylolytic activity. The intestinal enzymes complete chemical digestion and the epithelium absorbs products. The typhlosole is an internal longitudinal dorsal fold increasing absorptive surface area. Calling it large villi, as the source does, is an analogy of function, not a literal array of vertebrate intestinal villi.</p><p><strong>Source correction:</strong> the flowchart says amylase directly converts starch into glucose. Amylase primarily breaks starch into shorter carbohydrates, including maltose and dextrins; other hydrolytic enzymes complete production of absorbable monosaccharides. The note's overall carbohydrate-to-glucose outcome must not be assigned to amylase alone.</p><p>The posterior intestine or rectum reabsorbs water. Undigested material and soil particles are expelled through the circular anus as pellets or worm castings. This is egestion. Enteronephric waste reaches the digestive lumen through separate excretory ducts, explaining why castings may also carry metabolic waste without making all defecation identical to excretion.</p>"
    },
    {
      id: "earthworm-digestion-sequence",
      title: "The complete eight-step digestive flowchart",
      sources: [{ document: "biology", page: 9 }, { document: "biology", page: 8 }],
      html: "<ol><li>Mouth-region chemoreceptors identify food-related substances; the mouth and buccal cavity ingest food.</li><li>Muscles connecting the pharynx and body wall contract, enlarging the pharyngeal cavity and drawing particles into the buccal region.</li><li>Pharyngeal proteolytic enzymes hydrolyze proteins, while mucin lubricates and softens the food.</li><li>Food passes through the oesophagus to the gizzard, where squeezing and rolling grind it into small particles.</li><li>The ground material reaches the stomach, where the source's calciferous-gland account emphasizes neutralizing dietary acidity.</li><li>In the intestine, caecal amylolytic secretion contributes to starch digestion. Conversion to free glucose requires completion by additional carbohydrate-hydrolyzing activities rather than amylase alone.</li><li>Intestinal enzymes complete digestion, and products are absorbed across the gut wall. The typhlosole increases the available area.</li><li>Water is absorbed in the posterior gut, and undigested residues leave through the anus as castings.</li></ol><p>The right side of page 9 is empty ruled paper. It contains no extra step or missing organ to be supplied. Its legible content is the complete flowchart at left, consolidated here with the organ descriptions on page 8.</p>"
    },
    {
      id: "earthworm-nephridial-types",
      title: "All three nephridial types and every source range",
      sources: [{ document: "quick-revision", page: 166 }, { document: "biology", page: 10 }, { document: "biology", page: 6 }, { document: "biology", page: 12 }],
      html: "<p>Nephridia are microscopic, coiled tubular excretory organs arranged segmentally. They are functionally analogous to kidneys but are not miniature vertebrate kidneys. Exonephric means discharge directly outside; enteronephric, also called endonephric in the notes, means discharge into the alimentary canal. SP-Ent is the useful printed mnemonic: septal and pharyngeal are enteronephric.</p><table><thead><tr><th>Type</th><th>Structure, route and source distribution</th></tr></thead><tbody><tr><td>Integumentary</td><td>Smallest and most numerous; attached to the inner body wall, described as V-shaped, without a nephrostome. Terminal ducts open outside through nephridiopores, so they are exonephric. The printed table says except the first three segments; Biology instead says from 7 to last while its next line excludes the last segment as well.</td></tr><tr><td>Pharyngeal</td><td>Three paired tufts in segments 4, 5 and 6, without nephrostomes. Ducts lead to the anterior alimentary canal, so these are enteronephric. The source specifies tufts in 4 and 5 discharging to the pharynx and those in 6 to the buccal cavity.</td></tr><tr><td>Septal</td><td>Largest type; has a ciliated nephrostome opening to the coelom. Located on intersegmental septa in the intestinal region and drains into the intestine. Quick Revision says 15th to last; the handwritten notation says 15/16 to second-last.</td></tr></tbody></table><p>The quantitative entries on page 10 give approximately 200-250 integumentary nephridia per ordinary segment and about ten times that number in the clitellum. Septal entries give 80-100 per segment, with 40-50 at the first, fifteenth segment. These are the source model's approximate counts, not exact constants for every worm. The diagram labels buccal cavity 2-3, pharynx 4, paired pharyngeal tufts 4-6, integumentary fields drawn from 7 and septal nephridia in the intestinal region.</p><p><strong>Source disagreement:</strong> the handwritten recap says nephridia absent in 1, 2, 3 and last. That does not resolve the conflicting integumentary start or septal terminal boundary. The printed except first three means segment 4 onward, not 7 onward. These inconsistent boundaries are recorded as unresolved and are not converted into scored facts. The mutually consistent distinctions are the three pharyngeal tufts, the external versus gut-directed outlets, and nephrostome presence in the septal type.</p>"
    },
    {
      id: "earthworm-nephridial-drainage",
      title: "Septal nephrostome-to-intestine pathway",
      sources: [{ document: "biology", page: 10 }, { document: "quick-revision", page: 166 }],
      html: "<p>The source's drainage arrows read: coelomic fluid, nephrostome, neck, coiled nephridial body, terminal duct, septal excretory canal, supra-intestinal excretory canal, intestinal lumen. The terminal duct therefore does not open directly through the skin in the septal type.</p><p>The nephrostome collects coelomic fluid; wastes also exchange from blood into the nephridial tubule, with selective transport modifying its contents. <strong>Source correction:</strong> the diagram's combined coelom/blood arrow must not be read as an open blood vessel pouring blood directly into a nephrostome. Blood remains in the closed vascular system.</p><p>Gut-directed discharge allows further water recovery before waste leaves with gut contents. Integumentary nephridia lack an open coelomic funnel and drain to external nephridiopores; pharyngeal nephridia lack that funnel but drain internally. Thus funnel presence and outlet destination are two different classification criteria.</p>"
    },
    {
      id: "earthworm-male-reproduction",
      title: "Male organs, segment positions and the sperm pathway",
      sources: [{ document: "biology", page: 10 }, { document: "biology", page: 11 }],
      html: "<p>The same mature earthworm carries male and female organs: hermaphrodite, monoecious and the source's bisexual are anatomical descriptions here. Protandry means male gametes mature earlier than female gametes and helps favor cross-fertilization.</p><table><thead><tr><th>Male structure</th><th>Number, position and role</th></tr></thead><tbody><tr><td>Testes</td><td>Two pairs, four testes total, in segments 10 and 11. The source's 9/10 and 10/11 entries refer to attachment at the anterior septa of those segments. Finger-like lobes produce developing male germ cells.</td></tr><tr><td>Testis sacs</td><td>Two bilobed, thin double-walled sacs, one in 10 and one in 11, each enclosing the corresponding testicular pair and sperm funnels. The source calls the tenth sac smaller and the eleventh larger, with the latter associated with the first seminal-vesicle pair.</td></tr><tr><td>Seminal vesicles</td><td>Two pairs in segments 11 and 12. Developing male germ cells mature here; the source describes the eleventh pair as smaller than the twelfth. Monocystis may parasitize these vesicles.</td></tr><tr><td>Spermiducal funnels</td><td>Two pairs, in 10 and 11, ciliated and collecting mature sperm.</td></tr><tr><td>Vasa deferentia</td><td>Sperm ducts run posteriorly from the funnels in 10 and 11 toward the prostatic region at 17/18. The two ducts on each side run together and join the outlet arrangement leading to the male pore.</td></tr><tr><td>Prostate glands</td><td>One pair, flat and lobulated, described as dirty-white or creamy. The source range is 16-17 through 20 or 21, indicating extent rather than one fixed segment. Prostatic secretion supports sperm function.</td></tr><tr><td>Accessory glands</td><td>Two pairs in 17 and 19, associated with copulatory attachment.</td></tr><tr><td>Genital papillae</td><td>Two pairs on 17 and 19, external attachment structures associated with the accessory glands.</td></tr></tbody></table><p>The full sperm route is developing germ cells in testes, maturation in seminal vesicles, return to testis sacs, ciliated spermiducal funnels, vasa deferentia, common spermatic/prostatic outlet, and the paired male pores on segment 18. The diagram labels spermathecae, testes, testis sacs, sperm funnels, seminal vesicles, ovary, oviduct, vasa deferentia, common prostatic and spermatic ducts, accessory glands and prostate glands.</p><p><strong>Source corrections:</strong> the handwritten vasa efferentia heading should be vasa deferentia for these long sperm ducts. Two pairs on each side overcounts the depicted arrangement: there are two ducts per side from the two testicular levels. Developing germ cells should not all be called already mature spermatozoa. The source's statement that seminal vesicles give fructose is not established here for this annelid and must not be transferred uncritically from the mammalian seminal-vesicle model; the verified role in these notes is sperm maturation and nourishment.</p>"
    },
    {
      id: "earthworm-female-reproduction",
      title: "Ovaries, egg ducts and spermathecal anatomy",
      sources: [{ document: "biology", page: 11 }, { document: "biology", page: 6 }, { document: "biology", page: 10 }],
      html: "<table><thead><tr><th>Structure</th><th>Position and function</th></tr></thead><tbody><tr><td>Ovaries</td><td>One pair in segment 13, producing ova.</td></tr><tr><td>Oviducal funnels</td><td>A pair of ciliated funnels in segment 13, collecting ova.</td></tr><tr><td>Oviducts</td><td>Pass from segment 13 to 14 and lead to the single female genital opening.</td></tr><tr><td>Female genital pore</td><td>One midventral opening on segment 14.</td></tr><tr><td>Spermathecae</td><td>Four pairs, one pair each in segments 6, 7, 8 and 9; openings are in grooves 5/6, 6/7, 7/8 and 8/9.</td></tr></tbody></table><p>Spermathecae receive, retain and support a partner's sperm. The source includes them in the female reproductive account because they serve the sperm-receiving role; they do not make ova. The enlarged ampulla contains nutritive fluid, and the diverticulum stores received sperm. The sketch labels ampulla and diverticulum separately.</p><p>Do not confuse the spermathecae in 6-9 with the seminal vesicles in 11-12: the former store received sperm, while the latter support development of the individual's own sperm. Spermathecal segment positions and intersegmental pore positions are deliberately different numerical descriptions.</p>"
    },
    {
      id: "earthworm-cocoon-development",
      title: "Copulation, external fertilization and direct development",
      sources: [{ document: "quick-revision", page: 166 }, { document: "biology", page: 11 }, { document: "biology", page: 6 }],
      html: "<ol><li>Copulation commonly occurs on moist rainy nights in the source account. Two worms attach, and each transfers sperm to the other's spermathecae through the spermathecal pores.</li><li>The glandular clitellar epithelium forms a cocoon and supplies protective and nutritive secretions. The source also uses ootheca as an egg-case term; cocoon is the standard name here.</li><li>As the forming cocoon passes anteriorly, ova and previously received stored sperm enter it through the relevant openings.</li><li>Fertilization occurs outside the parent's body within the cocoon. It is therefore external fertilization, even though the sperm had been stored inside a worm.</li><li>The source gives 8-12 fertilized eggs in a cocoon and says only one embryo develops; the printed page similarly says many eggs but one embryo. This is the specified model account, not a universal cocoon yield for all earthworms.</li><li>Development is direct: a young worm emerges without a free-living larval stage or a metamorphosis like that of a frog.</li></ol><p>Protandry promotes cross-fertilization but should not be stated as a complete explanation of every barrier to selfing in every earthworm species. The clitellum is part of the reproductive apparatus, not simply a locomotory swelling, and papillae aid attachment rather than producing gametes.</p>"
    },
    {
      id: "earthworm-nervous-system",
      title: "Nerve ring, ventral cord and all source nerve counts",
      sources: [{ document: "biology", page: 11 }, { document: "quick-revision", page: 166 }, { document: "biology", page: 12 }],
      html: "<p>The source divides the nervous system into central, peripheral and autonomic or sympathetic components. The central system comprises cerebral ganglia, the circumenteric nerve ring and a ventral nerve cord with segmental ganglia. Peripheral nerves arise from it; the ordinary segmental nerves are mixed, carrying sensory and motor fibers. The autonomic comparison refers to visceral nerve plexuses, not an identical copy of the mammalian sympathetic division.</p><table><thead><tr><th>Part</th><th>Source position and connections</th></tr></thead><tbody><tr><td>Suprapharyngeal or cerebral ganglia</td><td>One fused pair, forming the brain, dorsally above the anterior pharyngeal/buccal region in segment 3. The source lists 8-10 pairs of branches toward the prostomium, buccal region and pharynx.</td></tr><tr><td>Circumpharyngeal connectives</td><td>One pair curving around the pharynx through segments 3-4 and joining the cerebral and subpharyngeal ganglia. The source assigns 2-3 pairs of peripheral branches toward the prostomium and buccal region.</td></tr><tr><td>Subpharyngeal ganglia</td><td>A fused pair ventrally in segment 4. The handwritten heading says 3 pairs, but the printed account and the nerve-ring organization identify one ganglionic pair; the branch list mentions 2-3 pairs of nerves to segments 2, 3 and 4.</td></tr><tr><td>Ventral nerve cord</td><td>Paired cords closely united into a solid ventral cord, with segmental ganglia. A typical segmental ganglion gives three pairs of nerves to the skin, muscles and alimentary canal.</td></tr></tbody></table><p><strong>Source corrections:</strong> ganglion counts must not be confused with counts of outgoing nerve pairs. The prostomium label first segment in the branch sketch denotes the anterior region it supplies; the prostomium itself is a preoral lobe, not the peristomial segment. The exact broad 8-10 and 2-3 branch ranges are retained as source descriptions, not fixed counts of all neuronal connections.</p><p>The comparison table describes the annelid cord as ventral, double and solid, versus the chordate dorsal, single, hollow embryonic nerve cord. Nonchordata is not one uniform nervous-system plan, so that contrast should not be applied to all nonchordate phyla. The recap's absent ganglia in segments 1 and 2 is consistent with the model's cerebral ganglia in 3 and ventral ganglionic organization beginning farther back.</p>"
    },
    {
      id: "earthworm-neurosecretory-senses",
      title: "Neurosecretion and sensory receptors",
      sources: [{ document: "biology", page: 11 }, { document: "biology", page: 12 }, { document: "biology", page: 6 }],
      html: "<p>Cerebral or suprapharyngeal ganglia contain neurosecretory cells. The source links their neurohormones with maturation and release of gametes, clitellar development and cocoon formation. This connects the nervous and reproductive systems; it does not make the cerebral ganglion a gamete-producing gland.</p><ul><li>Earthworms have sensory receptor cells but lack elaborate eyes or ears in this model.</li><li>Light-sensitive cells, especially in the anterior region including the prostomium, contain a specialized phaosome associated with photoreception.</li><li>Thigmoreceptors detect touch.</li><li>Gustatory and olfactory receptor terminology describes responses to chemicals, especially near the mouth and anterior region.</li></ul><p><strong>Source correction:</strong> the phrase L-shaped lens for the phaosome is misleading. A phaosome is a specialized intracellular cavity/membrane system of a light-sensitive cell, not an image-forming lens or compound eye. No special sense organs therefore does not mean the worm is unable to detect light, touch or chemicals.</p>"
    },
    {
      id: "earthworm-blood-glands",
      title: "Closed circulation, blood, blood glands and lymph glands",
      sources: [{ document: "biology", page: 12 }, { document: "quick-revision", page: 166 }],
      html: "<p>Earthworm circulation is closed: blood passes through vessels, capillaries and contractile pumping vessels rather than freely bathing the organs in a hemocoel. The source's first started in Annelida reflects the order of an introductory comparative classification, not proof of a single historical origin of closed circulation.</p><ul><li>Blood consists of plasma and corpuscles. There are no vertebrate-type red blood cells; respiratory hemoglobin is dissolved in the plasma and gives the blood its red color.</li><li>The statement low oxygen-carrying capacity has no comparator or measured concentration. Absence of RBCs does not by itself imply poor oxygen transport; extracellular hemoglobin can carry substantial oxygen.</li><li>Blood glands occur in segments 4, 5 and 6, near the pharyngeal nephridial tufts. The source associates them with formation of blood cells and hemoglobin.</li><li>The structures called lymph glands occur as a pair in each segment from about 26 onward in this model. The notes associate them with blood/coelomic cells, abbreviated C.F.C. for coelomic-fluid cells.</li><li>Earthworm lymph glands and circulating coelomocytes should not be mistaken for vertebrate lymph nodes or a separately demonstrated human-like lymphatic system.</li></ul>"
    },
    {
      id: "earthworm-blood-vessels",
      title: "Dorsal, ventral, lateral and intestinal vessels",
      sources: [{ document: "biology", page: 12 }, { document: "quick-revision", page: 166 }],
      html: "<p>The source lists longitudinal vessels, lateral vessels and the intestinal vascular plexus. The side-view drawing labels brain, mouth, alimentary canal, dorsal vessel, lateral hearts, ventral vessel and the separate ventral nerve cord. A blood vessel and a nerve cord occupying nearby ventral positions are not the same structure.</p><ul><li><strong>Dorsal vessel:</strong> the largest longitudinal vessel, middorsal above the intestine, with a thick contractile wall and valves. Blood moves chiefly from posterior toward anterior.</li><li>It is described as distributing blood in segments 1-13 and collecting in 14 onward. In the collecting region the source gives two pairs of dorso-intestinal vessels from the intestine and one pair of commissural vessels associated with the subneural vessel per segment.</li><li>The source calls the dorsal vessel the true heart because of its contractility and valves. This is a functional analogy; earthworms do not possess a single vertebrate-style chambered heart.</li><li><strong>Ventral vessel:</strong> the principal distributing vessel, running ventrally and lacking valves in the source comparison. The handwritten page ends after its range 2nd to last, with no further local description.</li><li>Supra-oesophageal vessels and lateral connections participate in circulation around the anterior gut. Anterior loops are present in segments 10 and 11 and must not be counted as additional pairs among the four pumping-heart pairs.</li></ul><p>The unfinished line dorsal vessel has thick wall and ... on page 12 is recorded as incomplete. The presence of valves is independently legible on Quick Revision page 166; it is not a guessed completion of that missing phrase.</p>"
    },
    {
      id: "earthworm-hearts",
      title: "Four pairs of pumping hearts and their connections",
      sources: [{ document: "biology", page: 12 }, { document: "quick-revision", page: 166 }],
      html: "<table><thead><tr><th>Pumping vessels</th><th>Positions and source details</th></tr></thead><tbody><tr><td>Lateral hearts</td><td>Two pairs, in segments 7 and 9: four individual pumping vessels. They connect the dorsal vessel to the ventral vessel. The source describes four pairs of valves, eight valve elements, in each and also uses pseudoheart. Its mnemonic notes the gizzard in segment 8 between the two levels.</td></tr><tr><td>Lateral oesophageal hearts</td><td>Two pairs, in 12 and 13: four individual pumping vessels. They receive from the dorsal and supra-oesophageal systems and pass blood to the ventral vessel. The notes describe thick walls and three pairs of valves, six valve elements, per heart.</td></tr></tbody></table><p>Thus four pairs means eight individual hearts in this model, not four chambers of one heart. The vessels curve around the alimentary canal. The printed diagrams explicitly show dorsal to lateral heart to ventral flow, and dorsal plus supra-oesophageal to lateral oesophageal heart to ventral flow. The handwritten extra anterior-loop arrow does not replace these direct connections; the loops themselves are at 10 and 11.</p><p><strong>Source qualification:</strong> the page calls the hearts neurogenic without a physiological demonstration. Annelid vascular contractility can be intrinsically rhythmic and neurally modulated, so membership in a nonchordate group does not establish an exclusively neurogenic pacemaker. That unsupported initiation label is not used as a graded fact. The clear anatomical claims are the contractile vessels, segment positions, valves and connections.</p>"
    },
    {
      id: "earthworm-respiration",
      title: "Cutaneous respiration and oxygen terminology",
      sources: [{ document: "biology", page: 12 }, { document: "biology", page: 6 }, { document: "biology", page: 7 }],
      html: "<p>The model has no specialized lungs, gills or tracheal respiratory system. Oxygen dissolves in the moisture coating the skin and diffuses across the thin body surface into blood; carbon dioxide diffuses outward. Mucus, coelomic fluid, the capillary supply and a moist habitat support this cutaneous exchange. If the skin dries severely, diffusion is impaired and the worm may die from respiratory failure.</p><ul><li>Asphyxia is suffocation or failure of effective gas exchange, the source's dry-skin example.</li><li>Hypoxia means inadequate oxygen availability or use at the tissue level.</li><li>Hypoxemia means abnormally low oxygen in blood, especially arterial blood in clinical usage.</li></ul><p><strong>Source correction:</strong> hypoxia is not defined only as oxygen present in blood but unable to diffuse into cells. That is one possible situation; low blood oxygen, poor perfusion, impaired carriage and impaired cellular utilization can also cause tissue hypoxia. Keeping hypoxia and hypoxemia separate preserves the useful distinction in the source without its overly narrow definition.</p>"
    },
    {
      id: "earthworm-comparative-circulation",
      title: "The THENA comparison mnemonic",
      sources: [{ document: "biology", page: 12 }],
      html: "<p>The boxed open-circulation mnemonic THENA expands in the source to Tunicates/Urochordates, Hemichordates, Echinoderms, Non-cephalopod molluscs and Arthropods. It is intended to contrast these traditional open or reduced circulatory arrangements with the closed vessels of an earthworm.</p><p><strong>Source correction:</strong> this is not one uniform cardiovascular plan. Arthropods and most non-cephalopod molluscs have open systems, whereas cephalopods have closed circulation. Echinoderms rely importantly on coelomic and water-vascular transport and have a reduced hemal system; treating that as an arthropod-like open heart-and-hemocoel circuit is misleading. Tunicate and hemichordate arrangements also need their own anatomical descriptions. Retain THENA as a historical comparison aid, not as a substitute for those distinctions.</p>"
    },
    {
      id: "earthworm-shared-arthropods",
      title: "Shared page 166: complete arthropod classification chart",
      sources: [{ document: "quick-revision", page: 166 }],
      html: "<p>The bottom of the assigned printed image begins Arthropoda. It states that this is the largest animal phylum, meaning by described species diversity, and emphasizes jointed appendages and typically open circulation. <strong>Source correction:</strong> segment number is not always fixed across all arthropods; it varies among groups and may change during development.</p><table><thead><tr><th>Historical chart branch</th><th>Every listed example and note</th></tr></thead><tbody><tr><td>Trilobitomorpha</td><td>Trilobites, extinct arthropods.</td></tr><tr><td>Chelicerata: Merostomata</td><td>Limulus, the horseshoe crab or king crab, called a living fossil. It is a chelicerate, not a true crustacean crab; living fossil is descriptive, not an assertion of no evolutionary change.</td></tr><tr><td>Chelicerata: Arachnida</td><td>Scorpions, ticks, mites and spiders.</td></tr><tr><td>Mandibulata: Crustacea</td><td>Daphnia, water flea; Cancer, crab; Palaemon, prawn; Astacus, crayfish.</td></tr><tr><td>Mandibulata: Insecta</td><td>Cockroaches, fleas, lice including Pediculus, butterflies, moths, wasps, bees and mosquitoes.</td></tr><tr><td>Mandibulata: Chilopoda</td><td>Scolopendra, centipede; poison claws. These claws are modified first trunk appendages, or forcipules. The printed 100 segments is not a literal fixed count for centipedes.</td></tr><tr><td>Mandibulata: Diplopoda</td><td>Julus, millipede; diplosegments, most bearing two pairs of legs.</td></tr></tbody></table><p>The chart labels Arthropoda as phylum, its principal branches as subphyla and the named subdivisions as classes. These are the source's historical ranks: modern pancrustacean relationships and the status of Merostomata are more complex than this scheme. Diplosegmentation means fusion of segmental units, not two entire animals joined together.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 166, status: "partial", sectionIds: ["earthworm-digestive-map", "earthworm-intestine-castings", "earthworm-nephridial-types", "earthworm-nephridial-drainage", "earthworm-cocoon-development", "earthworm-nervous-system", "earthworm-blood-glands", "earthworm-blood-vessels", "earthworm-hearts", "earthworm-shared-arthropods"], unresolved: ["Nephridial table: integumentary 'except first 3 segments' and septal '15th to last' disagree with Biology pages 6 and 10's starts/terminal exclusions. The original boundaries are preserved separately; no disputed endpoint is graded."] },
    { document: "biology", page: 6, status: "partial", sectionIds: ["earthworm-model-habitat", "earthworm-segments-clitellum", "earthworm-setae-locomotion", "earthworm-external-openings", "earthworm-nephridial-types", "earthworm-female-reproduction", "earthworm-cocoon-development", "earthworm-neurosecretory-senses", "earthworm-respiration"], unresolved: ["Internal segmentation: 'septa absent in 1 2 3 4 & 9-10' mixes segment and intersegment labels, leaving the exact anterior septal boundaries ambiguous.", "Body pores: the nephridiopore range appears as '7th to 2nd last'; this conflicts with Quick Revision page 166 and is not used as an exact scored range.", "Setae resistance in '40% KOH' gives no temperature or exposure duration, so an unconditional chemical-resistance claim cannot be established."] },
    { document: "biology", page: 7, status: "transcribed", sectionIds: ["earthworm-setae-locomotion", "earthworm-body-wall", "earthworm-coelom", "earthworm-respiration"], unresolved: [] },
    { document: "biology", page: 8, status: "transcribed", sectionIds: ["earthworm-digestive-map", "earthworm-anterior-digestion", "earthworm-intestine-castings", "earthworm-digestion-sequence"], unresolved: [] },
    { document: "biology", page: 9, status: "transcribed", sectionIds: ["earthworm-anterior-digestion", "earthworm-intestine-castings", "earthworm-digestion-sequence"], unresolved: [] },
    { document: "biology", page: 10, status: "partial", sectionIds: ["earthworm-nephridial-types", "earthworm-nephridial-drainage", "earthworm-male-reproduction", "earthworm-female-reproduction"], unresolved: ["Integumentary range is labelled '7-last', but the same column excludes the last segment; it also contradicts Quick Revision page 166's 'except first 3'.", "Septal range '15/16 to 2nd last' does not uniquely specify whether a first segment or a first septum is intended and differs from the printed terminal boundary.", "The assertion that the earthworm seminal vesicle supplies fructose is unsupported by the provided model description and may conflate annelid and mammalian organs; it is retained as a caution, not a graded fact."] },
    { document: "biology", page: 11, status: "transcribed", sectionIds: ["earthworm-external-openings", "earthworm-male-reproduction", "earthworm-female-reproduction", "earthworm-cocoon-development", "earthworm-nervous-system", "earthworm-neurosecretory-senses"], unresolved: [] },
    { document: "biology", page: 12, status: "partial", sectionIds: ["earthworm-segments-clitellum", "earthworm-nephridial-types", "earthworm-nervous-system", "earthworm-neurosecretory-senses", "earthworm-blood-glands", "earthworm-blood-vessels", "earthworm-hearts", "earthworm-respiration", "earthworm-comparative-circulation"], unresolved: ["Recap repeats the ambiguous anterior septal list and terminal nephridial exclusion; the exact disputed boundaries are not resolved here.", "Dorsal-vessel explanation ends 'as it has thick wall &' without its final phrase; the ventral-vessel subsection ends after '2nd-last'.", "The 'neurogenic heart' label supplies no defined pacemaker experiment or tissue context, so exclusive neurogenic initiation is not established.", "The blood entry 'low O2 carrying capacity' supplies no comparison organism or measurement; no numerical or universal capacity claim is inferred."] }
  ],
  questions: [
    {
      id: "note-earthworm-001", text: "In the Pheretima posthuma model, a glandular collar occupies segments 14-16. Which function best identifies it?",
      options: [{ key: "a", text: "Grinding ingested soil in the gizzard" }, { key: "b", text: "Producing the reproductive cocoon" }, { key: "c", text: "Pumping blood into the dorsal vessel" }, { key: "d", text: "Collecting food through a nephrostome" }],
      answer: "b", explanation: "The clitellum occupies segments 14-16 and secretes material involved in cocoon formation. The gizzard grinds food, hearts pump blood, and a nephrostome belongs to an excretory tubule rather than feeding.", sectionId: "earthworm-segments-clitellum", source: { document: "biology", page: 6 }, cognitive: "understanding"
    },
    {
      id: "note-earthworm-002", text: "Which set of regions lacks ordinary setae in the source's adult Pheretima model?",
      options: [{ key: "a", text: "Segments 2, 3, 4 and 5 only" }, { key: "b", text: "Segments 6, 7, 8 and 9 only" }, { key: "c", text: "Segments 10, 11, 12 and 13 only" }, { key: "d", text: "First, clitellar and terminal regions" }],
      answer: "d", explanation: "The source consistently excludes setae from the first segment, the clitellum at 14-16 and the terminal region. Those exclusions concern this species model and should not be transferred to all annelids.", sectionId: "earthworm-segments-clitellum", source: { document: "biology", page: 12 }, cognitive: "recall"
    },
    {
      id: "note-earthworm-003", text: "If circular muscles contract while coelomic volume is nearly maintained, an earthworm segment should become:",
      options: [{ key: "a", text: "Longer and narrower" }, { key: "b", text: "Shorter and wider" }, { key: "c", text: "Longer and wider" }, { key: "d", text: "Shorter and narrower" }],
      answer: "a", explanation: "Circular contraction reduces circumference. With nearly incompressible coelomic fluid, the segment lengthens as it narrows. Longitudinal contraction instead produces shortening and widening during the locomotory cycle.", sectionId: "earthworm-setae-locomotion", source: { document: "biology", page: 7 }, cognitive: "application"
    },
    {
      id: "note-earthworm-004", text: "Numerous setae form a ring around a typical Pheretima segment. Which term describes this arrangement?",
      options: [{ key: "a", text: "Lumbricine arrangement" }, { key: "b", text: "Parapodial arrangement" }, { key: "c", text: "Perichaetine arrangement" }, { key: "d", text: "Suctorial arrangement" }],
      answer: "c", explanation: "Perichaetine describes the ring of numerous setae around a segment. A lumbricine pattern has a different setal arrangement, parapodia are lateral appendages of polychaetes, and suckers are the leech comparison.", sectionId: "earthworm-setae-locomotion", source: { document: "biology", page: 6 }, cognitive: "recall"
    },
    {
      id: "note-earthworm-005", text: "Which earthworm covering is noncellular and nonchitinous, despite the chitinous nature of its setae?",
      options: [{ key: "a", text: "The glandular epidermis" }, { key: "b", text: "The parietal peritoneum" }, { key: "c", text: "The external cuticle" }, { key: "d", text: "The longitudinal muscle layer" }],
      answer: "c", explanation: "The external cuticle is a noncellular proteinaceous covering secreted by the epidermis. The epidermis, muscles and peritoneum are cellular tissues; chitinous setae do not make the entire body cuticle chitinous.", sectionId: "earthworm-body-wall", source: { document: "biology", page: 7 }, cognitive: "understanding"
    },
    {
      id: "note-earthworm-006", text: "Which arrangement correctly describes the earthworm body-wall muscles from outside toward the coelom?",
      options: [{ key: "a", text: "Circular, then longitudinal" }, { key: "b", text: "Longitudinal, then circular" }, { key: "c", text: "Oblique, then radial" }, { key: "d", text: "Radial, then oblique" }],
      answer: "a", explanation: "The body wall has an outer circular and inner longitudinal layer. The reverse sequence commonly quoted for a vertebrate alimentary canal refers to a different organ and cannot be transferred to the earthworm body wall.", sectionId: "earthworm-body-wall", source: { document: "biology", page: 7 }, cognitive: "recall"
    },
    {
      id: "note-earthworm-007", text: "Which lining separates the earthworm body-wall muscles from the coelomic space?",
      options: [{ key: "a", text: "The intestinal mucosa" }, { key: "b", text: "The visceral peritoneum" }, { key: "c", text: "The external cuticle" }, { key: "d", text: "The parietal peritoneum" }],
      answer: "d", explanation: "Parietal peritoneum lines the body-wall side of the coelom. Visceral peritoneum covers the gut, while the intestinal mucosa faces its lumen and the cuticle covers the outer body surface.", sectionId: "earthworm-body-wall", source: { document: "biology", page: 7 }, cognitive: "understanding"
    },
    {
      id: "note-earthworm-008", text: "The liver-like storage, detoxification and nitrogen-metabolism roles in the source are assigned chiefly to:",
      options: [{ key: "a", text: "Setal formative cells" }, { key: "b", text: "Chloragogen cells" }, { key: "c", text: "Buccal receptor cells" }, { key: "d", text: "Epidermal basal cells" }],
      answer: "b", explanation: "Chloragogen cells around the intestine perform metabolic functions analogous to some liver activities. Setal formative cells make bristles, buccal receptors detect chemicals, and basal epidermal cells renew the epithelium.", sectionId: "earthworm-coelom", source: { document: "biology", page: 7 }, cognitive: "recall"
    },
    {
      id: "note-earthworm-009", text: "In the source's segment map, which region immediately follows the oesophagus in segments 5-7?",
      options: [{ key: "a", text: "Gizzard in segment 8" }, { key: "b", text: "Pharynx in segment 8" }, { key: "c", text: "Intestine in segment 8" }, { key: "d", text: "Buccal cavity in segment 8" }],
      answer: "a", explanation: "The oesophagus in 5-7 leads to the muscular gizzard in 8, followed by the stomach in 9-14. The pharynx is anterior in 4, and the intestine begins only at segment 15 in this model.", sectionId: "earthworm-digestive-map", source: { document: "biology", page: 8 }, cognitive: "recall"
    },
    {
      id: "note-earthworm-010", text: "How can contraction of the radial pharyngeal dilator muscles help an earthworm ingest material?",
      options: [{ key: "a", text: "It narrows the pharynx to eject food" }, { key: "b", text: "It opens the anus to admit soil" }, { key: "c", text: "It enlarges the pharynx to draw food in" }, { key: "d", text: "It closes the mouth to begin grinding" }],
      answer: "c", explanation: "Radial muscles pull the pharyngeal wall outward toward the body wall, increasing cavity volume and drawing material inward. Muscular contraction does not always constrict a lumen; its effect depends on fiber geometry.", sectionId: "earthworm-anterior-digestion", source: { document: "biology", page: 9 }, cognitive: "application"
    },
    {
      id: "note-earthworm-011", text: "Which pairing separates chemical from mechanical digestion in the source earthworm model?",
      options: [{ key: "a", text: "Setae hydrolyze protein; clitellum grinds soil" }, { key: "b", text: "Pharyngeal proteases hydrolyze; gizzard grinds" }, { key: "c", text: "Dorsal pores hydrolyze; spermathecae grind" }, { key: "d", text: "Nephridia hydrolyze starch; ovaries grind" }],
      answer: "b", explanation: "Proteolytic enzymes from the pharyngeal glands chemically hydrolyze protein, while the gizzard mechanically crushes and rolls ingested material. Reproductive, locomotory and excretory structures do not perform the listed digestive reactions.", sectionId: "earthworm-anterior-digestion", source: { document: "biology", page: 8 }, cognitive: "understanding"
    },
    {
      id: "note-earthworm-012", text: "In the intestinal-caeca drawing, sacs originating in segment 26 project in which direction?",
      options: [{ key: "a", text: "Posteriorly toward segment 30" }, { key: "b", text: "Laterally through the body wall" }, { key: "c", text: "Ventrally into the nerve cord" }, { key: "d", text: "Anteriorly toward segment 22" }],
      answer: "d", explanation: "The paired caeca arise at the twenty-sixth segment and project forward toward the twenty-second. Their blind projections therefore point opposite to the overall posterior movement of food through the gut.", sectionId: "earthworm-intestine-castings", source: { document: "biology", page: 8 }, cognitive: "recall"
    },
    {
      id: "note-earthworm-013", text: "What is the direct functional consequence of adding the typhlosole to the intestinal lumen?",
      options: [{ key: "a", text: "A new external opening for sperm" }, { key: "b", text: "A separate chamber for pumping blood" }, { key: "c", text: "A valve preventing all food movement" }, { key: "d", text: "More epithelial surface for absorption" }],
      answer: "d", explanation: "The typhlosole is a longitudinal fold of the intestinal wall and increases absorptive area. It does not create a new body opening or heart and is not a complete partition blocking the gut lumen.", sectionId: "earthworm-intestine-castings", source: { document: "biology", page: 9 }, cognitive: "understanding"
    },
    {
      id: "note-earthworm-014", text: "What should replace the claim that amylase alone completes starch conversion into glucose?",
      options: [{ key: "a", text: "Amylase converts protein directly into glucose" }, { key: "b", text: "Other carbohydrate enzymes complete the process" }, { key: "c", text: "Amylase functions only in mechanical grinding" }, { key: "d", text: "Starch absorption requires no prior hydrolysis" }],
      answer: "b", explanation: "Amylase chiefly generates shorter carbohydrates such as maltose and dextrins. Additional hydrolytic activities complete their conversion into absorbable monosaccharides, so the final glucose outcome cannot be assigned to amylase alone.", sectionId: "earthworm-intestine-castings", source: { document: "biology", page: 9 }, cognitive: "understanding"
    },
    {
      id: "note-earthworm-015", text: "Which nephridial type combines a coelomic nephrostome with discharge into the intestine?",
      options: [{ key: "a", text: "Septal nephridia" }, { key: "b", text: "Pharyngeal nephridia" }, { key: "c", text: "Integumentary nephridia" }, { key: "d", text: "External nephridiopores" }],
      answer: "a", explanation: "Septal nephridia have a nephrostome and are enteronephric. Pharyngeal nephridia also discharge internally but lack a nephrostome; integumentary nephridia lack one and discharge outside through pores.", sectionId: "earthworm-nephridial-types", source: { document: "quick-revision", page: 166 }, cognitive: "understanding"
    },
    {
      id: "note-earthworm-016", text: "The source consistently locates three pairs of pharyngeal nephridial tufts in which segments?",
      options: [{ key: "a", text: "1, 2 and 3" }, { key: "b", text: "7, 8 and 9" }, { key: "c", text: "4, 5 and 6" }, { key: "d", text: "14, 15 and 16" }],
      answer: "c", explanation: "Both assigned sources place pharyngeal nephridial tufts in segments 4, 5 and 6. This consistent range is distinct from the conflicting integumentary and terminal septal boundaries, which are deliberately not assessed.", sectionId: "earthworm-nephridial-types", source: { document: "biology", page: 10 }, cognitive: "recall"
    },
    {
      id: "note-earthworm-017", text: "A tracer leaves a septal nephridium's terminal duct. Which downstream route matches the source diagram?",
      options: [{ key: "a", text: "Vas deferens, prostatic duct, male pore" }, { key: "b", text: "Septal canal, supra-intestinal canal, intestine" }, { key: "c", text: "Spermathecal duct, ampulla, diverticulum" }, { key: "d", text: "Dorsal vessel, lateral heart, ventral vessel" }],
      answer: "b", explanation: "The septal terminal ducts drain to septal excretory canals and then supra-intestinal excretory canals before reaching the gut lumen. The other routes belong to reproductive or vascular systems.", sectionId: "earthworm-nephridial-drainage", source: { document: "biology", page: 10 }, cognitive: "application"
    },
    {
      id: "note-earthworm-018", text: "Which two nephridial types share internal discharge despite differing in nephrostome presence?",
      options: [{ key: "a", text: "Septal and pharyngeal" }, { key: "b", text: "Septal and integumentary" }, { key: "c", text: "Pharyngeal and integumentary" }, { key: "d", text: "Integumentary and cutaneous" }],
      answer: "a", explanation: "The SP-Ent mnemonic identifies septal and pharyngeal nephridia as enteronephric. Septal nephridia have a nephrostome; pharyngeal ones do not. Integumentary nephridia instead discharge through external pores.", sectionId: "earthworm-nephridial-types", source: { document: "quick-revision", page: 166 }, cognitive: "recall"
    },
    {
      id: "note-earthworm-019", text: "Which comparison correctly distinguishes the two sperm-associated storage regions?",
      options: [{ key: "a", text: "Seminal vesicles make ova; spermathecae make sperm" }, { key: "b", text: "Seminal vesicles pump blood; spermathecae filter waste" }, { key: "c", text: "Seminal vesicles mature own sperm; spermathecae receive sperm" }, { key: "d", text: "Seminal vesicles form cocoons; spermathecae grind food" }],
      answer: "c", explanation: "Seminal vesicles in segments 11-12 support maturation of the worm's own developing sperm. Spermathecae in 6-9 store sperm received from a mating partner; neither organ is an ovary or a clitellum.", sectionId: "earthworm-female-reproduction", source: { document: "biology", page: 11 }, cognitive: "understanding"
    },
    {
      id: "note-earthworm-020", text: "A spermatheca lies in segment 8 of the model worm. Which listed intersegmental groove carries its external opening?",
      options: [{ key: "a", text: "5/6" }, { key: "b", text: "6/7" }, { key: "c", text: "8/9" }, { key: "d", text: "7/8" }],
      answer: "d", explanation: "The source pairs spermathecae in segments 6, 7, 8 and 9 with pores in 5/6, 6/7, 7/8 and 8/9 respectively. The segment-8 organ therefore opens in the groove immediately anterior to that segment.", sectionId: "earthworm-female-reproduction", source: { document: "biology", page: 6 }, cognitive: "application"
    },
    {
      id: "note-earthworm-021", text: "Which location contains the single paired set of ovaries in Pheretima posthuma?",
      options: [{ key: "a", text: "Segment 13" }, { key: "b", text: "Segment 10" }, { key: "c", text: "Segment 14" }, { key: "d", text: "Segment 18" }],
      answer: "a", explanation: "One pair of ovaries lies in segment 13, along with the collecting oviducal funnels. The female pore is on 14 and male pores on 18; the testes occupy the earlier segments 10 and 11.", sectionId: "earthworm-female-reproduction", source: { document: "biology", page: 11 }, cognitive: "recall"
    },
    {
      id: "note-earthworm-022", text: "Which external openings carry the common spermatic and prostatic discharge in the source model?",
      options: [{ key: "a", text: "One dorsal opening on segment 14" }, { key: "b", text: "Two midventral openings on segment 13" }, { key: "c", text: "Four anterior openings on segment 10" }, { key: "d", text: "Paired ventrolateral openings on segment 18" }],
      answer: "d", explanation: "The paired male genital pores on segment 18 discharge sperm with prostatic secretion. The female pore is single and midventral on 14, while spermathecal pores occupy earlier intersegmental grooves.", sectionId: "earthworm-external-openings", source: { document: "biology", page: 6 }, cognitive: "recall"
    },
    {
      id: "note-earthworm-023", text: "A worm stores a partner's sperm internally, but sperm and eggs fuse later inside a shed cocoon. Fertilization is classified as:",
      options: [{ key: "a", text: "Internal, because sperm was once stored" }, { key: "b", text: "External, because fusion occurs outside" }, { key: "c", text: "Asexual, because one cocoon is formed" }, { key: "d", text: "Parthenogenetic, because no sperm fuses" }],
      answer: "b", explanation: "Fertilization is classified by the site of gamete fusion, not the earlier site of sperm storage. Fusion occurs in the cocoon outside the parent, so it is external even though spermathecae previously held the sperm.", sectionId: "earthworm-cocoon-development", source: { document: "biology", page: 11 }, cognitive: "application"
    },
    {
      id: "note-earthworm-024", text: "In the described earthworm, male gametes mature before female gametes. This timing is called:",
      options: [{ key: "a", text: "Protogyny" }, { key: "b", text: "Parthenogenesis" }, { key: "c", text: "Protandry" }, { key: "d", text: "Metamorphosis" }],
      answer: "c", explanation: "Protandry is earlier male reproductive maturation and can promote cross-fertilization in a hermaphrodite. Protogyny is the opposite timing, parthenogenesis lacks fertilization, and metamorphosis is a developmental transformation.", sectionId: "earthworm-male-reproduction", source: { document: "biology", page: 10 }, cognitive: "recall"
    },
    {
      id: "note-earthworm-025", text: "What observation best supports direct development in the source earthworm model?",
      options: [{ key: "a", text: "A swimming tadpole leaves the cocoon" }, { key: "b", text: "A ciliated trochophore transforms outside" }, { key: "c", text: "A young worm emerges without a larval metamorphosis" }, { key: "d", text: "An adult releases unfertilized eggs that bud" }],
      answer: "c", explanation: "Direct development produces a juvenile worm without a free-living larval stage and metamorphosis. Tadpoles are the frog comparison, and a trochophore is not the developmental stage of this terrestrial earthworm model.", sectionId: "earthworm-cocoon-development", source: { document: "biology", page: 11 }, cognitive: "understanding"
    },
    {
      id: "note-earthworm-026", text: "Which nervous-system pairing matches the source's corrected earthworm anatomy?",
      options: [{ key: "a", text: "Brain in 4; subpharyngeal ganglia in 3" }, { key: "b", text: "Brain in 3; subpharyngeal ganglia in 4" }, { key: "c", text: "Brain in 7; subpharyngeal ganglia in 9" }, { key: "d", text: "Brain in 12; subpharyngeal ganglia in 13" }],
      answer: "b", explanation: "Cerebral or suprapharyngeal ganglia form the brain in segment 3, while the subpharyngeal ganglionic pair lies in 4. The other segment pairs are associated with pumping hearts rather than the nerve ring.", sectionId: "earthworm-nervous-system", source: { document: "quick-revision", page: 166 }, cognitive: "recall"
    },
    {
      id: "note-earthworm-027", text: "Which statement explains how earthworm blood can be red without vertebrate-type erythrocytes?",
      options: [{ key: "a", text: "Porphyrin-filled setae circulate through vessels" }, { key: "b", text: "Chlorophyll from leaves substitutes for hemoglobin" }, { key: "c", text: "Red skeletal muscle fibers detach into the coelom" }, { key: "d", text: "Respiratory hemoglobin is dissolved in plasma" }],
      answer: "d", explanation: "Earthworm hemoglobin is extracellular in blood plasma. Red blood color therefore does not require the vertebrate arrangement of hemoglobin packaged into erythrocytes, and it is separate from the body-wall pigment.", sectionId: "earthworm-blood-glands", source: { document: "biology", page: 12 }, cognitive: "understanding"
    },
    {
      id: "note-earthworm-028", text: "Which four segments contain the paired pumping hearts in the source's Pheretima model?",
      options: [{ key: "a", text: "7, 9, 12 and 13" }, { key: "b", text: "7, 8, 10 and 11" }, { key: "c", text: "4, 5, 6 and 7" }, { key: "d", text: "14, 15, 16 and 17" }],
      answer: "a", explanation: "Lateral hearts occur in 7 and 9; lateral oesophageal hearts occur in 12 and 13. The anterior loops in 10 and 11 are distinct vessels and must not replace heart levels in this count.", sectionId: "earthworm-hearts", source: { document: "quick-revision", page: 166 }, cognitive: "recall"
    },
    {
      id: "note-earthworm-029", text: "A severe loss of skin moisture most directly threatens which earthworm process?",
      options: [{ key: "a", text: "Diffusion of respiratory gases across the skin" }, { key: "b", text: "Ventilation of the paired internal lungs" }, { key: "c", text: "Pumping water across the external gills" }, { key: "d", text: "Opening air valves of the tracheal system" }],
      answer: "a", explanation: "The worm relies on cutaneous gas exchange through a moist surface. Drying interrupts this diffusion pathway; the model has no lungs, external respiratory gills or insect-like tracheal air valves.", sectionId: "earthworm-respiration", source: { document: "biology", page: 12 }, cognitive: "application"
    },
    {
      id: "note-earthworm-030", text: "Which vessel is the principal valveless distributing channel in the printed earthworm comparison?",
      options: [{ key: "a", text: "The middorsal collecting vessel" }, { key: "b", text: "The longitudinal ventral vessel" }, { key: "c", text: "The pair of anterior nerve connectives" }, { key: "d", text: "The supra-intestinal excretory canal" }],
      answer: "b", explanation: "The ventral blood vessel is the main distributing vessel and is described as lacking valves. The dorsal vessel is contractile and valved; nerve connectives and the supra-intestinal excretory canal do not carry out this vascular role.", sectionId: "earthworm-blood-vessels", source: { document: "quick-revision", page: 166 }, cognitive: "recall"
    }
  ]
};