window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["electrochemistry"] = {
  id: "electrochemistry",
  subject: "Chemistry",
  title: "Electrochemistry",
  sections: [
    {
      id: "cells-electrochemical-series",
      title: "Galvanic cells and the electrochemical series",
      sources: [{ document: "quick-revision", page: 65 }],
      html: "<p>A galvanic cell converts chemical energy into electrical energy through a spontaneous redox reaction. It is also called a voltaic cell. The source gives the Daniell cell as its example, spelling it 'Daniel'. Source exam label: KU 2013.</p><p>The electrochemical series arranges electrode couples in order of increasing standard reduction potential. A more positive standard reduction potential indicates a greater tendency for the corresponding oxidized species to undergo reduction under standard conditions. Keep all listed potentials in the same reduction convention when comparing or subtracting them.</p><p><strong>Source qualification:</strong> the heading says electrochemical cells generally, but the stated chemical-to-electrical conversion specifically describes galvanic cells. An electrolytic cell instead uses electrical energy to drive a nonspontaneous chemical change.</p>"
    },
    {
      id: "galvanic-electrodes-flow",
      title: "Electrode signs and both directions of external flow",
      sources: [{ document: "quick-revision", page: 65 }],
      html: "<table><thead><tr><th>Galvanic-cell feature</th><th>Source rule</th></tr></thead><tbody><tr><td>Anode</td><td>Negative pole; oxidation occurs</td></tr><tr><td>Cathode</td><td>Positive pole; reduction occurs</td></tr><tr><td>Electrons in the external wire</td><td>Negative anode to positive cathode</td></tr><tr><td>Conventional current in the external wire</td><td>Positive cathode to negative anode</td></tr></tbody></table><p>Electrons and conventional current therefore run in opposite directions in the external metallic circuit. Charge transfer through the electrolyte is carried by ions rather than electrons moving freely through the solution.</p><p><strong>Source qualification:</strong> anode always names the oxidation electrode and cathode the reduction electrode, but their negative/positive signs in this box are for a discharging galvanic cell. In an externally driven electrolytic cell the anode is positive and the cathode negative. Source exam labels: IOM 2011 and KU 2008.</p>"
    },
    {
      id: "metal-electrode-nernst",
      title: "Nernst equation for a metal-ion reduction",
      sources: [{ document: "quick-revision", page: 65 }],
      html: "<p>For M<sup>n+</sup>(aq) + ne<sup>-</sup> &rightleftharpoons; M(s), a pure metal has unit activity. The reaction quotient is therefore $Q=\\frac{1}{a(M^{n+})}$, and the electrode reduction potential is</p><p>$E=E^\\circ-\\frac{2.303RT}{nF}\\log_{10}\\frac{1}{a(M^{n+})}$.</p><p>Equivalently, $E=E^\\circ+\\frac{2.303RT}{nF}\\log_{10}a(M^{n+})$. The source uses the concentration [M<sup>n+</sup>] in place of activity, which is appropriate as a dilute ideal-solution approximation when referred to the standard concentration.</p><p>Here R is the gas constant, T absolute temperature, n the number of electrons in the reduction, and F the Faraday constant. At 298 K, $\\frac{2.303RT}{F}\\approx0.05916$ V. Increasing metal-ion activity raises this reduction potential; decreasing it lowers the potential. This specific quotient assumes the deposited metal is a pure solid rather than an alloy or another non-unit-activity phase.</p>"
    },
    {
      id: "cell-nernst-potential",
      title: "General reaction quotient and standard cell emf",
      sources: [{ document: "quick-revision", page: 65 }],
      html: "<p>For an overall cell reaction $aA+bB\\rightarrow cC+dD$, the source's concentration quotient is $Q=\\frac{[C]^c[D]^d}{[A]^a[B]^b}$. Use activities for a thermodynamic treatment, omit pure solid and pure liquid factors, and use partial-pressure activities for gases.</p><p>The Nernst equation is $E_{cell}=E^\\circ_{cell}-\\frac{2.303RT}{nF}\\log_{10}Q$. The balanced overall reaction determines both the exponents and the number of electrons transferred. Source exam labels: KU 2000 and 2001.</p><p>The standard emf is $E^\\circ_{cell}=E^\\circ_{cathode}-E^\\circ_{anode}$ when both tabulated electrode values are standard reduction potentials. Do not multiply an electrode potential by the balancing coefficient: potential is energy per charge, whereas the balanced electron count and the total reaction Gibbs energy scale with reaction amount.</p>"
    },
    {
      id: "equilibrium-gibbs-cell",
      title: "Equilibrium constant and Gibbs energy of a cell",
      sources: [{ document: "quick-revision", page: 65 }],
      html: "<p>At equilibrium the actual reversible cell emf is zero and Q = K. Substitution into the Nernst equation gives $E^\\circ_{cell}=\\frac{RT}{nF}\\ln K$, equivalently $E^\\circ_{cell}=\\frac{2.303RT}{nF}\\log_{10}K$.</p><p><strong>Source correction:</strong> the printed equilibrium-constant formula has 2.303 divided by nF but omits RT. The temperature and gas-constant factor is required, both algebraically and dimensionally. The source labels the constant Kc; a dimensionless activity-based K is required for the rigorous logarithm relation. A standard cell potential need not be zero merely because the actual cell has reached equilibrium.</p><p>The source also gives the correct energy relations $\\Delta_rG=-nFE_{cell}$ and $\\Delta_rG^\\circ=-RT\\ln K=-2.303RT\\log_{10}K$. Combining them under standard conditions gives $\\Delta_rG^\\circ=-nFE^\\circ_{cell}$. A positive cell emf corresponds to a negative reaction Gibbs energy and spontaneous discharge in the written direction at the specified conditions.</p>"
    },
    {
      id: "conductivity-definitions",
      title: "Specific, molar and equivalent conductivity",
      sources: [{ document: "quick-revision", page: 65 }],
      html: "<p>The source uses K for specific conductance; use kappa here to avoid confusing it with an equilibrium constant. Conductivity kappa characterizes a solution's ability to carry current after electrode geometry is accounted for.</p><p>Molar conductivity corresponds to conductivity normalized to the concentration of one mole of electrolyte. With kappa in S cm<sup>-1</sup> and molarity M in mol L<sup>-1</sup>, $\\Lambda_m=\\frac{1000\\kappa}{M}$ in S cm<sup>2</sup> mol<sup>-1</sup>. The factor 1000 converts liters to cubic centimeters.</p><p>Equivalent conductivity similarly refers to one gram-equivalent, meaning one mole of the specified charge or reaction equivalents, not one gram of any electrolyte. With normality N in equivalents L<sup>-1</sup>, $\\Lambda_{eq}=\\frac{1000\\kappa}{N}$ in S cm<sup>2</sup> equivalent<sup>-1</sup>.</p><p><strong>Source clarification:</strong> the short definitions 'conductance of a solution [containing] one mole' and 'one gram equivalent' omit the geometry and concentration normalization. These are conductivities per concentration, not the resistance-dependent conductance of an arbitrary beaker. If SI concentration is in mol m<sup>-3</sup> and conductivity in S m<sup>-1</sup>, use $\\Lambda_m=\\frac{\\kappa}{c}$ without the liter-to-centimeter factor.</p>"
    },
    {
      id: "conductivity-dilution",
      title: "Dilution: distinguish ions per sample from ions per volume",
      sources: [{ document: "quick-revision", page: 65 }],
      html: "<p>The source lists three dilution observations: number of ions increases and molar conductance increases; specific conductance decreases; molar and equivalent conductivity increase. At fixed temperature in the ordinary concentration range, the conductivity per unit volume generally decreases on dilution, whereas conductivity normalized per mole or equivalent increases toward a limiting value.</p><p><strong>Source correction:</strong> dilution does not necessarily create more ions in a fixed sample. For a strong electrolyte already dissociated, its total number of ions is essentially unchanged, while their concentration falls and interionic interactions diminish. For a weak electrolyte, dilution increases the degree of ionization, so the number of ions derived from a given initial amount can increase. Even then, ions per unit volume need not increase.</p><p>The rise in molar or equivalent conductivity must therefore not be confused with a rise in the bulk specific conductivity. Compare at the same temperature, since ionic mobility and conductivity also depend on temperature.</p>"
    },
    {
      id: "molar-equivalent-relation",
      title: "The valence-factor relation, with the algebra repaired",
      sources: [{ document: "quick-revision", page: 65 }],
      html: "<p>Let z be the source's v.f., the number of equivalents per mole for the specified ionic or reaction convention. Then normality N = Mz. Starting from the printed definitions:</p><p>$\\Lambda_{eq}=\\frac{1000\\kappa}{N}=\\frac{1000\\kappa}{Mz}$.</p><p>Since $\\Lambda_m=\\frac{1000\\kappa}{M}$, it follows that $\\Lambda_{eq}=\\frac{\\Lambda_m}{z}$ and $z\\Lambda_{eq}=\\Lambda_m$.</p><p><strong>Source correction:</strong> the intermediate printed line divides Lambda m by M times v.f. That extra M is an algebraic error: M is already incorporated into Lambda m. The final printed relation Lambda eq times v.f. = Lambda m is the correct one.</p><p>The page notes a minimum valence factor of one and therefore Lambda m greater than or equal to Lambda eq. This compares numerical values expressed in their corresponding molar and equivalent units for the ordinary positive-integer charge factors z &ge; 1. Equality holds for z = 1. Specify the equivalent convention when normality is reaction dependent; do not assign a valence factor without knowing which process is meant.</p>"
    },
    {
      id: "electrolysis-products",
      title: "Every electrolysis-product row and its conditions",
      sources: [{ document: "quick-revision", page: 65 }],
      html: "<p>The page gives the following four electrolyte rows. The source entries are retained, with conditions and the sulfuric-acid correction immediately below. Source exam label: KU 2008.</p><table><thead><tr><th>Electrolyte</th><th>Cathode</th><th>Anode</th></tr></thead><tbody><tr><td>Molten NaCl</td><td>Na metal</td><td>Cl<sub>2</sub> gas</td></tr><tr><td>Aqueous NaCl</td><td>H<sub>2</sub> gas</td><td>Source: Cl<sub>2</sub> gas; concentration-dependent</td></tr><tr><td>Dilute H<sub>2</sub>SO<sub>4</sub></td><td>H<sub>2</sub> gas</td><td>O<sub>2</sub> gas with suitable inert electrodes</td></tr><tr><td>Concentrated H<sub>2</sub>SO<sub>4</sub></td><td>H<sub>2</sub> gas</td><td>Source prints H<sub>2</sub>SO<sub>5</sub>; see correction</td></tr></tbody></table><p>Molten NaCl has no competing water reduction: Na<sup>+</sup> + e<sup>-</sup> &rarr; Na at the cathode, and 2Cl<sup>-</sup> &rarr; Cl<sub>2</sub> + 2e<sup>-</sup> at the anode. In aqueous brine, water reduction produces hydrogen rather than sodium. Concentrated chloride solutions and suitable anodes favor chlorine evolution; sufficiently dilute chloride and other electrode conditions can favor oxygen instead.</p><p>Dilute sulfuric acid with inert electrodes primarily electrolyzes water, yielding hydrogen at the cathode and oxygen at the anode. Electrode materials that themselves react require a different product analysis.</p><p><strong>Source correction:</strong> the usual controlled anodic oxidation of concentrated sulfate/bisulfate can form peroxodisulfate, represented in the acid form as H<sub>2</sub>S<sub>2</sub>O<sub>8</sub>, not an unconditional direct H<sub>2</sub>SO<sub>5</sub> product. For example, 2HSO<sub>4</sub><sup>-</sup> &rarr; S<sub>2</sub>O<sub>8</sub><sup>2-</sup> + 2H<sup>+</sup> + 2e<sup>-</sup>. Subsequent hydrolysis can form peroxomonosulfuric acid: H<sub>2</sub>S<sub>2</sub>O<sub>8</sub> + H<sub>2</sub>O &rarr; H<sub>2</sub>SO<sub>5</sub> + H<sub>2</sub>SO<sub>4</sub>.</p><p><strong>Unresolved source conditions:</strong> the aqueous-NaCl row supplies no concentration or electrode material, so its anode product is not uniquely determined as written. The concentrated-sulfuric-acid row supplies no temperature, electrode, current-density or subsequent-hydrolysis conditions, so its exact intended product sequence cannot be recovered. These incomplete rows are not used as unconditional facts in scored questions.</p>"
    },
    {
      id: "faraday-copper-deposition",
      title: "One faraday and the copper sulfate example",
      sources: [{ document: "quick-revision", page: 65 }],
      html: "<p>The source gives one faraday as approximately 96500 C, the magnitude of the charge carried by one mole of electrons. Its printed electron count is $6.023\\times10^{23}$. <strong>Source precision correction:</strong> the current exact Avogadro count is $6.02214076\\times10^{23}$ electrons per mole, and the Faraday constant is approximately 96485 C mol<sup>-1</sup>; 96500 is the rounded working value used in these notes. Source exam label: KU 2010.</p><p>In CuSO<sub>4</sub> solution, Cu<sup>2+</sup> + 2e<sup>-</sup> &rarr; Cu. One faraday supplies one mole of electrons, so it can deposit one-half mole of copper atoms at 100% current efficiency. This is the source's 'one-half gram atom of the metal', not one-half gram of copper. Source exam label: IOM 2011.</p><p>For a charge Q, the electron amount is $n_e=\\frac{Q}{F}$; if each deposited atom requires z electrons, the metal amount is $n_{metal}=\\frac{Q}{zF}$. With molar mass Mmetal, $m=\\frac{QM_{metal}}{zF}$. For constant current I over time t, Q = It. These expressions are the charge-balance working behind the source's copper example; competing reactions or less than 100% current efficiency reduce the deposited amount.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 65, status: "partial", sectionIds: ["cells-electrochemical-series", "galvanic-electrodes-flow", "metal-electrode-nernst", "cell-nernst-potential", "equilibrium-gibbs-cell", "conductivity-definitions", "conductivity-dilution", "molar-equivalent-relation", "electrolysis-products", "faraday-copper-deposition"], unresolved: ["Electrolysis table: aqueous NaCl has no chloride concentration or electrode material. The printed chlorine-anode entry is conditional; the actual intended experimental anode product is not uniquely recoverable.", "Electrolysis table: concentrated H2SO4 lists H2SO5 but omits electrode, temperature, current density and any subsequent hydrolysis step. The standard peroxodisulfate correction and possible H2SO5 hydrolysis product are distinguished; the intended experiment/product sequence remains unspecified."] }
  ],
  questions: [
    { id: "note-electrochemistry-001", text: "During spontaneous discharge, a galvanic cell primarily performs which energy conversion?", options: [{ key: "a", text: "Electrical energy into chemical energy" }, { key: "b", text: "Electrical energy into thermal energy" }, { key: "c", text: "Light energy into electrical energy" }, { key: "d", text: "Chemical energy into electrical energy" }], answer: "d", explanation: "A galvanic or voltaic cell uses a spontaneous chemical redox reaction to supply electrical energy to an external circuit. The reverse electrical-to-chemical role describes an externally driven electrolytic process.", sectionId: "cells-electrochemical-series", source: { document: "quick-revision", page: 65 }, cognitive: "recall" },
    { id: "note-electrochemistry-002", text: "The electrochemical series described on the page arranges electrode couples by increasing values of which quantity?", options: [{ key: "a", text: "Standard reduction potential" }, { key: "b", text: "Standard oxidation potential" }, { key: "c", text: "Electrolyte molar conductivity" }, { key: "d", text: "Electrode material molar mass" }], answer: "a", explanation: "The series uses increasing standard reduction potentials under a common reference convention. Reversing each half-reaction changes the potential sign, so increasing oxidation potential would reverse this ordering. Conductivity and molar mass do not define it.", sectionId: "cells-electrochemical-series", source: { document: "quick-revision", page: 65 }, cognitive: "recall" },
    { id: "note-electrochemistry-003", text: "Which description correctly identifies the anode of a discharging galvanic cell?", options: [{ key: "a", text: "Positive electrode where oxidation occurs" }, { key: "b", text: "Negative electrode where reduction occurs" }, { key: "c", text: "Negative electrode where oxidation occurs" }, { key: "d", text: "Positive electrode where reduction occurs" }], answer: "c", explanation: "The galvanic anode supplies electrons through oxidation and is the negative electrode. Oxidation at the anode is universal, but the negative sign is specific to the galvanic operating mode described here.", sectionId: "galvanic-electrodes-flow", source: { document: "quick-revision", page: 65 }, cognitive: "recall" },
    { id: "note-electrochemistry-004", text: "In the external wire of a discharging galvanic cell, how do electron flow and conventional current compare?", options: [{ key: "a", text: "Both run from cathode to anode." }, { key: "b", text: "Electrons run anode to cathode; current runs oppositely." }, { key: "c", text: "Electrons run cathode to anode; current runs oppositely." }, { key: "d", text: "Both run from anode to cathode." }], answer: "b", explanation: "Electrons leave the negative anode and arrive at the positive cathode through the wire. Conventional current is defined as positive-charge flow, so its direction is the reverse, cathode to anode.", sectionId: "galvanic-electrodes-flow", source: { document: "quick-revision", page: 65 }, cognitive: "understanding" },
    { id: "note-electrochemistry-005", text: "A Daniell-type cell uses standard reduction potentials Cu<sup>2+</sup>/Cu = +0.34 V and Zn<sup>2+</sup>/Zn = -0.76 V. What is its standard emf for zinc oxidation and copper-ion reduction?", options: [{ key: "a", text: "+1.10 V" }, { key: "b", text: "-1.10 V" }, { key: "c", text: "+0.42 V" }, { key: "d", text: "-0.42 V" }], answer: "a", explanation: "Subtract the anode's reduction potential from the cathode's: $E^\\circ_{cell}=0.34-(-0.76)=+1.10$ V. Adding the two reduction potentials directly would incorrectly give -0.42 V.", sectionId: "cell-nernst-potential", source: { document: "quick-revision", page: 65 }, cognitive: "application" },
    { id: "note-electrochemistry-006", text: "Every coefficient of a balanced cell reaction is doubled. What happens to its standard emf?", options: [{ key: "a", text: "It doubles because twice as many electrons move." }, { key: "b", text: "It halves because electron count is in the denominator." }, { key: "c", text: "It reverses sign because the quotient is squared." }, { key: "d", text: "It stays unchanged because energy and charge both double." }], answer: "d", explanation: "Potential is energy per charge. Doubling the equation doubles both the Gibbs energy change and n in delta G0 = -nFE0, leaving E0 unchanged. Electrode potentials are not multiplied by stoichiometric coefficients.", sectionId: "cell-nernst-potential", source: { document: "quick-revision", page: 65 }, cognitive: "understanding" },
    { id: "note-electrochemistry-007", text: "For M<sup>2+</sup> + 2e<sup>-</sup> &rightleftharpoons; M(s) at 298 K, ion activity rises by a factor of 100. Using 0.05916 V for 2.303RT/F, how does the reduction potential change?", options: [{ key: "a", text: "It falls by 0.05916 V." }, { key: "b", text: "It rises by 0.05916 V." }, { key: "c", text: "It rises by 0.02958 V." }, { key: "d", text: "It falls by 0.02958 V." }], answer: "b", explanation: "For a pure deposited metal, $\\Delta E=\\frac{0.05916}{2}\\log_{10}(100)=0.02958\\times2=+0.05916$ V. The ion occurs in the denominator of the reduction quotient, so increasing its activity raises E.", sectionId: "metal-electrode-nernst", source: { document: "quick-revision", page: 65 }, cognitive: "application" },
    { id: "note-electrochemistry-008", text: "For Cu<sup>2+</sup>/Cu, E0 = +0.340 V and the ion activity is 0.010 at 298 K. Using E = E0 + (0.05916/2) log<sub>10</sub>a, what is E?", options: [{ key: "a", text: "+0.399 V" }, { key: "b", text: "+0.310 V" }, { key: "c", text: "+0.281 V" }, { key: "d", text: "+0.222 V" }], answer: "c", explanation: "Since log10(0.010) = -2, $E=0.340+0.02958(-2)=0.28084$ V, approximately 0.281 V. Reduced ion activity lowers the reduction potential below its standard value.", sectionId: "metal-electrode-nernst", source: { document: "quick-revision", page: 65 }, cognitive: "application" },
    { id: "note-electrochemistry-009", text: "At 298 K, a cell has E0 = 1.100 V, n = 2 and reaction quotient Q = 10<sup>4</sup>. Using the Nernst coefficient 0.05916 V, what is its emf?", options: [{ key: "a", text: "1.218 V" }, { key: "b", text: "1.041 V" }, { key: "c", text: "0.863 V" }, { key: "d", text: "0.982 V" }], answer: "d", explanation: "The correction is $\\frac{0.05916}{2}\\log_{10}(10^4)=0.02958\\times4=0.11832$ V. Subtracting it from 1.100 V gives 0.98168 V, approximately 0.982 V.", sectionId: "cell-nernst-potential", source: { document: "quick-revision", page: 65 }, cognitive: "application" },
    { id: "note-electrochemistry-010", text: "What must be true when an ideal reversible cell reaction reaches equilibrium?", options: [{ key: "a", text: "The standard emf is zero and the actual emf is positive." }, { key: "b", text: "The actual emf is zero and its reaction quotient equals K." }, { key: "c", text: "Both electrode reduction potentials must equal zero." }, { key: "d", text: "The reaction quotient is one for every cell reaction." }], answer: "b", explanation: "At equilibrium the actual reaction Gibbs energy and reversible driving emf vanish, and Q = K. The standard emf can remain nonzero because it describes standard conditions, not necessarily the equilibrium composition.", sectionId: "equilibrium-gibbs-cell", source: { document: "quick-revision", page: 65 }, cognitive: "understanding" },
    { id: "note-electrochemistry-011", text: "A two-electron cell has standard emf 0.11832 V at 298 K. With E0 = (0.05916/n) log<sub>10</sub>K, what is K?", options: [{ key: "a", text: "$10^1$" }, { key: "b", text: "$10^2$" }, { key: "c", text: "$10^4$" }, { key: "d", text: "$10^8$" }], answer: "c", explanation: "Rearrange to $\\log_{10}K=\\frac{nE^\\circ}{0.05916}=\\frac{2\\times0.11832}{0.05916}=4$. Therefore K = 10^4, not the logarithm value 4 itself.", sectionId: "equilibrium-gibbs-cell", source: { document: "quick-revision", page: 65 }, cognitive: "application" },
    { id: "note-electrochemistry-012", text: "A cell reaction transfers two electrons and has emf +0.800 V at the conditions considered. Using F = 96500 C mol<sup>-1</sup>, what is its reaction Gibbs energy?", options: [{ key: "a", text: "-154.4 kJ mol<sup>-1</sup>" }, { key: "b", text: "+154.4 kJ mol<sup>-1</sup>" }, { key: "c", text: "-77.2 kJ mol<sup>-1</sup>" }, { key: "d", text: "+77.2 kJ mol<sup>-1</sup>" }], answer: "a", explanation: "Use $\\Delta_rG=-nFE=-2\\times96500\\times0.800=-154400$ J/mol, or -154.4 kJ/mol. A positive emf supplies useful electrical work and corresponds to a negative Gibbs energy change.", sectionId: "equilibrium-gibbs-cell", source: { document: "quick-revision", page: 65 }, cognitive: "application" },
    { id: "note-electrochemistry-013", text: "A solution has conductivity 0.012 S cm<sup>-1</sup> and molarity 0.10 mol L<sup>-1</sup>. What is its molar conductivity?", options: [{ key: "a", text: "12 S cm<sup>2</sup> mol<sup>-1</sup>" }, { key: "b", text: "120 S cm<sup>2</sup> mol<sup>-1</sup>" }, { key: "c", text: "1.2 S cm<sup>2</sup> mol<sup>-1</sup>" }, { key: "d", text: "1200 S cm<sup>2</sup> mol<sup>-1</sup>" }], answer: "b", explanation: "With these centimeter-liter units, $\\Lambda_m=\\frac{1000\\kappa}{M}=\\frac{1000\\times0.012}{0.10}=120$ S cm^2/mol. Omitting the conversion factor or multiplying by molarity gives the wrong quantity.", sectionId: "conductivity-definitions", source: { document: "quick-revision", page: 65 }, cognitive: "application" },
    { id: "note-electrochemistry-014", text: "A solution has conductivity 0.010 S cm<sup>-1</sup> and normality 0.20 equivalents L<sup>-1</sup>. What is its equivalent conductivity?", options: [{ key: "a", text: "2 S cm<sup>2</sup> equivalent<sup>-1</sup>" }, { key: "b", text: "20 S cm<sup>2</sup> equivalent<sup>-1</sup>" }, { key: "c", text: "100 S cm<sup>2</sup> equivalent<sup>-1</sup>" }, { key: "d", text: "50 S cm<sup>2</sup> equivalent<sup>-1</sup>" }], answer: "d", explanation: "Normalize by the given equivalent concentration: $\\Lambda_{eq}=\\frac{1000\\times0.010}{0.20}=50$ S cm^2/equivalent. Normality, not an unrelated molarity, belongs in this formula.", sectionId: "conductivity-definitions", source: { document: "quick-revision", page: 65 }, cognitive: "application" },
    { id: "note-electrochemistry-015", text: "An electrolyte has molar conductivity 150 S cm<sup>2</sup> mol<sup>-1</sup> and a specified equivalent factor z = 3. What is its equivalent conductivity?", options: [{ key: "a", text: "50 S cm<sup>2</sup> equivalent<sup>-1</sup>" }, { key: "b", text: "150 S cm<sup>2</sup> equivalent<sup>-1</sup>" }, { key: "c", text: "450 S cm<sup>2</sup> equivalent<sup>-1</sup>" }, { key: "d", text: "25 S cm<sup>2</sup> equivalent<sup>-1</sup>" }], answer: "a", explanation: "The correct relation is Lambda eq = Lambda m/z. Thus 150/3 = 50 S cm^2/equivalent. No extra molarity factor remains, because molarity is already included in the definition of molar conductivity.", sectionId: "molar-equivalent-relation", source: { document: "quick-revision", page: 65 }, cognitive: "application" },
    { id: "note-electrochemistry-016", text: "A fixed amount of an already dissociated strong electrolyte is diluted at constant temperature. Which description is ordinarily correct?", options: [{ key: "a", text: "Its total ion count and specific conductivity both rise." }, { key: "b", text: "Its total ion count falls while specific conductivity rises." }, { key: "c", text: "Its ion concentration falls while molar conductivity rises." }, { key: "d", text: "Its ion concentration rises while molar conductivity falls." }], answer: "c", explanation: "Dilution reduces ions per unit volume, so bulk conductivity usually falls. The total ions from a fixed fully dissociated amount remain essentially unchanged, while reduced interionic hindrance increases conductivity per mole.", sectionId: "conductivity-dilution", source: { document: "quick-revision", page: 65 }, cognitive: "understanding" },
    { id: "note-electrochemistry-017", text: "With suitable inert electrodes, how do the cathode products differ between molten NaCl and aqueous NaCl?", options: [{ key: "a", text: "Molten gives H<sub>2</sub>; aqueous gives Na." }, { key: "b", text: "Molten gives Cl<sub>2</sub>; aqueous gives H<sub>2</sub>." }, { key: "c", text: "Molten gives Na; aqueous gives H<sub>2</sub>." }, { key: "d", text: "Molten gives Na; aqueous gives Cl<sub>2</sub>." }], answer: "c", explanation: "In molten NaCl, Na+ is reduced to sodium because water is absent. In the aqueous solution, reduction of water produces hydrogen instead. Chlorine, when evolved, is an anode oxidation product rather than a cathode product.", sectionId: "electrolysis-products", source: { document: "quick-revision", page: 65 }, cognitive: "understanding" },
    { id: "note-electrochemistry-018", text: "Dilute sulfuric acid is electrolyzed using inert electrodes without competing electrode reactions. Which gases are expected at cathode and anode, respectively?", options: [{ key: "a", text: "H<sub>2</sub> and O<sub>2</sub>" }, { key: "b", text: "O<sub>2</sub> and H<sub>2</sub>" }, { key: "c", text: "H<sub>2</sub> and SO<sub>2</sub>" }, { key: "d", text: "SO<sub>2</sub> and O<sub>2</sub>" }], answer: "a", explanation: "Dilute sulfuric acid provides an ion-conducting medium while water is electrolyzed. Reduction yields hydrogen at the cathode and oxidation yields oxygen at the inert anode under the stated ordinary conditions.", sectionId: "electrolysis-products", source: { document: "quick-revision", page: 65 }, cognitive: "recall" },
    { id: "note-electrochemistry-019", text: "One faraday passes through CuSO<sub>4</sub> solution with 100% copper-deposition efficiency. Using copper molar mass 63.5 g mol<sup>-1</sup>, what copper mass is deposited?", options: [{ key: "a", text: "0.50 g" }, { key: "b", text: "63.5 g" }, { key: "c", text: "127 g" }, { key: "d", text: "31.75 g" }], answer: "d", explanation: "One faraday is one mole of electrons. Each Cu2+ needs two electrons, so it deposits 0.5 mol of copper. The mass is $0.5\\times63.5=31.75$ g; 'half a gram atom' is not half a gram.", sectionId: "faraday-copper-deposition", source: { document: "quick-revision", page: 65 }, cognitive: "application" },
    { id: "note-electrochemistry-020", text: "A current of 2.00 A passes through CuSO<sub>4</sub> for 965 s with 100% copper-deposition efficiency. Use F = 96500 C mol<sup>-1</sup> and copper molar mass 63.5 g mol<sup>-1</sup>. What mass is deposited?", options: [{ key: "a", text: "1.270 g" }, { key: "b", text: "0.635 g" }, { key: "c", text: "0.318 g" }, { key: "d", text: "6.350 g" }], answer: "b", explanation: "Charge is Q = It = 2.00 times 965 = 1930 C, corresponding to 0.0200 mol electrons. Copper requires two electrons per atom, so 0.0100 mol is deposited, with mass $0.0100\\times63.5=0.635$ g.", sectionId: "faraday-copper-deposition", source: { document: "quick-revision", page: 65 }, cognitive: "application" }
  ]
};