window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["endocrine"] = {
  id: "endocrine",
  subject: "Zoology",
  title: "Endocrine system",
  sections: [
    {
      id: "e127-signalling",
      title: "Endocrine coordination and the two signalling diagrams",
      sources: [{ document: "biology", page: 127 }],
      html: "<p>The endocrine system maintains homeostasis through hormones and works closely with the nervous system. A hormone is a signalling molecule or chemical messenger, called a primary or first messenger when contrasted with intracellular second messengers. Only cells with appropriate receptors and signalling machinery respond to it.</p><p>The neural diagram labels stimulus, neuron, neurotransmitter, receptor and target cell. It depicts a relatively rapid, short-term response across a local synapse. The endocrine diagram labels stimulus, endocrine cell, hormone, blood vessel, receptor and a more distant target cell; it depicts a slower, longer-lasting response. A nearby target receives a paracrine signal without requiring delivery through the general circulation.</p><p><strong>Source qualification:</strong> Speed and duration are tendencies, not absolute definitions. Circulating adrenaline can act rapidly, and neural activity can produce long-term changes. Endocrine communication is defined by secretion into internal fluid and transport to targets, not by a mandatory long distance or slow response.</p><table><thead><tr><th>Source comparison</th><th>Checked distinction</th></tr></thead><tbody><tr><td>Exocrine: ducted</td><td>Secretions pass through ducts to an epithelial surface or lumen. Examples include digestive enzymes, mucus and sweat; not every exocrine product is an enzyme.</td></tr><tr><td>Endocrine: ductless</td><td>Hormones enter interstitial fluid and blood rather than an excretory duct.</td></tr><tr><td>Exocrine near, endocrine far</td><td>The source uses this as a common pattern, not the diagnostic criterion. A duct can carry a secretion some distance and endocrine targets may be close.</td></tr></tbody></table>"
    },
    {
      id: "e127-chemical-classes",
      title: "Hormone chemistry, transport and receptor location",
      sources: [{ document: "biology", page: 127 }, { document: "quick-revision", page: 148 }],
      html: "<table><thead><tr><th>Class</th><th>Source examples and properties</th></tr></thead><tbody><tr><td>Amino-acid derivatives or amines</td><td>Dopamine, adrenaline, noradrenaline and thyroxine; the source mnemonic DANT preserves these four examples. Amines are derived from amino acids but are not themselves proteins.</td></tr><tr><td>Peptide/protein hormones</td><td>Many pituitary and pancreatic hormones, parathyroid hormone or Collip's hormone, calcitonin and MSH. The source cue PAPi CM groups Pancreatic, Parathyroid, Pituitary, Calcitonin and MSH.</td></tr><tr><td>Lipid-derived steroid hormones</td><td>Sex steroids and adrenal cortical steroids such as cortisol and aldosterone. The source cue joins Sex with Cortical hormones; steroids derive from cholesterol, not from peptide chains.</td></tr></tbody></table><p>Most peptide hormones and catecholamines circulate largely dissolved in plasma and bind cell-surface receptors. Steroids generally circulate substantially bound to carrier proteins and act through intracellular receptors, in cytoplasm and/or nucleus.</p><p><strong>Source correction:</strong> The source places all amines with freely circulating, membrane-receptor hormones. Thyroid hormones are the major exception: although amino-acid derivatives, they circulate mainly protein-bound and act chiefly through intracellular nuclear receptors. Solubility and receptor location therefore cannot be inferred from the word amine alone. Some hormones also have additional nonclassical signalling actions.</p><p>Proinsulin is a precursor of insulin. Processing removes the connecting C-peptide and yields mature insulin with A and B chains joined by disulfide bonds. The printed arrow 'peptide is removed' should be read specifically as C-peptide processing, not destruction of insulin's active chains.</p>"
    },
    {
      id: "e127-enzymes-and-interactions",
      title: "Enzymes, hormones, synergism and permissive action",
      sources: [{ document: "biology", page: 127 }],
      html: "<p>The handwritten comparison calls enzymes protein, reusable, locally acting and able to leave the body; it calls hormones protein or fat, not reusable, blood-borne and retained in the body. Its similarity list says both are synthesized in the body, easily soluble, not stored and highly specific.</p><p><strong>Source corrections:</strong> These contrasts need substantial qualification. Most enzymes are proteins, but catalytic RNA or ribozymes exist. Enzymes catalyse reactions without being consumed in each catalytic cycle; many work inside cells and never leave the body. Hormones convey regulatory information through receptors rather than necessarily catalysing reactions. They may be peptides, amines, steroids or other lipid-derived signals, and their metabolites are cleared or excreted. Solubility varies; steroid and thyroid hormones require carrier proteins to varying degrees. Peptide hormones can be stored in secretory vesicles and thyroid hormone precursors in extracellular colloid. Thus 'all protein', 'all easily soluble', 'not stored' and 'enzymes exit, hormones stay' are not universal rules. Biological specificity applies to enzyme-substrate and hormone-receptor relationships but does not make either relationship absolutely exclusive.</p><ul><li>Synergism: two hormones cooperate in producing a response. The source uses LH and FSH in reproductive function.</li><li>Permissive action: one hormone enables or enhances the full response to another. The source uses cortisol with glucagon in metabolic regulation. This need not mean absolutely zero response if either is absent.</li><li>Functional antagonism: hormones can produce opposing effects on a regulated quantity, such as insulin versus glucagon on blood glucose, without directly blocking one another's receptor.</li></ul>"
    },
    {
      id: "e127-functional-types",
      title: "Functional categories and every source example",
      sources: [{ document: "biology", page: 127 }],
      html: "<table><thead><tr><th>Category</th><th>Meaning and source example</th></tr></thead><tbody><tr><td>Autocrine</td><td>A signal acts on the cell that releases it. Platelet-activating factor is the source example; the same mediator can also act on neighbouring cells.</td></tr><tr><td>Local or paracrine</td><td>A mediator acts near its site of release. The source lists acetylcholine, histamine and serotonin. Acetylcholine is usually discussed as a synaptic neurotransmitter; local mediators are not all classical blood-borne endocrine hormones.</td></tr><tr><td>Lipolytic</td><td>Promotes release of fatty acids from stored fat. Epinephrine and glucagon are the listed examples. Epinephrine is an important human adipose lipolytic signal; glucagon's principal physiological human action is hepatic, and its direct adipose effect is context-dependent.</td></tr><tr><td>Prohormone</td><td>A precursor processed into an active hormone; proinsulin is the example. 'Inactive' is introductory shorthand because some precursors retain limited activity.</td></tr><tr><td>Immunoregulatory</td><td>Alters immune responses. The source broadly lists hypothalamic and adrenal hormones; cortisol is an important example, but not every hormone from either source has one identical immune action.</td></tr><tr><td>Tropic</td><td>Acts on another endocrine gland to regulate its hormone production, exemplified by several anterior pituitary hormones.</td></tr><tr><td>Releasing</td><td>A hypothalamic signal stimulates pituitary secretion, often of a tropic hormone. The hypothalamus also supplies inhibitory signals, so not every hypothalamic hormone is releasing.</td></tr></tbody></table>"
    },
    {
      id: "e127-local-mediators-history",
      title: "Prostaglandins, pheromones and historical notes",
      sources: [{ document: "biology", page: 127 }],
      html: "<p>The source uses 'parahormones' for hormone-like substances not secreted by a classical endocrine gland. This is older descriptive terminology, not a single modern chemical class.</p><ul><li>Prostaglandins are local lipid mediators found in semen and produced in many tissues, including seminal-vesicle-associated secretions. The source names linoleic and arachidonic acids and calls prostaglandins unsaturated fatty acids. More precisely, prostaglandins are oxygenated derivatives of fatty-acid precursors, particularly arachidonic acid; linoleic acid can contribute to precursor metabolism. Prostaglandins are not simply unchanged linoleic or arachidonic acid.</li><li>Pheromones are chemical signals released outside the body that influence other members of the same species. The source also uses ectohormone and semiochemical; semiochemical is a broader signalling category.</li><li>The examples are ant trail formation, female moth signals attracting males, queen-bee signals influencing workers, dog territorial scent marking and bee alarm signals recruiting defensive behaviour. These convey different messages rather than acting as blood-borne human hormones.</li></ul><p>The historical bullets name secretin from duodenum as the first hormone discovered, insulin as the first hormone synthesized in a laboratory, and Addison's disease as the first endocrine disease described. Secretin's identification was foundational to the hormone concept, and Addison's work established adrenal insufficiency as a recognizable disease.</p><p><strong>Source qualification:</strong> 'First hormone synthesized' needs a category: insulin is an early landmark in protein-hormone synthesis, but oxytocin had already been synthesized as a peptide hormone. The source supplies no date or category to make its insulin priority claim uniquely interpretable. Historical priority labels are retained as source claims, not new scored facts.</p>"
    },
    {
      id: "e128-feedback",
      title: "Negative and positive feedback",
      sources: [{ document: "biology", page: 128 }, { document: "biology", page: 129 }, { document: "quick-revision", page: 149 }],
      html: "<p>Negative feedback counteracts the disturbance that initiated a response and is the common self-limiting form of endocrine regulation. The source says a hormone inhibits its further secretion after a limit; the actual feedback signal can instead be a regulated metabolite or a downstream hormone.</p><ul><li>Insulin example: rising glucose promotes insulin secretion, insulin action lowers glucose, and the reduced glucose stimulus limits further secretion.</li><li>Thyroid axis: hypothalamic TRH promotes pituitary TSH; TSH stimulates thyroid T<sub>3</sub>/T<sub>4</sub>; thyroid hormones feed back to reduce hypothalamic and pituitary drive.</li><li>Adrenal axis: CRH promotes ACTH, which promotes cortisol; cortisol inhibits CRH and ACTH through negative feedback. Short-loop feedback can also occur.</li></ul><p><strong>Source correction:</strong> The printed example 'secretion of CRH in response to ACTH' does not adequately state a negative-feedback relationship. Increased downstream output must reduce, not automatically promote, upstream drive in the negative limb.</p><p>Positive feedback reinforces a response directly or indirectly and is less common. Sustained high estradiol before ovulation can trigger the LH surge. During parturition, cervical stretch promotes oxytocin release, uterine contractions increase stretch, and the cycle amplifies until delivery removes the initiating condition. Positive feedback is not unrestricted hormone production without a terminating event.</p>"
    },
    {
      id: "e128-origins",
      title: "Gland origins and the complete body map",
      sources: [{ document: "biology", page: 128 }],
      html: "<table><thead><tr><th>Source embryological group</th><th>Named structures</th></tr></thead><tbody><tr><td>Ectodermal</td><td>Pituitary, pineal and adrenal medulla. Anterior pituitary derives from oral ectoderm, posterior pituitary and pineal from neuroectoderm, adrenal medulla from neural crest.</td></tr><tr><td>Mesodermal</td><td>Gonadal somatic tissues, kidneys and adrenal cortex.</td></tr><tr><td>Endodermal</td><td>Thyroid follicular epithelium, parathyroid epithelium, thymic epithelium and pancreatic epithelium.</td></tr></tbody></table><p><strong>Source qualification:</strong> These labels chiefly describe the gland's characteristic functional epithelium or parenchyma, not every vessel, stromal cell or immigrant immune cell. The source's respiratory/digestive-system cues for endodermal organs are memory aids. Thyroid cell-lineage details and gonadal germ cells should not be reduced to the same blanket label as surrounding tissue.</p><p>The head-and-neck map labels hypothalamus, pineal gland, pituitary and thyroid. The body map labels parathyroids, thyroid right/left regions, thymus, heart, digestive tract, pancreas, kidneys, adrenal cortex/medulla, adipose tissue and gonads.</p><ul><li>Parathyroid: parathormone. Thyroid: thyroxine T<sub>4</sub>, triiodothyronine T<sub>3</sub> and calcitonin.</li><li>Thymus: thymosin and age-related involution. Heart: natriuretic peptides associated with lower blood pressure.</li><li>Digestive tract: gastrin, somatostatin, secretin, CCK, GIP and VIP.</li><li>Pancreas: insulin and glucagon. Kidney: erythropoietin. Adipose tissue: leptin, a signal of energy stores involved in appetite regulation.</li><li>Adrenal medulla: adrenaline/epinephrine and noradrenaline/norepinephrine. Cortex: cortisol in stress regulation and aldosterone in Na<sup>+</sup>/K<sup>+</sup> balance.</li><li>Ovarian hormones: estrogen, progesterone and inhibin. Testicular hormones: androgens, including testosterone, and inhibin.</li></ul><p>The right half of the source page is unused; no missing gland content is inferred from that blank space.</p>"
    },
    {
      id: "e128-hypothalamic-map",
      title: "Hypothalamic hormones and pituitary targets",
      sources: [{ document: "biology", page: 128 }, { document: "biology", page: 129 }],
      html: "<table><thead><tr><th>Hypothalamic label</th><th>Principal relation</th></tr></thead><tbody><tr><td>Thyrotropin-releasing hormone, TRH</td><td>Promotes TSH release; can also stimulate prolactin.</td></tr><tr><td>Dopamine</td><td>Principal tonic inhibitor of prolactin secretion.</td></tr><tr><td>Growth hormone-releasing hormone, GHRH</td><td>Promotes growth hormone secretion.</td></tr><tr><td>Somatostatin</td><td>Inhibits growth hormone and TSH secretion.</td></tr><tr><td>Gonadotropin-releasing hormone, GnRH</td><td>Pulsatile signalling promotes LH and FSH secretion.</td></tr><tr><td>Corticotropin-releasing hormone, CRH</td><td>Promotes ACTH secretion.</td></tr><tr><td>Oxytocin and vasopressin</td><td>Synthesized in hypothalamic neurons, carried along their axons and released from posterior pituitary terminals.</td></tr></tbody></table><p>The map explicitly separates anterior pituitary growth hormone, TSH, ACTH, FSH, LH and prolactin; intermediate-region MSH; and posterior-pituitary oxytocin/ADH storage. Its two posterior entries 'vasopressin' and 'antidiuretic hormone stored' denote the same hormone, not two different hormones.</p>"
    },
    {
      id: "e129-pituitary-anatomy",
      title: "Pituitary anatomy and all diagram labels",
      sources: [{ document: "biology", page: 129 }, { document: "quick-revision", page: 148 }],
      html: "<p>The pituitary or hypophysis cerebri lies in the hypophyseal fossa of the sella turcica of the sphenoid bone and connects with the hypothalamus through the infundibulum or pituitary stalk. The printed 'hypophyseal cerebrum' is a naming error. Its status as a master gland reflects regulation of several other endocrine glands, not independent control of every hormone.</p><ul><li>Adenohypophysis: glandular anterior region, including pars distalis, pars intermedia and pars tuberalis.</li><li>Neurohypophysis: neural posterior region with hypothalamic axons and supporting cells.</li><li>The upper diagram labels hypothalamic neurons that synthesize ADH and oxytocin, optic chiasm, infundibulum, hypothalamo-hypophyseal tract, axon terminals storing the two peptides, neurohypophysis and adenohypophyseal secreting cells.</li><li>The lower diagram labels optic chiasm, hypothalamus, pituitary stalk, anterior and posterior lobes, pars tuberalis around the stalk, pars intermedia between regions and pars distalis forming most of the anterior lobe.</li></ul><p><strong>Source correction:</strong> The printed 'smallest endocrine gland' is not a reliable universal description of the pituitary; individual parathyroid glands and the pineal can be smaller. The posterior lobe stores and releases hypothalamic hormones rather than being their chief site of synthesis.</p>"
    },
    {
      id: "e129-anterior-pituitary",
      title: "Six anterior pituitary hormones and MSH",
      sources: [{ document: "biology", page: 129 }, { document: "biology", page: 128 }, { document: "quick-revision", page: 148 }],
      html: "<p>The mnemonic FLAT PiG names FSH, LH, ACTH, TSH, prolactin and growth hormone, the six major anterior-pituitary hormones listed in the sources.</p><table><thead><tr><th>Hormone</th><th>Functions and source names</th></tr></thead><tbody><tr><td>GH, somatotropin</td><td>Promotes somatic growth directly and through IGF signalling. Normal thyroid status supports growth responses; the source says GH works in the presence of thyroxine.</td></tr><tr><td>FSH</td><td>Supports Sertoli-cell function and spermatogenesis in males; promotes ovarian follicular growth and granulosa-cell estrogen production in females. The source describes maturation towards a Graafian follicle.</td></tr><tr><td>LH</td><td>Promotes ovulation and corpus-luteum formation in females; supports ovarian steroid production. In males, interstitial-cell stimulating hormone or ICSH is an older name for LH, which stimulates Leydig-cell testosterone production.</td></tr><tr><td>Prolactin</td><td>Promotes milk production. Source names include mammotropic/mammotrophic hormone, MTH, luteotropic hormone, LTH, lactogenic hormone and 'hormone of maternity'. Luteotropic actions differ between species.</td></tr><tr><td>TSH</td><td>Stimulates thyroid follicular activity and T<sub>3</sub>/T<sub>4</sub> synthesis/release, subject to thyroid-hormone feedback.</td></tr><tr><td>ACTH</td><td>Stimulates adrenal cortical glucocorticoid production, particularly cortisol, and supports adrenal androgen production.</td></tr></tbody></table><p><strong>Source corrections:</strong> 'Luteotropin' should not blur LH with the older LTH name used for prolactin. LH does not directly prepare the endometrium independently of ovarian steroids. ACTH is not the principal long-term regulator of aldosterone: renin-angiotensin signalling and plasma K<sup>+</sup> are central controls, despite aldosterone appearing under the source's ACTH arrow.</p><p>The intermediate lobe or pars intermedia is associated with melanocyte-stimulating hormone, MSH, which promotes melanogenic signalling. The source says MSH is a vestigial hormone. More precisely, the adult human pars intermedia is rudimentary, while melanocortin peptides and receptors remain functional; a rudimentary lobe does not make all MSH activity biologically absent.</p>"
    },
    {
      id: "e129-gh-prolactin-disorders",
      title: "Growth hormone and prolactin disorders",
      sources: [{ document: "biology", page: 129 }, { document: "quick-revision", page: 148 }],
      html: "<table><thead><tr><th>Source GH table</th><th>Checked interpretation</th></tr></thead><tbody><tr><td>Deficiency in childhood: dwarfism</td><td>GH deficiency can cause proportionate growth failure. Short stature has many other causes, so the historical term does not diagnose GH deficiency by itself.</td></tr><tr><td>Excess in childhood: gigantism</td><td>Excess GH before epiphyseal fusion can cause excessive longitudinal skeletal growth.</td></tr><tr><td>Excess in adulthood: acromegaly</td><td>After epiphyseal fusion, enlargement chiefly affects hands, feet, jaw and soft tissues rather than producing the same increase in long-bone length. The source's coarse-appearance comparison refers to these features and is not a diagnostic criterion.</td></tr><tr><td>Deficiency in adulthood: Simmonds disease</td><td><strong>Source correction:</strong> Simmonds disease is a historical description of severe hypopituitarism/pituitary cachexia, not simply isolated adult GH deficiency.</td></tr></tbody></table><p>The prolactin excess list gives female amenorrhoea and galactorrhoea, and male infertility, reduced sexual desire and gynaecomastia. Hyperprolactinaemia can suppress reproductive-axis function and cause hypogonadism; galactorrhoea is inappropriate milk secretion, not necessarily normal excess nursing milk. Gynaecomastia has multiple causes and is not a specific direct prolactin effect.</p><p>Physiological lactational amenorrhoea during breastfeeding is distinct from a claim that every absence of menstruation indicates a prolactinoma. Prolactin promotes milk synthesis; oxytocin promotes milk ejection, so production and release from the breast are different processes.</p>"
    },
    {
      id: "e129-posterior-pituitary",
      title: "Oxytocin, vasopressin and water balance",
      sources: [{ document: "biology", page: 129 }, { document: "quick-revision", page: 148 }],
      html: "<p>Oxytocin and ADH are neuropeptides synthesized by hypothalamic neurons, transported along the hypothalamo-hypophyseal tract, stored in axon terminals and released into blood from the neurohypophysis.</p><ul><li>Oxytocin promotes milk ejection by contraction of mammary myoepithelial cells. It also stimulates uterine myometrial smooth muscle and contributes to parturition.</li><li>The source nicknames oxytocin birth, love, cuddle and abortion hormone. These labels must not substitute for its receptor-mediated physiology or imply a universal behavioural effect. Its clinical use in labour requires assessment and monitoring; inability to deliver is not by itself a reason to administer it without determining the cause.</li><li>ADH, vasopressin, and the historical preparation name Pitressin are linked in the printed source. ADH increases regulated or facultative water reabsorption, principally by increasing water permeability in the late distal nephron and collecting ducts.</li><li>Water then moves passively by osmosis when an appropriate medullary osmotic gradient is present; ADH does not actively pump water. Urine becomes more concentrated and its volume generally decreases.</li><li>At sufficient concentrations vasopressin also contracts vascular smooth muscle, including cutaneous and splanchnic vessels, and can raise blood pressure.</li><li>Inadequate ADH secretion causes central diabetes insipidus, with large volumes of dilute urine. Renal resistance to ADH causes nephrogenic diabetes insipidus, so not every case is hormone deficiency.</li><li>The source notes alcohol's diuretic action. Alcohol can reduce ADH release and increase water loss; the size of the response varies with dose, hydration and circumstances.</li></ul><p><strong>Source distinction:</strong> Diabetes insipidus involves impaired water conservation; diabetes mellitus involves hyperglycaemia from inadequate insulin secretion and/or action. Polyuria alone does not establish which disorder is present.</p>"
    },
    {
      id: "e130-thyroid-structure",
      title: "Thyroid follicles, colloid and hormone output",
      sources: [{ document: "biology", page: 130 }, { document: "quick-revision", page: 148 }],
      html: "<p>The thyroid has right and left lobes joined by an isthmus. The source marks its approximate adult neck extent C5-T1. This is a positional reference rather than an invariant boundary in every neck or swallowing position. It is often called the largest purely endocrine gland; mixed-function and diffuse endocrine tissues make an unqualified largest-gland claim misleading.</p><p>The microscopic diagram labels follicular cells around a colloid-filled lumen, parafollicular or C cells, and fenestrated capillaries. Follicular or principal cells make iodinated thyroid hormones. Thyroglobulin-containing colloid stores hormone precursor extracellularly within follicles; this is the unusual extracellular storage emphasized by the source, not a duct emptying outside the body.</p><table><thead><tr><th>Cell/output</th><th>Source reference</th></tr></thead><tbody><tr><td>Follicular cells: T<sub>3</sub></td><td>Triiodothyronine, described as the more active hormone; roughly 10% of direct secretion in the source's simplified ratio.</td></tr><tr><td>Follicular cells: T<sub>4</sub></td><td>Thyroxine; roughly 90% of direct secretion in that ratio. These percentages are approximate, not a serum concentration ratio; much circulating T<sub>3</sub> is formed by conversion of T<sub>4</sub> in tissues.</td></tr><tr><td>Parafollicular C cells</td><td>Calcitonin, a peptide distinct from the iodine-containing follicular hormones.</td></tr></tbody></table><p>The thyroid concentrates iodine, which is required for T<sub>3</sub>/T<sub>4</sub> production. Seafood is a rich dietary source; the printed 'maximum iodine in seafood' is not a fixed ranking of every food sample. Iodized salt is an important dietary prevention measure where intake is inadequate.</p>"
    },
    {
      id: "e130-thyroid-functions-disorders",
      title: "Thyroid functions, disease table and tadpole example",
      sources: [{ document: "biology", page: 130 }, { document: "quick-revision", page: 148 }, { document: "quick-revision", page: 149 }],
      html: "<p>T<sub>3</sub> and T<sub>4</sub> regulate basal metabolic rate, energy turnover, growth and development. The source lists ATP synthesis; thyroid hormones regulate metabolic machinery and ATP turnover rather than acting as ATP-synthesizing enzymes. Normal thyroid hormone is particularly important for childhood neural development and for normal growth responses alongside GH.</p><table><thead><tr><th>Source disease entry</th><th>Meaning and correction</th></tr></thead><tbody><tr><td>Iodine deficiency: simple goitre</td><td>Reduced hormone synthesis can increase TSH drive and enlarge the thyroid. Goitre means gland enlargement and is not synonymous with a single hormonal state.</td></tr><tr><td>Childhood deficiency: cretinism</td><td>A historical term for severe congenital/early thyroid-hormone deficiency with impaired growth and neurodevelopment. Congenital hypothyroidism is the preferred clinical terminology; consequences depend on timing and treatment.</td></tr><tr><td>Adult deficiency: myxoedema or Gull's disease</td><td>Severe hypothyroidism can cause slowing and characteristic tissue changes. The source's 'sluggish face' is one nonspecific appearance description.</td></tr><tr><td>Hashimoto disease</td><td>Autoimmune thyroiditis, commonly leading to hypothyroidism. The source's 'suicide of thyroid' and 'first autoimmune disease' are historical/mnemonic phrases, not literal mechanisms or a precise priority claim.</td></tr><tr><td>Excess: exophthalmic goitre, Graves or Basedow disease</td><td>Graves disease is an autoimmune cause of hyperthyroidism, often with goitre and sometimes thyroid eye disease. Thyrotoxicosis means effects of excess thyroid hormone and can have other causes.</td></tr></tbody></table><p><strong>Source correction:</strong> Graves-related bulging eyes result from orbital tissue inflammation and expansion, not simply enlarged eyeballs, and do not occur in every cause of thyroid-hormone excess.</p><p>Thyroid hormone drives tadpole metamorphosis. The source draws tadpole to frog with T<sub>4</sub> or I<sub>2</sub>, and states that removal of thyroid leaves a persistent or giant tadpole under laboratory maintenance. Iodine supports thyroid-hormone synthesis only when a functioning thyroid pathway is present; it is not itself a substitute receptor hormone. Thyroid removal blocks normal metamorphic signalling, whereas administering thyroid hormone can bypass the absent gland. 'Giant' reflects prolonged larval growth under suitable conditions, not an inevitable size in every experiment.</p>"
    },
    {
      id: "e130-calcium-regulation",
      title: "Parathyroids, calcitonin and the corrected calcium table",
      sources: [{ document: "biology", page: 130 }, { document: "quick-revision", page: 148 }],
      html: "<p>Humans usually have four parathyroid glands on the posterior aspect of the thyroid, although number and position can vary. The source says parathyroid glands are absent in fish, a comparative distinction from the discrete tetrapod glands, not absence of all calcium-regulating hormones in fishes.</p><table><thead><tr><th>Parathyroid cell</th><th>Readable comparison</th></tr></thead><tbody><tr><td>Chief cells</td><td>Small, numerous and commonly cuboidal; the principal PTH-secreting cells. The source calls them non-granular, which should not be interpreted as absence of secretory granules at the ultrastructural level.</td></tr><tr><td>Oxyphil cells</td><td>Larger, fewer, polygonal and granular/eosinophilic, with abundant mitochondria. The source calls them functionless; their biology is not adequately captured by a universal no-function claim.</td></tr></tbody></table><p>Parathyroid hormone, parathormone or the historical Collip's hormone raises blood Ca<sup>2+</sup> through coordinated bone, renal and vitamin-D-related effects. It promotes renal calcium conservation and formation of calcitriol, which supports intestinal calcium absorption.</p><p><strong>Source correction:</strong> The source says PTH increases both calcium and phosphate in blood. Bone resorption can release both, but PTH increases renal phosphate excretion; with functioning kidneys its usual net effect is higher calcium and lower serum phosphate. Calcitonin generally opposes bone resorption and can lower calcium/phosphate, but its role in normal adult human calcium homeostasis is less central than the simple equal-antagonist diagram suggests.</p><table><thead><tr><th>Source excess/deficiency entry</th><th>Checked teaching point</th></tr></thead><tbody><tr><td>PTH deficiency: tetany</td><td>Hypocalcaemia increases neuromuscular excitability and can cause painful spasms; this agrees with the printed muscular-spasm entry.</td></tr><tr><td>PTH excess: osteoporosis, hypercalcaemia, hypercalciuria and renal calculi</td><td>Excessive PTH can cause bone loss and increased stone risk. High filtered calcium can produce hypercalciuria despite PTH's renal calcium-conserving action.</td></tr><tr><td>PTH excess: childhood rickets; adult osteomalacia</td><td>These source labels are not a general primary-PTH-excess diagnosis. Rickets/osteomalacia concern defective mineralization, often related to vitamin D, calcium or phosphate problems; secondary PTH elevation may coexist.</td></tr><tr><td>Calcitonin excess: tetany</td><td>This is not a standard simple human syndrome assigning tetany to calcitonin excess. Tetany must be related to actual ionized-calcium physiology.</td></tr><tr><td>Calcitonin deficiency: childhood rickets; adult osteoporosis/osteomalacia</td><td>These are not established inevitable deficiency syndromes of calcitonin. Osteoporosis is loss of bone quantity; osteomalacia/rickets are mineralization disorders, not interchangeable names.</td></tr></tbody></table>"
    },
    {
      id: "e130-pineal",
      title: "Pineal gland, melatonin, serotonin and historical claims",
      sources: [{ document: "biology", page: 130 }, { document: "quick-revision", page: 149 }],
      html: "<p>The pineal gland is the epiphysis cerebri, not a separate gland located 'above epiphysis' as the printed wording implies. It lies in the epithalamic region. The source terms third eye and biological clock refer to comparative photosensory associations and rhythmic regulation; the human pineal is not a functioning third visual eye.</p><ul><li>Melatonin participates in circadian and sleep-wake timing. The hypothalamic suprachiasmatic nucleus is the principal circadian pacemaker; pineal output is one important downstream rhythmic signal.</li><li>The source links melatonin to puberty timing and antagonism of FSH/LH. Pineal and reproductive axes interact, with marked species and seasonal differences; melatonin is not a simple direct universal antagonist of both gonadotropin receptors.</li><li>The source calls melatonin an antagonist of MSH that inhibits melanocyte melanin production. Pigmentation effects in nonhuman systems should not be promoted to a universal human skin-colour law.</li><li>Brain sand or corpora arenacea consists of calcified concretions, often more conspicuous with age. The source's calcium-crystal label is retained; calcification does not mean the entire gland has degenerated and ceased function.</li></ul><p>The serotonin passage calls it an antagonist of histamine and a vasoconstrictor that reduces inflammation. <strong>Source correction:</strong> Serotonin and histamine have distinct receptor systems and diverse tissue-dependent effects. Serotonin can influence vascular tone, platelet function and inflammatory processes, but is not a universal antihistamine or uniformly anti-inflammatory agent.</p><p>Adrenoglomerulotropin is named as a pineal factor stimulating zona glomerulosa aldosterone secretion. This is a historical proposed factor, not an established principal human aldosterone-control hormone. Current basic physiology emphasizes angiotensin II and potassium. The historical claim is retained for recognition and excluded from new scored questions.</p>"
    },
    {
      id: "e131-adrenal-cortex",
      title: "Adrenal capsule, zones and cortical hormones",
      sources: [{ document: "biology", page: 131 }, { document: "quick-revision", page: 148 }, { document: "quick-revision", page: 149 }],
      html: "<p>The adrenal diagram labels capsule, zona glomerulosa, zona fasciculata, zona reticularis and central medulla. Cortex is mesodermal; medulla is neural-crest derived. The source gives cortex as approximately 80-90% of the gland and medulla as 20%. These are rough proportions, not a requirement that every endpoint of those figures sum to 100; medulla is often described as about 10-20%.</p><p>The cortical mnemonic 4S preserves sugar metabolism, salt retention, sex hormones and source of energy/stress support. The zone order G-F-R from outer to inner pairs with mineralocorticoid, glucocorticoid and sex-steroid production. The printed phrase 'GF Ramri Moj Gar Sala' is a sequence cue for these zone and secretion initials, not an extra physiological claim.</p><table><thead><tr><th>Zone</th><th>Main output and effect</th></tr></thead><tbody><tr><td>Zona glomerulosa</td><td>Mineralocorticoids, chiefly aldosterone. Promotes Na<sup>+</sup> retention and K<sup>+</sup> secretion in the distal nephron; water retention depends on osmotic and permeability conditions.</td></tr><tr><td>Zona fasciculata</td><td>Glucocorticoids, chiefly cortisol. Supports stress responses, fuel mobilization and hepatic glucose production; can oppose insulin's glucose-lowering effects and permit/enhance counter-regulatory responses.</td></tr><tr><td>Zona reticularis</td><td>Adrenal sex steroids, predominantly weak androgens such as DHEA and androstenedione, in both sexes.</td></tr></tbody></table><p><strong>Source corrections:</strong> 'Cortex under pituitary, medulla under ANS' is useful shorthand but incomplete: ACTH is central for cortisol, whereas renin-angiotensin and K<sup>+</sup> dominate aldosterone control. Calling cortisol an agonist of glucagon refers to complementary metabolic effects, not cortisol binding glucagon receptors. The source lists testosterone mainly in men and progesterone/estrogen mainly in women under reticularis; gonads and placenta, not ordinary adrenal reticularis, are their major relevant sources. Adrenal steroid products should not be assigned by a simple male/female split.</p>"
    },
    {
      id: "e131-adrenal-disorders",
      title: "Adrenal disease entries and their limits",
      sources: [{ document: "biology", page: 131 }, { document: "quick-revision", page: 148 }, { document: "quick-revision", page: 149 }],
      html: "<table><thead><tr><th>Disorder</th><th>Hormonal relation and listed features</th></tr></thead><tbody><tr><td>Addison's disease</td><td>Primary adrenal cortical insufficiency, typically involving cortisol deficiency and often aldosterone deficiency. The handwritten bracket correctly groups deficiency of both; the printed mineralocorticoid-only row is incomplete.</td></tr><tr><td>Conn's syndrome</td><td>Primary aldosterone excess, classically an aldosterone-producing adrenal adenoma; excessive renal sodium retention and potassium loss can contribute to hypertension and hypokalaemia.</td></tr><tr><td>Cushing syndrome</td><td>Chronic glucocorticoid excess. Source features: rounded or red moon face, dorsocervical fat accumulation called buffalo hump, and oedema. Endogenous excess and exogenous glucocorticoid exposure can cause the syndrome.</td></tr><tr><td>Virilism/virilization in females</td><td>Excess androgen action can produce virilizing features; an adrenal cause is possible but not the only cause.</td></tr><tr><td>Gynaecomastia in males</td><td>Breast glandular enlargement can reflect an altered estrogen-to-androgen action balance; it is not specific proof of an adrenal estrogen-secreting lesion.</td></tr></tbody></table><p><strong>Source qualification:</strong> Removal or destruction of both adrenal cortices can be fatal without replacement/support because essential glucocorticoid and mineralocorticoid functions are lost. The statement does not mean that every removal of a single adrenal gland is inevitably fatal. Cushing disease is the pituitary ACTH-dependent subtype, whereas Cushing syndrome includes other causes.</p>"
    },
    {
      id: "e131-adrenal-medulla",
      title: "Adrenal medulla, chromaffin cells and catecholamines",
      sources: [{ document: "biology", page: 131 }, { document: "quick-revision", page: 149 }],
      html: "<p>Chromaffin cells of the adrenal medulla are modified sympathetic neuroendocrine cells stimulated by preganglionic sympathetic input. They release mainly epinephrine/adrenaline and norepinephrine/noradrenaline. Dopamine, adrenaline and noradrenaline belong to the catecholamine family, derived from amino-acid metabolism.</p><p>The source names adrenaline emergency hormone and life-saving hormone/drug, and uses 3F for fright or fear, flight and fight. It lists increased heartbeat and blood pressure. Responses depend on receptor distribution and dose: cardiac stimulation, changes in vascular tone and metabolic fuel availability cooperate in the acute stress response; not every vessel constricts identically.</p><p><strong>Source corrections:</strong> The handwritten phrase 'norepinephrine inhibits adrenaline' is false as a general statement. Both are adrenergic agonists, with different receptor profiles and organ effects. The label 'chromaffin cells: camouflage of frog' confuses chromaffin endocrine cells with pigment-containing chromatophores. Similar-sounding cell names do not make the adrenal medulla a skin-colour organ. Clinical emergency use of catecholamines is condition-specific, not an instruction to inject them for any emergency.</p>"
    },
    {
      id: "e131-thymus",
      title: "Thymus, Hassall corpuscles and thymic factors",
      sources: [{ document: "biology", page: 131 }, { document: "biology", page: 128 }, { document: "quick-revision", page: 149 }],
      html: "<p>The thymus is a bilobed lymphoid organ in the anterior superior mediastinal region near the heart and lungs. The source calls it the training school of T lymphocytes, throne/master gland of immunity and clock of ageing. These names emphasize T-cell maturation and age-related involution, not control of every immune function or a literal clock governing whole-body ageing.</p><ul><li>It has an outer cortex and inner medulla. Young T cells acquire immunocompetence and undergo selection within its specialized microenvironment.</li><li>It is prominent and active in the young and becomes less conspicuous with age as functional tissue is increasingly replaced by fat. Glucocorticoids can promote thymic involution, but normal ageing is not caused solely by them.</li><li>Hassall's corpuscles occur in the medulla. They are concentric epithelial-reticular cell structures, often with central keratinization, not phagocytic cells as the printed source says. Macrophages in the thymus are a different population.</li><li>Thymosin is the source's named factor promoting immunocompetence in developing T cells.</li></ul><p>The second factor is written 'Thymin/Thymopoietin' with the claim that it inhibits acetylcholine at nerve endings. Thymopoietin is associated historically with thymic differentiation and experimental neuromuscular effects, but this line is not an adequate statement of a normal general anti-acetylcholine hormone mechanism. The identity intended by 'Thymin' and the conditions of the claimed neuromuscular effect remain unresolved; neither is used for a scored question.</p>"
    },
    {
      id: "e148-pancreas",
      title: "Pancreas: acini, islets and insulin-glucagon pathways",
      sources: [{ document: "quick-revision", page: 148 }, { document: "biology", page: 128 }],
      html: "<p>The pancreas combines an exocrine component, acini secreting digestive juice through ducts, and endocrine islets of Langerhans releasing hormones into blood.</p><table><thead><tr><th>Islet cell</th><th>Hormone and effect</th></tr></thead><tbody><tr><td>Beta cells</td><td>Insulin; the source cue Bin pairs Beta with Insulin. Promotes glucose utilization/storage and suppresses excessive hepatic glucose output.</td></tr><tr><td>Alpha cells</td><td>Glucagon; raises blood glucose chiefly by acting on liver glycogen breakdown and gluconeogenesis.</td></tr><tr><td>Delta cells</td><td>Somatostatin; locally inhibits release of insulin and glucagon and participates in digestive regulation.</td></tr></tbody></table><p>The source's two arrows read glucose to glycogen, glycogenesis, under insulin; and glycogen to glucose, glycogenolysis, under glucagon. These are regulated metabolic pathways, not reactions catalysed directly by the hormone. Liver glucose production is particularly relevant to glucagon; not all tissues export glucose from their glycogen stores.</p><p>Diabetes mellitus involves inadequate insulin secretion and/or inadequate tissue response, leading to hyperglycaemia. Glucose can appear in urine when its filtered load exceeds reabsorptive capacity; glycosuria is not obligatory at every disease stage. The source cue links mellitus with sweet sugar-containing urine. Insulin deficiency alone does not describe all type 2 diabetes.</p><p>Diabetes insipidus instead involves ADH secretion or action and produces dilute polyuria without requiring hyperglycaemia. The source's contrast between insulin and ADH is retained, with that renal-resistance qualification.</p>"
    },
    {
      id: "e132-digestive-hormones",
      title: "Gastric and intestinal endocrine signals",
      sources: [{ document: "biology", page: 132 }, { document: "biology", page: 128 }, { document: "quick-revision", page: 149 }],
      html: "<table><thead><tr><th>Hormone or source term</th><th>Source site, target and qualification</th></tr></thead><tbody><tr><td>Gastrin</td><td>Released from G cells, prominently in the gastric antrum; stimulates gastric secretory activity, especially acid secretion through direct and indirect pathways.</td></tr><tr><td>Secretin</td><td>Released by duodenal/upper-intestinal S cells in response to acid; stimulates pancreatic ductal bicarbonate-rich secretion and biliary bicarbonate/water secretion, and inhibits gastric acid activity.</td></tr><tr><td>Cholecystokinin, CCK</td><td>Promotes gallbladder contraction and pancreatic enzyme secretion. Pancreozymin is the older name for its pancreatic action; it is not an unrelated second hormone.</td></tr><tr><td>Somatostatin</td><td>Produced in stomach, pancreas and hypothalamus among other sites. The printed list includes inhibition of gastrin, secretin and CCK release/action in digestive regulation; effects are context-dependent inhibitory control rather than identical receptor antagonism.</td></tr><tr><td>GIP</td><td>Glucose-dependent insulinotropic polypeptide, historically gastric inhibitory polypeptide; an intestinal incretin supporting glucose-dependent insulin secretion.</td></tr><tr><td>VIP</td><td>Vasoactive intestinal peptide; a neurocrine peptide involved in smooth-muscle relaxation and intestinal secretion, named in the body map.</td></tr><tr><td>Duocrinin</td><td>The source assigns stimulation of Brunner-gland mucus secretion. This is older descriptive terminology, not a routinely used principal modern human endocrine hormone designation.</td></tr><tr><td>Enterocrinin</td><td>The source assigns stimulation of intestinal mucosal juice. Retained as a historical term; it should not be assumed to denote a uniquely characterized major circulating human hormone.</td></tr><tr><td>Enterogastrone</td><td>A historical functional term for intestinal inhibition of gastric secretion/motility rather than one uniquely defined molecule; the source says it retards gastric juice secretion.</td></tr></tbody></table><p><strong>Source correction:</strong> The printed secretin list includes stimulation of the gallbladder, but CCK is the principal gallbladder-contracting signal in this comparison. Secretin principally promotes bicarbonate-rich pancreatic/biliary secretion. The printed line 'Inhibit and secretions in stomach' is damaged/grammatically incomplete; inhibition of gastric acid activity is the checked physiological clarification, not a claimed literal recovery of the missing word.</p>"
    },
    {
      id: "e132-kidney-liver-heart",
      title: "Renal, hepatic, cardiac and adipose endocrine roles",
      sources: [{ document: "biology", page: 132 }, { document: "biology", page: 128 }, { document: "quick-revision", page: 149 }],
      html: "<ul><li>Renin is a renal proteolytic enzyme that initiates the renin-angiotensin pathway, leading through angiotensin II to aldosterone stimulation. Reduced renal perfusion and related signals can increase renin. Restoration of pressure/sodium balance and angiotensin feedback then limit further release.</li><li><strong>Source correction:</strong> 'Renin controls aldosterone as negative feedback' should not mean that renin directly inhibits aldosterone. Activation of the pathway stimulates aldosterone; the completed homeostatic loop supplies the negative feedback.</li><li>Erythropoietin, EPO, promotes erythroid production in bone marrow when oxygen availability is inadequate. Adult kidneys are its major source.</li><li>The source gives the liver as 15% of total EPO. Retain this as an approximate adult teaching figure, not a fixed proportion in every age or physiological state; the fetal liver has a much more important role.</li><li>Renal formation of calcitriol, active vitamin D, is promoted by PTH among other regulators. Calcitriol increases intestinal absorption of Ca<sup>2+</sup> and phosphate.</li><li>The printed kidney mnemonic RED means Renin, Erythropoietin and vitamin D/calcitriol. Renin is not rennin or chymosin, the milk-clotting gastric enzyme classically described in young ruminants. The source's 'rennin by stomach' must not be used to rename the renal enzyme.</li><li>The heart releases natriuretic peptides, including ANP, that promote renal sodium excretion and help reduce volume and blood pressure. Natriuresis means sodium loss in urine, not sodium retention.</li><li>Adipose tissue releases leptin, labelled in the body map, contributing to signals about energy stores and regulation of appetite.</li></ul>"
    },
    {
      id: "e132-gonads",
      title: "Gonadal hormones, cells and feedback loops",
      sources: [{ document: "biology", page: 132 }, { document: "biology", page: 129 }, { document: "quick-revision", page: 149 }],
      html: "<p>Testicular Leydig or interstitial cells produce testosterone in response to LH, historically ICSH in males. Androgens contribute to development of male reproductive structures, puberty and secondary sexual characteristics; the source's 'primary sexual character' is not the only category affected.</p><p>FSH acts on Sertoli cells to support spermatogenesis and inhibin secretion. The source arrow is FSH to Sertoli cells to inhibin, then inhibitory feedback to FSH. Inhibin selectively contributes to reduced FSH secretion rather than serving as another name for testosterone.</p><p>Ovarian follicles produce estrogens, including during development of the Graafian follicle. Estrogen promotes endometrial proliferation, reproductive development and maintenance of bone. The source contrasts follicular estrogen with progesterone and lists female sexual characteristics.</p><p><strong>Source correction:</strong> Estrogen production is not solely a theca-interna function. LH-stimulated theca cells supply androgen precursors, and FSH-supported granulosa-cell aromatase converts them into estrogens. The mature follicle functions as a cooperating cellular unit.</p><p>The corpus luteum is a temporary endocrine structure producing progesterone and estrogens after ovulation. Progesterone converts the estrogen-primed endometrium into a secretory, implantation-supporting state and supports early pregnancy. Implantation involves a blastocyst/early embryo, not an already developed fetus. High pregnancy steroid levels participate in suppression of further ovulation; 'prevents ova formation' is not an exact description of progesterone destroying or abolishing oocytes.</p><p>The printed FSH points state support of spermatogenesis and urinary excretion after menopause. FSH commonly rises after menopause because ovarian inhibin/estrogen feedback declines, and gonadotropins can be detected in urine. A creased fraction-like line under these points appears to relate FSH inversely to progesterone and then says 'prevents ova formation'; its exact missing wording and intended linkage cannot be recovered. No literal inverse-proportionality law is asserted.</p>"
    },
    {
      id: "e132-placenta",
      title: "Placental hormones and the pregnancy source timeline",
      sources: [{ document: "biology", page: 132 }, { document: "quick-revision", page: 149 }],
      html: "<table><thead><tr><th>Hormone</th><th>Role and source terminology</th></tr></thead><tbody><tr><td>Estrogens and progesterone</td><td>Placental steroid hormones that support the maternal and uterine adaptations of pregnancy.</td></tr><tr><td>hCG</td><td>Human chorionic gonadotropin, the source's pregnancy hormone detected by pregnancy tests. Supports corpus-luteum steroid secretion in early pregnancy through LH-receptor-related activity.</td></tr><tr><td>hCS or hPL</td><td>Human chorionic somatomammotropin, also called human placental lactogen; a protein hormone supporting maternal metabolic and mammary adaptations. It is the printed HCS entry, not another estrogen.</td></tr><tr><td>Relaxin</td><td>Associated with reproductive tissue remodelling, including cervical softening and changes in pelvic connective tissues. The source lists increased pubic-symphysis flexibility and cervical dilation; it is not the sole cause of birth-canal opening.</td></tr></tbody></table><p>The printed timeline gives the corpus luteum of pregnancy as the source of estrogen/progesterone during the first two months and placenta during the later seven months. Biology 132 says hCG maintains the corpus luteum for three months. These are overlapping teaching approximations of a progressive luteal-placental shift in early pregnancy, not contradictory exact switches at midnight on a particular month boundary.</p><p><strong>Source qualification:</strong> hCG does not abruptly disappear after three months; it rises early, subsequently declines from its peak and remains produced during pregnancy. Relaxin is also produced by the corpus luteum and other reproductive tissues, so its placement under placenta is not an exclusive-source statement. Corpus luteum and placenta are temporary endocrine structures, whereas a hormone molecule is not itself an organ.</p>"
    },
    {
      id: "e149-adjacent-heart-table",
      title: "Adjacent heart-chamber comparison on the assigned image",
      sources: [{ document: "quick-revision", page: 149 }],
      html: "<p>The bottom-right of the assigned image begins a cardiovascular section. Its complete visible table uses P A R B M for Pisces, Amphibia, Reptilia, Birds and Mammals.</p><table><thead><tr><th>Source group</th><th>Chamber entry and qualification</th></tr></thead><tbody><tr><td>Fishes</td><td>2 main pumping chambers: one atrium and one ventricle, not counting accessory inflow/outflow regions as additional main chambers.</td></tr><tr><td>Amphibians</td><td>3 main chambers: two atria and one ventricle.</td></tr><tr><td>Reptiles</td><td>Printed as incompletely four-chambered. Most noncrocodilian reptiles are more accurately described as two atria with an incompletely subdivided ventricle, rather than four fully separate chambers.</td></tr><tr><td>Birds</td><td>4 completely separated chambers.</td></tr><tr><td>Mammals</td><td>4 completely separated chambers.</td></tr><tr><td>Crocodilian exception</td><td>Crocodiles, alligators and gharials have four anatomically separated chambers; the source cue AG calls attention to alligators and gharials with crocodiles.</td></tr></tbody></table><p>This adjoining table is retained because it is readable assigned-page content, but it is not used to expand the endocrine question set into a cardiovascular test.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 148, status: "transcribed", sectionIds: ["e127-chemical-classes", "e129-pituitary-anatomy", "e129-anterior-pituitary", "e129-gh-prolactin-disorders", "e129-posterior-pituitary", "e130-thyroid-structure", "e130-thyroid-functions-disorders", "e130-calcium-regulation", "e131-adrenal-cortex", "e131-adrenal-disorders", "e148-pancreas"], unresolved: [] },
    { document: "quick-revision", page: 149, status: "partial", sectionIds: ["e128-feedback", "e130-thyroid-functions-disorders", "e130-pineal", "e131-adrenal-cortex", "e131-adrenal-disorders", "e131-adrenal-medulla", "e131-thymus", "e132-digestive-hormones", "e132-kidney-liver-heart", "e132-gonads", "e132-placenta", "e149-adjacent-heart-table"], unresolved: ["The creased fraction-like line below the FSH bullets and above somatostatin appears to link an inverse progesterone term to 'prevents ova formation'; missing wording and exact linkage are not recoverable.", "The secretin bullet reads 'Inhibit and secretions in stomach'; a word is missing/corrupt. Inhibition of gastric acid activity is supplied as an explicit physiological clarification, not a verbatim reconstruction."] },
    { document: "biology", page: 127, status: "partial", sectionIds: ["e127-signalling", "e127-chemical-classes", "e127-enzymes-and-interactions", "e127-functional-types", "e127-local-mediators-history"], unresolved: ["The priority claim 'first hormone synthesized in lab: insulin' has no date or peptide-versus-protein category. Its intended historical category is unresolved; the qualification is typed and no new question tests that priority."] },
    { document: "biology", page: 128, status: "transcribed", sectionIds: ["e128-feedback", "e128-origins", "e128-hypothalamic-map", "e129-anterior-pituitary", "e131-thymus", "e148-pancreas", "e132-digestive-hormones", "e132-kidney-liver-heart"], unresolved: [] },
    { document: "biology", page: 129, status: "transcribed", sectionIds: ["e128-feedback", "e128-hypothalamic-map", "e129-pituitary-anatomy", "e129-anterior-pituitary", "e129-gh-prolactin-disorders", "e129-posterior-pituitary", "e132-gonads"], unresolved: [] },
    { document: "biology", page: 130, status: "transcribed", sectionIds: ["e130-thyroid-structure", "e130-thyroid-functions-disorders", "e130-calcium-regulation", "e130-pineal"], unresolved: [] },
    { document: "biology", page: 131, status: "partial", sectionIds: ["e131-adrenal-cortex", "e131-adrenal-disorders", "e131-adrenal-medulla", "e131-thymus"], unresolved: ["The thymic factor labelled 'Thymin/Thymopoietin' is assigned inhibition of acetylcholine at nerve endings without experimental or physiological context; the intended first name and scope of the claim cannot be established, and are not scored."] },
    { document: "biology", page: 132, status: "transcribed", sectionIds: ["e132-digestive-hormones", "e132-kidney-liver-heart", "e132-gonads", "e132-placenta"], unresolved: [] }
  ],
  questions: [
    {
      id: "note-endocrine-001",
      text: "A circulating hormone reaches two tissues, but only one changes its activity. Which difference best explains the selective response in the source signalling diagram?",
      options: [{ key: "a", text: "Greater intracellular destruction of the hormone." }, { key: "b", text: "Loss of hormone-selective receptors in the tissue." }, { key: "c", text: "Presence of the relevant receptor-signalling pathway." }, { key: "d", text: "Complete extracellular binding to inactive carriers." }],
      answer: "c", explanation: "Biology 127 labels a receptor on the target cell. Delivery through blood alone does not make every tissue a target; the appropriate receptor and downstream signalling machinery are required for a response.", sectionId: "e127-signalling", source: { document: "biology", page: 127 }, cognitive: "application"
    },
    {
      id: "note-endocrine-002",
      text: "An amino-acid-derived hormone circulates mainly bound to proteins and acts chiefly through nuclear receptors. Which source hormone fits this exception to the simple amine rule?",
      options: [{ key: "a", text: "Thyroxine" }, { key: "b", text: "Adrenaline" }, { key: "c", text: "Noradrenaline" }, { key: "d", text: "Dopamine" }],
      answer: "a", explanation: "The Biology 127 classification requires a thyroid-hormone exception. Thyroxine is an amino-acid derivative but is largely carrier-bound in blood and acts mainly through intracellular receptors, unlike the listed catecholamines.", sectionId: "e127-chemical-classes", source: { document: "biology", page: 127 }, cognitive: "application"
    },
    {
      id: "note-endocrine-003",
      text: "Which distinction remains valid after correcting the source's broad enzyme-versus-hormone table?",
      options: [{ key: "a", text: "Enzymes act only outside cells; hormones act only inside cells." }, { key: "b", text: "Enzymes must be lipid-soluble; hormones must be water-soluble." }, { key: "c", text: "Enzymes are always secreted; hormones are never stored." }, { key: "d", text: "Enzymes catalyse reactions; hormones convey regulatory signals." }],
      answer: "d", explanation: "Biology 127's comparison is corrected to distinguish catalytic activity from receptor-mediated regulation. Location, storage and solubility are variable, so the absolute claims about leaving the body or never being stored are not reliable distinctions.", sectionId: "e127-enzymes-and-interactions", source: { document: "biology", page: 127 }, cognitive: "understanding"
    },
    {
      id: "note-endocrine-004",
      text: "When the connecting segment is removed from proinsulin, which structural result represents mature insulin?",
      options: [{ key: "a", text: "The A chain removed, with B and C segments retained" }, { key: "b", text: "A and B peptide chains retained with disulfide links" }, { key: "c", text: "The B chain removed, with A and C segments retained" }, { key: "d", text: "All three segments retained as one uncleaved precursor" }],
      answer: "b", explanation: "Quick Revision 148's processing arrow refers to removal of C-peptide. The corrected section explains that mature insulin retains A and B chains connected by disulfide bonds; it is not converted into a steroid or thyroid hormone.", sectionId: "e127-chemical-classes", source: { document: "quick-revision", page: 148 }, cognitive: "understanding"
    },
    {
      id: "note-endocrine-005",
      text: "The source uses LH and FSH as hormones cooperating in reproductive function. Which interaction term describes that cooperation?",
      options: [{ key: "a", text: "Functional antagonism" }, { key: "b", text: "Hormonal synergism" }, { key: "c", text: "Negative feedback" }, { key: "d", text: "Paracrine signalling" }],
      answer: "b", explanation: "Biology 127 labels two hormones working together as synergism and gives LH plus FSH. This differs from permissiveness, where one hormone enables a fuller response to another, and from functional antagonism.", sectionId: "e127-enzymes-and-interactions", source: { document: "biology", page: 127 }, cognitive: "recall"
    },
    {
      id: "note-endocrine-006",
      text: "A cell releases a mediator that feeds back onto receptors on that same cell. How is this route classified, regardless of additional effects on neighbouring cells?",
      options: [{ key: "a", text: "Exocrine signalling" }, { key: "b", text: "Pheromonal signalling" }, { key: "c", text: "Distant endocrine signalling" }, { key: "d", text: "Autocrine signalling" }],
      answer: "d", explanation: "Biology 127 defines autocrine action as a released signal acting on its secreting cell, illustrated by platelet-activating factor. An additional paracrine effect does not change the classification of the self-directed route.", sectionId: "e127-functional-types", source: { document: "biology", page: 127 }, cognitive: "application"
    },
    {
      id: "note-endocrine-007",
      text: "Why does prolonged GH excess after epiphyseal fusion enlarge the jaw and soft tissues without reproducing childhood long-bone growth?",
      options: [{ key: "a", text: "Closed growth plates restrict further longitudinal growth." }, { key: "b", text: "Adult GH excess loses all capacity to affect somatic tissues." }, { key: "c", text: "Thyroxine becomes the sole growth regulator after puberty." }, { key: "d", text: "The adult pituitary stores GH without releasing it into blood." }],
      answer: "a", explanation: "Biology 129's gigantism/acromegaly contrast depends on developmental timing. After epiphyseal fusion, GH excess still affects bone thickness and soft tissues, but the same mechanism cannot lengthen fused growth plates as in a child.", sectionId: "e129-gh-prolactin-disorders", source: { document: "biology", page: 129 }, cognitive: "understanding"
    },
    {
      id: "note-endocrine-008",
      text: "Which change corrects the disease-table label that equates isolated adult GH deficiency with Simmonds disease?",
      options: [{ key: "a", text: "Replace it with primary insulin resistance." }, { key: "b", text: "Define it as excess thyroid C-cell secretion." }, { key: "c", text: "Describe severe hypopituitarism rather than GH loss alone." }, { key: "d", text: "Treat it as an adrenal medullary catecholamine excess." }],
      answer: "c", explanation: "Quick Revision 148 places Simmonds under adult GH deficiency. The correction explains that this historical syndrome involves severe pituitary insufficiency, not merely loss of one GH output in an otherwise functioning pituitary.", sectionId: "e129-gh-prolactin-disorders", source: { document: "quick-revision", page: 148 }, cognitive: "understanding"
    },
    {
      id: "note-endocrine-009",
      text: "Hypothalamic neurons still synthesize ADH, but transport down their pituitary axons is interrupted. Which labelled store is deprived of its normal new supply?",
      options: [{ key: "a", text: "Thyroid follicular colloid" }, { key: "b", text: "Adrenal cortical lipid droplets" }, { key: "c", text: "Anterior pituitary secretory vesicles" }, { key: "d", text: "Posterior pituitary axon terminals" }],
      answer: "d", explanation: "The Biology 129 diagram follows ADH from hypothalamic cell bodies through the hypothalamo-hypophyseal tract to terminal stores in the neurohypophysis. Blocking axonal delivery can impair this supply even when synthesis continues upstream.", sectionId: "e129-pituitary-anatomy", source: { document: "biology", page: 129 }, cognitive: "application"
    },
    {
      id: "note-endocrine-010",
      text: "Inappropriate milk secretion is accompanied by disrupted menstrual cycles. Which source-listed pituitary excess could plausibly link these findings?",
      options: [{ key: "a", text: "Isolated TSH excess" }, { key: "b", text: "Isolated ACTH excess" }, { key: "c", text: "Prolactin excess" }, { key: "d", text: "Oxytocin excess alone" }],
      answer: "c", explanation: "Biology 129 lists galactorrhoea and amenorrhoea under prolactin excess. Prolactin promotes milk synthesis and, when abnormally elevated, can suppress reproductive-axis function; oxytocin chiefly promotes milk ejection instead.", sectionId: "e129-gh-prolactin-disorders", source: { document: "biology", page: 129 }, cognitive: "application"
    },
    {
      id: "note-endocrine-011",
      text: "Which conclusion correctly interprets the rudimentary adult human pars intermedia without declaring its peptide family biologically nonexistent?",
      options: [{ key: "a", text: "A small pars intermedia proves complete absence of melanocortin activity." }, { key: "b", text: "Melanocortin signalling can remain functional despite the small lobe." }, { key: "c", text: "MSH and melatonin therefore have identical effects on skin pigmentation." }, { key: "d", text: "All human MSH must instead be stored in thyroid follicular colloid." }],
      answer: "b", explanation: "Biology 129's 'vestigial hormone' label is corrected by separating the rudimentary anatomical lobe from functional melanocortin peptides and receptors. Reduced prominence of a lobe does not prove absence of all related signalling.", sectionId: "e129-anterior-pituitary", source: { document: "biology", page: 129 }, cognitive: "understanding"
    },
    {
      id: "note-endocrine-012",
      text: "Why should the phrase 'the whole adrenal cortex is controlled only by ACTH' be qualified?",
      options: [{ key: "a", text: "Aldosterone is chiefly regulated by angiotensin II and potassium." }, { key: "b", text: "ACTH primarily regulates adrenal medullary catecholamine release." }, { key: "c", text: "Cortisol secretion is normally controlled only by plasma calcium." }, { key: "d", text: "All cortical zones respond identically to one shared feedback signal." }],
      answer: "a", explanation: "Biology 131's cortex-versus-medulla control cue is a simplification. ACTH is crucial for cortisol regulation, whereas aldosterone is principally governed by the renin-angiotensin system and plasma potassium.", sectionId: "e131-adrenal-cortex", source: { document: "biology", page: 131 }, cognitive: "understanding"
    },
    {
      id: "note-endocrine-013",
      text: "A normal growth response requires adequate thyroid status alongside GH signalling. Which source interaction concept best explains the supporting thyroid condition?",
      options: [{ key: "a", text: "Permissive endocrine action" }, { key: "b", text: "Competitive GH-receptor blockade" }, { key: "c", text: "Negative feedback abolishing growth" }, { key: "d", text: "Direct antagonism of GH action" }],
      answer: "a", explanation: "Biology 129 notes that GH works with thyroxine. Adequate thyroid hormone supports the full growth response, illustrating permissive endocrine conditions rather than a chemical conversion of GH into thyroid hormone.", sectionId: "e129-anterior-pituitary", source: { document: "biology", page: 129 }, cognitive: "understanding"
    },
    {
      id: "note-endocrine-014",
      text: "Thyroid precursor is stored in the extracellular lumen of a follicle. Why does this not make the thyroid an exocrine gland?",
      options: [{ key: "a", text: "All extracellular storage must be classified as exocrine secretion." }, { key: "b", text: "Its hormones ultimately enter blood, not an external duct." }, { key: "c", text: "Gland classification depends only on where precursor is stored." }, { key: "d", text: "Its hormones act only locally and never enter the circulation." }],
      answer: "b", explanation: "Biology 130 emphasizes extracellular colloid storage inside a closed follicle. Endocrine classification depends on hormone release into internal fluid and blood, not on whether some precursor was stored outside the cell before release.", sectionId: "e130-thyroid-structure", source: { document: "biology", page: 130 }, cognitive: "understanding"
    },
    {
      id: "note-endocrine-015",
      text: "After complete thyroid removal in a maintained tadpole, why is dietary iodine alone not equivalent to supplying thyroid hormone?",
      options: [{ key: "a", text: "Iodine itself is the final ligand of thyroid-hormone receptors." }, { key: "b", text: "Iodine changes metamorphosis only by stimulating pituitary GH." }, { key: "c", text: "Iodine needs a functioning hormone-synthesis pathway." }, { key: "d", text: "Dietary iodine always bypasses the need for thyroid enzymes." }],
      answer: "c", explanation: "Biology 130 links thyroid hormone with metamorphosis but compresses hormone and iodine into one arrow. Iodine is a synthesis substrate, not the active receptor hormone; without the gland's pathway it cannot simply replace supplied thyroid hormone.", sectionId: "e130-thyroid-functions-disorders", source: { document: "biology", page: 130 }, cognitive: "application"
    },
    {
      id: "note-endocrine-016",
      text: "Which explanation correctly qualifies the source's description of bulging eyes in Graves disease?",
      options: [{ key: "a", text: "Every thyroid-hormone excess enlarges the whole eyeball." }, { key: "b", text: "Simple iodine deficiency inevitably causes Graves eye disease." }, { key: "c", text: "Exophthalmos is explained solely by raised aqueous pressure." }, { key: "d", text: "Orbital tissue inflammation and expansion can displace the eyes." }],
      answer: "d", explanation: "Biology 130's 'enlarged eyeball' wording is corrected to thyroid-associated orbital tissue change. Graves ophthalmopathy is not simply enlargement of the globe, and it is not an inevitable feature of every cause of thyrotoxicosis.", sectionId: "e130-thyroid-functions-disorders", source: { document: "biology", page: 130 }, cognitive: "understanding"
    },
    {
      id: "note-endocrine-017",
      text: "PTH-related bone resorption can release phosphate, yet serum phosphate often falls when the kidneys function normally. Which additional action explains this?",
      options: [{ key: "a", text: "PTH increases renal phosphate reabsorption." }, { key: "b", text: "PTH blocks formation of active vitamin D." }, { key: "c", text: "PTH increases renal phosphate excretion." }, { key: "d", text: "PTH suppresses all intestinal phosphate absorption." }],
      answer: "c", explanation: "The corrected Biology 130 calcium section distinguishes bone release from the net whole-body response. PTH promotes phosphaturia, which can outweigh phosphate release and lower serum phosphate when renal excretion is intact.", sectionId: "e130-calcium-regulation", source: { document: "biology", page: 130 }, cognitive: "application"
    },
    {
      id: "note-endocrine-018",
      text: "A parathyroid slide contains numerous small cells and fewer large eosinophilic cells. Which population is the principal source of PTH?",
      options: [{ key: "a", text: "Thyroid parafollicular cells" }, { key: "b", text: "Pancreatic alpha cells" }, { key: "c", text: "Parathyroid oxyphil cells" }, { key: "d", text: "Parathyroid chief cells" }],
      answer: "d", explanation: "Biology 130 distinguishes numerous small chief cells from larger oxyphil cells and assigns parathormone to chief cells. The source's light-microscopic 'non-granular' description does not negate their secretory function.", sectionId: "e130-calcium-regulation", source: { document: "biology", page: 130 }, cognitive: "application"
    },
    {
      id: "note-endocrine-019",
      text: "Which inference should be rejected when correcting the calcitonin disease table?",
      options: [{ key: "a", text: "Calcitonin deficiency alone necessarily explains all rickets." }, { key: "b", text: "Rickets involves defective mineralization in a growing skeleton." }, { key: "c", text: "Vitamin D and phosphate status matter for mineralization." }, { key: "d", text: "Osteoporosis and osteomalacia describe different bone problems." }],
      answer: "a", explanation: "Biology 130's calcitonin-deficiency labels are not established obligatory human syndromes. Rickets concerns mineralization and has multiple causes; it cannot be attributed to calcitonin deficiency alone from the source table.", sectionId: "e130-calcium-regulation", source: { document: "biology", page: 130 }, cognitive: "understanding"
    },
    {
      id: "note-endocrine-020",
      text: "Moving inward through the three adrenal cortical zones, which sequence of dominant secretion classes matches the labelled diagram?",
      options: [{ key: "a", text: "Glucocorticoids, mineralocorticoids, adrenal androgens" }, { key: "b", text: "Mineralocorticoids, glucocorticoids, adrenal androgens" }, { key: "c", text: "Adrenal androgens, glucocorticoids, mineralocorticoids" }, { key: "d", text: "Mineralocorticoids, adrenal androgens, glucocorticoids" }],
      answer: "b", explanation: "Quick Revision 149 and the typed zone table map glomerulosa to mineralocorticoids, fasciculata to glucocorticoids and reticularis to adrenal sex steroids. Catecholamines belong chiefly to the medulla rather than these cortical zones.", sectionId: "e131-adrenal-cortex", source: { document: "quick-revision", page: 149 }, cognitive: "recall"
    },
    {
      id: "note-endocrine-021",
      text: "Which statement corrects the handwritten claim that norepinephrine generally inhibits adrenaline?",
      options: [{ key: "a", text: "Norepinephrine antagonizes every receptor stimulated by adrenaline." }, { key: "b", text: "Both are adrenergic agonists with differing receptor effects." }, { key: "c", text: "Only adrenaline participates in sympathetic vascular signalling." }, { key: "d", text: "Norepinephrine is a glucocorticoid produced by the outer cortex." }],
      answer: "b", explanation: "Biology 131 places both molecules in adrenal medullary signalling but incorrectly calls norepinephrine an inhibitor. They are catecholamine agonists with distinct receptor preferences and organ effects, not a general hormone-antihormone pair.", sectionId: "e131-adrenal-medulla", source: { document: "biology", page: 131 }, cognitive: "understanding"
    },
    {
      id: "note-endocrine-022",
      text: "A source annotation links adrenal chromaffin cells to frog camouflage. Which distinction repairs the cell-name confusion?",
      options: [{ key: "a", text: "Chromaffin cells release catecholamines; chromatophores contain pigment." }, { key: "b", text: "Chromaffin cells store melanin; chromatophores release catecholamines." }, { key: "c", text: "Both names identify pigment cells, but only their locations differ." }, { key: "d", text: "Both names identify steroid-producing cells of the adrenal cortex." }],
      answer: "a", explanation: "The correction to Biology 131 distinguishes modified sympathetic endocrine chromaffin cells of the medulla from pigment-bearing chromatophores. The similar names do not identify the same cell population or function.", sectionId: "e131-adrenal-medulla", source: { document: "biology", page: 131 }, cognitive: "understanding"
    },
    {
      id: "note-endocrine-023",
      text: "A concentric epithelial structure in the thymic medulla is identified as a Hassall corpuscle. Which classification is appropriate?",
      options: [{ key: "a", text: "A single circulating phagocytic monocyte" }, { key: "b", text: "A thyroid follicle secreting triiodothyronine" }, { key: "c", text: "An adrenal ganglion of chromaffin cells" }, { key: "d", text: "A specialized epithelial-reticular cell structure" }],
      answer: "d", explanation: "Quick Revision 149 incorrectly calls Hassall corpuscles phagocytic cells. The corrected thymus section identifies them as concentric epithelial-reticular structures in the medulla; thymic macrophages are a separate population.", sectionId: "e131-thymus", source: { document: "quick-revision", page: 149 }, cognitive: "application"
    },
    {
      id: "note-endocrine-024",
      text: "Two people have polyuria. One has marked hyperglycaemia and urinary glucose; the other loses dilute urine despite normal glucose. Which distinction is supported?",
      options: [{ key: "a", text: "Both findings necessarily prove complete beta-cell destruction." }, { key: "b", text: "Urine volume alone identifies the same endocrine defect in both." }, { key: "c", text: "The first suggests a glucose disorder; the second a water-balance defect." }, { key: "d", text: "Normal glucose excludes any possible ADH-related disorder." }],
      answer: "c", explanation: "Quick Revision 148 contrasts mellitus and insipidus. Hyperglycaemia with glycosuria suggests impaired insulin-related glucose regulation, whereas dilute polyuria without hyperglycaemia supports investigation of ADH-related water conservation rather than assuming the same cause.", sectionId: "e148-pancreas", source: { document: "quick-revision", page: 148 }, cognitive: "application"
    },
    {
      id: "note-endocrine-025",
      text: "A locally released islet peptide reduces secretion from both alpha and beta cells. Which source-listed cell-hormone pair best fits this regulatory effect?",
      options: [{ key: "a", text: "Delta cell and somatostatin" }, { key: "b", text: "Alpha cell and thyroxine" }, { key: "c", text: "Beta cell and calcitonin" }, { key: "d", text: "Follicular cell and aldosterone" }],
      answer: "a", explanation: "Quick Revision 148 assigns somatostatin to delta cells. The typed section explains its local inhibitory effects on glucagon and insulin secretion, linking the cell label with regulation rather than simply treating every islet cell as insulin-producing.", sectionId: "e148-pancreas", source: { document: "quick-revision", page: 148 }, cognitive: "application"
    },
    {
      id: "note-endocrine-026",
      text: "Which set of sites preserves the printed source's distribution of somatostatin?",
      options: [{ key: "a", text: "Adrenal cortex, ovary and testis" }, { key: "b", text: "Thyroid, parathyroid and pineal" }, { key: "c", text: "Stomach, pancreas and hypothalamus" }, { key: "d", text: "Heart, kidney and adipose tissue" }],
      answer: "c", explanation: "Quick Revision 149 explicitly lists stomach, pancreas and hypothalamus under somatostatin. This illustrates that one peptide can have gastrointestinal, pancreatic local and hypothalamic inhibitory roles rather than one exclusive gland of origin.", sectionId: "e132-digestive-hormones", source: { document: "quick-revision", page: 149 }, cognitive: "recall"
    },
    {
      id: "note-endocrine-027",
      text: "In the source feedback diagram, Sertoli-cell output rises and feeds back to reduce FSH. Which output carries the labelled inhibitory feedback?",
      options: [{ key: "a", text: "Secretin" }, { key: "b", text: "Inhibin" }, { key: "c", text: "Calcitonin" }, { key: "d", text: "Oxytocin" }],
      answer: "b", explanation: "Biology 132 draws FSH stimulating Sertoli cells, followed by inhibin production and an inhibitory arrow back to FSH. This feedback signal is distinct from Leydig-cell testosterone production under LH control.", sectionId: "e132-gonads", source: { document: "biology", page: 132 }, cognitive: "understanding"
    },
    {
      id: "note-endocrine-028",
      text: "Which two-cell explanation corrects the claim that follicular estrogen comes from theca interna alone?",
      options: [{ key: "a", text: "Granulosa cells supply androgens; theca cells aromatize them." }, { key: "b", text: "Theca cells complete estrogen synthesis without granulosa participation." }, { key: "c", text: "Granulosa cells secrete LH; theca cells secrete FSH." }, { key: "d", text: "Theca cells supply androgens; granulosa cells aromatize them." }],
      answer: "d", explanation: "The Biology 132 correction describes cooperative follicular steroidogenesis: LH supports theca androgen production and FSH supports granulosa aromatase conversion to estrogen. The mature follicle is not one isolated theca-only estrogen factory.", sectionId: "e132-gonads", source: { document: "biology", page: 132 }, cognitive: "understanding"
    },
    {
      id: "note-endocrine-029",
      text: "One source says corpus-luteum support for two months and another says three months. How should the early-pregnancy endocrine transition be taught?",
      options: [{ key: "a", text: "hCG always disappears completely at exactly two months." }, { key: "b", text: "A gradual luteal-placental shift underlies the approximate timelines." }, { key: "c", text: "Placental steroids are absent until the final day of pregnancy." }, { key: "d", text: "Corpus luteum and placenta are two names for the same tissue." }],
      answer: "b", explanation: "Biology 132 and Quick Revision 149 use approximate month-based descriptions of the luteal-placental shift. The transition is progressive, so the shorthand should not be treated as an abrupt universal switch or disappearance of hCG.", sectionId: "e132-placenta", source: { document: "biology", page: 132 }, cognitive: "understanding"
    },
    {
      id: "note-endocrine-030",
      text: "Which sequence correctly separates renin's pathway activation from the negative feedback that eventually limits it?",
      options: [{ key: "a", text: "Renin activates angiotensin signalling; restored balance limits further renin." }, { key: "b", text: "Renin inhibits angiotensin II; low pressure suppresses aldosterone secretion." }, { key: "c", text: "Renin directly replaces aldosterone; angiotensin II has no role in this pathway." }, { key: "d", text: "Renin rises after sodium retention; feedback continually deepens sodium loss." }],
      answer: "a", explanation: "Biology 132's correction explains that renin stimulates the pathway leading to angiotensin II and aldosterone. Negative feedback belongs to restoration of pressure/sodium balance and downstream signals, not a direct inhibitory renin-to-aldosterone arrow.", sectionId: "e132-kidney-liver-heart", source: { document: "biology", page: 132 }, cognitive: "understanding"
    }
  ]
};