window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["haloalkanes"] = {
  id: "haloalkanes",
  subject: "Chemistry",
  title: "Haloalkanes and haloarenes",
  sections: [
    {
      id: "zaitsev-grignard",
      title: "Saytzeff orientation and the magnesium reaction",
      sources: [{ document: "quick-revision", page: 78 }],
      html: "<p><strong>Saytzeff's rule, also spelled Zaitsev's rule:</strong> if elimination can give more than one alkene, the major product commonly has the greater number of alkyl substituents on its double-bond carbons. Different beta-carbon positions, not merely the total number of beta hydrogens, provide different constitutional alkene products. For example, ordinary elimination of 2-bromopentane with a small base usually favours pent-2-ene over pent-1-ene.</p><p><strong>Conditions on the rule:</strong> it is a usual regioselectivity trend, not an exceptionless law. Base bulk, anti-periplanar geometry, ring constraints and conjugation can change the preference; the source statement does not specify those exceptions.</p><p><strong>Reaction with magnesium:</strong> RX + Mg &rarr; RMgX in dry ether. The product is an organomagnesium halide, a Grignard reagent. The new carbon-magnesium bond gives carbon strongly nucleophilic and basic character.</p><p>Dry conditions are essential because a protic impurity destroys the reagent: RMgX + H<sub>2</sub>O &rarr; RH + Mg(OH)X. This explains the source's 'dry ether' label; water does not simply dilute a Grignard reagent without changing it. R, X and the carbon skeleton must be carried consistently from the alkyl halide into the product.</p>"
    },
    {
      id: "haloarene-hydrolysis",
      title: "Chlorobenzene hydrolysis and nitro-group activation",
      sources: [{ document: "quick-revision", page: 78 }],
      html: "<p><strong>Dow's process:</strong> the source draws chlorobenzene becoming phenol with NaOH at 623 K and 300 atm. The carbon bearing Cl becomes the carbon bearing O; the ring remains intact.</p><p><strong>Source correction:</strong> the strongly alkaline reaction mixture contains sodium phenoxide, not isolated neutral phenol. The atom-balanced stages are C<sub>6</sub>H<sub>5</sub>Cl + 2NaOH &rarr; C<sub>6</sub>H<sub>5</sub>ONa + NaCl + H<sub>2</sub>O, followed by acidification: C<sub>6</sub>H<sub>5</sub>ONa + HCl &rarr; C<sub>6</sub>H<sub>5</sub>OH + NaCl. Acid work-up is omitted from the printed arrow.</p><p>The second ring drawing has Cl at carbon 1 and NO<sub>2</sub> at carbons 2, 4 and 6. Its source arrow says warm H<sub>2</sub>O and gives the corresponding OH compound, 2,4,6-trinitrophenol, also called picric acid. The three nitro groups remain at the same ring positions; only the chloride substituent is replaced.</p><p>Ortho and para nitro groups strongly activate an aryl halide toward addition-elimination nucleophilic substitution by stabilizing the anionic intermediate. Thus the trinitro compound is much easier to hydrolyse than chlorobenzene. The source's warm-water arrow is a compressed comparison and does not provide a complete preparative procedure; aqueous hydroxide readily gives the corresponding phenoxide or picrate salt, and acidification determines the neutral phenol form. This nitro-assisted pathway should not be confused with the harsh-condition pathway of unsubstituted chlorobenzene.</p>"
    },
    {
      id: "aryl-metal-coupling",
      title: "Fittig and Wurtz-Fittig coupling",
      sources: [{ document: "quick-revision", page: 78 }],
      html: "<p><strong>Fittig reaction:</strong> 2C<sub>6</sub>H<sub>5</sub>X + 2Na &rarr; C<sub>6</sub>H<sub>5</sub>-C<sub>6</sub>H<sub>5</sub> + 2NaX in ether, under dry conditions. The source calls the product diphenyl; its modern common name is biphenyl. The two six-membered aromatic rings are joined by a single carbon-carbon bond, not fused together and not linked through oxygen.</p><p><strong>Wurtz-Fittig reaction:</strong> C<sub>6</sub>H<sub>5</sub>X + RX + 2Na &rarr; C<sub>6</sub>H<sub>5</sub>R + 2NaX in dry ether. The aryl and alkyl fragments join to give an alkylbenzene. With methyl halide the intended cross-coupled product is toluene.</p><p><strong>Source correction:</strong> the Wurtz-Fittig drawing shows only one Na and one NaX although two halogen-bearing reactants are used. Two Na atoms and two sodium-halide units are required. If the two starting halogens differ, the products contain one equivalent of each sodium halide. Cross-coupling can compete with symmetrical coupling, so the equation describes the desired product rather than guaranteed exclusive selectivity.</p>"
    },
    {
      id: "haloarene-electrophilic-substitution",
      title: "Electrophilic substitution on chlorobenzene",
      sources: [{ document: "quick-revision", page: 78 }],
      html: "<p>The source treats chlorobenzene with CH<sub>3</sub>Cl and anhydrous AlCl<sub>3</sub> and draws two methylated rings: para-chlorotoluene and ortho-chlorotoluene. In both structures the original C-Cl bond remains, and a ring hydrogen is replaced by CH<sub>3</sub>. For either isomer the idealized net equation is C<sub>6</sub>H<sub>5</sub>Cl + CH<sub>3</sub>Cl &rarr; C<sub>6</sub>H<sub>4</sub>(Cl)(CH<sub>3</sub>) + HCl.</p><p>This chart illustrates chlorine's ortho/para orientation in electrophilic substitution. Chlorine nevertheless deactivates the ring overall, and Lewis-acid complexation can make Friedel-Crafts reactions less favourable than the simple diagram suggests. The source gives no isomer ratio or yield; neither should be inferred. This is ring substitution, not replacement of the chlorine by a methyl group.</p>"
    },
    {
      id: "polyhalogen-compounds",
      title: "Chloroform, iodoform and DDT",
      sources: [{ document: "quick-revision", page: 78 }],
      html: "<ul><li><strong>Chloroform, CHCl<sub>3</sub>:</strong> the source warns that light-assisted oxidation in air can produce poisonous carbonyl chloride, COCl<sub>2</sub>, called phosgene, along with HCl. Its net degradation equation is 2CHCl<sub>3</sub> + O<sub>2</sub> &rarr; 2COCl<sub>2</sub> + 2HCl. This is a storage-hazard warning, not a reaction to attempt; suspected degraded material requires appropriate hazardous-chemical handling.</li><li><strong>Iodoform, CHI<sub>3</sub>:</strong> the source lists its use as an antiseptic in wound dressings. This records the traditional use, not advice to apply laboratory iodoform or self-treat a wound.</li><li><strong>DDT:</strong> dichlorodiphenyltrichloroethane. The source identifies it as a pesticide and an organic pollutant. It is lipophilic, giving it a high potential for accumulation in fatty tissues. Persistence and accumulation explain the environmental concern; the historical pesticide use is not a recommendation for unrestricted present-day use.</li></ul>"
    },
    {
      id: "alcohol-boundary-properties",
      title: "Alcohol properties beginning on the assigned page",
      sources: [{ document: "quick-revision", page: 78 }],
      html: "<p>The right-hand page changes heading to Alcohol, Phenol and Ether. These lines are retained here because page 78 is the source page assigned to this topic.</p><ul><li>The general alcohol formula is C<sub>n</sub>H<sub>2n+1</sub>OH for acyclic saturated monohydric alcohols. It is not the formula for every polyhydric, unsaturated or cyclic alcohol.</li><li>The printed acidity order is H<sub>2</sub>O &gt; 1&deg; &gt; 2&deg; &gt; 3&deg;. In otherwise comparable simple alcohols, alkyl electron donation and poorer alkoxide solvation can decrease acidity as substitution increases.</li><li>For reactions dominated by cleavage of the C-OH bond through carbocation-like pathways, the source gives 3&deg; &gt; 2&deg; &gt; 1&deg;.</li><li>The source gives ease of acid-catalysed dehydration as 3&deg; &gt; 2&deg; &gt; 1&deg;, for comparable alcohols and conditions.</li><li><strong>Lucas reagent:</strong> concentrated HCl containing ZnCl<sub>2</sub>. The test depends on replacement of OH by Cl and formation of an insoluble alkyl chloride, observed as turbidity for suitable alcohols.</li></ul><p><strong>Source corrections and limits:</strong> the acidity sequence is not a solvent-independent ranking of all alcohols. Methanol can be slightly more acidic than water on the common aqueous pKa scale, and substituted alcohols may differ strongly. Methanol is not a conventional primary alcohol defined by one carbon substituent on the OH-bearing carbon. The C-OH cleavage and dehydration trends apply to the specified reaction families; they do not describe O-H proton removal or guarantee the same order for an SN2 pathway. Allylic and benzylic alcohols can be exceptions to simple Lucas classification.</p>"
    },
    {
      id: "methanol-synthesis",
      title: "Methanol: wood spirit and carbon monoxide hydrogenation",
      sources: [{ document: "quick-revision", page: 78 }],
      html: "<p>Methanol is also called wood spirit. The source gives catalytic hydrogenation of carbon monoxide:</p><p>CO + 2H<sub>2</sub> &rarr; CH<sub>3</sub>OH.</p><p>The arrow specifies a ZnO-Cr<sub>2</sub>O<sub>3</sub> catalyst. <strong>Source correction:</strong> the prose abbreviates this to 'in presence of Zn', but the printed catalytic system contains zinc oxide and chromium(III) oxide, not simply metallic zinc. The stoichiometric feed ratio is two moles of hydrogen per mole of carbon monoxide. This is a source-listed historical synthesis system; the page supplies no pressure, temperature or conversion value, and no claim is made that it is the only industrial catalyst.</p>"
    },
    {
      id: "ethanol-fermentation",
      title: "Ethanol from sugars: invertase and zymase",
      sources: [{ document: "quick-revision", page: 78 }],
      html: "<p>The source describes commercial ethanol production by fermentation of sugar from molasses, sugarcane or fruits. Its two reaction stages are distinct.</p><ol><li><strong>Invertase hydrolysis:</strong> C<sub>12</sub>H<sub>22</sub>O<sub>11</sub> + H<sub>2</sub>O &rarr; C<sub>6</sub>H<sub>12</sub>O<sub>6</sub> + C<sub>6</sub>H<sub>12</sub>O<sub>6</sub>. The products are one glucose and one fructose molecule, not two identically structured glucose molecules. The disaccharide is sucrose.</li><li><strong>Zymase fermentation:</strong> C<sub>6</sub>H<sub>12</sub>O<sub>6</sub> &rarr; 2C<sub>2</sub>H<sub>5</sub>OH + 2CO<sub>2</sub>. The diagram labels the input glucose and the organic output ethanol.</li></ol><p>Zymase is obtained from <em>Saccharomyces</em> yeast; the name describes the fermentation enzyme system. Fermentation requires suitable biological conditions and is not catalysed merely by adding invertase. The ideal equation gives two moles each of ethanol and carbon dioxide per mole of glucose. Actual fermentation yield need not equal this stoichiometric maximum.</p>"
    },
    {
      id: "alcohol-from-halide",
      title: "Alcohol preparation from alkyl halides",
      sources: [{ document: "quick-revision", page: 78 }],
      html: "<p>The final diagram gives two alternative routes from RX to ROH: aqueous KOH, or moist Ag<sub>2</sub>O, labelled AgOH in parentheses.</p><ul><li>RX + KOH(aq) &rarr; ROH + KX, under conditions favouring substitution.</li><li>2RX + Ag<sub>2</sub>O + H<sub>2</sub>O &rarr; 2ROH + 2AgX, representing the moist silver-oxide route.</li></ul><p><strong>Source clarification:</strong> 'AgOH' is a shorthand for the moist silver-oxide system, not a requirement to isolate stable bulk silver hydroxide. Aqueous hydroxide favours hydrolysis in the simple examples, while hot alcoholic base may favour elimination. The starting substrate here is an alkyl halide; aryl halides do not automatically follow the same mild substitution conditions.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 78, status: "transcribed", sectionIds: ["zaitsev-grignard", "haloarene-hydrolysis", "aryl-metal-coupling", "haloarene-electrophilic-substitution", "polyhalogen-compounds", "alcohol-boundary-properties", "methanol-synthesis", "ethanol-fermentation", "alcohol-from-halide"], unresolved: [] }
  ],
  questions: [
    { id: "note-haloalkanes-001", text: "Under ordinary Zaitsev-favouring elimination conditions, which alkene is preferred from 2-bromopentane?", options: [{ key: "a", text: "Pent-2-ene" }, { key: "b", text: "Pent-1-ene" }, { key: "c", text: "Pent-1-yne" }, { key: "d", text: "Pentane" }], answer: "a", explanation: "Elimination can form pent-1-ene or pent-2-ene. The internal pent-2-ene double bond has more alkyl substitution and is normally favoured with a small base.", sectionId: "zaitsev-grignard", source: { document: "quick-revision", page: 78 }, cognitive: "application" },
    { id: "note-haloalkanes-002", text: "What new bond is created when ethyl bromide reacts with magnesium in dry ether to form a Grignard reagent?", options: [{ key: "a", text: "An ethyl carbon-oxygen bond" }, { key: "b", text: "An ethyl carbon-magnesium bond" }, { key: "c", text: "An ethyl carbon-nitrogen bond" }, { key: "d", text: "An ethyl carbon-sulfur bond" }], answer: "b", explanation: "Magnesium gives C2H5MgBr by insertion into the carbon-halogen connection. The organomagnesium product contains the carbon-magnesium bond characteristic of Grignard reagents.", sectionId: "zaitsev-grignard", source: { document: "quick-revision", page: 78 }, cognitive: "understanding" },
    { id: "note-haloalkanes-003", text: "An ethylmagnesium bromide sample is accidentally exposed to water. Which organic product is expected from protonation?", options: [{ key: "a", text: "Ethene, C2H4" }, { key: "b", text: "Ethanol, C2H5OH" }, { key: "c", text: "Ethane, C2H6" }, { key: "d", text: "Ethanal, CH3CHO" }], answer: "c", explanation: "The ethyl group takes a proton from water: C2H5MgBr + H2O gives C2H6 + Mg(OH)Br. The reagent is destroyed rather than converted into ethanol.", sectionId: "zaitsev-grignard", source: { document: "quick-revision", page: 78 }, cognitive: "application" },
    { id: "note-haloalkanes-004", text: "In Dow's process, which species is present after chlorobenzene reacts with hot concentrated NaOH but before acid work-up?", options: [{ key: "a", text: "C6H5COONa" }, { key: "b", text: "C6H5CH2ONa" }, { key: "c", text: "C6H5SO3Na" }, { key: "d", text: "C6H5ONa" }], answer: "d", explanation: "Chloride is replaced by oxygen and the alkaline medium retains the phenoxide salt C6H5ONa. Acidification is needed to obtain the neutral phenol drawn in the source.", sectionId: "haloarene-hydrolysis", source: { document: "quick-revision", page: 78 }, cognitive: "application" },
    { id: "note-haloalkanes-005", text: "Why does 2,4,6-trinitrochlorobenzene undergo nucleophilic replacement much more readily than chlorobenzene?", options: [{ key: "a", text: "Nitro groups stabilize the anionic intermediate" }, { key: "b", text: "Nitro groups remove every aromatic carbon" }, { key: "c", text: "Nitro groups make chloride a carbon nucleophile" }, { key: "d", text: "Nitro groups prevent any nucleophilic approach" }], answer: "a", explanation: "The ortho and para nitro groups withdraw electron density and stabilize the negative charge generated in addition-elimination aromatic substitution.", sectionId: "haloarene-hydrolysis", source: { document: "quick-revision", page: 78 }, cognitive: "understanding" },
    { id: "note-haloalkanes-006", text: "The Fittig reaction couples two phenyl halide molecules. How are the rings connected in the organic product?", options: [{ key: "a", text: "Through an oxygen atom in an ether" }, { key: "b", text: "Through a single carbon-carbon bond" }, { key: "c", text: "Through a methylene bridge between rings" }, { key: "d", text: "Through two shared carbons in fused rings" }], answer: "b", explanation: "The product is biphenyl, C6H5-C6H5. Its rings are linked by one C-C bond; they do not share ring atoms and no oxygen or methylene bridge is inserted.", sectionId: "aryl-metal-coupling", source: { document: "quick-revision", page: 78 }, cognitive: "understanding" },
    { id: "note-haloalkanes-007", text: "For one mole each of bromobenzene and methyl bromide in the ideal Wurtz-Fittig equation, how many moles of sodium are required?", options: [{ key: "a", text: "1 mol of sodium" }, { key: "b", text: "3 mol of sodium" }, { key: "c", text: "2 mol of sodium" }, { key: "d", text: "4 mol of sodium" }], answer: "c", explanation: "Two bromine atoms must leave as two NaBr units. The balanced cross-coupling uses 2Na, correcting the one-sodium coefficient shown in the source diagram.", sectionId: "aryl-metal-coupling", source: { document: "quick-revision", page: 78 }, cognitive: "application" },
    { id: "note-haloalkanes-008", text: "In the source's methylation diagram for chlorobenzene, which bond change distinguishes electrophilic ring substitution from replacement of chlorine?", options: [{ key: "a", text: "The C-Cl bond is replaced by C-OH" }, { key: "b", text: "The aromatic ring is fully hydrogenated" }, { key: "c", text: "The C-Cl bond is replaced by C-MgCl" }, { key: "d", text: "A ring C-H bond is replaced by C-CH3" }], answer: "d", explanation: "The source products are ortho- and para-chlorotoluene. They retain chlorine and gain a methyl group in place of a ring hydrogen, so this is electrophilic substitution.", sectionId: "haloarene-electrophilic-substitution", source: { document: "quick-revision", page: 78 }, cognitive: "understanding" },
    { id: "note-haloalkanes-009", text: "Which toxic degradation product accounts for the source's warning about chloroform exposed to air and light?", options: [{ key: "a", text: "Carbonyl chloride, COCl2" }, { key: "b", text: "Carbon dioxide, CO2" }, { key: "c", text: "Chloromethane, CH3Cl" }, { key: "d", text: "Methanol, CH3OH" }], answer: "a", explanation: "The warning concerns formation of carbonyl chloride, called phosgene, rather than an ordinary carbon oxide or alcohol. It is a serious toxic-degradation hazard.", sectionId: "polyhalogen-compounds", source: { document: "quick-revision", page: 78 }, cognitive: "recall" },
    { id: "note-haloalkanes-010", text: "Which formula belongs to the compound traditionally called iodoform?", options: [{ key: "a", text: "CH3I" }, { key: "b", text: "CHI3" }, { key: "c", text: "CH2I2" }, { key: "d", text: "C2H5I" }], answer: "b", explanation: "Iodoform is triiodomethane, CHI3. Its three iodine substituents distinguish it from methyl iodide, diiodomethane and ethyl iodide.", sectionId: "polyhalogen-compounds", source: { document: "quick-revision", page: 78 }, cognitive: "recall" },
    { id: "note-haloalkanes-011", text: "Which property stated for DDT helps explain its accumulation in fatty tissues?", options: [{ key: "a", text: "Strong water solubility" }, { key: "b", text: "Complete ionic dissociation" }, { key: "c", text: "High affinity for lipids" }, { key: "d", text: "Rapid conversion to oxygen" }], answer: "c", explanation: "DDT is lipophilic, so it partitions into fatty material. Together with persistence, this favours bioaccumulation instead of rapid clearance through aqueous phases.", sectionId: "polyhalogen-compounds", source: { document: "quick-revision", page: 78 }, cognitive: "understanding" },
    { id: "note-haloalkanes-012", text: "Which formula fits a six-carbon acyclic saturated monohydric alcohol?", options: [{ key: "a", text: "C6H9OH" }, { key: "b", text: "C6H11OH" }, { key: "c", text: "C6H15OH" }, { key: "d", text: "C6H13OH" }], answer: "d", explanation: "Substitution of n = 6 into CnH2n+1OH gives C6H13OH, or C6H14O overall. The stated saturation, acyclic skeleton and single OH are necessary conditions.", sectionId: "alcohol-boundary-properties", source: { document: "quick-revision", page: 78 }, cognitive: "application" },
    { id: "note-haloalkanes-013", text: "For a comparable acid-catalysed process favouring carbocation formation, which alcohol most readily undergoes C-OH cleavage?", options: [{ key: "a", text: "2-Methylpropan-2-ol" }, { key: "b", text: "2-Methylpropan-1-ol" }, { key: "c", text: "Butan-1-ol" }, { key: "d", text: "Butan-2-ol" }], answer: "a", explanation: "2-Methylpropan-2-ol is tertiary. Under the specified carbocation-like conditions the elementary tertiary > secondary > primary trend favours its C-OH cleavage.", sectionId: "alcohol-boundary-properties", source: { document: "quick-revision", page: 78 }, cognitive: "application" },
    { id: "note-haloalkanes-014", text: "Which mixture is Lucas reagent?", options: [{ key: "a", text: "Dilute HCl with NaCl" }, { key: "b", text: "Concentrated HCl with ZnCl2" }, { key: "c", text: "Concentrated H2SO4 with KCl" }, { key: "d", text: "Dilute HNO3 with AgNO3" }], answer: "b", explanation: "Lucas reagent is concentrated hydrochloric acid containing zinc chloride. It promotes OH replacement by chloride; suitable insoluble products produce turbidity.", sectionId: "alcohol-boundary-properties", source: { document: "quick-revision", page: 78 }, cognitive: "recall" },
    { id: "note-haloalkanes-015", text: "Why should the printed water > primary > secondary > tertiary alcohol acidity order not be used as an absolute rule?", options: [{ key: "a", text: "Alcohols cannot lose an O-H proton" }, { key: "b", text: "Every alcohol has an identical alkoxide" }, { key: "c", text: "Solvation and substituents affect acidity" }, { key: "d", text: "Water has no measurable acid behaviour" }], answer: "c", explanation: "Acidity depends on stabilization of the conjugate base, including solvation and electronic effects. Methanol and substituted alcohols show why the printed sequence needs limits.", sectionId: "alcohol-boundary-properties", source: { document: "quick-revision", page: 78 }, cognitive: "understanding" },
    { id: "note-haloalkanes-016", text: "Which carbon-containing feed is shown in the source's ZnO-Cr2O3 methanol-synthesis equation?", options: [{ key: "a", text: "Methane, CH4" }, { key: "b", text: "Carbon dioxide, CO2" }, { key: "c", text: "Ethene, C2H4" }, { key: "d", text: "Carbon monoxide, CO" }], answer: "d", explanation: "The displayed equation is CO + 2H2 giving CH3OH over the oxide catalyst. This identifies the feed in that equation without claiming other methanol routes are impossible.", sectionId: "methanol-synthesis", source: { document: "quick-revision", page: 78 }, cognitive: "recall" },
    { id: "note-haloalkanes-017", text: "With complete conversion and hydrogen in excess, how much methanol can the source equation form from 0.40 mol of CO?", options: [{ key: "a", text: "0.40 mol of methanol" }, { key: "b", text: "0.20 mol of methanol" }, { key: "c", text: "0.80 mol of methanol" }, { key: "d", text: "1.20 mol of methanol" }], answer: "a", explanation: "CO and CH3OH have a 1:1 stoichiometric relationship. Thus 0.40 mol CO gives at most 0.40 mol methanol and consumes 0.80 mol H2 under the stated ideal assumptions.", sectionId: "methanol-synthesis", source: { document: "quick-revision", page: 78 }, cognitive: "application" },
    { id: "note-haloalkanes-018", text: "Invertase hydrolyses one sucrose molecule into which two monosaccharides?", options: [{ key: "a", text: "Glucose and galactose" }, { key: "b", text: "Glucose and fructose" }, { key: "c", text: "Fructose and galactose" }, { key: "d", text: "Glucose and ribose" }], answer: "b", explanation: "Sucrose hydrolysis adds water and yields glucose plus fructose. The source writes both as C6H12O6, but their identical molecular formula does not make them the same sugar.", sectionId: "ethanol-fermentation", source: { document: "quick-revision", page: 78 }, cognitive: "recall" },
    { id: "note-haloalkanes-019", text: "Which fermentation enzyme system and organism are paired in the source?", options: [{ key: "a", text: "Invertase from a mineral catalyst" }, { key: "b", text: "Pepsin from Saccharomyces yeast" }, { key: "c", text: "Zymase from Saccharomyces yeast" }, { key: "d", text: "Amylase from zinc oxide catalyst" }], answer: "c", explanation: "The source identifies zymase with Saccharomyces yeast. Invertase hydrolyses sucrose, while the zymase enzyme system carries out alcoholic fermentation.", sectionId: "ethanol-fermentation", source: { document: "quick-revision", page: 78 }, cognitive: "recall" },
    { id: "note-haloalkanes-020", text: "Ideal fermentation of 0.25 mol of glucose produces what amounts of ethanol and carbon dioxide?", options: [{ key: "a", text: "0.25 mol ethanol and 0.25 mol CO2" }, { key: "b", text: "0.50 mol ethanol and 0.25 mol CO2" }, { key: "c", text: "0.25 mol ethanol and 0.50 mol CO2" }, { key: "d", text: "0.50 mol ethanol and 0.50 mol CO2" }], answer: "d", explanation: "One glucose gives two ethanol and two CO2 in the balanced equation. Multiplying both product coefficients by 0.25 gives 0.50 mol of each product.", sectionId: "ethanol-fermentation", source: { document: "quick-revision", page: 78 }, cognitive: "application" }
  ]
};