window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["hydrocarbons"] = {
  id: "hydrocarbons",
  subject: "Chemistry",
  title: "Hydrocarbons and aromatic compounds",
  sections: [
    {
      id: "alkane-preparations",
      title: "Alkanes: hydrogenation, reduction and carbon-chain construction",
      sources: [{ document: "quick-revision", page: 75 }],
      html: "<p>In the reaction formulas R represents an alkyl group and X a halogen. The preparation list begins with hydrogenation of unsaturated hydrocarbons using Pt, Pd or Ni as catalyst.</p><ul><li>Ethene: CH<sub>2</sub>=CH<sub>2</sub> + H<sub>2</sub> &rarr; CH<sub>3</sub>CH<sub>3</sub>.</li><li>Ethyne, complete hydrogenation: HC&equiv;CH + 2H<sub>2</sub> &rarr; CH<sub>3</sub>CH<sub>3</sub>. <strong>Source correction:</strong> the printed equation shows only one H<sub>2</sub> for ethane formation; two equivalents are required by hydrogen balance.</li><li>Reduction of an alkyl halide: RX + 2[H] &rarr; RH + HX. The source places Zn/HCl over the arrow and writes H<sub>2</sub> on the reactant side. This represents reducing conditions, not a claim that molecular hydrogen without an appropriate activation system reduces every alkyl halide.</li><li><strong>Wurtz reaction:</strong> 2RX + 2Na &rarr; R-R + 2NaX, in dry ether. Coupling identical alkyl groups is the useful route to a symmetrical alkane; mixed halides generally give mixtures rather than a uniquely selected unsymmetrical product.</li><li><strong>Soda-lime decarboxylation:</strong> RCOONa + NaOH &rarr; RH + Na<sub>2</sub>CO<sub>3</sub>, with CaO and heat; the source gives 630 K. The product has one carbon fewer than the starting carboxylate.</li><li><strong>Kolbe electrolysis:</strong> 2RCOONa + 2H<sub>2</sub>O &rarr; R-R + 2CO<sub>2</sub> + 2NaOH + H<sub>2</sub>. The source labels this 'symmetrical alkanes only'. More precisely, a single suitable carboxylate gives the symmetrical coupling product; mixed carboxylates can give mixtures. The carboxyl carbons are lost as CO<sub>2</sub>, and the remaining R fragments couple at the anode.</li></ul><p>For example, sodium propanoate loses one carbon to give ethane in soda-lime decarboxylation, but two ethyl fragments combine to give butane in the corresponding ideal Kolbe coupling. These distinct carbon balances prevent confusing the two preparations.</p>"
    },
    {
      id: "alkane-reaction-map",
      title: "Alkanes: substitution, combustion and controlled oxidation",
      sources: [{ document: "quick-revision", page: 75 }],
      html: "<p><strong>Halogenation:</strong> exhaustive methane chlorination is represented by CH<sub>4</sub> + 4Cl<sub>2</sub> &rarr; CCl<sub>4</sub> + 4HCl. The source gives light, h&nu;, and 520-670 K as initiation conditions. Light or sufficient heating initiates the radical process; limited chlorine gives intermediate substitution products, not necessarily only carbon tetrachloride.</p><p><strong>Complete combustion:</strong> $\\mathrm{C}_n\\mathrm{H}_{2n+2}+\\frac{3n+1}{2}\\mathrm{O}_2\\rightarrow n\\mathrm{CO}_2+(n+1)\\mathrm{H}_2\\mathrm{O}$. This requires sufficient oxygen. Carbon fixes the coefficient n of CO<sub>2</sub>, hydrogen fixes n+1 of water, and oxygen balance then gives the displayed fraction.</p><p>The source gives three controlled-oxidation examples, distinct from complete combustion.</p><ul><li>CH<sub>4</sub> + O<sub>2</sub> &rarr; HCHO + H<sub>2</sub>O, with heated molybdenum oxide, printed as Mo<sub>2</sub>O<sub>3</sub>; the organic product is methanal.</li><li>2CH<sub>4</sub> + O<sub>2</sub> &rarr; 2CH<sub>3</sub>OH, with a heated copper tube; the organic product is methanol.</li><li>(CH<sub>3</sub>)<sub>3</sub>CH &rarr; (CH<sub>3</sub>)<sub>3</sub>COH, with KMnO<sub>4</sub> over the source arrow. The change replaces the tertiary C-H by C-OH, producing 2-methylpropan-2-ol.</li></ul><p><strong>Source qualification:</strong> these are idealized selective-oxidation equations. The source omits full pressure, contact-time and oxidant conditions. They must not be interpreted as reactions that cleanly occur whenever an alkane is mixed with oxygen or with cold dilute permanganate; ordinary alkanes do not give the standard alkene Baeyer test. No exact yield or complete preparative procedure is supplied.</p>"
    },
    {
      id: "alkane-reforming-conformations",
      title: "Isomerization, steam reforming, aromatization and conformers",
      sources: [{ document: "quick-revision", page: 75 }],
      html: "<ul><li><strong>Isomerization:</strong> CH<sub>3</sub>CH<sub>2</sub>CH<sub>2</sub>CH<sub>3</sub> &rarr; (CH<sub>3</sub>)<sub>3</sub>CH using anhydrous AlCl<sub>3</sub>/HCl. The source labels the reactant n-butane and the product isobutane, or 2-methylpropane. The molecular formula is unchanged.</li><li><strong>Reaction with steam:</strong> CH<sub>4</sub> + H<sub>2</sub>O &rarr; CO + 3H<sub>2</sub>, with Ni and heat. This steam-reforming equation forms carbon monoxide, not carbon dioxide.</li><li><strong>Aromatization:</strong> n-C<sub>6</sub>H<sub>14</sub> &rarr; C<sub>6</sub>H<sub>6</sub> + 4H<sub>2</sub>. The ring in the source is benzene. It lists Cr<sub>2</sub>O<sub>3</sub> or V<sub>2</sub>O<sub>5</sub> on Al<sub>2</sub>O<sub>3</sub>, 773 K and 10-20 atm. Cyclization and dehydrogenation convert the six-carbon chain into an aromatic ring.</li></ul><p><strong>Conformers:</strong> different spatial arrangements obtained by rotation about C-C single bonds without changing connectivity. The source gives 'staggered &gt; skew/gauche &gt; eclipsed' as its stability sequence.</p><p><strong>Source correction:</strong> a gauche conformer is itself staggered. For n-butane, the intended comparison is anti-staggered &gt; gauche-staggered &gt; eclipsed, with the fully eclipsed methyl-methyl arrangement least stable. For ethane, staggered is more stable than eclipsed; an anti-versus-gauche methyl comparison does not exist. Rotation has an energy barrier, so 'free rotation' does not mean all angles have equal energy.</p>"
    },
    {
      id: "alkene-preparations",
      title: "Alkenes: formula and elimination routes",
      sources: [{ document: "quick-revision", page: 75 }],
      html: "<p>Alkenes are also called olefins. C<sub>n</sub>H<sub>2n</sub> is the general formula for an acyclic hydrocarbon with one C=C bond; additional rings or multiple bonds change the formula.</p><p>The source joins four preparation arrows into one C=C product. Their readable reagent labels and intended bond changes are listed separately.</p><ul><li><strong>Alcohol dehydration:</strong> loss of OH from one carbon and H from an adjacent carbon, using concentrated H<sub>2</sub>SO<sub>4</sub> and heat, or heated Al<sub>2</sub>O<sub>3</sub>. The two catalysts are alternatives. An example is CH<sub>3</sub>CH<sub>2</sub>OH &rarr; CH<sub>2</sub>=CH<sub>2</sub> + H<sub>2</sub>O.</li><li><strong>Dehydrohalogenation:</strong> a haloalkane with a beta hydrogen gives an alkene with alcoholic KOH and heat. The eliminated atoms are H and X on adjacent carbons.</li><li><strong>Reductive dehalogenation:</strong> Zn in methanol, with heat, is shown. The standard adjacent-dihalide transformation is RCHBr-CHBrR + Zn &rarr; RCH=CHR + ZnBr<sub>2</sub>.</li><li><strong>Iodide dehalogenation:</strong> the adjacent dibromide is also shown with NaI in acetone. The ideal net change is RCHBr-CHBrR + 2NaI &rarr; RCH=CHR + 2NaBr + I<sub>2</sub>.</li></ul><p><strong>Source drawing issue:</strong> the Zn/methanol branch actually places both Br labels on the same carbon, unlike the neighbouring NaI branch. Direct removal of two halogens to expose a C=C bond is the vicinal-dihalide route written above. A geminal substrate needs a different mechanistic account, potentially involving a carbene; the scan does not state one. Whether this is an intended geminal conversion or a misplaced Br label remains unresolved, and the drawn geminal branch is not used as a scored fact.</p>"
    },
    {
      id: "alkyne-selective-reduction",
      title: "Selective reduction of an alkyne to cis or trans alkene",
      sources: [{ document: "quick-revision", page: 75 }],
      html: "<p>The source begins with an internal alkyne R-C&equiv;C-R and draws two different alkene geometries.</p><table><thead><tr><th>Reagents</th><th>Product geometry</th></tr></thead><tbody><tr><td>Na in liquid NH<sub>3</sub>; source temperature 196-200 K</td><td>Trans RCH=CHR: the two R groups lie on opposite sides of the double bond</td></tr><tr><td>H<sub>2</sub>, Lindlar catalyst</td><td>Cis RCH=CHR: the two R groups lie on the same side of the double bond</td></tr></tbody></table><p>Lindlar hydrogenation adds hydrogen syn and stops at the alkene stage under suitable conditions. Dissolving-metal reduction gives the trans alkene through electron-transfer and protonation steps. By contrast, ordinary active Pt, Pd or Ni with sufficient hydrogen can continue to the alkane.</p><p><strong>Source correction:</strong> the diagram labels alkyne reduction in Na/NH<sub>3</sub> 'Birch reduction'. The precise name here is dissolving-metal reduction of an alkyne; Birch reduction conventionally describes partial reduction of an aromatic ring. The cis/trans distinction requires an internal alkyne whose alkene product has appropriate substituents; ethene itself has no cis/trans pair.</p>"
    },
    {
      id: "alkene-addition-cleavage",
      title: "Alkene reaction map: addition, dihydroxylation and ozonolysis",
      sources: [{ document: "quick-revision", page: 75 }],
      html: "<p>The central structure in the source is RCH=CHR, with one hydrogen on each alkene carbon. Each branch is a separate reaction, not a consecutive sequence.</p><table><thead><tr><th>Reagent or conditions</th><th>Organic product</th></tr></thead><tbody><tr><td>X<sub>2</sub> in CCl<sub>4</sub> or ether</td><td>RCHX-CHXR, a vicinal dihalide</td></tr><tr><td>H<sub>2</sub> with Pt, Pd or Ni</td><td>RCH<sub>2</sub>-CH<sub>2</sub>R, the saturated alkane</td></tr><tr><td>H<sub>2</sub>O/H<sub>2</sub>SO<sub>4</sub></td><td>RCH<sub>2</sub>-CH(OH)R, an alcohol</td></tr><tr><td>Cold dilute alkaline KMnO<sub>4</sub>, Baeyer's reagent</td><td>RCH(OH)-CH(OH)R, a vicinal diol</td></tr><tr><td>HX</td><td>RCH<sub>2</sub>-CHXR, a haloalkane</td></tr><tr><td>First O<sub>3</sub>, then Zn/H<sub>2</sub>O</td><td>Two RCHO molecules for the symmetrical RCH=CHR drawn</td></tr></tbody></table><p>In reductive ozonolysis the C=C bond is split and each original alkene carbon becomes a carbonyl carbon. An alkene carbon bearing H gives an aldehyde; one bearing two carbon substituents gives a ketone. Thus the source's two-aldehyde result is specific to its drawn substrate, not a rule that every alkene yields two aldehydes. Cold mild permanganate preserves the carbon-carbon connection as a diol, whereas hot vigorous oxidation may cleave it.</p>"
    },
    {
      id: "markovnikov-peroxide",
      title: "Markovnikov addition and the peroxide effect",
      sources: [{ document: "quick-revision", page: 76 }, { document: "quick-revision", page: 77 }],
      html: "<p>Both source pages show addition to RCH=CH<sub>2</sub>.</p><ul><li>Ordinary ionic HBr addition: RCH=CH<sub>2</sub> + HBr &rarr; RCHBr-CH<sub>3</sub>. Hydrogen adds to the carbon already bearing more hydrogens, and Br to the more substituted carbon: the Markovnikov orientation.</li><li>HBr in the presence of peroxide: RCH=CH<sub>2</sub> + HBr &rarr; RCH<sub>2</sub>-CH<sub>2</sub>Br. Br is on the terminal, less substituted carbon: anti-Markovnikov addition, also called the peroxide or Kharasch effect.</li></ul><p>For propene these products are 2-bromopropane without peroxide and 1-bromopropane with peroxide. The peroxide reaction uses a radical chain mechanism. The conventional peroxide reversal applies to HBr, not generally to HCl or HI. The general HX arrow on page 77 denotes the usual ionic addition where applicable; reaction mechanism and substrate must be specified rather than treating every hydrogen halide identically.</p>"
    },
    {
      id: "alkyne-preparation-acidity",
      title: "Alkynes: preparation and terminal hydrogen",
      sources: [{ document: "quick-revision", page: 76 }],
      html: "<p>An alkyne is an unsaturated hydrocarbon containing at least one C&equiv;C bond. C<sub>n</sub>H<sub>2n-2</sub> is the formula for an acyclic hydrocarbon with one triple bond and no additional unsaturation.</p><ul><li><strong>Double dehydrohalogenation:</strong> CH<sub>2</sub>Br-CH<sub>2</sub>Br &rarr; HC&equiv;CH. The source places alcoholic KOH and NaNH<sub>2</sub> on the arrow. The first elimination forms a vinyl halide; the stronger base is needed for the difficult second elimination. The overall change removes two HBr equivalents.</li><li><strong>Laboratory carbide method:</strong> CaC<sub>2</sub> + 2H<sub>2</sub>O &rarr; HC&equiv;CH + Ca(OH)<sub>2</sub>. The compressed source arrow omits the calcium hydroxide product; it is included here to conserve atoms.</li><li><strong>Acidic nature:</strong> the source shows ethyne reacting with sodium at 475 K to form sodium hydrogen acetylide and hydrogen. An integer-balanced representation is 2HC&equiv;CH + 2Na &rarr; 2Na<sup>+</sup>[C&equiv;CH]<sup>-</sup> + H<sub>2</sub>.</li></ul><p>Acetylide formation requires a terminal C&equiv;C-H bond. An internal alkyne has no such terminal hydrogen. The relative acidity is associated with stabilization of negative charge on sp carbon; it does not make ethyne a strong aqueous acid or allow every weak base to remove its proton quantitatively.</p>"
    },
    {
      id: "alkyne-reactions-polymers",
      title: "Ethyne additions, hydration and polymerization",
      sources: [{ document: "quick-revision", page: 76 }],
      html: "<p>The source's four addition sequences all begin with HC&equiv;CH.</p><ol><li><strong>Hydrogen:</strong> HC&equiv;CH + H<sub>2</sub> &rarr; CH<sub>2</sub>=CH<sub>2</sub>; then CH<sub>2</sub>=CH<sub>2</sub> + H<sub>2</sub> &rarr; CH<sub>3</sub>CH<sub>3</sub>. Ni and 523-573 K appear on the first arrow. Active Ni does not guarantee selective isolation of the intermediate alkene; both stages can proceed.</li><li><strong>Chlorine in CCl<sub>4</sub>:</strong> HC&equiv;CH + Cl<sub>2</sub> &rarr; CHCl=CHCl; then CHCl=CHCl + Cl<sub>2</sub> &rarr; CHCl<sub>2</sub>-CHCl<sub>2</sub>. The final product is 1,1,2,2-tetrachloroethane.</li><li><strong>Hydrogen bromide:</strong> HC&equiv;CH + HBr &rarr; CH<sub>2</sub>=CHBr; then CH<sub>2</sub>=CHBr + HBr &rarr; CH<sub>3</sub>CHBr<sub>2</sub>, a geminal dibromide. These arrows depict ordinary addition without peroxide.</li><li><strong>Hydration:</strong> HC&equiv;CH + H<sub>2</sub>O &rarr; CH<sub>2</sub>=CHOH with H<sub>2</sub>SO<sub>4</sub>/HgSO<sub>4</sub>, 333 K as printed. The enol, vinyl alcohol, tautomerizes to CH<sub>3</sub>CHO, ethanal. The final isolated carbonyl is not ethanol. Ethyne is the terminal-alkyne exception that gives an aldehyde in this mercury-catalysed hydration; ordinary R-C&equiv;CH substrates give methyl ketones.</li></ol><p><strong>Linear polymerization:</strong> ethyne forms polyethyne, or polyacetylene, with repeating -CH=CH- units. The atom-balanced notation is nHC&equiv;CH &rarr; [-CH=CH-]<sub>n</sub>. <strong>Source correction:</strong> the source writes a four-carbon -CH=CH-CH=CH- unit with only n ethyne molecules; that alternative repeat unit requires 2n ethyne molecules.</p><p><strong>Cyclic polymerization or trimerization:</strong> 3HC&equiv;CH &rarr; C<sub>6</sub>H<sub>6</sub>, in a red-hot iron tube. The six-membered aromatic ring drawn is benzene, formed from three two-carbon molecules.</p>"
    },
    {
      id: "aromaticity",
      title: "Arenes and the aromaticity requirements",
      sources: [{ document: "quick-revision", page: 76 }],
      html: "<p>Aromatic hydrocarbons are called arenes. The source describes compounds containing one or more benzene rings, either fused or isolated. This describes benzenoid arenes; aromatic hydrocarbons also include non-benzenoid systems, so a benzene ring is not a universal requirement.</p><p><strong>Huckel rule:</strong> the source specifies (4n + 2) pi electrons in the ring and planarity allowing complete pi-electron delocalization. The full elementary condition is a cyclic, planar, continuously conjugated pi system with 4n + 2 pi electrons, where n is a nonnegative integer. Benzene has six pi electrons, so n = 1. Merely finding six pi electrons somewhere in a molecule is insufficient if a nonconjugated atom interrupts the ring.</p>"
    },
    {
      id: "benzene-reactions",
      title: "Benzene reaction chart: substitution, addition and combustion",
      sources: [{ document: "quick-revision", page: 76 }],
      html: "<p>Each branch of the source chart begins independently with benzene. The ring drawings and their labels correspond to the following compounds and conditions.</p><table><thead><tr><th>Reaction and source conditions</th><th>Product or balanced change</th></tr></thead><tbody><tr><td>Sulfonation; H<sub>2</sub>SO<sub>4</sub>, heat</td><td>C<sub>6</sub>H<sub>5</sub>SO<sub>3</sub>H, benzenesulfonic acid; H is replaced by SO<sub>3</sub>H</td></tr><tr><td>Friedel-Crafts acylation; RCOCl, anhydrous AlCl<sub>3</sub></td><td>C<sub>6</sub>H<sub>5</sub>COR + HCl, an aryl ketone</td></tr><tr><td>Friedel-Crafts alkylation; RCl, anhydrous AlCl<sub>3</sub></td><td>C<sub>6</sub>H<sub>5</sub>R + HCl, an alkylbenzene</td></tr><tr><td>Monochlorination; Cl<sub>2</sub>, anhydrous AlCl<sub>3</sub></td><td>C<sub>6</sub>H<sub>5</sub>Cl + HCl, chlorobenzene</td></tr><tr><td>Exhaustive substitution; source lists 6Cl<sub>2</sub>, anhydrous AlCl<sub>3</sub>, dark and cold</td><td>C<sub>6</sub>Cl<sub>6</sub> + 6HCl, hexachlorobenzene, with six ring hydrogens replaced</td></tr><tr><td>Nitration; concentrated HNO<sub>3</sub> and H<sub>2</sub>SO<sub>4</sub>, 323-333 K</td><td>C<sub>6</sub>H<sub>5</sub>NO<sub>2</sub> + H<sub>2</sub>O, nitrobenzene</td></tr></tbody></table><p>The exhaustive-chlorination arrow is an idealized net substitution; its brief 'dark, cold' label does not establish that ordinary mild monochlorination conditions will cleanly replace all six hydrogens. Friedel-Crafts alkylation may rearrange and polyalkylate; the R label alone is not a guarantee of one product for every alkyl chloride.</p><ul><li><strong>Combustion:</strong> $\\mathrm{C}_6\\mathrm{H}_6+\\frac{15}{2}\\mathrm{O}_2\\rightarrow6\\mathrm{CO}_2+3\\mathrm{H}_2\\mathrm{O}$. This is complete oxidation, not aromatic substitution.</li><li><strong>Photochemical chlorine addition:</strong> C<sub>6</sub>H<sub>6</sub> + 3Cl<sub>2</sub> &rarr; C<sub>6</sub>H<sub>6</sub>Cl<sub>6</sub>. The source lists UV and 500 K and draws a saturated six-membered ring with one chlorine on each carbon. The important distinction is addition under photochemical conditions versus Lewis-acid-catalysed substitution; the stated temperature is not a universal requirement.</li><li><strong>Hydrogenation:</strong> C<sub>6</sub>H<sub>6</sub> + 3H<sub>2</sub> &rarr; C<sub>6</sub>H<sub>12</sub>, with Ni under suitable hydrogenation conditions. The product ring is cyclohexane.</li></ul><p><strong>Source correction:</strong> the addition product is hexachlorocyclohexane, historically benzene hexachloride or BHC. Lindane is specifically its gamma isomer, not the name of every BHC isomer or the unseparated mixture. Hexachlorobenzene, C<sub>6</sub>Cl<sub>6</sub>, is a different aromatic substitution product and contains no hydrogens.</p>"
    },
    {
      id: "aromatic-directing-groups",
      title: "Activation and orientation in aromatic substitution",
      sources: [{ document: "quick-revision", page: 76 }],
      html: "<p>An ortho/para-directing substituent favours attack at positions 2 and 4 relative to itself; a meta director favours position 3. Symmetry-related positions are equivalent when no other substituents break the symmetry.</p><ul><li><strong>Activating, ortho/para-directing groups listed:</strong> -CH<sub>3</sub>, -C<sub>2</sub>H<sub>5</sub>, -OCH<sub>3</sub>, -NH<sub>2</sub>, -NHR and -NHCOCH<sub>3</sub>. The last group is attached to the ring through nitrogen, not through the carbonyl carbon.</li><li><strong>Halogen exception:</strong> halogens direct ortho/para but deactivate the ring overall because their electron-withdrawing inductive effect outweighs their resonance donation in the overall rate comparison.</li><li><strong>Deactivating, meta-directing groups listed:</strong> -NO<sub>2</sub>, -CN, -CHO, -COR, -COOH, -COOR and -SO<sub>3</sub>H.</li></ul><p>Activation compares reactivity with benzene; orientation predicts preferred substitution position. They are related but not identical properties. Strongly acidic conditions can change the identity of a substituent: protonated aniline is not the same directing species as neutral -NH<sub>2</sub>.</p>"
    },
    {
      id: "haloalkane-source-transition",
      title: "Haloalkane definitions and radical chlorination at the page boundary",
      sources: [{ document: "quick-revision", page: 76 }],
      html: "<p>The lower right of page 76 begins Haloalkanes and Haloarenes. A haloalkane is obtained formally by replacing one or more alkane hydrogens by the same number of halogen atoms. A halobenzene has a halogen directly replacing a hydrogen on the benzene ring; direct aryl attachment differs from a halogen on an alkyl side chain.</p><p>The source's methane arrow under UV light or heat lists CH<sub>3</sub>Cl, CH<sub>2</sub>Cl<sub>2</sub>, CHCl<sub>3</sub>, CCl<sub>4</sub> and HCl together. <strong>Source correction:</strong> that is a list of possible successive substitution products, not one balanced equation with one methane molecule producing all four organic compounds.</p><ol><li>CH<sub>4</sub> + Cl<sub>2</sub> &rarr; CH<sub>3</sub>Cl + HCl.</li><li>CH<sub>3</sub>Cl + Cl<sub>2</sub> &rarr; CH<sub>2</sub>Cl<sub>2</sub> + HCl.</li><li>CH<sub>2</sub>Cl<sub>2</sub> + Cl<sub>2</sub> &rarr; CHCl<sub>3</sub> + HCl.</li><li>CHCl<sub>3</sub> + Cl<sub>2</sub> &rarr; CCl<sub>4</sub> + HCl.</li></ol>"
    },
    {
      id: "alcohol-to-halide-exchange",
      title: "Page 77: alcohol conversion and halogen exchange",
      sources: [{ document: "quick-revision", page: 77 }],
      html: "<p>Page 77 is assigned to this digital topic even though its printed heading continues haloalkane chemistry. Its preparation map has ROH at the centre.</p><ul><li>ROH + PCl<sub>5</sub> &rarr; RCl + POCl<sub>3</sub> + HCl.</li><li>Red phosphorus with X<sub>2</sub> generates a phosphorus halide in situ, converting ROH to RX; the source does not supply a complete balanced equation for this branch.</li><li>ROH + SOCl<sub>2</sub> &rarr; RCl + SO<sub>2</sub> + HCl, with pyridine shown. Thionyl chloride replaces OH with Cl and gives gaseous by-products.</li><li>ROH + HCl &rarr; RCl + H<sub>2</sub>O, with anhydrous ZnCl<sub>2</sub>.</li><li>ROH + NaBr + H<sub>2</sub>SO<sub>4</sub> &rarr; RBr + NaHSO<sub>4</sub> + H<sub>2</sub>O, representing HBr generated in situ. Sulfuric-acid concentration matters because overly oxidizing conditions can oxidize bromide.</li><li>3ROH + PX<sub>3</sub> &rarr; 3RX + H<sub>3</sub>PO<sub>3</sub>. <strong>Source correction:</strong> the source compresses this to one ROH and one RX; the coefficient three is required.</li></ul><p><strong>Finkelstein reaction:</strong> RX + NaI &rarr; RI + NaX in dry acetone, normally starting from a suitable alkyl chloride or bromide. Precipitation of NaCl or NaBr helps drive exchange. <strong>Swarts reaction:</strong> RX + AgF &rarr; RF + AgX; this is the source's fluorination reagent. These substitution preparations depend on substrate structure and are not blanket methods for replacing halogen on every aryl carbon.</p>"
    },
    {
      id: "aryl-halide-preparation",
      title: "Page 77: aryl halides and diazonium replacements",
      sources: [{ document: "quick-revision", page: 77 }],
      html: "<p><strong>Ring halogenation:</strong> C<sub>6</sub>H<sub>6</sub> + X<sub>2</sub> &rarr; C<sub>6</sub>H<sub>5</sub>X + HX, with FeCl<sub>3</sub> printed over the general arrow. The common applications are chlorine/FeCl<sub>3</sub> and bromine/FeBr<sub>3</sub>; fluorination and iodination should not be assumed to behave identically under this generic label.</p><p>The centre of the next diagram is benzenediazonium chloride, [C<sub>6</sub>H<sub>5</sub>N<sub>2</sub>]<sup>+</sup>Cl<sup>-</sup>. Every replacement releases nitrogen gas.</p><table><thead><tr><th>Branch</th><th>Product and source interpretation</th></tr></thead><tbody><tr><td>KI</td><td>C<sub>6</sub>H<sub>5</sub>I + N<sub>2</sub> + KCl; copper catalyst is unnecessary</td></tr><tr><td>CuCl/HCl, Sandmeyer</td><td>Chlorobenzene + N<sub>2</sub>; the source uses the older Cu<sub>2</sub>Cl<sub>2</sub> notation</td></tr><tr><td>CuBr/HBr, Sandmeyer</td><td>Bromobenzene + N<sub>2</sub>; the source writes Cu<sub>2</sub>Br<sub>2</sub> but prints HCl below that branch</td></tr><tr><td>HBF<sub>4</sub>, followed by heating the diazonium tetrafluoroborate</td><td>Fluorobenzene + BF<sub>3</sub> + N<sub>2</sub>, the Balz-Schiemann reaction</td></tr></tbody></table><p><strong>Source corrections:</strong> the conventional bromide preparation uses the matching CuBr/HBr system rather than treating the printed HCl as its defining condition. In the fluorination branch the source prints NaNO<sub>2</sub>/HBF<sub>4</sub> beside an already formed diazonium salt. Nitrite belongs to diazotization when starting from an arylamine; replacement of an existing diazonium chloride requires formation of the BF<sub>4</sub><sup>-</sup> salt and thermal decomposition. The balanced decomposition is [C<sub>6</sub>H<sub>5</sub>N<sub>2</sub>]BF<sub>4</sub> &rarr; C<sub>6</sub>H<sub>5</sub>F + BF<sub>3</sub> + N<sub>2</sub>.</p>"
    },
    {
      id: "nucleophile-product-map",
      title: "Page 77: nucleophile-to-product map",
      sources: [{ document: "quick-revision", page: 77 }],
      html: "<p>The source polarizes the substrate bond as C<sup>&delta;+</sup>-X<sup>&delta;-</sup>. A nucleophile attacks carbon and the leaving group departs with the C-X bond pair: Nu<sup>-</sup> + RX &rarr; RNu + X<sup>-</sup>.</p><table><thead><tr><th>Reagent added to RX</th><th>Main textbook substitution product</th></tr></thead><tbody><tr><td>Aqueous KOH</td><td>ROH + KX, an alcohol</td></tr><tr><td>NaOR'</td><td>ROR' + NaX, an ether: Williamson synthesis</td></tr><tr><td>Alcoholic KCN</td><td>RCN + KX, a nitrile or alkyl cyanide</td></tr><tr><td>Alcoholic AgCN</td><td>RNC + AgX, an isocyanide</td></tr><tr><td>AgNO<sub>2</sub></td><td>RNO<sub>2</sub> + AgX, a nitroalkane</td></tr><tr><td>KNO<sub>2</sub></td><td>RONO + KX, an alkyl nitrite</td></tr><tr><td>R'COOAg</td><td>R'COOR + AgX, an ester</td></tr><tr><td>NaSR'</td><td>RSR' + NaX, a sulfide or thioether</td></tr></tbody></table><p><strong>Source corrections:</strong> RONO is labelled 'alkyl nitrile' in the scan; it is an alkyl nitrite, with an O-N connection. The NaSR branch is drawn giving RSH + Na; sodium thiolate actually supplies SR' and gives a thioether plus NaX. To obtain RSH by the corresponding simple substitution use NaSH: RX + NaSH &rarr; RSH + NaX. These are different nucleophiles and different products.</p><p>CN<sup>-</sup> and NO<sub>2</sub><sup>-</sup> are ambident nucleophiles. Their different bonding atoms explain the cyanide/isocyanide and nitro/nitrite distinctions. These are standard predominant-product comparisons under suitable conditions, not promises of quantitative selectivity for every substrate. Williamson synthesis works best with methyl or primary electrophiles; bulky substrates can eliminate.</p>"
    },
    {
      id: "sn1-sn2-stereochemistry",
      title: "Page 77: SN1 versus SN2",
      sources: [{ document: "quick-revision", page: 77 }],
      html: "<table><thead><tr><th>Feature</th><th>SN1</th><th>SN2</th></tr></thead><tbody><tr><td>Rate law in the elementary model</td><td>k[RX], first order</td><td>k[RX][Nu], second order overall</td></tr><tr><td>Bond-changing pathway</td><td>Ionization, then nucleophile capture</td><td>Concerted bond formation and cleavage</td></tr><tr><td>Intermediate</td><td>Carbocation</td><td>No intermediate; one transition state</td></tr><tr><td>Simple alkyl-substrate trend</td><td>3&deg; &gt; 2&deg; &gt; 1&deg;; methyl strongly disfavoured</td><td>Methyl &gt; 1&deg; &gt; 2&deg;; 3&deg; strongly disfavoured</td></tr><tr><td>Chiral reaction centre</td><td>Loss of stereochemical purity, often incomplete racemization</td><td>Backside attack with Walden inversion</td></tr></tbody></table><p><strong>Source corrections:</strong> an SN2 transition state is not an intermediate. The methyl symbol in the rate comparison refers to the methyl substrate, not an isolated methyl carbocation undergoing SN2. The source's SN1 phrase 'racemization and inversion' means both faces of a planar carbocation can be attacked, often with excess inversion because of ion-pair effects; it does not mean every SN1 reaction gives exactly 50:50 products. When a neutral nucleophile attacks, a subsequent proton-transfer step can be required beyond the source's two main bond-changing steps. Solvent, nucleophile, leaving group and resonance can alter the simple substrate trends.</p>"
    },
    {
      id: "optical-isomerism-elimination",
      title: "Page 77: optical relationships and beta elimination",
      sources: [{ document: "quick-revision", page: 77 }],
      html: "<ul><li><strong>Racemic mixture:</strong> an equimolar mixture of the two enantiomers, historically d and l or (+) and (-). Equal opposite optical rotations cancel, making the mixture optically inactive.</li><li><strong>Racemization:</strong> conversion of an enantiomerically enriched material toward a racemic mixture.</li><li><strong>Enantiomers:</strong> stereoisomers that are nonsuperimposable mirror images.</li><li><strong>Diastereomers:</strong> stereoisomers that are not mirror images. <strong>Source correction:</strong> calling all diastereomers 'optical isomers' is too restrictive; geometric isomers are also diastereomers, and a diastereomer need not be optically active.</li><li><strong>Meso compound:</strong> an achiral compound containing stereogenic centres, with internal symmetry making it superimposable on its mirror image. The source describes two or an even number of chiral carbons and an internal mirror plane. <strong>Source clarification:</strong> chirality must be assessed for the whole molecule; an even-number rule is not a general definition. A meso compound is one achiral substance, not an equimolar mixture of two chiral substances.</li></ul><p><strong>Beta elimination:</strong> heating a haloalkane with alcoholic KOH can remove a beta hydrogen and the leaving halogen from adjacent carbons. The printed example is RCH<sub>2</sub>-CHCl-CH<sub>3</sub> + KOH &rarr; RCH=CHCH<sub>3</sub> + KCl + H<sub>2</sub>O. Formation of a competing terminal alkene may also be possible; the displayed internal alkene is the usual more substituted product when the Zaitsev preference applies. A beta hydrogen is required for this ordinary elimination, and geometry and base bulk can affect the major product.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 75, status: "partial", sectionIds: ["alkane-preparations", "alkane-reaction-map", "alkane-reforming-conformations", "alkene-preparations", "alkyne-selective-reduction", "alkene-addition-cleavage"], unresolved: ["The Zn/methanol alkene-preparation branch draws both bromines on one carbon. The page does not resolve whether this is a misplaced Br label in the standard vicinal-dihalide route or an intended geminal conversion requiring a different mechanism; the literal geminal branch is not used in scored questions."] },
    { document: "quick-revision", page: 76, status: "transcribed", sectionIds: ["markovnikov-peroxide", "alkyne-preparation-acidity", "alkyne-reactions-polymers", "aromaticity", "benzene-reactions", "aromatic-directing-groups", "haloalkane-source-transition"], unresolved: [] },
    { document: "quick-revision", page: 77, status: "transcribed", sectionIds: ["markovnikov-peroxide", "alcohol-to-halide-exchange", "aryl-halide-preparation", "nucleophile-product-map", "sn1-sn2-stereochemistry", "optical-isomerism-elimination"], unresolved: [] }
  ],
  questions: [
    { id: "note-hydrocarbons-001", text: "How much H2 is required to convert 0.30 mol of ethyne completely into ethane?", options: [{ key: "a", text: "0.60 mol of H2" }, { key: "b", text: "0.15 mol of H2" }, { key: "c", text: "0.30 mol of H2" }, { key: "d", text: "0.90 mol of H2" }], answer: "a", explanation: "HC triple-bond CH contains two pi bonds and needs two H2 per molecule for complete saturation. Thus 0.30 times 2 = 0.60 mol H2 is required.", sectionId: "alkane-preparations", source: { document: "quick-revision", page: 75 }, cognitive: "application" },
    { id: "note-hydrocarbons-002", text: "Sodium propanoate is heated with soda lime. Which hydrocarbon follows from removal of its carboxyl carbon?", options: [{ key: "a", text: "Methane, CH4" }, { key: "b", text: "Ethane, C2H6" }, { key: "c", text: "Propane, C3H8" }, { key: "d", text: "Butane, C4H10" }], answer: "b", explanation: "Propanoate is CH3CH2COO-. Decarboxylation removes the carboxyl carbon and replaces the carboxyl group by hydrogen, giving CH3CH3 rather than the coupled product.", sectionId: "alkane-preparations", source: { document: "quick-revision", page: 75 }, cognitive: "application" },
    { id: "note-hydrocarbons-003", text: "In ideal Kolbe electrolysis of sodium propanoate alone, which hydrocarbon forms by coupling the anode radicals?", options: [{ key: "a", text: "Ethane, C2H6" }, { key: "b", text: "Propane, C3H8" }, { key: "c", text: "Butane, C4H10" }, { key: "d", text: "Hexane, C6H14" }], answer: "c", explanation: "Each propanoate loses CO2 to leave a two-carbon ethyl radical. Two ethyl radicals combine to form CH3CH2CH2CH3, so the coupled product contains four carbons.", sectionId: "alkane-preparations", source: { document: "quick-revision", page: 75 }, cognitive: "application" },
    { id: "note-hydrocarbons-004", text: "For complete combustion of 1 mol of pentane, how many moles of oxygen are required?", options: [{ key: "a", text: "5 mol of O2" }, { key: "b", text: "6 mol of O2" }, { key: "c", text: "7 mol of O2" }, { key: "d", text: "8 mol of O2" }], answer: "d", explanation: "C5H12 gives 5CO2 and 6H2O, requiring 16 oxygen atoms. Each O2 supplies two atoms, so 8 mol O2 are needed per mole of pentane.", sectionId: "alkane-reaction-map", source: { document: "quick-revision", page: 75 }, cognitive: "application" },
    { id: "note-hydrocarbons-005", text: "Which description corrects the source's comparison of staggered and gauche conformations for n-butane?", options: [{ key: "a", text: "Anti and gauche are both staggered" }, { key: "b", text: "Anti and gauche are both eclipsed" }, { key: "c", text: "Gauche has a broken central bond" }, { key: "d", text: "Anti has a different molecular formula" }], answer: "a", explanation: "Both anti and gauche n-butane have staggered bonds. Their methyl groups are separated by different dihedral angles, and anti is more stable because crowding is lower.", sectionId: "alkane-reforming-conformations", source: { document: "quick-revision", page: 75 }, cognitive: "understanding" },
    { id: "note-hydrocarbons-006", text: "But-2-yne is treated with one equivalent of hydrogen using Lindlar catalyst. Which product is expected?", options: [{ key: "a", text: "trans-But-2-ene" }, { key: "b", text: "cis-But-2-ene" }, { key: "c", text: "But-1-ene" }, { key: "d", text: "Butane" }], answer: "b", explanation: "Lindlar catalyst partially hydrogenates the triple bond with syn addition. The two methyl groups remain on the same side, giving cis-but-2-ene under selective conditions.", sectionId: "alkyne-selective-reduction", source: { document: "quick-revision", page: 75 }, cognitive: "application" },
    { id: "note-hydrocarbons-007", text: "Hex-3-ene, CH3CH2CH=CHCH2CH3, undergoes ozonolysis followed by Zn/H2O. Which organic products result?", options: [{ key: "a", text: "Two molecules of propanone" }, { key: "b", text: "Ethanal and butanone" }, { key: "c", text: "Two molecules of propanal" }, { key: "d", text: "Methanal and pentanone" }], answer: "c", explanation: "Cleavage places C=O at each original double-bond carbon. Each has H and an ethyl group, giving CH3CH2CHO on both sides; carbon count is 3 + 3 = 6.", sectionId: "alkene-addition-cleavage", source: { document: "quick-revision", page: 75 }, cognitive: "application" },
    { id: "note-hydrocarbons-008", text: "Which product distinguishes peroxide-initiated HBr addition to propene from its ordinary ionic HBr addition?", options: [{ key: "a", text: "1,2-Dibromopropane" }, { key: "b", text: "2-Bromopropane" }, { key: "c", text: "1,1-Dibromopropane" }, { key: "d", text: "1-Bromopropane" }], answer: "d", explanation: "The peroxide-initiated radical chain puts Br at the less substituted terminal carbon of propene. Ordinary ionic addition instead gives predominantly 2-bromopropane.", sectionId: "markovnikov-peroxide", source: { document: "quick-revision", page: 76 }, cognitive: "application" },
    { id: "note-hydrocarbons-009", text: "Which structural feature is required for formation of an acetylide by loss of a terminal alkyne proton?", options: [{ key: "a", text: "A C triple-bond C-H group" }, { key: "b", text: "A C triple-bond C-R group at both ends" }, { key: "c", text: "A carbonyl C=O group" }, { key: "d", text: "A benzene C-H group" }], answer: "a", explanation: "A terminal alkyne contains hydrogen directly attached to sp carbon. Internal alkynes lack that hydrogen, so the stated terminal-proton removal cannot occur.", sectionId: "alkyne-preparation-acidity", source: { document: "quick-revision", page: 76 }, cognitive: "understanding" },
    { id: "note-hydrocarbons-010", text: "After ethyne hydration with HgSO4 and aqueous sulfuric acid, which stable carbonyl product follows enol tautomerization?", options: [{ key: "a", text: "Methanal, HCHO" }, { key: "b", text: "Ethanal, CH3CHO" }, { key: "c", text: "Propanone, CH3COCH3" }, { key: "d", text: "Propanal, CH3CH2CHO" }], answer: "b", explanation: "Water addition gives CH2=CHOH, which tautomerizes to CH3CHO without changing its two-carbon skeleton. Ethyne therefore gives ethanal, not a three-carbon ketone.", sectionId: "alkyne-reactions-polymers", source: { document: "quick-revision", page: 76 }, cognitive: "application" },
    { id: "note-hydrocarbons-011", text: "Which product retains an aromatic ring after exhaustive replacement of all six benzene hydrogens by chlorine?", options: [{ key: "a", text: "C6H6Cl6, hexachlorocyclohexane" }, { key: "b", text: "C6H5Cl, chlorobenzene" }, { key: "c", text: "C6Cl6, hexachlorobenzene" }, { key: "d", text: "C6H12, cyclohexane" }], answer: "c", explanation: "Replacement of six H atoms leaves C6Cl6 and preserves the aromatic carbon skeleton. C6H6Cl6 instead comes from chlorine addition and has a saturated ring.", sectionId: "benzene-reactions", source: { document: "quick-revision", page: 76 }, cognitive: "understanding" },
    { id: "note-hydrocarbons-012", text: "Which substituent deactivates benzene overall but still directs a further electrophilic substitution mainly ortho and para?", options: [{ key: "a", text: "-NO2" }, { key: "b", text: "-COOH" }, { key: "c", text: "-CHO" }, { key: "d", text: "-Cl" }], answer: "d", explanation: "Chlorine withdraws inductively but donates a lone pair by resonance, so it deactivates overall while directing ortho/para. The other listed groups are meta directors.", sectionId: "aromatic-directing-groups", source: { document: "quick-revision", page: 76 }, cognitive: "understanding" },
    { id: "note-hydrocarbons-013", text: "Which reagent pair defines the Finkelstein conversion of a suitable primary alkyl bromide into its iodide?", options: [{ key: "a", text: "NaI in dry acetone" }, { key: "b", text: "AgF in dry ether" }, { key: "c", text: "KOH in hot ethanol" }, { key: "d", text: "NaCl in cold water" }], answer: "a", explanation: "Finkelstein exchange uses NaI in dry acetone. Formation of poorly soluble NaBr helps drive displacement of bromide by iodide on a suitable alkyl substrate.", sectionId: "alcohol-to-halide-exchange", source: { document: "quick-revision", page: 77 }, cognitive: "recall" },
    { id: "note-hydrocarbons-014", text: "Benzenediazonium chloride is treated with KI. Which aryl product and gas are expected?", options: [{ key: "a", text: "Chlorobenzene and oxygen" }, { key: "b", text: "Iodobenzene and nitrogen" }, { key: "c", text: "Nitrobenzene and hydrogen" }, { key: "d", text: "Bromobenzene and ammonia" }], answer: "b", explanation: "Iodide replaces the diazonio group, which leaves as N2. The organic product is iodobenzene; copper(I) is not required for this iodide replacement.", sectionId: "aryl-halide-preparation", source: { document: "quick-revision", page: 77 }, cognitive: "application" },
    { id: "note-hydrocarbons-015", text: "A suitable primary RX reacts separately with alcoholic KCN and AgCN. Which pairing states their predominant textbook products?", options: [{ key: "a", text: "KCN gives RNC; AgCN gives RCN" }, { key: "b", text: "KCN gives RONO; AgCN gives RNO2" }, { key: "c", text: "KCN gives RCN; AgCN gives RNC" }, { key: "d", text: "KCN gives RNO2; AgCN gives RONO" }], answer: "c", explanation: "Cyanide is ambident. KCN favours carbon bonding to form a nitrile RCN, whereas the classical AgCN comparison favours nitrogen bonding to form isocyanide RNC.", sectionId: "nucleophile-product-map", source: { document: "quick-revision", page: 77 }, cognitive: "understanding" },
    { id: "note-hydrocarbons-016", text: "Bromoethane reacts by substitution with sodium methanethiolate, NaSCH3. Which organic product conserves the nucleophile's methyl group?", options: [{ key: "a", text: "CH3CH2SH" }, { key: "b", text: "CH3CH2OH" }, { key: "c", text: "CH3CH2OCH3" }, { key: "d", text: "CH3CH2SCH3" }], answer: "d", explanation: "Methanethiolate attacks through sulfur and displaces bromide, giving ethyl methyl sulfide plus NaBr. Ethanethiol would require hydrosulfide, not methanethiolate.", sectionId: "nucleophile-product-map", source: { document: "quick-revision", page: 77 }, cognitive: "application" },
    { id: "note-hydrocarbons-017", text: "In an ideal SN2 experiment, both substrate and nucleophile concentrations are doubled while temperature and solvent are fixed. How does the rate change?", options: [{ key: "a", text: "It becomes four times as large" }, { key: "b", text: "It becomes twice as large" }, { key: "c", text: "It becomes half as large" }, { key: "d", text: "It remains the same" }], answer: "a", explanation: "The bimolecular rate law is rate = k[RX][Nu]. Doubling both concentration factors multiplies the rate by 2 times 2 = 4, provided the mechanism remains SN2.", sectionId: "sn1-sn2-stereochemistry", source: { document: "quick-revision", page: 77 }, cognitive: "application" },
    { id: "note-hydrocarbons-018", text: "Which statement describes the transition state in an SN2 substitution?", options: [{ key: "a", text: "An isolable carbocation has formed" }, { key: "b", text: "Bond formation and cleavage overlap" }, { key: "c", text: "The leaving group remains fully bonded" }, { key: "d", text: "The nucleophile acts after a stable radical" }], answer: "b", explanation: "SN2 is concerted: the new bond is partly formed as the old bond is partly broken. A transition state is a barrier configuration, not a stable or isolable intermediate.", sectionId: "sn1-sn2-stereochemistry", source: { document: "quick-revision", page: 77 }, cognitive: "understanding" },
    { id: "note-hydrocarbons-019", text: "A pure compound has stereogenic centres but is superimposable on its mirror image because of internal symmetry. Which description fits?", options: [{ key: "a", text: "A racemic mixture of two species" }, { key: "b", text: "A pair of separate enantiomers" }, { key: "c", text: "A single meso compound" }, { key: "d", text: "A pair of constitutional isomers" }], answer: "c", explanation: "A meso compound is one achiral substance containing stereogenic centres. Its inactivity is intrinsic to its symmetry, unlike cancellation between enantiomers in a racemate.", sectionId: "optical-isomerism-elimination", source: { document: "quick-revision", page: 77 }, cognitive: "understanding" },
    { id: "note-hydrocarbons-020", text: "What must a haloalkane possess for the ordinary beta elimination depicted with hot alcoholic KOH?", options: [{ key: "a", text: "A hydrogen on the leaving halogen" }, { key: "b", text: "An aromatic ring on every carbon" }, { key: "c", text: "A second halogen on the same carbon" }, { key: "d", text: "A hydrogen on an adjacent carbon" }], answer: "d", explanation: "The base removes a beta hydrogen while the halogen leaves the neighbouring alpha carbon. The new double bond forms between those adjacent carbon atoms.", sectionId: "optical-isomerism-elimination", source: { document: "quick-revision", page: 77 }, cognitive: "understanding" }
  ]
};