window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["organic-basics"] = {
  id: "organic-basics",
  subject: "Chemistry",
  title: "Organic principles and isomerism",
  sections: [
    {
      id: "organic-classification",
      title: "Organic compounds and the classification tree",
      sources: [{ document: "quick-revision", page: 73 }],
      html: "<p>Organic chemistry studies hydrocarbons and their derivatives. Catenation, the ability of carbon atoms to bond to one another, and isomerism account for the very large number of carbon compounds.</p><p>The source classification diagram can be read as the following hierarchy.</p><ul><li><strong>Acyclic or open-chain compounds:</strong> the chart calls these aliphatic. Saturated open-chain hydrocarbons are alkanes; unsaturated open-chain hydrocarbons include alkenes and alkynes.</li><li><strong>Cyclic, closed-chain or ring compounds:</strong> these divide into heterocyclic compounds, whose rings contain at least one non-carbon atom, and homocyclic compounds, whose ring atoms are all carbon.</li><li><strong>Homocyclic compounds:</strong> the chart divides these into alicyclic and aromatic compounds. Alicyclic rings may be saturated or unsaturated. Aromatic compounds are further divided into benzenoid and non-benzenoid compounds.</li></ul><p><strong>Source clarification:</strong> the tree is a teaching classification, not a claim that heterocycles cannot be aromatic. Aromaticity is possible in both carbocyclic and heterocyclic rings. Likewise, an unsaturated ring is not automatically aromatic.</p>"
    },
    {
      id: "homologues-naming-isomerism",
      title: "Homologous series, IUPAC name components and isomerism",
      sources: [{ document: "quick-revision", page: 73 }],
      html: "<p>A homologous series is a family of structurally related organic compounds with the same functional group. Successive members differ by one CH<sub>2</sub> unit, corresponding to a molecular-mass difference of about 14 u. Their shared functional group gives similar characteristic reactions, while physical properties can change along the series.</p><p>The five-part naming scheme printed in the source is: secondary prefix + primary prefix + word root + primary suffix + secondary suffix. In this school-level scheme the secondary prefix names substituents, the primary prefix can indicate a cyclic skeleton, the root indicates the parent carbon skeleton, the primary suffix indicates saturation or unsaturation, and the secondary suffix identifies the principal characteristic group. Not every name needs all five parts.</p><p>The source prints the following principal-group preference: SO<sub>3</sub>H &gt; COOH &gt; COOR &gt; COCl &gt; CONH<sub>2</sub> &gt; CN &gt; NC &gt; CHO &gt; CO &gt; OH &gt; SH &gt; NH<sub>2</sub>. Here COOR denotes an ester, COCl an acyl chloride, CONH<sub>2</sub> an amide, CN a nitrile, NC an isocyanide, CHO an aldehyde, and CO a ketone carbonyl.</p><p><strong>Source correction:</strong> this is not a reliable complete IUPAC seniority table. In particular, carboxylic acids take seniority over sulfonic acids, and isocyanides should not be inserted as an ordinary principal suffix between nitriles and aldehydes. For the common functional groups represented here, carboxylic-acid derivatives precede nitriles, aldehydes precede ketones, ketones precede alcohols, alcohols precede thiols, and thiols precede amines. A multifunctional compound must be named using the applicable IUPAC parent and suffix rules, not the uncorrected printed chain.</p><p><strong>Isomerism:</strong> two or more compounds have the same molecular formula but different arrangements of atoms. The source describes them as having different properties. More precisely, constitutional isomers differ in connectivity and stereoisomers differ in spatial arrangement; not every measurable property must differ. For example, enantiomers have identical ordinary physical properties in an achiral environment apart from the direction of optical rotation.</p>"
    },
    {
      id: "cleavage-reagents",
      title: "Bond cleavage and attacking reagents",
      sources: [{ document: "quick-revision", page: 73 }],
      html: "<p><strong>Heterolytic cleavage:</strong> both electrons of a covalent bond go to one fragment. The products are ions; cleavage involving carbon can produce a carbocation or a carbanion, depending on which fragment receives the electron pair. A schematic C-X cleavage giving C<sup>+</sup> and X<sup>-</sup> conserves the original overall charge.</p><p><strong>Homolytic cleavage:</strong> each fragment receives one electron of the original bond pair, producing free radicals. A radical has an unpaired electron; the source's expression 'an paired electron' is a typographical error for 'unpaired electron'.</p><ul><li><strong>Nucleophile:</strong> the source mnemonic is 'nucleus-loving reagent'. Chemically, a nucleophile donates an electron pair to an electron-deficient centre. A neutral species with a lone pair can be a nucleophile; a negative charge is not essential.</li><li><strong>Electrophile:</strong> the source mnemonic is 'electron-loving reagent'. An electrophile accepts an electron pair from an electron-rich species. An electrophile need not carry a positive formal charge.</li></ul>"
    },
    {
      id: "reaction-intermediates",
      title: "Carbocations, carbanions and carbon radicals",
      sources: [{ document: "quick-revision", page: 73 }],
      html: "<table><thead><tr><th>Intermediate</th><th>Charge or electron state</th><th>Usual simple-alkyl geometry</th></tr></thead><tbody><tr><td>Carbocation</td><td>Positively charged carbon</td><td>sp<sup>2</sup>, trigonal planar, with an empty p orbital</td></tr><tr><td>Carbanion</td><td>Negatively charged carbon with a lone pair</td><td>Usually sp<sup>3</sup>, pyramidal</td></tr><tr><td>Carbon radical</td><td>Carbon with an unpaired electron</td><td>Approximately sp<sup>2</sup> and planar for the simple examples</td></tr></tbody></table><table><thead><tr><th>Simple alkyl intermediate</th><th>Source stability order</th></tr></thead><tbody><tr><td>Carbocation</td><td>3&deg; &gt; 2&deg; &gt; 1&deg;</td></tr><tr><td>Carbanion</td><td>1&deg; &gt; 2&deg; &gt; 3&deg;</td></tr><tr><td>Free radical</td><td>3&deg; &gt; 2&deg; &gt; 1&deg;</td></tr></tbody></table><p>The degree counts carbon groups directly attached to the reactive carbon. Alkyl donation and hyperconjugation help stabilize simple carbocations and radicals, whereas alkyl electron donation tends to destabilize a localized negative charge.</p><p><strong>Conditions on the table:</strong> these are comparisons among otherwise similar, non-resonance-stabilized alkyl species. Resonance, electron-withdrawing substituents, hybridization and solvent can change the order. A conjugated carbanion can be planar, and not every carbon radical has exactly the same geometry. The table must not be applied indiscriminately to allylic, benzylic, vinylic or aryl intermediates.</p>"
    },
    {
      id: "electronic-effects",
      title: "Inductive, electromeric and resonance effects",
      sources: [{ document: "quick-revision", page: 73 }],
      html: "<p><strong>Inductive effect:</strong> displacement or polarization of sigma-bond electron density along a carbon chain by an electron-withdrawing or electron-donating substituent. It is transmitted through sigma bonds and diminishes with distance; it is not complete movement of a bonded electron pair to a different molecule.</p><ul><li>The source's decreasing -I sequence is NO<sub>2</sub> &gt; CN &gt; COOH &gt; F &gt; Cl &gt; Br &gt; I &gt; H. These labels mean attached substituent groups, with hydrogen used as a comparison reference.</li><li>The source's decreasing +I sequence is (CH<sub>3</sub>)<sub>3</sub>C- &gt; (CH<sub>3</sub>)<sub>2</sub>CH- &gt; CH<sub>3</sub>CH<sub>2</sub>- &gt; CH<sub>3</sub>- &gt; H: tert-butyl, isopropyl, ethyl, methyl, hydrogen.</li></ul><p><strong>Electromeric effect:</strong> in the source's traditional terminology, an attacking reagent induces complete transfer of a multiple-bond pi-electron pair toward one of the bonded atoms. It is a temporary reaction-induced effect, unlike the permanent polarization described by the inductive effect.</p><p><strong>Resonance or mesomeric effect:</strong> delocalization of pi electrons, or of a suitable lone pair, through a conjugated system. The nuclei do not move between resonance contributors; the contributors describe one delocalized species.</p><p>The source prints the +R/+M line as OH &gt; OR &gt; SH &gt; SR &gt; NH<sub>2</sub> &gt; NR<sub>2</sub> &gt; I &lt; Br &lt; Cl, and the -R/-M line as C=O &gt; CHO &gt; COOR &gt; CN &gt; NO<sub>2</sub>.</p><p><strong>Source correction:</strong> these printed inequalities are not a dependable universal ranking of resonance strength; the +R line even changes inequality direction at iodine. Retain the useful classification instead: appropriately attached OH, OR, SH, SR, amino groups and halogens can donate a lone pair by resonance; carbonyl-containing groups, CN and NO<sub>2</sub> can withdraw through a conjugated pi system. The attachment point, charge and molecular environment matter. Halogens combine a withdrawing -I effect with a donating +R effect, so the two labels must not be treated as interchangeable.</p>"
    },
    {
      id: "hyperconjugation",
      title: "Hyperconjugation and the alpha-hydrogen count",
      sources: [{ document: "quick-revision", page: 73 }, { document: "quick-revision", page: 74 }],
      html: "<p>Hyperconjugation is delocalization of sigma electrons, commonly from a C-H bond of an alkyl group directly adjacent to an unsaturated or electron-deficient centre, into an appropriately aligned neighbouring orbital. The source calls it sigma-pi conjugation and 'no-bond resonance', and associates it with the Baker-Nathan effect.</p><p><strong>Source correction:</strong> page 73 also calls this the 'anchimeric effect'. Anchimeric assistance is neighbouring-group participation in a reaction and is not another name for hyperconjugation. The Baker-Nathan effect is a historical substituent-reactivity observation discussed in relation to hyperconjugation, not a definition of every hyperconjugative interaction.</p><p>Page 74 prints 'number of resonating structures due to hyperconjugation = number of alpha H - 1'. <strong>Source correction:</strong> in the elementary no-bond representation, the number of C-H hyperconjugative contributors is the number of eligible adjacent alpha C-H bonds, not that number minus one. If the ordinary bonded contributor is included, the total number of depicted contributors is one more, not one less.</p><p>For the source's comparison of a single alkyl substituent attached to the same unsaturated system, methyl has three eligible hydrogens on its directly attached carbon, ethyl two, isopropyl one, and tert-butyl none. Thus the elementary alpha-C-H count follows CH<sub>3</sub>- &gt; CH<sub>3</sub>CH<sub>2</sub>- &gt; (CH<sub>3</sub>)<sub>2</sub>CH- &gt; (CH<sub>3</sub>)<sub>3</sub>C-. This is opposite to the printed +I alkyl order because the two effects use different comparisons. It is not a general ranking of every reaction rate or every possible C-C hyperconjugative contribution.</p>"
    },
    {
      id: "quantitative-element-analysis",
      title: "Quantitative analysis: element and method",
      sources: [{ document: "quick-revision", page: 74 }],
      html: "<table><thead><tr><th>Element</th><th>Method named in the source</th></tr></thead><tbody><tr><td>Carbon and hydrogen</td><td>Liebig's combustion method</td></tr><tr><td>Nitrogen</td><td>Dumas method, measured as N<sub>2</sub>; Kjeldahl's method, determined through NH<sub>3</sub></td></tr><tr><td>Halogen</td><td>Carius method</td></tr><tr><td>Sulfur</td><td>Carius method</td></tr><tr><td>Phosphorus</td><td>Ignition method</td></tr><tr><td>Oxygen</td><td>Iodine method</td></tr></tbody></table><p>Liebig combustion determines carbon and hydrogen through the carbon dioxide and water produced. Dumas measures nitrogen gas; Kjeldahl converts suitable organic nitrogen to ammonium compounds and then liberates ammonia for determination. The latter is not automatically suitable for every nitro, azo or ring-nitrogen compound without modification. Classical Carius halogen determination uses silver-halide formation and is normally applied to chlorine, bromine and iodine, not soluble silver fluoride.</p><p>The source's 'iodine method' denotes an indirect oxygen determination through iodine liberation, not simply adding iodine to the original compound. In the classical method oxygen is converted to carbon monoxide, which reduces iodine pentoxide: 5CO + I<sub>2</sub>O<sub>5</sub> &rarr; I<sub>2</sub> + 5CO<sub>2</sub>. The iodine formed is related to the oxygen in the analysed sample. The table only names the phosphorus ignition method; it does not supply a full experimental procedure.</p>"
    },
    {
      id: "crystallization-sublimation",
      title: "Crystallization and sublimation",
      sources: [{ document: "quick-revision", page: 74 }],
      html: "<table><thead><tr><th>Method</th><th>Principle and source examples</th></tr></thead><tbody><tr><td>Crystallization</td><td>Different solubilities of the desired compound and impurities in the same solvent. The source lists glucose and fructose; sugar and common salt; and a mixture of naphthalene and phthalic acid.</td></tr><tr><td>Sublimation</td><td>Conversion of a solid directly to vapour, followed by deposition, without collecting an intervening liquid. The source lists iodine from sodium chloride, camphor, naphthalene, anthracene, benzoic acid, NH<sub>4</sub>Cl and indigo.</td></tr></tbody></table><p>A crystallization solvent must be chosen for the actual solubility contrast; listing two solids does not mean every solvent will separate them. In fractional crystallization, the less soluble component can crystallize first under the selected conditions.</p><p>For iodine mixed with sodium chloride, iodine is transferred to the vapour and deposited on a cool surface while the nonvolatile salt remains. Some entries need qualification: ammonium chloride undergoes dissociation to ammonia and hydrogen chloride vapours and recombination on cooling, often called dissociative sublimation. Indigo and other less volatile solids require suitable temperature and pressure conditions; the source list is not a claim that all sublime readily under identical conditions.</p>"
    },
    {
      id: "distillation-methods",
      title: "Simple, steam, azeotropic and vacuum distillation",
      sources: [{ document: "quick-revision", page: 74 }],
      html: "<p><strong>Distillation:</strong> separates a volatile liquid from nonvolatile material, or separates liquids with a sufficient boiling-point difference by vaporization and condensation. Under simple distillation the source lists hexane and toluene, benzene and aniline, and benzene and toluene. Close-boiling mixtures or stringent purity requirements may need fractional rather than a single simple distillation.</p><p><strong>Steam distillation:</strong> the application list begins on the left and continues at the top of the right-hand page. It includes sandalwood oil purification, turpentine oil, essential oils, aniline purification, and separation of ortho- and para-nitrophenol. The method applies to suitably steam-volatile material that is immiscible or only sparingly miscible with water. In the nitrophenol pair, intramolecular hydrogen bonding makes the ortho isomer more steam-volatile, whereas intermolecular association reduces the volatility of the para isomer.</p><p><strong>Azeotropic mixtures:</strong> a mixture at the azeotropic composition boils with vapour and liquid of the same composition at a specified pressure. The source lists rectified spirit as 95.87% ethanol and 4.13% water in its azeotropic-distillation row.</p><p><strong>Source correction:</strong> the source gives no mass or volume basis for those percentages. The familiar ethanol-water azeotrope at approximately atmospheric pressure is about 95.6% ethanol by mass, and its composition depends on pressure. Do not use 95.87% as an exact universal constant or suggest ordinary fractional distillation can cross the azeotropic composition. Azeotropic distillation requires a changed separation strategy, commonly an entrainer; it is not merely a synonym for distilling any constant-boiling mixture.</p><p><strong>Vacuum distillation:</strong> distillation at reduced pressure lowers the boiling temperature and is useful for high-boiling or thermally unstable liquids that decompose near their ordinary boiling points. The source examples are glycerin and concentration of raw juice in sugar factories. In the sugar example the reduced-pressure operation removes water while limiting heat damage; sugar itself is not distilled.</p>"
    },
    {
      id: "atmolysis-chromatography",
      title: "Atmolysis and chromatography",
      sources: [{ document: "quick-revision", page: 74 }],
      html: "<p><strong>Atmolysis:</strong> separation or enrichment of a gas mixture based on different diffusion rates, classically through a porous partition. The source lists CH<sub>4</sub>/O<sub>2</sub> and H<sub>2</sub>/O<sub>2</sub> as examples. At the same temperature and under comparable conditions, the lighter gas diffuses faster. These are theoretical separation examples, not instructions for handling potentially combustible mixtures.</p><p><strong>Chromatography:</strong> components of a mixture move differently through or along a stationary phase under the influence of a mobile phase because of their different interactions with the phases. The source applications are purification and separation of complex mixtures of organic substances, including proteins, amino acids, vitamins and hormones. The stationary and mobile phases have distinct roles; the method is not defined simply by boiling point or by one component being coloured.</p>"
    },
    {
      id: "alkane-transition",
      title: "Beginning of the hydrocarbons material on page 74",
      sources: [{ document: "quick-revision", page: 74 }],
      html: "<p>The bottom of the assigned page begins the next source heading, Hydrocarbons, with two alkane facts: the general formula is C<sub>n</sub>H<sub>2n+2</sub>, and all carbon atoms are sp<sup>3</sup>-hybridized. The formula is for acyclic saturated hydrocarbons, not cycloalkanes. These two lines are retained here because they are actually on page 74; subsequent hydrocarbon reactions belong to the following assigned pages.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 73, status: "transcribed", sectionIds: ["organic-classification", "homologues-naming-isomerism", "cleavage-reagents", "reaction-intermediates", "electronic-effects", "hyperconjugation"], unresolved: [] },
    { document: "quick-revision", page: 74, status: "transcribed", sectionIds: ["hyperconjugation", "quantitative-element-analysis", "crystallization-sublimation", "distillation-methods", "atmolysis-chromatography", "alkane-transition"], unresolved: [] }
  ],
  questions: [
    { id: "note-organic-basics-001", text: "A nonaromatic ring contains only carbon atoms and one C=C bond. Which description fits it?", options: [{ key: "a", text: "Unsaturated alicyclic compound" }, { key: "b", text: "Saturated heterocyclic compound" }, { key: "c", text: "Unsaturated acyclic compound" }, { key: "d", text: "Benzenoid aromatic compound" }], answer: "a", explanation: "An all-carbon ring is homocyclic. Since it is explicitly nonaromatic, it is alicyclic; the C=C bond makes it unsaturated.", sectionId: "organic-classification", source: { document: "quick-revision", page: 73 }, cognitive: "application" },
    { id: "note-organic-basics-002", text: "Two adjacent members of a homologous series differ by which molecular unit?", options: [{ key: "a", text: "CH, approximately 13 u" }, { key: "b", text: "CH2, approximately 14 u" }, { key: "c", text: "CH3, approximately 15 u" }, { key: "d", text: "C2H2, approximately 26 u" }], answer: "b", explanation: "Successive homologues retain the same functional group and differ by CH2. Using C = 12 and H = 1 gives a mass difference of 14 u.", sectionId: "homologues-naming-isomerism", source: { document: "quick-revision", page: 73 }, cognitive: "recall" },
    { id: "note-organic-basics-003", text: "In the source's five-part naming scheme, which component identifies the principal functional group?", options: [{ key: "a", text: "The primary prefix" }, { key: "b", text: "The secondary prefix" }, { key: "c", text: "The secondary suffix" }, { key: "d", text: "The carbon word root" }], answer: "c", explanation: "The secondary suffix denotes the principal characteristic group. The primary suffix instead indicates saturation or unsaturation of the parent.", sectionId: "homologues-naming-isomerism", source: { document: "quick-revision", page: 73 }, cognitive: "recall" },
    { id: "note-organic-basics-004", text: "Two molecules have the same molecular formula but different carbon-to-carbon connectivity. What relationship is established?", options: [{ key: "a", text: "They are successive homologues" }, { key: "b", text: "They are resonance contributors" }, { key: "c", text: "They are isotopic substitutions" }, { key: "d", text: "They are constitutional isomers" }], answer: "d", explanation: "Constitutional isomers have the same formula but different connectivity. Resonance contributors preserve atom connectivity and differ only in electron representation.", sectionId: "homologues-naming-isomerism", source: { document: "quick-revision", page: 73 }, cognitive: "understanding" },
    { id: "note-organic-basics-005", text: "When a covalent bond breaks so that each fragment receives one bonding electron, which process has occurred?", options: [{ key: "a", text: "Homolysis producing radicals" }, { key: "b", text: "Heterolysis producing ions" }, { key: "c", text: "Resonance producing isomers" }, { key: "d", text: "Induction producing nuclei" }], answer: "a", explanation: "Equal division of the bonding pair leaves one electron on each fragment. This is homolytic cleavage, and the resulting fragments are radicals.", sectionId: "cleavage-reagents", source: { document: "quick-revision", page: 73 }, cognitive: "recall" },
    { id: "note-organic-basics-006", text: "A neutral molecule donates a lone pair to an electron-deficient carbon. What role does that molecule play?", options: [{ key: "a", text: "Electrophile accepting a pair" }, { key: "b", text: "Nucleophile donating a pair" }, { key: "c", text: "Radical supplying one electron" }, { key: "d", text: "Carbocation losing a proton" }], answer: "b", explanation: "Nucleophilicity is electron-pair donation, not a requirement for negative formal charge. Neutral lone-pair donors can therefore act as nucleophiles.", sectionId: "cleavage-reagents", source: { document: "quick-revision", page: 73 }, cognitive: "application" },
    { id: "note-organic-basics-007", text: "Which geometry is expected at the positively charged carbon of a simple classical alkyl carbocation?", options: [{ key: "a", text: "sp, linear geometry" }, { key: "b", text: "sp3, pyramidal geometry" }, { key: "c", text: "sp2, planar geometry" }, { key: "d", text: "sp3, tetrahedral geometry" }], answer: "c", explanation: "A simple tricoordinate carbocation is approximately sp2 and trigonal planar, with an empty p orbital available to accept electron density.", sectionId: "reaction-intermediates", source: { document: "quick-revision", page: 73 }, cognitive: "recall" },
    { id: "note-organic-basics-008", text: "For otherwise comparable localized alkyl carbanions, which substitution order is the elementary stability prediction?", options: [{ key: "a", text: "Tertiary > secondary > primary" }, { key: "b", text: "Secondary > primary > tertiary" }, { key: "c", text: "Primary > tertiary > secondary" }, { key: "d", text: "Primary > secondary > tertiary" }], answer: "d", explanation: "For this restricted comparison, alkyl electron donation destabilizes the negative centre. The simple carbanion trend therefore reverses the carbocation trend.", sectionId: "reaction-intermediates", source: { document: "quick-revision", page: 73 }, cognitive: "understanding" },
    { id: "note-organic-basics-009", text: "Which alkyl substituent is placed first in the source's decreasing +I sequence?", options: [{ key: "a", text: "tert-Butyl, (CH3)3C-" }, { key: "b", text: "Isopropyl, (CH3)2CH-" }, { key: "c", text: "Ethyl, CH3CH2-" }, { key: "d", text: "Methyl, CH3-" }], answer: "a", explanation: "The printed elementary +I order is tert-butyl, isopropyl, ethyl, then methyl. It must not be confused with the adjacent C-H hyperconjugation count.", sectionId: "electronic-effects", source: { document: "quick-revision", page: 73 }, cognitive: "recall" },
    { id: "note-organic-basics-010", text: "An attacking reagent causes complete displacement of a multiple-bond electron pair toward one bonded atom. Which traditional effect describes this?", options: [{ key: "a", text: "Permanent inductive effect" }, { key: "b", text: "Temporary electromeric effect" }, { key: "c", text: "Static crystallization effect" }, { key: "d", text: "Ordinary catenation effect" }], answer: "b", explanation: "The electromeric effect is the traditional description of reagent-induced complete displacement of a pi pair. Induction describes sigma-bond polarization instead.", sectionId: "electronic-effects", source: { document: "quick-revision", page: 73 }, cognitive: "understanding" },
    { id: "note-organic-basics-011", text: "What remains unchanged between valid resonance contributors of one molecule?", options: [{ key: "a", text: "The location of every pi electron" }, { key: "b", text: "The formal charge on every atom" }, { key: "c", text: "The connectivity of the nuclei" }, { key: "d", text: "The position of every lone pair" }], answer: "c", explanation: "Resonance redistributes electron representation within a fixed nuclear framework. Moving atoms or changing the skeletal connectivity would describe a different species.", sectionId: "electronic-effects", source: { document: "quick-revision", page: 73 }, cognitive: "understanding" },
    { id: "note-organic-basics-012", text: "For CH3- directly attached to an unsaturated centre, how many C-H no-bond hyperconjugative contributors are counted in the elementary model?", options: [{ key: "a", text: "Zero eligible contributors" }, { key: "b", text: "One eligible contributor" }, { key: "c", text: "Two eligible contributors" }, { key: "d", text: "Three eligible contributors" }], answer: "d", explanation: "The directly attached methyl carbon has three eligible C-H bonds. The elementary count is three, correcting the source's erroneous subtraction of one.", sectionId: "hyperconjugation", source: { document: "quick-revision", page: 74 }, cognitive: "application" },
    { id: "note-organic-basics-013", text: "Which analytical pairing specifically determines nitrogen through molecular nitrogen gas?", options: [{ key: "a", text: "Dumas method: N2" }, { key: "b", text: "Kjeldahl method: NH3" }, { key: "c", text: "Liebig method: CO2" }, { key: "d", text: "Carius method: AgCl" }], answer: "a", explanation: "Dumas nitrogen analysis measures nitrogen as N2. Kjeldahl uses ammonia after digestion, whereas the other listed products belong to different elemental analyses.", sectionId: "quantitative-element-analysis", source: { document: "quick-revision", page: 74 }, cognitive: "recall" },
    { id: "note-organic-basics-014", text: "The source assigns the same named quantitative method to sulfur and the usual chloride, bromide or iodide determinations. Which method is it?", options: [{ key: "a", text: "Liebig combustion method" }, { key: "b", text: "Carius analytical method" }, { key: "c", text: "Kjeldahl digestion method" }, { key: "d", text: "Dumas gas-volume method" }], answer: "b", explanation: "The table lists Carius for both sulfur and halogens. The usual silver-halide form concerns chlorine, bromine and iodine, not soluble silver fluoride.", sectionId: "quantitative-element-analysis", source: { document: "quick-revision", page: 74 }, cognitive: "recall" },
    { id: "note-organic-basics-015", text: "A heated iodine-sodium chloride mixture deposits iodine on a cool surface while salt remains behind. Which property enables separation?", options: [{ key: "a", text: "Equal liquid boiling points" }, { key: "b", text: "Equal aqueous solubilities" }, { key: "c", text: "Selective solid-to-vapour transfer" }, { key: "d", text: "Selective nitrogen evolution" }], answer: "c", explanation: "Iodine can sublime and redeposit while sodium chloride remains nonvolatile under the chosen conditions. No collected liquid iodine phase is required.", sectionId: "crystallization-sublimation", source: { document: "quick-revision", page: 74 }, cognitive: "application" },
    { id: "note-organic-basics-016", text: "A liquid decomposes near its atmospheric boiling point. Which change most directly permits distillation at a lower temperature?", options: [{ key: "a", text: "Raise the external pressure" }, { key: "b", text: "Increase the impurity content" }, { key: "c", text: "Increase the heating rate" }, { key: "d", text: "Reduce the external pressure" }], answer: "d", explanation: "Boiling occurs when vapour pressure reaches the external pressure. Lowering external pressure lowers the required temperature, the basis of vacuum distillation.", sectionId: "distillation-methods", source: { document: "quick-revision", page: 74 }, cognitive: "application" },
    { id: "note-organic-basics-017", text: "Which source example belongs to steam distillation?", options: [{ key: "a", text: "Purification of sandalwood oil" }, { key: "b", text: "Determination of organic nitrogen" }, { key: "c", text: "Separation of iodine from salt" }, { key: "d", text: "Ignition analysis of phosphorus" }], answer: "a", explanation: "Sandalwood oil is listed among the steam-distillation applications. The other operations use gas analysis, sublimation or elemental analysis rather than steam volatility.", sectionId: "distillation-methods", source: { document: "quick-revision", page: 74 }, cognitive: "recall" },
    { id: "note-organic-basics-018", text: "At fixed pressure, a mixture's boiling vapour has the same composition as its liquid. What is the relevant limitation?", options: [{ key: "a", text: "No component can enter the vapour" }, { key: "b", text: "Ordinary distillation cannot enrich it" }, { key: "c", text: "The mixture must contain only solids" }, { key: "d", text: "Both components must have equal masses" }], answer: "b", explanation: "At the azeotropic composition, evaporation does not enrich one component relative to the liquid. A different separation strategy is needed to pass that composition.", sectionId: "distillation-methods", source: { document: "quick-revision", page: 74 }, cognitive: "understanding" },
    { id: "note-organic-basics-019", text: "Which principle underlies chromatographic separation of amino acids?", options: [{ key: "a", text: "Identical affinity for both phases" }, { key: "b", text: "Complete conversion into vapours" }, { key: "c", text: "Different interactions with two phases" }, { key: "d", text: "Conversion into the same precipitate" }], answer: "c", explanation: "Different affinities for the stationary and mobile phases produce different migration rates. Chromatography does not require equal affinity or vaporization of every solute.", sectionId: "atmolysis-chromatography", source: { document: "quick-revision", page: 74 }, cognitive: "understanding" },
    { id: "note-organic-basics-020", text: "Which statement correctly applies the two alkane facts printed at the end of page 74?", options: [{ key: "a", text: "Acyclic C4H8 has only sp3 carbon" }, { key: "b", text: "Cyclic C4H10 has only sp2 carbon" }, { key: "c", text: "Acyclic C4H6 has only sp carbon" }, { key: "d", text: "Acyclic C4H10 has only sp3 carbon" }], answer: "d", explanation: "For an acyclic saturated hydrocarbon with four carbons, H = 2(4) + 2 = 10. Its carbons are sp3; the alkane formula does not apply to a ring.", sectionId: "alkane-transition", source: { document: "quick-revision", page: 74 }, cognitive: "application" }
  ]
};