window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["oscillations"] = {
  id: "oscillations",
  subject: "Physics",
  title: "Oscillations and simple harmonic motion",
  sections: [
    {
      id: "restoring-force-inertia",
      title: "Restoring force, inertia and the SHM equation",
      sources: [{ document: "quick-revision", page: 14 }, { document: "quick-revision", page: 15 }],
      html: "<p>Displacement $y$ is measured from the mean or stable equilibrium position, with a chosen positive direction. In simple harmonic motion, the net restoring force is proportional to displacement and opposite to it: $F=-k_sy=-m\\omega^2y$. Here $k_s$ is a positive force constant. Thus $a=-\\omega^2y$ and $\\frac{d^2y}{dt^2}+\\omega^2y=0$.</p><p>The source says SHM needs both elasticity and inertia. Elasticity here means a restoring tendency; it need not be literal deformation of an elastic material, since gravity can supply the restoring effect for a pendulum. Inertia carries the body through equilibrium, and the restoring force then turns it back. A restoring effect without the necessary inertia does not produce this mechanical oscillation.</p><p><strong>Source clarification:</strong> the printed equation $\\frac{d^2y}{dt^2}+ky=0$ is dimensionally correct only if its $k$ denotes $\\omega^2$, with units of inverse time squared. If $k$ means the spring force constant, the coefficient must be $\\frac{k}{m}$. This note uses $k_s$ for stiffness to avoid silently mixing those meanings.</p><p>The ideal linear oscillator's period is independent of amplitude. Increasing amplitude does not change its period as long as the force remains linear and the system parameters remain fixed. This consolidates the repeated amplitude-independence statements on pages 14 and 15. Finite-angle pendulum motion and nonlinear springs need not have an amplitude-independent period.</p>"
    },
    {
      id: "displacement-velocity-acceleration",
      title: "Displacement, velocity, acceleration and phase",
      sources: [{ document: "quick-revision", page: 15 }, { document: "quick-revision", page: 14 }],
      html: "<p>Writing the amplitude as $A$ (the source uses $r$), a solution is $y=A\\sin(\\omega t+\\phi)$. The page's $y=r\\sin\\omega t$ is the special case starting at equilibrium with positive velocity and phase $\\phi=0$. Frequency and period are $f=\\frac{\\omega}{2\\pi}$ and $T=\\frac{2\\pi}{\\omega}$.</p><p>Differentiation gives $v=A\\omega\\cos(\\omega t+\\phi)$ and $a=-A\\omega^2\\sin(\\omega t+\\phi)=-\\omega^2y$. Therefore maximum speed is $A\\omega$ and maximum acceleration magnitude is $A\\omega^2$. At equilibrium speed is greatest and restoring force and acceleration are zero. At either extreme the velocity is zero and the restoring acceleration magnitude is greatest.</p><p>Eliminating phase gives $v^2=\\omega^2(A^2-y^2)$. The speed is $|v|=\\omega\\sqrt{A^2-y^2}$, whereas signed velocity is $v=\\pm\\omega\\sqrt{A^2-y^2}$ depending on the direction of travel. <strong>Source clarification:</strong> its positive square-root expression is a speed, not a unique signed velocity at each position.</p><p>Displacement, acceleration, velocity, force, potential energy and kinetic energy all vary through the cycle, as page 14 states. Velocity has two possible signs at an interior displacement; position alone does not tell whether the body is moving outward or returning. Force and acceleration are opposite in phase to displacement, while velocity differs in phase by a quarter-cycle.</p>"
    },
    {
      id: "shm-graph-shapes",
      title: "The complete SHM graph list",
      sources: [{ document: "quick-revision", page: 9 }, { document: "quick-revision", page: 15 }],
      html: "<ul><li>Displacement-time, velocity-time, acceleration-time, restoring-force-time and momentum-time graphs are sinusoidal, with appropriate phase shifts. A cosine curve is also a sinusoid; not all five graphs peak together.</li><li>The displacement-velocity phase curve is an ellipse: $\\frac{y^2}{A^2}+\\frac{v^2}{A^2\\omega^2}=1$. Both velocity signs belong to the complete curve.</li><li>Acceleration-displacement and force-displacement graphs are straight lines through the origin with negative slopes: $a=-\\omega^2y$ and $F=-m\\omega^2y$.</li><li>Potential energy against displacement is an upward-opening parabola, while kinetic energy against displacement is a downward-opening parabola over $-A\\leq y\\leq A$.</li><li>Total mechanical energy against displacement is a horizontal straight line for an undamped, undriven oscillator.</li></ul><p><strong>Source correction:</strong> the first sine-curve list on page 9 starts with 'y-v', but the next line correctly labels y-v as an ellipse. The sinusoidal displacement graph is y-t, not y-v. Momentum $p=mv$ has the same time dependence as velocity for fixed mass. The energy curves are explained by the separate squared-displacement formulas, rather than being additional sinusoidal displacement plots.</p>"
    },
    {
      id: "shm-energy-frequencies",
      title: "Energy ratios and twice-frequency variation",
      sources: [{ document: "quick-revision", page: 9 }, { document: "quick-revision", page: 15 }],
      html: "<p>Choose zero potential energy at the mean position. The elastic or effective oscillation potential is $U=\\frac12m\\omega^2y^2$, kinetic energy is $K=\\frac12m\\omega^2(A^2-y^2)$, and total mechanical energy is $E=\\frac12m\\omega^2A^2$. The source ratio is therefore $K:U:E=(A^2-y^2):y^2:A^2$.</p><p>At the mean position the energy is entirely kinetic; at the extremes it is entirely potential. Equal kinetic and potential energies occur at $|y|=\\frac{A}{\\sqrt2}$. Doubling amplitude with $m$ and $\\omega$ fixed multiplies energy by four, while leaving the period unchanged.</p><p>For $y=A\\sin(\\omega t+\\phi)$, $U=E\\sin^2(\\omega t+\\phi)$ and $K=E\\cos^2(\\omega t+\\phi)$. The squared sine and cosine repeat after half an oscillation, so each energy varies with frequency $2f$ when displacement has frequency $f$.</p><p><strong>Source clarification:</strong> page 9's 'K.E., P.E. = 2f; T.E. = 0' refers to frequencies of variation. It does not say kinetic energy numerically equals $2f$, or total energy equals zero. Total energy is a nonzero constant for nonzero amplitude and has no oscillatory variation. These results presume no damping or external work input.</p>"
    },
    {
      id: "spring-period-and-equilibrium",
      title: "Spring period and constant external forces",
      sources: [{ document: "quick-revision", page: 14 }, { document: "quick-revision", page: 15 }],
      html: "<p>For an ideal mass $m$ on a light linear spring of stiffness $k_s$, displacement from equilibrium obeys $m\\ddot y=-k_sy$. Hence $\\omega=\\sqrt{\\frac{k_s}{m}}$ and $T=2\\pi\\sqrt{\\frac{m}{k_s}}$. The period depends on inertia and stiffness, not on gravitational acceleration.</p><p>The source lists three situations in which the spring period stays the same: taking it to the Moon, dipping it in a nonviscous liquid, and placing it in an accelerating vehicle. The following conditions make those statements precise:</p><ul><li>On the Moon, changing $g$ changes the equilibrium extension of a vertical spring but not $T$, if $m$ and $k_s$ remain unchanged.</li><li>For a fully submerged bob of fixed volume, uniform buoyancy is a constant force and shifts equilibrium. The same period follows only if added fluid inertia, wave effects and viscous drag are neglected. Nonviscous liquid alone does not guarantee zero added mass.</li><li>Constant translational acceleration of the support adds a constant inertial force in that frame. It shifts equilibrium but leaves the small-displacement stiffness unchanged. Time-varying acceleration can drive the oscillator and is not covered by this simple statement.</li></ul><p>A constant external force $F_0$ gives equilibrium shift $y_0=\\frac{F_0}{k_s}$ in the force direction. Writing the motion relative to the new equilibrium removes that constant term and leaves the same natural period. This consolidates the source's repeated 'Spring: gravity independent; nonviscous liquid and accelerating vehicles' mnemonic.</p>"
    },
    {
      id: "charged-sheets-unresolved",
      title: "The charged-sheet box lacks its setup",
      sources: [{ document: "quick-revision", page: 14 }],
      html: "<p>The source box is headed 'Two sheets with charges'. It lists 'Similar: Speed up, time period increases' and 'Opposite: Slow, up, time period decreases'. No diagram identifies the moving body, its charge, the sheets' placement, field direction, or whether 'speed' means the particle's speed or a clock's running rate.</p><p>Charge signs alone cannot decide an oscillation period. A spatially constant electric force shifts the equilibrium of an ideal linear spring without changing its natural period. For a charged pendulum, a vertical electric force can instead change the effective gravity and hence its period; upward force reduces the downward effective gravity and increases the small-angle period, while downward force increases it and decreases that period, provided a stable hanging equilibrium remains.</p><p>The two source lines are preserved as unresolved claims. They cannot justify a scored question or a general rule about similar and opposite charges without the missing physical arrangement. In particular, an increased period means fewer cycles per unit time, so the source's 'speed up' wording must not automatically be read as a faster clock.</p>"
    },
    {
      id: "damped-period",
      title: "Damping and the oscillation period",
      sources: [{ document: "quick-revision", page: 14 }],
      html: "<p>The source states that damping increases the period. For linear viscous damping, the equation is $m\\ddot y+b\\dot y+k_sy=0$. Let $\\omega_0=\\sqrt{\\frac{k_s}{m}}$ and $\\gamma=\\frac{b}{2m}$. In the underdamped case, $0&lt;\\gamma&lt;\\omega_0$, the oscillation frequency is $\\omega_d=\\sqrt{\\omega_0^2-\\gamma^2}$.</p><p>Thus $T_d=\\frac{2\\pi}{\\omega_d}$ is greater than the undamped period $T_0=\\frac{2\\pi}{\\omega_0}$. The amplitude decays as $e^{-\\gamma t}$, so this is a period between successive phases of a decaying motion, not an exact repetition of the entire state. At critical or greater damping, the system no longer oscillates and there is no ordinary oscillation period to compare. Different damping laws require their own analysis.</p>"
    },
    {
      id: "long-pendulum-source",
      title: "The Earth-radius pendulum estimate",
      sources: [{ document: "quick-revision", page: 14 }],
      html: "<p>The source says that a pendulum with length comparable to Earth's radius has a period of one hour. Its pivot and bob positions are not given. At this scale the assumption of a parallel, spatially uniform gravitational field is no longer adequate.</p><p>A particular ideal model does reproduce about one hour: a bob lies near Earth's surface at equilibrium, and its pivot is directly above it at height $l$. Let Earth's radius be $R$ and the surface acceleration be $g$. The radial direction of gravity changes as the bob swings. To first order in angle, the equation is $\\ddot\\theta+\\frac{g(R+l)}{Rl}\\theta=0$, giving $T=2\\pi\\sqrt{\\frac{Rl}{g(R+l)}}$.</p><p>For $l=R$, this becomes $T=2\\pi\\sqrt{\\frac{R}{2g}}$, about $59.8$ minutes for $R=6.4\\times10^6\\,\\mathrm m$ and $g=9.8\\,\\mathrm{m\\,s^{-2}}$. Applying the ordinary uniform-field formula at $l=R$ would instead give about $84.6$ minutes. Neither is a universal answer for every length merely 'comparable' to $R$: the source needs an explicit geometry and gravitational model. The conditional one-hour reconstruction is not used as a scored question.</p>"
    },
    {
      id: "series-springs",
      title: "Springs connected in series",
      sources: [{ document: "quick-revision", page: 14 }],
      html: "<p>The source drawing shows two springs connected end to end beneath a fixed support, with a mass hanging from the lower spring. For light springs and a light connector, the same tension passes through both. Their extensions are $x_1=\\frac{F}{k_1}$ and $x_2=\\frac{F}{k_2}$, so they generally differ when the stiffnesses differ.</p><p>The total extension is $x=x_1+x_2$. Defining the equivalent stiffness by the force-magnitude relation $F=k_{\\mathrm{eff}}x$ gives $\\frac{1}{k_{\\mathrm{eff}}}=\\frac{1}{k_1}+\\frac{1}{k_2}$, or $k_{\\mathrm{eff}}=\\frac{k_1k_2}{k_1+k_2}$. The series combination is softer than either positive individual stiffness.</p><p>The source's 'force same, extension different' is a useful contrast with parallel springs, not a prohibition on equal extensions when $k_1=k_2$. The sign of an actual restoring force relative to displacement is negative; $F=kx$ here describes the tensile-force magnitude. A suspended oscillator uses the equivalent stiffness in $T=2\\pi\\sqrt{\\frac{m}{k_{\\mathrm{eff}}}}$.</p>"
    },
    {
      id: "parallel-and-cut-springs",
      title: "Parallel springs and equal pieces of a spring",
      sources: [{ document: "quick-revision", page: 15 }],
      html: "<p>The parallel-spring drawing has three springs labelled $k_1$, $k_2$ and $k_3$ between a fixed upper support and a common lower bar carrying the load $F$. A translating rigid bar without tilt gives each spring the same extension $x$. Their forces are $F_1=k_1x$, $F_2=k_2x$ and $F_3=k_3x$, and their sum supports the load.</p><p>Therefore $k_{\\mathrm{eff}}=k_1+k_2+k_3$. The source's 'same extension, different force' means the forces can differ in proportion to unequal stiffnesses; identical springs carry equal forces. The supports and common attachment are part of the parallel condition.</p><p>If a uniform spring of stiffness $K$ is cut into $n$ equal parts with otherwise unchanged coil geometry, each shorter piece has stiffness $nK$, because stiffness is inversely proportional to active length. Putting all $n$ pieces in parallel gives $K_{\\mathrm{eff}}=n(nK)=n^2K$, as stated in the source. The pieces must be equal for this particular shortcut. Rejoining the same pieces in series restores $K$ in the ideal model.</p>"
    },
    {
      id: "pendulum-clock-and-graphs",
      title: "Pendulum gravity changes and period-length graphs",
      sources: [{ document: "quick-revision", page: 15 }],
      html: "<p>For a simple pendulum of length $l$ in a uniform gravitational field, at small angular amplitude, $T=2\\pi\\sqrt{\\frac{l}{g}}$. The effective length is measured from the pivot to the bob's centre of mass. This period differs from that of a spring because gravity supplies the pendulum's restoring effect.</p><p>For a clock calibrated at a fixed length, lower $g$ increases the period and the clock loses time. Greater $g$ reduces the period and the clock gains time. Moving above Earth's surface reduces $g$ and therefore makes the ideal unchanged pendulum run slow, as in the source. These statements assume temperature and other influences have not changed the effective length.</p><p>The T-l relation is $T\\propto\\sqrt l$. With $l$ horizontal and $T$ vertical, it is the positive square-root branch of the sideways parabola $l=\\frac{g}{4\\pi^2}T^2$, which explains the source's 'parabolic' label. A plot of $T^2$ against $l$ is a straight line through the origin with slope $\\frac{4\\pi^2}{g}$. A period-length graph is not itself the sinusoidal time history of a bob's displacement.</p>"
    },
    {
      id: "u-tube-liquid",
      title: "Liquid oscillation in a uniform U-tube",
      sources: [{ document: "quick-revision", page: 15 }],
      html: "<p>Let an incompressible liquid of density $\\rho$ occupy total length $l$ in a uniform-area U-tube, with two vertical open arms. If one free surface is displaced upward by $y$, the other moves downward by $y$, producing a level difference $2y$. With tube area $A_c$, the restoring force along the liquid column is $F=-2\\rho A_cgy$.</p><p>The moving mass is $m=\\rho A_cl$, so the equation becomes $\\ddot y+\\frac{2g}{l}y=0$. The period is $T=2\\pi\\sqrt{\\frac{l}{2g}}$, matching the source. Here $l$ is the total moving liquid-column length, including the connecting bend, not the length in only one arm.</p><p>The density and common cross-sectional area cancel between inertia and restoring force. Thus the ideal period is independent of both, for fixed $l$ and $g$. This assumes negligible viscosity, sufficiently small motions with both surfaces staying in uniform vertical arms, and no unequal gas pressures or other restoring effects. Unequal arm areas or substantial damping require a modified model.</p>"
    },
    {
      id: "rolling-formula-continuation",
      title: "Rolling formulas at the top of page 14",
      sources: [{ document: "quick-revision", page: 14 }],
      html: "<p>The top of the assigned page continues rolling motion before the SHM heading. Let a rigid body have mass $m$, rolling radius $R$ and centre-of-mass moment of inertia $I=mk_g^2$, with $k_g$ the radius of gyration (printed as K). For rolling without slipping, $v=\\omega R$.</p><p>The total translational-plus-rotational kinetic energy is $E_{\\mathrm{kin}}=\\frac12mv^2(1+\\frac{k_g^2}{R^2})$. The rotational part alone is $E_R=\\frac12mv^2\\frac{k_g^2}{R^2}=\\frac{L^2}{2I}$, where $L=I\\omega$ is angular momentum about the same centre-of-mass axis. The source's $E_T$ here means the combined kinetic energy, not potential energy added to it.</p><p>For descent from rest through a fixed distance down a fixed incline, $a=\\frac{g\\sin\\theta}{1+\\frac{k_g^2}{R^2}}$, so $t\\propto\\sqrt{1+\\frac{k_g^2}{R^2}}$. Adequate static friction is required. Resolving translation and rotation gives $\\frac{f_s}{N}=\\frac{k_g^2}{k_g^2+R^2}\\tan\\theta$, so no slipping requires $\\mu_s\\geq\\frac{k_g^2}{k_g^2+R^2}\\tan\\theta$. These are all four continuation formulas, with the time square root retained and with the symbols distinguished from spring stiffness and SHM amplitude.</p>"
    },
    {
      id: "gravitational-force-boundary",
      title: "Gravitational force on the shared source page",
      sources: [{ document: "quick-revision", page: 9 }],
      html: "<p>The assigned page changes from SHM graphs to gravitational force. In Newtonian gravity, the pairwise force between two point masses at fixed positions is $F=\\frac{Gm_1m_2}{r^2}$. It does not acquire a material-medium factor like electrostatic permittivity, and another body's presence does not alter that fixed pairwise term.</p><p>The source's independence-from-other-bodies statement must be read with superposition: other masses contribute their own gravitational forces, changing the resultant force. Their presence can also change the subsequent positions of the bodies. Thus the net gravitational field is not independent of other bodies even though the specified pair interaction has the same law.</p>"
    },
    {
      id: "orbital-escape-comparison",
      title: "Every entry of the orbital and escape comparison",
      sources: [{ document: "quick-revision", page: 9 }],
      html: "<p>For a circular orbit at distance $r=R+h$ from the centre of a spherical planet of mass $M$, $v_o=\\sqrt{\\frac{GM}{r}}$, $\\omega_o=\\sqrt{\\frac{GM}{r^3}}$ and $T_o=2\\pi\\sqrt{\\frac{r^3}{GM}}$. At fixed planet, these depend on orbital height but not on satellite mass. <strong>Source clarification:</strong> 'depends only on height' keeps $M$ and $R$ fixed; it is not a comparison between arbitrary planets.</p><ul><li>The source gives near-Earth circular speed as $8$ or more precisely $7.92\\,\\mathrm{km\\,s^{-1}}$.</li><li>It gives the hypothetical surface-orbit period as $84.6$ minutes. With $r\\approx R$, this is $2\\pi\\sqrt{\\frac{R}{g}}$; atmosphere and terrain prevent such a literal surface-skimming orbit.</li><li>The listed angular speed $\\frac{1}{800}$ is an approximate near-Earth value if its unstated unit is radians per second. It is not the angular speed of every orbit; the source omits the unit and explicit radius beside this entry.</li></ul><p>At the same radius, the minimum ideal escape speed is $v_e=\\sqrt{\\frac{2GM}{r}}=\\sqrt2v_o$. With potential energy zero at infinity, the threshold condition is $\\frac12mv_e^2=\\frac{GMm}{r}=|U_i|$. <strong>Source correction:</strong> the escape column's 'Equal to gravitational potential energy' must refer to the required launch kinetic energy equalling the magnitude of the binding potential energy, not a velocity equalling an energy.</p><p>The source's near-Earth escape value is $11.2\\,\\mathrm{km\\,s^{-1}}$. Its list of dependencies, planet mass, density, radius and launch height, is understood through $M$ and $r=R+h$. For a uniform-density sphere, $M=\\frac43\\pi R^3\\rho$, so density and radius can replace mass in the expression; these are not all independent parameters. Escape speed does not depend on the test body's mass. The values assume no atmospheric losses, no rotational launch assistance and no additional propulsion after the initial launch.</p>"
    },
    {
      id: "geostationary-values",
      title: "Geostationary orbit values on page 9",
      sources: [{ document: "quick-revision", page: 9 }],
      html: "<p>The source lists a geostationary satellite's height as approximately $36{,}000\\,\\mathrm{km}$ above Earth, orbital speed as approximately $3.1\\,\\mathrm{km\\,s^{-1}}$ and period as $24$ hours. These are rounded revision values: the usual altitude is about $35{,}786\\,\\mathrm{km}$ and the period is one sidereal day, about 23 hours 56 minutes, matching Earth's rotation relative to distant stars.</p><p>A geostationary satellite must also have a circular equatorial orbit in Earth's rotation direction. Matching the period without matching the orbital plane and direction is not enough to remain over one ground location. Its speed in an Earth-centred inertial frame is nonzero even though it appears fixed from the ground.</p><p><strong>Source terminology:</strong> the page calls these 'parking orbits'. A parking orbit can technically mean a temporary orbit before a transfer; it is not a defining synonym for geostationary orbit. The three numerical geostationary entries are retained with their approximation conditions.</p>"
    },
    {
      id: "kepler-area-law",
      title: "Equal areas, angular momentum and orbital duration",
      sources: [{ document: "quick-revision", page: 9 }],
      html: "<p>Kepler's second law states that the radius vector from the Sun to a planet sweeps out equal areas in equal time intervals. A central gravitational force has zero torque about the Sun, conserving orbital angular momentum. If the planet's mass is $M_p$ and angular momentum magnitude is $L$, the areal velocity is $\\frac{dA}{dt}=\\frac{L}{2M_p}$, as printed.</p><p>On an elliptical orbit, the planet's speed is greatest at its closest approach to the Sun and least at its greatest separation. Equal-area motion does not mean equal distances are covered in equal times, and angular speed is not constant on an ellipse.</p><p>The source adds that the duration of a year increases with distance. For different orbits about the same dominant central mass, the precise distance measure is semi-major axis $a$, and Kepler's third law gives $T^2\\propto a^3$. This period comparison is distinct from the second law. A planet's period does not change from instant to instant merely because its distance varies around one fixed elliptical orbit.</p>"
    },
    {
      id: "elasticity-page-boundary",
      title: "Elasticity notes at the end of page 15",
      sources: [{ document: "quick-revision", page: 15 }],
      html: "<p>The page ends with four elasticity points. A bent rod has longitudinal strain: fibres on the outside of a bend lengthen, those on the inside shorten, and a neutral layer has no longitudinal extension in the elementary bending model. Opposite strain signs across the cross-section are why bending cannot be represented by one uniform axial strain.</p><p>A close-coiled helical spring under axial load mainly stores energy through twisting of its wire, producing shear strain in that wire. The spring's overall change in length does not imply that the wire is undergoing only longitudinal strain.</p><p>The source says hammering and rolling increase elasticity and attaches the mnemonic 'HIRO'. <strong>Source clarification:</strong> cold working can raise a metal's elastic limit or yield strength through strain hardening. It does not generally guarantee an increased Young's modulus. The page does not specify material, temperature, processing history or which elastic property is meant, so the broad increase claim remains under-specified.</p><p>The source's steel-versus-copper comparison uses the exam convention 'more elastic' to mean the material with the larger Young's modulus: ordinary steel is stiffer than copper and undergoes less longitudinal elastic strain for the same stress within the elastic range. This is not the same as saying that steel can stretch farther before fracture or recover from every larger deformation.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 9, status: "partial", sectionIds: ["shm-graph-shapes", "shm-energy-frequencies", "gravitational-force-boundary", "orbital-escape-comparison", "geostationary-values", "kepler-area-law"], unresolved: ["The orbital angular-velocity entry is printed as 1/800 without units or an explicit orbital radius; the notes identify the consistent approximate near-Earth radian-per-second interpretation, not a universal orbital value."] },
    { document: "quick-revision", page: 14, status: "partial", sectionIds: ["restoring-force-inertia", "displacement-velocity-acceleration", "spring-period-and-equilibrium", "charged-sheets-unresolved", "damped-period", "long-pendulum-source", "series-springs", "rolling-formula-continuation"], unresolved: ["Two sheets with charges: Similar speed up/time period increases; Opposite slow up/time period decreases lacks the moving body, charges, sheet geometry, electric-field direction and meaning of speed. No definite period rule is inferred.", "The one-hour pendulum with length comparable to Earth's radius has no pivot/bob geometry or gravitational-field model. A surface-bob radial-field model with length exactly R gives about 59.8 minutes, but the original setup remains unspecified."] },
    { document: "quick-revision", page: 15, status: "partial", sectionIds: ["restoring-force-inertia", "displacement-velocity-acceleration", "shm-graph-shapes", "shm-energy-frequencies", "spring-period-and-equilibrium", "parallel-and-cut-springs", "pendulum-clock-and-graphs", "u-tube-liquid", "elasticity-page-boundary"], unresolved: ["The coefficient k in d2y/dt2 + k*y = 0 is not defined or assigned units; it must mean omega squared, or be replaced by stiffness/mass if it means the spring constant.", "Hammering and rolling increase elasticity, mnemonic HIRO, does not identify material, temperature, processing history or whether elasticity means modulus or elastic limit; these cannot be treated as interchangeable properties."] }
  ],
  questions: [
    { id: "note-oscillations-001", text: "For a positive constant $c$, which net force law produces exact one-dimensional SHM about $y=0$ over its stated range?", options: [{ key: "a", text: "$F=c$" }, { key: "b", text: "$F=cy$" }, { key: "c", text: "$F=-cy^3$" }, { key: "d", text: "$F=-cy$" }], answer: "d", explanation: "Exact SHM requires a restoring force that is linear in displacement and directed toward equilibrium. The law $F=-cy$ satisfies both conditions for positive $c$. A cubic restoring force is nonlinear, while $F=cy$ drives a displacement farther away.", sectionId: "restoring-force-inertia", source: { document: "quick-revision", page: 15 }, cognitive: "recall" },
    { id: "note-oscillations-002", text: "An oscillator has displacement $y=0.040\\sin(5t)$ metres, with $t$ in seconds. What is its maximum acceleration magnitude?", options: [{ key: "a", text: "$0.20\\,\\mathrm{m\\,s^{-2}}$" }, { key: "b", text: "$1.00\\,\\mathrm{m\\,s^{-2}}$" }, { key: "c", text: "$0.040\\,\\mathrm{m\\,s^{-2}}$" }, { key: "d", text: "$5.00\\,\\mathrm{m\\,s^{-2}}$" }], answer: "b", explanation: "The amplitude is $A=0.040\\,\\mathrm m$ and the angular frequency is $5\\,\\mathrm{rad\\,s^{-1}}$. Maximum acceleration is $A\\omega^2=0.040\\times25=1.00\\,\\mathrm{m\\,s^{-2}}$. The product $A\\omega=0.20$ is maximum speed instead.", sectionId: "displacement-velocity-acceleration", source: { document: "quick-revision", page: 15 }, cognitive: "application" },
    { id: "note-oscillations-003", text: "A particle oscillates with amplitude $5.0\\,\\mathrm{cm}$ and angular frequency $10\\,\\mathrm{rad\\,s^{-1}}$. What is its speed at a displacement of $3.0\\,\\mathrm{cm}$ from equilibrium?", options: [{ key: "a", text: "$0.40\\,\\mathrm{m\\,s^{-1}}$" }, { key: "b", text: "$0.20\\,\\mathrm{m\\,s^{-1}}$" }, { key: "c", text: "$0.30\\,\\mathrm{m\\,s^{-1}}$" }, { key: "d", text: "$0.50\\,\\mathrm{m\\,s^{-1}}$" }], answer: "a", explanation: "Using metres, the speed is $\\omega\\sqrt{A^2-y^2}=10\\sqrt{0.050^2-0.030^2}=0.40\\,\\mathrm{m\\,s^{-1}}$. Its sign would require the direction of motion, but the question asks only for speed.", sectionId: "displacement-velocity-acceleration", source: { document: "quick-revision", page: 15 }, cognitive: "application" },
    { id: "note-oscillations-004", text: "A recorder plots signed velocity against displacement for a complete nonzero-amplitude cycle of ideal SHM. Which curve results?", options: [{ key: "a", text: "A single sloping straight line" }, { key: "b", text: "A sinusoid with time on one axis" }, { key: "c", text: "A closed elliptical phase curve" }, { key: "d", text: "An open upward parabola" }], answer: "c", explanation: "Eliminating time gives $\\frac{y^2}{A^2}+\\frac{v^2}{A^2\\omega^2}=1$, which is an ellipse. The complete cycle includes positive and negative velocities. A sine curve would describe displacement against time, not this pair of axes.", sectionId: "shm-graph-shapes", source: { document: "quick-revision", page: 9 }, cognitive: "understanding" },
    { id: "note-oscillations-005", text: "With acceleration on the vertical axis and displacement on the horizontal axis, what is the slope of an ideal SHM graph?", options: [{ key: "a", text: "$+\\omega$" }, { key: "b", text: "$-\\omega^2$" }, { key: "c", text: "$+\\omega^2$" }, { key: "d", text: "$-\\omega$" }], answer: "b", explanation: "The defining relation is $a=-\\omega^2y$. Thus the graph is a straight line through the origin with slope $-\\omega^2$. The negative sign encodes restoring acceleration, and the squared frequency supplies the required inverse-time-squared units.", sectionId: "shm-graph-shapes", source: { document: "quick-revision", page: 9 }, cognitive: "understanding" },
    { id: "note-oscillations-006", text: "An ideal oscillator completes three displacement cycles each second. At what frequency does its kinetic energy repeat?", options: [{ key: "a", text: "$1.5\\,\\mathrm{Hz}$" }, { key: "b", text: "$3.0\\,\\mathrm{Hz}$" }, { key: "c", text: "$9.0\\,\\mathrm{Hz}$" }, { key: "d", text: "$6.0\\,\\mathrm{Hz}$" }], answer: "d", explanation: "Kinetic energy is proportional to the square of velocity, so it repeats twice during each displacement cycle. Its frequency is therefore $2f=2\\times3=6\\,\\mathrm{Hz}$. Total mechanical energy remains constant instead of oscillating at that frequency.", sectionId: "shm-energy-frequencies", source: { document: "quick-revision", page: 9 }, cognitive: "application" },
    { id: "note-oscillations-007", text: "At displacement $y=\\frac{A}{2}$ in ideal SHM, what is the ratio of kinetic energy to potential energy, with potential energy zero at equilibrium?", options: [{ key: "a", text: "$1:3$" }, { key: "b", text: "$1:1$" }, { key: "c", text: "$3:1$" }, { key: "d", text: "$4:1$" }], answer: "c", explanation: "Potential energy is the fraction $\\frac{y^2}{A^2}=\\frac14$ of total energy. Kinetic energy is the remaining $\\frac34$. Their ratio is therefore $3:1$, not the ratio of displacement to amplitude.", sectionId: "shm-energy-frequencies", source: { document: "quick-revision", page: 15 }, cognitive: "application" },
    { id: "note-oscillations-008", text: "A $0.40\\,\\mathrm{kg}$ oscillator has angular frequency $5.0\\,\\mathrm{rad\\,s^{-1}}$ and amplitude $0.20\\,\\mathrm m$. What is its total mechanical energy above the equilibrium minimum?", options: [{ key: "a", text: "$0.20\\,\\mathrm J$" }, { key: "b", text: "$0.10\\,\\mathrm J$" }, { key: "c", text: "$0.40\\,\\mathrm J$" }, { key: "d", text: "$1.00\\,\\mathrm J$" }], answer: "a", explanation: "The maximum speed is $A\\omega=1.0\\,\\mathrm{m\\,s^{-1}}$. At equilibrium all the oscillation energy is kinetic, so $E=\\frac12mv_{\\max}^2=\\frac12\\times0.40\\times1^2=0.20\\,\\mathrm J$, agreeing with $\\frac12m\\omega^2A^2$.", sectionId: "shm-energy-frequencies", source: { document: "quick-revision", page: 15 }, cognitive: "application" },
    { id: "note-oscillations-009", text: "An ideal linear spring oscillator is given twice its original amplitude without changing its mass or spring. How do its period and total energy change?", options: [{ key: "a", text: "Period unchanged; energy becomes four times larger." }, { key: "b", text: "Period doubles; energy becomes four times larger." }, { key: "c", text: "Period unchanged; energy becomes twice as large." }, { key: "d", text: "Period halves; energy becomes twice as large." }], answer: "a", explanation: "The natural period depends only on mass and stiffness for a linear spring, so it stays fixed. Oscillation energy is proportional to amplitude squared, making the energy four times as large when amplitude doubles. This assumes the spring remains within its linear range.", sectionId: "shm-energy-frequencies", source: { document: "quick-revision", page: 15 }, cognitive: "understanding" },
    { id: "note-oscillations-010", text: "An ideal linear spring oscillator is placed in a vehicle with constant translational acceleration. Its mass and stiffness stay fixed. Which change follows from the constant inertial force alone?", options: [{ key: "a", text: "The equilibrium is unchanged and the period increases." }, { key: "b", text: "The equilibrium shifts and the period must decrease." }, { key: "c", text: "The equilibrium shifts while the natural period stays fixed." }, { key: "d", text: "The stiffness doubles while the equilibrium stays fixed." }], answer: "c", explanation: "A constant inertial force adds a constant term to the force balance, shifting the equilibrium position. Measuring displacement from that new equilibrium leaves $m\\ddot y=-k_sy$, so the natural period is unchanged. Time-varying support acceleration would be a different problem.", sectionId: "spring-period-and-equilibrium", source: { document: "quick-revision", page: 14 }, cognitive: "understanding" },
    { id: "note-oscillations-011", text: "Two light springs with stiffnesses $60$ and $120\\,\\mathrm{N\\,m^{-1}}$ are connected in series. What is their effective stiffness?", options: [{ key: "a", text: "$180\\,\\mathrm{N\\,m^{-1}}$" }, { key: "b", text: "$90\\,\\mathrm{N\\,m^{-1}}$" }, { key: "c", text: "$60\\,\\mathrm{N\\,m^{-1}}$" }, { key: "d", text: "$40\\,\\mathrm{N\\,m^{-1}}$" }], answer: "d", explanation: "In series the same force acts through both springs and their extensions add. Thus $k_{\\mathrm{eff}}=\\frac{60\\times120}{60+120}=40\\,\\mathrm{N\\,m^{-1}}$. Adding the stiffnesses would describe a parallel combination instead.", sectionId: "series-springs", source: { document: "quick-revision", page: 14 }, cognitive: "application" },
    { id: "note-oscillations-012", text: "Three parallel springs of stiffness $100$, $200$ and $300\\,\\mathrm{N\\,m^{-1}}$ share a rigid translating bar. Each stretches by $0.020\\,\\mathrm m$. What force does the $200\\,\\mathrm{N\\,m^{-1}}$ spring carry?", options: [{ key: "a", text: "$2.0\\,\\mathrm N$" }, { key: "b", text: "$4.0\\,\\mathrm N$" }, { key: "c", text: "$6.0\\,\\mathrm N$" }, { key: "d", text: "$12\\,\\mathrm N$" }], answer: "b", explanation: "Parallel springs have the same extension, not necessarily the same force. The middle spring carries $F=200\\times0.020=4.0\\,\\mathrm N$. The individual forces are 2, 4 and 6 N, and their total is 12 N.", sectionId: "parallel-and-cut-springs", source: { document: "quick-revision", page: 15 }, cognitive: "application" },
    { id: "note-oscillations-013", text: "A uniform spring of stiffness $90\\,\\mathrm{N\\,m^{-1}}$ is cut into three equal pieces. What effective stiffness results when all three pieces are mounted in parallel?", options: [{ key: "a", text: "$30\\,\\mathrm{N\\,m^{-1}}$" }, { key: "b", text: "$270\\,\\mathrm{N\\,m^{-1}}$" }, { key: "c", text: "$810\\,\\mathrm{N\\,m^{-1}}$" }, { key: "d", text: "$90\\,\\mathrm{N\\,m^{-1}}$" }], answer: "c", explanation: "Each piece has one-third of the original active length and therefore three times its stiffness: $270\\,\\mathrm{N\\,m^{-1}}$. Three such pieces in parallel add to $810\\,\\mathrm{N\\,m^{-1}}$, or $n^2K$ with $n=3$.", sectionId: "parallel-and-cut-springs", source: { document: "quick-revision", page: 15 }, cognitive: "application" },
    { id: "note-oscillations-014", text: "A mass of $0.36\\,\\mathrm{kg}$ oscillates on a light spring of effective stiffness $144\\,\\mathrm{N\\,m^{-1}}$. What is its natural period?", options: [{ key: "a", text: "$\\frac{\\pi}{10}\\,\\mathrm s$" }, { key: "b", text: "$\\frac{\\pi}{5}\\,\\mathrm s$" }, { key: "c", text: "$\\frac{\\pi}{20}\\,\\mathrm s$" }, { key: "d", text: "$\\frac{2\\pi}{5}\\,\\mathrm s$" }], answer: "a", explanation: "The angular frequency is $\\omega=\\sqrt{\\frac{144}{0.36}}=20\\,\\mathrm{rad\\,s^{-1}}$. Therefore $T=\\frac{2\\pi}{20}=\\frac{\\pi}{10}\\,\\mathrm s$, approximately 0.314 s. The reciprocal of angular frequency alone is not a complete period.", sectionId: "spring-period-and-equilibrium", source: { document: "quick-revision", page: 14 }, cognitive: "application" },
    { id: "note-oscillations-015", text: "A linearly damped oscillator has undamped angular frequency $10\\,\\mathrm{rad\\,s^{-1}}$ and damping parameter $\\gamma=\\frac{b}{2m}=6\\,\\mathrm{s^{-1}}$. What is the ratio of damped period to undamped period?", options: [{ key: "a", text: "$0.80$" }, { key: "b", text: "$1.25$" }, { key: "c", text: "$1.60$" }, { key: "d", text: "$2.50$" }], answer: "b", explanation: "The motion is underdamped because $6&lt;10$. Its angular frequency is $\\omega_d=\\sqrt{10^2-6^2}=8\\,\\mathrm{rad\\,s^{-1}}$. Since period is inversely proportional to angular frequency, $\\frac{T_d}{T_0}=\\frac{10}{8}=1.25$.", sectionId: "damped-period", source: { document: "quick-revision", page: 14 }, cognitive: "application" },
    { id: "note-oscillations-016", text: "A fixed-length pendulum clock is moved to a place where gravity is $0.81$ of its calibration value. Which period change and clock behaviour follow in the small-angle model?", options: [{ key: "a", text: "Period becomes $0.81T_0$; the clock gains time." }, { key: "b", text: "Period becomes $0.90T_0$; the clock gains time." }, { key: "c", text: "Period becomes $\\frac{100}{81}T_0$; the clock loses time." }, { key: "d", text: "Period becomes $\\frac{10}{9}T_0$; the clock loses time." }], answer: "d", explanation: "At fixed length, $T\\propto\\frac{1}{\\sqrt g}$. The new-to-old period ratio is $\\frac{1}{\\sqrt{0.81}}=\\frac{10}{9}$. Each swing takes longer, so a clock calibrated to the old swing period registers less elapsed time and runs slow.", sectionId: "pendulum-clock-and-graphs", source: { document: "quick-revision", page: 15 }, cognitive: "application" },
    { id: "note-oscillations-017", text: "A graph of simple-pendulum $T^2$ against length $l$ has slope $4.0\\,\\mathrm{s^2\\,m^{-1}}$. What gravitational acceleration does it imply?", options: [{ key: "a", text: "$\\pi^2\\,\\mathrm{m\\,s^{-2}}$" }, { key: "b", text: "$2\\pi^2\\,\\mathrm{m\\,s^{-2}}$" }, { key: "c", text: "$4\\pi^2\\,\\mathrm{m\\,s^{-2}}$" }, { key: "d", text: "$\\frac{\\pi^2}{2}\\,\\mathrm{m\\,s^{-2}}$" }], answer: "a", explanation: "Squaring the pendulum formula gives $T^2=\\frac{4\\pi^2}{g}l$. Hence the graph slope is $\\frac{4\\pi^2}{g}=4$, which yields $g=\\pi^2\\,\\mathrm{m\\,s^{-2}}$. The axes matter: the reciprocal slope belongs to a graph with the axes exchanged.", sectionId: "pendulum-clock-and-graphs", source: { document: "quick-revision", page: 15 }, cognitive: "application" },
    { id: "note-oscillations-018", text: "An ideal uniform U-tube contains a liquid column of total length $0.80\\,\\mathrm m$. For $g=10\\,\\mathrm{m\\,s^{-2}}$, what is the small-oscillation period?", options: [{ key: "a", text: "$0.20\\pi\\,\\mathrm s$" }, { key: "b", text: "$0.80\\pi\\,\\mathrm s$" }, { key: "c", text: "$0.60\\pi\\,\\mathrm s$" }, { key: "d", text: "$0.40\\pi\\,\\mathrm s$" }], answer: "d", explanation: "The level difference is twice the displacement of one surface, giving $\\omega^2=\\frac{2g}{l}$. Therefore $T=2\\pi\\sqrt{\\frac{0.80}{20}}=2\\pi(0.20)=0.40\\pi\\,\\mathrm s$, about 1.26 s. The given length already includes the whole moving column.", sectionId: "u-tube-liquid", source: { document: "quick-revision", page: 15 }, cognitive: "application" },
    { id: "note-oscillations-019", text: "Two ideal uniform U-tubes have the same total liquid-column length. The second has twice the cross-sectional area and four times the liquid density. At the same gravity, how do their periods compare?", options: [{ key: "a", text: "The second period is twice the first." }, { key: "b", text: "The two periods are equal." }, { key: "c", text: "The second period is four times the first." }, { key: "d", text: "The second period is half the first." }], answer: "b", explanation: "Both the restoring-force coefficient and the liquid mass contain the same factor $\\rho A_c$, which cancels. With equal total column length and gravity, both tubes have $T=2\\pi\\sqrt{\\frac{l}{2g}}$. The comparison assumes the ideal uniform-area, negligible-viscosity model.", sectionId: "u-tube-liquid", source: { document: "quick-revision", page: 15 }, cognitive: "understanding" },
    { id: "note-oscillations-020", text: "At which position does a nonzero-amplitude ideal SHM oscillator have maximum speed and zero restoring acceleration?", options: [{ key: "a", text: "At either extreme displacement" }, { key: "b", text: "Halfway from the mean to an extreme" }, { key: "c", text: "At its mean equilibrium position" }, { key: "d", text: "At every point during a complete cycle" }], answer: "c", explanation: "At $y=0$, the restoring acceleration $a=-\\omega^2y$ vanishes and the speed is $\\omega A$, its maximum. At an extreme, the situation reverses: speed is zero and acceleration magnitude is greatest.", sectionId: "displacement-velocity-acceleration", source: { document: "quick-revision", page: 15 }, cognitive: "recall" }
  ]
};