window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["p-block"] = {
  id: "p-block",
  subject: "Chemistry",
  title: "p-block elements and non-metals",
  sections: [
    {
      id: "aluminium-minerals",
      title: "Aluminium minerals at the opening of page 97",
      sources: [{ document: "quick-revision", page: 97 }],
      html: "<table><thead><tr><th>Source mineral</th><th>Formula and significance</th></tr></thead><tbody><tr><td>Bauxite</td><td>The chief aluminium ore; represented in the source as Al<sub>2</sub>O<sub>3</sub>&middot;2H<sub>2</sub>O.</td></tr><tr><td>Feldspar</td><td>The listed potassium feldspar composition is KAlSi<sub>3</sub>O<sub>8</sub>.</td></tr><tr><td>Corundum</td><td>Al<sub>2</sub>O<sub>3</sub>.</td></tr><tr><td>Cryolite</td><td>Na<sub>3</sub>AlF<sub>6</sub>.</td></tr></tbody></table><p><strong>Source clarification:</strong> Bauxite is a variable mixture of hydrated aluminium oxides and hydroxides, not a pure mineral with one invariant hydration number. Feldspar is a mineral group; the printed formula describes a potassium member. These aluminium-containing minerals do not all have the same economic role: cryolite is especially important as a component of the electrolyte used in aluminium extraction.</p>"
    },
    {
      id: "group14-trends",
      title: "Group 14: electronic structure and oxidation states",
      sources: [{ document: "quick-revision", page: 97 }],
      html: "<p>The listed group-14 members, in increasing atomic number, are carbon, silicon, germanium, tin and lead: C, Si, Ge, Sn and Pb. Their general valence configuration is ns<sup>2</sup>np<sup>2</sup>. Covalent radius generally increases down this series.</p><p>The source prints the ionization-enthalpy order C &gt; Si &gt; Ge &gt; Sn &gt; Pb. <strong>Source correction:</strong> For first ionization enthalpy, lead is slightly higher than tin; the corrected decreasing order is <strong>C &gt; Si &gt; Ge &gt; Pb &gt; Sn</strong>. A general downward trend does not remove this exception.</p><p>The source emphasizes +4 for carbon and silicon and +2/+4 for the heavier members. From Ge to Pb, +4 generally becomes less stable relative to +2; the increasing stability of +2 is associated with the inert-pair effect, or reduced participation of the ns<sup>2</sup> pair in bonding.</p><p><strong>Source clarification:</strong> This is an oxidation-state trend, not a claim that carbon and silicon have only +4. Carbon is +2 in CO and &minus;4 in methane. The source's catenation order is C &gt;&gt;&gt; Si &gt; Ge &asymp; Sn: carbon has a particularly strong tendency to form extended chains and rings, but catenation is not exclusive to carbon.</p>"
    },
    {
      id: "group14-oxides-halides-water",
      title: "Group 14: oxides, halides and water",
      sources: [{ document: "quick-revision", page: 97 }],
      html: "<p>The source classifies CO as a neutral oxide; CO<sub>2</sub>, SiO<sub>2</sub> and GeO<sub>2</sub> as acidic oxides; and SnO<sub>2</sub> and PbO<sub>2</sub> as amphoteric oxides. <strong>Source clarification:</strong> GeO<sub>2</sub> lies near the acidic-amphoteric boundary and can show amphoteric behaviour under suitable conditions. Such acid-base categories describe specified reactions, not an assertion that every oxide reacts equally rapidly with every acid or base.</p><p>Group-14 halides commonly have formulas MX<sub>4</sub> and MX<sub>2</sub>. The source contrasts SnF<sub>4</sub> and PbF<sub>4</sub>, called ionic, with other largely covalent tetrahalides. <strong>Source clarification:</strong> The solid fluorides have extended, highly coordinated structures and appreciable ionic character; 'ionic' should not imply perfectly ionic bonding in every phase. Molecular versus extended structure is an important distinction alongside bond polarity.</p><p>The source attributes lead's apparent resistance to water to a protective oxide film and says C, Si and Ge are unaffected by water. These statements concern ordinary conditions. Carbon reacts with steam at high temperature, for example in water-gas formation. Lead can corrode or release toxic lead species depending on water chemistry, so passivation does not establish that lead is safe in contact with drinking water.</p>"
    },
    {
      id: "carbon-allotropes",
      title: "Diamond, graphite and fullerenes",
      sources: [{ document: "quick-revision", page: 97 }],
      html: "<table><thead><tr><th>Allotrope</th><th>All source properties and structural meaning</th></tr></thead><tbody><tr><td>Diamond</td><td>Carbon is approximately sp<sup>3</sup>-hybridized in a rigid three-dimensional covalent network. The material is extremely hard and is used as an abrasive.</td></tr><tr><td>Graphite</td><td>The thermodynamically stable common carbon allotrope at ordinary pressure. Its sheets contain sp<sup>2</sup>-bonded carbon. It conducts electricity and is used as a lubricant in machinery.</td></tr><tr><td>Fullerenes</td><td>Molecular carbon cages. Buckminsterfullerene, C<sub>60</sub>, has a football-like cage and is the principal example illustrated by the source's description.</td></tr></tbody></table><p><strong>Source corrections:</strong> Graphite has strong covalent bonds <em>within</em> each sheet and weak van der Waals attractions <em>between</em> sheets; the printed phrase about each layer being held by van der Waals forces must not be applied to the in-plane bonds. Delocalized electrons explain conduction, while easy interlayer sliding contributes to lubrication. Diamond's 'hardest substance' label is an introductory description of exceptional hardness, not an unrestricted claim for every material, direction or pressure. Fullerenes form a family, so not every fullerene molecule is C<sub>60</sub>.</p>"
    },
    {
      id: "industrial-gas-mixtures",
      title: "Carbogen and the complete fuel-gas table",
      sources: [{ document: "quick-revision", page: 97 }],
      html: "<p><strong>Carbogen</strong> is a mixture of oxygen and carbon dioxide, O<sub>2</sub> + CO<sub>2</sub>. Its composition is a chemical identification here, not guidance for inhalation or medical use.</p><table><thead><tr><th>Gas</th><th>Composition printed in the source</th></tr></thead><tbody><tr><td>Water gas</td><td>CO + H<sub>2</sub></td></tr><tr><td>Synthetic gas or synthesis gas</td><td>CO + 2H<sub>2</sub></td></tr><tr><td>Semi-water gas</td><td>CO + N<sub>2</sub> + H<sub>2</sub></td></tr><tr><td>Producer gas</td><td>2CO + 4N<sub>2</sub></td></tr><tr><td>Oil gas</td><td>H<sub>2</sub> + CO + CH<sub>4</sub> + C<sub>2</sub>H<sub>4</sub></td></tr><tr><td>Natural gas</td><td>CH<sub>4</sub> + CO<sub>2</sub> + CO + H<sub>2</sub>, as printed</td></tr><tr><td>Biogas</td><td>CH<sub>4</sub> + CO<sub>2</sub></td></tr><tr><td>Coal gas</td><td>H<sub>2</sub> + CO + CH<sub>4</sub></td></tr></tbody></table><p><strong>Source corrections:</strong> These are component lists or idealized mixtures, not fixed analytical compositions. Synthesis gas generally means a CO/H<sub>2</sub> mixture whose ratio depends on production and intended synthesis; 1:2 is one useful composition. Producer gas also has a variable CO/N<sub>2</sub> ratio and other components. Natural gas is principally methane with variable higher hydrocarbons and impurities such as CO<sub>2</sub> or nitrogen; CO and H<sub>2</sub> are not defining major constituents of ordinary natural gas. Water gas, oil gas and coal gas can contain poisonous CO; the table is not a description of breathable mixtures.</p>"
    },
    {
      id: "borax-bead-glass",
      title: "Borax bead products and glass types",
      sources: [{ document: "quick-revision", page: 97 }],
      html: "<ul><li>The source identifies a <strong>metal metaborate</strong> as the coloured compound formed in the classical borax-bead test. The observed colour depends on the metal and flame conditions.</li><li><strong>Flint glass:</strong> the source's optical-instrument example contains lead compounds, which can give a high refractive index and dispersion.</li><li><strong>Pyrex:</strong> the laboratory-glass example refers to borosilicate glass containing boron oxide, with useful resistance to thermal shock.</li></ul><p><strong>Source corrections:</strong> Glass at room temperature is an <strong>amorphous solid</strong>, not a liquid that slowly flows like a normal fluid. Calling it a 'supercooled liquid' is historical shorthand that obscures the glass transition and solid-like behaviour. Not all modern flint glasses contain lead, and a brand name alone does not guarantee that every commercial product is borosilicate.</p>"
    },
    {
      id: "group15-trends",
      title: "Group 15: members, forms and trends",
      sources: [{ document: "quick-revision", page: 97 }, { document: "quick-revision", page: 98 }],
      html: "<p>Group 15 is the pnictogen or pnicogen family. The source lists N, P, As, Sb and Bi, with valence configuration ns<sup>2</sup>np<sup>3</sup>. Nitrogen is commonly N<sub>2</sub>, a relatively unreactive gas; phosphorus is a solid non-metal; arsenic and antimony are solid metalloids; bismuth is a metal. Atomic radii generally increase and electronegativity generally decreases down the group.</p><p><strong>Source corrections:</strong> N<sub>2</sub> is relatively unreactive because of its strong triple bond, not incapable of reaction. P<sub>4</sub> describes white phosphorus, not every phosphorus allotrope. The printed As<sub>4</sub> and Sb<sub>4</sub> labels do not describe the ordinary extended structures of all solid arsenic and antimony samples.</p><p>The source says all members except Bi show allotropy. This is a conventional comparison of common ambient forms, not a claim about every high-pressure phase. It also gives a rough melting-point rise from nitrogen to arsenic followed by a fall toward antimony and bismuth. Allotrope and pressure matter: arsenic sublimes at ordinary pressure rather than having an ordinary-pressure melting point. Crystal structure and bonding must be considered, so attributing the whole melting trend simply to the inert-pair effect is inadequate.</p>"
    },
    {
      id: "group15-trihalides",
      title: "Group-15 trihalide comparisons",
      sources: [{ document: "quick-revision", page: 98 }],
      html: "<ul><li>The printed stability comparison is NF<sub>3</sub> &gt; NCl<sub>3</sub> &gt; NBr<sub>3</sub>. It describes the relative stability of these nitrogen trihalides; the heavier compounds are much less stable.</li><li>The phosphorus-trihalide bond-angle order is PF<sub>3</sub> &lt; PCl<sub>3</sub> &lt; PBr<sub>3</sub> &lt; PI<sub>3</sub>. Changing halogen electronegativity changes the distribution of bonding electron density and the interbond repulsions near phosphorus.</li><li>The source prints 'Lewis acid strength: PCl<sub>3</sub> &gt; AsCl<sub>3</sub> &gt; SbCl<sub>3</sub>'. This comparative assertion is retained but is not accepted as a universally verified order.</li></ul><p><strong>Unresolved source qualification:</strong> The trichlorides can participate in donor and acceptor chemistry. A Lewis-acidity ranking requires a defined ligand, medium or comparison criterion; none is provided. It is unclear whether the author intended a Lewis-basicity comparison instead. No scored question depends on the printed acidity order.</p>"
    },
    {
      id: "nitrogen-oxide-table",
      title: "All six nitrogen oxides: preparation and properties",
      sources: [{ document: "quick-revision", page: 98 }],
      html: "<table><thead><tr><th>Oxide and nitrogen oxidation state</th><th>Source reaction and properties</th></tr></thead><tbody><tr><td>N<sub>2</sub>O; average +1</td><td>NH<sub>4</sub>NO<sub>3</sub> &rarr; N<sub>2</sub>O + 2H<sub>2</sub>O on controlled thermal decomposition. Colourless gas; neutral oxide.</td></tr><tr><td>NO; +2</td><td>2NaNO<sub>2</sub> + 2FeSO<sub>4</sub> + 3H<sub>2</sub>SO<sub>4</sub> &rarr; Fe<sub>2</sub>(SO<sub>4</sub>)<sub>3</sub> + 2NaHSO<sub>4</sub> + 2NO + 2H<sub>2</sub>O. Colourless gas; neutral oxide.</td></tr><tr><td>N<sub>2</sub>O<sub>3</sub>; average +3</td><td>The low-temperature combination is represented by 2NO + N<sub>2</sub>O<sub>4</sub> &rightleftharpoons; 2N<sub>2</sub>O<sub>3</sub>; the source labels the arrow 250 K. Blue, acidic condensed material.</td></tr><tr><td>NO<sub>2</sub>; +4</td><td>2Pb(NO<sub>3</sub>)<sub>2</sub> &rarr; 2PbO + 4NO<sub>2</sub> + O<sub>2</sub>, with 673 K printed on the arrow. Brown gas; acidic oxide.</td></tr><tr><td>N<sub>2</sub>O<sub>4</sub>; +4</td><td>2NO<sub>2</sub> &rightleftharpoons; N<sub>2</sub>O<sub>4</sub>. Cooling favours the dimer; heating favours NO<sub>2</sub>. Colourless pure substance; acidic oxide.</td></tr><tr><td>N<sub>2</sub>O<sub>5</sub>; +5</td><td>4HNO<sub>3</sub> + P<sub>4</sub>O<sub>10</sub> &rarr; 4HPO<sub>3</sub> + 2N<sub>2</sub>O<sub>5</sub>. Colourless solid; acidic oxide.</td></tr></tbody></table><p><strong>Source corrections:</strong> The oxidation states for oxides containing inequivalent nitrogen atoms are averages. The source calls N<sub>2</sub>O<sub>3</sub> a blue solid, but at the stated 250 K its condensed form is liquid, not solid; it is unstable toward dissociation, and a solid requires lower temperature. N<sub>2</sub>O<sub>4</sub> is not restricted to the source's 'solid/liquid' description: vapour and a temperature-dependent NO<sub>2</sub>/N<sub>2</sub>O<sub>4</sub> equilibrium also occur. These equations describe chemistry, not instructions for generating toxic gases or heating hazardous salts.</p>"
    },
    {
      id: "nitric-acid-preparation",
      title: "Nitric acid preparation and the Ostwald sequence",
      sources: [{ document: "quick-revision", page: 98 }],
      html: "<p>The nitrate-sulfuric-acid preparation is NaNO<sub>3</sub> + H<sub>2</sub>SO<sub>4</sub> &rarr; NaHSO<sub>4</sub> + HNO<sub>3</sub>. <strong>Source correction:</strong> The printed coefficient 5 before H<sub>2</sub>SO<sub>4</sub> is incorrect for these products; the balanced coefficient is 1.</p><p>The source's <strong>Ostwald process</strong> consists of three linked reactions:</p><ol><li>4NH<sub>3</sub> + 5O<sub>2</sub> &rarr; 4NO + 6H<sub>2</sub>O, over platinum-rhodium gauze.</li><li>2NO + O<sub>2</sub> &rightleftharpoons; 2NO<sub>2</sub>.</li><li>3NO<sub>2</sub> + H<sub>2</sub>O &rarr; 2HNO<sub>3</sub> + NO; the NO can be reoxidized.</li></ol><p><strong>Source correction:</strong> The ammonia-oxidation arrow prints 500 K and 9 bar. The 500 K value is not a representative industrial burner temperature: platinum-rhodium ammonia oxidation normally operates at much higher temperatures, roughly 800-900 &deg;C, with actual conditions depending on plant design. The pressure shown is one process example, not a universal requirement. The equations and catalyst identity are the study points; no operating procedure is supplied.</p>"
    },
    {
      id: "nitric-acid-metals",
      title: "Nitric acid and metals: every concentration-table entry",
      sources: [{ document: "quick-revision", page: 98 }],
      html: "<p>Nitric acid acts as an acid and an oxidizing agent. Its reduction product depends on concentration, metal, temperature and surface condition. The source table lists principal products rather than complete balanced equations; water is consequently omitted in several rows.</p><table><thead><tr><th>Source condition and metal</th><th>Printed or corrected main products</th></tr></thead><tbody><tr><td>Very dilute HNO<sub>3</sub>; Mg, Mn</td><td>H<sub>2</sub> and metal nitrate, the familiar conditional exceptions to the usual oxidizing-acid behaviour.</td></tr><tr><td>Very dilute HNO<sub>3</sub>; Fe, Zn, Sn</td><td>NH<sub>4</sub>NO<sub>3</sub> and metal nitrate.</td></tr><tr><td>Dilute HNO<sub>3</sub>; Pb, Cu, Ag, Hg</td><td>NO and metal nitrate. The source's 'Na' in this product cell is a typographical error, not sodium metal.</td></tr><tr><td>Dilute HNO<sub>3</sub>; Fe, Zn</td><td>N<sub>2</sub>O and metal nitrate under appropriate reducing conditions.</td></tr><tr><td>Dilute HNO<sub>3</sub>; Sn</td><td>NH<sub>4</sub>NO<sub>3</sub> and Sn(NO<sub>3</sub>)<sub>2</sub>, as the source's limiting-product description.</td></tr><tr><td>Concentrated HNO<sub>3</sub>; Zn, Fe, Pb, Cu, Ag</td><td>NO<sub>2</sub> and metal nitrate in the source's simplified reacting-metal row.</td></tr><tr><td>Concentrated HNO<sub>3</sub>; Sn</td><td>NO<sub>2</sub> and H<sub>2</sub>SnO<sub>3</sub>, conventionally called metastannic acid or hydrated tin(IV) oxide.</td></tr></tbody></table><p><strong>Source corrections:</strong> These rows are conditional teaching patterns, not guaranteed products for every dilution or metal surface. Iron is commonly passivated by cold concentrated nitric acid and therefore cannot be treated as automatically reacting like copper in that row. Tin chemistry and the extent of nitrate reduction are especially condition-dependent.</p><p>Two well-defined copper equations illustrate the distinction: 3Cu + 8HNO<sub>3</sub> &rarr; 3Cu(NO<sub>3</sub>)<sub>2</sub> + 2NO + 4H<sub>2</sub>O for the usual dilute-acid comparison; Cu + 4HNO<sub>3</sub> &rarr; Cu(NO<sub>3</sub>)<sub>2</sub> + 2NO<sub>2</sub> + 2H<sub>2</sub>O for the concentrated-acid comparison. For the stated tin(IV) product: Sn + 4HNO<sub>3</sub> &rarr; H<sub>2</sub>SnO<sub>3</sub> + 4NO<sub>2</sub> + H<sub>2</sub>O.</p>"
    },
    {
      id: "brown-ring-test",
      title: "The brown-ring nitrate test",
      sources: [{ document: "quick-revision", page: 98 }],
      html: "<p>Nitrate is reduced to nitric oxide by Fe<sup>2+</sup> in an acidic medium. The balanced ionic equation is NO<sub>3</sub><sup>&minus;</sup> + 3Fe<sup>2+</sup> + 4H<sup>+</sup> &rarr; NO + 3Fe<sup>3+</sup> + 2H<sub>2</sub>O.</p><p>The source then represents formation of the brown nitrosyl complex as [Fe(H<sub>2</sub>O)<sub>6</sub>]<sup>2+</sup> + NO &rarr; [Fe(H<sub>2</sub>O)<sub>5</sub>(NO)]<sup>2+</sup> + H<sub>2</sub>O. The brown colour is associated with this coordinated nitrosyl species.</p><p><strong>Source correction:</strong> The first printed equation omits essential coefficients. Nitrogen changes from +5 in nitrate to +2 in free NO, so it gains three electrons and requires three Fe<sup>2+</sup> ions to become Fe<sup>3+</sup>. The complex's total charge should not be confused with an unqualified assignment of every internal metal-ligand oxidation state.</p>"
    },
    {
      id: "phosphorus-allotropes",
      title: "White, red and black phosphorus",
      sources: [{ document: "quick-revision", page: 98 }, { document: "quick-revision", page: 100 }],
      html: "<ul><li><strong>White phosphorus:</strong> molecular P<sub>4</sub> has a strained tetrahedral structure and is relatively reactive and less stable than red or black phosphorus. The repeated source description calls its glow 'phosphorescence'.</li><li><strong>Red phosphorus:</strong> less reactive than white phosphorus; an extended polymeric structure can be described using linked or opened phosphorus units. It is not simply a collection of independent P<sub>4</sub> molecules.</li><li><strong>Black phosphorus:</strong> an extended layered allotrope. The source distinguishes an '&alpha;-black' form with monoclinic crystals that allegedly sublimes in air and a '&beta;-black' form with a layered structure.</li></ul><p><strong>Source corrections:</strong> White phosphorus glows through slow oxidative <em>chemiluminescence</em>, not ordinary light-storage phosphorescence. The later statement 'phosphorus is tetratomic' applies to white P<sub>4</sub>, not to the red and black extended allotropes. Ordinary black phosphorus has a layered orthorhombic structure and is susceptible to oxidation in air; the printed air-sublimation claim is not a safe handling rule.</p><p><strong>Unresolved source qualification:</strong> The source gives no phase conditions or definitions that reliably identify its two black-phosphorus labels. The exact phase intended by the monoclinic '&alpha;-black' entry remains unresolved; no MCQ requires that label-to-structure assignment.</p>"
    },
    {
      id: "group16-trends",
      title: "Group 16: members, states and periodic trends",
      sources: [{ document: "quick-revision", page: 98 }, { document: "quick-revision", page: 99 }],
      html: "<p>The listed group-16 elements are O, S, Se, Te and Po, with valence configuration ns<sup>2</sup>np<sup>4</sup>. Oxygen commonly occurs as diatomic O<sub>2</sub>, with multiple bonding involving p orbitals. Sulfur commonly occurs as solid S<sub>8</sub>; selenium and tellurium are solids; polonium is radioactive and metallic.</p><p>Atomic and comparable ionic radii generally increase down the group, while electronegativity generally decreases. The source records increasing melting and boiling temperatures toward Te, with Po lower than Te, and notes allotropy among these members. Such comparisons require the relevant allotrope and pressure.</p><p><strong>Source corrections:</strong> The chalcogen name applies to the group, not only to its first four members as stated in the source. Selenium is normally classified as a non-metal and tellurium as a metalloid; grouping both simply as metalloids obscures this distinction. Ionic-radius comparisons require matched charge and coordination, rather than comparing arbitrary ions.</p>"
    },
    {
      id: "group16-hydrides",
      title: "All six comparisons for group-16 hydrides",
      sources: [{ document: "quick-revision", page: 99 }],
      html: "<table><thead><tr><th>Property</th><th>Source order</th></tr></thead><tbody><tr><td>Increasing boiling temperature</td><td>H<sub>2</sub>S &lt; H<sub>2</sub>Se &lt; H<sub>2</sub>Te &lt; H<sub>2</sub>O</td></tr><tr><td>Decreasing bond angle</td><td>H<sub>2</sub>O &gt; H<sub>2</sub>S &gt; H<sub>2</sub>Se &gt; H<sub>2</sub>Te</td></tr><tr><td>Decreasing reducing power</td><td>H<sub>2</sub>Te &gt; H<sub>2</sub>Se &gt; H<sub>2</sub>S &gt; H<sub>2</sub>O</td></tr><tr><td>Decreasing volatility</td><td>H<sub>2</sub>S &gt; H<sub>2</sub>Se &gt; H<sub>2</sub>Te &gt; H<sub>2</sub>O</td></tr><tr><td>Increasing acidic character</td><td>H<sub>2</sub>O &lt; H<sub>2</sub>S &lt; H<sub>2</sub>Se &lt; H<sub>2</sub>Te</td></tr><tr><td>Decreasing thermal stability</td><td>H<sub>2</sub>O &gt; H<sub>2</sub>S &gt; H<sub>2</sub>Se &gt; H<sub>2</sub>Te</td></tr></tbody></table><p>Hydrogen bonding gives water its unusually high boiling temperature and low volatility. Down the heavier hydrides, increasing polarizability raises boiling temperature, while weaker element-hydrogen bonds help explain lower thermal stability and greater acidity and reducing ability. The bond-angle trend is a structural comparison, not a ranking of intermolecular hydrogen-bond strength.</p>"
    },
    {
      id: "oxide-classification",
      title: "Simple, mixed, acidic, basic, amphoteric and neutral oxides",
      sources: [{ document: "quick-revision", page: 99 }, { document: "quick-revision", page: 100 }],
      html: "<table><thead><tr><th>Source category</th><th>Every listed example</th></tr></thead><tbody><tr><td>Simple oxides</td><td>MgO, PbO, FeO</td></tr><tr><td>Mixed oxides</td><td>Pb<sub>3</sub>O<sub>4</sub> and Fe<sub>3</sub>O<sub>4</sub>; formal representations are 2PbO&middot;PbO<sub>2</sub> and FeO&middot;Fe<sub>2</sub>O<sub>3</sub>.</td></tr><tr><td>Acidic oxides</td><td>SO<sub>3</sub>, Mn<sub>2</sub>O<sub>7</sub>, CO<sub>2</sub>, N<sub>2</sub>O<sub>5</sub>, V<sub>2</sub>O<sub>5</sub></td></tr><tr><td>Basic oxides</td><td>Na<sub>2</sub>O, CaO, BaO</td></tr><tr><td>Amphoteric oxides</td><td>Al<sub>2</sub>O<sub>3</sub>, BeO</td></tr><tr><td>Neutral oxides</td><td>CO, NO, N<sub>2</sub>O, H<sub>2</sub>O</td></tr></tbody></table><p>The composition classes 'simple' and 'mixed' are separate from acid-base classification. High-oxidation-state metal oxides can be acidic; acidity is not confined to non-metal oxides. V<sub>2</sub>O<sub>5</sub> is often treated as predominantly acidic but can show amphoteric behaviour under appropriate conditions. Water's placement among neutral oxides does not deny its amphiprotic behaviour as a solvent.</p><p>The page-100 comparison says MgO does not appreciably dissolve by reaction with aqueous NaOH because it is basic, while SO<sub>2</sub>/SiO<sub>2</sub> and Al<sub>2</sub>O<sub>3</sub> react with alkali because they are acidic and amphoteric, respectively. <strong>Source clarification:</strong> Silica and crystalline alumina do not necessarily dissolve rapidly in cold dilute NaOH; temperature, concentration and solid form matter. Amphoteric does not mean equally soluble under every condition.</p>"
    },
    {
      id: "sulfur-allotropes",
      title: "Rhombic and monoclinic sulfur",
      sources: [{ document: "quick-revision", page: 99 }, { document: "quick-revision", page: 100 }],
      html: "<table><thead><tr><th>Allotrope</th><th>Source properties</th></tr></thead><tbody><tr><td>Rhombic or &alpha;-sulfur</td><td>Yellow; insoluble in water and soluble in carbon disulfide, CS<sub>2</sub>.</td></tr><tr><td>Monoclinic or &beta;-sulfur</td><td>Needle-shaped crystals; soluble in CS<sub>2</sub>. The source calls the crystals colourless.</td></tr></tbody></table><p><strong>Source correction:</strong> Monoclinic sulfur is generally described as pale yellow rather than universally colourless. These two common forms contain S<sub>8</sub> rings but differ in crystal packing. Their transition temperature is about 95.5 &deg;C, rounded to <strong>96 &deg;C</strong> in the source: rhombic sulfur is the stable form below it and monoclinic sulfur above it, before melting. The source also identifies sulfur as the cross-linking agent in conventional rubber vulcanization.</p>"
    },
    {
      id: "group17-elements",
      title: "Group 17: halogens and their elemental trends",
      sources: [{ document: "quick-revision", page: 99 }],
      html: "<p>The source lists F, Cl, Br, I and At, with valence configuration ns<sup>2</sup>np<sup>5</sup>.</p><table><thead><tr><th>Elemental substance</th><th>Source appearance near room conditions</th></tr></thead><tbody><tr><td>F<sub>2</sub></td><td>Pale yellow gas</td></tr><tr><td>Cl<sub>2</sub></td><td>Greenish-yellow gas</td></tr><tr><td>Br<sub>2</sub></td><td>Reddish-brown liquid</td></tr><tr><td>I<sub>2</sub></td><td>Printed as a purple solid; more precisely, dark grey-violet crystals give a violet vapour.</td></tr></tbody></table><p>Atomic radius generally increases down the group. Fluorine is the most electronegative element, and electronegativity decreases from F to I. Melting and boiling temperatures of the familiar molecular halogens increase down the series as dispersion forces strengthen.</p><p>The source gives both oxidizing-power and general reactivity orders F<sub>2</sub> &gt; Cl<sub>2</sub> &gt; Br<sub>2</sub> &gt; I<sub>2</sub>. The oxidizing order is useful for the usual redox comparisons, but 'reactivity' also depends on the reactant and conditions. Fluorine reacts with water, so its position is not a recipe for a simple aqueous displacement experiment.</p><p><strong>Source clarification:</strong> Calling halogens the smallest atoms in a period refers to a covalent-radius trend; it is not valid to compare their covalent radii directly with noble-gas van der Waals radii as though the definitions were identical.</p>"
    },
    {
      id: "hydrogen-halide-trends",
      title: "Hydrogen halides: the complete property list",
      sources: [{ document: "quick-revision", page: 99 }, { document: "quick-revision", page: 100 }],
      html: "<table><thead><tr><th>Property, decreasing order</th><th>Comparison</th></tr></thead><tbody><tr><td>Boiling temperature</td><td>HF &gt; HI &gt; HBr &gt; HCl</td></tr><tr><td>Melting temperature</td><td>HI &gt; HF &gt; HBr &gt; HCl</td></tr><tr><td>H-X bond length</td><td>HI &gt; HBr &gt; HCl &gt; HF</td></tr><tr><td>Bond dissociation energy</td><td>HF &gt; HCl &gt; HBr &gt; HI</td></tr><tr><td>Conventional acid-strength order</td><td>HI &gt; HBr &gt; HCl &gt; HF</td></tr><tr><td>Thermal stability</td><td>HF &gt; HCl &gt; HBr &gt; HI</td></tr><tr><td>Reducing power</td><td>HI &gt; HBr &gt; HCl &gt; HF</td></tr></tbody></table><p>Hydrogen bonding accounts for HF's high boiling temperature. HCl, the lowest-boiling member, is the most volatile in this set. HF is the weakest acid in ordinary dilute aqueous comparison because H-F is unusually strong; this does not mean HF is safe. Water levels the apparent strengths of the other strong acids, so the rank should not be converted directly into different pH values for equal dilute concentrations without a defined model.</p><p>The source prints 'ionic character: HF &gt; MCl &gt; MBr &gt; MI', mixing hydrogen and a generic metal symbol. <strong>Source correction:</strong> For the hydrogen-halide bond-polarity comparison, use HF &gt; HCl &gt; HBr &gt; HI. For a fixed-metal halide comparison the first formula would instead be MF. Bond polarity is not the same as the extent of ionization of an acid in water.</p><p>Concentrated sulfuric acid can release HCl from a chloride in the usual preparation, but it oxidizes HBr and HI more readily. Their greater reducing power makes the analogous route unsuitable for obtaining pure HBr or HI.</p>"
    },
    {
      id: "nitrogen-analysis-shortpoints",
      title: "Nitrogen and ammonia: qualitative-test points",
      sources: [{ document: "quick-revision", page: 99 }],
      html: "<ul><li>Ammonia gives a black product mixture with mercurous nitrate: Hg<sub>2</sub>(NO<sub>3</sub>)<sub>2</sub> + 2NH<sub>3</sub> &rarr; Hg + Hg(NH<sub>2</sub>)NO<sub>3</sub> + NH<sub>4</sub>NO<sub>3</sub>. Finely divided mercury contributes to the black appearance; the source brackets Hg and the amido nitrate together as a precipitate.</li><li>Nessler's reagent identifies ammonia or ammonium after conversion to ammonia in its alkaline medium. The source answer is NH<sub>4</sub><sup>+</sup>.</li><li>N<sub>2</sub> can be collected over water, described as downward displacement of water, because its solubility is low and it does not appreciably react with water under ordinary collection conditions.</li><li>AgI is practically insoluble in aqueous ammonia, traditionally called NH<sub>4</sub>OH, under the usual qualitative-test conditions.</li><li>NO<sub>2</sub> is a mixed acid anhydride of HNO<sub>2</sub> and HNO<sub>3</sub>: 2NO<sub>2</sub> + H<sub>2</sub>O &rarr; HNO<sub>2</sub> + HNO<sub>3</sub>.</li><li>The acidic nitrogen hydride printed as N<sub>3</sub>H is conventionally written HN<sub>3</sub>, hydrazoic acid; it is hazardous and is listed only for identification.</li><li>Nitroglycerine is identified as the energetic ingredient historically associated with dynamite. No preparation or use procedure is implied.</li></ul>"
    },
    {
      id: "nitrate-reduction-ammonia",
      title: "Nitrate reduction, ammonium salts and calcium cyanamide",
      sources: [{ document: "quick-revision", page: 99 }, { document: "quick-revision", page: 100 }],
      html: "<p>The source states that zinc reduces potassium nitrate in alkaline medium to ammonia. It gives a similar nitrate test using aluminium and NaOH, but prints NH<sub>2</sub> as the product.</p><p><strong>Source correction:</strong> The identified product is <strong>NH<sub>3</sub></strong>, not the neutral NH<sub>2</sub> radical. A balanced ionic representation of aluminium reduction in alkaline solution is 3NO<sub>3</sub><sup>&minus;</sup> + 8Al + 5OH<sup>&minus;</sup> + 18H<sub>2</sub>O &rarr; 3NH<sub>3</sub> + 8[Al(OH)<sub>4</sub>]<sup>&minus;</sup>.</p><ul><li>Calcium hydroxide and ammonium sulfate release ammonia: Ca(OH)<sub>2</sub> + (NH<sub>4</sub>)<sub>2</sub>SO<sub>4</sub> &rarr; CaSO<sub>4</sub> + 2NH<sub>3</sub> + 2H<sub>2</sub>O.</li><li>Calcium carbide reacts with nitrogen at elevated temperature to form calcium cyanamide: CaC<sub>2</sub> + N<sub>2</sub> &rarr; CaCN<sub>2</sub> + C.</li></ul><p>These are separate reactions: ammonia release from an ammonium salt is acid-base chemistry, whereas conversion of nitrate nitrogen from +5 to &minus;3 is reduction.</p>"
    },
    {
      id: "gas-removal-table",
      title: "Complete gas-removal and drying table",
      sources: [{ document: "quick-revision", page: 99 }, { document: "quick-revision", page: 100 }],
      html: "<p>The source labels all entries 'adsorbents'. The table is reproduced with the more general heading gas-removal agents because the mechanisms differ.</p><table><thead><tr><th>Gas or vapour</th><th>Listed agent</th></tr></thead><tbody><tr><td>O<sub>2</sub></td><td>Alkaline pyrogallol</td></tr><tr><td>O<sub>3</sub></td><td>Turpentine oil</td></tr><tr><td>N<sub>2</sub></td><td>Heated magnesium</td></tr><tr><td>NO</td><td>FeSO<sub>4</sub> solution</td></tr><tr><td>CO and C<sub>2</sub>H<sub>2</sub></td><td>Ammoniacal cuprous chloride, written Cu<sub>2</sub>Cl<sub>2</sub></td></tr><tr><td>PH<sub>3</sub></td><td>Acidified cuprous chloride, written Cu<sub>2</sub>Cl<sub>2</sub></td></tr><tr><td>CO<sub>2</sub>, SO<sub>2</sub>, NO<sub>2</sub></td><td>NaOH or KOH solution</td></tr><tr><td>Water vapour</td><td>Concentrated H<sub>2</sub>SO<sub>4</sub></td></tr><tr><td>Water</td><td>Anhydrous CuSO<sub>4</sub></td></tr><tr><td>NH<sub>3</sub>, from the separate source bullet</td><td>Concentrated H<sub>2</sub>SO<sub>4</sub></td></tr></tbody></table><p><strong>Source corrections:</strong> These are not all physical surface-adsorption processes. Nitrogen reacts to form Mg<sub>3</sub>N<sub>2</sub>; NO forms a complex with ferrous ions; acid gases undergo reactions with alkali; anhydrous copper sulfate is hydrated. Ammonia is absorbed and protonated by sulfuric acid, for example 2NH<sub>3</sub> + H<sub>2</sub>SO<sub>4</sub> &rarr; (NH<sub>4</sub>)<sub>2</sub>SO<sub>4</sub>, so the acid is not an inert drying agent for ammonia. Cu<sub>2</sub>Cl<sub>2</sub> is an older representation of copper(I) chloride, CuCl, not copper(II) chloride. Some listed combinations produce highly hazardous substances; the table is not an experimental procedure.</p>"
    },
    {
      id: "n2o5-bonding",
      title: "Phase-dependent bonding in N2O5",
      sources: [{ document: "quick-revision", page: 100 }],
      html: "<p>The source says N<sub>2</sub>O<sub>5</sub> contains covalent and dative bonds. This is a traditional Lewis-structure description for molecular forms, in which an oxygen bridges two nitrogen-containing groups.</p><p><strong>Source correction:</strong> The physical state must be specified. Molecular N<sub>2</sub>O<sub>5</sub> occurs in the gas phase, but the familiar crystalline solid is described as nitronium nitrate, [NO<sub>2</sub>]<sup>+</sup>[NO<sub>3</sub>]<sup>&minus;</sup>. It therefore has ionic interactions between polyatomic ions as well as covalent bonding within them. 'Covalent and dative' alone is not a complete statement about solid N<sub>2</sub>O<sub>5</sub>, and dative notation is a bonding model rather than a permanently distinct type of electron.</p>"
    },
    {
      id: "phosphorus-reactions-skin-correction",
      title: "Phosphorus reactions and the nitric-acid skin claim",
      sources: [{ document: "quick-revision", page: 99 }, { document: "quick-revision", page: 100 }],
      html: "<ul><li>Concentrated nitric acid oxidizes phosphorus to phosphoric acid, H<sub>3</sub>PO<sub>4</sub>. A formal equation per phosphorus atom is P + 5HNO<sub>3</sub> &rarr; H<sub>3</sub>PO<sub>4</sub> + 5NO<sub>2</sub> + H<sub>2</sub>O.</li><li>The source's element whose oxide and chloride both yield solutions with the same litmus effect is phosphorus. Its oxide and chlorides can hydrolyse to acidic products, so both turn blue litmus red. This observation alone is not a unique identification without a restricted set of candidates.</li><li>Metaphosphoric acid has empirical unit HPO<sub>3</sub>; common forms are cyclic or polymeric, represented as (HPO<sub>3</sub>)<sub>n</sub>.</li><li>White phosphorus reacts with aqueous alkali to give phosphine and hypophosphite: P<sub>4</sub> + 3NaOH + 3H<sub>2</sub>O &rarr; PH<sub>3</sub> + 3NaH<sub>2</sub>PO<sub>2</sub>. This is disproportionation, producing phosphorus at &minus;3 and +1 from elemental phosphorus.</li></ul><p><strong>Source correction and safety:</strong> The printed account of nitric acid turning a palm yellow must not be used as a test on skin. Nitric acid is corrosive. Yellowing can result from nitration of aromatic residues in proteins, associated with the xanthoproteic reaction; it does not establish that free NO<sub>2</sub> was originally present in the skin. The observation is explained as a chemical effect of exposure, not a demonstration to perform.</p>"
    },
    {
      id: "sulfur-oxygen-redox",
      title: "Sulfur dioxide, ozone, sulfuric acid and oleum",
      sources: [{ document: "quick-revision", page: 100 }],
      html: "<ul><li>SO<sub>2</sub> and H<sub>2</sub>S can form a sulfur precipitate: SO<sub>2</sub> + 2H<sub>2</sub>S &rarr; 3S + 2H<sub>2</sub>O. SO<sub>2</sub> is the oxidizing agent because its sulfur is reduced from +4 to 0.</li><li>In the source's reaction of SO<sub>2</sub> with metallic iron, iron is oxidized and SO<sub>2</sub> accepts electrons. Exact products require conditions not specified in that short bullet.</li><li>SO<sub>2</sub> can also be a reducing agent because sulfur(+4) can be oxidized further. For example, SO<sub>2</sub> + Br<sub>2</sub> + 2H<sub>2</sub>O &rarr; H<sub>2</sub>SO<sub>4</sub> + 2HBr.</li><li>Concentrated H<sub>2</sub>SO<sub>4</sub> is useful for liberating more volatile acids because it is relatively nonvolatile and high-boiling. Its oxidizing action limits which acids can be prepared this way.</li><li>Upper-atmosphere ozone forms following UV action on O<sub>2</sub>. Photodissociation supplies oxygen atoms, which combine with O<sub>2</sub> while a third body removes excess energy.</li><li>The source gives &alpha;-sulfur as a product of oxidation of H<sub>2</sub>S by HNO<sub>3</sub>. This is a conditional sulfur-forming outcome, not a guarantee under every oxidizing condition; further oxidation to sulfate can occur.</li><li>Strong heating decomposes mercury(II) oxide: 2HgO &rarr; 2Hg + O<sub>2</sub>. Mercury is reduced, but the overall process is thermal decomposition with simultaneous oxidation of oxide oxygen.</li></ul><p>The source separately equates <strong>oleum</strong> with pyrosulfuric acid, H<sub>2</sub>S<sub>2</sub>O<sub>7</sub>, and gives fuming sulfuric acid as H<sub>2</sub>SO<sub>4</sub> + SO<sub>3</sub>. <strong>Source correction:</strong> Oleum is a variable solution of SO<sub>3</sub> in sulfuric acid, not always pure H<sub>2</sub>S<sub>2</sub>O<sub>7</sub>. The disulfuric-acid composition is represented by H<sub>2</sub>SO<sub>4</sub> + SO<sub>3</sub> &rightleftharpoons; H<sub>2</sub>S<sub>2</sub>O<sub>7</sub>.</p>"
    },
    {
      id: "halogen-reaction-points",
      title: "Halogen reactions and applications",
      sources: [{ document: "quick-revision", page: 100 }],
      html: "<ul><li><strong>Hot concentrated alkali:</strong> 3Cl<sub>2</sub> + 6NaOH &rarr; NaClO<sub>3</sub> + 5NaCl + 3H<sub>2</sub>O. Chlorine disproportionates to chlorate and chloride. This differs from the usual cold dilute-alkali hypochlorite reaction.</li><li><strong>Bleaching:</strong> chlorine's conventional bleaching action needs moisture; reaction with water produces HOCl-containing solution. Oxidation of susceptible coloured substances, not merely exposure to dry gas, explains the source observation.</li><li><strong>Iodine to hydrogen iodide:</strong> H<sub>2</sub>S reduces iodine: I<sub>2</sub> + H<sub>2</sub>S &rarr; 2HI + S.</li><li><strong>Photography:</strong> the source's photographic paste or emulsion contains photosensitive AgBr, silver bromide.</li><li><strong>Iodide displacement:</strong> Cl<sub>2</sub> + 2KI &rarr; 2KCl + I<sub>2</sub>; iodide is oxidized to iodine.</li><li><strong>Bromide displacement:</strong> Cl<sub>2</sub> + 2KBr &rarr; 2KCl + Br<sub>2</sub>. The molecular oxidizing-power series is F<sub>2</sub> &gt; Cl<sub>2</sub> &gt; Br<sub>2</sub> &gt; I<sub>2</sub>; atomic electronegativity is a distinct property written F &gt; Cl &gt; Br &gt; I.</li><li><strong>MnO<sub>2</sub> and hydrochloric acid:</strong> MnO<sub>2</sub> + 4HCl &rarr; MnCl<sub>2</sub> + Cl<sub>2</sub> + 2H<sub>2</sub>O. MnO<sub>2</sub> is the oxidizing agent.</li><li><strong>Liquid non-metal:</strong> bromine is liquid at ordinary room temperature.</li><li><strong>Tincture of iodine:</strong> the source lists I<sub>2</sub>, KI and alcohol. Iodide can increase iodine solubility through I<sub>3</sub><sup>&minus;</sup> formation. This identifies ingredients, not a formulation recipe or wound-care recommendation.</li><li><strong>Insecticide manufacture:</strong> chlorine is a historical chemical feedstock for some chlorinated insecticides. This is not an endorsement of unrestricted use or a statement that all modern insecticides contain chlorine.</li><li><strong>Permanganate and hydrochloric acid:</strong> the source names this as a chlorine-forming reaction. The balanced equation is 2KMnO<sub>4</sub> + 16HCl &rarr; 2KCl + 2MnCl<sub>2</sub> + 8H<sub>2</sub>O + 5Cl<sub>2</sub>; the phrase 'small amount' is not an intrinsic stoichiometric property.</li></ul><p><strong>Source correction:</strong> 'Fluorine does not form oxyacids' is too absolute. It does not form the usual positive-oxidation-state halogen oxoacid series, but hypofluorous acid, HOF, is known and has fluorine at &minus;1. The source's weakest-hydrogen-halide-acid answer, HF, concerns aqueous acid strength, not safety. Chlorine-forming reactions are hazardous chemistry and are not instructions for mixing cleaning agents.</p>"
    },
    {
      id: "light-reaction-aqua-regia",
      title: "Light-sensitive halogen chemistry and aqua regia",
      sources: [{ document: "quick-revision", page: 101 }],
      html: "<p>The opening source bullet labels fluorine as the element that mixes with hydrogen in the dark but reacts explosively in light. <strong>Source correction:</strong> The familiar light-initiated comparison concerns <strong>chlorine</strong>, not fluorine. Fluorine reacts vigorously with hydrogen even without light. The source's word 'safely' is also inappropriate: neither hydrogen-halogen mixture is a safe classroom mixing rule.</p><p>Gold is not appreciably dissolved by hydrochloric acid alone, but can dissolve in aqua regia. The source attributes this to 'nascent chlorine'. <strong>Source clarification:</strong> Oxidation of gold and stabilization of dissolved gold by chloride complex formation work together; oxidizing species generated by the acid mixture contribute. Formation of a chloroaurate complex helps drive dissolution. 'Nascent chlorine' is historical shorthand, not a complete mechanistic explanation involving a special isolated kind of chlorine.</p>"
    },
    {
      id: "noble-gases",
      title: "Group 18: noble gases",
      sources: [{ document: "quick-revision", page: 101 }],
      html: "<p>The source lists He, Ne, Ar, Kr, Xe and Rn as monatomic noble gases. Their usual closed-shell valence configuration is ns<sup>2</sup>np<sup>6</sup>, with the important exception <strong>helium: 1s<sup>2</sup></strong>.</p><ul><li>Atomic size, conventionally compared using van der Waals radii, increases down the group.</li><li>Melting and boiling temperatures are low because the atoms interact mainly through weak dispersion forces. These forces increase as the atoms become more polarizable down the group.</li><li>Ionization enthalpy is high and generally decreases down the group.</li><li>Electron addition to an isolated closed-shell neutral atom is energetically unfavourable in the simple source comparison; the source calls electron-gain enthalpy positive.</li><li>The filled shell, difficult electron removal and unfavourable electron addition explain low reactivity.</li></ul><p><strong>Source correction:</strong> Low reactivity is not complete chemical inertness. The xenon compounds on this same page are counterexamples. The listed familiar elements and simple isolated-atom trends should not be extended without qualification to every possible compound or extreme condition.</p>"
    },
    {
      id: "xenon-shapes",
      title: "All four xenon compound shapes",
      sources: [{ document: "quick-revision", page: 101 }],
      html: "<table><thead><tr><th>Compound</th><th>Shape and source hybridization label</th></tr></thead><tbody><tr><td>XeF<sub>2</sub></td><td>Linear; source label sp<sup>3</sup>d. A VSEPR account has two bonding domains and three equatorial lone pairs.</td></tr><tr><td>XeF<sub>4</sub></td><td>Square planar; source label sp<sup>3</sup>d<sup>2</sup>. Four bonds and two opposite lone pairs derive from an octahedral domain arrangement.</td></tr><tr><td>XeF<sub>6</sub></td><td>Distorted octahedral; source label sp<sup>3</sup>d<sup>3</sup>. The six fluorine ligands and stereochemically active lone pair give a less simple, fluxional structure.</td></tr><tr><td>XeO<sub>3</sub></td><td>Trigonal pyramidal; source label sp<sup>3</sup>. Three oxygen-bonding domains and one lone pair surround xenon.</td></tr></tbody></table><p><strong>Source clarification:</strong> The expanded-shell hybridization labels are traditional shape mnemonics, not proof that xenon must promote electrons into strongly participating d orbitals. Modern descriptions of hypervalent bonding use molecular orbitals; molecular geometry and electron counting remain the reliable introductory study points.</p>"
    },
    {
      id: "xenon-reactions",
      title: "Xenon fluorides and partial hydrolysis",
      sources: [{ document: "quick-revision", page: 101 }],
      html: "<p>The source gives two partial-hydrolysis reactions:</p><ul><li>XeF<sub>6</sub> + H<sub>2</sub>O &rarr; XeOF<sub>4</sub> + 2HF.</li><li>XeF<sub>6</sub> + 2H<sub>2</sub>O &rarr; XeO<sub>2</sub>F<sub>2</sub> + 4HF.</li></ul><p>It also gives the direct fluorination equations and parenthetical reactant-feed ratios:</p><table><thead><tr><th>Balanced equation</th><th>Source Xe:F2 feed ratio</th></tr></thead><tbody><tr><td>Xe + F<sub>2</sub> &rarr; XeF<sub>2</sub></td><td>1:2</td></tr><tr><td>Xe + 2F<sub>2</sub> &rarr; XeF<sub>4</sub></td><td>1:5</td></tr><tr><td>Xe + 3F<sub>2</sub> &rarr; XeF<sub>6</sub></td><td>1:20</td></tr></tbody></table><p><strong>Source clarification:</strong> The parenthetical ratios describe mixtures containing excess fluorine, not the stoichiometric coefficients. The balanced consumption ratios are 1:1, 1:2 and 1:3. Product formation also depends on reaction conditions, so feed ratio alone is not a complete preparation method.</p>"
    },
    {
      id: "page-boundary-d-block-series",
      title: "Page 101 boundary: d-block definition and four series",
      sources: [{ document: "quick-revision", page: 101 }],
      html: "<p>The right column starts 'd and f block elements' and then discusses the d block. These elements occupy the region between the s and p blocks, with the differentiating electron commonly entering an (n &minus; 1)d orbital. The source's configuration range is (n &minus; 1)d<sup>1-10</sup>ns<sup>1-2</sup>.</p><table><thead><tr><th>Series</th><th>Source range</th></tr></thead><tbody><tr><td>First, 3d</td><td>Sc, atomic number 21, through Zn, 30.</td></tr><tr><td>Second, 4d</td><td>Y, 39, through Cd, 48.</td></tr><tr><td>Third, 5d</td><td>The source's conventional layout lists La, 57, then Hf, 72, through Hg, 80.</td></tr><tr><td>Fourth, 6d</td><td>The source lists Ac, then Rf, 104, through Cn, 112. Actinium's atomic number is 89.</td></tr></tbody></table><p><strong>Source corrections:</strong> The printed '80 Ac' is wrong; 80 is mercury and <strong>Ac is 89</strong>. Some ground-state configurations have ns<sup>0</sup>, notably palladium, so the ns<sup>1-2</sup> range is not exceptionless. A transition element strictly has an incomplete d subshell in its atom or a relevant cation; d-block membership is broader than that definition, so the usual Zn/Cd/Hg d<sup>10</sup> examples need qualification. The La/Ac series starts reflect the source's traditional group-3 layout rather than resolving all periodic-table placement conventions.</p>"
    },
    {
      id: "page-boundary-d-block-properties",
      title: "Page 101 boundary: all transition-metal property points",
      sources: [{ document: "quick-revision", page: 101 }],
      html: "<ul><li><strong>Atomic and ionic size:</strong> increasing nuclear charge and incomplete shielding by d electrons commonly produce a modest contraction across a series. The source also notes increasing size down a group and similar sizes for corresponding second- and third-series elements because of lanthanide contraction.</li><li><strong>Ionization enthalpy:</strong> the source describes it as relatively high and generally increasing left to right. The actual sequence is irregular and depends on electronic configuration. Cr and Cu have unusually high second ionization enthalpies because removal then disrupts the relatively stable Cr<sup>+</sup> d<sup>5</sup> and Cu<sup>+</sup> d<sup>10</sup> configurations.</li><li><strong>Melting and boiling temperatures:</strong> many are high because of strong metallic bonding involving available valence electrons. Electron participation and band structure matter, rather than a rule that each added valence electron always increases the melting point.</li><li><strong>Oxidation states:</strong> variable oxidation states are common. The source excepts the first and last members and calls +2 and +3 compounds mostly ionic; these are rough trends, not universal statements for every series or ligand.</li><li><strong>Magnetism:</strong> unpaired electrons give a paramagnetic contribution. The spin-only estimate is $\\mu_{\\mathrm{so}}=\\sqrt{n(n+2)}\\,\\mu_{\\mathrm{B}}$, where n is the number of unpaired electrons and &mu;<sub>B</sub> is the Bohr magneton.</li><li><strong>Colour:</strong> many ions with partly filled d orbitals are coloured in solids and aqueous solution. Splitting of d levels and electronic transitions can explain many of these colours.</li></ul><p><strong>Source corrections:</strong> Across-series radii and ionization energies are not strictly monotonic, and second-/third-series radii are similar rather than always exactly equal. Ionization enthalpy concerns removing an electron from an isolated gaseous species, not simply the strength of metallic bonding. Zn, Cd and especially Hg show why 'all have high melting points' is false. Not every transition-metal species is paramagnetic or coloured: paired-electron species can be diamagnetic, and d<sup>0</sup>/d<sup>10</sup> ions lack ordinary d-d transitions, although charge-transfer transitions can still give colour. The source's phrase 'unpaired elements' should read 'unpaired electrons'. The spin-only formula neglects orbital contributions and is not an exact universal magnetic moment.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 97, status: "transcribed", sectionIds: ["aluminium-minerals", "group14-trends", "group14-oxides-halides-water", "carbon-allotropes", "industrial-gas-mixtures", "borax-bead-glass", "group15-trends"], unresolved: [] },
    { document: "quick-revision", page: 98, status: "partial", sectionIds: ["group15-trends", "group15-trihalides", "nitrogen-oxide-table", "nitric-acid-preparation", "nitric-acid-metals", "brown-ring-test", "phosphorus-allotropes", "group16-trends"], unresolved: ["Top-left 'Lewis acid strength' line: PCl3 > AsCl3 > SbCl3 is legible, but no ligand, medium or comparison criterion is specified. Its intended acid/base property and unqualified ranking remain unresolved; it is reproduced as unverified and excluded from MCQs.", "Right column, black-phosphorus bullets: the alpha/beta phase labels lack identifying conditions. The intended phase behind 'alpha-black, monoclinic, can be sublimed in air' cannot be safely matched to a verified phase; ordinary layered orthorhombic black phosphorus and air-oxidation risk are distinguished explicitly."] },
    { document: "quick-revision", page: 99, status: "transcribed", sectionIds: ["group16-trends", "group16-hydrides", "oxide-classification", "sulfur-allotropes", "group17-elements", "hydrogen-halide-trends", "nitrogen-analysis-shortpoints", "nitrate-reduction-ammonia", "gas-removal-table", "phosphorus-reactions-skin-correction"], unresolved: [] },
    { document: "quick-revision", page: 100, status: "transcribed", sectionIds: ["phosphorus-allotropes", "oxide-classification", "sulfur-allotropes", "hydrogen-halide-trends", "nitrate-reduction-ammonia", "gas-removal-table", "n2o5-bonding", "phosphorus-reactions-skin-correction", "sulfur-oxygen-redox", "halogen-reaction-points"], unresolved: [] },
    { document: "quick-revision", page: 101, status: "transcribed", sectionIds: ["light-reaction-aqua-regia", "noble-gases", "xenon-shapes", "xenon-reactions", "page-boundary-d-block-series", "page-boundary-d-block-properties"], unresolved: [] }
  ],
  questions: [
    {
      id: "note-p-block-001", text: "Which listed aluminium-bearing material is the chief commercial ore rather than chiefly an electrolyte component?",
      options: [{ key: "a", text: "Cryolite" }, { key: "b", text: "Corundum" }, { key: "c", text: "Bauxite" }, { key: "d", text: "Potassium feldspar" }],
      answer: "c", explanation: "Bauxite is the chief aluminium ore in the source list. Cryolite is particularly important in the extraction electrolyte; merely containing aluminium does not give every mineral the same economic role.", sectionId: "aluminium-minerals", source: { document: "quick-revision", page: 97 }, cognitive: "recall"
    },
    {
      id: "note-p-block-002", text: "Which change is expected down the Ge-Sn-Pb series as the inert-pair effect becomes more important?",
      options: [{ key: "a", text: "The +2 state becomes more stable relative to +4." }, { key: "b", text: "The +4 state becomes the only possible oxidation state." }, { key: "c", text: "The valence ns pair participates progressively more readily." }, { key: "d", text: "Every member acquires the noble-gas valence configuration." }],
      answer: "a", explanation: "Reduced participation of the ns2 pair favours oxidation states two units below the maximum group valence. Thus the +2 state gains relative stability toward lead, while +4 becomes less favoured.", sectionId: "group14-trends", source: { document: "quick-revision", page: 97 }, cognitive: "understanding"
    },
    {
      id: "note-p-block-003", text: "Which bonding description explains why graphite can be both a robust layered solid and a lubricant?",
      options: [{ key: "a", text: "Weak bonds within sheets and stronger bonds between them" }, { key: "b", text: "Strong covalent bonds within sheets and weak attractions between them" }, { key: "c", text: "Only ionic bonds connecting isolated carbon ions in all directions" }, { key: "d", text: "No chemical bonds within or between any carbon-containing units" }],
      answer: "b", explanation: "Each graphite sheet is held by strong covalent carbon-carbon bonds. Weaker interlayer van der Waals attractions allow sheets to slide, which contributes to lubrication without making the in-plane network weak.", sectionId: "carbon-allotropes", source: { document: "quick-revision", page: 97 }, cognitive: "understanding"
    },
    {
      id: "note-p-block-004", text: "Which gas name denotes an oxygen-carbon dioxide mixture rather than a CO-containing fuel-gas mixture?",
      options: [{ key: "a", text: "Water gas" }, { key: "b", text: "Producer gas" }, { key: "c", text: "Coal gas" }, { key: "d", text: "Carbogen" }],
      answer: "d", explanation: "Carbogen contains O2 and CO2. Water gas, producer gas and coal gas are different mixtures that contain carbon monoxide in the source table; the names are not interchangeable.", sectionId: "industrial-gas-mixtures", source: { document: "quick-revision", page: 97 }, cognitive: "recall"
    },
    {
      id: "note-p-block-005", text: "Which correction best characterizes ordinary natural gas?",
      options: [{ key: "a", text: "Its defining major components are always equal CO and H2." }, { key: "b", text: "It is principally methane with variable other constituents." }, { key: "c", text: "It contains only oxygen and carbon dioxide in a fixed ratio." }, { key: "d", text: "It is a pure nitrogen compound with no hydrocarbons." }],
      answer: "b", explanation: "Natural gas is principally methane and can contain other hydrocarbons and impurities. The source's inclusion of CO and H2 must not be read as defining major components of ordinary natural gas.", sectionId: "industrial-gas-mixtures", source: { document: "quick-revision", page: 97 }, cognitive: "understanding"
    },
    {
      id: "note-p-block-006", text: "Which description is preferable to calling ordinary window glass a slowly flowing liquid at room temperature?",
      options: [{ key: "a", text: "A gas of freely moving silicate molecules" }, { key: "b", text: "A perfect crystal of only silicon atoms" }, { key: "c", text: "An amorphous solid with glassy structure" }, { key: "d", text: "A suspension made solely of liquid lead" }],
      answer: "c", explanation: "Glass is an amorphous solid at room temperature. Its lack of long-range crystalline order does not mean that it flows like an ordinary liquid under everyday conditions.", sectionId: "borax-bead-glass", source: { document: "quick-revision", page: 97 }, cognitive: "understanding"
    },
    {
      id: "note-p-block-007", text: "Which listed nitrogen oxide is a brown gas with nitrogen in oxidation state +4?",
      options: [{ key: "a", text: "NO<sub>2</sub>" }, { key: "b", text: "NO" }, { key: "c", text: "N<sub>2</sub>O" }, { key: "d", text: "N<sub>2</sub>O<sub>5</sub>" }],
      answer: "a", explanation: "In NO2, two oxide oxygens contribute -4, so nitrogen is +4. NO2 is brown, unlike the colourless NO and N2O gases and the colourless N2O5 solid listed in the table.", sectionId: "nitrogen-oxide-table", source: { document: "quick-revision", page: 98 }, cognitive: "recall"
    },
    {
      id: "note-p-block-008", text: "The equation 2Pb(NO<sub>3</sub>)<sub>2</sub> &rarr; 2PbO + 4NO<sub>2</sub> + O<sub>2</sub> is complete. What theoretical amount of O<sub>2</sub> corresponds to 0.50 mol of the nitrate?",
      options: [{ key: "a", text: "0.50 mol" }, { key: "b", text: "1.00 mol" }, { key: "c", text: "2.00 mol" }, { key: "d", text: "0.25 mol" }],
      answer: "d", explanation: "The stoichiometric ratio is two moles of lead nitrate to one mole of oxygen. Therefore 0.50 divided by 2 gives 0.25 mol O2. This is a theoretical balance, not a heating procedure.", sectionId: "nitrogen-oxide-table", source: { document: "quick-revision", page: 98 }, cognitive: "application"
    },
    {
      id: "note-p-block-009", text: "In the nitrate-to-NO step of the brown-ring test, how many Fe<sup>2+</sup> ions supply electrons per nitrate ion reduced?",
      options: [{ key: "a", text: "Three" }, { key: "b", text: "One" }, { key: "c", text: "Two" }, { key: "d", text: "Four" }],
      answer: "a", explanation: "Nitrogen changes from +5 in nitrate to +2 in NO, gaining three electrons. Each Fe2+ supplies one electron when it becomes Fe3+, so three ferrous ions are required per nitrate ion.", sectionId: "brown-ring-test", source: { document: "quick-revision", page: 98 }, cognitive: "application"
    },
    {
      id: "note-p-block-010", text: "Why must iron be qualified in a table predicting NO<sub>2</sub> from every metal with concentrated nitric acid?",
      options: [{ key: "a", text: "Iron is a noble gas with no metallic surface." }, { key: "b", text: "Nitric acid is never an oxidizing acid." }, { key: "c", text: "Iron cannot form any nitrate under any conditions." }, { key: "d", text: "Cold concentrated nitric acid can passivate iron." }],
      answer: "d", explanation: "A protective surface layer can passivate iron in cold concentrated nitric acid. The source's generalized reacting-metal row therefore cannot be applied without accounting for surface state and temperature.", sectionId: "nitric-acid-metals", source: { document: "quick-revision", page: 98 }, cognitive: "understanding"
    },
    {
      id: "note-p-block-011", text: "In the usual dilute-nitric-acid reaction with copper, which nitrogen oxide appears in the balanced equation?",
      options: [{ key: "a", text: "N<sub>2</sub>O<sub>5</sub>" }, { key: "b", text: "NO" }, { key: "c", text: "N<sub>2</sub>O<sub>3</sub>" }, { key: "d", text: "NO<sub>2</sub>" }],
      answer: "b", explanation: "The usual dilute comparison is 3Cu + 8HNO3 -> 3Cu(NO3)2 + 2NO + 4H2O. Concentrated acid commonly gives NO2 instead; sodium metal cannot be the product printed as 'Na' in that table cell.", sectionId: "nitric-acid-metals", source: { document: "quick-revision", page: 98 }, cognitive: "recall"
    },
    {
      id: "note-p-block-012", text: "What is the more precise description of the glow associated with slow oxidation of white phosphorus?",
      options: [{ key: "a", text: "Electrical conduction through a metal filament" }, { key: "b", text: "Light stored indefinitely without chemical change" }, { key: "c", text: "Chemiluminescence from an oxidation process" }, { key: "d", text: "Fluorescence caused only by an external UV lamp" }],
      answer: "c", explanation: "White phosphorus glows as a consequence of chemical oxidation, so chemiluminescence is the appropriate term. The source's phosphorescence wording should not be confused with delayed emission following light absorption.", sectionId: "phosphorus-allotropes", source: { document: "quick-revision", page: 98 }, cognitive: "understanding"
    },
    {
      id: "note-p-block-013", text: "What coefficient of H<sub>2</sub>SO<sub>4</sub> balances NaNO<sub>3</sub> + H<sub>2</sub>SO<sub>4</sub> &rarr; NaHSO<sub>4</sub> + HNO<sub>3</sub> when each other coefficient is one?",
      options: [{ key: "a", text: "5" }, { key: "b", text: "2" }, { key: "c", text: "1" }, { key: "d", text: "3" }],
      answer: "c", explanation: "One sulfur atom and two hydrogen atoms are needed on the reactant side to match NaHSO4 plus HNO3. A coefficient of one balances all atoms; the source's coefficient five does not.", sectionId: "nitric-acid-preparation", source: { document: "quick-revision", page: 98 }, cognitive: "application"
    },
    {
      id: "note-p-block-014", text: "Why does water boil at a higher temperature than H<sub>2</sub>S, H<sub>2</sub>Se and H<sub>2</sub>Te despite its smaller molecular mass?",
      options: [{ key: "a", text: "Water has no intermolecular forces." }, { key: "b", text: "Water forms extensive intermolecular hydrogen bonds." }, { key: "c", text: "Water contains the largest atom in the group." }, { key: "d", text: "Water is an ionic salt of free oxygen ions." }],
      answer: "b", explanation: "Hydrogen bonding between water molecules raises its boiling temperature substantially. The heavier hydrides mainly follow increasing dispersion forces, so molecular mass alone fails to predict water's position.", sectionId: "group16-hydrides", source: { document: "quick-revision", page: 99 }, cognitive: "understanding"
    },
    {
      id: "note-p-block-015", text: "Which hydride has the greatest reducing power in the stated group-16 comparison?",
      options: [{ key: "a", text: "H<sub>2</sub>O" }, { key: "b", text: "H<sub>2</sub>S" }, { key: "c", text: "H<sub>2</sub>Se" }, { key: "d", text: "H<sub>2</sub>Te" }],
      answer: "d", explanation: "The source order is H2Te > H2Se > H2S > H2O. The weakening of element-hydrogen bonds down the heavier series accompanies lower thermal stability and increasing reducing ability.", sectionId: "group16-hydrides", source: { document: "quick-revision", page: 99 }, cognitive: "recall"
    },
    {
      id: "note-p-block-016", text: "Which formal combination reproduces the composition of magnetite, Fe<sub>3</sub>O<sub>4</sub>?",
      options: [{ key: "a", text: "FeO&middot;Fe<sub>2</sub>O<sub>3</sub>" }, { key: "b", text: "2FeO&middot;Fe<sub>2</sub>O<sub>3</sub>" }, { key: "c", text: "FeO&middot;2Fe<sub>2</sub>O<sub>3</sub>" }, { key: "d", text: "3FeO&middot;Fe<sub>2</sub>O<sub>3</sub>" }],
      answer: "a", explanation: "FeO contributes one iron and one oxygen, while Fe2O3 contributes two irons and three oxygens. Their total is Fe3O4, illustrating a mixed oxide containing iron in more than one oxidation state.", sectionId: "oxide-classification", source: { document: "quick-revision", page: 99 }, cognitive: "application"
    },
    {
      id: "note-p-block-017", text: "Which hydrogen halide has the largest H-X bond dissociation energy in the source comparison?",
      options: [{ key: "a", text: "HCl" }, { key: "b", text: "HF" }, { key: "c", text: "HI" }, { key: "d", text: "HBr" }],
      answer: "b", explanation: "HF has the shortest and strongest H-X bond in this set. The stated bond-dissociation order is HF > HCl > HBr > HI, opposite to the simple bond-length order.", sectionId: "hydrogen-halide-trends", source: { document: "quick-revision", page: 99 }, cognitive: "recall"
    },
    {
      id: "note-p-block-018", text: "Why does the high polarity of the H-F bond not make HF the strongest aqueous acid in the listed series?",
      options: [{ key: "a", text: "Bond breaking and solvation matter as well as bond polarity." }, { key: "b", text: "Fluorine is the least electronegative halogen." }, { key: "c", text: "Every polar bond dissociates completely in water." }, { key: "d", text: "Hydrogen fluoride contains no hydrogen atom." }],
      answer: "a", explanation: "Acid ionization is an overall equilibrium, not a direct reading of bond polarity alone. The unusually strong H-F bond contributes to HF being weak in ordinary dilute water despite its strongly polar bond.", sectionId: "hydrogen-halide-trends", source: { document: "quick-revision", page: 99 }, cognitive: "understanding"
    },
    {
      id: "note-p-block-019", text: "Nitrogen removal by heated magnesium is best classified as which process?",
      options: [{ key: "a", text: "Only reversible water condensation" }, { key: "b", text: "Only physical adsorption on unchanged magnesium" }, { key: "c", text: "Chemical reaction forming magnesium nitride" }, { key: "d", text: "Conversion of nitrogen directly into oxygen" }],
      answer: "c", explanation: "Magnesium reacts with nitrogen to form Mg3N2, so the process chemically consumes the gas. The source's blanket 'adsorbent' heading does not correctly describe the mechanism of every row.", sectionId: "gas-removal-table", source: { document: "quick-revision", page: 99 }, cognitive: "understanding"
    },
    {
      id: "note-p-block-020", text: "In SO<sub>2</sub> + 2H<sub>2</sub>S &rarr; 3S + 2H<sub>2</sub>O, what role does SO<sub>2</sub> play?",
      options: [{ key: "a", text: "A catalyst whose sulfur oxidation state is unchanged" }, { key: "b", text: "A reducing agent whose sulfur changes from +4 to +6" }, { key: "c", text: "An inert solvent that takes no part in electron transfer" }, { key: "d", text: "An oxidizing agent whose sulfur changes from +4 to 0" }],
      answer: "d", explanation: "Sulfur in SO2 gains four electrons overall as it changes from +4 to 0. SO2 is therefore reduced and acts as the oxidizing agent, while sulfur in H2S is oxidized from -2 to 0.", sectionId: "sulfur-oxygen-redox", source: { document: "quick-revision", page: 100 }, cognitive: "application"
    },
    {
      id: "note-p-block-021", text: "In the hot concentrated-NaOH reaction of chlorine, what is the molar ratio of chloride to chlorate produced?",
      options: [{ key: "a", text: "5:1" }, { key: "b", text: "1:5" }, { key: "c", text: "1:1" }, { key: "d", text: "3:2" }],
      answer: "a", explanation: "The balanced equation is 3Cl2 + 6NaOH -> 5NaCl + NaClO3 + 3H2O. Five chlorine atoms are reduced to chloride while one is oxidized to chlorate, giving a 5:1 product ratio.", sectionId: "halogen-reaction-points", source: { document: "quick-revision", page: 100 }, cognitive: "application"
    },
    {
      id: "note-p-block-022", text: "Which nitrogen-containing product correctly replaces the printed NH<sub>2</sub> in alkaline aluminium reduction of nitrate?",
      options: [{ key: "a", text: "NO<sub>2</sub>" }, { key: "b", text: "N<sub>2</sub>O<sub>5</sub>" }, { key: "c", text: "NH<sub>3</sub>" }, { key: "d", text: "HNO<sub>3</sub>" }],
      answer: "c", explanation: "Aluminium in alkaline medium can reduce nitrate to ammonia, NH3, with nitrogen at -3. The source's NH2 formula is not the neutral ammonia product and would incorrectly denote a different species.", sectionId: "nitrate-reduction-ammonia", source: { document: "quick-revision", page: 100 }, cognitive: "recall"
    },
    {
      id: "note-p-block-023", text: "Which representation best describes the familiar crystalline solid form of N<sub>2</sub>O<sub>5</sub>?",
      options: [{ key: "a", text: "[NH<sub>4</sub>]<sup>+</sup>[NO<sub>3</sub>]<sup>&minus;</sup>" }, { key: "b", text: "[NO]<sup>+</sup>[NO<sub>2</sub>]<sup>&minus;</sup>" }, { key: "c", text: "[N<sub>2</sub>]<sup>+</sup>[O<sub>5</sub>]<sup>&minus;</sup>" }, { key: "d", text: "[NO<sub>2</sub>]<sup>+</sup>[NO<sub>3</sub>]<sup>&minus;</sup>" }],
      answer: "d", explanation: "Solid N2O5 is nitronium nitrate, containing NO2+ and NO3- ions. Their atoms total N2O5 and their charges balance; the gaseous molecular form requires a different structural description.", sectionId: "n2o5-bonding", source: { document: "quick-revision", page: 100 }, cognitive: "understanding"
    },
    {
      id: "note-p-block-024", text: "When chlorine oxidizes iodide in aqueous KI, which change occurs to iodine?",
      options: [{ key: "a", text: "Iodine changes from 0 to -1." }, { key: "b", text: "Iodine changes from -1 to 0." }, { key: "c", text: "Iodine remains at +5 throughout." }, { key: "d", text: "Iodine is converted into chlorine atoms." }],
      answer: "b", explanation: "The reaction Cl2 + 2I- -> 2Cl- + I2 oxidizes iodide from -1 to elemental iodine at 0. Chlorine gains the electrons and is reduced from 0 to -1.", sectionId: "halogen-reaction-points", source: { document: "quick-revision", page: 100 }, cognitive: "application"
    },
    {
      id: "note-p-block-025", text: "Which compound requires qualification of the absolute claim that fluorine forms no oxygen-containing acid?",
      options: [{ key: "a", text: "HCl" }, { key: "b", text: "NaF" }, { key: "c", text: "CaF<sub>2</sub>" }, { key: "d", text: "HOF" }],
      answer: "d", explanation: "Hypofluorous acid, HOF, is known and contains fluorine at -1. Fluorine lacks the usual positive-oxidation-state halogen oxoacid series, but that narrower statement is not the same as denying HOF's existence.", sectionId: "halogen-reaction-points", source: { document: "quick-revision", page: 100 }, cognitive: "understanding"
    },
    {
      id: "note-p-block-026", text: "Which halogen belongs in the familiar light-initiated reaction with hydrogen that the source incorrectly assigns to fluorine?",
      options: [{ key: "a", text: "Chlorine" }, { key: "b", text: "Iodine" }, { key: "c", text: "Astatine" }, { key: "d", text: "Bromine" }],
      answer: "a", explanation: "The conventional light-initiation example is the hydrogen-chlorine reaction. Fluorine reacts vigorously with hydrogen without requiring light; neither mixture should be described as safe to prepare.", sectionId: "light-reaction-aqua-regia", source: { document: "quick-revision", page: 101 }, cognitive: "recall"
    },
    {
      id: "note-p-block-027", text: "Which lone-pair arrangement explains the square-planar shape of XeF<sub>4</sub> in the elementary VSEPR model?",
      options: [{ key: "a", text: "Three lone pairs in equatorial positions" }, { key: "b", text: "Two lone pairs at opposite octahedral positions" }, { key: "c", text: "One lone pair in a tetrahedral arrangement" }, { key: "d", text: "No lone pairs around the xenon atom" }],
      answer: "b", explanation: "XeF4 has four bonding domains and two lone pairs. Placing the lone pairs opposite one another within an octahedral domain arrangement leaves the four fluorines in one square plane.", sectionId: "xenon-shapes", source: { document: "quick-revision", page: 101 }, cognitive: "understanding"
    },
    {
      id: "note-p-block-028", text: "Which xenon product accompanies 4HF in the stated partial hydrolysis XeF<sub>6</sub> + 2H<sub>2</sub>O?",
      options: [{ key: "a", text: "XeF<sub>4</sub>" }, { key: "b", text: "XeOF<sub>4</sub>" }, { key: "c", text: "XeO<sub>2</sub>F<sub>2</sub>" }, { key: "d", text: "XeO<sub>3</sub>" }],
      answer: "c", explanation: "Two water molecules supply two oxygen atoms and four hydrogens. Four fluorines leave as 4HF, leaving XeO2F2; the resulting equation balances Xe, F, O and H separately.", sectionId: "xenon-reactions", source: { document: "quick-revision", page: 101 }, cognitive: "application"
    },
    {
      id: "note-p-block-029", text: "Which listed noble gas is the exception to the ns<sup>2</sup>np<sup>6</sup> valence-shell pattern?",
      options: [{ key: "a", text: "Helium" }, { key: "b", text: "Neon" }, { key: "c", text: "Argon" }, { key: "d", text: "Xenon" }],
      answer: "a", explanation: "Helium has the configuration 1s2 and a complete first shell without any occupied p subshell. Neon, argon and xenon have the usual filled s and p valence pattern stated for the later noble gases.", sectionId: "noble-gases", source: { document: "quick-revision", page: 101 }, cognitive: "recall"
    },
    {
      id: "note-p-block-030", text: "A metal ion has three unpaired electrons. What is its spin-only magnetic moment using the source formula?",
      options: [{ key: "a", text: "1.73 Bohr magnetons" }, { key: "b", text: "3.87 Bohr magnetons" }, { key: "c", text: "2.83 Bohr magnetons" }, { key: "d", text: "4.90 Bohr magnetons" }],
      answer: "b", explanation: "With n = 3, the spin-only expression gives $\\sqrt{3(3+2)}=\\sqrt{15}\\approx3.87$ Bohr magnetons. This estimate assumes orbital contributions can be neglected; it is not an exact value for every ion.", sectionId: "page-boundary-d-block-properties", source: { document: "quick-revision", page: 101 }, cognitive: "application"
    }
  ]
};