window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["photosynthesis"] = {
  id: "photosynthesis",
  subject: "Botany",
  title: "Photosynthesis",
  sections: [
    {
      id: "nature-and-overall-reaction",
      title: "Nature, requirements and overall redox reaction",
      sources: [{ document: "biology", page: 289 }],
      html: "<p>Photosynthesis is a physicochemical, enzyme-mediated, anabolic and endergonic process. Absorption of sunlight is the physical energy-input event; subsequent photochemical and biochemical reactions convert that energy into chemical forms and assimilate inorganic carbon. The source's endogonic spelling is read as endergonic, meaning that the overall synthesis requires an energy supply.</p>" +
        "<p>For oxygenic photosynthesis, the source writes the uncancelled overall equation: 6CO<sub>2</sub> + 12H<sub>2</sub>O &rarr; C<sub>6</sub>H<sub>12</sub>O<sub>6</sub> + 6H<sub>2</sub>O + 6O<sub>2</sub>, with light and photosynthetic pigments required. Cancelling six waters gives the familiar net equation. This is an overall balance, not one enzyme reaction or proof that free glucose is the first product.</p>" +
        "<ul><li>The oxidation bracket in the drawing connects water with released oxygen. Water supplies the electrons for oxygenic photosynthetic electron flow.</li><li>The reduction bracket connects carbon dioxide with carbohydrate. Carbon is reduced during assimilation.</li><li>Consequently, photosynthesis is a redox process, involving both oxidation and reduction. The source's preference for reduction alone describes the fate of carbon, not the entire reaction.</li><li>The required inputs are light energy, carbon dioxide, water and photosynthetic pigments. In a terrestrial plant, roots supply water; atmospheric CO<sub>2</sub> and internally released respiratory CO<sub>2</sub> can supply carbon.</li><li>Carbon assimilation uses ATP and reduced NADP supplied by the light reactions. NADPH carries reducing equivalents; it is not simply a container transporting all free protons from water to sugar.</li></ul>" +
        "<p><strong>Source correction:</strong> the statement that 90% of photosynthesis is performed by oceanic BGA is not a reliable global estimate. Cyanobacteria, traditionally called blue-green algae or BGA, were important early oxygenic phototrophs, but marine photosynthesis also includes many eukaryotic algae and does not justify that percentage. Anoxygenic photosynthesis also exists; first true photosynthesis should not imply that it is unreal.</p>"
    },
    {
      id: "photosynthetic-sites-and-membranes",
      title: "Photosynthetic sites and the thylakoid hierarchy",
      sources: [{ document: "biology", page: 289 }, { document: "biology", page: 290 }, { document: "biology", page: 291 }],
      html: "<p>The source's anatomical sequence is leaf &rarr; mesophyll cell &rarr; chloroplast &rarr; thylakoid &rarr; thylakoid membrane &rarr; pigment-protein complexes. A thylakoid is a membrane-bound sac. Stacked thylakoids form a granum; grana is plural. Grana are connected by stroma lamellae, also called intergranal thylakoids. The fluid outside the thylakoids but inside the chloroplast envelope is the stroma; the enclosed thylakoid space is the lumen.</p>" +
        "<table><thead><tr><th>Process</th><th>Location and exchange</th></tr></thead><tbody><tr><td>Light reactions</td><td>Thylakoid membranes; light energy drives electron transport, water oxidation and formation of ATP and NADPH.</td></tr><tr><td>Calvin cycle</td><td>Chloroplast stroma; CO<sub>2</sub> is assimilated using ATP and NADPH, returning ADP, phosphate and NADP<sup>+</sup>.</td></tr><tr><td>Prokaryotic photosynthesis</td><td>Photosynthetic membrane systems described in the source as chromatophores, lamellae or cytoplasmic thylakoids; their organization varies among groups.</td></tr></tbody></table>" +
        "<p><strong>Source corrections:</strong> prokaryotes do not possess chloroplasts, but they are not restricted to light reactions. Photosynthetic carbon assimilation also occurs in appropriate prokaryotes. Grana alone is an incomplete location for light reactions because unstacked thylakoids participate too. Dark reaction means that a photon is not directly consumed by each carbon-fixation step; it does not mean obligatory night-time operation or independence from light-generated ATP, NADPH and enzyme regulation.</p>"
    },
    {
      id: "discovery-and-tracer-evidence",
      title: "Historical experiments and isotope evidence",
      sources: [{ document: "quick-revision", page: 131 }, { document: "quick-revision", page: 132 }, { document: "quick-revision", page: 133 }, { document: "biology", page: 292 }],
      html: "<table><thead><tr><th>Investigator</th><th>Source association and interpretation</th></tr></thead><tbody><tr><td>Ruben and Kamen</td><td>Isotope evidence that evolved O<sub>2</sub> comes from water; Chlorella is the alga named in the printed notes. Oxygen-labelled water, rather than merely carbon-labelled CO<sub>2</sub>, addresses oxygen's origin.</td></tr><tr><td>Ingenhousz</td><td>The role of light and green plant parts in the oxygen-releasing process.</td></tr><tr><td>de Saussure</td><td>The source associates him with CO<sub>2</sub> use. More precisely, his quantitative work established contributions of both carbon dioxide and water to plant growth; this is not sole credit for discovering all CO<sub>2</sub> uptake.</td></tr><tr><td>Blackman</td><td>Evidence distinguishing light-dependent and temperature-sensitive biochemical limitations, and the limiting-factor principle. The source's two steps wording refers to these broad phases.</td></tr><tr><td>Arnon</td><td>Photophosphorylation: light-driven formation of ATP in chloroplast preparations.</td></tr><tr><td>Calvin and coworkers</td><td>Tracing carbon fixation with radioactive <sup>14</sup>C supplied as CO<sub>2</sub>, using Chlorella, separation of products and autoradiography.</td></tr></tbody></table>" +
        "<p>The two tracer questions are different: labelled oxygen tests the source of evolved oxygen, while <sup>14</sup>C follows carbon into compounds such as 3-phosphoglycerate. Autoradiography reveals the radioactive products after separation; it is not the biochemical pathway itself.</p><p>The printed <strong>Gibbs effect</strong> entry, written as asymmetrical leveling of glucose, refers to asymmetrical isotopic labelling of newly formed sugar in carbon-tracer experiments. It does not describe unequal glucose concentrations on the two sides of a leaf, and its placement under C<sub>4</sub> does not make it a defining C<sub>4</sub> reaction.</p>"
    },
    {
      id: "pigment-families-and-colours",
      title: "Pigment families, colours and solubility",
      sources: [{ document: "biology", page: 290 }, { document: "quick-revision", page: 131 }, { document: "quick-revision", page: 132 }, { document: "quick-revision", page: 133 }],
      html: "<p>The pigment tree separates principal pigments, chlorophyll a and bacteriochlorophyll in their respective phototrophs, from accessory pigments. The accessory branches name chlorophyll b, c and d; carotenoids comprising carotenes and xanthophylls; and phycobilins comprising phycoerythrin and phycocyanin. Pigments absorb different wavelength bands and thereby broaden usable light capture.</p>" +
        "<ul><li>Chlorophyll a is the principal blue-green pigment of most oxygenic photosynthetic systems. Chlorophyll b is yellow-green, described as greenish yellow on the page.</li><li>Carotenes are commonly orange and xanthophylls commonly yellow. Xanthophylls are oxygen-containing carotenoids; carotenes are hydrocarbons.</li><li>Carotenoids act as antenna pigments and as shield pigments, protecting chlorophyll and the photosynthetic apparatus from photooxidative damage.</li><li>Phycoerythrin and phycocyanin occur as light-harvesting phycobiliproteins. These complexes are water-soluble, unlike the lipid-soluble chlorophylls and carotenoids.</li><li>Paper chromatography can separate leaf pigments. Chlorosis means loss or deficient formation of chlorophyll, producing abnormal yellowing; it is a symptom rather than one specific nutrient diagnosis.</li><li>Rhodospirillum is the printed example of a purple nonsulfur photosynthetic bacterium. Its bacteriochlorophyll-based photosynthesis is anoxygenic.</li><li>Anthocyanins are the source's vegetable chameleon pigments, reflecting pH-dependent colour changes. They are vacuolar pigments, not reaction-centre chlorophylls.</li></ul>" +
        "<p><strong>Source corrections:</strong> all pigments are fat soluble conflicts with the page's own water-soluble phycobilin branch. Chlorophyll a is not literally universal in every type of phototroph; anoxygenic bacteria use bacteriochlorophylls, and specialized oxygenic systems can use other chlorophylls in reaction centres. Anthocyanin colour does not prove that chlorophyll is absent from the same leaf. Phycocyanin transfers absorbed excitation energy in cyanobacteria; it does not itself split water. Water oxidation is catalysed by the oxygen-evolving complex of photosystem II.</p>"
    },
    {
      id: "pigment-formulas-and-chlorophyll-structure",
      title: "Pigment formulas and chlorophyll structure",
      sources: [{ document: "biology", page: 290 }, { document: "quick-revision", page: 131 }, { document: "quick-revision", page: 132 }],
      html: "<table><thead><tr><th>Pigment</th><th>Formula and qualification</th></tr></thead><tbody><tr><td>Chlorophyll a</td><td>C<sub>55</sub>H<sub>72</sub>MgN<sub>4</sub>O<sub>5</sub>; methyl, &ndash;CH<sub>3</sub>, at the substituent position compared with b.</td></tr><tr><td>Chlorophyll b</td><td>C<sub>55</sub>H<sub>70</sub>MgN<sub>4</sub>O<sub>6</sub>; formyl, &ndash;CHO, at the corresponding position.</td></tr><tr><td>Chlorophyll c</td><td>The written C<sub>35</sub>H<sub>28</sub>MgN<sub>4</sub>O<sub>5</sub> identifies chlorophyll c<sub>2</sub>, not every member of the c family.</td></tr><tr><td>Chlorophyll d</td><td>C<sub>54</sub>H<sub>70</sub>MgN<sub>4</sub>O<sub>6</sub>.</td></tr><tr><td>Bacteriochlorophyll</td><td>The written C<sub>55</sub>H<sub>74</sub>MgN<sub>4</sub>O<sub>6</sub> is the common phytylated bacteriochlorophyll a formula, not a formula for every bacterial pigment.</td></tr><tr><td>Carotene</td><td>Beta-carotene is C<sub>40</sub>H<sub>56</sub>. The page incorrectly adds O<sub>2</sub>.</td></tr><tr><td>Xanthophyll</td><td>C<sub>40</sub>H<sub>56</sub>O<sub>2</sub> fits examples such as lutein and zeaxanthin, not every xanthophyll.</td></tr></tbody></table>" +
        "<p>The chlorophyll drawing resembles a head with a long tail. The head is a conjugated tetrapyrrole, more precisely a chlorin-type ring in chlorophyll a, with a central Mg ion coordinated by four nitrogen atoms. The hydrocarbon phytol tail is attached through an ester linkage and helps anchor the molecule in the membrane environment. The source calls the head hydrophilic and the tail lipophilic: the head is relatively polar, but the whole chlorophyll molecule remains poorly water-soluble.</p>" +
        "<p>The methyl/formyl comparison is annotated as the third carbon of pyrrole ring II in the source's older numbering; it corresponds to the commonly designated C7 substituent. Chlorophyll c lacks the usual long phytol tail, so the tadpole-shaped model should not be applied unchanged to all chlorophyll families. The presence of magnesium in chlorophyll must not be confused with manganese in the water-oxidizing complex.</p>"
    },
    {
      id: "photosystems-antennae-and-quantasomes",
      title: "Photosystems, antenna transfer and the quantasome model",
      sources: [{ document: "biology", page: 290 }, { document: "quick-revision", page: 131 }, { document: "quick-revision", page: 132 }, { document: "quick-revision", page: 133 }, { document: "biology", page: 294 }],
      html: "<p>A photosystem is an organized pigment-protein complex with light-harvesting antennae and a reaction centre. Photosystem I is associated with P700 and photosystem II with P680, named for characteristic reaction-centre absorption near 700 and 680 nm. The printed memory cues link I with the similar-looking 1 and 7 in 700, and A with 1 to remember the greater chlorophyll a emphasis in PSI antenna comparisons.</p>" +
        "<p><strong>Source corrections:</strong> both ordinary higher-plant reaction centres contain specialized chlorophyll a, not chlorophyll b as the PSII reaction-centre pigment. A relatively greater proportion of chlorophyll b in a PSII antenna is not the same claim. P680 and P700 do not mean that every pigment in the corresponding photosystem stops absorbing at an exact wavelength boundary.</p>" +
        "<p>Excitation energy can pass between antenna pigments by resonance energy transfer until it reaches a reaction centre. <strong>Source correction:</strong> the printed electron transfer between chlorophyll through resonance should say excitation-energy transfer; net electron transfer begins with reaction-centre charge separation. Excess excitation can be released as fluorescence, that is, emitted light, or dissipated by other processes such as heat.</p>" +
        "<p>The historical <strong>quantasome</strong> account is attributed to Park and Biggins and called a functional unit of the chloroplast. Its listed composition is 230 chlorophyll molecules, divided into 160 a and 70 b, plus 50 carotenoids. The page separately assigns 50 chlorophyll molecules and only PSI to a bacterial unit, while BGA has PSI and PSII.</p>" +
        "<p><strong>Source qualification:</strong> these quantasome counts are a historical model, not invariant stoichiometry for every modern photosystem. Cyanobacteria have the two interacting oxygenic photosystems. Anoxygenic bacteria commonly have one reaction-centre type, but it can be type I or type II; calling all of them plant PSI/P700 is incorrect. These old particle counts are retained as source context, not scored as universal constants.</p>"
    },
    {
      id: "spectra-and-light-quality",
      title: "PAR, absorption spectra and action spectra",
      sources: [{ document: "biology", page: 289 }, { document: "biology", page: 294 }, { document: "quick-revision", page: 133 }],
      html: "<p>The conventional photosynthetically active radiation band, PAR, is 400&ndash;700 nm. An <strong>absorption spectrum</strong> plots absorption against wavelength for a pigment or a specified pigment mixture. An <strong>action spectrum</strong> plots a biological response, such as photosynthetic oxygen evolution or carbon assimilation, against wavelength under controlled illumination. Strong absorption and high photosynthetic effectiveness are related but not identical measurements.</p>" +
        "<p>The handwritten rankings are absorption blue &gt; violet &gt; red; action blue-violet &gt; red; efficiency red &gt; violet-blue; and total production white &gt; mixed &gt; red &gt; blue, with green lowest. The printed notes instead give action red &gt; blue, absorption blue &gt; red and sunlight &gt; red &gt; blue.</p>" +
        "<p><strong>Source qualification:</strong> these rankings cannot be combined into one universal order. Pigment composition, the response measured, leaf depth, equal incident energy versus equal photon number, and light intensity affect comparisons. Red and blue regions generally contribute strong peaks, while chlorophyll absorbs green less strongly; green light can still support photosynthesis. White light may provide a useful broad spectrum but is not automatically superior to every mixed light at a matched photon flux. The conflicting action-spectrum orders lack an experimental normalization and are not used as scored rankings.</p>" +
        "<p>Quantum yield is product formed per absorbed photon. If an idealized reaction used eight photons per O<sub>2</sub>, its yield would be $\\frac{1}{8}=0.125$ O<sub>2</sub> per photon. The printed 12 percentage entry is not a universal solar-energy efficiency: a molecular quantum yield and a percentage of incident energy retained in biomass have different denominators.</p>"
    },
    {
      id: "linear-electron-transport",
      title: "Linear electron transport and water oxidation",
      sources: [{ document: "biology", page: 290 }, { document: "biology", page: 291 }, { document: "quick-revision", page: 133 }],
      html: "<p>The two handwritten diagrams represent the same noncyclic, or linear, flow. Their labels include PSII 680, pheophytin, PQ/plastoquinone, cytochrome complex, PC/plastocyanin, PSI 700, ferredoxin, NADP reductase, water, oxygen, electrons, protons, stroma and thylakoid space.</p>" +
        "<ol><li><strong>Photoexcitation:</strong> antenna absorption drives excitation and charge separation at PSII. The source's physical/physiological first event refers to electron excitation; charge separation is itself photochemistry.</li><li><strong>Water oxidation:</strong> the PSII oxygen-evolving complex replaces lost electrons by oxidizing water. Its manganese-containing catalytic cluster also involves calcium, with chloride needed for normal function. The balanced half-reaction is 2H<sub>2</sub>O &rarr; O<sub>2</sub> + 4H<sup>+</sup> + 4e<sup>&minus;</sup>. Per water molecule, this is 2H<sup>+</sup>, 2e<sup>&minus;</sup> and half an O<sub>2</sub>.</li><li><strong>PSII acceptors:</strong> pheophytin is the early acceptor highlighted in the notes; electrons then pass through quinone acceptors into the plastoquinone pool. The source's secondary acceptor label refers to PQ.</li><li><strong>Inter-photosystem carriers:</strong> reduced plastoquinone supplies electrons to the cytochrome b<sub>6</sub>f complex; plastocyanin, a mobile copper-containing protein on the lumenal side, carries electrons onward to PSI. Cytochromes contain iron-bearing heme.</li><li><strong>PSI excitation:</strong> a second light-driven excitation sends electrons through PSI acceptors and iron-sulfur centres to ferredoxin on the stromal side.</li><li><strong>Terminal reduction:</strong> ferredoxin-NADP<sup>+</sup> reductase transfers reducing equivalents to NADP<sup>+</sup>, forming NADPH. Water is the ultimate electron donor and NADP<sup>+</sup> the terminal soluble acceptor in this standard flow.</li></ol>" +
        "<p><strong>Source corrections:</strong> NAD<sup>+</sup>/NADH in the diagrams and comparison table must be NADP<sup>+</sup>/NADPH, consistent with their own NADP-reductase label. Ferredoxin is a downstream PSI acceptor, not its first molecular acceptor; A<sub>0</sub> chlorophyll, A<sub>1</sub> phylloquinone and iron-sulfur centres intervene. Photohydrolysis is better called photolysis or light-driven water oxidation; a proton gradient does not split the water. The one-water equation on p.290 is missing an electron, although the two-water diagram above it has the correct four.</p>"
    },
    {
      id: "chemiosmosis-and-assimilatory-power",
      title: "Chemiosmosis, ATP synthase and assimilatory power",
      sources: [{ document: "biology", page: 290 }, { document: "biology", page: 291 }, { document: "biology", page: 289 }, { document: "quick-revision", page: 131 }, { document: "quick-revision", page: 132 }],
      html: "<p>The drawings place many H<sup>+</sup> symbols in the thylakoid space and fewer in the stroma. Water oxidation releases protons into the lumen. Electron transfer involving plastoquinone and cytochrome b<sub>6</sub>f contributes to proton transfer from stroma to lumen, while NADP<sup>+</sup> reduction consumes stromal protons. These processes build an electrochemical proton gradient across an intact thylakoid membrane.</p>" +
        "<p>Protons return from lumen to stroma through ATP synthase. Its stromal catalytic portion couples this downhill return to ADP + P<sub>i</sub> &rarr; ATP. Thus the source's four-part light-reaction sequence is photoexcitation, water oxidation, electron transport and photophosphorylation. These are coupled processes, not four isolated reactions that each wait for the previous process to finish completely.</p>" +
        "<ul><li>ATP means adenosine triphosphate and supplies transferable chemical energy.</li><li>NAD means nicotinamide adenine dinucleotide. NADP is its phosphate-containing relative, nicotinamide adenine dinucleotide phosphate.</li><li>NADP<sup>+</sup> is the natural terminal hydrogen/electron acceptor named by the printed notes for the photosynthetic reducing-power pathway.</li><li>ATP plus NADPH constitute <strong>assimilatory power</strong>. Older NADPH<sub>2</sub> notation denotes reduced NADP with hydrogen equivalents, not a distinct modern coenzyme replacing NADPH.</li><li>The Calvin cycle uses both forms of assimilatory power, then returns ADP, inorganic phosphate and oxidized NADP<sup>+</sup> for reuse.</li></ul>" +
        "<p><strong>Source clarification:</strong> calling ATP alone assimilatory power leaves out the necessary reducing power. ATP synthase uses the gradient; the cytochrome complex helps establish it. Oxygen diffuses away as a byproduct of water oxidation, not as a product of ATP synthase. Proton accumulation must not be placed in the stroma merely because STROMA labels occur above and below a folded membrane drawing.</p>"
    },
    {
      id: "cyclic-versus-linear-flow",
      title: "Cyclic and noncyclic photophosphorylation",
      sources: [{ document: "biology", page: 291 }, { document: "quick-revision", page: 131 }, { document: "quick-revision", page: 132 }],
      html: "<table><thead><tr><th>Feature</th><th>Cyclic flow around plant PSI</th></tr></thead><tbody><tr><td>Photosystem</td><td>PSI/P700; PSII is not required for the cyclic circuit itself.</td></tr><tr><td>Electron route</td><td>Excited electrons pass to PSI acceptors and ferredoxin, then are routed back through the inter-photosystem chain to oxidized P700.</td></tr><tr><td>Net products</td><td>Supports ATP formation; no net NADPH production and no water-derived O<sub>2</sub> production by this circuit.</td></tr><tr><td>Electron donor/return point</td><td>The source identifies P700 as both the initial donor and final return point.</td></tr></tbody></table>" +
        "<table><thead><tr><th>Feature</th><th>Linear flow</th></tr></thead><tbody><tr><td>Photosystems</td><td>PSII followed by PSI, although PSI was named first historically.</td></tr><tr><td>Electron route</td><td>Water &rarr; PSII &rarr; pheophytin/quinones &rarr; cytochrome complex &rarr; plastocyanin &rarr; PSI &rarr; ferredoxin &rarr; NADP<sup>+</sup>.</td></tr><tr><td>Net products</td><td>O<sub>2</sub>, NADPH and a proton gradient supporting ATP synthesis.</td></tr><tr><td>Electron endpoints</td><td>Ultimate donor water; terminal soluble acceptor NADP<sup>+</sup>.</td></tr></tbody></table>" +
        "<p>The printed table assigns two ATP to cyclic flow and one ATP plus one NADPH<sub>2</sub> to noncyclic flow. <strong>Source correction:</strong> without a defined number of electrons, photons and coupling stoichiometry these are not fixed yields. Cyclic flow can supplement ATP when the ATP-to-NADPH demand is higher than linear flow alone supplies.</p><p>The handwritten primitive bacteria versus advanced labels are historical shorthand, not mutually exclusive organism categories: plants and cyanobacteria can use cyclic flow as well as linear flow. Cyclic flow is not confined to weak light and is not defined as an anaerobic process. The absence of oxygen production is different from a requirement that environmental oxygen be absent.</p>"
    },
    {
      id: "emerson-and-red-drop",
      title: "Red drop and Emerson enhancement",
      sources: [{ document: "biology", page: 291 }, { document: "biology", page: 294 }],
      html: "<p>The red-drop observation is a marked decline in photosynthetic quantum yield when illumination is shifted into the far-red region beyond roughly 680 nm in the classical experiments. Far-red light excites PSI more effectively than PSII, so the two photosystems are no longer supplied with balanced excitation for linear flow.</p>" +
        "<p>Emerson enhancement occurs when a shorter red beam and a far-red beam are supplied together and the photosynthetic rate exceeds the sum of the rates produced by the same beams separately. The source illustrates this with approximately 680 and 700 nm. This cooperation supports the presence of two photosystems operating in series. The p.291 enhancement heading has no worked description; the p.294 notes supply the comparison.</p>" +
        "<p>For rates measured with consistent units and experimental conditions, the relationship is $R_{\\mathrm{combined}} &gt; R_{\\mathrm{red}} + R_{\\mathrm{far-red}}$. For example, rates of 3 and 2 units separately but 7 together show enhancement because 7 &gt; 3 + 2.</p><p><strong>Source correction:</strong> the handwritten inequality adds quantum yields directly. A quantum yield is normalized by absorbed photons, so such normalized ratios cannot generally be added as if they were rates. The rate comparison above preserves the intended experiment. The wavelength numbers identify characteristic excitation, not absolute upper limits beyond which every associated pigment is inactive.</p>"
    },
    {
      id: "calvin-cycle-identity",
      title: "Calvin cycle: acceptor, enzyme and products",
      sources: [{ document: "biology", page: 292 }, { document: "biology", page: 291 }, { document: "quick-revision", page: 133 }, { document: "biology", page: 293 }],
      html: "<p>The Calvin-Benson cycle operates in chloroplast stroma. The initial carbon dioxide acceptor is five-carbon ribulose-1,5-bisphosphate, RuBP. Rubisco catalyses its carboxylation. Rubisco means ribulose-1,5-bisphosphate carboxylase/oxygenase: its full name includes both competing activities. It is an exceptionally abundant enzyme, conventionally described as the most abundant enzyme on Earth.</p>" +
        "<p>The unstable six-carbon addition product splits into two molecules of three-carbon 3-phosphoglycerate, 3-PGA. This is why ordinary Calvin-cycle carbon fixation is called C<sub>3</sub>. Reduction forms glyceraldehyde-3-phosphate, G3P, also called PGAL. PGAL is the source's connecting compound between photosynthesis and respiration because triose phosphates also participate in glycolytic metabolism. Net triose phosphate can be used to synthesize glucose and other carbohydrates.</p>" +
        "<p><strong>Source corrections:</strong> PGA is the first stable carboxylation product, but it is a phosphorylated organic acid, not the first free sugar. Glucose is a useful overall end-product representation, not the direct product released in each turn. The handwritten ribulose biphosphase expansion is incorrect; bisphosphate names two phosphate groups on the acceptor, and carboxylase/oxygenase names the enzyme.</p>" +
        "<p>The printed source lists algae, bryophytes, pteridophytes and gymnosperms in its C<sub>3</sub> account. The Calvin cycle is also retained in C<sub>4</sub> and CAM plants; it is not exclusive to plants called C<sub>3</sub>. Carbon-concentrating mechanisms vary among algae and other groups, so this list cannot prove universally high photorespiration in every member. The p.292 annotation 16% in chloroplast lacks a denominator and is retained as an unresolved percentage, not a protein-abundance key.</p>"
    },
    {
      id: "calvin-steps-and-carbon-budget",
      title: "Calvin-cycle steps and the carbon/energy budget",
      sources: [{ document: "biology", page: 292 }, { document: "quick-revision", page: 133 }],
      html: "<p>The handwritten sequence is carboxylation, glycolytic reversal and regeneration of RuBP. Glycolytic reversal is a teaching name for the reduction phase, not a claim that every glycolytic reaction simply runs backwards. Both inserted source diagrams show the same three-carbon-input budget.</p>" +
        "<ol><li><strong>Carboxylation:</strong> three CO<sub>2</sub> molecules add to three five-carbon RuBP molecules. The resulting 18 carbons appear in six three-carbon 3-PGA molecules. Rubisco catalyses fixation; the diagrams label RuBP as starting material and this phase as carbon fixation.</li><li><strong>Reduction:</strong> six ATP phosphorylate six 3-PGA and six NADPH supply reducing equivalents, yielding six G3P molecules. The reaction sequence passes through 1,3-bisphosphoglycerate. ADP, phosphate and NADP<sup>+</sup> return to the light-reaction pools. The source's NADPH-to-NADP<sup>+</sup> arrow, not the sign of a decorative proton label, defines oxidation of the carrier.</li><li><strong>Net output:</strong> one of the six G3P molecules can leave as the net three-carbon product. A diagram arrow from this one G3P to glucose is shorthand for subsequent sugar synthesis; one three-carbon molecule cannot alone supply six carbons.</li><li><strong>Regeneration:</strong> the remaining five G3P, containing 15 carbons, are rearranged and use three more ATP to regenerate three RuBP, also containing 15 carbons. The displayed 3 ADP and phosphate labels represent ATP expenditure.</li></ol>" +
        "<p>Therefore three fixed CO<sub>2</sub> give one net G3P at a cost of nine ATP and six NADPH. Six fixed CO<sub>2</sub> give two net G3P, sufficient carbon for one hexose equivalent, at a cost of 18 ATP and 12 NADPH. Per fixed CO<sub>2</sub>, the idealized cost is three ATP and two NADPH. These values assume the ordinary cycle without additional photorespiratory loss or carbon-concentrating costs. The handwritten requirement 12 NADH is corrected to 12 NADPH.</p>"
    },
    {
      id: "photorespiration-entry-and-cost",
      title: "Photorespiration: Rubisco oxygenation and carbon loss",
      sources: [{ document: "biology", page: 292 }, { document: "biology", page: 294 }, { document: "quick-revision", page: 133 }],
      html: "<p>Photorespiration, the C<sub>2</sub> or photorespiratory carbon-oxidation cycle, begins when Rubisco oxygenates RuBP instead of carboxylating it. The same enzyme has both activities; it does not transform into a separate RuBP oxygenase protein. The source's Dicker and Tio on tobacco attribution refers to work conventionally credited to Decker and Tio.</p>" +
        "<p>One five-carbon RuBP plus O<sub>2</sub> yields one three-carbon 3-PGA and one two-carbon 2-phosphoglycolate. Removal of phosphate produces glycolate, the two-carbon compound emphasized as the first stable product in the abbreviated notes. The direct oxygenation product is 2-phosphoglycolate; it should not be called chemically unstable merely to make glycolate the first product.</p>" +
        "<ul><li>High temperature and a high O<sub>2</sub>-to-CO<sub>2</sub> ratio favour oxygenation relative to carboxylation. Water stress can close stomata and restrict CO<sub>2</sub> entry.</li><li>RuBP is the five-carbon substrate being oxygenated, not a CO<sub>2</sub> acceptor in this particular reaction. The source's CO<sub>2</sub>-acceptor label is carried over from the Calvin-cycle comparison.</li><li>The pathway salvages carbon from phosphoglycolate but consumes energy and releases some previously fixed CO<sub>2</sub>; it does not deliver a net ATP or glucose gain.</li><li>The source calls it wasteful. Relative to direct carbon assimilation it incurs a cost, but the salvage pathway also prevents accumulation of inhibitory phosphoglycolate and has physiological roles.</li></ul>" +
        "<p><strong>Source corrections:</strong> the p.292 sentence saying no energy is produced but glucose and ATP are produced is internally inconsistent; photorespiration does not provide net glucose and ATP. The printed more than 50% of total energy is lost is not an invariant fraction. Loss depends on conditions and must not be confused with the specific one-carbon loss from two two-carbon glycolate equivalents during salvage.</p>"
    },
    {
      id: "photorespiratory-organelle-pathway",
      title: "The chloroplast-peroxisome-mitochondrion pathway",
      sources: [{ document: "biology", page: 292 }, { document: "quick-revision", page: 133 }],
      html: "<p>The printed mnemonic <strong>CPM</strong> recalls the outward sequence chloroplast &rarr; peroxisome &rarr; mitochondrion. The complete salvage route returns through peroxisome to chloroplast. These compartments, not a single organelle, explain the source diagram.</p>" +
        "<ol><li><strong>Chloroplast:</strong> Rubisco oxygenation of RuBP produces 3-PGA plus 2-phosphoglycolate. Phosphoglycolate is dephosphorylated to glycolate, which leaves the chloroplast. The 3-PGA remains available to carbon metabolism.</li><li><strong>Peroxisome:</strong> glycolate oxidation produces glyoxylate and H<sub>2</sub>O<sub>2</sub>. Transamination produces glycine. Catalase removes peroxide: 2H<sub>2</sub>O<sub>2</sub> &rarr; 2H<sub>2</sub>O + O<sub>2</sub>. The source's peroxide and half-oxygen labels should be understood as linked oxidation and peroxide-detoxification processes, not as the main photosynthetic oxygen source.</li><li><strong>Mitochondrion:</strong> two glycine molecules, four carbons altogether, are converted into one three-carbon serine with release of one CO<sub>2</sub> and ammonia, NH<sub>3</sub>. Glycine decarboxylase and serine hydroxymethyltransferase mediate the coupled conversion. The source labels ammonia toxic; it is reassimilated rather than deliberately accumulated.</li><li><strong>Return through peroxisome:</strong> serine-derived carbon passes through hydroxypyruvate to glycerate.</li><li><strong>Return to chloroplast:</strong> glycerate is phosphorylated using ATP to form 3-PGA, returning salvaged carbon to the Calvin-cycle pool.</li></ol>" +
        "<p><strong>Source corrections:</strong> the printed 2 glycine &rarr; serine + 2CO<sub>2</sub> creates five product carbons from four input carbons. The correct carbon balance releases one CO<sub>2</sub>. The handwritten diagram places the serine-to-glycerate return entirely in the mitochondrial box; the peroxisomal return is missing and has been restored here. Its chloroplast most important organ label is not a reason to omit the other two compartments.</p>"
    },
    {
      id: "c4-anatomy-and-carboxylation",
      title: "C4 anatomy and initial fixation",
      sources: [{ document: "biology", page: 293 }, { document: "quick-revision", page: 133 }, { document: "biology", page: 289 }],
      html: "<p>C<sub>4</sub> photosynthesis concentrates CO<sub>2</sub> around Rubisco. It is advantageous in many warm, strongly illuminated environments where photorespiration would otherwise be substantial. The printed hot and dry association and handwritten tropical humid association describe examples of habitat, not mutually exclusive definitions. A C<sub>4</sub> plant does not become C<sub>4</sub> only when atmospheric CO<sub>2</sub> falls on a particular day.</p>" +
        "<p>The usual <strong>Kranz</strong>, meaning wreath, anatomy has a vascular bundle surrounded by a ring of chloroplast-containing bundle-sheath cells, with mesophyll outside. The source micrograph labels vascular bundle, bundle sheath cells and mesophyll. Its dimorphic chlorophyll heading should read dimorphic chloroplasts: the two cell types can have differently organized chloroplasts.</p>" +
        "<table><thead><tr><th>Cell type</th><th>Source comparison with qualifications</th></tr></thead><tbody><tr><td>Mesophyll</td><td>Initial inorganic-carbon fixation by PEP carboxylase; ordinary granal and stromal organization in the illustrated type. Rubisco is predominantly localized elsewhere in the standard two-cell C<sub>4</sub> account.</td></tr><tr><td>Bundle sheath</td><td>High local CO<sub>2</sub> and Rubisco support the Calvin cycle. The source depicts few/no grana and relatively little O<sub>2</sub> evolution.</td></tr></tbody></table>" +
        "<p><strong>Source corrections:</strong> agranal bundle-sheath chloroplasts and low PSII activity are characteristic of some C<sub>4</sub> subtypes, not all C<sub>4</sub> plants. Bundle-sheath chloroplasts can carry out light reactions, including cyclic flow; only dark reactions is too absolute. Reduced photorespiration depends principally on CO<sub>2</sub> concentration around Rubisco, not a universal absence of oxygen. Kranz anatomy is usual, but exceptional single-cell C<sub>4</sub> systems exist.</p>" +
        "<p>The initial three-carbon acceptor is phosphoenolpyruvate, PEP. PEP carboxylase, PEPC or the source's PEPCO/pepase, fixes bicarbonate derived from CO<sub>2</sub> to produce four-carbon oxaloacetate, OAA, also called oxaloacetic acid. RuBP is still the acceptor when released CO<sub>2</sub> subsequently enters the Calvin cycle.</p>"
    },
    {
      id: "c4-shuttle-and-comparison",
      title: "C4 transport steps, costs and examples",
      sources: [{ document: "biology", page: 293 }, { document: "quick-revision", page: 133 }],
      html: "<ol><li>PEP, three carbons, is carboxylated in mesophyll to OAA, four carbons.</li><li>OAA is converted to malate or aspartate, called malic acid or aspartic acid in the diagram, and four-carbon material moves to bundle-sheath cells.</li><li>Decarboxylation releases CO<sub>2</sub> near Rubisco. The carbon enters RuBP &rarr; 3-PGA &rarr; G3P/3-GP &rarr; sugar, while most Calvin-cycle carbon regenerates RuBP.</li><li>A three-carbon return compound moves back to mesophyll and PEP is regenerated. In the common malic-enzyme route, malate produces pyruvate plus CO<sub>2</sub>; pyruvate phosphate dikinase regenerates PEP at a cost equivalent to two ATP per CO<sub>2</sub> concentrated.</li></ol>" +
        "<p><strong>Source correction:</strong> the schematic malic/aspartic acid &rarr; CO<sub>2</sub> + PEP collapses several subtype-dependent reactions and omits the energy requirement. It is not one universal unassisted conversion. Some decarboxylation routes involve PEP carboxykinase; the transport and return intermediates must be distinguished from the Calvin-cycle acceptor.</p>" +
        "<table><thead><tr><th>Feature</th><th>C3 compared with conventional C4</th></tr></thead><tbody><tr><td>First acceptor/product</td><td>C<sub>3</sub>: RuBP/3-PGA. C<sub>4</sub> initial fixation: PEP/OAA.</td></tr><tr><td>Hexose-equivalent cost</td><td>C<sub>3</sub>: 18 ATP and 12 NADPH. Idealized C<sub>4</sub>: 30 ATP equivalents and 12 NADPH, including 12 extra ATP equivalents for six CO<sub>2</sub>.</td></tr><tr><td>Photorespiration</td><td>Often appreciable in C<sub>3</sub>; strongly suppressed, not necessarily absolutely absent, in C<sub>4</sub>.</td></tr><tr><td>Calvin-cycle site</td><td>Ordinary C<sub>3</sub> leaf: mesophyll chloroplasts. Typical two-cell C<sub>4</sub> leaf: bundle-sheath chloroplasts.</td></tr><tr><td>Source temperature ranges</td><td>C<sub>3</sub>: 10&ndash;25 &deg;C, temperate association. C<sub>4</sub>: 30&ndash;45 &deg;C, tropical association. These are illustrative, species-dependent ranges.</td></tr></tbody></table>" +
        "<p>C<sub>3</sub> examples listed are rice, wheat, barley, cotton, soybean, tobacco and potato. C<sub>4</sub> examples are sugarcane, sorghum, maize, common C<sub>4</sub> millets and switchgrass; Amaranthus is the highlighted dicot example. C<sub>4</sub> land plants occur among angiosperms, prominently grasses but also eudicots. The source's 85% C<sub>3</sub>/15% C<sub>4</sub> split has no defined population or measurement and is not a reliable universal species fraction.</p>" +
        "<p>Atriplex is the printed both C<sub>3</sub> and C<sub>4</sub> example. The genus includes different photosynthetic types, and a C<sub>4</sub> plant itself also operates the Calvin cycle. This statement alone does not identify one species that switches pathways under every condition.</p>"
    },
    {
      id: "cam-night-and-day",
      title: "CAM: night-time uptake and daytime carbon use",
      sources: [{ document: "biology", page: 293 }, { document: "biology", page: 291 }],
      html: "<p>CAM stands for <strong>crassulacean acid metabolism</strong>. Many succulent xerophytes conserve water by opening stomata mainly at night, the source's scotoactive condition. Carbon concentration is separated in time within photosynthetic tissue, rather than obligatorily between mesophyll and bundle sheath as in typical C<sub>4</sub> leaves.</p>" +
        "<ol><li><strong>Night:</strong> stomata open; incoming CO<sub>2</sub> supplies bicarbonate for PEP carboxylase. PEP is converted to four-carbon OAA, then malate. Malic acid accumulates in the vacuole. The night diagram labels PEP, OAA, malic acid, vacuole and a stomatal gas opening.</li><li><strong>Day:</strong> stomata are commonly closed. Stored acid leaves the vacuole and is decarboxylated, supplying CO<sub>2</sub> internally. The source separately notes malic acid to pyruvic acid.</li><li>Released CO<sub>2</sub> enters the Calvin cycle through RuBP, PGA and G3P, supporting sugar synthesis using light-generated ATP and NADPH. Three-carbon material is recycled to replenish the carbohydrate/PEP pool.</li></ol>" +
        "<p>The source's C<sub>3</sub> anatomy, C<sub>4</sub> physiology phrase is a mnemonic for absence of obligatory Kranz anatomy plus initial four-carbon acid formation; CAM remains a distinct temporal strategy. The daytime malic acid &rarr; PEP + CO<sub>2</sub> arrow abbreviates decarboxylation and metabolic regeneration, not one universal reaction. The O<sub>2</sub> arrow by the night-time stoma must not be taken as oxygen evolution from dark PEP fixation: the light-driven water-oxidation reaction is separate.</p>" +
        "<p>Listed examples are Bryophyllum, members of Crassulaceae, snake plants, pineapple and Opuntia. Not every succulent necessarily uses the same CAM pattern, and facultative CAM plants can vary uptake with conditions. The final source location list correctly places Calvin fixation in mesophyll for ordinary C<sub>3</sub> and bundle sheath for typical C<sub>4</sub>, but its third entry is written C5 &rarr; mesophyll without defining C5. That label is unresolved and is not introduced here as another established pathway.</p>"
    },
    {
      id: "compensation-and-limiting-factors",
      title: "CO2 compensation and limiting factors",
      sources: [{ document: "biology", page: 289 }, { document: "biology", page: 293 }, { document: "biology", page: 294 }, { document: "quick-revision", page: 131 }, { document: "quick-revision", page: 132 }, { document: "quick-revision", page: 133 }],
      html: "<p>The <strong>CO<sub>2</sub> compensation point</strong> is the CO<sub>2</sub> concentration at which net CO<sub>2</sub> exchange is zero under specified light, temperature and oxygen conditions: photosynthetic uptake balances release from respiratory processes, including photorespiration where applicable. It is not simply the smallest CO<sub>2</sub> concentration at which any biochemical cycle can run.</p>" +
        "<p>The handwritten comparison gives C<sub>3</sub> 50&ndash;100 ppm, C<sub>4</sub> 0&ndash;10 ppm and CAM 5&ndash;10 ppm; the printed C<sub>3</sub> entry says high compensation point and high photorespiration. These source ranges illustrate the comparatively lower apparent compensation associated with carbon concentration, not fixed diagnostic boundaries. CAM measurements depend especially on phase and whether external or internal CO<sub>2</sub> exchange is measured.</p>" +
        "<p>The limiting-factor principle states that the rate is constrained by the factor presently least adequate relative to demand. The source gives CO<sub>2</sub> first and light next if CO<sub>2</sub> becomes abundant. Its CO<sub>2</sub>-response graph has rate on the vertical axis, CO<sub>2</sub> on the horizontal axis, an initial rise and an eventual flattening as another process limits the rate.</p>" +
        "<p><strong>Source corrections:</strong> CO<sub>2</sub> is not always the most important limiting factor, and it can limit C<sub>4</sub> plants under sufficiently low availability. Their concentrating mechanism reduces sensitivity under many conditions but cannot manufacture carbon. The p.289 statement that CO<sub>2</sub> limits C<sub>3</sub> and CAM but not C<sub>4</sub> is therefore too absolute. Likewise, the printed claim that light is never limiting except on cloudy days excludes shade, dawn, dusk and controlled low illumination without justification.</p>"
    },
    {
      id: "light-water-temperature-and-oxygen",
      title: "Light intensity, water status, temperature and oxygen",
      sources: [{ document: "biology", page: 294 }, { document: "quick-revision", page: 133 }],
      html: "<p>The light-intensity graph shows rate rising at low intensity and then approaching a plateau. Increasing intensity helps only while light supply is limiting. At saturation another constraint dominates; excessive light can cause photoinhibition or photooxidative injury. The source's denaturing of chlorophyll explanation is imprecise: saturation does not itself establish pigment destruction, and chlorophyll is not a protein enzyme that simply denatures.</p>" +
        "<ul><li>The printed intermittent light &gt; continuous light can apply to particular pulse patterns and equal-light-dose comparisons; it is not an unconditional ranking.</li><li>Light duration is distinct from instantaneous intensity. A longer suitable photoperiod can change total daily carbon gain, so duration does not affect photosynthesis is too broad.</li><li>Healthy mature leaves generally have greater developed photosynthetic capacity than very young leaves; this does not mean senescent leaves always outperform expanding ones.</li><li>Turgid, adequately hydrated cells usually support photosynthesis better than water-stressed flaccid tissue. Water shortage affects stomatal aperture, CO<sub>2</sub> supply and metabolism, not just the stoichiometric amount of water split.</li><li>The source's temperature curve rises to an optimum and then falls. Its printed 25&ndash;30 &deg;C range is a common teaching example, not a universal optimum.</li></ul>" +
        "<p>The temperature-flow diagram is transcribed with its sign corrected: heat/water loss &rarr; stomatal closure to restrict water loss &rarr; reduced internal CO<sub>2</sub> relative to O<sub>2</sub> &rarr; greater relative photorespiration &rarr; reduced net photosynthesis. The source's downward arrow at photorespiration contradicts the mechanism and should be upward in this comparison. Heat can also impair enzymes and membranes independently.</p>" +
        "<p><strong>Warburg effect:</strong> oxygen inhibits net photosynthesis in susceptible systems, notably through competition with CO<sub>2</sub> at Rubisco and increased photorespiration. <strong>Source correction:</strong> p.294 says increasing CO<sub>2</sub> causes the Warburg effect; the printed O<sub>2</sub> association is the correct one. The source formula photosynthesis proportional to the reciprocal of oxygen is only a directional mnemonic, not a quantitative inverse law. The separately printed <strong>Pasteur effect</strong> refers to oxygen suppressing fermentation and often reducing the carbohydrate-consumption rate when aerobic ATP production becomes available; it is not simply all respiration increases with oxygen.</p>"
    },
    {
      id: "source-efficiency-and-blocking-claims",
      title: "Efficiency claims and photosynthetic inhibition",
      sources: [{ document: "biology", page: 294 }, { document: "quick-revision", page: 131 }, { document: "quick-revision", page: 132 }, { document: "quick-revision", page: 133 }],
      html: "<p>The handwritten efficiency list states that 1% of solar energy is absorbed by plants and 0.1&ndash;0.2% is utilized for photosynthesis. It labels sugarcane most efficient at 10% sunlight and a winter evening primrose, written Oenothera calviformis, second at 8%. These entries do not specify the radiation denominator, time scale, gross versus net production, growing conditions or measurement method.</p>" +
        "<p><strong>Source qualification:</strong> do not combine these figures or treat them as established universal rankings. Fraction of total incident solar energy, fraction of PAR absorbed and fraction stored in net biomass are different quantities. The evening-primrose binomial cannot be safely normalized from this page alone; its exact identity and both crop efficiencies remain unresolved. The printed 12% quantum-yield entry also lacks a stated basis and cannot verify these energy percentages.</p>" +
        "<p>The last highlighted p.294 phrase says herbicides kill plants by blocking, with a bracket beside the PSI/PSII descriptions but no named compound or completed target. Some herbicides inhibit photosynthetic electron transport, whereas others act elsewhere in metabolism. The unfinished phrase cannot identify a particular herbicide, photosystem or molecular target and is excluded from scored questions.</p>" +
        "<p>The repeated printed Pigment system line reads photolysis of water not flowering. Its missing connection is not recoverable from the assigned pages. The complete nearby water-oxidation and photosystem statements are transcribed separately; no invented flowering relationship is supplied.</p>"
    },
    {
      id: "source-metabolic-and-mineral-reminders",
      title: "Metabolic and mineral reminders on the printed spread",
      sources: [{ document: "quick-revision", page: 131 }, { document: "quick-revision", page: 132 }],
      html: "<p>The printed pages begin with cross-topic reminders before the photosynthesis heading. They distinguish <strong>floating respiration</strong>, use of carbohydrate reserves, from <strong>protoplasmic respiration</strong>, use of protein/protoplasmic material, especially in starvation. The hydrate/water/floating word association is a memory aid; it does not mean that carbohydrate metabolism physically floats on water.</p>" +
        "<table><thead><tr><th>Element</th><th>Source associations and qualifications</th></tr></thead><tbody><tr><td>Chromium, Cr</td><td>Promotes insulin action in the source's animal-nutrition reminder. This is not a plant-essentiality criterion; chromium's essentiality in humans is disputed and this line does not establish a need for supplementation.</td></tr><tr><td>Manganese, Mn</td><td>Indirect contribution to chlorophyll-related metabolism and a vital catalytic role in the PSII oxygen-evolving complex.</td></tr><tr><td>Zinc, Zn</td><td>Carbonic anhydrase; auxin-related metabolism; animal associations with insulin storage/function and wound healing. These are physiological associations, not treatment instructions.</td></tr><tr><td>Iron, Fe</td><td>Aconitase, catalase and cytochrome oxidase. Iron-sulfur centres and heme groups explain different roles; the source's Fe<sup>2+</sup> heading does not mean every listed iron atom stays in that state.</td></tr><tr><td>Copper, Cu</td><td>Tyrosinase, with copper changing oxidation state in catalysis. Plastocyanin is the photosynthetic copper-protein example.</td></tr><tr><td>Molybdenum, Mo</td><td>Conventional Mo-containing nitrogenase and xanthine oxidase; this does not exclude alternative nitrogenases in some microbes.</td></tr><tr><td>Magnesium, Mg</td><td>Cofactor for many kinases, enolase and appropriate dehydrogenases; supports Rubisco activation and PEP-carboxylase catalysis.</td></tr><tr><td>Nickel, Ni</td><td>Metal cofactor of urease.</td></tr></tbody></table>" +
        "<p><strong>Source corrections:</strong> magnesium activates RuBP and PEP is shorthand for activation of enzymes using those substrates; the substrates are not themselves enzymes. Not every dehydrogenase requires magnesium. Tyrosinase and insulin examples should not be relabelled as functions unique to plants. Cytochromes are iron-containing electron-transfer proteins shared in broad function between respiratory and photosynthetic chains, but the individual complexes of the two systems differ.</p>"
    },
    {
      id: "classical-photosynthesis-experiments",
      title: "Light-screen, half-leaf and bubbler experiments",
      sources: [{ document: "quick-revision", page: 133 }],
      html: "<table><thead><tr><th>Experiment</th><th>What is tested</th></tr></thead><tbody><tr><td>Ganong's light screen</td><td>Light is needed for photosynthetic starch formation. In a destarched leaf, an opaque screen excludes light from a region while exposed tissue serves as a comparison; the subsequent starch test distinguishes the regions.</td></tr><tr><td>Moll's half-leaf experiment</td><td>CO<sub>2</sub> is needed. Part of a suitably destarched leaf is exposed to CO<sub>2</sub>-depleted air, conventionally using an absorber such as KOH, while another part has carbon dioxide available; lighting and other conditions must remain suitable.</td></tr><tr><td>Willmott's bubbler</td><td>Measures oxygen evolution as an index of photosynthetic activity in an aquatic preparation.</td></tr></tbody></table>" +
        "<p>Destarching reduces the chance that previously stored carbohydrate is mistaken for new photosynthesis. An appropriate comparison is essential: covering a leaf and removing its CO<sub>2</sub> at the same time cannot isolate which factor caused the change. Bubble counts are only an approximate rate measure because bubble volume, dissolved oxygen, temperature and respiration can influence the relation to gross photosynthetic oxygen production.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 131, status: "partial", sectionIds: ["discovery-and-tracer-evidence", "pigment-families-and-colours", "pigment-formulas-and-chlorophyll-structure", "photosystems-antennae-and-quantasomes", "chemiosmosis-and-assimilatory-power", "cyclic-versus-linear-flow", "compensation-and-limiting-factors", "source-efficiency-and-blocking-claims", "source-metabolic-and-mineral-reminders"], unresolved: ["Upper-right Pigment system bullet reads 'Photolysis of water not flowering' without a complete connection or proposition. No flowering-related claim can be recovered or scored."] },
    { document: "quick-revision", page: 132, status: "partial", sectionIds: ["discovery-and-tracer-evidence", "pigment-families-and-colours", "pigment-formulas-and-chlorophyll-structure", "photosystems-antennae-and-quantasomes", "chemiosmosis-and-assimilatory-power", "cyclic-versus-linear-flow", "compensation-and-limiting-factors", "source-efficiency-and-blocking-claims", "source-metabolic-and-mineral-reminders"], unresolved: ["This second photograph repeats p.131, including the incomplete upper-right 'Photolysis of water not flowering' bullet. The intended missing connection remains unresolved and is not scored."] },
    { document: "quick-revision", page: 133, status: "partial", sectionIds: ["discovery-and-tracer-evidence", "pigment-families-and-colours", "photosystems-antennae-and-quantasomes", "spectra-and-light-quality", "linear-electron-transport", "calvin-cycle-identity", "calvin-steps-and-carbon-budget", "photorespiration-entry-and-cost", "photorespiratory-organelle-pathway", "c4-anatomy-and-carboxylation", "c4-shuttle-and-comparison", "compensation-and-limiting-factors", "light-water-temperature-and-oxygen", "source-efficiency-and-blocking-claims", "classical-photosynthesis-experiments"], unresolved: ["Upper-left 'Quantum yield of photosynthesis is 12 percentage' does not identify absorbed versus incident photons or a product basis; it is distinguished from energy efficiency, not used as an exact key.", "Right-column action-spectrum Red > Blue and unconditional light rankings lack equal-photon/equal-energy conditions and conflict with Biology p.289's action order; no universal ranking is scored."] },
    { document: "biology", page: 289, status: "partial", sectionIds: ["nature-and-overall-reaction", "photosynthetic-sites-and-membranes", "spectra-and-light-quality", "chemiosmosis-and-assimilatory-power", "c4-anatomy-and-carboxylation", "compensation-and-limiting-factors"], unresolved: ["Lower-right action spectrum Blue-violet > Red and separate efficiency Red > Violet-blue give no incident-energy or photon-flux normalization; the rankings are preserved with this limitation and not scored."] },
    { document: "biology", page: 290, status: "transcribed", sectionIds: ["photosynthetic-sites-and-membranes", "pigment-families-and-colours", "pigment-formulas-and-chlorophyll-structure", "photosystems-antennae-and-quantasomes", "linear-electron-transport", "chemiosmosis-and-assimilatory-power"], unresolved: [] },
    { document: "biology", page: 291, status: "transcribed", sectionIds: ["photosynthetic-sites-and-membranes", "linear-electron-transport", "chemiosmosis-and-assimilatory-power", "cyclic-versus-linear-flow", "emerson-and-red-drop", "calvin-cycle-identity", "cam-night-and-day"], unresolved: [] },
    { document: "biology", page: 292, status: "partial", sectionIds: ["discovery-and-tracer-evidence", "calvin-cycle-identity", "calvin-steps-and-carbon-budget", "photorespiration-entry-and-cost", "photorespiratory-organelle-pathway"], unresolved: ["Upper-left Rubisco annotation '16% in chloroplast' does not state whether the denominator is protein, mass or another quantity. The enzyme identity is clear, but this percentage is not scored."] },
    { document: "biology", page: 293, status: "partial", sectionIds: ["calvin-cycle-identity", "c4-anatomy-and-carboxylation", "c4-shuttle-and-comparison", "cam-night-and-day", "compensation-and-limiting-factors"], unresolved: ["C3/C4 table headings assign 85% and 15% of plants without defining species counts, biomass or another population; these fractions are retained as unverified source figures, not keys.", "Final right-column Calvin-cycle location list labels its third row 'C5 -> Mesophyll cell' without defining C5. It is not silently substituted for CAM or used as a scored pathway name."] },
    { document: "biology", page: 294, status: "partial", sectionIds: ["photosystems-antennae-and-quantasomes", "spectra-and-light-quality", "emerson-and-red-drop", "photorespiration-entry-and-cost", "compensation-and-limiting-factors", "light-water-temperature-and-oxygen", "source-efficiency-and-blocking-claims"], unresolved: ["Middle-left 1% absorption, 0.1-0.2% utilization, sugarcane 10% and evening-primrose 8% figures lack a radiation denominator and measurement conditions. The written 'Oenothera calviformis' identity is also not safely resolved from the assigned pages; none is a scored efficiency/ranking key.", "Right-column final phrase 'Herbicides kill plants by blocking' ends without naming a herbicide or completing its target; the adjacent photosystem bracket does not uniquely supply one."] }
  ],
  questions: [
    {
      id: "note-photosynthesis-001", text: "The overall photosynthetic equation shows water becoming oxygen and carbon dioxide becoming carbohydrate. Which description accounts for both changes?",
      options: [{ key: "a", text: "Both water and carbon dioxide are oxidized" }, { key: "b", text: "Water is oxidized and carbon dioxide is reduced" }, { key: "c", text: "Water is reduced and carbon dioxide is oxidized" }, { key: "d", text: "Both water and carbon dioxide are reduced" }],
      answer: "b", explanation: "Water donates electrons and is oxidized to oxygen, whereas carbon in CO2 gains reducing equivalents during carbohydrate formation. Photosynthesis is therefore an overall redox process, even though carbon assimilation alone is a reduction.", sectionId: "nature-and-overall-reaction", source: { document: "biology", page: 289 }, cognitive: "understanding"
    },
    {
      id: "note-photosynthesis-002", text: "An illuminated algal culture receives oxygen-labelled water and ordinary CO2. Before substantial isotope exchange, which product directly tests the origin of evolved oxygen?",
      options: [{ key: "a", text: "Labelled oxygen gas from water oxidation" }, { key: "b", text: "Unlabelled oxygen gas from carbon fixation" }, { key: "c", text: "Labelled carbon atoms in the first sugar" }, { key: "d", text: "Unlabelled ATP made by the Calvin cycle" }],
      answer: "a", explanation: "The oxygen atoms released as O2 originate in water. Isotopic oxygen in the supplied water therefore appears in the evolved gas. A carbon tracer would instead follow assimilation into carbon compounds, addressing a different question.", sectionId: "discovery-and-tracer-evidence", source: { document: "quick-revision", page: 131 }, cognitive: "application"
    },
    {
      id: "note-photosynthesis-003", text: "A chloroplast preparation retains an intact thylakoid system but loses most stromal enzymes. Which ability is directly impaired by the loss of the stromal enzymes?",
      options: [{ key: "a", text: "Antenna absorption of incoming photons" }, { key: "b", text: "Water oxidation at photosystem II" }, { key: "c", text: "Electron transfer through plastocyanin" }, { key: "d", text: "Calvin-cycle assimilation of carbon dioxide" }],
      answer: "d", explanation: "The Calvin-cycle enzymes operate in the stroma, so removal of those enzymes directly impairs carbon assimilation. Antenna pigments, the water-oxidation machinery and electron-transfer complexes belong to the retained thylakoid apparatus, although sustained operation still needs suitable substrates.", sectionId: "photosynthetic-sites-and-membranes", source: { document: "biology", page: 291 }, cognitive: "application"
    },
    {
      id: "note-photosynthesis-004", text: "Which pair comprises the phycobilin-associated accessory pigments named in the handwritten pigment tree?",
      options: [{ key: "a", text: "Chlorophyll a and chlorophyll b" }, { key: "b", text: "Beta-carotene and xanthophyll" }, { key: "c", text: "Phycoerythrin and phycocyanin" }, { key: "d", text: "Anthocyanin and bacteriochlorophyll" }],
      answer: "c", explanation: "The phycobilin branch names phycoerythrin and phycocyanin. In photosynthetic antennae they occur in water-soluble phycobiliprotein complexes, distinct from chlorophylls, carotenoids and vacuolar anthocyanins.", sectionId: "pigment-families-and-colours", source: { document: "biology", page: 290 }, cognitive: "recall"
    },
    {
      id: "note-photosynthesis-005", text: "Replacing the compared methyl group of chlorophyll a with the formyl group of chlorophyll b changes which part of the molecular formula?",
      options: [{ key: "a", text: "Two more hydrogens and one less oxygen" }, { key: "b", text: "Two fewer hydrogens and one less oxygen" }, { key: "c", text: "Two more hydrogens and one more oxygen" }, { key: "d", text: "Two fewer hydrogens and one more oxygen" }],
      answer: "d", explanation: "A methyl group is CH3 and a formyl group is CHO. Carbon count stays the same, hydrogen decreases by two and oxygen increases by one. Thus chlorophyll a has H72/O5 whereas chlorophyll b has H70/O6, with C55, Mg and N4 unchanged.", sectionId: "pigment-formulas-and-chlorophyll-structure", source: { document: "biology", page: 290 }, cognitive: "understanding"
    },
    {
      id: "note-photosynthesis-006", text: "One graph plots pigment absorbance against wavelength; another plots oxygen evolution against wavelength at a controlled photon flux. How are the graphs classified?",
      options: [{ key: "a", text: "First action spectrum; second absorption spectrum" }, { key: "b", text: "First absorption spectrum; second action spectrum" }, { key: "c", text: "Both absorption spectra of isolated pigments" }, { key: "d", text: "Both action spectra of carbon fixation" }],
      answer: "b", explanation: "Absorbance measures how strongly light is absorbed, defining an absorption spectrum. Oxygen evolution is a biological response, defining an action spectrum when measured across wavelengths. Controlled illumination makes the response comparison meaningful.", sectionId: "spectra-and-light-quality", source: { document: "biology", page: 289 }, cognitive: "understanding"
    },
    {
      id: "note-photosynthesis-007", text: "Which early PSII electron acceptor is explicitly labelled before plastoquinone in both handwritten light-reaction diagrams?",
      options: [{ key: "a", text: "Pheophytin" }, { key: "b", text: "Plastocyanin" }, { key: "c", text: "Ferredoxin" }, { key: "d", text: "NADP reductase" }],
      answer: "a", explanation: "Pheophytin receives electrons early on the PSII acceptor side before the quinone pathway. Plastocyanin transfers electrons towards PSI, ferredoxin acts downstream of PSI and NADP reductase forms NADPH.", sectionId: "linear-electron-transport", source: { document: "biology", page: 291 }, cognitive: "recall"
    },
    {
      id: "note-photosynthesis-008", text: "Which mobile copper-containing carrier links the cytochrome b6f complex with photosystem I?",
      options: [{ key: "a", text: "Plastoquinone" }, { key: "b", text: "Pheophytin" }, { key: "c", text: "Plastocyanin" }, { key: "d", text: "Ferredoxin" }],
      answer: "c", explanation: "Plastocyanin is the mobile copper protein on the lumenal side that delivers electrons to PSI. Plastoquinone is a quinone carrier, pheophytin is a pigment acceptor and ferredoxin is an iron-sulfur protein downstream of PSI.", sectionId: "linear-electron-transport", source: { document: "quick-revision", page: 133 }, cognitive: "recall"
    },
    {
      id: "note-photosynthesis-009", text: "Water oxidation supplies 12 electrons to the linear photosynthetic chain. Using the balanced half-reaction, how many water and oxygen molecules are involved?",
      options: [{ key: "a", text: "3 water molecules consumed; 6 oxygen molecules formed" }, { key: "b", text: "6 water molecules consumed; 6 oxygen molecules formed" }, { key: "c", text: "6 water molecules consumed; 3 oxygen molecules formed" }, { key: "d", text: "12 water molecules consumed; 3 oxygen molecules formed" }],
      answer: "c", explanation: "The half-reaction consumes 2 H2O to release 4 electrons and 1 O2. Twelve electrons require three such batches: 6 H2O are consumed and 3 O2 formed, with 12 protons released into the lumen.", sectionId: "linear-electron-transport", source: { document: "biology", page: 290 }, cognitive: "application"
    },
    {
      id: "note-photosynthesis-010", text: "In a normally illuminated chloroplast, which proton movement is directly coupled to ATP formation?",
      options: [{ key: "a", text: "Stroma to lumen through Rubisco" }, { key: "b", text: "Lumen to stroma through plastocyanin" }, { key: "c", text: "Stroma to lumen through ferredoxin" }, { key: "d", text: "Lumen to stroma through ATP synthase" }],
      answer: "d", explanation: "The light reactions accumulate protons in the thylakoid lumen. Their downhill return through ATP synthase to the stroma drives phosphorylation of ADP. Rubisco, plastocyanin and ferredoxin do not form the ATP-synthase proton channel.", sectionId: "chemiosmosis-and-assimilatory-power", source: { document: "biology", page: 291 }, cognitive: "understanding"
    },
    {
      id: "note-photosynthesis-011", text: "A diagram labels its enzyme NADP reductase but writes NAD+ as the terminal acceptor and NADH as the product. Which repair makes the labels consistent?",
      options: [{ key: "a", text: "Use FAD as acceptor and FADH2 as product" }, { key: "b", text: "Use NADP+ as acceptor and NADPH as product" }, { key: "c", text: "Use ADP as acceptor and ATP as product" }, { key: "d", text: "Use oxygen as acceptor and water as product" }],
      answer: "b", explanation: "Ferredoxin-NADP+ reductase reduces NADP+ to NADPH at the end of standard linear photosynthetic electron flow. The NAD+/NADH pair belongs to a different coenzyme pool and conflicts with the enzyme identity in this drawing.", sectionId: "linear-electron-transport", source: { document: "biology", page: 291 }, cognitive: "understanding"
    },
    {
      id: "note-photosynthesis-012", text: "A chloroplast redirects PSI-derived electrons back into the inter-photosystem chain. Which net change is expected from that cyclic circuit itself?",
      options: [{ key: "a", text: "Additional ATP without net NADPH or oxygen production" }, { key: "b", text: "Additional NADPH without net ATP or oxygen production" }, { key: "c", text: "Additional oxygen without net ATP or NADPH production" }, { key: "d", text: "Additional glucose without net ATP or NADPH consumption" }],
      answer: "a", explanation: "Returning PSI electrons through the chain supports proton-gradient formation and ATP synthesis. Because the circuit returns the electrons rather than reducing NADP+ and does not require PSII water oxidation, it gives no net NADPH or O2 by itself.", sectionId: "cyclic-versus-linear-flow", source: { document: "biology", page: 291 }, cognitive: "understanding"
    },
    {
      id: "note-photosynthesis-013", text: "Red and far-red beams give photosynthetic rates of 4 and 1 units separately. With the same beams together the rate is 8 units. What does this demonstrate?",
      options: [{ key: "a", text: "Enhancement because 8 exceeds the separate-rate sum of 5" }, { key: "b", text: "Red drop because 8 exceeds the separate-rate sum of 5" }, { key: "c", text: "Compensation because 8 equals net zero carbon uptake" }, { key: "d", text: "Photoinhibition because 8 is smaller than both separate rates" }],
      answer: "a", explanation: "The expected sum from independent separate responses is 4 + 1 = 5 units. The combined rate of 8 exceeds that sum by 3 units, illustrating Emerson enhancement and cooperative excitation of the two photosystems, not addition of normalized quantum-yield ratios.", sectionId: "emerson-and-red-drop", source: { document: "biology", page: 294 }, cognitive: "application"
    },
    {
      id: "note-photosynthesis-014", text: "Three five-carbon RuBP molecules each fix one CO2 in the Calvin cycle. Which immediate stable-product inventory conserves all input carbon?",
      options: [{ key: "a", text: "Three molecules of three-carbon PGA" }, { key: "b", text: "Five molecules of three-carbon PGA" }, { key: "c", text: "Six molecules of three-carbon PGA" }, { key: "d", text: "Six molecules of five-carbon RuBP" }],
      answer: "c", explanation: "Three RuBP contain 15 carbons and three CO2 add 3, making 18 total. Six molecules of 3-PGA contain 6 times 3 = 18 carbons. Each unstable six-carbon addition product splits into two 3-PGA molecules.", sectionId: "calvin-steps-and-carbon-budget", source: { document: "biology", page: 292 }, cognitive: "application"
    },
    {
      id: "note-photosynthesis-015", text: "Six G3P molecules form after the reduction phase for three fixed CO2. Why can only one normally leave as net product while the cycle continues?",
      options: [{ key: "a", text: "The other five are all oxidized to five carbon dioxide molecules" }, { key: "b", text: "The other five form five new six-carbon glucose molecules" }, { key: "c", text: "The other five provide electrons for splitting five water molecules" }, { key: "d", text: "The other five regenerate the three five-carbon RuBP acceptors" }],
      answer: "d", explanation: "Five G3P contain 15 carbons, exactly the carbon needed to regenerate three RuBP. One three-carbon G3P is the net output from three newly fixed CO2; exporting all six would drain the acceptor pool and stop the cycle.", sectionId: "calvin-steps-and-carbon-budget", source: { document: "biology", page: 292 }, cognitive: "understanding"
    },
    {
      id: "note-photosynthesis-016", text: "Ignoring photorespiration and concentrating costs, what does the Calvin cycle require to supply four net G3P molecules?",
      options: [{ key: "a", text: "6 CO2, 18 ATP and 12 NADPH" }, { key: "b", text: "12 CO2, 36 ATP and 24 NADPH" }, { key: "c", text: "12 CO2, 24 ATP and 36 NADPH" }, { key: "d", text: "24 CO2, 36 ATP and 12 NADPH" }],
      answer: "b", explanation: "One net G3P requires 3 CO2, 9 ATP and 6 NADPH. Multiplying every quantity by four gives 12 CO2, 36 ATP and 24 NADPH. Four G3P contain 12 carbons, matching the twelve fixed carbon dioxide molecules.", sectionId: "calvin-steps-and-carbon-budget", source: { document: "biology", page: 292 }, cognitive: "application"
    },
    {
      id: "note-photosynthesis-017", text: "Which molecule is the five-carbon carbon-dioxide acceptor of the Calvin cycle?",
      options: [{ key: "a", text: "Phosphoenolpyruvate" }, { key: "b", text: "Oxaloacetate" }, { key: "c", text: "Glyceraldehyde-3-phosphate" }, { key: "d", text: "Ribulose-1,5-bisphosphate" }],
      answer: "d", explanation: "RuBP, ribulose-1,5-bisphosphate, is the five-carbon acceptor carboxylated by Rubisco. PEP is the three-carbon initial acceptor in C4/CAM fixation, OAA is a four-carbon product, and G3P is a reduced triose phosphate.", sectionId: "calvin-cycle-identity", source: { document: "biology", page: 292 }, cognitive: "recall"
    },
    {
      id: "note-photosynthesis-018", text: "Rubisco is exposed to increased oxygen relative to carbon dioxide. Which description correctly explains the change in reaction preference?",
      options: [{ key: "a", text: "The same enzyme increasingly oxygenates RuBP" }, { key: "b", text: "Rubisco is replaced by a new PEP-carboxylase protein" }, { key: "c", text: "RuBP becomes a four-carbon acceptor before fixation" }, { key: "d", text: "The enzyme starts producing ATP directly from oxygen" }],
      answer: "a", explanation: "Rubisco already possesses both carboxylase and oxygenase activities. A higher O2-to-CO2 ratio favours oxygenation relative to carboxylation; it does not convert Rubisco into an unrelated enzyme or change RuBP's five-carbon identity.", sectionId: "photorespiration-entry-and-cost", source: { document: "biology", page: 292 }, cognitive: "understanding"
    },
    {
      id: "note-photosynthesis-019", text: "The source mnemonic CPM gives which outward organelle order for the standard plant photorespiratory pathway?",
      options: [{ key: "a", text: "Chloroplast, mitochondrion, peroxisome" }, { key: "b", text: "Cytosol, peroxisome, mitochondrion" }, { key: "c", text: "Chloroplast, peroxisome, mitochondrion" }, { key: "d", text: "Cytosol, plastid envelope, mesophyll" }],
      answer: "c", explanation: "CPM recalls chloroplast, peroxisome and mitochondrion. The full salvage route subsequently returns through peroxisome to chloroplast, so remembering the outward order does not mean that glycerate returns directly from mitochondrion without further processing.", sectionId: "photorespiratory-organelle-pathway", source: { document: "quick-revision", page: 133 }, cognitive: "recall"
    },
    {
      id: "note-photosynthesis-020", text: "Two two-carbon glycine molecules produce one three-carbon serine during photorespiration. How many carbon dioxide molecules does the carbon balance permit in that conversion?",
      options: [{ key: "a", text: "Zero carbon dioxide molecules" }, { key: "b", text: "One carbon dioxide molecule" }, { key: "c", text: "Two carbon dioxide molecules" }, { key: "d", text: "Three carbon dioxide molecules" }],
      answer: "b", explanation: "The two glycines supply 2 times 2 = 4 carbons. Serine retains 3, leaving 1 carbon for one CO2. Writing two CO2 would make 3 + 2 = 5 product carbons and violate conservation, which is the explicit printed-source correction.", sectionId: "photorespiratory-organelle-pathway", source: { document: "quick-revision", page: 133 }, cognitive: "application"
    },
    {
      id: "note-photosynthesis-021", text: "Glycolate oxidation produces hydrogen peroxide in a leaf peroxisome. Which paired process limits accumulation of that peroxide?",
      options: [{ key: "a", text: "Rubisco reduces peroxide into RuBP" }, { key: "b", text: "Catalase converts peroxide to water and oxygen" }, { key: "c", text: "PEP carboxylase fixes peroxide into OAA" }, { key: "d", text: "ATP synthase converts peroxide into NADPH" }],
      answer: "b", explanation: "Peroxisomal catalase detoxifies H2O2 by the reaction 2 H2O2 to 2 H2O plus O2. This oxygen release is a peroxide-removal reaction, distinct from PSII water oxidation, and the other named enzymes have different substrates and roles.", sectionId: "photorespiratory-organelle-pathway", source: { document: "biology", page: 292 }, cognitive: "understanding"
    },
    {
      id: "note-photosynthesis-022", text: "A C3 leaf becomes water-stressed on a hot day and closes its stomata. Which immediate carbon-related consequence favours photorespiration?",
      options: [{ key: "a", text: "CO2 entry falls relative to the oxygen available to Rubisco" }, { key: "b", text: "Rubisco loses its ability to bind oxygen completely" }, { key: "c", text: "The leaf immediately acquires a new Kranz cell ring" }, { key: "d", text: "All stromal carbon fixation becomes independent of ATP" }],
      answer: "a", explanation: "Stomatal closure restricts CO2 diffusion into the leaf. With less CO2 relative to O2 at Rubisco, oxygenation becomes more competitive, especially at high temperature. Kranz anatomy is not produced immediately by stomatal closure, and energy requirements remain.", sectionId: "light-water-temperature-and-oxygen", source: { document: "biology", page: 294 }, cognitive: "application"
    },
    {
      id: "note-photosynthesis-023", text: "Which enzyme catalyses the initial conversion of PEP and inorganic carbon into oxaloacetate in a typical C4 mesophyll cell?",
      options: [{ key: "a", text: "Glycine decarboxylase" }, { key: "b", text: "Ferredoxin-NADP reductase" }, { key: "c", text: "Ribulose-bisphosphate oxygenase" }, { key: "d", text: "Phosphoenolpyruvate carboxylase" }],
      answer: "d", explanation: "PEP carboxylase uses bicarbonate derived from CO2 to carboxylate three-carbon PEP, yielding four-carbon OAA. Rubisco acts later in the Calvin cycle after concentrated CO2 is released near the bundle-sheath chloroplasts.", sectionId: "c4-anatomy-and-carboxylation", source: { document: "biology", page: 293 }, cognitive: "recall"
    },
    {
      id: "note-photosynthesis-024", text: "Why is the carbon shuttle from mesophyll to bundle sheath useful in the usual two-cell C4 arrangement?",
      options: [{ key: "a", text: "It removes the need for Rubisco in sugar synthesis" }, { key: "b", text: "It transfers all Calvin-cycle enzymes into the vacuole" }, { key: "c", text: "It releases concentrated CO2 near bundle-sheath Rubisco" }, { key: "d", text: "It replaces all photosynthetic electron flow with glycolysis" }],
      answer: "c", explanation: "Four-carbon compounds carry fixed inorganic carbon to bundle-sheath tissue, where decarboxylation raises the CO2 supply around Rubisco. This favours carboxylation and suppresses photorespiration while retaining the Calvin cycle and light reactions.", sectionId: "c4-shuttle-and-comparison", source: { document: "biology", page: 293 }, cognitive: "understanding"
    },
    {
      id: "note-photosynthesis-025", text: "Assume a C4 concentrating cycle costs two extra ATP equivalents per CO2. What total ATP-equivalent cost accompanies six fixed CO2 when the Calvin-cycle cost is included?",
      options: [{ key: "a", text: "12 ATP equivalents" }, { key: "b", text: "18 ATP equivalents" }, { key: "c", text: "24 ATP equivalents" }, { key: "d", text: "30 ATP equivalents" }],
      answer: "d", explanation: "Six CO2 require 18 ATP in the Calvin cycle. The concentrating cycle adds 6 times 2 = 12 ATP equivalents. The total is therefore 18 + 12 = 30, under the idealized assumptions given and without additional leakage or photorespiratory costs.", sectionId: "c4-shuttle-and-comparison", source: { document: "quick-revision", page: 133 }, cognitive: "application"
    },
    {
      id: "note-photosynthesis-026", text: "Which source-listed plant supplies the dicot counterexample to the claim that C4 photosynthesis occurs only in grasses?",
      options: [{ key: "a", text: "Tobacco" }, { key: "b", text: "Amaranthus" }, { key: "c", text: "Wheat" }, { key: "d", text: "Soybean" }],
      answer: "b", explanation: "Amaranthus is the dicot example explicitly listed beside the C4 grass examples. Tobacco, wheat and soybean are in the source's C3 list. The prevalence of C4 metabolism among grasses does not exclude eudicot lineages.", sectionId: "c4-shuttle-and-comparison", source: { document: "biology", page: 293 }, cognitive: "recall"
    },
    {
      id: "note-photosynthesis-027", text: "A succulent leaf takes up most external CO2 at night and has a larger vacuolar malic-acid pool at dawn than at dusk. Which pathway pattern best fits?",
      options: [{ key: "a", text: "CAM with nocturnal acid accumulation" }, { key: "b", text: "C3 fixation restricted to mitochondrial matrix" }, { key: "c", text: "C4 fixation requiring daytime-only stomatal opening" }, { key: "d", text: "Photorespiration with net glucose production" }],
      answer: "a", explanation: "CAM stores nocturnally fixed carbon as malic acid in vacuoles. The acid pool is built during the night and drawn down during the day to provide internal CO2 for the Calvin cycle while stomata are commonly closed.", sectionId: "cam-night-and-day", source: { document: "biology", page: 293 }, cognitive: "application"
    },
    {
      id: "note-photosynthesis-028", text: "A CAM plant's stomata are closed during the day. How can its Calvin cycle still receive carbon dioxide?",
      options: [{ key: "a", text: "ATP synthase converts oxygen directly into carbon dioxide" }, { key: "b", text: "Chlorophyll releases carbon atoms whenever it absorbs light" }, { key: "c", text: "Stored organic acids are decarboxylated inside the tissue" }, { key: "d", text: "The vacuole converts inorganic phosphate into carbon dioxide" }],
      answer: "c", explanation: "Night-time fixation stores carbon in organic acids, principally malate in the illustrated account. Daytime decarboxylation supplies internal CO2 to Rubisco, so daytime Calvin-cycle activity need not require simultaneous external CO2 uptake.", sectionId: "cam-night-and-day", source: { document: "biology", page: 293 }, cognitive: "understanding"
    },
    {
      id: "note-photosynthesis-029", text: "At the measured CO2 compensation point of a leaf, what is zero under the specified experimental conditions?",
      options: [{ key: "a", text: "The number of chlorophyll molecules" }, { key: "b", text: "The gross rate of water oxidation" }, { key: "c", text: "The net carbon-dioxide exchange" }, { key: "d", text: "The amount of respiratory enzyme" }],
      answer: "c", explanation: "Compensation means that photosynthetic CO2 uptake balances CO2 release, giving zero net exchange. Gross photosynthesis and respiration can both continue. It does not mean that pigments disappear or that no reaction can occur.", sectionId: "compensation-and-limiting-factors", source: { document: "biology", page: 293 }, cognitive: "understanding"
    },
    {
      id: "note-photosynthesis-030", text: "Increasing CO2 initially increases a leaf's photosynthetic rate, but further increases have no effect until light intensity is raised. What best explains the plateau?",
      options: [{ key: "a", text: "CO2 has ceased to be a carbon source" }, { key: "b", text: "The leaf has permanently become a CAM plant" }, { key: "c", text: "The increased CO2 has removed all chlorophyll" }, { key: "d", text: "Light has become limiting under those conditions" }],
      answer: "d", explanation: "The response to added light shows that illumination constrained the rate after CO2 ceased to be the immediate limiting supply. A plateau alone need not identify the next factor, but the stated light response discriminates it here.", sectionId: "compensation-and-limiting-factors", source: { document: "biology", page: 294 }, cognitive: "application"
    },
    {
      id: "note-photosynthesis-031", text: "Why is an observed light-saturation plateau insufficient evidence that chlorophyll has been destroyed?",
      options: [{ key: "a", text: "Chlorophyll never changes under excessive illumination" }, { key: "b", text: "Another process can limit the rate while pigments remain intact" }, { key: "c", text: "Photosynthesis must keep increasing at every light intensity" }, { key: "d", text: "Saturation proves that carbon fixation no longer needs enzymes" }],
      answer: "b", explanation: "At light saturation, additional photons may not increase carbon assimilation because CO2 supply or biochemical capacity is limiting. Photoinhibition can occur under excessive light, but a plateau by itself does not demonstrate pigment destruction.", sectionId: "light-water-temperature-and-oxygen", source: { document: "biology", page: 294 }, cognitive: "understanding"
    },
    {
      id: "note-photosynthesis-032", text: "Which gas change belongs to the Warburg effect discussed in the source corrections?",
      options: [{ key: "a", text: "Higher oxygen inhibits net photosynthesis in susceptible leaves" }, { key: "b", text: "Higher carbon dioxide always inhibits net photosynthesis in leaves" }, { key: "c", text: "Lower nitrogen directly eliminates both photosystem reaction centres" }, { key: "d", text: "Lower water vapour converts a C3 leaf into a C4 leaf" }],
      answer: "a", explanation: "The Warburg effect is inhibition of photosynthesis by oxygen, consistent with enhanced competition at Rubisco and photorespiration in susceptible systems. The handwritten CO2 label is explicitly corrected using the oxygen association in the printed source.", sectionId: "light-water-temperature-and-oxygen", source: { document: "biology", page: 294 }, cognitive: "recall"
    },
    {
      id: "note-photosynthesis-033", text: "In an idealized example, eight absorbed photons yield one O2 molecule. What is the molecular quantum yield, without interpreting it as a biomass-energy percentage?",
      options: [{ key: "a", text: "0.125 O2 molecule per absorbed photon" }, { key: "b", text: "0.25 O2 molecule per absorbed photon" }, { key: "c", text: "4 O2 molecules per absorbed photon" }, { key: "d", text: "8 O2 molecules per absorbed photon" }],
      answer: "a", explanation: "Quantum yield is product divided by absorbed photons: 1 divided by 8 equals 0.125 O2 per photon. The reciprocal, eight photons per O2, is a quantum requirement. Neither quantity alone gives the percentage of sunlight stored as biomass.", sectionId: "spectra-and-light-quality", source: { document: "quick-revision", page: 133 }, cognitive: "application"
    },
    {
      id: "note-photosynthesis-034", text: "Which source-listed technique can separate the differently coloured pigments of a leaf extract?",
      options: [{ key: "a", text: "A half-leaf carbon-dioxide exclusion test" }, { key: "b", text: "A light screen fitted over a destarched leaf" }, { key: "c", text: "Paper chromatography of the extract" }, { key: "d", text: "Counting oxygen bubbles from an intact shoot" }],
      answer: "c", explanation: "Paper chromatography separates components of a pigment mixture according to their partitioning and movement with the solvent. The other procedures investigate environmental requirements or oxygen evolution rather than separating extracted pigments.", sectionId: "pigment-families-and-colours", source: { document: "biology", page: 290 }, cognitive: "recall"
    },
    {
      id: "note-photosynthesis-035", text: "Which element pairing correctly distinguishes the centre of chlorophyll from a key metal in the oxygen-evolving complex?",
      options: [{ key: "a", text: "Chlorophyll: manganese; oxygen-evolving complex: magnesium" }, { key: "b", text: "Chlorophyll: copper; oxygen-evolving complex: iron" }, { key: "c", text: "Chlorophyll: iron; oxygen-evolving complex: copper" }, { key: "d", text: "Chlorophyll: magnesium; oxygen-evolving complex: manganese" }],
      answer: "d", explanation: "Chlorophyll's tetrapyrrole ring coordinates magnesium. Manganese participates in the catalytic water-oxidizing cluster of PSII, with calcium and chloride also important for the functioning complex. Similar names do not make the two metals interchangeable.", sectionId: "pigment-formulas-and-chlorophyll-structure", source: { document: "quick-revision", page: 131 }, cognitive: "recall"
    },
    {
      id: "note-photosynthesis-036", text: "Which pair constitutes the assimilatory power used in the source's carbon-assimilation account?",
      options: [{ key: "a", text: "ADP and NADP+" }, { key: "b", text: "ATP and NADPH" }, { key: "c", text: "Oxygen and carbon dioxide" }, { key: "d", text: "RuBP and oxaloacetate" }],
      answer: "b", explanation: "ATP provides energy and NADPH provides reducing equivalents for carbon assimilation. ADP and NADP+ are regenerated after those resources are used. RuBP and OAA are carbon intermediates, not the paired energy and reducing-power supply.", sectionId: "chemiosmosis-and-assimilatory-power", source: { document: "quick-revision", page: 132 }, cognitive: "recall"
    },
    {
      id: "note-photosynthesis-037", text: "A cyanobacterium's phycocyanin captures light that contributes to oxygenic photosynthesis. What is its direct antenna role?",
      options: [{ key: "a", text: "Catalysing cleavage of water at its pigment centre" }, { key: "b", text: "Carboxylating RuBP without any enzyme protein" }, { key: "c", text: "Replacing ATP synthase as the proton channel" }, { key: "d", text: "Transferring excitation energy towards a reaction centre" }],
      answer: "d", explanation: "Phycocyanin acts in a light-harvesting antenna and transfers excitation energy. The oxygen-evolving complex of PSII, not phycocyanin itself, oxidizes water. The source's direct photolysis wording conflates energy capture with the catalytic reaction.", sectionId: "pigment-families-and-colours", source: { document: "quick-revision", page: 131 }, cognitive: "understanding"
    },
    {
      id: "note-photosynthesis-038", text: "The historical association with demonstrating photophosphorylation in chloroplast preparations belongs to whom in the printed list?",
      options: [{ key: "a", text: "Arnon" }, { key: "b", text: "Ingenhousz" }, { key: "c", text: "de Saussure" }, { key: "d", text: "Ruben and Kamen" }],
      answer: "a", explanation: "Arnon is associated with light-driven ATP formation in chloroplast preparations. Ingenhousz is linked with the light requirement, de Saussure with quantitative carbon dioxide/water contributions, and Ruben and Kamen with oxygen-origin isotope evidence.", sectionId: "discovery-and-tracer-evidence", source: { document: "quick-revision", page: 132 }, cognitive: "recall"
    },
    {
      id: "note-photosynthesis-039", text: "A destarched leaf is illuminated while one portion receives CO2-depleted air and another receives ordinary air. Which requirement is isolated by this half-leaf comparison?",
      options: [{ key: "a", text: "The requirement for a night-time dark interval" }, { key: "b", text: "The requirement for different pigment colours" }, { key: "c", text: "The requirement for carbon dioxide availability" }, { key: "d", text: "The requirement for different oxygen-bubble sizes" }],
      answer: "c", explanation: "With illumination and other relevant conditions held suitable, the controlled difference is CO2 supply. Reduced new starch formation in the CO2-depleted part supports that requirement. Destarching helps exclude previously stored starch as the explanation.", sectionId: "classical-photosynthesis-experiments", source: { document: "quick-revision", page: 133 }, cognitive: "application"
    },
    {
      id: "note-photosynthesis-040", text: "Excited chlorophyll releases some excess energy as emitted light instead of passing it to photochemistry. Which term describes that release?",
      options: [{ key: "a", text: "Carboxylation" }, { key: "b", text: "Fluorescence" }, { key: "c", text: "Photophosphorylation" }, { key: "d", text: "Transamination" }],
      answer: "b", explanation: "Fluorescence is emission of light during loss of excitation energy. It is distinct from ATP formation, fixation of CO2 or transfer of an amino group. Resonance transfer between antenna pigments transfers excitation without necessarily emitting a photon.", sectionId: "photosystems-antennae-and-quantasomes", source: { document: "quick-revision", page: 133 }, cognitive: "understanding"
    }
  ]
};