window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["plant-anatomy"] = {
  id: "plant-anatomy",
  subject: "Botany",
  title: "Plant anatomy and tissues",
  sections: [
    {
      id: "anatomy-and-staining",
      title: "Plant anatomy, historical names and stains",
      sources: [{ document: "biology", page: 271 }],
      html: "<p>Plant anatomy concerns the internal structure and organization of plant organs. The introductory page associates N. Grew, Nehemiah Grew, with the title father of plant anatomy, and Nageli with father of modern plant anatomy. These are the source's historical honorifics, not exclusive scientific definitions or graded identification rules.</p>" +
        "<table><thead><tr><th>Stain in the notes</th><th>Recorded appearance</th></tr></thead><tbody><tr><td>Safranin</td><td>Red staining of lignified tissues, exemplified by sclerenchyma.</td></tr><tr><td>Haematoxylin</td><td>Blue or purple staining associated with cellulosic parenchyma in the source's preparation.</td></tr></tbody></table><p><strong>Source clarification:</strong> stain colour and selectivity depend on the formulation, mordant and preparation. Haematoxylin is not a cellulose-specific chemical test; a blue or purple result alone does not establish that a cell is parenchyma. The large unused portion of this introductory sheet contains no additional study content.</p>"
    },
    {
      id: "meristematic-cell-features",
      title: "Meristematic cells and their contents",
      sources: [{ document: "biology", page: 272 }],
      html: "<p>The first division of tissues in the handwritten chart is meristematic versus permanent. Meristematic cells are immature, relatively undifferentiated cells retaining the capacity for division. Their activity supplies new cells for growth.</p>" +
        "<table><thead><tr><th>Feature</th><th>Description and necessary qualification</th></tr></thead><tbody><tr><td>Cell wall</td><td>Thin, cellulosic primary wall; a heavily differentiated secondary wall is normally absent.</td></tr><tr><td>Cell shape and packing</td><td>Oval, rounded or polygonal cells, closely packed without conspicuous intercellular spaces.</td></tr><tr><td>Cytoplasm and nucleus</td><td>Dense cytoplasm and a conspicuous nucleus, rather than the large central vacuole of a mature storage cell.</td></tr><tr><td>Metabolism</td><td>High metabolic and respiratory activity in actively growing cells.</td></tr><tr><td>Food reserves</td><td>The source says absent because all food is converted to energy. Reserve accumulation is usually limited in an active meristem, but this is not literal absence of every reserve molecule.</td></tr><tr><td>Organelles listed as present</td><td>Mitochondria, proplastids and endoplasmic reticulum.</td></tr><tr><td>Organelles listed as absent</td><td>Golgi bodies, plastids and vacuoles in the source. This blanket list needs correction.</td></tr></tbody></table>" +
        "<p><strong>Source corrections:</strong> meristematic cells possess Golgi bodies, which participate in secretion and wall formation. They contain proplastids, themselves plastids; differentiated chloroplasts are often absent. Small vacuoles may occur even though a large central vacuole is generally lacking. The source's continuous state of cell division means retained proliferative ability, not that every meristem cell divides constantly; the quiescent centre is an explicit counterexample.</p>" +
        "<p>The cytoplasm is called dense crystalline colloidal, with an accompanying note that adding water increases density. <strong>Source correction:</strong> cytoplasm is not simply a crystalline mass, and adding water does not establish a universal increase in its density. Dense cytoplasm here describes its relatively high content of cellular material, not a tested water-addition law.</p>"
    },
    {
      id: "meristem-origin-and-dedifferentiation",
      title: "Promeristem, primary meristem and secondary meristem",
      sources: [{ document: "biology", page: 272 }, { document: "biology", page: 279 }],
      html: "<p>The origin chart distinguishes promeristem, primary meristem and secondary meristem. Promeristem is primordial meristematic tissue of embryonic origin, associated with the embryo and the earliest growing regions. It supplies primary meristematic derivatives and, through differentiation, primary permanent tissues.</p>" +
        "<ol><li>Promeristem develops into primary meristem. Root and shoot apices are the named primary growth regions.</li><li>Primary meristem differentiates into primary permanent tissue.</li><li>Some living permanent cells regain division capacity by dedifferentiation, establishing a secondary meristem.</li><li>Products of the secondary meristem differentiate into secondary permanent tissues.</li></ol>" +
        "<p>The handwritten examples of secondary meristem are cork cambium, vascular cambium and especially interfascicular vascular cambium. Wound healing is linked to secondary meristem: living cells near an injury can resume division and produce reparative tissue.</p><p><strong>Source clarification:</strong> vascular cambium is not uniformly secondary in developmental origin. In a typical dicot stem, fascicular cambium is retained from the primary procambium, whereas interfascicular cambium arises through renewed division of intervening parenchyma. Their union forms the continuous cambial ring shown on p.279. Origin, position and the production of secondary tissue are related classifications, not interchangeable definitions.</p>"
    },
    {
      id: "meristem-position-and-derivatives",
      title: "Meristem positions and primary tissue systems",
      sources: [{ document: "biology", page: 272 }],
      html: "<table><thead><tr><th>Position</th><th>Location and function</th></tr></thead><tbody><tr><td>Apical meristem</td><td>At the shoot tip and subterminally in the root, immediately behind the protective root cap. It contributes to primary growth in length.</td></tr><tr><td>Intercalary meristem</td><td>Between differentiated permanent tissues; a retained portion of an apical meristem. The source emphasizes its relatively short-lived activity, subsequent differentiation and internode elongation, which increases shoot height.</td></tr><tr><td>Lateral meristem</td><td>Cambial tissue along the sides of the axis. Vascular and cork cambia contribute to secondary growth and increased diameter or girth.</td></tr></tbody></table>" +
        "<p>The two small apical sketches distinguish a root meristem protected behind a cap from a shoot meristem at the terminal growing point. The quiescent centre is located in the root apex and has relatively low mitotic activity. The separate source claim that apical meristem cells always have the highest concentration of salts lacks a specified solute, species or comparison; it is retained as an unverified claim, not a scored fact.</p>" +
        "<table><thead><tr><th>Functional category</th><th>Derivatives in the source chart</th></tr></thead><tbody><tr><td>Protoderm</td><td>Outermost primary meristematic cells, giving rise to the epidermis.</td></tr><tr><td>Procambium</td><td>Internal vascular precursor, giving rise to primary xylem and primary phloem, with residual cambium in open bundles.</td></tr><tr><td>Ground meristem</td><td>Ground tissues including hypodermis, cortex, endodermis, pith and primary medullary regions. The source additionally places pericycle in this list.</td></tr></tbody></table><p><strong>Source correction:</strong> pericycle, especially in roots, is commonly derived from the procambial region, so it should not be assigned universally to ground meristem. Procambium means a vascular precursor, not every cell that happens to be innermost.</p>"
    },
    {
      id: "permanent-tissues-and-parenchyma",
      title: "Permanent tissue classification and parenchyma",
      sources: [{ document: "biology", page: 273 }, { document: "biology", page: 278 }, { document: "quick-revision", page: 120 }],
      html: "<p>The permanent-tissue chart has three branches. Simple tissues include parenchyma, collenchyma and sclerenchyma; the last divides into fibres and sclereids. Complex tissues are xylem and phloem. Secretory tissues are divided into glandular and laticiferous types. Simple tissue is dominated by one basic cell type, while a complex tissue combines different cell types performing related functions.</p>" +
        "<p>Parenchyma develops from meristematic derivatives. Typical cells are living, have thin cellulosic walls and large vacuoles, and function prominently in storage. The notes call it fundamental tissue and the most common ground or packing tissue. Locations listed are cortex, pericycle, pith, medullary rays, leaf mesophyll and flowers.</p>" +
        "<p>The chart lists prosenchyma, aerenchyma, chlorenchyma with palisade and spongy forms, mucilage parenchyma and idioblastic parenchyma. An idioblast is a specialized cell distinguishable from neighbouring cells; the chart gives no separate named example for this last category.</p><p><strong>Source clarification:</strong> calling parenchyma fundamental does not mean that every mature plant tissue must develop from an already differentiated parenchyma cell. The upper-right prompt on p.278, packing tissue in fern is, has no answer or further context. Its next line explicitly gives parenchyma as packing tissue in plants; that general answer is preserved without inventing a missing fern-specific response.</p>"
    },
    {
      id: "parenchyma-specializations",
      title: "Water storage, air spaces, prosenchyma and chlorenchyma",
      sources: [{ document: "biology", page: 273 }, { document: "quick-revision", page: 119 }],
      html: "<table><thead><tr><th>Form</th><th>Characters, function and examples</th></tr></thead><tbody><tr><td>Mucilage parenchyma</td><td>Stores water associated with mucilage in succulent xerophytes. The handwritten leaf-succulent examples are Aloe vera and Agave.</td></tr><tr><td>Aerenchyma</td><td>Parenchyma with conspicuous air chambers or connected intercellular spaces, aiding internal aeration and often flotation. Hydrophyte examples: Pistia and Eichhornia.</td></tr><tr><td>Stellate parenchyma</td><td>Star-like cells leaving air spaces; compared with aerenchyma and associated with aeration. Source examples: banana and Canna.</td></tr><tr><td>Prosenchyma</td><td>Elongated, taper-ended, compactly arranged cells associated with mechanical strength and rigidity. The source additionally records lines of lignin in the walls and starch contents, with Bougainvillea stems and root pericycle as examples.</td></tr><tr><td>Chlorenchyma</td><td>Parenchyma containing chloroplasts. Present in leaves, young green stems and green fruits; photosynthetic mesophyll is the major leaf example.</td></tr></tbody></table>" +
        "<p>In the source comparison, spongy mesophyll has large air spaces, with gaseous exchange emphasized as its primary function and photosynthesis as an additional function. Palisade mesophyll has elongated, parallel, closely packed cells, with photosynthesis emphasized. Both remain photosynthetic tissues; the ordering of functions is a teaching emphasis, not an exclusive division of labour.</p><p><strong>Source clarification:</strong> prosenchyma is a descriptive historical term for elongated cells, not a guarantee of a particular lignin pattern or starch content in every plant or organ. Those extra features are retained as the source's examples, not used as universal diagnostic MCQ answers.</p>"
    },
    {
      id: "collenchyma-and-flexible-support",
      title: "Collenchyma and living mechanical support",
      sources: [{ document: "biology", page: 273 }, { document: "quick-revision", page: 119 }],
      html: "<p>Collenchyma is living mechanical tissue with thickened primary walls containing cellulose, pectin and hemicellulose. The pectin-rich walls provide tensile support while allowing flexibility and elasticity in growing organs. The printed cue <strong>CoP</strong> links collenchyma with pectin.</p><p>The printed locations are herbaceous dicot stems and leaf midribs; roots and monocots are listed as lacking it. The handwritten location is between the cortex of stem and endodermis. <strong>Source correction:</strong> the usual prominent collenchyma is subepidermal, forming the hypodermis or outer cortex of young dicot shoots, and also occurs in petioles and along leaf veins. It is generally absent in ordinary roots and most monocots, but the source's only and absent statements should not be universalized.</p>" +
        "<table><thead><tr><th>Type</th><th>Wall pattern and source examples</th></tr></thead><tbody><tr><td>Angular</td><td>Thickening concentrated at cell corners; tomato and Datura.</td></tr><tr><td>Lamellate or plate</td><td>Thickening mainly on tangential walls, giving a layered appearance; sunflower in the notes.</td></tr><tr><td>Lacunate or lacunar</td><td>Thickening associated with the boundaries of intercellular spaces; Cucurbitaceae in the notes.</td></tr></tbody></table>" +
        "<p>The source connects water absorption by pectin with mucilage and an expansion of 200%. The hydration idea is retained, but no starting dimension, measured quantity or experimental condition is given for 200%, so that number is unresolved and ungraded. Some collenchyma cells contain chloroplasts. <strong>Source correction:</strong> the phrase chloroplast for food storage confuses photosynthesis with a primary storage role; chloroplasts chiefly support photosynthetic carbon assimilation, although transient starch can accumulate within them.</p>"
    },
    {
      id: "sclerenchyma-fibres-and-sclereids",
      title: "Sclerenchyma, fibres and sclereids",
      sources: [{ document: "biology", page: 273 }, { document: "quick-revision", page: 119 }],
      html: "<p>Sclerenchyma provides stiffness, mechanical support and resistance to bending, tearing and shearing. Typical mature cells are dead, lack protoplasm and have thick lignified secondary walls. The printed locations include monocot-stem hypodermis and supporting cells associated with xylem, phloem and pericycle.</p><p><strong>Source correction:</strong> lignin is a structural wall polymer, not itself a plant tissue. The source descriptions hardest plant tissue and hardest plant substance are imprecise superlatives; lignification increases rigidity, but does not define a universal hardness ranking or alone explain every developmental cell death.</p>" +
        "<table><thead><tr><th>Source comparison</th><th>Fibres</th><th>Sclereids</th></tr></thead><tbody><tr><td>Shape</td><td>Long, spindle-shaped cells with tapering ends.</td><td>Shorter or irregular cells; oval, cylindrical, spherical, dumbbell-shaped or branched forms are listed.</td></tr><tr><td>Wall and lumen</td><td>Relatively thinner lignified wall and wider lumen in the source's comparison.</td><td>Relatively thicker lignified wall and narrower lumen in the illustrated stone cell.</td></tr><tr><td>Pits</td><td>Unbranched pit canals; simple, oblique and bordered pits are all listed.</td><td>Simple pits with branched or unbranched canals.</td></tr></tbody></table>" +
        "<p>The fibre figure labels the lumen, secondary wall, pits, primary cell wall and middle lamella. The sclereid figure labels a thick cell wall, radiating pit canals and the residual central lumen. These drawings explain how extensive wall deposition reduces the internal space. Relative wall thickness and lumen width vary, so the comparison is not an absolute distinction between all fibres and all sclereids.</p>" +
        "<ul><li>Ramie fibres are highlighted as exceptionally long plant cells; the source calls them the longest. They are long individual fibres, not a chain of vessel elements.</li><li>Stone cells occur in the guava-seed and pear-pulp examples. They account for gritty texture in pear and the source's guava comparison.</li><li>Hard protective sclerenchyma occurs in the endocarp or shell examples coconut, mango and walnut.</li><li>The notes list mature tea leaves and lotus petioles under astrosclereids, or star cells. Branched supporting sclereids must be distinguished from long unbranched fibres.</li><li>Sclereids form protective coverings in legume seeds; the source's epidermal covering of legume entry refers to such specialized seed-coat cells.</li></ul>"
    },
    {
      id: "xylem-components-and-conduction",
      title: "Xylem, tracheids, vessels and living parenchyma",
      sources: [{ document: "biology", page: 274 }, { document: "quick-revision", page: 119 }],
      html: "<p>Xylem conducts sap containing water, H<sub>2</sub>O, and mineral ions and contributes mechanical strength. Root-to-leaf movement is the usual emphasis of the notes. Secondary xylem is wood. Protoxylem is the first-formed primary xylem and usually has smaller conducting elements; metaxylem is later formed and usually has larger elements.</p><p>The older functional term <strong>hadrome</strong> denotes the conducting tracheary elements, vessels and tracheids. The printed <strong>XY had TV</strong> cue links xylem, hadrome, tracheids and vessels.</p>" +
        "<table><thead><tr><th>Character</th><th>Tracheids</th><th>Vessel elements</th></tr></thead><tbody><tr><td>Shape and lumen</td><td>Generally elongated, narrow-lumened cells with tapering ends.</td><td>Usually wider-lumened elements arranged end to end into a vessel.</td></tr><tr><td>End walls</td><td>No perforation plate; end walls remain intact.</td><td>Perforations form by loss of wall material at the end-wall connection.</td></tr><tr><td>Water pathway</td><td>Water passes through pits between adjacent cells.</td><td>Axial flow passes through perforations; lateral exchange occurs through pits.</td></tr><tr><td>Source wall comparison</td><td>Thick walls and mechanical support are emphasized.</td><td>Relatively thinner walls and a wider lumen are emphasized, but walls are still reinforced.</td></tr><tr><td>Traditional description</td><td>Primitive conducting element, occurring across pteridophytes, gymnosperms and angiosperms.</td><td>Advanced conducting element in the teaching comparison.</td></tr></tbody></table>" +
        "<p><strong>Source correction:</strong> the sketches label tracheids axial and vessels radial. They illustrate pit-mediated pathways, not a rule that vessels fail to carry water along the axis. Both contribute to longitudinal water transport. Primitive and advanced here are historical structural comparisons, not a ranking of entire living plants.</p>" +
        "<p>Xylem parenchyma, or wood parenchyma, is the living component emphasized in the standard four-element account. It stores food, particularly starch, and assists redistribution and lateral movement of sap constituents. Thus xylem contains living cells; it is not entirely living tissue. Xylem or wood fibres are thick-walled supporting sclerenchyma, typically dead at maturity, especially emphasized in woody dicots. The conventional only living element rule describes this basic teaching classification; some specialized wood fibres can also retain living contents.</p>"
    },
    {
      id: "vessel-patterns-exceptions-and-tyloses",
      title: "Wall thickening, vessel exceptions and tyloses",
      sources: [{ document: "biology", page: 274 }, { document: "quick-revision", page: 119 }],
      html: "<table><thead><tr><th>Wall pattern</th><th>Meaning of the illustrated reinforcement</th></tr></thead><tbody><tr><td>Annular</td><td>Separate lignified rings.</td></tr><tr><td>Spiral or helical</td><td>Coiled bands running along the element.</td></tr><tr><td>Scalariform</td><td>Ladder-like bars.</td></tr><tr><td>Reticulate</td><td>A network of connected thickenings.</td></tr><tr><td>Pitted</td><td>Extensive secondary wall interrupted by pits; the illustration shows both simple-looking and bordered pit outlines.</td></tr></tbody></table>" +
        "<p>The source's advancement arrow orders pitted, reticulate, scalariform, spiral and annular from more extensive to less extensive wall coverage. This is retained as a structural teaching sequence, not a mandatory developmental transformation through all five forms. Annular and helical reinforcement is particularly compatible with elongation in young organs.</p>" +
        "<p>The printed claim that vessels occur only in angiosperms is contradicted by the handwritten exception list. <strong>Source correction:</strong> Gnetum, Ephedra and Welwitschia, recalled by <strong>GEW</strong>, are vessel-bearing gymnosperms. Tracheids remain important in these plants and in other vascular groups.</p>" +
        "<p>The handwritten vessel-less angiosperm list gives Winteraceae, Tetracentraceae, Trochodendraceae, Amborellaceae and Chloranthaceae. These are retained as a traditional source list, with spelling regularized. Family boundaries and reports of vessel-like elements need care: Tetracentron is now commonly included in Trochodendraceae, and Chloranthaceae is not uniformly vessel-less. The source's pteridophyte mnemonic <strong>SEM</strong> lists Selaginella, Equisetum and Marsilea as vessel exceptions. No species, organ or anatomical criterion is supplied for those three entries, so they are not graded as universal genus traits.</p>" +
        "<p>The page ranks Eucalyptus first and oak second for longest vessels, without species, measurements or distinction between a whole vessel and one vessel element. That ranking remains unresolved. A separate box calls Eucalyptus an angiosperm largest-tree example, Sequoia the tallest genus, and Eucalyptus regnans the tallest species. <strong>Source correction:</strong> height and trunk volume are different records. Sequoia sempervirens includes the tallest documented living trees; Eucalyptus regnans is an exceptionally tall flowering tree, not the tallest living tree species overall. Sequoiadendron giganteum is the familiar giant-tree example for trunk volume. None of the unspecific source rankings is used as a question key.</p>" +
        "<p><strong>Tyloses</strong> are balloon-like outgrowths of adjacent living parenchyma through pits into conducting lumina, characteristically vessels. They can obstruct flow, including during heartwood formation or responses to injury. The printed cue <strong>TYLoses / XYLem</strong> associates the words. The source also mentions tracheids, but its phrase vessels are generally blocked should not imply that every healthy functioning vessel is plugged.</p>"
    },
    {
      id: "phloem-and-vascular-comparison",
      title: "Phloem, sieve-tube plugs and the xylem comparison",
      sources: [{ document: "quick-revision", page: 119 }, { document: "quick-revision", page: 120 }],
      html: "<p>Phloem transports assimilated organic food materials from sources to sinks. The notes emphasize living, generally thin-walled conducting cells and the functional term <strong>leptome</strong>. Companion cells associated with sieve-tube elements are characteristic of angiosperms. Phloem fibres are the dead supporting component in the standard tissue account, not the food-conducting cells.</p>" +
        "<table><thead><tr><th>Comparison</th><th>Xylem</th><th>Phloem</th></tr></thead><tbody><tr><td>Older functional name</td><td>Hadrome.</td><td>Leptome.</td></tr><tr><td>Secondary tissue</td><td>Wood, secondary xylem.</td><td>Bast, secondary phloem; bast fibres are its fibres.</td></tr><tr><td>Transported material</td><td>Water and mineral ions.</td><td>Organic assimilates, including sugars.</td></tr><tr><td>Source direction label</td><td>Unidirectional, emphasizing root-to-shoot flow.</td><td>Bidirectional, describing different source-to-sink paths.</td></tr><tr><td>Occlusion example</td><td>Tyloses in conducting lumina.</td><td>Callose at sieve pores and P-protein plugs.</td></tr></tbody></table>" +
        "<p>P-protein occurs in sieve-tube elements and can aggregate into the source's slime plugs. Callose deposition can narrow or block sieve-plate pores. <strong>Source correction:</strong> callose is a beta-1,3-linked glucan, a polymer of glucose, not a deposit of free beta-D-glucose molecules. Protein plugging and callose deposition are distinct processes.</p>" +
        "<p><strong>Source clarification:</strong> phloem can move material upward in one path and downward in another because sink positions differ; this does not mean simultaneous opposite bulk streams within one sieve tube. Xylem flow is driven by water-potential gradients, so unidirectional is a usual whole-plant teaching pattern, not an exceptionless physical law. The mnemonic <strong>BP</strong> links bast with phloem. Calling secondary phloem only phloem fibres would omit its other cell types.</p>"
    },
    {
      id: "secretory-cavities-and-rubber",
      title: "Secretory spaces, latex and rubber-source examples",
      sources: [{ document: "quick-revision", page: 119 }, { document: "quick-revision", page: 120 }, { document: "biology", page: 273 }],
      html: "<p>The permanent-tissue chart includes glandular and laticiferous secretory tissues. Laticiferous tissue contains latex; secretory cavities and ducts differ in how their spaces originate.</p>" +
        "<table><thead><tr><th>Space</th><th>Formation and entries in the source</th></tr></thead><tbody><tr><td>Lysigenous cavity</td><td>Space produced through cell disintegration or lysis. The <strong>CELL lysis</strong> cue records C for Citrus oil cavity, E for Eucalyptus and L for lysigenous.</td></tr><tr><td>Schizogenous cavity</td><td>Space produced by separation of cells. Pinus resin ducts and Cycas mucilage ducts are the examples, with <strong>RMS</strong> recalling resin, mucilage and schizogenous.</td></tr><tr><td>Schizolysigenous cavity</td><td>Space formation involving separation and breakdown. The source places the maize-stem protoxylem cavity here and calls it a water-storage space.</td></tr></tbody></table>" +
        "<p><strong>Source qualifications:</strong> developmental accounts of Citrus and Eucalyptus secretory cavities differ with organ, species and interpretation, so the printed lysigenous pairing is preserved as a traditional claim rather than a universal graded fact. A maize protoxylem lacuna is produced as early tracheary elements break down or are stretched during growth. It is a vascular lacuna, not a secretory gland, and water storage is not its defining anatomical criterion.</p>" +
        "<table><thead><tr><th>Rubber name in the notes</th><th>Plant source</th></tr></thead><tbody><tr><td>Para or natural rubber</td><td>Hevea brasiliensis.</td></tr><tr><td>Indian rubber</td><td>Ficus elastica.</td></tr><tr><td>Panama rubber</td><td>Castilla elastica.</td></tr><tr><td>Ceara rubber, printed Cera</td><td>Manihot glaziovii.</td></tr></tbody></table>"
    },
    {
      id: "vascular-bundle-types",
      title: "Radial, conjoint and concentric vascular bundles",
      sources: [{ document: "quick-revision", page: 119 }, { document: "quick-revision", page: 120 }, { document: "biology", page: 276 }],
      html: "<p>In a radial arrangement, xylem and phloem occupy separate alternating radii. The sketch shows separate xylem and phloem groups around the root axis. Both dicot and monocot roots are the source examples; the printed dicot comparison gives two to six xylem poles or alternating vascular groups.</p>" +
        "<p>In a conjoint bundle, xylem and phloem lie on the same radius within one bundle, commonly in stems. A collateral bundle has outer phloem and inner xylem. An open collateral bundle retains cambium between them, as in a typical dicot stem. A closed collateral bundle lacks that cambium, as in a typical monocot stem. The sketch's red strip is the cambium, not another phloem layer.</p>" +
        "<p>A bicollateral bundle has xylem between outer and inner phloem. The source describes these as open and gives Cucurbitaceae, especially Cucurbita, and Solanaceae. The mnemonic <strong>Bi CuCu double</strong> recalls the two phloem positions in Cucurbita.</p>" +
        "<table><thead><tr><th>Concentric type</th><th>Centre, surrounding tissue and source examples</th></tr></thead><tbody><tr><td>Amphivasal or leptocentric</td><td>Phloem at the centre, surrounded by xylem. Dracaena, the dragon plant, Acorus and Yucca are the printed examples.</td></tr><tr><td>Amphicribral or hadrocentric</td><td>Xylem at the centre, surrounded by phloem. Ferns, Lycopodium and Selaginella are listed; the handwritten column also mentions aquatic angiosperms without a species.</td></tr></tbody></table>" +
        "<p><strong>Source correction:</strong> the two concentric headings above the p.276 drawings are interchanged. The drawing with central phloem belongs to amphivasal/leptocentric, while the one with central xylem belongs to amphicribral/hadrocentric. The printed p.120 wording gives the correct tissue order. The cues <strong>PHloem vitra</strong>, phloem inside, and <strong>PHloem bahira</strong>, phloem outside, preserve the source's memory aid; hadrocentric links hadrome with the centre.</p>" +
        "<p>The printed note calls amphivasal bundles closed and uses <strong>DAY</strong> for Dracaena, Acorus and Yucca. It also repeats DAY as examples of anomalous secondary growth. <strong>Source qualification:</strong> Dracaena and Yucca are standard examples of unusual monocot thickening, but inclusion in the amphivasal list alone does not establish the same growth mechanism in Acorus. The Acorus secondary-growth assertion remains an unverified source claim, not a question key. Likewise, the fern and aquatic-plant list is not a claim that every species has the identical whole-stele configuration.</p>"
    },
    {
      id: "primary-xylem-arrangement",
      title: "Endarch, exarch, mesarch and centrarch xylem",
      sources: [{ document: "quick-revision", page: 120 }, { document: "biology", page: 276 }],
      html: "<table><thead><tr><th>Arrangement</th><th>Protoxylem position and maturation</th></tr></thead><tbody><tr><td>Endarch</td><td>Protoxylem lies towards the centre or pith, with metaxylem farther outward. Maturation is centrifugal. Typical dicot and monocot stems are the source examples.</td></tr><tr><td>Exarch</td><td>Protoxylem lies towards the periphery, with later metaxylem inward. Maturation is centripetal. Typical dicot and monocot roots are the source examples.</td></tr><tr><td>Mesarch</td><td>Protoxylem lies within the xylem strand, with later xylem on more than one side.</td></tr><tr><td>Centrarch</td><td>A central protoxylem region is surrounded by later xylem, as shown by the compact cluster drawing.</td></tr></tbody></table>" +
        "<p>The source sketches use smaller cells for early protoxylem and larger cells for later metaxylem. Endarch and exarch refer to positions in a strand relative to the organ centre; centrarch depicts a centrally initiated xylem mass and is not simply another word for every endarch stem bundle.</p><p>The printed <strong>Ex = outside</strong> cue compares exarch with exobiology, the study of life beyond Earth. In the notes this is only a word association for the peripheral protoxylem; centripetal and centrifugal describe the direction of xylem differentiation, not necessarily the direction of sap flow.</p>"
    },
    {
      id: "epidermis-bulliform-and-hairs",
      title: "Epidermis, bulliform cells, velamen and hairs",
      sources: [{ document: "biology", page: 276 }],
      html: "<p>The epidermal tissue system includes epidermis, stomata and epidermal outgrowths. The ordinary epidermis is a continuous outer layer, usually one cell thick. Its cells are generally living. A cuticle covers exposed shoot epidermis, while the absorbing root epidermis or epiblema normally lacks a substantial cuticle.</p><p>Ordinary epidermal cells usually lack chloroplasts; guard cells are the prominent exception. The source additionally lists shade plants, hydrophytes and some ferns as situations in which other epidermal cells may contain chloroplasts, not as a rule that every member of those groups does.</p>" +
        "<ul><li><strong>Bulliform or motor cells:</strong> enlarged epidermal cells in some monocot leaves, especially grasses. The notes call them hygroscopic. Loss of turgor during water shortage and high transpiration is associated with leaf rolling; recovery of hydration assists unrolling.</li><li><strong>Velamen:</strong> a multilayered covering of aerial roots, with cells dead at maturity. Orchids, particularly Vanda, are the named examples. This is a specific exception to the simple single-layered epidermis description.</li><li><strong>Root hairs:</strong> unicellular outgrowths of root epidermal cells, increasing the absorbing surface.</li><li><strong>Trichomes:</strong> shoot hairs may be multicellular, branched or unbranched, and soft or stiff as listed. They provide protection and can reduce excessive water loss.</li></ul><p><strong>Source clarification:</strong> not every trichome is multicellular, and the final phrase protection and excess water loss means protection against excessive loss, not that hairs are formed in order to increase it.</p>"
    },
    {
      id: "stomata-shape-and-distribution",
      title: "Guard cells, stomatal opening and leaf-surface distribution",
      sources: [{ document: "biology", page: 276 }, { document: "biology", page: 277 }, { document: "quick-revision", page: 120 }],
      html: "<p>A stoma is an epidermal pore bordered by two guard cells. Specialized neighbouring cells, when present, are subsidiary or accessory cells. Guard cells contain chloroplasts, and changes in their turgor alter the aperture: the source contrasts turgid/open with flaccid/closed.</p><p><strong>Source correction:</strong> the handwritten thick inner cuticle and thin outer cuticle should refer chiefly to differential guard-cell wall thickening and extensibility. In the familiar kidney-shaped example, the pore-facing wall is thicker and less extensible than the outer wall. The stomatal pore itself is not kidney-shaped; that descriptor concerns the guard cells.</p>" +
        "<table><thead><tr><th>Term or shape</th><th>Meaning and source examples</th></tr></thead><tbody><tr><td>Kidney- or bean-shaped guard cells</td><td>The common dicot example and many other plants.</td></tr><tr><td>Dumbbell-shaped guard cells</td><td>The grass-type monocot example; illustrated as expanded ends joined by a narrow middle.</td></tr><tr><td>Amphistomatic</td><td>Stomata on both leaf surfaces; associated with the source's monocot/isobilateral example.</td></tr><tr><td>Hypostomatic</td><td>Stomata restricted mainly or entirely to the lower surface; associated with the source's dorsiventral dicot example.</td></tr><tr><td>Epistomatic</td><td>Stomata on the upper surface, illustrated by floating hydrophyte leaves.</td></tr><tr><td>Absent stomata</td><td>Typical submerged hydrophyte leaves, algae and fungi in the source list.</td></tr><tr><td>Sunken stomata</td><td>Pores recessed below the general surface in many xerophytes.</td></tr></tbody></table>" +
        "<p><strong>Source corrections:</strong> the printed monocot/dumbbell versus dicot/kidney contrast describes familiar examples, not every monocot and dicot. Stomatal distribution is not fixed by guard-cell shape. The handwritten shrunken type in xerophytes means <em>sunken</em> stomata, not merely temporarily shrunken guard cells. Surface distribution and density depend on leaf type and habitat; amphistomatic does not require exactly equal counts on both faces.</p>"
    },
    {
      id: "lateral-roots-and-shoot-branches",
      title: "Endogenous lateral roots and exogenous shoot branches",
      sources: [{ document: "biology", page: 276 }, { document: "biology", page: 277 }],
      html: "<p>The lateral-root sequence shows a primordium arising internally, growing through the cortex and emerging through the surface while retaining connection with the parent vascular system. Lateral roots are therefore endogenous. Their origin is the pericycle, commonly opposite the protoxylem poles in the standard dicot-root example.</p><p><strong>Source correction:</strong> seat is in protoxylem does not mean that mature protoxylem vessel cells divide to produce the root. The initiating cells are pericycle cells at a position related to a protoxylem pole.</p><p>The second sequence shows an outwardly initiated shoot branch expanding from a superficial bud region. The notes call it exogenous, from cortex, with a seat in the outer cortex. <strong>Source clarification:</strong> ordinary shoot branches develop from axillary meristems associated with the shoot apex and leaf axils; they should not be defined as outgrowths of any arbitrary mature cortical cell. The intended comparison is a superficial bud origin versus a lateral root's internal pericycle origin.</p>"
    },
    {
      id: "ground-tissue-and-pericycle",
      title: "Cortex, pericycle, pith and medullary rays",
      sources: [{ document: "biology", page: 277 }, { document: "biology", page: 273 }],
      html: "<p>The ground-tissue page uses the historical histogen terms <strong>periblem</strong>, giving cortex, and <strong>plerome</strong>, giving stele. Cortex lies outside the endodermal boundary, and the stele lies inside it. <strong>Source clarification:</strong> the endodermis is the innermost cortical layer; the stele includes vascular tissues and is not wholly ground tissue merely because it is drawn beneath that heading.</p>" +
        "<table><thead><tr><th>Region</th><th>Characters and function</th></tr></thead><tbody><tr><td>Hypodermis</td><td>Outermost cortical tissue beneath the epidermis. The herbaceous dicot example is collenchymatous; the typical monocot stem example is sclerenchymatous.</td></tr><tr><td>Cortex</td><td>Predominantly parenchymatous, often with conspicuous intercellular spaces. Its innermost layer is the endodermis.</td></tr><tr><td>Pericycle</td><td>A single or a few layers internal to the endodermis, parenchymatous or partly sclerenchymatous according to organ. It initiates lateral roots in the ordinary root account.</td></tr><tr><td>Pith or medulla</td><td>Parenchymatous central region of the axis, associated with storage.</td></tr><tr><td>Medullary rays</td><td>Radial parenchymatous regions, associated with storage and lateral transport rather than only axial conduction.</td></tr></tbody></table>" +
        "<p>The sunflower pericycle is described as mixed: thin-walled cells store food, while thick-walled patches provide mechanical support. The source says pericycle occurs in most roots except parasitic and aquatic forms. Such reduction or modification is species-dependent; the exception must not be applied to every aquatic or parasitic root.</p><p>Pith is distinct in the source's monocot root and dicot stem, but small or indistinct in its dicot root. The phrase scattered in monocot stem refers to undifferentiated ground tissue around scattered bundles; it does not establish many separate piths or a conventional system of medullary rays. Storage and lateral transport by parenchyma are distinct from the support furnished by the thick-walled components.</p>"
    },
    {
      id: "endodermis-and-casparian-strips",
      title: "Endodermis, Casparian strips and passage cells",
      sources: [{ document: "biology", page: 277 }],
      html: "<p>The endodermis is described as one layer of barrel-shaped, closely packed living cells. The page says no intracellular space; the intended tissue feature is no conspicuous <em>intercellular</em> gaps. A starch-storing endodermal layer in many dicot stems is traditionally called the starch sheath.</p><p>The root endodermis provides a selective boundary around the stele. Casparian strips occur in the radial and transverse walls and restrict uncontrolled apoplastic passage. The source lists lignification, suberization and cutin in the radial walls.</p>" +
        "<p><strong>Source correction:</strong> the strip is a lignin-rich wall domain, with subsequent suberin lamellae and secondary wall changes in many mature endodermal cells. Cutin is not the defining constituent of a Casparian strip. Later whole-wall thickening must be distinguished from the initial strip.</p><p>Passage cells remain relatively thin-walled and less extensively suberized than surrounding mature cells, often opposite protoxylem poles. The source calls them non-lignified; that shorthand does not mean that every selective endodermal barrier is absent from them.</p>" +
        "<p>The general text correctly associates Casparian strips with both monocot and dicot roots, but the adjacent table says no Casparian stripes at maturity for monocot roots. <strong>Source correction:</strong> monocot roots also develop Casparian strips; later thickening does not make their prior formation or barrier function nonexistent. Passage-cell prominence is variable, not an absolute monocot-well-developed versus dicot-poorly-developed rule.</p><p>The ordinary monocot stem often lacks a clearly distinguishable endodermis, and the dicot stem's layer may be less conspicuous than that of a root. These are the source's anatomical examples, not proof that every monocot organ lacks endodermis.</p>"
    },
    {
      id: "monocot-dicot-stem-comparison",
      title: "Typical monocot and dicot stems",
      sources: [{ document: "biology", page: 277 }, { document: "quick-revision", page: 120 }, { document: "biology", page: 276 }],
      html: "<table><thead><tr><th>Feature</th><th>Typical monocot stem</th><th>Typical dicot stem</th></tr></thead><tbody><tr><td>Epidermal comparison</td><td>Dumbbell-shaped guard cells and no hairs in the source's example.</td><td>Bean-shaped guard cells and multicellular hairs in the source's example.</td></tr><tr><td>Vascular arrangement</td><td>Atactostele: scattered bundles.</td><td>Eustele: bundles in a ring.</td></tr><tr><td>Bundle type</td><td>Conjoint, collateral, closed; no ordinary intrabundle cambium.</td><td>Conjoint, collateral, open; cambium between xylem and phloem.</td></tr><tr><td>Primary xylem</td><td>Endarch.</td><td>Endarch.</td></tr><tr><td>Bundle size</td><td>Smaller towards the periphery, larger towards the centre in the maize-type example.</td><td>Fewer, more similar-sized bundles in the illustrated ring.</td></tr><tr><td>Hypodermis</td><td>Sclerenchymatous.</td><td>Collenchymatous in the herbaceous example.</td></tr><tr><td>Bundle sheath</td><td>A conspicuous supporting sheath surrounds each bundle.</td><td>The comparable enclosing sheath is absent in the source's example.</td></tr><tr><td>Medullary rays</td><td>No distinct conventional rays through differentiated cortex and pith.</td><td>Parenchymatous rays between bundles.</td></tr><tr><td>Secondary growth</td><td>Ordinary vascular-cambial secondary growth absent.</td><td>May occur through the cambial ring.</td></tr></tbody></table>" +
        "<p><strong>Source correction:</strong> the handwritten dicot entry dictyostele is erroneous for this typical stem comparison; the printed notes correctly give eustele. A dictyostele is a different vascular organization, classically associated with many ferns. The <strong>MADE</strong> cue records Monocot, Atactostele, the source's most Advanced description, and Dicot Eustele; scattered is the useful anatomical feature, whereas most advanced is an outdated ranking, not a testable evolutionary law.</p><p>Hair presence, guard-cell shape, bundle number and sheath development vary. Likewise not every dicot is woody, and unusual secondary thickening in monocots such as Dracaena and Yucca does not convert a typical maize bundle into an open dicot bundle.</p>"
    },
    {
      id: "monocot-dicot-root-comparison",
      title: "Typical monocot and dicot roots",
      sources: [{ document: "biology", page: 277 }, { document: "quick-revision", page: 119 }],
      html: "<table><thead><tr><th>Feature</th><th>Typical monocot root</th><th>Typical dicot root</th></tr></thead><tbody><tr><td>Cortex</td><td>Relatively wide in the source comparison.</td><td>Relatively narrow in that comparison.</td></tr><tr><td>Endodermal barrier</td><td>Casparian strips present, despite the contradictory table entry.</td><td>Casparian strips present.</td></tr><tr><td>Passage cells</td><td>Described as well developed by the source.</td><td>Described as less developed; prominence actually varies.</td></tr><tr><td>Pericycle derivatives</td><td>Lateral roots emphasized.</td><td>Lateral roots and contributions to cork cambium and vascular cambium in roots undergoing secondary growth.</td></tr><tr><td>Vascular organization</td><td>Radial and exarch.</td><td>Radial and exarch.</td></tr><tr><td>Xylem-pole number</td><td>Polyarch, generally more than six; the handwritten example gives eight.</td><td>Commonly two to six in the source.</td></tr><tr><td>Cambial growth</td><td>No ordinary vascular-cambial secondary growth.</td><td>A vascular cambium can develop and produce secondary growth.</td></tr><tr><td>Pith</td><td>Usually well developed in the illustrated type.</td><td>Small, poorly developed or absent in the illustrated type.</td></tr></tbody></table>" +
        "<p><strong>Source clarification:</strong> eight is not a universal monocot-root bundle count, and the two-to-six comparison refers to xylem poles and alternating phloem groups, not conjoint stem bundles. The dicot entry with cambium describes developmental potential or a later stage; the young primary root does not begin as a ring of open collateral bundles.</p><p>The table allows grafting in dicots and says no grafting in monocots because they lack cambium. <strong>Source qualification:</strong> the lack of a conventional continuous vascular cambium makes ordinary grafting difficult in typical monocots, but absolute impossibility is too broad. Successful graft union also requires appropriate compatibility and developmental conditions, not merely a dicot label.</p>"
    },
    {
      id: "monocot-dicot-leaf-comparison",
      title: "Typical leaf anatomy and the limits of Kranz comparisons",
      sources: [{ document: "biology", page: 277 }, { document: "biology", page: 273 }, { document: "biology", page: 276 }],
      html: "<table><thead><tr><th>Feature</th><th>Monocot example</th><th>Dicot example</th></tr></thead><tbody><tr><td>Cuticle</td><td>Similar on both surfaces.</td><td>Thicker on the upper, adaxial surface and thinner on the lower, abaxial surface.</td></tr><tr><td>Leaf organization</td><td>Isobilateral, with more similar upper and lower sides.</td><td>Dorsiventral, with differentiated upper and lower sides.</td></tr><tr><td>Stomata</td><td>On both faces; the source says the same number.</td><td>Fewer above and more below.</td></tr><tr><td>Guard cells</td><td>Dumbbell-shaped in the grass example.</td><td>Bean-shaped in the example.</td></tr><tr><td>Mesophyll</td><td>Not distinctly divided into palisade and spongy tissues in the illustrated type.</td><td>Upper palisade and lower spongy mesophyll.</td></tr><tr><td>Veins</td><td>Usually parallel.</td><td>Usually reticulate.</td></tr><tr><td>Leaf bundles</td><td>Conjoint, collateral and closed.</td><td>Conjoint, collateral and closed.</td></tr><tr><td>Bulliform cells</td><td>Present in many grass leaves.</td><td>Absent in the source's ordinary dicot example.</td></tr></tbody></table>" +
        "<p>The page also pairs monocots with Kranz anatomy and a green bundle sheath, and dicots with no Kranz anatomy and a colourless bundle sheath. <strong>Source correction:</strong> Kranz anatomy is associated with many C<sub>4</sub> plants, not with monocots as a whole. Many monocots are C<sub>3</sub>, and C<sub>4</sub> dicots can have Kranz organization. Bundle-sheath chloroplasts cannot be predicted solely from the monocot/dicot distinction.</p><p>Adaxial means facing the axis, usually the upper face of an ordinary horizontal leaf; abaxial means away from it, usually the lower face. The source additionally calls these ventral and dorsal, respectively. Use adaxial and abaxial for positional clarity. Isobilateral does not require an exactly identical stomatal count or cuticle thickness on both sides, and the tabulated venation patterns also have exceptions.</p>"
    },
    {
      id: "lenticels-pneumatophores-and-hydathodes",
      title: "Lenticels, respiratory roots and hydathodes",
      sources: [{ document: "biology", page: 278 }, { document: "biology", page: 279 }],
      html: "<p>The short glossary contrasts stomata, lenticels, pneumatophores and hydathodes. The bare stomata entry supplies no new definition beyond the guard-cell account on p.276.</p><ul><li><strong>Lenticels:</strong> localized, loosely arranged aerating tissue in a periderm, allowing gas exchange across an otherwise strongly protective covering. The source lists stems, roots and leaves and calls lenticels stomata lacking guard cells.</li><li><strong>Pneumatophores:</strong> specialized respiratory roots that project into aerated surroundings from oxygen-poor substrates. The source calls them stomata of root.</li><li><strong>Hydathodes:</strong> water-exuding structures often at leaf tips or margins, including relatively open water pores and associated tissues.</li></ul>" +
        "<p><strong>Source corrections:</strong> a lenticel is not simply a stoma after removal of its guard cells, and pneumatophores are entire modified roots, not stomatal pores. Stems and roots with periderm are the standard lenticel sites; leaves are not a universal lenticel-bearing category. Hydathodes may include modified stomatal water pores, but the whole hydathode is more than the pore alone.</p><p>Hydathodes release liquid water containing dissolved mineral solutes as <strong>guttation</strong>. The source connects this with high root pressure and low transpiration, especially at night or early morning. Guttation is distinct from vapour loss by transpiration and from dew condensed out of the surrounding air.</p>"
    },
    {
      id: "wood-types-and-porosity",
      title: "Pycnoxylic, manoxylic, porous and nonporous wood",
      sources: [{ document: "biology", page: 278 }, { document: "quick-revision", page: 120 }],
      html: "<table><thead><tr><th>Wood organization</th><th>Source comparison</th></tr></thead><tbody><tr><td>Pycnoxylic</td><td>Compact wood with relatively little parenchyma and abundant tracheary tissue. Pinus is the example; strength, durability and construction use are emphasized.</td></tr><tr><td>Manoxylic</td><td>Looser wood with relatively abundant living parenchyma and less tracheary tissue. Cycas is the example, described as softer, weaker and less useful as structural timber. The page associates Cycas with sago, a starchy food.</td></tr></tbody></table>" +
        "<p><strong>Source correction:</strong> the handwritten hard wood beside pycnoxylic is an informal hardness comparison. Pinus is botanically a softwood, despite its pycnoxylic organization. Pycnoxylic/manoxylic and hardwood/softwood are different classifications. The Cycas food entry is historical; raw cycad material can be toxic, and this association is not advice to eat or process it.</p>" +
        "<table><thead><tr><th>Timber terminology</th><th>Meaning</th></tr></thead><tbody><tr><td>Porous, heteroxylous or hardwood in the source</td><td>Typically angiosperm wood with vessel pores and differentiated conducting/supporting cell types; the printed comparison says dicots.</td></tr><tr><td>Nonporous, homoxylous or softwood in the source</td><td>Typically conifer wood dominated by tracheids and lacking vessel pores; the printed comparison says gymnosperms.</td></tr><tr><td>Ring-porous</td><td>Large earlywood vessel pores contrast conspicuously with smaller later-season pores.</td></tr><tr><td>Diffuse-porous</td><td>Vessel diameters and distribution are more uniform across the growth increment, without a strong earlywood pore ring.</td></tr></tbody></table>" +
        "<p>Hardwood is not guaranteed to be physically harder than every softwood. Vessel-bearing gnetophytes and vessel-less angiosperms prevent the printed vessel rule from being universal. Likewise homoxylous does not mean literally one cell type; rays and other cells are still present.</p><p>The source groups ring-porous wood with temperate trees and lists Dalbergia sissoo, oak and Shorea robusta; diffuse-porous wood is grouped with tropical trees and neem. These exact examples are retained, but climatic category alone does not determine porosity. Shorea robusta is commonly described as diffuse-porous, and Dalbergia and neem descriptions can depend on species and classification criteria. The named list is therefore not used as a graded climate/wood rule. The source's uniform in all seasons prompt refers to diffuse porosity, with uniform understood comparatively, not mathematically identical vessel diameters.</p>" +
        "<p>Tectona grandis, teak, is called king of woods and most durable wood in Quick Revision. These are source epithets for valued durable timber, not an established universal ranking of all wood samples.</p>"
    },
    {
      id: "vascular-secondary-growth",
      title: "Cambial ring formation and secondary vascular tissues",
      sources: [{ document: "biology", page: 279 }, { document: "biology", page: 272 }],
      html: "<p>The secondary-growth sheet shows a young dicot-stem section with epidermis, cortex, endodermis, pericycle, phloem, xylem, pith and intervening medullary rays. Its numbered sequence separates vascular growth from the protective growth outside the stele.</p>" +
        "<ol><li><strong>Formation of the cambial ring:</strong> fascicular cambium, a retained primary meristem between the bundle's xylem and phloem, joins interfascicular cambium. The latter forms by renewed division of interfascicular parenchyma or primary medullary-ray cells, labelled interfascicular pith in the drawing.</li><li><strong>Secondary growth within the stele:</strong> the continuous vascular cambium produces secondary xylem on its inner side and secondary phloem on its outer side. Primary xylem remains towards the centre; primary phloem is displaced outward as tissues accumulate.</li><li><strong>Secondary rays:</strong> ray initials in the cambium produce radial parenchyma associated with lateral transport and storage.</li><li><strong>Seasonal wood:</strong> differences in cambial activity and the size of conducting elements can establish annual growth rings.</li><li><strong>Heartwood and sapwood:</strong> older internal wood can become nonconducting heartwood while younger outer wood remains functional sapwood.</li><li><strong>Extrastelar protective growth:</strong> a separate cork cambium establishes periderm outside the vascular system.</li></ol>" +
        "<p><strong>Source correction:</strong> the box labelled interstellar region concerns the <em>intrastelar</em> region, inside the stele, not a region between stars. Similarly, pushes primary xylem inward describes its increasing distance from the expanding cambium, not wholesale relocation of the original organ centre.</p><p>In a dicot root, the page traces vascular cambium to tissue on the inner side of phloem together with pericycle portions outside the protoxylem poles. These initially discontinuous regions form the cambial system. Do not substitute the stem's pre-existing open-bundle ring for this root developmental sequence.</p>"
    },
    {
      id: "periderm-cork-and-bark",
      title: "Phellogen, phellem, phelloderm and bark",
      sources: [{ document: "biology", page: 279 }, { document: "quick-revision", page: 120 }],
      html: "<p>In the illustrated stem, cortical permanent cells resume division to form cork cambium, or <strong>phellogen</strong>, a secondary meristem. The source's gen/forming/generate cue recalls that phellogen produces cells. It cuts off <strong>phellem</strong>, cork, towards the outside and <strong>phelloderm</strong>, secondary cortical parenchyma, towards the inside.</p>" +
        "<table><thead><tr><th>Term</th><th>Identity and position</th></tr></thead><tbody><tr><td>Phellogen</td><td>Cork cambium, the dividing layer.</td></tr><tr><td>Phellem</td><td>Cork, formed externally by the phellogen.</td></tr><tr><td>Phelloderm</td><td>Secondary cortex, formed internally by the phellogen.</td></tr><tr><td>Periderm</td><td>Phellem, phellogen and phelloderm together.</td></tr><tr><td>Bark</td><td>All tissues outside the vascular cambium, including secondary phloem and the periderm.</td></tr></tbody></table>" +
        "<p><strong>Source correction:</strong> Quick Revision calls phelloderm secondary phloem. The handwritten diagram correctly identifies it as secondary cortex. Secondary phloem is produced by vascular cambium, whereas phelloderm is produced by cork cambium. Similar spellings do not make these tissues synonymous.</p>" +
        "<p>The expanded cross-section labels primary xylem, secondary xylem, secondary phloem, primary phloem, endodermis, primary cortex, secondary cortex/phelloderm, phellogen, cork/phellem and epidermis. Its bark bracket includes the surviving tissues outside vascular cambium. The original epidermis and outer primary tissues may later rupture, die or be shed as successive protective layers form; they need not all remain intact in mature bark.</p>" +
        "<p>Cork cells are dead at maturity, have suberized walls and provide a strong barrier to water and gases; tannins may also accumulate, as recorded in the source. Lenticels permit localized gas exchange through this protective region. <strong>Source clarification:</strong> suberin is deposited in the wall, not simply a liquid filling every cell lumen, and cork walls are not invariably equally thick. The line primary cortex outside cork cambium refers to pre-existing outer tissue that can become isolated; it does not mean cork is identical to primary cortex.</p><p>Bark contains several tissue types, some living and some dead, so the source correctly warns that its cells may or may not be strongly impermeable. Cork is one part of bark, not another name for the whole bark.</p>"
    },
    {
      id: "growth-rings-heartwood-and-sapwood",
      title: "Seasonal rings, heartwood and sapwood",
      sources: [{ document: "biology", page: 279 }, { document: "quick-revision", page: 120 }],
      html: "<p>Spring or earlywood is associated with greater cambial activity and relatively large conducting lumina. Autumn or latewood is associated with reduced activity and smaller lumina, often with a greater wall contribution. The source calls these large and small vessels; in vessel-less conifer wood, the contrasting cells are tracheids, not vessels.</p><p>In a tree with one reliable seasonal cycle per year, earlywood and latewood together make one annual ring. Dendrochronology studies and dates tree rings; the printed note emphasizes age estimation by counting them. A count at one trunk height dates the sampled growth increments, not automatically every year since seed germination. False or missing rings and cross-dating matter.</p>" +
        "<table><thead><tr><th>Feature</th><th>Sapwood, alburnum</th><th>Heartwood, duramen</th></tr></thead><tbody><tr><td>Position and age</td><td>Outer, younger secondary xylem.</td><td>Inner, older secondary xylem.</td></tr><tr><td>Typical colour</td><td>Lighter.</td><td>Darker from deposited substances.</td></tr><tr><td>Function</td><td>Water/mineral conduction and storage in living parenchyma.</td><td>Predominantly mechanical support; no longer the main conducting region.</td></tr><tr><td>Contents emphasized</td><td>Living parenchyma associated with functional conduits.</td><td>Tannins, resins, gums and oils; conduits may become occluded.</td></tr></tbody></table>" +
        "<p>The cues <strong>duramen/durable</strong> and <strong>dil bhitra</strong>, heart inside, preserve the printed memory aids. Deposited extractives can make heartwood more resistant to decay and account for the source's hard and tough description, but durability varies by species.</p><p><strong>Source correction:</strong> the handwritten sapwood living versus heartwood dead contrast must not turn sapwood vessels and tracheids into living cells. Mature conducting tracheary elements are already dead; sapwood retains living parenchyma and conducting function. Heartwood formation involves loss of that living component and changes in the conduits and extractives.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 119, status: "transcribed", sectionIds: ["parenchyma-specializations", "collenchyma-and-flexible-support", "sclerenchyma-fibres-and-sclereids", "xylem-components-and-conduction", "vessel-patterns-exceptions-and-tyloses", "phloem-and-vascular-comparison", "secretory-cavities-and-rubber", "vascular-bundle-types", "monocot-dicot-root-comparison"], unresolved: [] },
    { document: "quick-revision", page: 120, status: "transcribed", sectionIds: ["permanent-tissues-and-parenchyma", "phloem-and-vascular-comparison", "secretory-cavities-and-rubber", "vascular-bundle-types", "primary-xylem-arrangement", "stomata-shape-and-distribution", "monocot-dicot-stem-comparison", "wood-types-and-porosity", "periderm-cork-and-bark", "growth-rings-heartwood-and-sapwood"], unresolved: [] },
    { document: "biology", page: 271, status: "transcribed", sectionIds: ["anatomy-and-staining"], unresolved: [] },
    { document: "biology", page: 272, status: "partial", sectionIds: ["meristematic-cell-features", "meristem-origin-and-dedifferentiation", "meristem-position-and-derivatives", "vascular-secondary-growth"], unresolved: ["Upper-right apical-meristem question asserts the highest concentration of salts without naming the solute, species or comparison. The claim is transcribed as unverified and is not used as a graded fact."] },
    { document: "biology", page: 273, status: "partial", sectionIds: ["permanent-tissues-and-parenchyma", "parenchyma-specializations", "collenchyma-and-flexible-support", "sclerenchyma-fibres-and-sclereids", "secretory-cavities-and-rubber", "ground-tissue-and-pericycle", "monocot-dicot-leaf-comparison"], unresolved: ["Right-column collenchyma hydration line says 'Expand 200%' but provides no baseline, measured dimension or experimental condition. The literal number is retained without assigning it a quantitative meaning or question key."] },
    { document: "biology", page: 274, status: "partial", sectionIds: ["xylem-components-and-conduction", "vessel-patterns-exceptions-and-tyloses"], unresolved: ["Left vessel column ranks Eucalyptus first and oak second for longest vessels without species, measurements or a vessel-versus-vessel-element distinction; the ranking is preserved but unverified.", "The vessel-exception list 'SEM' gives Selaginella, Equisetum and Marsilea without species, organs or criteria for a vessel. These exact source entries are retained but are not scored as universal genus characters."] },
    { document: "biology", page: 276, status: "transcribed", sectionIds: ["vascular-bundle-types", "primary-xylem-arrangement", "epidermis-bulliform-and-hairs", "stomata-shape-and-distribution", "lateral-roots-and-shoot-branches", "monocot-dicot-stem-comparison", "monocot-dicot-leaf-comparison"], unresolved: [] },
    { document: "biology", page: 277, status: "transcribed", sectionIds: ["stomata-shape-and-distribution", "lateral-roots-and-shoot-branches", "ground-tissue-and-pericycle", "endodermis-and-casparian-strips", "monocot-dicot-stem-comparison", "monocot-dicot-root-comparison", "monocot-dicot-leaf-comparison"], unresolved: [] },
    { document: "biology", page: 278, status: "partial", sectionIds: ["permanent-tissues-and-parenchyma", "lenticels-pneumatophores-and-hydathodes", "wood-types-and-porosity"], unresolved: ["Upper-right prompt 'Packing tissue in fern is' is unanswered. The separate following line gives parenchyma as packing tissue in plants, but no fern-specific answer or intended distinction is supplied."] },
    { document: "biology", page: 279, status: "transcribed", sectionIds: ["meristem-origin-and-dedifferentiation", "lenticels-pneumatophores-and-hydathodes", "vascular-secondary-growth", "periderm-cork-and-bark", "growth-rings-heartwood-and-sapwood"], unresolved: [] }
  ],
  questions: [
    {
      id: "note-plant-anatomy-001", text: "A root-tip section contains a small region with much lower mitotic activity than neighbouring initials. Which structure does this identify?",
      options: [{ key: "a", text: "The intercalary meristem" }, { key: "b", text: "The quiescent centre" }, { key: "c", text: "The cork cambium" }, { key: "d", text: "The starch sheath" }],
      answer: "b", explanation: "The quiescent centre is a relatively slowly dividing region of the root apical meristem. Its presence also shows why the source's continuous cell division description cannot mean that every meristematic cell divides at the same rate.", sectionId: "meristem-position-and-derivatives", source: { document: "biology", page: 272 }, cognitive: "understanding"
    },
    {
      id: "note-plant-anatomy-002", text: "Mature living cells beside a stem wound resume division and establish reparative tissue. Which developmental change best describes this response?",
      options: [{ key: "a", text: "Lignification of a conducting vessel" }, { key: "b", text: "Differentiation into a mature sclereid" }, { key: "c", text: "Loss of protoplasm during maturation" }, { key: "d", text: "Dedifferentiation into a secondary meristem" }],
      answer: "d", explanation: "The cells had differentiated but regain proliferative capacity, which is dedifferentiation. The source connects wound repair with secondary meristem formation. Dead mature vessels and sclereids cannot themselves restart mitosis.", sectionId: "meristem-origin-and-dedifferentiation", source: { document: "biology", page: 272 }, cognitive: "application"
    },
    {
      id: "note-plant-anatomy-003", text: "Which term names the small, undifferentiated plastid precursors present in meristematic cells?",
      options: [{ key: "a", text: "Proplastids" }, { key: "b", text: "Amyloplasts" }, { key: "c", text: "Chromoplasts" }, { key: "d", text: "Chloroplasts" }],
      answer: "a", explanation: "Proplastids are undifferentiated plastid precursors present in meristematic cells. Amyloplasts, chromoplasts and chloroplasts are differentiated plastid forms, so absence of mature chloroplasts does not mean absence of all plastids.", sectionId: "meristematic-cell-features", source: { document: "biology", page: 272 }, cognitive: "recall"
    },
    {
      id: "note-plant-anatomy-004", text: "Selective damage to the protoderm would most directly disrupt formation of which primary tissue?",
      options: [{ key: "a", text: "Primary phloem" }, { key: "b", text: "Central pith" }, { key: "c", text: "Surface epidermis" }, { key: "d", text: "Primary xylem" }],
      answer: "c", explanation: "Protoderm is the outer primary meristem that produces the epidermis. Procambium supplies the primary vascular tissues, while ground meristem supplies much of the ground tissue, including pith where it is differentiated.", sectionId: "meristem-position-and-derivatives", source: { document: "biology", page: 272 }, cognitive: "application"
    },
    {
      id: "note-plant-anatomy-005", text: "An internode continues elongating from a dividing zone between already differentiated tissues. Which meristem is responsible?",
      options: [{ key: "a", text: "Cork cambium" }, { key: "b", text: "Vascular cambium" }, { key: "c", text: "Intercalary meristem" }, { key: "d", text: "Quiescent centre" }],
      answer: "c", explanation: "An intercalary meristem is a retained meristematic region between permanent tissues and can lengthen an internode. Cork and vascular cambia principally increase girth, while the quiescent centre belongs to the root apex.", sectionId: "meristem-position-and-derivatives", source: { document: "biology", page: 272 }, cognitive: "application"
    },
    {
      id: "note-plant-anatomy-006", text: "Which role explains the mucilage-rich parenchyma described in Agave and Aloe vera leaves?",
      options: [{ key: "a", text: "Retention of stored water" }, { key: "b", text: "Production of sieve plates" }, { key: "c", text: "Formation of vessel perforations" }, { key: "d", text: "Initiation of lateral roots" }],
      answer: "a", explanation: "The source identifies these as succulent xerophyte examples whose mucilage parenchyma stores water. The other processes belong to vascular differentiation or root initiation, not the stated function of this storage tissue.", sectionId: "parenchyma-specializations", source: { document: "biology", page: 273 }, cognitive: "recall"
    },
    {
      id: "note-plant-anatomy-007", text: "A hydrophyte petiole contains large connected air spaces among living parenchyma cells. Which combined effect is most consistent with this anatomy?",
      options: [{ key: "a", text: "Greater lignification and greater rigidity" }, { key: "b", text: "More cambial growth and more cork" }, { key: "c", text: "Reduced aeration and reduced buoyancy" }, { key: "d", text: "Improved aeration and improved buoyancy" }],
      answer: "d", explanation: "The observed air-space system is aerenchyma. Its spaces facilitate internal gas movement and can reduce tissue density, aiding flotation. Pistia and Eichhornia are the hydrophyte examples named in the source.", sectionId: "parenchyma-specializations", source: { document: "biology", page: 273 }, cognitive: "application"
    },
    {
      id: "note-plant-anatomy-008", text: "Which cell shape is emphasized by the historical term prosenchyma in these notes?",
      options: [{ key: "a", text: "Short cells with a star-shaped outline" }, { key: "b", text: "Long cells with tapering ends" }, { key: "c", text: "Round cells enclosing a wide air chamber" }, { key: "d", text: "Paired cells with kidney-shaped outlines" }],
      answer: "b", explanation: "Prosenchyma describes elongated cells with tapering ends. The notes associate their compact arrangement with support. The term alone does not guarantee the same lignin distribution or starch content in every organ.", sectionId: "parenchyma-specializations", source: { document: "biology", page: 273 }, cognitive: "recall"
    },
    {
      id: "note-plant-anatomy-009", text: "A young petiole bends without breaking, supported by living cells with pectin-rich thickened walls. Which tissue best accounts for this combination?",
      options: [{ key: "a", text: "Collenchyma" }, { key: "b", text: "Mature cork" }, { key: "c", text: "Vessel elements" }, { key: "d", text: "Stone-cell sclerenchyma" }],
      answer: "a", explanation: "Collenchyma combines living contents with thickened, pectin-containing primary walls, supplying flexible support to growing organs. Mature cork, vessels and typical stone cells do not share this combination of living flexible support.", sectionId: "collenchyma-and-flexible-support", source: { document: "biology", page: 273 }, cognitive: "understanding"
    },
    {
      id: "note-plant-anatomy-010", text: "A collenchyma section has the greatest wall thickening at the corners where several cells meet. Which type is indicated?",
      options: [{ key: "a", text: "Lacunar collenchyma" }, { key: "b", text: "Lamellate collenchyma" }, { key: "c", text: "Angular collenchyma" }, { key: "d", text: "Reticulate xylem" }],
      answer: "c", explanation: "Corner-focused wall thickening identifies angular collenchyma, for which tomato and Datura are source examples. Lamellate thickening emphasizes tangential walls, while lacunar thickening borders intercellular spaces.", sectionId: "collenchyma-and-flexible-support", source: { document: "biology", page: 273 }, cognitive: "recall"
    },
    {
      id: "note-plant-anatomy-011", text: "The gritty particles in pear pulp are most directly associated with which cells?",
      options: [{ key: "a", text: "Bulliform cells" }, { key: "b", text: "Stone-cell sclereids" }, { key: "c", text: "Companion cells" }, { key: "d", text: "Passage cells" }],
      answer: "b", explanation: "Pear pulp contains thick-walled sclereids, commonly called stone cells, which account for its grit. Their lignified walls and restricted lumina contrast with the softer surrounding parenchyma.", sectionId: "sclerenchyma-fibres-and-sclereids", source: { document: "biology", page: 273 }, cognitive: "recall"
    },
    {
      id: "note-plant-anatomy-012", text: "The unusually long cells highlighted in the ramie example belong to which category?",
      options: [{ key: "a", text: "Astrosclereids" }, { key: "b", text: "Guard cells" }, { key: "c", text: "Vessel elements" }, { key: "d", text: "Sclerenchyma fibres" }],
      answer: "d", explanation: "Ramie is the source's example of exceptionally long sclerenchyma fibres. A fibre is an elongated individual supporting cell, not a whole vessel assembled from many vessel elements or a branched astrosclereid.", sectionId: "sclerenchyma-fibres-and-sclereids", source: { document: "biology", page: 273 }, cognitive: "recall"
    },
    {
      id: "note-plant-anatomy-013", text: "Which feature most directly distinguishes a tracheid from a vessel element at its end-wall connection?",
      options: [{ key: "a", text: "The tracheid retains a living nucleus" }, { key: "b", text: "The tracheid lacks secondary-wall lignin" }, { key: "c", text: "The tracheid carries only organic sugars" }, { key: "d", text: "The tracheid lacks a perforation plate" }],
      answer: "d", explanation: "A tracheid transfers water across pits while its end-wall boundary remains unperforated. Vessel elements have perforation plates linking their lumina into a vessel. Both are normally dead, lignified conducting cells at maturity.", sectionId: "xylem-components-and-conduction", source: { document: "biology", page: 274 }, cognitive: "understanding"
    },
    {
      id: "note-plant-anatomy-014", text: "In a developing primary xylem strand, what does the prefix proto- identify?",
      options: [{ key: "a", text: "The last-formed conducting elements" }, { key: "b", text: "The first-formed conducting elements" }, { key: "c", text: "The outermost secondary wood ring" }, { key: "d", text: "The first-formed secondary phloem" }],
      answer: "b", explanation: "Protoxylem is the first-formed primary xylem and commonly has smaller elements. Metaxylem forms later. Neither term specifies a secondary growth ring or identifies a phloem component.", sectionId: "xylem-components-and-conduction", source: { document: "biology", page: 274 }, cognitive: "recall"
    },
    {
      id: "note-plant-anatomy-015", text: "Which reinforcement pattern leaves separated lignified bands that can accommodate elongation of a young conducting element?",
      options: [{ key: "a", text: "A continuous pitted secondary wall" }, { key: "b", text: "A solid mass of heartwood extractives" }, { key: "c", text: "Separate annular rings along the wall" }, { key: "d", text: "A plug extending across the whole lumen" }],
      answer: "c", explanation: "Annular reinforcement consists of separate rings, leaving intervening wall regions able to extend. A nearly continuous pitted wall restricts extension more strongly, while extractives and lumen plugs are not elongation-compatible wall patterns.", sectionId: "vessel-patterns-exceptions-and-tyloses", source: { document: "biology", page: 274 }, cognitive: "application"
    },
    {
      id: "note-plant-anatomy-016", text: "Which pair belongs entirely to the GEW vessel-bearing gymnosperm group recorded in the handwritten notes?",
      options: [{ key: "a", text: "Gnetum and Ephedra" }, { key: "b", text: "Cycas and Ginkgo" }, { key: "c", text: "Pinus and Cedrus" }, { key: "d", text: "Abies and Picea" }],
      answer: "a", explanation: "GEW represents Gnetum, Ephedra and Welwitschia. Their vessels disprove the printed claim that vessels are restricted to angiosperms. The other listed pairs are not the gnetophyte vessel-bearing group.", sectionId: "vessel-patterns-exceptions-and-tyloses", source: { document: "biology", page: 274 }, cognitive: "recall"
    },
    {
      id: "note-plant-anatomy-017", text: "A balloon-like outgrowth enters a vessel through a pit from neighbouring parenchyma. What is the resulting obstruction called?",
      options: [{ key: "a", text: "A sieve plate" }, { key: "b", text: "A tylosis" }, { key: "c", text: "A Casparian strip" }, { key: "d", text: "A bulliform cell" }],
      answer: "b", explanation: "A tylosis is an outgrowth of living parenchyma into a conducting lumen, characteristically a vessel, through a pit. Sieve plates belong to phloem, Casparian strips to endodermal walls, and bulliform cells to leaf epidermis.", sectionId: "vessel-patterns-exceptions-and-tyloses", source: { document: "quick-revision", page: 119 }, cognitive: "understanding"
    },
    {
      id: "note-plant-anatomy-018", text: "Sugars move upward towards a young shoot in one phloem pathway and downward towards a root in another. Which interpretation is justified?",
      options: [{ key: "a", text: "Different source-to-sink paths can have different directions" }, { key: "b", text: "Every sieve tube must carry opposite streams simultaneously" }, { key: "c", text: "The upward pathway must actually be a xylem vessel" }, { key: "d", text: "The downward pathway must lack living conducting cells" }],
      answer: "a", explanation: "Bidirectional phloem transport describes the whole network: different sinks can lie in different directions from a source. It does not require simultaneous opposing bulk flow within one sieve tube.", sectionId: "phloem-and-vascular-comparison", source: { document: "quick-revision", page: 119 }, cognitive: "understanding"
    },
    {
      id: "note-plant-anatomy-019", text: "Which substance can be deposited around sieve pores as a glucose polymer rather than as a protein plug?",
      options: [{ key: "a", text: "Suberin" }, { key: "b", text: "P-protein" }, { key: "c", text: "Lignin" }, { key: "d", text: "Callose" }],
      answer: "d", explanation: "Callose is a beta-1,3-linked glucan and can narrow or occlude sieve pores. P-protein is proteinaceous, while lignin and suberin are associated with different wall properties. Free glucose is not synonymous with callose.", sectionId: "phloem-and-vascular-comparison", source: { document: "quick-revision", page: 119 }, cognitive: "recall"
    },
    {
      id: "note-plant-anatomy-020", text: "Which plant is paired with Para rubber in the source's latex-product table?",
      options: [{ key: "a", text: "Ficus elastica" }, { key: "b", text: "Castilla elastica" }, { key: "c", text: "Hevea brasiliensis" }, { key: "d", text: "Manihot glaziovii" }],
      answer: "c", explanation: "Para or natural rubber is associated with Hevea brasiliensis. The same table pairs Ficus elastica with Indian rubber, Castilla elastica with Panama rubber and Manihot glaziovii with Ceara rubber.", sectionId: "secretory-cavities-and-rubber", source: { document: "quick-revision", page: 120 }, cognitive: "recall"
    },
    {
      id: "note-plant-anatomy-021", text: "A root section shows phloem groups alternating with xylem groups on different radii. Which vascular arrangement is present?",
      options: [{ key: "a", text: "Bicollateral" }, { key: "b", text: "Amphivasal" }, { key: "c", text: "Radial" }, { key: "d", text: "Collateral" }],
      answer: "c", explanation: "Separate alternating xylem and phloem radii define a radial arrangement. In conjoint collateral or bicollateral bundles the tissues share a radius, and an amphivasal bundle encloses central phloem with xylem.", sectionId: "vascular-bundle-types", source: { document: "biology", page: 276 }, cognitive: "understanding"
    },
    {
      id: "note-plant-anatomy-022", text: "In an isolated concentric bundle, phloem occupies the centre and xylem forms the surrounding region. Which name is correct?",
      options: [{ key: "a", text: "Amphicribral, or hadrocentric" }, { key: "b", text: "Radial, with alternating groups" }, { key: "c", text: "Bicollateral, with two phloem bands" }, { key: "d", text: "Amphivasal, or leptocentric" }],
      answer: "d", explanation: "Central phloem surrounded by xylem is amphivasal or leptocentric. Amphicribral or hadrocentric has the reverse order. The typed notes explicitly correct the transposed headings above the handwritten concentric diagrams.", sectionId: "vascular-bundle-types", source: { document: "quick-revision", page: 120 }, cognitive: "application"
    },
    {
      id: "note-plant-anatomy-023", text: "Later xylem differentiates inward from peripheral protoxylem poles in a root. Which description fits this sequence?",
      options: [{ key: "a", text: "Endarch and centrifugal" }, { key: "b", text: "Exarch and centripetal" }, { key: "c", text: "Exarch and centrifugal" }, { key: "d", text: "Endarch and centripetal" }],
      answer: "b", explanation: "Exarch places protoxylem towards the periphery; later metaxylem differentiates inward, a centripetal sequence. The direction concerns maturation of xylem, not necessarily the direction in which water is moving.", sectionId: "primary-xylem-arrangement", source: { document: "quick-revision", page: 120 }, cognitive: "understanding"
    },
    {
      id: "note-plant-anatomy-024", text: "Why is a typical dicot stem's collateral vascular bundle described as open?",
      options: [{ key: "a", text: "Cambium remains between its xylem and phloem" }, { key: "b", text: "The vessel lumina open directly to the atmosphere" }, { key: "c", text: "The bundle is missing its entire phloem region" }, { key: "d", text: "Xylem and phloem alternate on separate radii" }],
      answer: "a", explanation: "Open refers to the presence of cambium between the xylem and phloem of a collateral bundle. It does not mean an exposed vessel lumen. Alternating separate radii would instead describe a radial root arrangement.", sectionId: "vascular-bundle-types", source: { document: "biology", page: 276 }, cognitive: "understanding"
    },
    {
      id: "note-plant-anatomy-025", text: "During dry conditions a grass leaf rolls as enlarged epidermal cells lose turgor. Which cells are implicated?",
      options: [{ key: "a", text: "Bulliform cells" }, { key: "b", text: "Companion cells" }, { key: "c", text: "Stone cells" }, { key: "d", text: "Passage cells" }],
      answer: "a", explanation: "Bulliform or motor cells are enlarged epidermal cells associated with rolling and unrolling in many grass leaves. Their hydration changes are distinct from phloem support, sclereid hardness or the root-endodermal passage-cell function.", sectionId: "epidermis-bulliform-and-hairs", source: { document: "biology", page: 276 }, cognitive: "application"
    },
    {
      id: "note-plant-anatomy-026", text: "The multilayered covering of a Vanda aerial root, composed of cells dead at maturity, is called what?",
      options: [{ key: "a", text: "Phelloderm" }, { key: "b", text: "Velamen" }, { key: "c", text: "Leptome" }, { key: "d", text: "Palisade" }],
      answer: "b", explanation: "Velamen is the specialized multilayered covering associated with aerial roots of orchids such as Vanda. Phelloderm is produced by cork cambium, leptome refers to phloem conduction, and palisade is photosynthetic mesophyll.", sectionId: "epidermis-bulliform-and-hairs", source: { document: "biology", page: 276 }, cognitive: "recall"
    },
    {
      id: "note-plant-anatomy-027", text: "A floating leaf has its lower face against water and stomata confined to its air-exposed upper face. Which distribution term applies?",
      options: [{ key: "a", text: "Hypostomatic" }, { key: "b", text: "Amphistomatic" }, { key: "c", text: "Epistomatic" }, { key: "d", text: "Astomatic" }],
      answer: "c", explanation: "Epistomatic leaves bear stomata on the upper surface, as in the source's floating-hydrophyte example. Hypostomatic means lower-surface stomata, amphistomatic means both surfaces, and astomatic means no stomata.", sectionId: "stomata-shape-and-distribution", source: { document: "biology", page: 276 }, cognitive: "application"
    },
    {
      id: "note-plant-anatomy-028", text: "Which change usually opens a stoma in the kidney-shaped guard-cell example?",
      options: [{ key: "a", text: "Loss of turgor with collapse of the outer walls" }, { key: "b", text: "Lignification of both guard-cell walls" }, { key: "c", text: "Death of both guard cells around the pore" }, { key: "d", text: "Gain of turgor with unequal wall extension" }],
      answer: "d", explanation: "Increasing guard-cell turgor acts on walls with unequal thickness and extensibility, causing the cells to bow apart and open the pore. The mechanism depends on living cells and wall mechanics, not wall lignification or death.", sectionId: "stomata-shape-and-distribution", source: { document: "biology", page: 276 }, cognitive: "understanding"
    },
    {
      id: "note-plant-anatomy-029", text: "Where does an ordinary dicot lateral-root primordium originate in the source's developmental sequence?",
      options: [{ key: "a", text: "In the root cap beyond the apex" }, { key: "b", text: "In the epidermis among root hairs" }, { key: "c", text: "In a mature protoxylem vessel lumen" }, { key: "d", text: "In the pericycle near a protoxylem pole" }],
      answer: "d", explanation: "The source's endogenous lateral root begins in the pericycle, commonly opposite a protoxylem pole, and grows through surrounding tissues. Its position near protoxylem does not mean that a dead vessel element divides to make the root.", sectionId: "lateral-roots-and-shoot-branches", source: { document: "biology", page: 276 }, cognitive: "recall"
    },
    {
      id: "note-plant-anatomy-030", text: "A dissolved tracer moving through cortical cell walls is stopped from freely continuing into the stele. Which boundary most directly explains the restriction?",
      options: [{ key: "a", text: "The lumen of a central vessel" }, { key: "b", text: "The outer face of a root hair" }, { key: "c", text: "Casparian strips in the endodermis" }, { key: "d", text: "Air spaces in the spongy mesophyll" }],
      answer: "c", explanation: "Casparian strips interrupt free apoplastic movement at the root endodermis, forcing a more selective route towards the stele. They occur in monocot as well as dicot roots, despite the contradictory source comparison.", sectionId: "endodermis-and-casparian-strips", source: { document: "biology", page: 277 }, cognitive: "application"
    },
    {
      id: "note-plant-anatomy-031", text: "A stem has scattered closed bundles, smaller near the surface, with endarch xylem and no distinct medullary rays. Which interpretation best fits?",
      options: [{ key: "a", text: "A typical monocot stem with an atactostele" }, { key: "b", text: "A typical dicot root with radial xylem" }, { key: "c", text: "A typical dicot stem with an open bundle ring" }, { key: "d", text: "A typical monocot root with polyarch xylem" }],
      answer: "a", explanation: "Scattered closed vascular bundles and undifferentiated ground tissue are characteristic of the source's monocot-stem comparison. A root would have radial, usually exarch organization, while a typical dicot stem has an open bundle ring.", sectionId: "monocot-dicot-stem-comparison", source: { document: "biology", page: 277 }, cognitive: "application"
    },
    {
      id: "note-plant-anatomy-032", text: "Which combination best supports identification of the typical monocot root illustrated in the notes?",
      options: [{ key: "a", text: "Endarch xylem, open bundles and a ring of cambium" }, { key: "b", text: "Exarch xylem, many poles and a well-developed pith" }, { key: "c", text: "Endarch xylem, scattered bundles and no distinct pith" }, { key: "d", text: "Exarch xylem, two poles and a very small pith" }],
      answer: "b", explanation: "A typical monocot root has radial, exarch, polyarch xylem and a conspicuous pith. A two-pole root with little pith better matches a common dicot-root example. Endarch conjoint bundles instead suggest stem anatomy.", sectionId: "monocot-dicot-root-comparison", source: { document: "biology", page: 277 }, cognitive: "application"
    },
    {
      id: "note-plant-anatomy-033", text: "Which bundle description is shared by both leaf columns in the handwritten monocot/dicot comparison?",
      options: [{ key: "a", text: "Radial, exarch and polyarch" }, { key: "b", text: "Conjoint, collateral and closed" }, { key: "c", text: "Conjoint, bicollateral and open" }, { key: "d", text: "Concentric, amphivasal and closed" }],
      answer: "b", explanation: "Both source leaf columns specify conjoint, collateral, closed vascular bundles. This shared leaf feature must not be replaced by the stem comparison, in which typical dicot bundles are open and typical monocot bundles closed.", sectionId: "monocot-dicot-leaf-comparison", source: { document: "biology", page: 277 }, cognitive: "recall"
    },
    {
      id: "note-plant-anatomy-034", text: "A dicot leaf has a conspicuous chloroplast-rich bundle sheath arranged in Kranz fashion. What is the sound conclusion?",
      options: [{ key: "a", text: "The specimen must have been wrongly labelled as a dicot" }, { key: "b", text: "Every other dicot leaf must possess the same arrangement" }, { key: "c", text: "Kranz anatomy establishes parallel venation in this leaf" }, { key: "d", text: "The observation is compatible with a C4 dicot leaf" }],
      answer: "d", explanation: "Kranz anatomy is associated with many C4 plants, including some dicots. It is not a universal monocot character or universally absent in dicots, and it does not by itself establish the leaf's venation pattern.", sectionId: "monocot-dicot-leaf-comparison", source: { document: "biology", page: 277 }, cognitive: "understanding"
    },
    {
      id: "note-plant-anatomy-035", text: "Across one wood growth increment, vessel diameters remain relatively uniform rather than forming a band of much larger early vessels. Which porosity is indicated?",
      options: [{ key: "a", text: "Ring-porous wood" }, { key: "b", text: "Nonporous wood" }, { key: "c", text: "Diffuse-porous wood" }, { key: "d", text: "Vessel-less wood" }],
      answer: "c", explanation: "Diffuse-porous wood has a comparatively uniform vessel distribution across an increment. Ring-porous wood has a marked band of larger earlywood pores, while nonporous or vessel-less wood does not have the described vessel pattern.", sectionId: "wood-types-and-porosity", source: { document: "biology", page: 278 }, cognitive: "application"
    },
    {
      id: "note-plant-anatomy-036", text: "How can Pinus have compact pycnoxylic wood yet still be classified as a softwood?",
      options: [{ key: "a", text: "Pycnoxylic describes tissue organization; softwood identifies a timber group" }, { key: "b", text: "Pycnoxylic describes bark density; softwood describes the internal wood" }, { key: "c", text: "Pycnoxylic describes young wood; softwood describes the same wood at maturity" }, { key: "d", text: "Pycnoxylic describes annual rings; softwood describes the absence of rings" }],
      answer: "a", explanation: "Pycnoxylic describes compact wood with relatively little parenchyma. Softwood is the timber category associated with gymnosperms such as conifers, not a promise of low physical hardness. The two classifications are independent.", sectionId: "wood-types-and-porosity", source: { document: "biology", page: 278 }, cognitive: "understanding"
    },
    {
      id: "note-plant-anatomy-037", text: "Which two cambial regions join to establish the continuous vascular cambium in the illustrated dicot stem?",
      options: [{ key: "a", text: "Root-cap initials and protoderm" }, { key: "b", text: "Phellogen and phelloderm" }, { key: "c", text: "Fascicular and interfascicular cambium" }, { key: "d", text: "Bulliform cells and subsidiary cells" }],
      answer: "c", explanation: "The source diagram joins retained fascicular cambium with newly meristematic interfascicular regions. Phellogen belongs to the separate periderm system, and phelloderm is a differentiated product rather than the missing vascular cambial segment.", sectionId: "vascular-secondary-growth", source: { document: "biology", page: 279 }, cognitive: "recall"
    },
    {
      id: "note-plant-anatomy-038", text: "Which pair gives the usual inward and outward products of the vascular cambium, respectively?",
      options: [{ key: "a", text: "Secondary xylem; secondary phloem" }, { key: "b", text: "Secondary phloem; secondary xylem" }, { key: "c", text: "Phellem; phelloderm" }, { key: "d", text: "Phelloderm; phellem" }],
      answer: "a", explanation: "Vascular cambium produces secondary xylem inward and secondary phloem outward. Phelloderm inward and phellem outward instead describe cork cambium, so those tissues must not be substituted for vascular derivatives.", sectionId: "vascular-secondary-growth", source: { document: "biology", page: 279 }, cognitive: "recall"
    },
    {
      id: "note-plant-anatomy-039", text: "Which identity correctly repairs the printed phelloderm entry?",
      options: [{ key: "a", text: "Secondary phloem made by phellogen" }, { key: "b", text: "Secondary xylem made by phellogen" }, { key: "c", text: "External cork made by vascular cambium" }, { key: "d", text: "Secondary cortex made by phellogen" }],
      answer: "d", explanation: "Phelloderm is secondary cortical parenchyma produced towards the inside by phellogen. The printed secondary-phloem label is corrected explicitly using the distinction between the cork and vascular cambial systems.", sectionId: "periderm-cork-and-bark", source: { document: "quick-revision", page: 120 }, cognitive: "recall"
    },
    {
      id: "note-plant-anatomy-040", text: "A trunk section contains 11 complete earlywood/latewood pairs, with one reliable pair formed yearly and no missing rings. What does this directly establish?",
      options: [{ key: "a", text: "Exactly 22 years have elapsed since germination" }, { key: "b", text: "Eleven annual increments are represented at that height" }, { key: "c", text: "Exactly 11 years have elapsed since germination" }, { key: "d", text: "Twenty-two annual increments are represented at that height" }],
      answer: "b", explanation: "One earlywood/latewood pair represents one annual increment under the stated conditions, so 11 pairs give 11 increments. A sample above ground level does not include the time the seedling took to reach that height, and the two seasonal components are not separate years.", sectionId: "growth-rings-heartwood-and-sapwood", source: { document: "biology", page: 279 }, cognitive: "application"
    }
  ]
};