window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["plasmodium"] = {
  id: "plasmodium",
  subject: "Zoology",
  title: "Plasmodium and malaria",
  sections: [
    {
      id: "plasmodium-identity-hosts",
      title: "Identity, historical classification and two hosts",
      sources: [{ document: "biology", page: 4 }],
      html: "<p>Plasmodium is the malarial parasite. Malaria derives from words meaning bad air; the source's bad night air is a historical explanation of the name, not the cause of infection. Infection is caused by parasites, ordinarily transmitted through the bite of an infective female Anopheles mosquito.</p><p>The source classification reads Kingdom Protista, Phylum Protozoa, Class Sporozoa, Order Eucoccida, Genus Plasmodium. These are historical teaching ranks. In modern classification Plasmodium is an apicomplexan of the order Haemosporida; the source's old Protozoa/Sporozoa/Eucoccida sequence is not a current phylogenetic classification.</p><ul><li>The parasite is digenetic in the source's sense that its life cycle involves two hosts.</li><li>Humans are the intermediate or secondary host, with asexual multiplication in liver cells and erythrocytes.</li><li>Female Anopheles is the primary or definitive host because gamete formation and fertilization occur there. FAM in the handwritten diagram means female Anopheles mosquito.</li><li>The form infective to humans by mosquito inoculation is the sporozoite. The form taken up from human blood that continues development in the mosquito is the gametocyte.</li><li>The source calls the merozoite the pathogenic form. More precisely, pathology is associated with the whole erythrocytic infection, including multiplication, red-cell destruction, inflammation and, especially in falciparum malaria, sequestration of infected cells.</li></ul>"
    },
    {
      id: "plasmodium-species",
      title: "Every species row: fever pattern and clinical labels",
      sources: [{ document: "quick-revision", page: 159 }, { document: "biology", page: 4 }],
      html: "<table><thead><tr><th>Species</th><th>Source type, periodicity and severity</th></tr></thead><tbody><tr><td>P. falciparum</td><td>Malignant tertian malaria. The printed row gives every second and third day, after 36-48 hours; the handwritten table instead says irregular crisis. An approximately 48-hour erythrocytic cycle can produce irregular or poorly synchronized fever. The page emphasizes very serious disease and possible death without effective prompt treatment.</td></tr><tr><td>P. vivax</td><td>Historically benign tertian or vivax malaria; fever about every 48 hours, also expressed as every two days. The handwritten severity cell says grave, but with a delayed onset. Delay is not an invariant species feature, and vivax malaria can be severe.</td></tr><tr><td>P. malariae</td><td>Historically benign quartan malaria. Every fourth day in inclusive counting means a 72-hour interval, equivalent to every three elapsed days. The handwritten table describes moderate, less frequent disease.</td></tr><tr><td>P. ovale</td><td>The printed row says benign sub-tertian, and the handwritten row benign tertian. Both describe a 48-hour interval, every third day by inclusive counting or every two elapsed days. The handwritten severity cell says moderate, less frequently.</td></tr></tbody></table><p>Tertian counts a fever day as day one and its recurrence as day three: the elapsed interval is 48 hours. Quartan similarly refers to day one and day four, 72 hours apart. A paroxysm is an attack of symptoms such as chills, fever and sweating. The source table's heading febrile seizures period should be read as fever-paroxysm periodicity; not every attack involves a seizure.</p><p><strong>Source corrections:</strong> benign means the historical relatively milder category, not safe or harmless; malignant means severe or dangerous. P. falciparum can cause cerebral malaria. Blackwater fever denotes marked hemoglobinuria associated with severe intravascular hemolysis, not a synonym for every falciparum infection. The blanket all species benign except falciparum is false, and all tertian except malariae applies only as an oversimplification of the four listed species, not all malaria parasites. Other human malaria parasites, including P. knowlesi with an approximately 24-hour cycle, prevent that statement from being universal.</p>"
    },
    {
      id: "plasmodium-stippling-timing",
      title: "Stippling, prepatent period and incubation: complete source values",
      sources: [{ document: "quick-revision", page: 159 }, { document: "biology", page: 4 }],
      html: "<table><thead><tr><th>Species</th><th>Staining feature in the source</th></tr></thead><tbody><tr><td>P. vivax</td><td>Schuffner's dots or granules.</td></tr><tr><td>P. falciparum</td><td>Maurer's dots or clefts.</td></tr><tr><td>P. malariae</td><td>Ziemann's dots.</td></tr><tr><td>P. ovale</td><td>James' dots in Quick Revision; Schuffner's dots in Biology. These are descriptions of Schuffner-like stippling in ovale-infected cells rather than incompatible parasite identities.</td></tr></tbody></table><p><strong>Source correction:</strong> the handwritten heading antigens/granules conflates concepts. The named dots are staining appearances or parasite-induced changes in infected erythrocytes, not a list of four diagnostic antigen molecules.</p><table><thead><tr><th>Species</th><th>Nominal periods written in the sources</th></tr></thead><tbody><tr><td>P. falciparum</td><td>Printed prepatent: 6 days. Incubation: 12 days in both tables.</td></tr><tr><td>P. vivax</td><td>Printed prepatent: 8 days. Incubation: 14 days in both tables.</td></tr><tr><td>P. malariae</td><td>Printed prepatent: 20 days. Incubation: 28 days in both tables.</td></tr><tr><td>P. ovale</td><td>Printed prepatent: 8 days. Incubation: 14 days in Quick Revision, but 17 days in Biology.</td></tr></tbody></table><p>The prepatent period is the interval from infection to first detectable parasitemia in blood. The handwritten definition first appearance of parasite in blood captures this idea, although detection depends on the test. The printed definition ending at initiation of the erythrocytic cycle is not exactly equivalent to detection. The standalone handwritten 8 days is not a universal prepatent period.</p><p>Incubation is the interval from infection to the appearance of symptoms. Quick Revision also gives a general 14-28 days, even though its falciparum row gives 12 days. Actual incubation and detectable parasitemia vary with species, strain, inoculum, host factors, previous exposure, prophylaxis and test sensitivity. These table numbers are retained as source entries, not exact biological constants. The unexplained ovale 14-versus-17-day difference and the unspecified meaning of the nominal prepatent values remain unresolved and are excluded from scored numerical questions.</p>"
    },
    {
      id: "plasmodium-liver-cycle",
      title: "Liver phase and all labels in the historical hepatic diagram",
      sources: [{ document: "biology", page: 4 }],
      html: "<ol><li>Infective sporozoites leave mosquito salivary glands during inoculation and eventually invade liver cells, or hepatocytes. The sketch describes them as slender sickle- or spindle-shaped invasive forms.</li><li>Within a hepatocyte the parasite grows into a liver schizont and undergoes schizogony, asexual multiple division.</li><li>Merozoites released from liver schizonts enter blood and invade erythrocytes. The pre-erythrocytic label describes development before the blood-cell phase.</li></ol><p>The source additionally labels the initial liver products cryptozoites or cryptomerozoites. It then draws a second entry into liver cells, another schizont, metacryptozoites or metacryptomerozoites, a mega-metacryptozoite branch that repeats the hepatic cycle, and a micro-metacryptozoite branch entering RBCs. The small diagrams depict hepatocytes containing dividing parasites, release of daughter forms, and a separate erythrocyte containing a trophozoite. Every label is retained here to identify the drawing.</p><p><strong>Source correction:</strong> that repeated mega/micro hepatic-cycle model is an older account and should not be taught as the established human malaria life cycle. Blood-stage merozoites do not normally re-enter hepatocytes to restart that loop. In P. vivax and P. ovale, relapses arise from dormant liver forms called hypnozoites that later reactivate, not from perpetual reinvasion of liver cells by erythrocytic merozoites. P. falciparum and P. malariae do not have hypnozoites. Exo-erythrocytic means outside erythrocytes and includes liver development; it does not by itself validate the source's secondary hepatic loop.</p>"
    },
    {
      id: "plasmodium-blood-cycle",
      title: "Erythrocytic or Golgi cycle and blood-stage diagram",
      sources: [{ document: "biology", page: 4 }],
      html: "<ol><li>A merozoite enters an RBC and becomes a young trophozoite. The source calls the trophozoite the feeding stage.</li><li>A prominent parasite vacuole leaves a thin rim of cytoplasm and a chromatin dot, giving the signet-ring appearance. The nuclear dot is the parasite's nucleus; a mature human RBC has no nucleus to push aside.</li><li>The trophozoite grows. The next source label is amoeboid trophozoite, an appearance particularly conspicuous in P. vivax.</li><li>The mature parasite becomes a schizont. Nuclear divisions and segmentation generate daughter merozoites within the erythrocyte. The source drawing labels dots in this stage.</li><li>A segmented schizont may show a rosette arrangement, particularly the classical P. malariae form. Rosette is not a mandatory separate stage in every species.</li><li>The erythrocyte ruptures, releasing merozoites that can invade fresh RBCs. The sketch calls the residual disrupted erythrocyte a ghost cell.</li><li>Some parasites commit to sexual differentiation and form male or female gametocytes rather than simply continuing asexual blood multiplication.</li></ol><p>This repeated erythrocytic schizogony is the Golgi cycle in the notes. The bottom arrows label RBC merozoites and mega- or micromerozoites leading toward female and male gametocyte branches. Those older labels do not establish two universally recognizable sex-specific merozoite types. Use macrogametocyte for the female gametocyte and microgametocyte for the male; sexual commitment is a developmental process.</p>"
    },
    {
      id: "plasmodium-pigment-pathology",
      title: "Hemoglobin digestion, hemozoin and fever",
      sources: [{ document: "biology", page: 4 }, { document: "quick-revision", page: 159 }],
      html: "<p>The parasite digests host hemoglobin within its digestive compartment. The source splits Hb into globin, used nutritionally, and haematin/heme, leading to the pigment hemozoin. Free heme is toxic; crystallization into hemozoin helps the parasite handle this by-product. The pigment is released with other parasite material when infected erythrocytes rupture and can accumulate in phagocytic cells, including those of the spleen.</p><p>Red-cell rupture and host inflammatory responses contribute to fever paroxysms. Anemia also involves removal of infected and some uninfected erythrocytes and other host responses. The immune response is not reducible to one pigment acting alone.</p><p><strong>Source corrections:</strong> the statement that hemozoin is secreted after a post-erythrocytic cycle misplaces its production: it forms during hemoglobin digestion in erythrocytic parasites. The statement that hemozoin is released in the spleen where lysolecithin is secreted to kill RBCs is not a valid stand-alone mechanism of malarial hemolysis. The source's toxin symbol records a pathology association, but hemozoin is a crystallized heme product, not a secreted toxin identical to lysolecithin.</p><p>The source associates rising temperature with rigor with a useful time to find parasites. <strong>Source correction:</strong> testing for suspected malaria must not wait for a particular fever phase. Parasites may be detectable outside a paroxysm, and a negative initial test may require repeat testing according to the clinical situation.</p>"
    },
    {
      id: "plasmodium-mosquito-cycle",
      title: "Gametogenesis, fertilization, ookinete, oocyst and sporogony",
      sources: [{ document: "biology", page: 4 }, { document: "quick-revision", page: 159 }],
      html: "<ol><li>A female Anopheles ingests male microgametocytes and female macrogametocytes with human blood. The source notes that these stages escape ordinary digestion and continue development in the mosquito gut.</li><li>The microgametocyte undergoes exflagellation, producing motile flagellated male microgametes. The female macrogametocyte matures into a macrogamete; the handwritten megagametocyte label refers to this female branch.</li><li>The printed cone of reception is the classical description of the female gamete's contact region during fertilization, not a permanent cone required on every human-blood macrogametocyte.</li><li>A male and a female gamete fuse to form a diploid zygote, labelled 2n and synkaryon in the sketch. The male/female branches therefore join before the later mosquito-wall stages.</li><li>The zygote differentiates into a motile ookinete. This is the elongated form that crosses the mosquito midgut epithelium. Saying simply that the zygote is motile omits this differentiation.</li><li>An oocyst develops from the ookinete on the outer side of the midgut wall. The source calls this the stomach wall and draws the rounded oocyst beside the epithelial cells.</li><li>Following the sexual nuclear events and meiotic reduction, repeated division and sporogony generate numerous sporozoites inside the oocyst. The source labels the intervening sporozoite-producing masses sporoblasts.</li><li>Released sporozoites migrate to the salivary glands, where they are available for inoculation during a subsequent bite.</li></ol><p><strong>Source corrections:</strong> gametocytes develop in human blood before ingestion, rather than first being produced in the mosquito stomach. Gamete formation, fertilization and oocyst development occur in the mosquito. The handwritten bracket placing sporogony/sexual cycle under both female Anopheles and human being is misleading: humans supply gametocytes, but sporogony does not occur in human tissues. Likewise, the diagram's post-erythrocytic label denotes its mosquito-side continuation, not a new human organ phase.</p>"
    },
    {
      id: "plasmodium-history-treatment",
      title: "Discovery and treatment notes with their limits",
      sources: [{ document: "biology", page: 4 }],
      html: "<ul><li>Alphonse Laveran is associated with recognition of malaria parasites in human blood, including erythrocytes.</li><li>Ronald Ross is associated with demonstration of mosquito-associated parasite development; the source's FAM gut label summarizes the mosquito connection. His experimental work included avian malaria, so it is not an attribution of every human malaria life-cycle discovery to Ross alone.</li><li>Quinine is an antimalarial alkaloid obtained from Cinchona bark. The handwritten Chinchona spelling is corrected to Cinchona.</li><li><strong>Source correction:</strong> pre-erythrocytic cycle is not synonymous with drug-resistant phase. Activity depends on the drug and parasite stage; resistance is a parasite's reduced susceptibility to a drug, not merely a normal liver location. Dormant liver hypnozoites require specific stage-active treatment considerations, but this is not a reason to label all liver parasites universally resistant.</li></ul><p>The source supplies no dose, treatment duration or patient-specific regimen. Selection of therapy depends on species, severity, local resistance, pregnancy and other clinical factors; the pharmacology name above is a study fact, not a treatment instruction.</p>"
    },
    {
      id: "plasmodium-shared-paramecium-body",
      title: "Shared page 159: Paramecium body and ingestion structures",
      sources: [{ document: "quick-revision", page: 159 }],
      html: "<p>The printed page also begins Paramecium; its complete visible content is retained as shared-page material. John Hill is credited in the source with discovering and naming Paramecium. Historical naming and priority accounts vary, so the compound discovery claim is not used as a scored fact.</p><ul><li>The body is covered by a pellicle.</li><li>Trichocysts are listed with food capture, offence, defence and anchoring. They are cortical extrusomes; defence is a demonstrated role, but this list should not imply that all proposed functions are equally established or essential for filter feeding.</li><li>The written ingestion sequence is oral groove, vestibule, buccal cavity, cytostome and cytopharynx. These lead to food-vacuole formation.</li><li>The special oral ciliary groups are the dorsal quadrulus and ventral peniculi. These positional descriptions refer to the oral apparatus, not a claim that every dorsal body cilium is a quadrulus or every ventral cilium a peniculus.</li><li>Nutrition is holozoic, with ciliary filter feeding.</li><li>The food vacuole is described as analogous in digestive function to the gastrovascular cavity of Hydra. Digestion inside a Paramecium food vacuole is intracellular, whereas Hydra begins digestion extracellularly in its multicellular body's cavity.</li></ul>"
    },
    {
      id: "plasmodium-shared-paramecium-nuclei",
      title: "Shared page 159: nuclear types, vacuoles and killer strains",
      sources: [{ document: "quick-revision", page: 159 }],
      html: "<p>Paramecium is described as heterokaryotic, meaning nuclear dimorphism in this source. The macronucleus has vegetative functions and the micronucleus participates in germline reproduction. The ordinary model has one macronucleus; the printed always one is not valid during all nuclear reorganization stages.</p><table><thead><tr><th>Species</th><th>Micronuclei in the source model</th></tr></thead><tbody><tr><td>P. caudatum</td><td>One.</td></tr><tr><td>P. aurelia</td><td>Two.</td></tr><tr><td>P. multimicronucleatum</td><td>Many, as indicated by the species name.</td></tr></tbody></table><p>Contractile vacuoles perform osmoregulation. The page reports the posterior vacuole working faster than the anterior one; this is an observation for the described model and conditions, not an immutable rule for every cell. Kappa particles multiply in the cytoplasm and are bacterial endosymbionts associated with killer strains. Such strains produce the killing factor historically called paramecin. Cytoplasmic bacterial replication does not mean the trait is wholly independent of the host's nuclear genotype or that all Paramecium possess kappa particles.</p>"
    },
    {
      id: "plasmodium-shared-paramecium-reproduction",
      title: "Shared page 159: all reproductive entries",
      sources: [{ document: "quick-revision", page: 159 }],
      html: "<ul><li>Binary fission is the asexual method.</li><li>Autogamy is self-fertilization, with P. aurelia as the example. The source says produces a daughter Paramecium. Autogamy itself reorganizes nuclei by fusion within a cell; increased cell number requires subsequent division.</li><li>Cytogamy is listed for P. caudatum: paired cells reorganize their nuclei without exchanging the gametic nuclei.</li><li>Hemixis is reorganization of the macronucleus without change in the micronucleus.</li><li>Endomixis is called parthenogenesis with four daughter paramecia. <strong>Source correction:</strong> this is historical internal nuclear-reorganization terminology, not ordinary development from an unfertilized egg. Four descendants belong to the specified account with subsequent fissions, not the definition of endomixis.</li><li>Conjugation is described as the sexual process under unfavorable conditions. Nutritional stress can favor it in competent cells, but compatible mating types and physiological readiness also matter; not every unfavorable condition causes conjugation.</li><li>The synkaryon is the diploid fusion nucleus formed when a received migratory haploid pronucleus fuses with the stationary haploid pronucleus. The source calls them male and female pronuclei. It is the nucleus, not fusion of the entire two cells into one organism.</li></ul>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 159, status: "partial", sectionIds: ["plasmodium-species", "plasmodium-stippling-timing", "plasmodium-pigment-pathology", "plasmodium-mosquito-cycle", "plasmodium-shared-paramecium-body", "plasmodium-shared-paramecium-nuclei", "plasmodium-shared-paramecium-reproduction"], unresolved: ["The nominal 6/8/20/8-day prepatent values lack detection conditions and are paired with a definition ending at erythrocytic-cycle initiation; their intended measurement endpoint is not specified.", "The general incubation entry 14-28 days conflicts with the same page's falciparum 12-day row; ovale 14 days also differs from Biology page 4's 17 days. Values are preserved but not graded as constants."] },
    { document: "biology", page: 4, status: "partial", sectionIds: ["plasmodium-identity-hosts", "plasmodium-species", "plasmodium-stippling-timing", "plasmodium-liver-cycle", "plasmodium-blood-cycle", "plasmodium-pigment-pathology", "plasmodium-mosquito-cycle", "plasmodium-history-treatment"], unresolved: ["Ovale incubation is 17 days here versus 14 days on Quick Revision page 159, with no strain, range or other conditions given to reconcile them.", "The hepatic drawing's mega-/micro-metacryptozoite repeating-liver loop has no specified historical model species. Its labels are transcribed and its application to human malaria explicitly corrected, but the intended model cannot be identified from this page."] }
  ],
  questions: [
    {
      id: "note-plasmodium-001", text: "Which feature, rather than the severity of illness in humans, makes female Anopheles the definitive malaria host?",
      options: [{ key: "a", text: "It contains the first liver schizont" }, { key: "b", text: "It contains mature human erythrocytes" }, { key: "c", text: "It supports parasite gamete fusion" }, { key: "d", text: "It develops the highest fever peaks" }],
      answer: "c", explanation: "A definitive host is defined by the occurrence of sexual reproduction. Plasmodium gametes fuse in the mosquito gut; human liver and blood schizogony are asexual, regardless of how severe human disease becomes.", sectionId: "plasmodium-identity-hosts", source: { document: "biology", page: 4 }, cognitive: "understanding"
    },
    {
      id: "note-plasmodium-002", text: "A mosquito inoculates Plasmodium forms that subsequently invade hepatocytes. Which forms were inoculated?",
      options: [{ key: "a", text: "Sporozoites" }, { key: "b", text: "Ookinetes" }, { key: "c", text: "Macrogametes" }, { key: "d", text: "Blood schizonts" }],
      answer: "a", explanation: "Sporozoites are the salivary-gland forms inoculated into humans and capable of initiating liver infection. Ookinetes and gametes belong to mosquito-gut development, while blood schizonts develop within human RBCs.", sectionId: "plasmodium-liver-cycle", source: { document: "biology", page: 4 }, cognitive: "application"
    },
    {
      id: "note-plasmodium-003", text: "Which parasite forms in a human blood meal permit the next sexual phase in a female Anopheles?",
      options: [{ key: "a", text: "Dormant liver hypnozoites" }, { key: "b", text: "Mature mosquito-wall oocysts" }, { key: "c", text: "Salivary-gland sporozoites" }, { key: "d", text: "Male and female gametocytes" }],
      answer: "d", explanation: "The mosquito ingests microgametocytes and macrogametocytes from human blood. They give rise to gametes in the gut; liver hypnozoites, wall oocysts and salivary sporozoites are not the relevant human-blood forms.", sectionId: "plasmodium-mosquito-cycle", source: { document: "biology", page: 4 }, cognitive: "recall"
    },
    {
      id: "note-plasmodium-004", text: "The flagellated male gametes of Plasmodium are produced by which process after mosquito ingestion?",
      options: [{ key: "a", text: "Hepatic schizogony" }, { key: "b", text: "Microgametocyte exflagellation" }, { key: "c", text: "Erythrocyte encystment" }, { key: "d", text: "Macrogamete sporulation" }],
      answer: "b", explanation: "Exflagellation of a microgametocyte generates motile male microgametes. Hepatic schizogony produces asexual daughter forms, and the female gamete is not the source of exflagellating male gametes.", sectionId: "plasmodium-mosquito-cycle", source: { document: "quick-revision", page: 159 }, cognitive: "recall"
    },
    {
      id: "note-plasmodium-005", text: "An elongated fertilization product crosses the mosquito midgut epithelium. Which stage is being described?",
      options: [{ key: "a", text: "Sporozoite" }, { key: "b", text: "Ookinete" }, { key: "c", text: "Merozoite" }, { key: "d", text: "Gametocyte" }],
      answer: "b", explanation: "The zygote differentiates into a motile ookinete that traverses the midgut epithelium. It subsequently becomes an oocyst on the outer wall; the salivary sporozoite stage appears only later.", sectionId: "plasmodium-mosquito-cycle", source: { document: "biology", page: 4 }, cognitive: "application"
    },
    {
      id: "note-plasmodium-006", text: "Where does the oocyst normally develop after an ookinete crosses the mosquito gut?",
      options: [{ key: "a", text: "Inside a human liver cell" }, { key: "b", text: "Inside a human erythrocyte" }, { key: "c", text: "Within a mosquito salivary duct" }, { key: "d", text: "On the outer mosquito midgut wall" }],
      answer: "d", explanation: "The oocyst develops on the outer side of the mosquito midgut wall. Sporogony within it produces sporozoites, which later migrate to salivary glands; the glands are not the normal oocyst site.", sectionId: "plasmodium-mosquito-cycle", source: { document: "quick-revision", page: 159 }, cognitive: "recall"
    },
    {
      id: "note-plasmodium-007", text: "Which sequence correctly orders the mosquito stages after fertilization?",
      options: [{ key: "a", text: "Zygote, ookinete, oocyst, sporozoite" }, { key: "b", text: "Zygote, oocyst, ookinete, sporozoite" }, { key: "c", text: "Oocyst, zygote, sporozoite, ookinete" }, { key: "d", text: "Ookinete, sporozoite, zygote, oocyst" }],
      answer: "a", explanation: "Fusion gives the zygote, differentiation gives the invasive ookinete, and wall-associated development gives the oocyst. Sporogony then produces the sporozoites that reach the salivary glands.", sectionId: "plasmodium-mosquito-cycle", source: { document: "biology", page: 4 }, cognitive: "understanding"
    },
    {
      id: "note-plasmodium-008", text: "Which source term names the sporozoite-producing masses during development inside the oocyst?",
      options: [{ key: "a", text: "Hypnozoites" }, { key: "b", text: "Trophozoites" }, { key: "c", text: "Sporoblasts" }, { key: "d", text: "Macrogametes" }],
      answer: "c", explanation: "The printed source says sporozoites are formed from sporoblasts. This belongs to oocyst sporogony in the mosquito, not to dormant liver stages or the erythrocytic feeding trophozoite.", sectionId: "plasmodium-mosquito-cycle", source: { document: "quick-revision", page: 159 }, cognitive: "recall"
    },
    {
      id: "note-plasmodium-009", text: "A thin rim of parasite cytoplasm surrounds a vacuole, with a chromatin dot at one side inside an RBC. This appearance identifies the:",
      options: [{ key: "a", text: "Motile ookinete" }, { key: "b", text: "Mature oocyst" }, { key: "c", text: "Hepatic hypnozoite" }, { key: "d", text: "Young ring trophozoite" }],
      answer: "d", explanation: "The vacuole, cytoplasmic rim and parasite chromatin dot produce the signet-ring appearance of a young erythrocytic trophozoite. The dot is not a displaced human RBC nucleus because mature human RBCs are anucleate.", sectionId: "plasmodium-blood-cycle", source: { document: "biology", page: 4 }, cognitive: "application"
    },
    {
      id: "note-plasmodium-010", text: "What is the direct outcome when a mature erythrocytic schizont segments and its host cell ruptures?",
      options: [{ key: "a", text: "Release of mosquito-infective oocysts" }, { key: "b", text: "Release of RBC-invading merozoites" }, { key: "c", text: "Release of liver-dormant hypnozoites" }, { key: "d", text: "Release of flagellated microgametes" }],
      answer: "b", explanation: "Erythrocytic schizogony produces daughter merozoites that can invade fresh RBCs after rupture. Oocysts and microgametes are mosquito stages, while hypnozoites remain a liver-stage phenomenon.", sectionId: "plasmodium-blood-cycle", source: { document: "biology", page: 4 }, cognitive: "understanding"
    },
    {
      id: "note-plasmodium-011", text: "The Golgi cycle label in these notes refers to repeated parasite multiplication in which cells?",
      options: [{ key: "a", text: "Mosquito salivary cells" }, { key: "b", text: "Human nerve cells" }, { key: "c", text: "Human erythrocytes" }, { key: "d", text: "Mosquito ovarian cells" }],
      answer: "c", explanation: "The source uses Golgi cycle as a name for the erythrocytic cycle. It is the repeated trophozoite-schizont-merozoite sequence within and between human red blood cells, not a mosquito organ cycle.", sectionId: "plasmodium-blood-cycle", source: { document: "biology", page: 4 }, cognitive: "recall"
    },
    {
      id: "note-plasmodium-012", text: "Hemozoin is produced chiefly as the parasite handles which consequence of feeding?",
      options: [{ key: "a", text: "Free heme from hemoglobin digestion" }, { key: "b", text: "Urea from hepatic protein breakdown" }, { key: "c", text: "Chitin from the mosquito gut lining" }, { key: "d", text: "Bilirubin from human bile secretion" }],
      answer: "a", explanation: "Hemoglobin digestion releases heme, which is toxic in its free form. The parasite crystallizes it into hemozoin in its digestive compartment; it is not a pigment first secreted by the spleen to lyse RBCs.", sectionId: "plasmodium-pigment-pathology", source: { document: "biology", page: 4 }, cognitive: "understanding"
    },
    {
      id: "note-plasmodium-013", text: "Which staining association is appropriate for P. falciparum-infected erythrocytes in the source comparison?",
      options: [{ key: "a", text: "Maurer's dots or clefts" }, { key: "b", text: "Schuffner's stippling" }, { key: "c", text: "Ziemann's dots" }, { key: "d", text: "James' stippling" }],
      answer: "a", explanation: "The table associates falciparum infection with Maurer's dots or clefts. Schuffner's is used for vivax, Ziemann's for malariae, and James' for the ovale-associated stippling in the printed source.", sectionId: "plasmodium-stippling-timing", source: { document: "quick-revision", page: 159 }, cognitive: "recall"
    },
    {
      id: "note-plasmodium-014", text: "A synchronized quartan pattern produces an attack at noon Monday. At what time would the next attack occur after one 72-hour interval?",
      options: [{ key: "a", text: "Noon Tuesday" }, { key: "b", text: "Noon Wednesday" }, { key: "c", text: "Noon Thursday" }, { key: "d", text: "Noon Friday" }],
      answer: "c", explanation: "Seventy-two hours is three elapsed days: Monday noon plus 24 hours is Tuesday, plus 48 is Wednesday, and plus 72 is Thursday. Inclusive counting calls Monday day one and Thursday day four, hence quartan.", sectionId: "plasmodium-species", source: { document: "quick-revision", page: 159 }, cognitive: "application"
    },
    {
      id: "note-plasmodium-015", text: "Why can a fever recurring every two elapsed days be called tertian?",
      options: [{ key: "a", text: "Two days contain three 24-hour cycles" }, { key: "b", text: "The first attack is counted as day one" }, { key: "c", text: "The parasite alternates among three hosts" }, { key: "d", text: "Each red cell produces three gametocytes" }],
      answer: "b", explanation: "Tertian uses inclusive counting: an attack on day one recurs on day three, 48 hours later. It does not mean a 72-hour interval, three hosts or a fixed gametocyte count.", sectionId: "plasmodium-species", source: { document: "biology", page: 4 }, cognitive: "understanding"
    },
    {
      id: "note-plasmodium-016", text: "Which pairing distinguishes prepatency from incubation?",
      options: [{ key: "a", text: "Prepatency ends at fever; incubation at gamete fusion" }, { key: "b", text: "Prepatency ends at relapse; incubation at liver entry" }, { key: "c", text: "Prepatency ends at a bite; incubation at oocyst rupture" }, { key: "d", text: "Prepatency ends at detection; incubation at symptoms" }],
      answer: "d", explanation: "Prepatency runs from infection to first detectable blood parasitemia, whereas incubation runs from infection to symptoms. Detection and symptoms need not coincide, and neither interval is a universal fixed number of days.", sectionId: "plasmodium-stippling-timing", source: { document: "biology", page: 4 }, cognitive: "understanding"
    },
    {
      id: "note-plasmodium-017", text: "Which mechanism correctly explains a liver-derived relapse of vivax malaria after the initial blood infection has cleared?",
      options: [{ key: "a", text: "A mosquito oocyst divides inside the spleen" }, { key: "b", text: "Every blood merozoite returns to the liver" }, { key: "c", text: "A dormant hepatic hypnozoite reactivates" }, { key: "d", text: "A circulating zygote becomes a sporozoite" }],
      answer: "c", explanation: "Vivax and ovale can persist as dormant liver hypnozoites and later reactivate. This corrects the source's generalized repeating hepatic loop; erythrocytic merozoites do not normally reinvade hepatocytes to sustain that model.", sectionId: "plasmodium-liver-cycle", source: { document: "biology", page: 4 }, cognitive: "application"
    },
    {
      id: "note-plasmodium-018", text: "Why is it inaccurate to define all pre-erythrocytic parasites as drug-resistant?",
      options: [{ key: "a", text: "Drug activity depends on both compound and stage" }, { key: "b", text: "No antimalarial ever acts outside erythrocytes" }, { key: "c", text: "Liver location converts parasites into bacteria" }, { key: "d", text: "Resistance applies only to mosquito insecticides" }],
      answer: "a", explanation: "Normal stage-specific susceptibility differs from acquired drug resistance. Some compounds act against particular liver stages, so liver location alone cannot establish universal resistance to antimalarial drugs.", sectionId: "plasmodium-history-treatment", source: { document: "biology", page: 4 }, cognitive: "understanding"
    },
    {
      id: "note-plasmodium-019", text: "The plant source associated with the antimalarial alkaloid quinine is:",
      options: [{ key: "a", text: "Rauvolfia" }, { key: "b", text: "Digitalis" }, { key: "c", text: "Ephedra" }, { key: "d", text: "Cinchona" }],
      answer: "d", explanation: "Quinine is obtained from Cinchona bark. This is the source's pharmacognosy association; it does not specify a dose or establish quinine as the appropriate treatment for every malaria patient.", sectionId: "plasmodium-history-treatment", source: { document: "biology", page: 4 }, cognitive: "recall"
    },
    {
      id: "note-plasmodium-020", text: "Which statement avoids treating a historical malaria label as a guarantee about severity?",
      options: [{ key: "a", text: "Benign vivax infection cannot cause serious illness" }, { key: "b", text: "Vivax malaria can be severe despite its old label" }, { key: "c", text: "Every falciparum fever necessarily causes coma" }, { key: "d", text: "Quartan periodicity excludes all clinical danger" }],
      answer: "b", explanation: "Benign tertian is historical terminology, not a guarantee that vivax malaria is harmless. Severity varies, and falciparum infection does not always produce cerebral malaria or coma; fever periodicity alone does not establish safety.", sectionId: "plasmodium-species", source: { document: "quick-revision", page: 159 }, cognitive: "understanding"
    }
  ]
};