window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["protozoa"] = {
  id: "protozoa",
  subject: "Zoology",
  title: "Protozoa",
  sections: [
    {
      id: "protozoa-organization",
      title: "Protozoa, organization and ways of life",
      sources: [{ document: "biology", page: 26 }],
      html: "<p>Proto means first and zoa means animals. Protozoology is the study of protozoa. Antonie van Leeuwenhoek is conventionally called the father of protozoology and a pioneer of microscopy. The source places this material under Kingdom Protista. Protozoa is a traditional grouping of predominantly microscopic, unicellular, animal-like eukaryotes, not a single natural evolutionary lineage in modern classification.</p><ul><li>Organization is described as the protoplasmic grade: one cell performs the functions of an entire organism. There are no multicellular tissues or organ systems.</li><li>Nuclear number varies. Some forms have one nucleus, others two or many. Nuclear dimorphism means nuclei of different functional types, as in the macronucleus and micronucleus of ciliates. The source's word heterokaryotic refers here to this dimorphism, not to every protozoan being multinucleate.</li><li>Many amoeboid forms lack a fixed symmetry. Giardia has bilateral symmetry. The source's spherical example, Volvox, is a colonial green alga; its inclusion is part of the older broad treatment of protists, not evidence that it is an animal-like protozoan.</li><li>Pseudopodia provide locomotion in Amoeba, flagella in Euglena and Trypanosoma, and cilia in Paramecium.</li><li>Free-living examples listed are Amoeba, Euglena, Paramecium and Volvox. Parasitic examples are Entamoeba, Trypanosoma, Giardia, Trichomonas, Leishmania and Plasmodium; not every species of Entamoeba is pathogenic.</li><li>Most examples are solitary. Volvox and Proterospongia illustrate colonial organization in the source's broad protist comparison. Proterospongia is a colonial choanoflagellate, not a sponge.</li></ul>"
    },
    {
      id: "protozoa-physiology",
      title: "Nutrition, digestion, exchange and reproduction",
      sources: [{ document: "biology", page: 26 }, { document: "quick-revision", page: 158 }],
      html: "<ul><li>Holozoic nutrition involves ingestion of particles and intracellular digestion in food vacuoles. Holophytic or autotrophic nutrition uses photosynthesis. Saprozoic nutrition absorbs dissolved organic material; parasitic nutrition obtains resources from a host. Mixotrophy combines modes, with Euglena as the listed example.</li><li>Food-vacuole contents in the classical Amoeba and Paramecium account become acidic and subsequently less acidic or alkaline as digestion proceeds. This is a changing digestive compartment, not a fixed pH for every protist.</li><li><strong>Source correction:</strong> the handwritten description of trypsin as a universal protein-digesting enzyme is too broad. Intracellular proteases digest proteins, but pancreatic-type trypsin is not a universal protozoan enzyme. Likewise, the printed statement that an omnivorous Amoeba cannot digest fat is not a defensible general restriction on amoebal nutrition.</li><li>Respiratory gases and many soluble metabolic wastes exchange across the general cell surface by diffusion. This is distinct from expelling undigested food.</li><li>Contractile vacuoles collect and discharge excess water, chiefly for osmoregulation. The notes describe one or two in familiar freshwater examples. They are generally absent in the marine and parasitic examples being contrasted; their occurrence and number are not universal taxonomic rules.</li><li>Asexual processes listed are binary fission, multiple fission, budding and sporulation. Sexual processes include gamete formation followed by syngamy, and conjugation involving nuclear exchange. Sporulation alone must not be used as a definition of sexual reproduction.</li><li>The shorthand pinocytosis = taking in and exocytosis = throwing out is retained with a distinction: pinocytosis takes up extracellular fluid in vesicles, whereas exocytosis releases vesicular contents outside.</li></ul>"
    },
    {
      id: "protozoa-historical-classification",
      title: "Historical locomotory classification and all listed examples",
      sources: [{ document: "quick-revision", page: 158 }, { document: "biology", page: 26 }, { document: "biology", page: 27 }, { document: "biology", page: 28 }],
      html: "<p>The source classifies protozoa by locomotory structures into Sarcodina/Rhizopoda, Mastigophora/Flagellata, Sporozoa, Ciliata and Suctoria. These are historical teaching categories; they should not be substituted for modern evolutionary classification.</p><table><thead><tr><th>Source group</th><th>Features and examples</th></tr></thead><tbody><tr><td>Rhizopoda or Sarcodina</td><td>Pseudopodia; free-living and parasitic forms. The naked, changing body and single nucleus describe Amoeba-like models, not all historical rhizopods. Amoeba proteus is a freshwater animalcule with blunt lobopodia. Pelomyxa is listed as a giant amoeba. Entamoeba supplies parasitic and commensal examples.</td></tr><tr><td>Mastigophora or Flagellata</td><td>Flagella; free-living and parasitic forms. A pellicle helps maintain shape in the examples discussed. Listed genera are Trichomonas, Trypanosoma, Giardia, Leishmania, Trichonympha and Proterospongia; Euglena is another locomotory example.</td></tr><tr><td>Sporozoa</td><td>Endoparasitic forms, conventionally described as lacking conspicuous locomotory organelles and contractile vacuoles. Plasmodium causes malaria; Monocystis inhabits earthworm seminal vesicles; Eimeria causes coccidiosis in rabbits and chickens.</td></tr><tr><td>Ciliata</td><td>Cilia and commonly contractile vacuoles; free-living or endoparasitic examples. Paramecium is the free-living slipper animalcule. The lists also name Vorticella, Nyctotherus, Balantidium and historically Opalina.</td></tr><tr><td>Suctoria</td><td>The source places these with ciliates under Ciliophora and notes nuclear dimorphism. Young dispersal stages bear cilia; adults generally lack cilia and have feeding tentacles. Examples: Acineta, Ephelota and Podophrya.</td></tr></tbody></table><p><strong>Source corrections:</strong> Suctoria are specialized ciliates, not a separate modern protozoan phylum. Opalina, found in the rectum of frogs and toads, is an opalinid stramenopile rather than a true ciliate; the handwritten spelling Epalina is normalized accordingly. Eimeria is not appropriately described simply as a blood parasite: the rabbit/chicken examples chiefly infect intestinal or, in some species, biliary tissues. Apicomplexans can glide, and some gametes are flagellated, so no locomotion is an oversimplification. Their sexual cycle includes gamete fusion; spore formation alone is not sex. Noctiluca is the listed bioluminescent dinoflagellate. Proterospongia is historically used to illustrate similarities between choanoflagellates and sponge choanocytes, not a demonstrated direct ancestor.</p>"
    },
    {
      id: "protozoa-amoeba-feeding",
      title: "Amoeboid movement and particle capture",
      sources: [{ document: "quick-revision", page: 158 }, { document: "biology", page: 27 }, { document: "biology", page: 30 }],
      html: "<p>Amoeba proteus forms lobopodia. The sol-gel account explains movement through changes in cytoplasmic consistency and viscosity, with streaming into a projecting pseudopodium. It is a classical description of actin-dependent cell movement, not movement of blood plasma.</p><table><thead><tr><th>Term</th><th>Process and situation</th></tr></thead><tbody><tr><td>Phagocytosis</td><td>Pseudopodia engulf a solid particle or prey, enclosing it in a food vacuole. The source contrasts large food particles with dissolved nutrients.</td></tr><tr><td>Circumvallation</td><td>Pseudopodia encircle and contain active, mobile or relatively large prey before the enclosing surfaces meet. The diagram shows projections building a boundary around the food particle.</td></tr><tr><td>Circumfluence</td><td>The cell flows around relatively inactive, immobile or easily surrounded smaller prey. The diagram shows the cell outline extending around the particle rather than leaving it outside.</td></tr><tr><td>Invagination</td><td>A local infolding of the membrane forms a pocket or tube. The printed account calls this tube-forming engulfment; Biology page 30 describes an infolding enclosing extracellular fluid and dissolved nutrients in a vesicle.</td></tr><tr><td>Import</td><td>The older printed terminology describes passive intake of food. This descriptive label should not imply that all vesicle formation or nutrient transport is energetically passive.</td></tr></tbody></table><p><strong>Source distinction:</strong> invagination describes a membrane shape change, not an additional nutrient class. The fluid-uptake version on page 30 overlaps pinocytosis; it is not a completely independent process. The drawings distinguish the original cell outline, advancing pseudopodia, an external food particle and its eventual enclosure. Both circumvallation and circumfluence are forms of particle ingestion, not different digestive enzymes.</p>"
    },
    {
      id: "protozoa-vesicle-processes",
      title: "Fluid uptake, selective uptake, recycling and egestion",
      sources: [{ document: "biology", page: 30 }, { document: "biology", page: 26 }],
      html: "<table><thead><tr><th>Process</th><th>Mechanism and use</th></tr></thead><tbody><tr><td>Pinocytosis</td><td>Extracellular fluid and small dissolved molecules are enclosed in small vesicles. The notes contrast absorption from a dilute solution with capturing solid prey. Fluid uptake does not require the cell to build a large pseudopodial enclosure.</td></tr><tr><td>Receptor-mediated endocytosis</td><td>Selected extracellular molecules bind membrane receptors. The membrane then invaginates and internalizes the bound material in vesicles. The important contrast is selective capture rather than indiscriminate bulk fluid uptake.</td></tr><tr><td>Autophagy</td><td>Damaged or unnecessary components of the cell itself are enclosed in a membrane-bound compartment that joins the lysosomal degradation pathway. Recycling becomes important during nutrient scarcity or cellular stress. This is intracellular recycling, not engulfment of external food.</td></tr><tr><td>Exocytosis</td><td>A vesicle fuses with the plasma membrane and releases its contents. After digestion, this can remove undigested residue. Exocytosis also serves secretion; it is not restricted to waste removal.</td></tr><tr><td>Endocytosis</td><td>The general term for bringing external substances into a cell in vesicles. Particle uptake, fluid uptake and selective receptor-dependent uptake are included.</td></tr></tbody></table><p>The source's repeated summary condenses the same distinctions: phagocytosis takes particles; circumvallation contains mobile prey; circumfluence surrounds inactive prey; invagination is inward folding; pinocytosis takes fluid; receptors confer selectivity; autophagy recycles internal components; exocytosis releases material; endocytosis is the umbrella term. These processes are not nine mutually exclusive alternatives. Undigested food removal is egestion, whereas elimination of metabolic products is excretion.</p>"
    },
    {
      id: "protozoa-entamoeba",
      title: "Entamoeba and the intestinal or oral comparisons",
      sources: [{ document: "quick-revision", page: 158 }, { document: "biology", page: 26 }, { document: "biology", page: 27 }],
      html: "<p>Entamoeba histolytica causes amoebiasis, which can produce amoebic dysentery, gastrointestinal illness and invasion of the mucosa and submucosa of the large-intestinal wall. Invasive disease may spread to the liver and produce an amoebic liver abscess. The printed phrase fetal condition is an error in this context: liver abscess is a complication of invasive infection, not a fetal developmental stage.</p><ul><li>The mature infective cyst has four nuclei: quadrinucleate and tetranucleate mean the same thing. Infection follows ingestion of cysts in fecally contaminated water, food or on contaminated hands.</li><li><strong>Source correction:</strong> houseflies can mechanically carry cysts to food, but they are neither an obligatory biological host nor the main definition of transmission. The essential route is fecal-oral. The life cycle is direct or monogenetic, without an intermediate animal host.</li><li>A contractile vacuole is absent in the parasite. The source contrasts the host environment with hypotonic freshwater; this is not a claim that every host compartment has one exactly fixed osmotic concentration.</li><li>The handwritten phrase causes acidic vacuole has no clear biological referent. Its intended meaning remains unresolved and is not used in a question.</li><li>Shigella is the contrasting bacterial cause of bacillary dysentery; it is not an amoeba.</li><li>Entamoeba coli is a generally nonpathogenic commensal of the human colon. Do not confuse it with Escherichia coli, a bacterium.</li><li>The source describes intestinal Escherichia coli as obtaining nutrients in the host intestine and producing vitamin K. Some intestinal strains can synthesize menaquinones, but nutritional contribution varies. Some strains cause foodborne disease; not every E. coli strain is pathogenic.</li><li>Entamoeba gingivalis occurs in the buccal cavity and is associated with periodontal disease. It has no established cyst stage and may pass in saliva or on contaminated oral items; the printed reference to kissing concerns trophozoite transfer.</li><li><strong>Source correction:</strong> the claim that pyorrhoea is caused by Trichomonas buccalis and aggravated by Entamoeba gingivalis oversimplifies a multifactorial periodontal disease. Trichomonas tenax is the usual modern name of the oral trichomonad referred to by the old buccalis name. Associations with diseased gums do not establish either organism as the sole cause.</li></ul>"
    },
    {
      id: "protozoa-disease-table",
      title: "The source disease and symptom table",
      sources: [{ document: "biology", page: 26 }, { document: "quick-revision", page: 158 }],
      html: "<table><thead><tr><th>Organism and disease</th><th>Listed symptom or effect</th></tr></thead><tbody><tr><td>Plasmodium: malaria</td><td>High fever.</td></tr><tr><td>African human trypanosomes: sleeping sickness</td><td>Neurological symptoms, particularly after nervous-system involvement.</td></tr><tr><td>Leishmania: leishmaniasis; L. donovani: visceral leishmaniasis or kala-azar</td><td>The handwritten symptom cell contains only a bullet, with no symptom supplied.</td></tr><tr><td>Giardia: giardiasis</td><td>Diarrhoea and abdominal pain.</td></tr><tr><td>Entamoeba histolytica: amoebiasis</td><td>Dysentery and gastrointestinal problems.</td></tr><tr><td>Trichomonas vaginalis: trichomoniasis</td><td>A sexually transmitted infection that may cause vaginal infection and irritation.</td></tr></tbody></table><p>These are study associations, not a diagnostic rule that a symptom identifies one parasite. Vaginitis is the printed association with Trichomonas; the human sexually transmitted species is T. vaginalis. Sleeping sickness does not describe every Trypanosoma species, and not all leishmaniasis is visceral kala-azar.</p>"
    },
    {
      id: "protozoa-trypanosomes",
      title: "Trypanosoma species, diseases and vectors",
      sources: [{ document: "quick-revision", page: 158 }, { document: "biology", page: 27 }],
      html: "<table><thead><tr><th>Source name and disease</th><th>Vector and distinction</th></tr></thead><tbody><tr><td>Trypanosoma gambiense: West and Central African sleeping sickness, called Gambian fever</td><td>Modern name: Trypanosoma brucei gambiense. The source names the tsetse fly Glossina palpalis. Parasites occur in blood and lymph and can later invade the central nervous system.</td></tr><tr><td>Trypanosoma rhodesia: Rhodesian fever</td><td>Correct name: Trypanosoma brucei rhodesiense, causing East/Southern African sleeping sickness. The source names Glossina morsitans, a tsetse fly.</td></tr><tr><td>Trypanosoma cruzi: Chagas disease</td><td>Triatomine reduviid or kissing bugs, including Triatoma and Panstrongylus. The parasite typically enters when infective bug feces contaminate broken skin or a mucosal surface.</td></tr><tr><td>Trypanosoma evansi: surra in cattle and other animals</td><td>The source names Tabanus horseflies. Transmission is mechanical, unlike the biological development of African human trypanosomes in tsetse flies.</td></tr></tbody></table><p><strong>Source corrections:</strong> Chagas disease is American trypanosomiasis, not American sleeping sickness. Triatoma is not a water bug, and Panstrongylus is the corrected spelling of the printed Panstroylus. The two Glossina species are source examples, not exclusive vector lists. The handwritten Trypanosoma spelling is normalized to gambiense rather than retained as a nonexistent species.</p>"
    },
    {
      id: "protozoa-leishmania",
      title: "Leishmania forms, hosts and disease distribution",
      sources: [{ document: "quick-revision", page: 158 }, { document: "biology", page: 27 }],
      html: "<p>Leishmania donovani causes visceral leishmaniasis, also called kala-azar, black fever or Dumdum fever in the notes. The life cycle is digenetic in the source's sense of involving a vertebrate host and a sandfly. Different forms occur in the two hosts.</p><table><thead><tr><th>Form</th><th>Features and location</th></tr></thead><tbody><tr><td>Amastigote</td><td>The intracellular multiplying form in human mononuclear phagocytes, including macrophages of the reticuloendothelial system. The older label is leishmanial form. It lacks a free external flagellum; calling it a feeding stage contrasts it with the transmitted promastigote.</td></tr><tr><td>Promastigote</td><td>An elongated form with a free flagellum; the older label is leptomonad or Leptomonas form. It develops in the sandfly alimentary tract. Metacyclic promastigotes are the form infective to humans during a sandfly bite.</td></tr></tbody></table><p><strong>Source corrections:</strong> the handwritten human form labelled mastigate should be amastigote. It is not simply a freely circulating flagellate in human blood. The printed salivary gland and gut entry should not be learned literally: promastigotes develop in the sandfly gut and accumulate near the anterior gut/proboscis for transmission, not as a required salivary-gland stage like malaria sporozoites.</p><ul><li>Leishmania tropica is associated with cutaneous disease of the skin.</li><li>Leishmania braziliensis is associated with mucocutaneous disease, including damage to nasal and oral mucosa; the source calls this the naso-oral cavity.</li><li>The branching diagram therefore reads: sandfly/promastigote, transmission to human, human intracellular amastigote, and return to the sandfly during feeding. It contrasts morphology and host location, not two unrelated parasites.</li></ul>"
    },
    {
      id: "protozoa-giardia",
      title: "Giardia: habitat, dimorphism and transmission",
      sources: [{ document: "biology", page: 27 }, { document: "biology", page: 26 }, { document: "quick-revision", page: 158 }],
      html: "<p>Giardia lamblia, also called G. duodenalis or G. intestinalis, causes giardiasis. The source's mnemonic old man of the intestine refers to the face-like appearance of the trophozoite, especially its two nuclei. Trophozoites occupy the duodenum and upper jejunum and attach to the intestinal lining.</p><table><thead><tr><th>Cyst</th><th>Trophozoite</th></tr></thead><tbody><tr><td>Resistant, infective form acquired by ingestion through the fecal-oral route.</td><td>Active feeding and multiplying form in the upper small intestine.</td></tr><tr><td>A mature cyst is quadrinucleate.</td><td>Usually binucleate and bilaterally symmetrical.</td></tr><tr><td>Survives outside the host better than the trophozoite.</td><td>Pear-shaped or racket-like; the source uses badminton/tennis shaped as a visual mnemonic, not a literal spherical tennis-ball shape.</td></tr></tbody></table><p>Listed effects are diarrhoea, bloating and abdominal pain. The treatment names in the source are metronidazole and tinidazole; these are pharmacology associations, not a self-treatment schedule. The dimorphism diagram separates the infective cyst from the feeding trophozoite and must not reverse their nuclear counts.</p>"
    },
    {
      id: "protozoa-malaria-overview",
      title: "Malaria material on the shared classification page",
      sources: [{ document: "quick-revision", page: 158 }],
      html: "<ul><li>Charles Louis Alphonse Laveran identified the malaria parasite as the causative organism of malaria.</li><li>Ronald Ross demonstrated the relationship between malaria parasites and mosquitoes, including development associated with the mosquito gut wall. His experimental work included avian malaria; it should not be reduced to discovery of every detail of human malaria transmission.</li><li>Giovanni Battista Grassi and colleagues established the role of female Anopheles in the human malaria life cycle.</li><li>Asexual multiplication by schizogony occurs in human liver cells and red blood cells. In the traditional host terminology, humans are intermediate or secondary hosts.</li><li>Gamete formation and fertilization occur in the female Anopheles gut; the resulting ookinete crosses the gut wall, and sporogony occurs in an oocyst on its outer surface. Sporozoites subsequently reach the salivary glands.</li><li>Sporozoites are the form inoculated into humans during a bite by an infective female Anopheles.</li></ul><p><strong>Source correction:</strong> the printed grouping of gametogony and sporogony in the gut wall and salivary gland conflates locations. Salivary glands receive sporozoites; they are not the site of parasite fertilization or oocyst sporogony. The mosquito is the definitive host because sexual reproduction occurs there.</p>"
    },
    {
      id: "protozoa-paramecium-structure",
      title: "Paramecium pellicle, cilia and diagram labels",
      sources: [{ document: "biology", page: 28 }],
      html: "<p>Paramecium is the slipper animalcule. It is free-living and can be maintained by the infusion method, in which an infusion supports the microbes on which it feeds. Its pellicle maintains the characteristic body outline while permitting flexibility.</p><ul><li>The surface diagram shows a hexagonal cortical depression, a projecting cilium and its basal granule or kinetosome. The kinetosome anchors and organizes the cilium beneath the surface.</li><li>The whole-cell drawing labels the pellicle, cilia, oral groove, large macronucleus, small micronucleus, contractile vacuoles and their radiating canals. The two vacuoles collect water through their associated canals and discharge it outside.</li><li>Holotrichous is the source's traditional term for cilia distributed over the body. Longer cilia at the posterior end form a caudal tuft; the handwritten tail mnemonic refers to this position.</li><li>Trichocysts are cortical extrusomes in the ectoplasm. They can rapidly discharge filaments. The source contrasts an attachment interpretation with older defence/offence descriptions; they should not be taught as exclusively attachment organs, because defensive functions are documented.</li><li>Kappa particles are cytoplasmic bacterial endosymbionts in certain killer strains. They are associated with the killing factor historically called paramecin and illustrate cytoplasmic inheritance; they are not present in every Paramecium.</li><li><strong>Source corrections:</strong> the pellicle is an organized membrane/cortical complex, not simply gelatin. Movement toward a cathode is galvanotaxis or electrotaxis. Rheotaxis is orientation to a water current, so the source's negative rheotaxis arrow pointing toward the cathode mixes two different stimuli.</li></ul>"
    },
    {
      id: "protozoa-paramecium-feeding",
      title: "Paramecium feeding path and food-vacuole circulation",
      sources: [{ document: "biology", page: 28 }, { document: "biology", page: 26 }],
      html: "<p>Paramecium has holozoic nutrition and uses ciliary currents to collect suspended food. The source compares filter feeding with that of baleen whales, sponges and the freshwater mussel Unio; these organisms share a feeding strategy, not homologous oral organs.</p><ol><li>The oral groove directs food toward the vestibule, which collects incoming particles.</li><li>The cytostome is the cell mouth. Food passes through it to the cytopharynx, or cell gullet.</li><li>Food vacuoles, called gastrioles in the notes, form and undergo intracellular digestion. Their contents pass through an acidic phase and later become less acidic or alkaline.</li><li>Food vacuoles circulate through the endoplasm by cyclosis. This cytoplasmic streaming distributes digestive compartments and their absorbed products.</li><li>Undigested residue leaves through the cytoproct or cytopyge, the cell anus. This is egestion, not the primary route of nitrogenous-waste diffusion.</li></ol><p>The handwritten phrase resembling intercellular digestion is corrected to intracellular digestion: food is digested inside one cell, not between cells. Cilia, mouth, gullet, food vacuoles and cell anus are distinct structures; the contractile vacuole belongs to water balance rather than this food pathway.</p>"
    },
    {
      id: "protozoa-paramecium-nuclei",
      title: "Nuclear dimorphism and division",
      sources: [{ document: "biology", page: 28 }, { document: "biology", page: 29 }],
      html: "<table><thead><tr><th>Macronucleus</th><th>Micronucleus</th></tr></thead><tbody><tr><td>Somatic nucleus controlling everyday metabolism, physiology and much gene expression.</td><td>Germline nucleus carrying hereditary information used in sexual processes and nuclear exchange.</td></tr><tr><td>Divides amitotically during ordinary binary fission in the classical account.</td><td>Divides mitotically during binary fission; undergoes meiosis during sexual nuclear reorganization.</td></tr><tr><td>The old macronucleus degenerates during conjugation, and new macronuclei differentiate from descendants of the fusion nucleus.</td><td>Produces haploid pronuclei that participate in exchange and fusion.</td></tr></tbody></table><p><strong>Source correction:</strong> both nuclear types possess a nuclear envelope. The handwritten macronucleus entry no nuclear membrane is false; amitotic division does not mean absence of a nuclear envelope. The different roles explain nuclear dimorphism, not a prokaryotic versus eukaryotic division inside the same cell.</p>"
    },
    {
      id: "protozoa-paramecium-fission",
      title: "Transverse binary fission and its diagram",
      sources: [{ document: "biology", page: 29 }],
      html: "<p>During favorable conditions, Paramecium reproduces asexually by transverse binary fission. The micronucleus divides mitotically and the macronucleus divides amitotically; the cell then separates across its long axis. The anterior daughter is the proter and the posterior daughter the opisthe. Each restores the structures it needs, including an appropriate oral apparatus and contractile-vacuole system.</p><p>The source diagram labels the anterior/proter and posterior/opisthe pieces and shows one contractile-vacuole region in each prospective daughter. Its statement that the oral groove first disappears is too absolute: oral structures undergo remodeling, the proter retains the parental oral apparatus in the standard account, and the opisthe develops a new one.</p><p>The page gives both 2-3 times per day and a time of 30 minutes-2 hours. These may refer to population doubling versus the visible division process, but no conditions or definition of the second interval are supplied. Both source numbers are retained here as an unresolved timing statement, not as compatible universal rates or graded facts.</p>"
    },
    {
      id: "protozoa-nuclear-processes",
      title: "Autogamy, endomixis, hemixis and cytogamy",
      sources: [{ document: "biology", page: 29 }],
      html: "<ul><li><strong>Autogamy:</strong> self-fertilization in which two haploid gametic nuclei formed within one individual fuse. The source gives Paramecium aurelia and the mnemonic one mother gives two gametes. The mother here is one cell; the gametes are gametic nuclei.</li><li><strong>Endomixis:</strong> a historical term for internal nuclear reorganization without exchange with another individual. The source associates it with P. aurelia and a one-parent-to-four-descendants diagram. The exact nuclear details are model-dependent.</li><li><strong>Hemixis:</strong> the source's purification act, involving reorganization or fragmentation of the macronucleus without corresponding change in the micronucleus. It is not the production of a new individual by fusion.</li><li><strong>Cytogamy:</strong> paired cells undergo a sexual nuclear process without exchanging pronuclei; nuclear fusion occurs internally in each participant.</li><li><strong>Conjugation:</strong> temporary pairing and exchange of gametic nuclei. Nuclear reorganization and genetic recombination are associated with the classical description of rejuvenation after repeated fission and senescence.</li></ul><p><strong>Source corrections:</strong> autogamy is a sexual nuclear process despite its placement under the handwritten asexual heading. Endomixis is not equivalent to ordinary parthenogenesis, which means development from an unfertilized egg. Historical accounts differ among Paramecium species and should not be merged into a single universal reproductive sequence.</p>"
    },
    {
      id: "protozoa-conjugation",
      title: "Conjugation: nuclear sequence and descendant counts",
      sources: [{ document: "biology", page: 29 }, { document: "quick-revision", page: 160 }],
      html: "<p>The drawings and the printed continuation present the classical single-micronucleus Paramecium caudatum teaching model. This should be distinguished from other species, including the P. aurelia examples used for autogamy and endomixis.</p><ol><li>Two compatible cells join along their oral surfaces. The oral region is reorganized and a cytoplasmic bridge permits nuclear exchange.</li><li>The old macronucleus degenerates. The micronucleus undergoes meiosis to form four haploid nuclei; three degenerate.</li><li>The surviving haploid nucleus divides mitotically, producing a stationary pronucleus and a migratory pronucleus.</li><li>The migratory pronucleus passes into the partner. Each received pronucleus fuses with the stationary pronucleus there. The resulting diploid fusion nucleus is the synkaryon.</li><li>The conjugants separate as exconjugants. Fusion belongs to the exchange process; the page layout places cell separation before the fusion drawing, but that layout must not be mistaken for the required biological order.</li><li>In each exconjugant, three successive mitotic divisions of the synkaryon produce eight nuclear descendants. Four become macronuclear anlagen and four are initially micronuclear.</li><li>In the printed model, three of those four micronuclei degenerate. The remaining micronucleus divides during the subsequent two cell fissions so that each daughter receives a micronucleus.</li><li>Each exconjugant produces four daughter paramecia, each with a macronucleus and micronucleus. Two exconjugants therefore yield eight descendants after these later fissions.</li></ol><p><strong>Source distinction:</strong> the handwritten oval containing four large and four small nuclei is a schematic intermediate, not the final stable nuclear complement of each daughter. The mnemonic 1 + 1 becomes 8 includes the later fissions; conjugation itself does not immediately turn two cells into eight or directly increase their number.</p>"
    },
    {
      id: "protozoa-shared-page-behaviour",
      title: "Shared page 160: taxis and animal migration",
      sources: [{ document: "quick-revision", page: 160 }],
      html: "<p>The following adjacent material is retained because it occupies the same assigned image as the conjugation continuation.</p><table><thead><tr><th>Orientation</th><th>Meaning and source examples</th></tr></thead><tbody><tr><td>Klinotaxis</td><td>Sequential sampling of stimulus direction, often by side-to-side movements. The page gives Planaria moving toward food. Its phrase incapable of discriminating the source means no simultaneous bilateral comparison, not an inability ever to locate a stimulus.</td></tr><tr><td>Tropotaxis</td><td>Orientation through simultaneous comparison by paired receptors, bringing a bilaterally symmetrical organism into alignment. Listed examples are Argulus, Planaria and ticks; the mechanism depends on the receptors and experimental situation.</td></tr><tr><td>Telotaxis</td><td>Selection of one of two competing stimulus sources rather than an intermediate direction. The source gives a visiting honeybee.</td></tr><tr><td>Menotaxis</td><td>Maintaining a constant angle to a directional cue. Examples: honeybees and homing ants returning home.</td></tr><tr><td>Mnemotaxis</td><td>Orientation using a learned configuration of environmental cues. The listed example is a hunting wasp; remembered landmarks, not merely stimulus complexity, distinguish the mechanism.</td></tr></tbody></table><table><thead><tr><th>Fish migration</th><th>Route and examples</th></tr></thead><tbody><tr><td>Diadromous</td><td>Movement between freshwater and the sea; the umbrella category for the following three patterns.</td></tr><tr><td>Anadromous</td><td>From the sea to freshwater for breeding: salmon, hilsa and sea lamprey in the source.</td></tr><tr><td>Catadromous</td><td>From freshwater to the sea for breeding: European and American eels, Anguilla.</td></tr><tr><td>Amphidromous</td><td>Movement between fresh and salt water as part of the life cycle, not primarily a spawning migration: gobies are the example.</td></tr><tr><td>Potamodromous</td><td>Migration entirely within freshwater: freshwater populations of carps and trout.</td></tr><tr><td>Oceanodromous</td><td>Migration entirely within the sea: herring, mackerels and tunas.</td></tr></tbody></table><p>Bird migration is contrasted by direction: latitudinal migration runs north-south and back, with golden plover as the example; longitudinal migration runs east-west and back, with starlings as the example. These describe route patterns, not rules that every population of the named bird or fish migrates identically. Some trout populations are anadromous, so trout is not exclusively potamodromous.</p>"
    },
    {
      id: "protozoa-shared-page-origins",
      title: "Shared page 160: historical ideas about life's origin",
      sources: [{ document: "quick-revision", page: 160 }],
      html: "<ul><li>Theory of special creation: the source associates this with Hebrew religious tradition. It is a religious account, not an experimentally established biological theory or an attribution to a scientist named Hebrew.</li><li>Spontaneous generation: the historical claim that organisms routinely arise directly from nonliving material under ordinary present-day conditions. This is distinct from scientific research into ancient chemical origins of life.</li><li>Panspermia or the cosmozoic theory: the source attributes the proposal to Richter, printed Ritcher. It proposes arrival of life or its precursors from elsewhere and does not by itself explain their ultimate origin.</li><li>Catastrophism: associated with Georges Cuvier. The source also calls him the father of modern palaeontology.</li><li>Biogenesis: the experimental tradition associated with Francesco Redi, Lazzaro Spallanzani and Louis Pasteur, supporting generation of organisms from pre-existing organisms under the tested conditions.</li><li>Germ theory of disease: the source associates it with Pasteur. Germplasm theory is a different idea associated with August Weismann; the names must not be interchanged.</li><li>The source labels Leonardo da Vinci father of palaeontology and Cuvier father of modern palaeontology. Leonardo made important early interpretations of fossils, but these honorifics vary between historical accounts and are not exclusive scientific discoveries.</li></ul><p>Homologous organs, introduced at the bottom of the page, have a common evolutionary origin and may serve different functions. Common origin is the defining criterion; different function is a frequent comparison, not an obligatory requirement for homology.</p>"
    },
    {
      id: "protozoa-shared-page-links",
      title: "Shared page 160: the complete connecting-link table",
      sources: [{ document: "quick-revision", page: 160 }, { document: "biology", page: 26 }, { document: "biology", page: 27 }],
      html: "<p>Connecting link is historical comparative terminology. The source associations below are preserved with their modern limitations; they do not identify a living species as the literal ancestor of two whole groups.</p><table><thead><tr><th>Listed organism</th><th>Source comparison and qualification</th></tr></thead><tbody><tr><td>Viruses</td><td>Living and nonliving: acellular infectious entities that reproduce using host cells; not a taxonomic intermediate between life and inert matter.</td></tr><tr><td>Euglena</td><td>Plants and animals: combines photosynthesis with motility and other modes of nutrition; a euglenid, not a literal plant-animal hybrid.</td></tr><tr><td>Proterospongia</td><td>Protozoa and Porifera: a colonial choanoflagellate illustrating similarities with sponge collar cells.</td></tr><tr><td>Peripatus</td><td>Annelida and Arthropoda: the traditional comparison of wormlike and arthropod-like features. It belongs to Onychophora, not Annelida.</td></tr><tr><td>Neopilina</td><td>Annelida and Mollusca: serial repetition of some organs motivated the old comparison. It is a monoplacophoran mollusc.</td></tr><tr><td>Seymouria</td><td>Amphibia and reptiles: an extinct reptiliomorph with a mosaic of features, not a modern reptile.</td></tr><tr><td>Dipnoi or lungfish</td><td>Fishes and amphibians: lung-bearing sarcopterygians relevant to comparisons with the origin of tetrapods; living lungfish are not amphibian ancestors.</td></tr><tr><td>Balanoglossus</td><td>Nonchordates and chordates: a hemichordate sharing deuterostome characters. Its stomochord is not a true notochord.</td></tr><tr><td>Chimaera</td><td>Cartilaginous and bony fishes in the old table. It is a holocephalan cartilaginous fish, not an intermediate bony fish.</td></tr><tr><td>Archaeopteryx</td><td>Reptiles and birds: a fossil early avialan combining ancestral theropod and avian features. Modern birds are themselves within the reptile lineage.</td></tr><tr><td>Ornithorhynchus, the platypus</td><td>Reptiles and mammals: an egg-laying monotreme mammal with a mosaic of features, not a reptile-mammal hybrid.</td></tr></tbody></table>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 158, status: "transcribed", sectionIds: ["protozoa-physiology", "protozoa-historical-classification", "protozoa-amoeba-feeding", "protozoa-entamoeba", "protozoa-disease-table", "protozoa-trypanosomes", "protozoa-leishmania", "protozoa-giardia", "protozoa-malaria-overview"], unresolved: [] },
    { document: "quick-revision", page: 160, status: "transcribed", sectionIds: ["protozoa-conjugation", "protozoa-shared-page-behaviour", "protozoa-shared-page-origins", "protozoa-shared-page-links"], unresolved: [] },
    { document: "biology", page: 26, status: "partial", sectionIds: ["protozoa-organization", "protozoa-physiology", "protozoa-historical-classification", "protozoa-vesicle-processes", "protozoa-entamoeba", "protozoa-disease-table", "protozoa-giardia", "protozoa-paramecium-feeding", "protozoa-shared-page-links"], unresolved: ["Right-hand disease table: the Leishmania symptoms/effects cell has a bullet but no symptom text; the intended entry is absent."] },
    { document: "biology", page: 27, status: "partial", sectionIds: ["protozoa-historical-classification", "protozoa-amoeba-feeding", "protozoa-entamoeba", "protozoa-trypanosomes", "protozoa-leishmania", "protozoa-giardia", "protozoa-shared-page-links"], unresolved: ["Left column, Entamoeba histolytica: 'causes Acidic vacuole' is legible but has no coherent specified pathological meaning; the intended fact cannot be reconstructed."] },
    { document: "biology", page: 28, status: "transcribed", sectionIds: ["protozoa-historical-classification", "protozoa-paramecium-structure", "protozoa-paramecium-feeding", "protozoa-paramecium-nuclei"], unresolved: [] },
    { document: "biology", page: 29, status: "partial", sectionIds: ["protozoa-paramecium-nuclei", "protozoa-paramecium-fission", "protozoa-nuclear-processes", "protozoa-conjugation"], unresolved: ["Binary-fission timing: '2-3 times/day' and 'Time: 30 min-2 hrs' appear together without defining whether the latter is division duration or generation time; no universal timing answer is inferred."] },
    { document: "biology", page: 30, status: "transcribed", sectionIds: ["protozoa-amoeba-feeding", "protozoa-vesicle-processes"], unresolved: [] }
  ],
  questions: [
    {
      id: "note-protozoa-001", text: "A protist has a large somatic nucleus and a smaller germline nucleus. Which description best fits this observation?",
      options: [{ key: "a", text: "Multicellular tissue organization" }, { key: "b", text: "Functional nuclear dimorphism" }, { key: "c", text: "Prokaryotic chromosome division" }, { key: "d", text: "Colonial reproductive specialization" }],
      answer: "b", explanation: "The macronucleus and micronucleus differ in function within a single cell, so this is nuclear dimorphism. It neither creates a multicellular tissue nor makes either nucleus prokaryotic.", sectionId: "protozoa-organization", source: { document: "biology", page: 26 }, cognitive: "understanding"
    },
    {
      id: "note-protozoa-002", text: "The blunt temporary projections used by Amoeba proteus are specifically called:",
      options: [{ key: "a", text: "Axopodia" }, { key: "b", text: "Reticulopodia" }, { key: "c", text: "Filopodia" }, { key: "d", text: "Lobopodia" }],
      answer: "d", explanation: "Amoeba proteus forms broad, blunt lobopodia. Axopodia are stiff radiating projections, reticulopodia form networks, and filopodia are slender extensions rather than the model's characteristic lobes.", sectionId: "protozoa-historical-classification", source: { document: "biology", page: 27 }, cognitive: "recall"
    },
    {
      id: "note-protozoa-003", text: "Water continually enters a freshwater protist by osmosis. Which activity directly prevents excessive accumulation?",
      options: [{ key: "a", text: "Repeated discharge of contractile vacuoles" }, { key: "b", text: "Repeated formation of digestive vacuoles" }, { key: "c", text: "Repeated exchange of haploid pronuclei" }, { key: "d", text: "Repeated breakdown of the macronucleus" }],
      answer: "a", explanation: "Contractile vacuoles collect excess intracellular water and discharge it, maintaining osmotic balance. Food vacuoles digest particles, while nuclear exchange and macronuclear breakdown are reproductive events.", sectionId: "protozoa-physiology", source: { document: "biology", page: 26 }, cognitive: "application"
    },
    {
      id: "note-protozoa-004", text: "An amoeba builds pseudopodial walls around a rapidly moving prey item before enclosing it. Which source term describes this capture?",
      options: [{ key: "a", text: "Circumfluence" }, { key: "b", text: "Pinocytosis" }, { key: "c", text: "Circumvallation" }, { key: "d", text: "Exocytosis" }],
      answer: "c", explanation: "Circumvallation means encircling and containing active prey with pseudopodia. Circumfluence describes flowing around less active prey; pinocytosis takes fluid and exocytosis releases contents.", sectionId: "protozoa-amoeba-feeding", source: { document: "biology", page: 30 }, cognitive: "application"
    },
    {
      id: "note-protozoa-005", text: "During starvation, a cell encloses its own damaged organelles for lysosomal degradation. The process is:",
      options: [{ key: "a", text: "Phagocytosis" }, { key: "b", text: "Circumfluence" }, { key: "c", text: "Autophagy" }, { key: "d", text: "Pinocytosis" }],
      answer: "c", explanation: "Autophagy recycles the cell's own components, especially during stress or nutrient shortage. The other listed processes concern uptake of material from outside the cell, not internal organelle recycling.", sectionId: "protozoa-vesicle-processes", source: { document: "biology", page: 30 }, cognitive: "application"
    },
    {
      id: "note-protozoa-006", text: "Which feature distinguishes receptor-mediated uptake from bulk uptake of extracellular fluid?",
      options: [{ key: "a", text: "Specific ligands bind surface receptors" }, { key: "b", text: "External fluid contacts the cell surface" }, { key: "c", text: "Membrane surrounds an internal vesicle" }, { key: "d", text: "Cytoplasm is enclosed by a cell membrane" }],
      answer: "a", explanation: "Selective binding of a ligand to its receptor is the distinguishing step. Both receptor-mediated endocytosis and bulk pinocytosis can use membrane-bound vesicles and begin at the cell surface.", sectionId: "protozoa-vesicle-processes", source: { document: "biology", page: 30 }, cognitive: "understanding"
    },
    {
      id: "note-protozoa-007", text: "Which ingested form initiates the usual fecal-oral infection by Entamoeba histolytica?",
      options: [{ key: "a", text: "A binucleate trophozoite" }, { key: "b", text: "An octonucleate mature cyst" }, { key: "c", text: "A flagellated promastigote" }, { key: "d", text: "A quadrinucleate mature cyst" }],
      answer: "d", explanation: "The mature infective E. histolytica cyst has four nuclei. Quadrinucleate and tetranucleate are synonyms. Its acquisition is by ingestion, not by inoculation of a flagellated Leishmania form.", sectionId: "protozoa-entamoeba", source: { document: "quick-revision", page: 158 }, cognitive: "recall"
    },
    {
      id: "note-protozoa-008", text: "A housefly deposits amoebic cysts on food but the parasite does not develop in the fly. The fly's role is best described as:",
      options: [{ key: "a", text: "An obligatory intermediate host" }, { key: "b", text: "A mechanical carrier of cysts" }, { key: "c", text: "A definitive host for syngamy" }, { key: "d", text: "A host for hepatic schizogony" }],
      answer: "b", explanation: "Transport without parasite development is mechanical carriage. E. histolytica has a direct life cycle; a fly can contaminate food but is not a required intermediate or definitive host.", sectionId: "protozoa-entamoeba", source: { document: "biology", page: 27 }, cognitive: "application"
    },
    {
      id: "note-protozoa-009", text: "Which identification avoids confusing two organisms often abbreviated E. coli?",
      options: [{ key: "a", text: "Entamoeba coli is a commensal protist" }, { key: "b", text: "Entamoeba coli is a flagellated bacterium" }, { key: "c", text: "Escherichia coli is a ciliated protist" }, { key: "d", text: "Escherichia coli is an intestinal amoeba" }],
      answer: "a", explanation: "Entamoeba coli is a generally nonpathogenic amoeboid commensal in the colon. Escherichia coli is a bacterium, and the shared abbreviation does not imply that the two are the same kind of organism.", sectionId: "protozoa-entamoeba", source: { document: "biology", page: 27 }, cognitive: "understanding"
    },
    {
      id: "note-protozoa-010", text: "A pear-shaped Giardia cell with two nuclei is attached to the upper small-intestinal lining. It is the:",
      options: [{ key: "a", text: "Resistant mature cyst" }, { key: "b", text: "Flagellated microgamete" }, { key: "c", text: "Active trophozoite" }, { key: "d", text: "Encysted oocyst stage" }],
      answer: "c", explanation: "The binucleate, pear-shaped Giardia trophozoite feeds and multiplies on the duodenal and upper jejunal lining. A mature infective cyst instead has four nuclei and is adapted for transmission.", sectionId: "protozoa-giardia", source: { document: "biology", page: 27 }, cognitive: "application"
    },
    {
      id: "note-protozoa-011", text: "Which Giardia stage-feature pairing is correct?",
      options: [{ key: "a", text: "Mature cyst: two nuclei and active feeding" }, { key: "b", text: "Mature cyst: four nuclei and transmission" }, { key: "c", text: "Trophozoite: four nuclei and encystment wall" }, { key: "d", text: "Trophozoite: one nucleus and tissue invasion" }],
      answer: "b", explanation: "The mature Giardia cyst is quadrinucleate and transmits infection after ingestion. The active trophozoite is binucleate; neither the stated one-nucleus nor four-nucleus trophozoite pairing is correct.", sectionId: "protozoa-giardia", source: { document: "biology", page: 27 }, cognitive: "recall"
    },
    {
      id: "note-protozoa-012", text: "In visceral leishmaniasis, which parasite form is expected inside human macrophages?",
      options: [{ key: "a", text: "A metacyclic trypomastigote" }, { key: "b", text: "A flagellated promastigote" }, { key: "c", text: "An encysted sporozoite" }, { key: "d", text: "An intracellular amastigote" }],
      answer: "d", explanation: "Leishmania multiplies as amastigotes within human mononuclear phagocytes. Promastigotes are the flagellated sandfly forms, with metacyclic promastigotes responsible for transmission to a new human host.", sectionId: "protozoa-leishmania", source: { document: "quick-revision", page: 158 }, cognitive: "recall"
    },
    {
      id: "note-protozoa-013", text: "Which location correctly replaces the source's misleading salivary-gland entry for Leishmania promastigote development?",
      options: [{ key: "a", text: "The human red blood cell" }, { key: "b", text: "The mosquito salivary duct" }, { key: "c", text: "The human liver hepatocyte" }, { key: "d", text: "The sandfly alimentary tract" }],
      answer: "d", explanation: "Promastigotes develop in the sandfly gut and reach its anterior region for transmission. A required salivary-gland phase would incorrectly copy the malaria sporozoite pathway onto Leishmania.", sectionId: "protozoa-leishmania", source: { document: "quick-revision", page: 158 }, cognitive: "understanding"
    },
    {
      id: "note-protozoa-014", text: "Which source-listed Leishmania species is associated chiefly with cutaneous lesions rather than visceral kala-azar?",
      options: [{ key: "a", text: "Leishmania donovani" }, { key: "b", text: "Leishmania tropica" }, { key: "c", text: "Trypanosoma evansi" }, { key: "d", text: "Giardia duodenalis" }],
      answer: "b", explanation: "The notes associate L. tropica with skin disease and L. donovani with visceral kala-azar. L. braziliensis is the separate mucocutaneous example involving nasal and oral mucosa.", sectionId: "protozoa-leishmania", source: { document: "biology", page: 27 }, cognitive: "recall"
    },
    {
      id: "note-protozoa-015", text: "The source's West and Central African sleeping-sickness row pairs T. brucei gambiense with which vector example?",
      options: [{ key: "a", text: "Glossina palpalis" }, { key: "b", text: "Triatoma infestans" }, { key: "c", text: "Anopheles stephensi" }, { key: "d", text: "Phlebotomus argentipes" }],
      answer: "a", explanation: "Glossina palpalis is the tsetse example listed for gambiense sleeping sickness. Triatoma is associated with Chagas disease, Anopheles with malaria and Phlebotomus with leishmaniasis.", sectionId: "protozoa-trypanosomes", source: { document: "quick-revision", page: 158 }, cognitive: "recall"
    },
    {
      id: "note-protozoa-016", text: "After a triatomine bug feeds, its infected feces contaminate a skin abrasion. Which infection mechanism fits?",
      options: [{ key: "a", text: "Malaria from injected oocysts" }, { key: "b", text: "Surra from swallowed trophozoites" }, { key: "c", text: "Chagas disease from T. cruzi" }, { key: "d", text: "Kala-azar from mature cysts" }],
      answer: "c", explanation: "T. cruzi can enter through damaged skin or mucosa contaminated with triatomine feces. This is Chagas disease, not African sleeping sickness or a malaria infection caused by injection of oocysts.", sectionId: "protozoa-trypanosomes", source: { document: "quick-revision", page: 158 }, cognitive: "application"
    },
    {
      id: "note-protozoa-017", text: "Which disease-organism pair belongs to the source row naming Tabanus as a mechanical vector?",
      options: [{ key: "a", text: "Kala-azar: Leishmania donovani" }, { key: "b", text: "Surra: Trypanosoma evansi" }, { key: "c", text: "Malaria: Plasmodium vivax" }, { key: "d", text: "Giardiasis: Giardia lamblia" }],
      answer: "b", explanation: "The table links surra in cattle with T. evansi and Tabanus horseflies. Mechanical carriage by a blood-feeding fly differs from parasite development within a required biological vector.", sectionId: "protozoa-trypanosomes", source: { document: "quick-revision", page: 158 }, cognitive: "recall"
    },
    {
      id: "note-protozoa-018", text: "Which traditional sporozoan example is associated with earthworm seminal vesicles?",
      options: [{ key: "a", text: "Monocystis" }, { key: "b", text: "Balantidium" }, { key: "c", text: "Vorticella" }, { key: "d", text: "Noctiluca" }],
      answer: "a", explanation: "Monocystis is the gregarine example associated with earthworm seminal vesicles. Balantidium and Vorticella are ciliates, while Noctiluca is the source's bioluminescent dinoflagellate example.", sectionId: "protozoa-historical-classification", source: { document: "biology", page: 28 }, cognitive: "recall"
    },
    {
      id: "note-protozoa-019", text: "Which correction best fits the Eimeria examples in the two source lists?",
      options: [{ key: "a", text: "They cause sleeping sickness in humans" }, { key: "b", text: "They are free-living freshwater ciliates" }, { key: "c", text: "They cause coccidiosis in animal tissues" }, { key: "d", text: "They are flagellates of sandfly saliva" }],
      answer: "c", explanation: "Eimeria causes coccidiosis, with rabbits and chickens as the source examples. Calling it simply a blood parasite loses the relevant intestinal or biliary tissue infections and is corrected in the section.", sectionId: "protozoa-historical-classification", source: { document: "quick-revision", page: 158 }, cognitive: "understanding"
    },
    {
      id: "note-protozoa-020", text: "A sessile protist has feeding tentacles as an adult, but its young dispersal stage is ciliated. Which source grouping fits?",
      options: [{ key: "a", text: "Rhizopoda, as in Amoeba" }, { key: "b", text: "Sporozoa, as in Plasmodium" }, { key: "c", text: "Flagellata, as in Giardia" }, { key: "d", text: "Suctoria, as in Acineta" }],
      answer: "d", explanation: "Suctorians such as Acineta have ciliated young and tentaculate adults. They are specialized ciliates in modern classification, even though the historical source lists Suctoria as a separate teaching group.", sectionId: "protozoa-historical-classification", source: { document: "biology", page: 28 }, cognitive: "application"
    },
    {
      id: "note-protozoa-021", text: "In the Paramecium sketch, radiating canals lead toward a star-like collecting structure. What is its main role?",
      options: [{ key: "a", text: "Collecting water for osmotic regulation" }, { key: "b", text: "Collecting gametes for nuclear fusion" }, { key: "c", text: "Collecting proteins for food digestion" }, { key: "d", text: "Collecting pigments for photosynthesis" }],
      answer: "a", explanation: "The radiating canals belong to a contractile-vacuole complex. They collect excess water for discharge, rather than collecting food or gametic nuclei. The oral groove and food vacuoles serve nutrition.", sectionId: "protozoa-paramecium-structure", source: { document: "biology", page: 28 }, cognitive: "understanding"
    },
    {
      id: "note-protozoa-022", text: "Paramecin production associated with kappa particles illustrates which kind of biological relationship?",
      options: [{ key: "a", text: "A universal chloroplast-based trait" }, { key: "b", text: "An obligatory nuclear meiotic stage" }, { key: "c", text: "A contractile-vacuole digestive process" }, { key: "d", text: "A cytoplasmic endosymbiont-associated trait" }],
      answer: "d", explanation: "Kappa particles are bacterial endosymbionts in certain killer strains and are associated with paramecin production. The example concerns cytoplasmic inheritance, not a universal organelle found in every Paramecium.", sectionId: "protozoa-paramecium-structure", source: { document: "biology", page: 28 }, cognitive: "recall"
    },
    {
      id: "note-protozoa-023", text: "After food crosses the cytostome of Paramecium, which structure receives it before a digestive vacuole forms?",
      options: [{ key: "a", text: "Cytoproct" }, { key: "b", text: "Cytopharynx" }, { key: "c", text: "Kinetosome" }, { key: "d", text: "Trichocyst" }],
      answer: "b", explanation: "The cytostome is the cell mouth and leads to the cytopharynx or cell gullet, where food-vacuole formation follows. The cytoproct is the egestion site, the kinetosome anchors a cilium, and a trichocyst is an extrusome.", sectionId: "protozoa-paramecium-feeding", source: { document: "biology", page: 28 }, cognitive: "recall"
    },
    {
      id: "note-protozoa-024", text: "Which statement about the two Paramecium nuclear types is biologically correct?",
      options: [{ key: "a", text: "Only the germline nucleus has an envelope" }, { key: "b", text: "Only the somatic nucleus has an envelope" }, { key: "c", text: "Both nuclear types have nuclear envelopes" }, { key: "d", text: "Neither nuclear type has a nuclear envelope" }],
      answer: "c", explanation: "Both the macronucleus and micronucleus are membrane-enclosed eukaryotic nuclei. The source's no-membrane entry for the macronucleus is incorrect; its amitotic division does not imply absence of an envelope.", sectionId: "protozoa-paramecium-nuclei", source: { document: "biology", page: 28 }, cognitive: "understanding"
    },
    {
      id: "note-protozoa-025", text: "A Paramecium orients toward the cathode in an applied electric field. Which term identifies the stimulus correctly?",
      options: [{ key: "a", text: "Chemotaxis" }, { key: "b", text: "Rheotaxis" }, { key: "c", text: "Galvanotaxis" }, { key: "d", text: "Phototaxis" }],
      answer: "c", explanation: "Galvanotaxis is directional movement in response to an electric field. Rheotaxis concerns water flow, chemotaxis chemicals and phototaxis light, so the source's cathode/rheotaxis pairing must be corrected.", sectionId: "protozoa-paramecium-structure", source: { document: "biology", page: 28 }, cognitive: "application"
    },
    {
      id: "note-protozoa-026", text: "The anterior daughter formed by transverse division of Paramecium is called the:",
      options: [{ key: "a", text: "Opisthe" }, { key: "b", text: "Proter" }, { key: "c", text: "Synkaryon" }, { key: "d", text: "Kinetosome" }],
      answer: "b", explanation: "Proter names the anterior daughter and opisthe the posterior daughter. A synkaryon is a fusion nucleus, whereas a kinetosome is the basal body of a cilium; neither names a daughter cell.", sectionId: "protozoa-paramecium-fission", source: { document: "biology", page: 29 }, cognitive: "recall"
    },
    {
      id: "note-protozoa-027", text: "In the source's historical terminology, macronuclear reorganization without a corresponding micronuclear change is:",
      options: [{ key: "a", text: "Conjugation" }, { key: "b", text: "Autogamy" }, { key: "c", text: "Cytogamy" }, { key: "d", text: "Hemixis" }],
      answer: "d", explanation: "Hemixis is the source's purification or macronuclear reorganization process without a corresponding micronuclear change. Conjugation, autogamy and cytogamy instead involve gametic nuclear events.", sectionId: "protozoa-nuclear-processes", source: { document: "biology", page: 29 }, cognitive: "recall"
    },
    {
      id: "note-protozoa-028", text: "Two haploid gametic nuclei formed within a single Paramecium fuse without exchange with another cell. This is:",
      options: [{ key: "a", text: "Autogamy" }, { key: "b", text: "Binary fission" }, { key: "c", text: "Hemixis" }, { key: "d", text: "Budding" }],
      answer: "a", explanation: "Autogamy is self-fertilization through fusion of gametic nuclei from the same cell. It is a sexual nuclear process, even though the handwritten page mistakenly places it under an asexual heading.", sectionId: "protozoa-nuclear-processes", source: { document: "biology", page: 29 }, cognitive: "understanding"
    },
    {
      id: "note-protozoa-029", text: "In the specified classical conjugation model, each of two exconjugants later forms four daughters. How many descendants result after those fissions?",
      options: [{ key: "a", text: "Eight descendants" }, { key: "b", text: "Four descendants" }, { key: "c", text: "Six descendants" }, { key: "d", text: "Sixteen descendants" }],
      answer: "a", explanation: "There are two exconjugants and four descendants from each, so 2 times 4 equals 8. The count includes postconjugational fissions; conjugation itself does not immediately increase the two-cell population.", sectionId: "protozoa-conjugation", source: { document: "quick-revision", page: 160 }, cognitive: "application"
    },
    {
      id: "note-protozoa-030", text: "Which pair fuses to produce the synkaryon in each conjugating Paramecium?",
      options: [{ key: "a", text: "Two degenerating somatic macronuclei" }, { key: "b", text: "Received and stationary haploid pronuclei" }, { key: "c", text: "A contractile vacuole and a micronucleus" }, { key: "d", text: "Two unchanged diploid parent micronuclei" }],
      answer: "b", explanation: "The migratory haploid pronucleus received from the partner fuses with the local stationary haploid pronucleus. Their fusion restores diploidy in the synkaryon; the old macronucleus degenerates instead of participating.", sectionId: "protozoa-conjugation", source: { document: "biology", page: 29 }, cognitive: "understanding"
    }
  ]
};