window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["s-block"] = {
  id: "s-block",
  subject: "Chemistry",
  title: "Hydrogen, water and s-block elements",
  sections: [
    {
      id: "permanent-hardness-and-heavy-water",
      title: "Permanent hardness and heavy water",
      sources: [{ document: "quick-revision", page: 94 }],
      html: "<p>The page begins with the continuation of water hardness. Permanent hardness is associated with dissolved chlorides and sulfates of calcium and magnesium. Unlike bicarbonate hardness, it is not removed simply by ordinary boiling.</p><ul><li><strong>Calgon treatment:</strong> the source writes sodium hexametaphosphate as Na<sub>2</sub>[Na<sub>4</sub>(PO<sub>3</sub>)<sub>6</sub>], compositionally Na<sub>6</sub>P<sub>6</sub>O<sub>18</sub> or (NaPO<sub>3</sub>)<sub>6</sub>. It binds or sequesters hardness ions in soluble complexes, preventing their usual hardness reactions. Sequestration is not the same as physically removing all calcium and magnesium from the water.</li><li><strong>Ion exchange:</strong> exchanges hardness-causing ions for other ions on an exchanger.</li><li><strong>Zeolite or permutit process:</strong> the sodium form exchanges its sodium ions for Ca<sup>2+</sup> and Mg<sup>2+</sup>. This is a particular ion-exchange softening method.</li></ul><p>Heavy water is D<sub>2</sub>O, with deuterium replacing protium. It is used as a neutron moderator in certain nuclear reactors: moderation slows neutrons, rather than simply absorbing every neutron or serving as the nuclear fuel.</p>"
    },
    {
      id: "hydrogen-peroxide-preparation",
      title: "All hydrogen-peroxide preparation routes",
      sources: [{ document: "quick-revision", page: 94 }],
      html: "<p>Hydrogen peroxide has formula H<sub>2</sub>O<sub>2</sub>. The source gives three preparation schemes.</p><ol><li><strong>Hydrated barium peroxide and sulfuric acid:</strong> BaO<sub>2</sub>&middot;H<sub>2</sub>O + H<sub>2</sub>SO<sub>4</sub> &rarr; BaSO<sub>4</sub> + H<sub>2</sub>O<sub>2</sub> + H<sub>2</sub>O, retaining the hydrate form actually printed. The sulfate precipitates. For a different hydration state, the water coefficient must change accordingly.</li><li><strong>Peroxodisulfuric-acid route:</strong> the printed sequence is sulfuric-acid electrolysis to H<sub>2</sub>S<sub>2</sub>O<sub>8</sub>, followed by hydrolysis to peroxide and regenerated acid. A complete overall electrolysis equation is 2H<sub>2</sub>SO<sub>4</sub> &rarr; H<sub>2</sub>S<sub>2</sub>O<sub>8</sub> + H<sub>2</sub>. Hydrolysis is H<sub>2</sub>S<sub>2</sub>O<sub>8</sub> + 2H<sub>2</sub>O &rarr; H<sub>2</sub>O<sub>2</sub> + 2H<sub>2</sub>SO<sub>4</sub>. The regenerated acid may be represented as 2H<sup>+</sup> + 2HSO<sub>4</sub><sup>-</sup>, as on the source page.</li><li><strong>Anthraquinone cycle:</strong> 2-ethylanthraquinol, the reduced hydroquinone form, is oxidized by oxygen from air to form H<sub>2</sub>O<sub>2</sub> and the corresponding 2-ethylanthraquinone. Hydrogen with a Pd catalyst regenerates the reduced carrier. The carrier is cycled; it is not consumed as the final peroxide product.</li></ol><p><strong>Source correction:</strong> The abbreviated electrolysis arrow omits the cathodic hydrogen product, and the hydrolysis arrow omits reactant water. The completed equations conserve atoms; the printed arrows alone are process summaries, not balanced standalone equations. The source does not specify concentrations, cell conditions or a complete operating procedure.</p>"
    },
    {
      id: "peroxide-volume-strength",
      title: "Volume strength, concentration and normality",
      sources: [{ document: "quick-revision", page: 94 }],
      html: "<p>On complete decomposition, 2H<sub>2</sub>O<sub>2</sub> &rarr; 2H<sub>2</sub>O + O<sub>2</sub>. Volume strength is the volume of oxygen produced at the specified reference conditions by one volume of peroxide solution. Ten-volume peroxide therefore gives ten litres of oxygen per litre of solution.</p><p>The source's factors use the historical gas convention 273.15 K and 1 atm, with oxygen molar volume approximately 22.4 L mol<sup>-1</sup>. One mole H<sub>2</sub>O<sub>2</sub> gives half a mole O<sub>2</sub>, or 11.2 L. If $C$ is peroxide molarity, $S=11.2C$, where $S$ is volume strength. Under the usual two-electron redox convention, normality $N=2C$, so $S=5.6N$.</p><ul><li>Ten-volume solution has $C=\\frac{10}{11.2}=0.8929$ mol L<sup>-1</sup> approximately.</li><li>Using molar mass 34.0 g mol<sup>-1</sup>, its concentration is approximately 30.36 g L<sup>-1</sup>; the source rounds this to 30.35 g L<sup>-1</sup>.</li><li>This corresponds to approximately 3.036 g per 100 mL, or 3.036% mass/volume; the source gives 3.035% without naming the percentage basis.</li><li>A mass percentage cannot be inferred exactly without solution density. A different oxygen reference temperature or pressure changes the factors 11.2 and 5.6.</li></ul><p><strong>Source qualifications:</strong> The percentage is interpreted as mass per volume to be consistent with its grams-per-litre value. Normality is reaction-dependent; the stated relation assumes the two-electron oxidation-reduction equivalent, not every possible acid-base use of H<sub>2</sub>O<sub>2</sub>.</p>"
    },
    {
      id: "hydrogen-and-water-exam-points",
      title: "Hydrogen spin forms, water test and named processes",
      sources: [{ document: "quick-revision", page: 94 }],
      html: "<ul><li><strong>Ortho and para hydrogen:</strong> distinguished by the relative nuclear spins of the two protons in H<sub>2</sub>, not by different elemental identities. Ortho hydrogen has the proton-spin triplet arrangement; para hydrogen has the singlet arrangement.</li><li><strong>Atomic hydrogen and CO:</strong> the source associates atomic hydrogen reacting with carbon monoxide with formaldehyde. The formal net addition is CO + 2[H] &rarr; HCHO. The source supplies no medium, generation method or selectivity conditions, so this is not a claim that CO and ordinary molecular H<sub>2</sub> automatically give formaldehyde.</li><li><strong>Anhydrous copper sulfate test:</strong> anhydrous CuSO<sub>4</sub> is white and turns blue on hydration. It tests for the presence of water in the examined material. <strong>Source correction:</strong> A positive result does not prove that an unknown colourless liquid is pure water; a water-containing mixture can also hydrate the salt.</li><li><strong>Peroxide use:</strong> the source calls H<sub>2</sub>O<sub>2</sub> a solvent and antiseptic in toothpaste. Its relevant role in suitably formulated oral-care products is oxidizing, bleaching or antimicrobial action, not a characteristic general-purpose solvent role. This is a description of formulated products, not a recommendation to use concentrated peroxide.</li><li><strong>Named hydrogen-manufacture processes:</strong> Lane's process, Uyeno's process and Bosch's process. The source provides the recall mnemonic LUB. No reaction sequence or operating conditions accompany these three names on the page.</li></ul>"
    },
    {
      id: "alkali-metal-properties",
      title: "s-block membership and alkali-metal properties",
      sources: [{ document: "quick-revision", page: 94 }, { document: "quick-revision", page: 96 }],
      html: "<p>The differentiating electron of an s-block element enters an s subshell. The source discusses groups 1 and 2: alkali metals and alkaline-earth metals. Hydrogen has an s configuration but is not an alkali metal; helium has 1s<sup>2</sup> although it belongs to group 18.</p><p>Alkali metals have outer configuration ns<sup>1</sup>: Li, Na, K, Rb, Cs and Fr. They react with water to form alkaline hydroxides and hydrogen, summarized by 2M + 2H<sub>2</sub>O &rarr; 2MOH + H<sub>2</sub>. Their generally low melting and boiling temperatures decrease from Li toward Cs.</p><ul><li>Their densities are relatively low and broadly increase down the group. <strong>Source correction:</strong> This is not monotonic: potassium is less dense than sodium.</li><li>They tarnish on exposure to air and are protected from air and moisture in suitable inert storage media. <strong>Source correction:</strong> The printed exception claiming lithium does not tarnish is false; lithium also reacts with atmospheric oxygen, nitrogen and moisture. The source mentions kerosene as a protective medium.</li><li>The isolated neutral atoms have an unpaired ns electron, whereas M<sup>+</sup> ions have closed shells. This explains the source's paramagnetic-atom versus diamagnetic-salt comparison. <strong>Source qualification:</strong> Bulk-metal magnetism is a band property, and a salt containing a paramagnetic counterion need not be diamagnetic merely because its alkali cation is closed-shell.</li><li>Page 96 identifies dilute alkali-metal solutions in liquid ammonia as reducing agents. Sodium gives a blue solution because of solvated electrons; those electrons are available for reduction. The reductant is the metal-electron solution, not pure liquid ammonia by itself.</li><li>Sodium reacts more vigorously with water than lithium under comparable conditions. The source attributes this to greater electropositive character; reaction rate also depends on kinetic and physical factors and must not be confused with the ranking of aqueous standard reduction potentials.</li><li>Electrolysis of fused halides is a standard route to certain alkali metals, including sodium and lithium. <strong>Source qualification:</strong> This is not the exclusive commercial route for every alkali metal. Aqueous electrolysis generally reduces water to hydrogen instead of depositing these highly reactive metals.</li></ul><table><thead><tr><th>Alkali metal</th><th>All source flame colours</th></tr></thead><tbody><tr><td>Li</td><td>Crimson red.</td></tr><tr><td>Na</td><td>Golden yellow.</td></tr><tr><td>K</td><td>Pale violet.</td></tr><tr><td>Rb</td><td>Reddish violet.</td></tr></tbody></table>"
    },
    {
      id: "alkali-trend-comparisons",
      title: "All alkali-metal trend comparisons",
      sources: [{ document: "quick-revision", page: 94 }],
      html: "<table><thead><tr><th>Property</th><th>Source trend with interpretation</th></tr></thead><tbody><tr><td>Electropositive character</td><td>Li &lt; Na &lt; K &lt; Rb &lt; Cs.</td></tr><tr><td>Hydration strength</td><td>Li<sup>+</sup> &gt; Na<sup>+</sup> &gt; K<sup>+</sup> &gt; Rb<sup>+</sup> &gt; Cs<sup>+</sup>, when comparing the magnitude of exothermic hydration enthalpy.</td></tr><tr><td>Hydroxide solubility and basic character</td><td>LiOH &lt; NaOH &lt; KOH &lt; RbOH &lt; CsOH as the source's general trend.</td></tr><tr><td>Carbonate thermal stability</td><td>Li<sub>2</sub>CO<sub>3</sub> &lt; Na<sub>2</sub>CO<sub>3</sub> &lt; K<sub>2</sub>CO<sub>3</sub> &lt; Rb<sub>2</sub>CO<sub>3</sub> &lt; Cs<sub>2</sub>CO<sub>3</sub>.</td></tr><tr><td>Bicarbonates</td><td>Thermal stability is generally summarized as increasing down the group. The printed chain NaHCO<sub>3</sub> &lt; KHCO<sub>3</sub> &gt; RbHCO<sub>3</sub> &lt; CsHCO<sub>3</sub> contains an inconsistent middle sign.</td></tr></tbody></table><p><strong>Source corrections:</strong> Hydration enthalpies are negative, so the first hydration ordering is of their magnitudes, not their signed algebraic values. The carbonate formula at the end is Cs<sub>2</sub>CO<sub>3</sub>, not the printed CsCO<sub>3</sub>. The exact bicarbonate ranking is not adopted as a scored fact because the page gives neither a thermal criterion nor consistent inequalities. LiHCO<sub>3</sub> is normally encountered in solution rather than as an isolable ordinary stable solid.</p><p>Lithium is the strongest reducing agent of these alkali metals in aqueous standard-state comparisons because strong hydration of Li<sup>+</sup> offsets the cost of atomization and ionization. The source names caesium as the strongest in dry conditions, reflecting easier electron loss by the larger atom; an actual nonaqueous redox ranking still requires a defined reaction and medium. The hydroxide basicity trend also must not be interpreted as a mandatory pH difference between equally concentrated, fully dissociated strong bases in water.</p>"
    },
    {
      id: "sodium-carbonate-solvay",
      title: "Washing soda and the complete Solvay sequence",
      sources: [{ document: "quick-revision", page: 95 }],
      html: "<p>Washing soda is Na<sub>2</sub>CO<sub>3</sub>&middot;10H<sub>2</sub>O. Sodium carbonate is made by the Solvay or ammonia-soda process; the hydrate is subsequently obtained by crystallization. The source lists NaCl, NH<sub>3</sub> and limestone as the raw materials. Ammonia participates in the process and is normally recovered for reuse.</p><ol><li>2NH<sub>3</sub> + H<sub>2</sub>O + CO<sub>2</sub> &rarr; (NH<sub>4</sub>)<sub>2</sub>CO<sub>3</sub>.</li><li>(NH<sub>4</sub>)<sub>2</sub>CO<sub>3</sub> + H<sub>2</sub>O + CO<sub>2</sub> &rarr; 2NH<sub>4</sub>HCO<sub>3</sub>.</li><li>NH<sub>4</sub>HCO<sub>3</sub> + NaCl &rarr; NH<sub>4</sub>Cl + NaHCO<sub>3</sub>; sodium bicarbonate precipitates under the process conditions.</li><li>On heating, 2NaHCO<sub>3</sub> &rarr; Na<sub>2</sub>CO<sub>3</sub> + H<sub>2</sub>O + CO<sub>2</sub>.</li></ol><p>The first two lines are the source's conventional solution-reaction representation; the key separation is the relatively low solubility of NaHCO<sub>3</sub> in cold ammoniated brine.</p><p><strong>Source correction:</strong> The usual Solvay process is unsuitable for making K<sub>2</sub>CO<sub>3</sub> because the analogous KHCO<sub>3</sub> intermediate is too soluble for efficient precipitation, not simply because final K<sub>2</sub>CO<sub>3</sub> is soluble in water. Sodium carbonate itself is also water-soluble.</p>"
    },
    {
      id: "sodium-hydroxide-salt-and-mixtures",
      title: "Caustic soda, crude salt and every named mixture",
      sources: [{ document: "quick-revision", page: 95 }, { document: "quick-revision", page: 96 }],
      html: "<p>Sodium hydroxide, NaOH, is caustic soda. The source names the historical Castner-Kellner cell, with a mercury cathode and carbon anode, for brine electrolysis. This is an aqueous chlor-alkali route to NaOH, not electrolysis of molten NaCl to obtain sodium metal. Modern membrane-cell production need not use mercury.</p><p>Crude sodium chloride is obtained by crystallization of brine. Its listed impurities are Na<sub>2</sub>SO<sub>4</sub>, CaSO<sub>4</sub>, MgCl<sub>2</sub> and CaCl<sub>2</sub>. <strong>Source correction:</strong> The deliquescent MgCl<sub>2</sub> and CaCl<sub>2</sub> impurities help make crude salt damp; the statement should not describe all four impurities as equally deliquescent.</p><table><thead><tr><th>Name</th><th>Composition in the source</th></tr></thead><tbody><tr><td>Fusion mixture</td><td>K<sub>2</sub>CO<sub>3</sub> + Na<sub>2</sub>CO<sub>3</sub>.</td></tr><tr><td>Soda lime</td><td>NaOH + CaO.</td></tr><tr><td>Pearl ash</td><td>K<sub>2</sub>CO<sub>3</sub>.</td></tr><tr><td>Soda ash</td><td>Na<sub>2</sub>CO<sub>3</sub>.</td></tr><tr><td>Black ash</td><td>Na<sub>2</sub>CO<sub>3</sub> + CaS, the characteristic mixture named in the older carbonate process.</td></tr></tbody></table><p><strong>Source correction:</strong> The page says Na<sub>2</sub>CO<sub>3</sub> exposed to air shows brisk 'effervescence'. Hydrated washing soda can instead show <em>efflorescence</em>, losing crystallization water in sufficiently dry air. Anhydrous sodium carbonate does not automatically bubble merely on air exposure. Effervescence means gas bubbling, as when a carbonate reacts with an acid.</p>"
    },
    {
      id: "chlorine-alkali-and-zinc-reactions",
      title: "Cold versus hot alkali and other sodium reactions",
      sources: [{ document: "quick-revision", page: 96 }],
      html: "<p><strong>Cold, dilute NaOH:</strong> Cl<sub>2</sub> + 2NaOH &rarr; NaCl + NaClO + H<sub>2</sub>O. The oxidized product is sodium hypochlorite. In the source's generic notation, NaXO is a sodium hypohalite.</p><p><strong>Hot, concentrated NaOH:</strong> 3Cl<sub>2</sub> + 6NaOH &rarr; 5NaCl + NaClO<sub>3</sub> + 3H<sub>2</sub>O. The oxidized product is sodium chlorate; NaXO<sub>3</sub> is the source's generic sodium halate.</p><p><strong>Source corrections:</strong> The prose gives chlorate for both hot and cold conditions, contradicting the cold/hypohalite row. The printed hot equation X<sub>2</sub> + 2NaOH &rarr; NaX + NaXO<sub>3</sub> + H<sub>2</sub>O is not balanced; the chlorine equation above supplies the correct 3:6:5:1:3 coefficients. These generic schemes are not universal for every halogen: fluorine reacts differently and unstable hypohalites need appropriate qualifications.</p><p>The page's 'Oxone: Na<sub>2</sub>O<sub>2</sub> + dilute HCl' entry describes the peroxide-forming reagent pair: Na<sub>2</sub>O<sub>2</sub> + 2HCl &rarr; 2NaCl + H<sub>2</sub>O<sub>2</sub>. The intended historical use of 'Oxone' is unspecified. Modern commercial Oxone commonly refers instead to the potassium peroxymonosulfate triple-salt mixture 2KHSO<sub>5</sub>&middot;KHSO<sub>4</sub>&middot;K<sub>2</sub>SO<sub>4</sub>; the trade name must not substitute for an unambiguous formula.</p><p>Excess NaOH reacting with Zn is represented in the source as sodium zincate plus hydrogen: Zn + 2NaOH &rarr; Na<sub>2</sub>ZnO<sub>2</sub> + H<sub>2</sub>. In strongly alkaline aqueous solution, write the hydroxo-complex form Zn + 2NaOH + 2H<sub>2</sub>O &rarr; Na<sub>2</sub>[Zn(OH)<sub>4</sub>] + H<sub>2</sub>. The first equation is a traditional anhydrous product representation; the source does not specify the phase conditions.</p>"
    },
    {
      id: "alkaline-earth-properties",
      title: "Alkaline-earth metals and flame colours",
      sources: [{ document: "quick-revision", page: 95 }],
      html: "<p>Group 2 metals have valence configuration ns<sup>2</sup>: Be, Mg, Ca, Sr, Ba and Ra. They are good thermal and electrical conductors. Their isolated ground-state valence electrons are paired, and their M<sup>2+</sup> ions have closed-shell noble-gas configurations.</p><p><strong>Source correction:</strong> The page says their melting and boiling points are lower than those of corresponding alkali metals because of smaller size. They are generally higher, associated with stronger metallic bonding and participation of two valence electrons, although numerical trends down group 2 are not perfectly regular. The source's blanket 'diamagnetic' statements should be confined to the appropriate closed-shell atoms or simple salts; counterions and bulk electronic structure also matter.</p><table><thead><tr><th>Metal</th><th>All listed flame colours</th></tr></thead><tbody><tr><td>Ca</td><td>Brick red.</td></tr><tr><td>Sr</td><td>Crimson red.</td></tr><tr><td>Ba</td><td>Apple green.</td></tr></tbody></table><p>These metals act as reducing agents, with reducing tendency broadly increasing from Be toward Ba while ionization energy generally falls. <strong>Source correction:</strong> The corresponding standard reduction potentials become more negative; reversing the half-reaction gives more positive oxidation potentials. The printed statement that oxidation potential decreases is inconsistent with the stated increasing reducing tendency unless it actually meant reduction potential.</p><p>Beryllium's small size and charge density help explain its diagonal relationship with aluminium, with similarities that differ from the usual behavior of the heavier group 2 metals.</p>"
    },
    {
      id: "alkaline-earth-trend-table",
      title: "Every group 2 trend row",
      sources: [{ document: "quick-revision", page: 95 }],
      html: "<table><thead><tr><th>Property</th><th>Source sequence and qualification</th></tr></thead><tbody><tr><td>Hydration-enthalpy magnitude</td><td>Be<sup>2+</sup> &gt; Mg<sup>2+</sup> &gt; Ca<sup>2+</sup> &gt; Sr<sup>2+</sup> &gt; Ba<sup>2+</sup>. Hydration becomes less exothermic as the ion becomes larger.</td></tr><tr><td>Reducing character</td><td>Be &lt; Mg &lt; Ca &lt; Sr &lt; Ba &lt; Ra as the source's broad trend.</td></tr><tr><td>Hydroxide basicity, solubility and thermal stability</td><td>Mg(OH)<sub>2</sub> &lt; Ca(OH)<sub>2</sub> &lt; Sr(OH)<sub>2</sub> &lt; Ba(OH)<sub>2</sub>.</td></tr><tr><td>Carbonate thermal stability</td><td>BeCO<sub>3</sub> &lt; MgCO<sub>3</sub> &lt; CaCO<sub>3</sub> &lt; SrCO<sub>3</sub> &lt; BaCO<sub>3</sub> as the formal revision sequence; ordinary simple BeCO<sub>3</sub> is particularly unstable.</td></tr><tr><td>Sulfate solubility</td><td>BeSO<sub>4</sub> &gt; MgSO<sub>4</sub> &gt; CaSO<sub>4</sub> &gt; SrSO<sub>4</sub> &gt; BaSO<sub>4</sub> in the standard qualitative comparison.</td></tr></tbody></table><p><strong>Source corrections:</strong> The reducing-character row prints Si between Ca and Ba; the intended group 2 element is Sr. Hydration arrows compare absolute magnitudes, not the signed negative enthalpies. The carbonate caption says 'solubility opposite', but carbonate solubilities are low, phase- and equilibrium-dependent, and do not justify an exact universal reverse ordering. Hydrates, temperature, dissolved CO<sub>2</sub> and pH matter; the source supplies none of these controls.</p>"
    },
    {
      id: "lime-gypsum-and-plaster",
      title: "Quicklime, limewater, gypsum and plaster",
      sources: [{ document: "quick-revision", page: 95 }],
      html: "<p>Quicklime is CaO. The source describes preparation by heating limestone in a rotary kiln: CaCO<sub>3</sub> &rarr; CaO + CO<sub>2</sub>. Adding water to lime forms slaked lime, Ca(OH)<sub>2</sub>. Milk of lime is a suspension of slaked lime, whereas limewater is the clear filtered aqueous solution. Suspension and solution are not interchangeable terms.</p><p>Gypsum is CaSO<sub>4</sub>&middot;2H<sub>2</sub>O. Controlled heating at about the source's 393 K produces plaster of Paris, calcium sulfate hemihydrate, $\\mathrm{CaSO_4}\\cdot\\frac{1}{2}\\mathrm{H_2O}$. One formula unit of gypsum loses $\\frac{3}{2}$ water molecules per formula unit on average; in whole-number notation, 2CaSO<sub>4</sub>&middot;2H<sub>2</sub>O &rarr; (CaSO<sub>4</sub>)<sub>2</sub>&middot;H<sub>2</sub>O + 3H<sub>2</sub>O.</p><p>Further heating can form anhydrous CaSO<sub>4</sub>; strongly heated, poorly rehydrating material is termed dead-burnt plaster. <strong>Source qualification:</strong> The source says all heating above 393 K gives dead-burnt plaster. This is not a universal sharp temperature boundary: time, water-vapour pressure, heating history and the anhydrite form affect the product and its reactivity.</p>"
    },
    {
      id: "biological-roles-of-s-block-ions",
      title: "All sodium, potassium, magnesium and calcium roles",
      sources: [{ document: "quick-revision", page: 95 }, { document: "quick-revision", page: 96 }],
      html: "<table><thead><tr><th>Ion or element</th><th>Roles listed across the two pages</th></tr></thead><tbody><tr><td>Na<sup>+</sup></td><td>Prominent in blood plasma and interstitial fluid; participates in nerve-signal transmission.</td></tr><tr><td>K<sup>+</sup></td><td>Prominent in intracellular fluids; activates many enzymes and supports glucose metabolism and ATP production.</td></tr><tr><td>Mg</td><td>Cofactor for enzymes that use ATP; the central metal in chlorophyll.</td></tr><tr><td>Ca</td><td>Present in bones and teeth; important in neuromuscular function, neuronal transmission and blood coagulation.</td></tr></tbody></table><p>Sodium is primarily an extracellular cation and potassium an intracellular cation; this does not mean either is absolutely absent from the other compartment. Potassium's role in glucose oxidation is through enzyme and cellular function, not by serving as the oxidant itself. The calcium continuation appears at the top of page 96 and is retained with this biological comparison.</p>"
    },
    {
      id: "p-block-group-thirteen-carryover",
      title: "p-block and group 13 material on the assigned page",
      sources: [{ document: "quick-revision", page: 96 }],
      html: "<p>The last electron of a p-block element enters a p subshell, giving the general pattern ns<sup>2</sup>np<sup>1-6</sup>. The source lists the familiar group 13 elements B, Al, Ga, In and Tl, with ns<sup>2</sup>np<sup>1</sup> valence configurations. These source examples are not an assertion that the modern group ends at thallium.</p><ul><li>Metallic radii do not increase regularly down the group. Poor shielding by intervening d and f electrons can offset the effect of adding shells; boron itself is not normally described by a metallic-crystal radius.</li><li>Successive ionization enthalpies for one element obey $\\Delta H_1&lt;\\Delta H_2&lt;\\Delta H_3$.</li><li>The checked first-ionization order is B &gt; Tl &gt; Ga &gt; Al &gt; In. <strong>Source correction:</strong> The printed 'Ti' is Tl, thallium; titanium is not a group 13 element.</li><li>The +1 oxidation state becomes more stable relative to +3 down the group, associated with the inert-pair effect: the ns<sup>2</sup> pair becomes less readily involved in bonding.</li><li>The source says electronegativity drops B to Al and then rises continuously to Tl. <strong>Source correction:</strong> The initial drop is valid, but the later trend is not monotonic on the Pauling scale; Ga is above Al, while In and Tl do not continue a simple rise.</li><li>Boron forms boron trioxide, B<sub>2</sub>O<sub>3</sub>, when heated with oxygen.</li><li>B and Al form nitrides, BN and AlN, with nitrogen at high temperature.</li><li>Al reacts with suitable acids and alkalis, illustrating its amphoteric chemistry. Boron resists ordinary nonoxidizing acids and aqueous alkalis more strongly. <strong>Source qualification:</strong> It is not absolutely inert to every acid or alkali under all conditions, as the source's unqualified wording would imply.</li><li>These elements form trihalides MX<sub>3</sub> in their +3 state on reaction with suitable halogens and under suitable conditions.</li></ul>"
    },
    {
      id: "borax-boric-acid-diborane-carryover",
      title: "All boron-compound formulas and reactions",
      sources: [{ document: "quick-revision", page: 96 }],
      html: "<p><strong>Borax:</strong> Na<sub>2</sub>B<sub>4</sub>O<sub>7</sub>&middot;10H<sub>2</sub>O, alternatively represented as Na<sub>2</sub>[B<sub>4</sub>O<sub>5</sub>(OH)<sub>4</sub>]&middot;8H<sub>2</sub>O. These formulas have the same overall atom inventory; the second distinguishes hydroxyl groups from water of crystallization.</p><p><strong>Heating and metaborate:</strong> Na<sub>2</sub>B<sub>4</sub>O<sub>7</sub>&middot;10H<sub>2</sub>O &rarr; Na<sub>2</sub>B<sub>4</sub>O<sub>7</sub> + 10H<sub>2</sub>O on dehydration. Further heating is represented as Na<sub>2</sub>B<sub>4</sub>O<sub>7</sub> &rarr; 2NaBO<sub>2</sub> + B<sub>2</sub>O<sub>3</sub>, yielding sodium metaborate and boron trioxide in the glass-forming mixture. The source's first arrow omits the released water, which is restored here for atom balance.</p><p><strong>Orthoboric acid:</strong> H<sub>3</sub>BO<sub>3</sub>, also written B(OH)<sub>3</sub>, is prepared by acidifying an aqueous borax solution. The printed equation is balanced: Na<sub>2</sub>B<sub>4</sub>O<sub>7</sub> + 2HCl + 5H<sub>2</sub>O &rarr; 2NaCl + 4B(OH)<sub>3</sub>.</p><p><strong>Diborane:</strong> B<sub>2</sub>H<sub>6</sub>. The source labels 2NaBH<sub>4</sub> + I<sub>2</sub> &rarr; B<sub>2</sub>H<sub>6</sub> + 2NaI + H<sub>2</sub> as a laboratory route. Its industrial-route equation is 2BF<sub>3</sub> + 6NaH &rarr; B<sub>2</sub>H<sub>6</sub> + 6NaF, with 450 K printed over the arrow. These are source reaction schemes, not complete operating instructions or proof that every present-day process uses that route.</p><p>Diborane has two bridging B-H-B bonds described as three-centre two-electron bonds, traditionally called 'banana bonds'. Each bridge spreads one electron pair over three atomic centres; it is not two independent ordinary two-centre bonds. The remaining four hydrogens are terminal.</p><p><strong>Ruby:</strong> the source lists Al<sub>2</sub>O<sub>3</sub> as its component. More specifically, ruby is a corundum host containing chromium impurities responsible for the red colour; pure alumina alone does not specify ruby's colour.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 94, status: "partial", sectionIds: ["permanent-hardness-and-heavy-water", "hydrogen-peroxide-preparation", "peroxide-volume-strength", "hydrogen-and-water-exam-points", "alkali-metal-properties", "alkali-trend-comparisons"], unresolved: ["Peroxide volume strength omits oxygen reference conditions, percentage basis and the normality reaction. The standard 273.15 K/1 atm, mass-volume and two-electron interpretations are explicitly supplied rather than claimed to be printed.", "The atomic-hydrogen/CO to formaldehyde statement omits medium, atomic-hydrogen generation and selectivity conditions; it is not used as an assessed preparation claim.", "The bicarbonate-stability chain has an inconsistent middle inequality and no stability criterion or temperature; no exact ranking is scored.", "Lane, Uyeno and Bosch are named without process equations or conditions, and the peroxide preparation schemes do not provide complete operating conditions."] },
    { document: "quick-revision", page: 95, status: "partial", sectionIds: ["sodium-carbonate-solvay", "sodium-hydroxide-salt-and-mixtures", "alkaline-earth-properties", "alkaline-earth-trend-table", "lime-gypsum-and-plaster", "biological-roles-of-s-block-ions"], unresolved: ["The carbonate 'solubility opposite' statement has no hydrate, temperature, pH or dissolved-CO2 conditions and cannot support an exact reverse-solubility order.", "The dead-burnt-plaster claim specifies only 'above 393 K', omitting heating duration and water-vapour pressure; the actual phase/reactivity boundary cannot be reconstructed."] },
    { document: "quick-revision", page: 96, status: "partial", sectionIds: ["alkali-metal-properties", "sodium-hydroxide-salt-and-mixtures", "chlorine-alkali-and-zinc-reactions", "biological-roles-of-s-block-ions", "p-block-group-thirteen-carryover", "borax-boric-acid-diborane-carryover"], unresolved: ["The 'Oxone' reagent-pair label has no historical or product reference; the sodium-peroxide reaction is retained separately from the modern peroxymonosulfate trade-name meaning.", "The Zn/NaOH zincate equation omits phase and heating conditions; anhydrous and aqueous hydroxo-complex descriptions are separated.", "The generic halogen/alkali and boron acid/alkali claims lack species-specific reaction limits; chlorine equations and explicit qualifications replace universal interpretations."] }
  ],
  questions: [
    { id: "note-s-block-001", text: "How does the sodium hexametaphosphate treatment described for hard water differ from removing all hardness ions by precipitation?", options: [{ key: "a", text: "It deposits the hardness ions as insoluble hydroxides" }, { key: "b", text: "It sequesters hardness ions in soluble complexes" }, { key: "c", text: "It exchanges the hardness ions for hydrogen ions" }, { key: "d", text: "It decomposes bicarbonates solely through boiling" }], answer: "b", explanation: "Calgon-type phosphate treatment binds hardness ions so they do not behave as free calcium or magnesium in hardness reactions. Complexation need not physically remove the metal from solution.", sectionId: "permanent-hardness-and-heavy-water", source: { document: "quick-revision", page: 94 }, cognitive: "understanding" },
    { id: "note-s-block-002", text: "What is the principal function of D<sub>2</sub>O when used as a nuclear-reactor moderator?", options: [{ key: "a", text: "Absorbing neutrons to stop the chain reaction" }, { key: "b", text: "Providing the fissile nuclei that release energy" }, { key: "c", text: "Reflecting neutrons without changing their energy" }, { key: "d", text: "Slowing down energetic neutrons" }], answer: "d", explanation: "A moderator reduces neutron kinetic energy through scattering. Heavy water serves this role in appropriate reactors; moderation is distinct from being fuel or indiscriminately absorbing neutrons.", sectionId: "permanent-hardness-and-heavy-water", source: { document: "quick-revision", page: 94 }, cognitive: "recall" },
    { id: "note-s-block-003", text: "A peroxide solution has volume strength 20, with oxygen measured using 22.4 L mol<sup>-1</sup>. What is its approximate molarity?", options: [{ key: "a", text: "0.446 mol L<sup>-1</sup>" }, { key: "b", text: "0.893 mol L<sup>-1</sup>" }, { key: "c", text: "1.786 mol L<sup>-1</sup>" }, { key: "d", text: "3.571 mol L<sup>-1</sup>" }], answer: "c", explanation: "Each mole of H2O2 produces half a mole of oxygen, or 11.2 L under the stated convention. Thus molarity is 20/11.2 = 1.786 mol/L, not 20/22.4.", sectionId: "peroxide-volume-strength", source: { document: "quick-revision", page: 94 }, cognitive: "application" },
    { id: "note-s-block-004", text: "Using M(H<sub>2</sub>O<sub>2</sub>) = 34.0 g mol<sup>-1</sup> and the 22.4 L mol<sup>-1</sup> oxygen convention, how much peroxide is present in one litre of ten-volume solution?", options: [{ key: "a", text: "30.36 g" }, { key: "b", text: "15.18 g" }, { key: "c", text: "3.036 g" }, { key: "d", text: "60.72 g" }], answer: "a", explanation: "Ten litres of oxygen represent 10/22.4 mol O2. Decomposition needs twice that amount of H2O2, so the mass is $2\\times\\frac{10}{22.4}\\times34.0=30.36$ g.", sectionId: "peroxide-volume-strength", source: { document: "quick-revision", page: 94 }, cognitive: "application" },
    { id: "note-s-block-005", text: "Ortho and para forms of molecular hydrogen differ in which feature?", options: [{ key: "a", text: "Mass numbers of their hydrogen nuclei" }, { key: "b", text: "Relative spins of their bonding electrons" }, { key: "c", text: "Their relative proton nuclear spins" }, { key: "d", text: "Numbers of electrons in their H-H bonds" }], answer: "c", explanation: "Both are H2 with the same nuclei and formula. Their distinction is the coupled nuclear-spin state of the two protons, triplet for ortho and singlet for para hydrogen.", sectionId: "hydrogen-and-water-exam-points", source: { document: "quick-revision", page: 94 }, cognitive: "recall" },
    { id: "note-s-block-006", text: "Which flame colour corresponds to sodium in the source comparison?", options: [{ key: "a", text: "Golden yellow" }, { key: "b", text: "Crimson red" }, { key: "c", text: "Pale violet" }, { key: "d", text: "Apple green" }], answer: "a", explanation: "Sodium gives a characteristic intense golden-yellow flame. Crimson red is listed for lithium, pale violet for potassium, and apple green for barium.", sectionId: "alkali-metal-properties", source: { document: "quick-revision", page: 94 }, cognitive: "recall" },
    { id: "note-s-block-007", text: "Which observation prevents the alkali-metal density trend from being called strictly increasing from Li to Cs?", options: [{ key: "a", text: "Caesium is denser than rubidium" }, { key: "b", text: "Sodium is denser than lithium" }, { key: "c", text: "Rubidium is denser than potassium" }, { key: "d", text: "Potassium is less dense than sodium" }], answer: "d", explanation: "The broad down-group density increase has the familiar Na/K exception. Potassium is less dense than sodium, so a strictly monotonic source statement needs correction.", sectionId: "alkali-metal-properties", source: { document: "quick-revision", page: 94 }, cognitive: "understanding" },
    { id: "note-s-block-008", text: "Why can lithium be the strongest aqueous reducing agent among the listed alkali metals despite its relatively high ionization energy?", options: [{ key: "a", text: "The lithium atom is much larger than caesium" }, { key: "b", text: "Strong Li+ hydration favors the overall oxidation" }, { key: "c", text: "Lithium has the lowest ionization energy" }, { key: "d", text: "Lithium has the weakest metallic bonding in the group" }], answer: "b", explanation: "Aqueous electrode behavior includes atomization, ionization and hydration. The large favorable hydration enthalpy of small Li+ strongly stabilizes the aqueous oxidation product.", sectionId: "alkali-trend-comparisons", source: { document: "quick-revision", page: 94 }, cognitive: "understanding" },
    { id: "note-s-block-009", text: "Which precipitation is central to the ordinary Solvay process for sodium carbonate?", options: [{ key: "a", text: "NaHCO<sub>3</sub> from ammoniated brine" }, { key: "b", text: "KHCO<sub>3</sub> from ammoniated potassium brine" }, { key: "c", text: "Na<sub>2</sub>CO<sub>3</sub> directly before bicarbonate formation" }, { key: "d", text: "NH<sub>4</sub>Cl before the bicarbonate separation" }], answer: "a", explanation: "Relatively insoluble sodium bicarbonate precipitates in the process liquor and is then heated to sodium carbonate. Potassium bicarbonate is too soluble for the same efficient separation.", sectionId: "sodium-carbonate-solvay", source: { document: "quick-revision", page: 95 }, cognitive: "understanding" },
    { id: "note-s-block-010", text: "Which pair of sodium salts is formed when chlorine reacts with cold, dilute NaOH under the usual conditions?", options: [{ key: "a", text: "NaCl and NaClO<sub>3</sub>" }, { key: "b", text: "NaCl and NaClO" }, { key: "c", text: "NaClO<sub>2</sub> and NaClO<sub>4</sub>" }, { key: "d", text: "NaClO<sub>3</sub> and NaClO<sub>4</sub>" }], answer: "b", explanation: "Cold dilute alkali gives chloride and hypochlorite: Cl2 + 2NaOH produces NaCl + NaClO + H2O. Chlorate is the characteristic hot concentrated-alkali product.", sectionId: "chlorine-alkali-and-zinc-reactions", source: { document: "quick-revision", page: 96 }, cognitive: "recall" },
    { id: "note-s-block-011", text: "In the balanced hot, concentrated NaOH reaction with chlorine, what is the molar product ratio NaCl : NaClO<sub>3</sub>?", options: [{ key: "a", text: "1 : 1" }, { key: "b", text: "3 : 1" }, { key: "c", text: "1 : 5" }, { key: "d", text: "5 : 1" }], answer: "d", explanation: "The balanced equation is 3Cl2 + 6NaOH gives 5NaCl + NaClO3 + 3H2O. One chlorine reaches +5 while five reach -1, producing a 5:1 salt ratio.", sectionId: "chlorine-alkali-and-zinc-reactions", source: { document: "quick-revision", page: 96 }, cognitive: "application" },
    { id: "note-s-block-012", text: "Crystals of washing soda become powdery while losing water of crystallization in dry air. What is this process called?", options: [{ key: "a", text: "Effervescence" }, { key: "b", text: "Deliquescence" }, { key: "c", text: "Efflorescence" }, { key: "d", text: "Electrolysis" }], answer: "c", explanation: "Efflorescence is loss of crystallization water from a hydrate. Effervescence means gas bubbling, while deliquescence involves moisture uptake until a solution forms.", sectionId: "sodium-hydroxide-salt-and-mixtures", source: { document: "quick-revision", page: 96 }, cognitive: "understanding" },
    { id: "note-s-block-013", text: "Which group 2 flame colour is assigned specifically to strontium?", options: [{ key: "a", text: "Brick red" }, { key: "b", text: "Golden yellow" }, { key: "c", text: "Apple green" }, { key: "d", text: "Crimson red" }], answer: "d", explanation: "The group 2 comparison lists calcium as brick red, strontium as crimson red and barium as apple green. Golden yellow is the characteristic sodium colour.", sectionId: "alkaline-earth-properties", source: { document: "quick-revision", page: 95 }, cognitive: "recall" },
    { id: "note-s-block-014", text: "Which sulfate is least soluble in the standard group 2 sulfate comparison?", options: [{ key: "a", text: "MgSO<sub>4</sub>" }, { key: "b", text: "CaSO<sub>4</sub>" }, { key: "c", text: "BaSO<sub>4</sub>" }, { key: "d", text: "SrSO<sub>4</sub>" }], answer: "c", explanation: "The listed sulfate-solubility trend decreases down the group toward BaSO4. Barium sulfate is much less soluble than the corresponding magnesium and calcium salts.", sectionId: "alkaline-earth-trend-table", source: { document: "quick-revision", page: 95 }, cognitive: "recall" },
    { id: "note-s-block-015", text: "When exactly 2 mol of gypsum, CaSO<sub>4</sub>&middot;2H<sub>2</sub>O, become calcium sulfate hemihydrate, how much water is released?", options: [{ key: "a", text: "3 mol" }, { key: "b", text: "1 mol" }, { key: "c", text: "2 mol" }, { key: "d", text: "4 mol" }], answer: "a", explanation: "Each CaSO4 unit changes from two waters to half a water, releasing 1.5 waters. For two moles of gypsum, 2 x 1.5 = 3 mol water are released.", sectionId: "lime-gypsum-and-plaster", source: { document: "quick-revision", page: 95 }, cognitive: "application" },
    { id: "note-s-block-016", text: "Which pairing describes the predominant distribution of Na<sup>+</sup> and K<sup>+</sup> in body fluids?", options: [{ key: "a", text: "Na+ mainly intracellular; K+ mainly extracellular" }, { key: "b", text: "Na+ mainly extracellular; K+ mainly intracellular" }, { key: "c", text: "Na+ mainly extracellular; K+ mainly extracellular" }, { key: "d", text: "Na+ mainly intracellular; K+ mainly intracellular" }], answer: "b", explanation: "The notes place sodium prominently in plasma and interstitial fluid and potassium in cell fluids. These are predominant distributions, not absolute exclusion from other compartments.", sectionId: "biological-roles-of-s-block-ions", source: { document: "quick-revision", page: 95 }, cognitive: "recall" },
    { id: "note-s-block-017", text: "The group 13 first-ionization sequence is printed B &gt; Ti &gt; Ga &gt; Al &gt; In. Which name repairs the misplaced Ti symbol?", options: [{ key: "a", text: "Tellurium" }, { key: "b", text: "Titanium" }, { key: "c", text: "Thallium" }, { key: "d", text: "Tin" }], answer: "c", explanation: "The intended element is Tl, thallium, which belongs to group 13. Ti is titanium, a d-block element, and cannot be the intended member of this group comparison.", sectionId: "p-block-group-thirteen-carryover", source: { document: "quick-revision", page: 96 }, cognitive: "understanding" },
    { id: "note-s-block-018", text: "As the inert-pair effect becomes more important down group 13, which oxidation state gains stability relative to +3?", options: [{ key: "a", text: "+5" }, { key: "b", text: "+4" }, { key: "c", text: "+2" }, { key: "d", text: "+1" }], answer: "d", explanation: "If the ns2 pair is less available for bonding, only the np electron is readily involved, favoring +1. Thus +1 becomes relatively more stable down group 13.", sectionId: "p-block-group-thirteen-carryover", source: { document: "quick-revision", page: 96 }, cognitive: "understanding" },
    { id: "note-s-block-019", text: "Complete acidification of 1 mol of Na<sub>2</sub>B<sub>4</sub>O<sub>7</sub> produces how many moles of B(OH)<sub>3</sub>, assuming complete conversion?", options: [{ key: "a", text: "2 mol" }, { key: "b", text: "4 mol" }, { key: "c", text: "1 mol" }, { key: "d", text: "8 mol" }], answer: "b", explanation: "One tetraborate formula unit contains four boron atoms. Each boric-acid molecule contains one, so conservation of boron gives four moles, matching the balanced source equation.", sectionId: "borax-boric-acid-diborane-carryover", source: { document: "quick-revision", page: 96 }, cognitive: "application" },
    { id: "note-s-block-020", text: "Which description applies to one bridging B-H-B bond in diborane?", options: [{ key: "a", text: "Three centres sharing two electrons" }, { key: "b", text: "Two centres sharing four electrons" }, { key: "c", text: "Three centres sharing six electrons" }, { key: "d", text: "Two centres sharing one electron" }], answer: "a", explanation: "A diborane bridge is a three-centre two-electron bond: one pair is spread across B-H-B. Treating it as two independent ordinary two-centre bonds would overcount electrons.", sectionId: "borax-boric-acid-diborane-carryover", source: { document: "quick-revision", page: 96 }, cognitive: "recall" }
  ]
};