window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["solid-state"] = {
  id: "solid-state",
  subject: "Chemistry",
  title: "Solid state and crystals",
  sections: [
    {
      id: "unit-cell-types",
      title: "Primitive and centred unit cells",
      sources: [{ document: "quick-revision", page: 70 }],
      html: "<p>A unit cell repeats by translation to describe a crystal. In the elementary lattice-point description used here, a primitive cell has lattice points only at its corners, with a total contribution of one lattice point. A centred conventional cell has additional lattice points.</p><ul><li><strong>Body-centred:</strong> a point at the body centre in addition to the corner points.</li><li><strong>Face-centred:</strong> a point at the centre of every face in addition to the corners.</li><li><strong>End-centred or base-centred:</strong> a point at the centre of each of one pair of opposite faces, in addition to the corners. This does not mean all six faces are centred.</li></ul><p><strong>Source qualification:</strong> The source calls the lattice points 'constituent particles'. A lattice point can carry a multi-atom basis. Therefore, lattice-point counts equal atom counts only for the monatomic structures assumed in the simple cubic, BCC and FCC atom-count table.</p>"
    },
    {
      id: "seven-crystal-systems",
      title: "All seven crystal systems and examples",
      sources: [{ document: "quick-revision", page: 70 }],
      html: "<p>Write the cell edges as $a,b,c$. The interaxial angles are $\\alpha$ between $b,c$, $\\beta$ between $a,c$, and $\\gamma$ between $a,b$. Crystal system describes lattice symmetry; it is not the same classification as primitive versus centred.</p><table><thead><tr><th>Crystal system</th><th>Edges and angles</th></tr></thead><tbody><tr><td>Cubic</td><td>$a=b=c$; $\\alpha=\\beta=\\gamma=90^\\circ$. Highest symmetry among these seven systems.</td></tr><tr><td>Tetragonal</td><td>$a=b\\ne c$; all three angles 90&deg;.</td></tr><tr><td>Orthorhombic or rhombic</td><td>Three generally unequal edges; all three angles 90&deg;.</td></tr><tr><td>Monoclinic</td><td>Three generally unequal edges; $\\alpha=\\gamma=90^\\circ$ and $\\beta\\ne90^\\circ$ in the conventional unique-b setting.</td></tr><tr><td>Hexagonal</td><td>$a=b\\ne c$; $\\alpha=\\beta=90^\\circ$, $\\gamma=120^\\circ$.</td></tr><tr><td>Trigonal in rhombohedral axes</td><td>$a=b=c$; three equal angles that are not 90&deg; in the general rhombohedral description.</td></tr><tr><td>Triclinic</td><td>Edges and angles have no equality or right-angle constraints; conventionally drawn with three unequal edges and three unequal non-right angles. Lowest symmetry.</td></tr></tbody></table><table><thead><tr><th>System</th><th>Every listed example, with phase qualifications</th></tr></thead><tbody><tr><td>Cubic</td><td>Cu, zinc blende (ZnS), KCl, NaCl.</td></tr><tr><td>Tetragonal</td><td>White or beta-Sn; SnO<sub>2</sub> in the cassiterite structure; TiO<sub>2</sub> in rutile or anatase forms. CaSO<sub>4</sub> is also printed in this row but is misplaced for ordinary anhydrite.</td></tr><tr><td>Orthorhombic</td><td>Rhombic sulfur, ordinary room-temperature KNO<sub>3</sub>, BaSO<sub>4</sub>.</td></tr><tr><td>Monoclinic</td><td>Monoclinic sulfur; the source also lists Na<sub>2</sub>SO<sub>4</sub> without a phase or hydration state.</td></tr><tr><td>Hexagonal</td><td>Graphite, ZnO and CdS in their hexagonal forms.</td></tr><tr><td>Trigonal</td><td>CaCO<sub>3</sub> as calcite, HgS as cinnabar.</td></tr><tr><td>Triclinic</td><td>K<sub>2</sub>Cr<sub>2</sub>O<sub>7</sub> and CuSO<sub>4</sub>&middot;5H<sub>2</sub>O.</td></tr></tbody></table><p><strong>Source corrections:</strong> Triclinic is printed as 'most symmetrical' with a contradictory right-angle expression; it is the least symmetrical system and has no symmetry-imposed right angles. The printed K<sub>2</sub>Cl<sub>2</sub>O<sub>7</sub> is corrected to potassium dichromate, K<sub>2</sub>Cr<sub>2</sub>O<sub>7</sub>. Ordinary anhydrite CaSO<sub>4</sub> is orthorhombic, not tetragonal; gypsum is a different, hydrated monoclinic phase. Ordinary anhydrous sodium sulfate, thenardite, is orthorhombic, while its decahydrate mirabilite is monoclinic. The unspecified source Na<sub>2</sub>SO<sub>4</sub> entry cannot serve as a phase-independent classification. Polymorphs of a compound need not share a crystal system.</p>"
    },
    {
      id: "unit-cell-particle-counts",
      title: "Counting atoms in conventional cells",
      sources: [{ document: "quick-revision", page: 70 }, { document: "quick-revision", page: 71 }],
      html: "<p>In the cubic cells shown, a corner atom is shared by eight cells and contributes $\\frac{1}{8}$ to one cell. A face-centred atom is shared by two cells and contributes $\\frac{1}{2}$. An atom at the body centre lies wholly inside the cell and contributes one.</p><table><thead><tr><th>Cell</th><th>Contributions and total $Z$</th></tr></thead><tbody><tr><td>Simple cubic</td><td>$8\\times\\frac{1}{8}=1$; no face or body-centred atoms. $Z=1$.</td></tr><tr><td>Body-centred cubic</td><td>$8\\times\\frac{1}{8}+1=2$; no face-centred atoms. $Z=2$.</td></tr><tr><td>Face-centred cubic</td><td>$8\\times\\frac{1}{8}+6\\times\\frac{1}{2}=4$; no body-centred atom. $Z=4$.</td></tr></tbody></table><p>For a base-centred conventional cell with eight corners and two occupied opposite face centres, the same sharing argument gives $1+2\\times\\frac{1}{2}=2$ lattice points. Use a basis or formula-unit count separately for compounds; do not count every ion in a compound as a full formula unit.</p>"
    },
    {
      id: "close-packing-and-voids",
      title: "Layer stacking and interstitial voids",
      sources: [{ document: "quick-revision", page: 70 }],
      html: "<p>In hexagonal close packing, successive close-packed layers follow ABAB... stacking: the third layer repeats the first. Cubic close packing follows ABCABC... stacking: the fourth layer repeats the first. Cubic close packing is the same sphere arrangement as FCC.</p><ul><li><strong>Tetrahedral void:</strong> a three-dimensional cavity surrounded by four spheres whose centres form a tetrahedron. It is produced by a triangular space in one layer capped by a sphere in the next, not merely by a flat triangular hole.</li><li><strong>Octahedral void:</strong> a cavity surrounded by six spheres, associated with opposing triangular spaces in adjacent layers. The centres of the six surrounding spheres form an octahedron.</li><li>If a close-packed assembly contains $N$ equal host spheres, it contains $2N$ tetrahedral holes and $N$ octahedral holes.</li><li>The largest sphere fitting an undistorted tetrahedral void has radius approximately $0.225R$, where $R$ is the host-sphere radius.</li><li>The largest sphere fitting an undistorted octahedral void has radius approximately $0.414R$.</li></ul><p>These size ratios assume equal, rigid, mutually touching host spheres. They are geometric limits, not exact measured ion radii for all real compounds. The void count is independent of whether every hole is actually occupied.</p>"
    },
    {
      id: "radius-ratio-coordination",
      title: "Radius-ratio rules and their limits",
      sources: [{ document: "quick-revision", page: 70 }],
      html: "<p>The radius ratio is $\\frac{r_+}{r_-}$, with the cation radius in the numerator and the anion radius in the denominator. The simple hard-sphere rule estimates which local coordination can accommodate the smaller ion while neighboring larger ions touch.</p><table><thead><tr><th>Ratio and coordination number</th><th>Arrangement and printed example</th></tr></thead><tbody><tr><td>0.155-0.225; CN 3</td><td>Planar triangular; boron trioxide, B<sub>2</sub>O<sub>3</sub>.</td></tr><tr><td>0.225-0.414; CN 4</td><td>Tetrahedral; sphalerite or zinc blende, ZnS.</td></tr><tr><td>0.414-0.732; CN 6</td><td>Octahedral; rock salt, NaCl.</td></tr><tr><td>0.732-1.0; CN 8</td><td>Cubic coordination; caesium chloride, CsCl.</td></tr></tbody></table><p>The decimal boundaries are rounded limiting ratios; do not infer a uniquely determined real structure from a ratio exactly at a printed boundary. Actual structures also depend on bonding, pressure, temperature and effective ionic radii.</p><p><strong>Source corrections:</strong> CsCl has eightfold local cubic coordination, but its crystal is not a monatomic BCC Bravais lattice: corner and centre sites are different species and form a simple-cubic lattice with a two-ion basis. The table's 'body centred cubic' describes a visual local arrangement, not equivalence of those lattice sites. B<sub>2</sub>O<sub>3</sub> has substantial network-covalent bonding and is an illustration of three-coordinate boron, not proof of a purely ionic radius-ratio model.</p>"
    },
    {
      id: "cubic-packing-metrics",
      title: "Cell edge, radius, packing efficiency and neighbours",
      sources: [{ document: "quick-revision", page: 71 }],
      html: "<p>For monatomic cubic hard-sphere models, $a$ is the cell edge, $r$ the atom radius and $d=2r$ the nearest-neighbour centre distance. Here $d$ is a distance, not density. Packing efficiency is the fraction of the cell volume occupied by the spheres.</p><table><thead><tr><th>Structure</th><th>All source metrics</th></tr></thead><tbody><tr><td>Simple cubic</td><td>$Z=1$; contact along the edge; $d=a=2r$, $r=\\frac{a}{2}$. Packing efficiency 52.4%; coordination number 6.</td></tr><tr><td>FCC or cubic close packing</td><td>$Z=4$; contact along the face diagonal; $4r=\\sqrt{2}a$, $d=\\frac{a}{\\sqrt{2}}$, $r=\\frac{a}{2\\sqrt{2}}$. Packing efficiency 74%; coordination number 12.</td></tr><tr><td>BCC</td><td>$Z=2$; contact along the body diagonal; $4r=\\sqrt{3}a$, $d=\\frac{\\sqrt{3}a}{2}$, $r=\\frac{\\sqrt{3}a}{4}$. Packing efficiency 68%; coordination number 8.</td></tr></tbody></table><p>The competitive-exam list repeats the coordination numbers FCC 12, simple cubic 6 and BCC 8. Coordination number counts nearest neighbours, whereas $Z$ counts the effective atoms within the chosen conventional cell. BCC and simple cubic are included in the source's packing comparison but are not close-packed arrangements in the strict FCC/HCP sense.</p>"
    },
    {
      id: "crystal-density",
      title: "Density and explicit length units",
      sources: [{ document: "quick-revision", page: 71 }],
      html: "<p>The cell mass is $\\frac{ZM}{N_A}$, so for a cubic cell its density is $\\rho=\\frac{ZM}{N_Aa^3}$. Here $Z$ is atoms per cell for an element or formula units per cell for a compound, $M$ is the corresponding molar mass, and $N_A$ is Avogadro's constant.</p><ul><li>With $M$ in g mol<sup>-1</sup> and $a$ in cm, the expression directly gives g cm<sup>-3</sup>.</li><li>With $M$ in kg mol<sup>-1</sup> and $a$ in m, it gives kg m<sup>-3</sup>.</li><li>If $a$ is supplied in &Aring;, convert using $1\u00a0\\mathrm{\\AA}=10^{-8}$ cm before cubing, or use $\\rho=\\frac{ZM\\times10^{24}}{N_Aa_{\\mathrm{\\AA}}^3}$ in g cm<sup>-3</sup>.</li><li>If $a$ is supplied in pm, use $1$ pm $=10^{-10}$ cm and $\\rho=\\frac{ZM\\times10^{30}}{N_Aa_{\\mathrm{pm}}^3}$ in g cm<sup>-3</sup>.</li></ul><p><strong>Source correction:</strong> The printed denominator includes an unexplained factor $10^{-3}$ while reporting g cm<sup>-3</sup>. No unit for $a$ is given, so this is not a generally usable formula. Convert the length explicitly, cube the converted length, and use the mass-per-volume derivation above.</p>"
    },
    {
      id: "frenkel-and-schottky",
      title: "Frenkel and Schottky defects",
      sources: [{ document: "quick-revision", page: 71 }],
      html: "<table><thead><tr><th>Defect</th><th>Location change and density</th></tr></thead><tbody><tr><td>Frenkel</td><td>A smaller ion, usually a cation, leaves its normal lattice site and occupies an interstitial position. A vacancy-interstitial pair is formed. No ion leaves the crystal, so density is unchanged in the elementary fixed-volume treatment. Source examples: ZnS, AgCl, AgBr.</td></tr><tr><td>Schottky</td><td>A charge-neutral stoichiometric set of cations and anions is absent from normal lattice sites. Missing matter lowers density in the elementary treatment. For an AB salt this means equal numbers of cation and anion vacancies.</td></tr></tbody></table><p>AgBr is the source's example capable of showing both Frenkel and Schottky defects. Both descriptions preserve overall electrical neutrality.</p><p><strong>Source corrections:</strong> Schottky ions are missing from normal lattice sites, not from 'interstitial space'. Equal cation and anion counts apply to 1:1 salts; other stoichiometries require the corresponding neutral ratio. The page calls a Frenkel defect a 'dislocation defect', but a Frenkel pair is a point-defect pair, distinct from a line dislocation in crystallography.</p>"
    },
    {
      id: "intermolecular-forces-page-carryover",
      title: "States of matter: four intermolecular interactions",
      sources: [{ document: "quick-revision", page: 71 }],
      html: "<p>The States of Matter heading begins on this assigned page; its complete visible force list is retained.</p><ol><li><strong>Dipole-dipole:</strong> interactions between polar molecules with permanent dipole moments. Favorable orientations give attraction; molecular orientation matters.</li><li><strong>Dipole-induced dipole:</strong> a polar molecule's permanent dipole distorts the electron cloud of a neighbour lacking a permanent dipole. The source example is HCl with He. The attraction depends on the permanent dipole moment and the neighbour's polarizability. Helium is an atom, not a molecule, in this example.</li><li><strong>Dispersion or London:</strong> instantaneous fluctuations induce correlated dipoles, producing attraction between polarizable particles, including atoms, molecules and ions. At sufficiently separated, non-overlapping particles in the usual nonretarded approximation, the attractive potential is $U=-\\frac{C_6}{r^6}$ with $C_6&gt;0$. The magnitude therefore varies inversely as the sixth power of separation.</li><li><strong>Hydrogen bonding:</strong> a particularly important directional interaction involving a hydrogen bonded to an electronegative donor and an appropriate acceptor. The elementary source examples involve highly polar N-H, O-H and H-F bonds. The donor bond alone is not enough; a suitable accepting site and geometry are also required.</li></ol><p><strong>Source qualifications:</strong> The London $r^{-6}$ law is an energy relation, not a force relation; its corresponding force magnitude scales as $r^{-7}$ within that model. The total interaction becomes repulsive at sufficiently small separation, so 'always attractive' refers to the dispersion contribution, not the complete interparticle potential. Hydrogen bonding is more specific than an unrestricted attraction between any polar molecules.</p>"
    },
    {
      id: "gas-laws-page-carryover",
      title: "Gaseous state: Boyle, Charles and pressure-temperature laws",
      sources: [{ document: "quick-revision", page: 71 }],
      html: "<table><thead><tr><th>Law and fixed quantities</th><th>Statement and equation</th></tr></thead><tbody><tr><td>Boyle: fixed temperature and amount of gas</td><td>Pressure varies inversely with volume: $P\\propto\\frac{1}{V}$ and $P_1V_1=P_2V_2$.</td></tr><tr><td>Charles: fixed pressure and amount of gas</td><td>Volume varies directly with absolute temperature: $\\frac{V_1}{T_1}=\\frac{V_2}{T_2}$.</td></tr><tr><td>Gay-Lussac pressure law: fixed volume and amount of gas</td><td>Pressure varies directly with absolute temperature: $\\frac{P_1}{T_1}=\\frac{P_2}{T_2}$.</td></tr></tbody></table><p>Use kelvin for every temperature ratio and absolute rather than gauge pressure. These are exact ideal-gas relations and approximate real-gas relations when nonideality is small. Charles's law also requires fixed amount even though the printed formula only repeats 'constant P'. Gay-Lussac's law here means the pressure-temperature law, not the separate law of combining gaseous volumes.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 70, status: "partial", sectionIds: ["unit-cell-types", "seven-crystal-systems", "unit-cell-particle-counts", "close-packing-and-voids", "radius-ratio-coordination"], unresolved: ["The monoclinic Na2SO4 example omits hydration state, polymorph, temperature and pressure; thenardite and mirabilite are distinguished in the transcription, but the source's intended phase remains unspecified."] },
    { document: "quick-revision", page: 71, status: "partial", sectionIds: ["unit-cell-particle-counts", "cubic-packing-metrics", "crystal-density", "frenkel-and-schottky", "intermolecular-forces-page-carryover", "gas-laws-page-carryover"], unresolved: ["The density formula's 10^-3 factor has no stated input length or molar-mass units. Its intended conversion cannot be recovered; dimensionally explicit alternatives are supplied."] }
  ],
  questions: [
    { id: "note-solid-state-001", text: "A monatomic cubic cell contains atoms at its eight corners and one at its body centre. How many atoms belong to one cell?", options: [{ key: "a", text: "2" }, { key: "b", text: "9" }, { key: "c", text: "4" }, { key: "d", text: "1" }], answer: "a", explanation: "The eight shared corners contribute $8\\times\\frac{1}{8}=1$ atom. The body-centred atom is wholly inside the cell and adds one, giving two atoms.", sectionId: "unit-cell-particle-counts", source: { document: "quick-revision", page: 70 }, cognitive: "application" },
    { id: "note-solid-state-002", text: "A conventional cell has eight corner lattice points and centres on just two opposite faces. What is its effective lattice-point count?", options: [{ key: "a", text: "1" }, { key: "b", text: "3" }, { key: "c", text: "2" }, { key: "d", text: "4" }], answer: "c", explanation: "Corners supply one point in total. Two face centres contribute $2\\times\\frac{1}{2}=1$ more, so the base-centred conventional cell contains two lattice points.", sectionId: "unit-cell-particle-counts", source: { document: "quick-revision", page: 70 }, cognitive: "application" },
    { id: "note-solid-state-003", text: "How many nearest neighbours surround one atom in an ideal monatomic FCC crystal?", options: [{ key: "a", text: "4" }, { key: "b", text: "6" }, { key: "c", text: "8" }, { key: "d", text: "12" }], answer: "d", explanation: "FCC has coordination number 12. Its four atoms per conventional cell are a different count: cell occupancy must not be confused with nearest neighbours.", sectionId: "cubic-packing-metrics", source: { document: "quick-revision", page: 71 }, cognitive: "recall" },
    { id: "note-solid-state-004", text: "Which crystal system has the fewest symmetry restrictions on its cell edges and interaxial angles?", options: [{ key: "a", text: "Cubic" }, { key: "b", text: "Triclinic" }, { key: "c", text: "Tetragonal" }, { key: "d", text: "Hexagonal" }], answer: "b", explanation: "The triclinic system has no symmetry-imposed edge equalities or right angles and is the least symmetrical. The source's 'most symmetrical' label is reversed.", sectionId: "seven-crystal-systems", source: { document: "quick-revision", page: 70 }, cognitive: "recall" },
    { id: "note-solid-state-005", text: "In conventional hexagonal axes, what is the angle between the equal a and b axes?", options: [{ key: "a", text: "90&deg;" }, { key: "b", text: "120&deg;" }, { key: "c", text: "109.5&deg;" }, { key: "d", text: "180&deg;" }], answer: "b", explanation: "The hexagonal convention has a = b, alpha = beta = 90 degrees and gamma = 120 degrees. Gamma is the angle between the a and b axes.", sectionId: "seven-crystal-systems", source: { document: "quick-revision", page: 70 }, cognitive: "recall" },
    { id: "note-solid-state-006", text: "Which specifically identified phase belongs to the trigonal system in the checked example table?", options: [{ key: "a", text: "Copper metal" }, { key: "b", text: "Rhombic sulfur" }, { key: "c", text: "White tin" }, { key: "d", text: "Calcite" }], answer: "d", explanation: "Calcite is the trigonal form of CaCO3 listed in the source. Copper is cubic, rhombic sulfur is orthorhombic, and white tin is tetragonal.", sectionId: "seven-crystal-systems", source: { document: "quick-revision", page: 70 }, cognitive: "recall" },
    { id: "note-solid-state-007", text: "An ideal FCC metal has a cell edge of 400 pm. Approximately what is its atomic radius?", options: [{ key: "a", text: "141.4 pm" }, { key: "b", text: "200.0 pm" }, { key: "c", text: "173.2 pm" }, { key: "d", text: "282.8 pm" }], answer: "a", explanation: "Contact runs along the face diagonal: $4r=\\sqrt{2}a$. Thus $r=\\frac{400}{2\\sqrt{2}}=141.4$ pm, not half the edge as in simple cubic packing.", sectionId: "cubic-packing-metrics", source: { document: "quick-revision", page: 71 }, cognitive: "application" },
    { id: "note-solid-state-008", text: "An ideal BCC metal has a 400 pm cell edge. Approximately what radius follows from body-diagonal contact?", options: [{ key: "a", text: "141.4 pm" }, { key: "b", text: "200.0 pm" }, { key: "c", text: "173.2 pm" }, { key: "d", text: "346.4 pm" }], answer: "c", explanation: "The body diagonal equals $\\sqrt{3}a$ and spans four radii. Therefore $r=\\frac{\\sqrt{3}\\times400}{4}=173.2$ pm; 346.4 pm is the diameter.", sectionId: "cubic-packing-metrics", source: { document: "quick-revision", page: 71 }, cognitive: "application" },
    { id: "note-solid-state-009", text: "Which occupied-volume fraction is closest to that of ideal equal spheres in cubic close packing?", options: [{ key: "a", text: "52%" }, { key: "b", text: "68%" }, { key: "c", text: "74%" }, { key: "d", text: "100%" }], answer: "c", explanation: "Cubic close packing is FCC and has approximately 74% packing efficiency. The remaining approximately 26% is void space even in this close-packed arrangement.", sectionId: "cubic-packing-metrics", source: { document: "quick-revision", page: 71 }, cognitive: "recall" },
    { id: "note-solid-state-010", text: "A close-packed assembly contains 240 host spheres. How many tetrahedral holes does its bulk counting rule give?", options: [{ key: "a", text: "480" }, { key: "b", text: "240" }, { key: "c", text: "120" }, { key: "d", text: "960" }], answer: "a", explanation: "An assembly of N close-packed spheres has 2N tetrahedral holes. With N = 240, the count is 480; the octahedral-hole count would instead be 240.", sectionId: "close-packing-and-voids", source: { document: "quick-revision", page: 70 }, cognitive: "application" },
    { id: "note-solid-state-011", text: "For close-packed host spheres of radius 200 pm, what is the approximate largest radius fitting an undistorted octahedral void?", options: [{ key: "a", text: "45.0 pm" }, { key: "b", text: "82.8 pm" }, { key: "c", text: "146.4 pm" }, { key: "d", text: "200.0 pm" }], answer: "b", explanation: "The octahedral-hole radius is approximately 0.414 times the host radius: 0.414 x 200 = 82.8 pm. The 45.0 pm choice uses the tetrahedral ratio 0.225.", sectionId: "close-packing-and-voids", source: { document: "quick-revision", page: 70 }, cognitive: "application" },
    { id: "note-solid-state-012", text: "Using only the simple radius-ratio rule, a 90 pm cation with a 180 pm anion falls in which coordination range?", options: [{ key: "a", text: "Three-coordinate planar" }, { key: "b", text: "Four-coordinate tetrahedral" }, { key: "c", text: "Eight-coordinate cubic" }, { key: "d", text: "Six-coordinate octahedral" }], answer: "d", explanation: "The cation-to-anion ratio is 90/180 = 0.50, between 0.414 and 0.732. The model predicts sixfold octahedral coordination, not a guaranteed real crystal structure.", sectionId: "radius-ratio-coordination", source: { document: "quick-revision", page: 70 }, cognitive: "application" },
    { id: "note-solid-state-013", text: "Which statement avoids confusing CsCl local coordination with a monatomic BCC lattice?", options: [{ key: "a", text: "Cs and Cl sites are translationally identical" }, { key: "b", text: "Each Cs ion has four nearest chloride ions" }, { key: "c", text: "The CsCl cell contains only one chemical species" }, { key: "d", text: "Cs has eight unlike neighbours in a two-ion basis" }], answer: "d", explanation: "CsCl has eightfold unlike-ion coordination, but the corner and central sites are different ions. The Bravais lattice is simple cubic with a two-ion basis, not monatomic BCC.", sectionId: "radius-ratio-coordination", source: { document: "quick-revision", page: 70 }, cognitive: "understanding" },
    { id: "note-solid-state-014", text: "A cation moves from its normal site to an interstitial site without leaving the crystal. In the elementary fixed-volume model, its density:", options: [{ key: "a", text: "Decreases because normal-site occupancy falls" }, { key: "b", text: "Remains unchanged because mass is retained" }, { key: "c", text: "Increases because an interstitial site is filled" }, { key: "d", text: "Cannot be inferred without the ion's charge" }], answer: "b", explanation: "This is a Frenkel vacancy-interstitial pair. The crystal retains the same mass; with volume unchanged in the elementary model, mass per unit volume is unchanged.", sectionId: "frenkel-and-schottky", source: { document: "quick-revision", page: 71 }, cognitive: "understanding" },
    { id: "note-solid-state-015", text: "Which change defines a Schottky defect in a 1:1 ionic crystal?", options: [{ key: "a", text: "Excess electrons occupy anion vacancies" }, { key: "b", text: "One cation moves into an interstitial hole" }, { key: "c", text: "Equal cation and anion lattice vacancies form" }, { key: "d", text: "Impurity cations replace normal host cations" }], answer: "c", explanation: "Schottky disorder removes a neutral stoichiometric set from normal lattice sites. For an AB salt this gives equal cation and anion vacancies and a lower density.", sectionId: "frenkel-and-schottky", source: { document: "quick-revision", page: 71 }, cognitive: "recall" },
    { id: "note-solid-state-016", text: "An FCC element has molar mass 50.0 g mol<sup>-1</sup> and cell edge 400 pm. Using $N_A=6.022\\times10^{23}$ mol<sup>-1</sup>, estimate its density.", options: [{ key: "a", text: "5.19 g cm<sup>-3</sup>" }, { key: "b", text: "1.30 g cm<sup>-3</sup>" }, { key: "c", text: "2.59 g cm<sup>-3</sup>" }, { key: "d", text: "20.8 g cm<sup>-3</sup>" }], answer: "a", explanation: "FCC gives Z = 4, and 400 pm = $4.00\\times10^{-8}$ cm. Cell volume is $6.40\\times10^{-23}$ cm3. Dividing $4(50.0)/N_A$ grams by that volume gives 5.19 g cm-3.", sectionId: "crystal-density", source: { document: "quick-revision", page: 71 }, cognitive: "application" },
    { id: "note-solid-state-017", text: "In the nonretarded London model, two particles are moved from separation r to 2r. The magnitude of dispersion energy becomes:", options: [{ key: "a", text: "One sixty-fourth of its original value" }, { key: "b", text: "One eighth of its original value" }, { key: "c", text: "One fourth of its original value" }, { key: "d", text: "One half of its original value" }], answer: "a", explanation: "The attractive energy magnitude scales as the inverse sixth power of separation. Doubling r therefore multiplies the magnitude by $\\frac{1}{2^6}=\\frac{1}{64}$.", sectionId: "intermolecular-forces-page-carryover", source: { document: "quick-revision", page: 71 }, cognitive: "application" },
    { id: "note-solid-state-018", text: "Which pair illustrates a permanent dipole inducing a dipole in a particle with no permanent dipole?", options: [{ key: "a", text: "Two isolated sodium cations" }, { key: "b", text: "Two isolated helium atoms" }, { key: "c", text: "A chloride ion and a sodium ion" }, { key: "d", text: "An HCl molecule and a helium atom" }], answer: "d", explanation: "HCl has a permanent dipole that can distort helium's electron cloud. Two helium atoms instead illustrate dispersion through instantaneous and induced dipoles.", sectionId: "intermolecular-forces-page-carryover", source: { document: "quick-revision", page: 71 }, cognitive: "understanding" },
    { id: "note-solid-state-019", text: "A fixed ideal-gas sample occupies 2.4 L at 0.50 atm. At unchanged temperature, what volume follows when absolute pressure becomes 1.00 atm?", options: [{ key: "a", text: "4.8 L" }, { key: "b", text: "2.4 L" }, { key: "c", text: "1.2 L" }, { key: "d", text: "0.6 L" }], answer: "c", explanation: "Boyle's law gives $V_2=\\frac{P_1V_1}{P_2}=\\frac{0.50\\times2.4}{1.00}=1.2$ L. Doubling absolute pressure halves volume at fixed temperature and amount.", sectionId: "gas-laws-page-carryover", source: { document: "quick-revision", page: 71 }, cognitive: "application" },
    { id: "note-solid-state-020", text: "A fixed ideal-gas sample expands from 400 mL at 300 K to 500 mL at constant pressure. What is its final temperature?", options: [{ key: "a", text: "240 K" }, { key: "b", text: "375 K" }, { key: "c", text: "400 K" }, { key: "d", text: "450 K" }], answer: "b", explanation: "Charles's law requires absolute temperatures: $T_2=T_1\\frac{V_2}{V_1}=300\\times\\frac{500}{400}=375$ K. Temperature increases by the same factor as volume.", sectionId: "gas-laws-page-carryover", source: { document: "quick-revision", page: 71 }, cognitive: "application" }
  ]
};