window.CEE_DIGITAL_TOPICS = window.CEE_DIGITAL_TOPICS || {};
window.CEE_DIGITAL_TOPICS["solutions"] = {
  id: "solutions",
  subject: "Chemistry",
  title: "Solutions and colloids",
  sections: [
    {
      id: "electrochemistry-continuation",
      title: "Electrochemistry continuation: mercury, copper sulfate and LOAN",
      sources: [{ document: "quick-revision", page: 66 }],
      html: "<p>The top of this assigned page finishes electrochemistry before beginning Surface Chemistry and Catalyst. Its first statement is 'Does not displace H2: Hg'. In the usual activity-series comparison, mercury does not liberate hydrogen from an ordinary dilute nonoxidizing acid such as hydrochloric acid. Oxidizing acids have different reactions and must not be treated as hydrogen-displacement tests. Source exam label: IOM 2009.</p><p><strong>Unresolved source conditions:</strong> the short mercury statement does not identify the reagent or conditions from which hydrogen is supposedly displaced. The dilute-nonoxidizing-acid interpretation above is stated explicitly, not presented as text supplied by the source.</p><p>The next claim says that during electrolysis of CuSO<sub>4</sub>, its density remains constant. <strong>Source correction:</strong> approximately unchanged concentration and density are expected with a dissolving copper anode and a copper-depositing cathode, at fixed temperature with negligible volume change, evaporation and side reactions. Copper entering as Cu<sup>2+</sup> at the anode replenishes that removed at the cathode. With inert electrodes, copper-ion depletion and other chemical changes make an unconditional constant-density claim incorrect. Source exam label: IOM 2016.</p><p><strong>Unresolved source conditions:</strong> the copper-sulfate statement omits the electrode materials and temperature/volume controls; its intended experiment cannot be established uniquely.</p><p>The source's mnemonic is <strong>LOAN</strong>: Left, Oxidation, Anode, Negative. In the conventional notation for a discharging galvanic cell, the anode is written on the left, oxidation occurs there, and it is negative. Left is a writing convention, not a required physical location; the negative sign is not the anode sign in an electrolytic cell. Source exam labels for anode: KU 2000, 2001 and 2010.</p>"
    },
    {
      id: "kohlrausch-law-applications",
      title: "Kohlrausch's law and all four listed applications",
      sources: [{ document: "quick-revision", page: 66 }],
      html: "<p>At infinite dilution, each ionic species makes a definite independent contribution to an electrolyte's limiting conductivity. The source describes this as the complete-dissociation limit and writes the equivalent-conductivity form:</p><p>$\\Lambda_{eq}^{\\infty}=\\lambda_{eq,c}^{\\infty}+\\lambda_{eq,a}^{\\infty}$.</p><p>The subscripts c and a refer to cation and anion. In molar notation, include the numbers of ions per formula unit: $\\Lambda_m^{\\infty}=\\nu_+\\lambda_+^{\\infty}+\\nu_-\\lambda_-^{\\infty}$. Limiting contributions must use the same temperature and unit convention.</p><ol><li>Determine the degree of ionization, alpha, of a weak electrolyte.</li><li>Determine its dissociation constant, K.</li><li>Determine limiting molar or equivalent conductivity of a weak electrolyte.</li><li>Determine the solubility of a sparingly soluble salt.</li></ol><p>Working relations behind these listed applications: for a weak electrolyte whose ion mobility is adequately represented by the limiting value, $\\alpha\\approx\\frac{\\Lambda_m}{\\Lambda_m^{\\infty}}$. For a binary weak electrolyte of formal concentration c with no added common ions, $K=\\frac{c\\alpha^2}{1-\\alpha}$. Independent ionic contributions can be combined by adding and subtracting suitable strong-electrolyte limiting conductivities to obtain the desired weak-electrolyte limit.</p><p>For a very dilute saturated salt solution with background-water conductivity subtracted, negligible side equilibria and limiting molar conductivity applicable, $s\\approx\\frac{1000\\kappa}{\\Lambda_m^{\\infty}}$ when kappa is in S cm<sup>-1</sup> and s in mol L<sup>-1</sup>. The source lists these applications but does not give a numerical worked example; the formulas here make their conditions and charge/concentration reasoning explicit.</p>"
    },
    {
      id: "faraday-equivalent",
      title: "Faraday and one gram-equivalent",
      sources: [{ document: "quick-revision", page: 66 }],
      html: "<p>The source states that one faraday corresponds to deposition of one gram-equivalent and calls the Faraday constant a universal constant. Source exam labels: deposition, KU 2013; constant, KU 2016.</p><p>One faraday is the magnitude of one mole of electron charge, approximately 96500 C. If z electrons are required per deposited atom and its molar mass is M, one faraday deposits $\\frac{1}{z}$ mole, or $\\frac{M}{z}$ grams, provided current efficiency is 100%. This mass is one gram-equivalent for that reaction; it is not necessarily one gram. The Faraday constant itself does not depend on electrode area, electrolyte identity or the mass deposited.</p>"
    },
    {
      id: "adsorption-absorption",
      title: "Adsorption and absorption: all comparison rows",
      sources: [{ document: "quick-revision", page: 66 }],
      html: "<table><thead><tr><th>Feature</th><th>Adsorption</th><th>Absorption</th></tr></thead><tbody><tr><td>Location</td><td>Accumulation at the surface of the adsorbent</td><td>Uptake throughout the bulk of the material</td></tr><tr><td>Concentration</td><td>Surface concentration differs from the bulk</td><td>Source says concentration is the same throughout the material</td></tr><tr><td>Rate</td><td>Source says high initially, then decreasing</td><td>Source says the rate remains the same throughout</td></tr></tbody></table><p>The central distinction is surface accumulation versus penetration into the bulk. The source's adsorption-rate description is a common approach-to-saturation pattern, not a universal kinetic law.</p><p><strong>Source correction:</strong> absorption does not universally occur at a constant rate. Its rate can change as the concentration gradient, available capacity or transport conditions change. Likewise, uniform bulk concentration is an equilibrium or well-mixed idealization; concentration gradients may exist while absorption is occurring. These qualifications preserve the comparison without presenting the source's rate and concentration simplifications as definitions.</p>"
    },
    {
      id: "particle-size-comparison",
      title: "Particle sizes and the optical comparison",
      sources: [{ document: "quick-revision", page: 66 }],
      html: "<p>The source orders particle size as true solution &lt; colloid &lt; suspension. It associates them with transparent, translucent and opaque appearances, respectively. Source exam label: IOM 2000.</p><table><thead><tr><th>Dispersion</th><th>Usual size convention</th><th>Source optical description</th></tr></thead><tbody><tr><td>True solution</td><td>Below about 10<sup>-7</sup> cm, or 1 nm</td><td>Transparent</td></tr><tr><td>Colloid</td><td>About 10<sup>-7</sup> to 10<sup>-4</sup> cm, or 1 to 1000 nm</td><td>Translucent</td></tr><tr><td>Suspension</td><td>Above about 10<sup>-4</sup> cm, or 1000 nm</td><td>Opaque</td></tr></tbody></table><p><strong>Source correction:</strong> the colloid interval is printed in descending order as 10^-4 to 10^-7 cm. More importantly, the suspension cutoff is printed &gt;10^-7 cm, which overlaps virtually the whole stated colloidal range. The conventional suspension cutoff matching this table is &gt;10^-4 cm. Since 1 cm = 10<sup>7</sup> nm, the corrected boundaries are 1 and 1000 nm.</p><p><strong>Source qualification:</strong> these are approximate classroom size and appearance categories. Concentration, particle refractive index, absorption and path length affect whether a particular dispersion looks clear, translucent or opaque; appearance alone is not a universal size measurement.</p>"
    },
    {
      id: "colloid-types-eight-rows",
      title: "All eight dispersed-phase and medium combinations",
      sources: [{ document: "quick-revision", page: 66 }],
      html: "<p>The type of colloidal dispersion is classified by the physical states of the dispersed phase and the continuous dispersion medium, in that order. Every row and example in the source table follows. Source exam labels: IOM 2005, 2012 and 2013.</p><table><thead><tr><th>Phase in medium</th><th>Type</th><th>Source examples</th></tr></thead><tbody><tr><td>Solid in solid</td><td>Solid sol</td><td>Some colored glasses and gemstones</td></tr><tr><td>Solid in liquid</td><td>Sol</td><td>Paints, cell fluid</td></tr><tr><td>Solid in gas</td><td>Aerosol</td><td>Smoke, dust</td></tr><tr><td>Liquid in solid</td><td>Gel</td><td>Cheese, butter, jellies</td></tr><tr><td>Liquid in liquid</td><td>Emulsion</td><td>Milk, hair cream</td></tr><tr><td>Liquid in gas</td><td>Liquid aerosol</td><td>Fog, mist, cloud, insecticide spray</td></tr><tr><td>Gas in solid</td><td>Solid foam</td><td>Pumice stone, foam rubber, bread</td></tr><tr><td>Gas in liquid</td><td>Foam</td><td>Froth, whipped cream, soap lather</td></tr></tbody></table><p>The order matters: gas in liquid is foam, whereas liquid in gas is a liquid aerosol. A gas-gas mixture is normally molecularly mixed rather than a separate colloidal dispersed phase, so there is no ninth gas-in-gas colloid row.</p><p><strong>Source qualifications:</strong> these are schematic classifications of complex materials. Only glasses or gemstones whose color comes from a separate dispersed particle phase illustrate solid sols; dissolved color centers alone do not establish a colloid. Butter is more specifically a water-in-fat emulsion supported by a fat-crystal network, rather than a universal simple liquid-in-solid gel. The source's butter entry is retained as its classroom grouping, not used as an unqualified classification in a scored question. Foods, paints and cell fluids can contain more than one dispersed structure.</p>"
    },
    {
      id: "tyndall-brownian-properties",
      title: "Tyndall effect and Brownian movement",
      sources: [{ document: "quick-revision", page: 66 }],
      html: "<p><strong>Tyndall effect, an optical property:</strong> colloidal particles scatter light, making the path of a beam visible from the side. The visible path is due to scattering, not the particles generating their own light. Source exam labels are printed as IOM 2000 and 2064; the latter label is retained as printed without assuming a calendar conversion.</p><p><strong>Brownian movement, a mechanical property:</strong> colloidal particles move in an irregular zigzag path because molecules of the dispersion medium bombard them unevenly. The particles are buffeted by the thermal motion of the surrounding molecules; the visible random motion is not a directed flow caused by an electric field.</p>"
    },
    {
      id: "protective-colloids",
      title: "Protective colloids and the gold-number comparison",
      sources: [{ document: "quick-revision", page: 66 }],
      html: "<p>When a suitable lyophilic sol is added to a lyophobic sol, the lyophilic material forms a solvated protective layer around the lyophobic particles. It thereby helps protect the latter against aggregation or coagulation. The lyophilic material serving this role is called a protective colloid.</p><p>The source's gold-number rule is: smaller gold number means greater protective action. Gold number is an operational measure of the quantity of protective colloid needed in a standardized gold-sol protection test, so a smaller required quantity indicates more effective protection. Compare values measured by the same test; a high gold number is not a sign of stronger protection.</p>"
    },
    {
      id: "catalyst-electroosmosis",
      title: "Nickel catalysis and electro-osmosis",
      sources: [{ document: "quick-revision", page: 66 }],
      html: "<p>The catalyst named for hydrogenation of oil is nickel. Hydrogen is added across unsaturated bonds on a catalytic metal surface; nickel is the source's industrial example. Source exam label: IOM 1993.</p><p>The source calls migration of the dispersion medium under the influence of electric current <strong>electro-osmosis</strong>. More precisely, an applied electric field drives the liquid medium relative to an immobilized charged surface or dispersed phase. It is the medium that moves in this description. Migration of the dispersed particles themselves under an electric field is electrophoresis, a different electrokinetic observation. Source exam labels: IOM 1998 and 2014.</p>"
    }
  ],
  pageCoverage: [
    { document: "quick-revision", page: 66, status: "partial", sectionIds: ["electrochemistry-continuation", "kohlrausch-law-applications", "faraday-equivalent", "adsorption-absorption", "particle-size-comparison", "colloid-types-eight-rows", "tyndall-brownian-properties", "protective-colloids", "catalyst-electroosmosis"], unresolved: ["Top-left 'Does not displace H2: Hg' does not identify the reagent or reaction conditions. The ordinary dilute-nonoxidizing-acid interpretation is explicitly qualified; the source's exact intended test is unspecified.", "Top-left CuSO4 electrolysis constant-density claim does not specify electrode materials or temperature/volume control. A dissolving copper-anode interpretation is explained, but the intended apparatus and conditions cannot be recovered."] }
  ],
  questions: [
    { id: "note-solutions-001", text: "In the ordinary activity-series test with dilute nonoxidizing hydrochloric acid and no oxidant, which listed metal does not liberate hydrogen?", options: [{ key: "a", text: "Magnesium" }, { key: "b", text: "Zinc" }, { key: "c", text: "Mercury" }, { key: "d", text: "Iron" }], answer: "c", explanation: "Mercury lies below hydrogen in the usual activity-series comparison and does not displace hydrogen from this specified nonoxidizing acid. The reagent condition is essential; oxidizing-acid reactions are a different test.", sectionId: "electrochemistry-continuation", source: { document: "quick-revision", page: 66 }, cognitive: "understanding" },
    { id: "note-solutions-002", text: "Why can CuSO<sub>4</sub> concentration remain nearly constant during copper electrolysis with a soluble copper anode, fixed volume and negligible side reactions?", options: [{ key: "a", text: "The cathode releases copper ions as the anode removes them." }, { key: "b", text: "Both electrodes remove identical amounts of copper ions." }, { key: "c", text: "Water decomposition continuously creates new copper ions." }, { key: "d", text: "Anode copper dissolution replaces copper ions deposited at the cathode." }], answer: "d", explanation: "Oxidation of the copper anode supplies Cu2+ to the solution, while cathodic reduction removes Cu2+ as copper metal. Equal charge through the two electrodes balances these copper-ion amounts under the given assumptions.", sectionId: "electrochemistry-continuation", source: { document: "quick-revision", page: 66 }, cognitive: "understanding" },
    { id: "note-solutions-003", text: "Which metal is the common oil-hydrogenation catalyst named in these notes?", options: [{ key: "a", text: "Nickel" }, { key: "b", text: "Iron" }, { key: "c", text: "Copper" }, { key: "d", text: "Zinc" }], answer: "a", explanation: "The source specifically names nickel for catalytic hydrogenation of oil. Its surface facilitates addition of hydrogen to unsaturated bonds; the other listed metals are not the named industrial hydrogenation catalyst.", sectionId: "catalyst-electroosmosis", source: { document: "quick-revision", page: 66 }, cognitive: "recall" },
    { id: "note-solutions-004", text: "For a 1:1 electrolyte, limiting ionic molar conductivities at the same temperature are 50.0 and 76.3 S cm<sup>2</sup> mol<sup>-1</sup>. What is its limiting molar conductivity?", options: [{ key: "a", text: "26.3 S cm<sup>2</sup> mol<sup>-1</sup>" }, { key: "b", text: "126.3 S cm<sup>2</sup> mol<sup>-1</sup>" }, { key: "c", text: "63.15 S cm<sup>2</sup> mol<sup>-1</sup>" }, { key: "d", text: "252.6 S cm<sup>2</sup> mol<sup>-1</sup>" }], answer: "b", explanation: "Kohlrausch's law adds the independent ionic contributions. A 1:1 formula unit supplies one of each ion, so the limiting molar conductivity is 50.0 + 76.3 = 126.3 S cm^2/mol.", sectionId: "kohlrausch-law-applications", source: { document: "quick-revision", page: 66 }, cognitive: "application" },
    { id: "note-solutions-005", text: "A weak electrolyte has molar conductivity 30 S cm<sup>2</sup> mol<sup>-1</sup> and limiting molar conductivity 300 in the same units. If mobility corrections are negligible, what is its approximate degree of ionization?", options: [{ key: "a", text: "0.01, or 1%" }, { key: "b", text: "0.30, or 30%" }, { key: "c", text: "0.90, or 90%" }, { key: "d", text: "0.10, or 10%" }], answer: "d", explanation: "The conductivity estimate is $\\alpha\\approx\\frac{\\Lambda_m}{\\Lambda_m^{\\infty}}=\\frac{30}{300}=0.10$. This is ten percent ionization; the approximation assumes the limiting ionic mobility adequately represents the dissociated ions.", sectionId: "kohlrausch-law-applications", source: { document: "quick-revision", page: 66 }, cognitive: "application" },
    { id: "note-solutions-006", text: "A very dilute saturated salt solution has background-corrected conductivity 1.5 &times; 10<sup>-6</sup> S cm<sup>-1</sup>. Its applicable limiting molar conductivity is 150 S cm<sup>2</sup> mol<sup>-1</sup>. What is its molar solubility?", options: [{ key: "a", text: "$10^{-8}$ mol L<sup>-1</sup>" }, { key: "b", text: "$10^{-5}$ mol L<sup>-1</sup>" }, { key: "c", text: "$10^{-3}$ mol L<sup>-1</sup>" }, { key: "d", text: "$10^{-2}$ mol L<sup>-1</sup>" }], answer: "b", explanation: "Rearrange the molar-conductivity relation: $s=\\frac{1000\\kappa}{\\Lambda_m^{\\infty}}=\\frac{1000\\times1.5\\times10^{-6}}{150}=10^{-5}$ mol/L. The stated background correction and very dilute limit are necessary.", sectionId: "kohlrausch-law-applications", source: { document: "quick-revision", page: 66 }, cognitive: "application" },
    { id: "note-solutions-007", text: "A molten salt deposits a metal from M<sup>3+</sup>. With molar mass 27 g mol<sup>-1</sup> and 100% current efficiency, what mass is deposited by one faraday?", options: [{ key: "a", text: "1 g" }, { key: "b", text: "27 g" }, { key: "c", text: "9 g" }, { key: "d", text: "81 g" }], answer: "c", explanation: "One faraday supplies one mole of electrons. Each M3+ needs three electrons, so the deposit is one-third mole, with mass $\\frac{27}{3}=9$ g. That is one gram-equivalent for this reduction.", sectionId: "faraday-equivalent", source: { document: "quick-revision", page: 66 }, cognitive: "application" },
    { id: "note-solutions-008", text: "A substance becomes concentrated on a solid's surface while its concentration in the bulk remains lower. Which process does this describe?", options: [{ key: "a", text: "Adsorption at an interface" }, { key: "b", text: "Absorption throughout the bulk" }, { key: "c", text: "Uniform molecular diffusion only" }, { key: "d", text: "Complete bulk dissolution only" }], answer: "a", explanation: "Preferential accumulation at an interface is adsorption. Absorption instead refers to uptake into the material's bulk; the words are distinguished by location, not merely by whether the process happens quickly.", sectionId: "adsorption-absorption", source: { document: "quick-revision", page: 66 }, cognitive: "understanding" },
    { id: "note-solutions-009", text: "Which qualification is needed for the source's claim that absorption proceeds at the same rate throughout?", options: [{ key: "a", text: "Its rate can change as concentration gradients and capacity change." }, { key: "b", text: "Its rate must equal adsorption rate whenever both processes occur." }, { key: "c", text: "Its rate is fixed by initial concentration throughout the process." }, { key: "d", text: "Its rate stays constant while a closed system reaches equilibrium." }], answer: "a", explanation: "Absorption is bulk uptake, not a definition of constant-rate kinetics. Transport gradients, saturation and mixing can change over time, so its rate need not remain constant as the source comparison suggests.", sectionId: "adsorption-absorption", source: { document: "quick-revision", page: 66 }, cognitive: "understanding" },
    { id: "note-solutions-010", text: "Using the conventional particle-size ranges in the corrected notes, a dispersion with particles of diameter 50 nm is classified as what?", options: [{ key: "a", text: "A molecular true solution" }, { key: "b", text: "A coarse suspension" }, { key: "c", text: "A colloidal dispersion" }, { key: "d", text: "A gas-gas molecular mixture" }], answer: "c", explanation: "Fifty nanometers lies between the conventional colloid boundaries of approximately 1 and 1000 nm. A true solution has molecular-scale particles below about 1 nm, while coarse suspensions lie above about 1000 nm.", sectionId: "particle-size-comparison", source: { document: "quick-revision", page: 66 }, cognitive: "application" },
    { id: "note-solutions-011", text: "The conventional upper colloid boundary is about 10<sup>-4</sup> cm. What is that length in nanometers?", options: [{ key: "a", text: "1 nm" }, { key: "b", text: "1000 nm" }, { key: "c", text: "10 nm" }, { key: "d", text: "100 nm" }], answer: "b", explanation: "One centimeter equals 10^7 nanometers. Therefore $10^{-4}\\times10^7=10^3$ nm, or 1000 nm. This conversion also shows why the source's suspension cutoff at 10^-7 cm overlaps the colloidal range.", sectionId: "particle-size-comparison", source: { document: "quick-revision", page: 66 }, cognitive: "application" },
    { id: "note-solutions-012", text: "In whipped cream considered as a foam, what are the dispersed phase and continuous medium?", options: [{ key: "a", text: "Liquid dispersed in gas" }, { key: "b", text: "Solid dispersed in liquid" }, { key: "c", text: "Gas dispersed in solid" }, { key: "d", text: "Gas dispersed in liquid" }], answer: "d", explanation: "A foam is a gas dispersed in a liquid continuous medium. The source groups whipped cream with froth and soap lather in this category, distinct from solid foams such as pumice or foam rubber.", sectionId: "colloid-types-eight-rows", source: { document: "quick-revision", page: 66 }, cognitive: "recall" },
    { id: "note-solutions-013", text: "Liquid fat droplets dispersed in a liquid aqueous medium, as in milk's emulsion structure, belong to which type?", options: [{ key: "a", text: "Solid sol" }, { key: "b", text: "Emulsion" }, { key: "c", text: "Solid foam" }, { key: "d", text: "Aerosol" }], answer: "b", explanation: "An emulsion has a liquid dispersed phase in another liquid. This distinguishes the source's milk and hair-cream examples from aerosols, whose continuous medium is a gas, and solid sols or foams.", sectionId: "colloid-types-eight-rows", source: { document: "quick-revision", page: 66 }, cognitive: "understanding" },
    { id: "note-solutions-014", text: "What distinguishes the source's smoke and fog examples when both are dispersed in air?", options: [{ key: "a", text: "Smoke disperses solid particles; fog disperses liquid droplets." }, { key: "b", text: "Smoke disperses liquid droplets; fog disperses solid particles." }, { key: "c", text: "Smoke has a liquid medium; fog has a solid medium." }, { key: "d", text: "Smoke has a solid medium; fog has a liquid medium." }], answer: "a", explanation: "Both examples have gas as the dispersion medium. Smoke contains dispersed solids, while fog contains dispersed liquid droplets, so they are respectively solid and liquid aerosols in the source classification.", sectionId: "colloid-types-eight-rows", source: { document: "quick-revision", page: 66 }, cognitive: "understanding" },
    { id: "note-solutions-015", text: "A colored glass contains discrete solid nanoparticles dispersed within a solid glass matrix. Which source-table category fits this stated structure?", options: [{ key: "a", text: "Emulsion" }, { key: "b", text: "Liquid aerosol" }, { key: "c", text: "Liquid foam" }, { key: "d", text: "Solid sol" }], answer: "d", explanation: "The question explicitly supplies a solid dispersed phase and solid continuous medium, which define a solid sol. Color alone would not establish this structure, since some glass color comes from dissolved ions or other color centers.", sectionId: "colloid-types-eight-rows", source: { document: "quick-revision", page: 66 }, cognitive: "application" },
    { id: "note-solutions-016", text: "Water is held within the solid-like network of a jelly. Which simplified colloid type matches that liquid-in-solid structure?", options: [{ key: "a", text: "Aerosol" }, { key: "b", text: "Foam" }, { key: "c", text: "Gel" }, { key: "d", text: "Solid sol" }], answer: "c", explanation: "The source's simplified gel category describes liquid retained in a solid-like continuous network, with jellies among its examples. A foam instead contains dispersed gas, while an aerosol has a gaseous medium.", sectionId: "colloid-types-eight-rows", source: { document: "quick-revision", page: 66 }, cognitive: "understanding" },
    { id: "note-solutions-017", text: "Which process primarily explains a light beam's visible path through a colloid when viewed from the side?", options: [{ key: "a", text: "Selective absorption by dissolved molecular species" }, { key: "b", text: "Reflection at the smooth outside container walls" }, { key: "c", text: "Fluorescence emission after the medium absorbs light" }, { key: "d", text: "Scattering of light by dispersed colloidal particles" }], answer: "d", explanation: "The Tyndall effect redirects incident light at dispersed particles, making the beam path visible from the side. It does not require fluorescence emission, and reflection at container walls does not explain a visible path within the dispersion.", sectionId: "tyndall-brownian-properties", source: { document: "quick-revision", page: 66 }, cognitive: "understanding" },
    { id: "note-solutions-018", text: "What causes the irregular zigzag Brownian motion of a colloidal particle in a still liquid?", options: [{ key: "a", text: "A constant one-direction force from gravity alone" }, { key: "b", text: "Uneven impacts from thermally moving medium molecules" }, { key: "c", text: "A continuous chemical reaction inside every particle" }, { key: "d", text: "A required externally applied electric field" }], answer: "b", explanation: "Molecules of the dispersion medium bombard the particle from different directions with momentarily unbalanced impulses. Their thermal motion produces the random zigzag motion even without an applied electric field or bulk liquid flow.", sectionId: "tyndall-brownian-properties", source: { document: "quick-revision", page: 66 }, cognitive: "recall" },
    { id: "note-solutions-019", text: "Four protective colloids have gold numbers measured by the same procedure. Which value indicates the greatest protective action?", options: [{ key: "a", text: "0.50" }, { key: "b", text: "0.10" }, { key: "c", text: "0.01" }, { key: "d", text: "1.00" }], answer: "c", explanation: "A smaller gold number means less protective colloid is needed in the standard test. Among these four values, 0.01 is the smallest and therefore indicates the strongest protective action, not the largest numerical value.", sectionId: "protective-colloids", source: { document: "quick-revision", page: 66 }, cognitive: "application" },
    { id: "note-solutions-020", text: "An electric field moves the liquid dispersion medium relative to an immobilized charged phase. What is this process called?", options: [{ key: "a", text: "Electro-osmosis" }, { key: "b", text: "Electrophoresis" }, { key: "c", text: "Brownian movement" }, { key: "d", text: "Tyndall scattering" }], answer: "a", explanation: "Movement of the medium relative to a fixed charged structure under an electric field is electro-osmosis. Electrophoresis concerns movement of dispersed charged particles, while Brownian movement and Tyndall scattering have different causes.", sectionId: "catalyst-electroosmosis", source: { document: "quick-revision", page: 66 }, cognitive: "understanding" }
  ]
};